obj-y += apk_dlna_dms.o
obj-y += apk_dlna_dmp.o
obj-y += apk_dlna_dmr.o
obj-y += apk_dlna_dial.o
obj-y += apk_dlna_woonserver.o
obj-y += apk_dlna_satip.o
obj-y += apk_dlna_rc.o
obj-y += apk_dlna_common.o

# APPKIT v2 local include path
ccflags-y += -I$(OCTOTOP_SRC_DIR)/appkit/local_include

