obj-y					+= param/
obj-y					+= svcmanager/

obj-y += db_main.o

# Additional include path
ccflags-y += -I$(OCTO_DB_DIR)/local_include
ccflags-y += -I$(OCTO_DB_DIR)/param/local_include
ccflags-y += -I$(OCTO_DB_DIR)/svcmanager/local_include
ccflags-y += -I$(OCTO_DB_DIR)/include_plugin

