#
obj-y += tmbslTDA18260/src/
obj-y += tmddTDA18260Shared/src/
obj-y += tmddTDA18260Stream/src/
obj-y += drv_channel_tda18260.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/tmbslTDA18260/inc

HUMAX_EXTRA_CFLAG += -D_TMDD_TDA18260_REGMAP_DEFINED
