############################################################
#     (c)2003-2008 Broadcom Corporation
#
#  This program is the proprietary software of Broadcom Corporation and/or its licensors,
#  and may only be used, duplicated, modified or distributed pursuant to the terms and
#  conditions of a separate, written license agreement executed between you and Broadcom
#  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
#  no license (express or implied), right to use, or waiver of any kind with respect to the
#  Software, and Broadcom expressly reserves all rights in and to the Software and all
#  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
#  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
#  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
#
#  Except as expressly set forth in the Authorized License,
#
#  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
#  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
#  and to use this information only in connection with your use of Broadcom integrated circuit products.
#
#  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
#  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
#  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
#  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
#  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
#  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
#  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
#  USE OR PERFORMANCE OF THE SOFTWARE.
#
#  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
#  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
#  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
#  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
#  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
#  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
#  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
#  ANY LIMITED REMEDY.
#
# $brcm_Workfile: Makefile $
# $brcm_Revision: 8 $
# $brcm_Date: 6/24/10 9:43a $
#
# Module Description:
#
# Revision History:
#
# Created: 08/28/2007 by Jon Garrett
#
# $brcm_Log: /BSEAV/app/thumbnail/Makefile $
# 
# 8   6/24/10 9:43a erickson
# SW3548-2959: clean up Makefile
#
# 7   6/18/10 2:06p erickson
# SW3548-2959: fix Makefile
#
# 6   8/14/09 3:13p erickson
# PR55994: refactor to only use bthumbnail_extractor, not
# bthumbnail_manager and _stream
#
# 5   3/13/09 2:52p vsilyaev
# PR 53225: Adeed NEXUS_BIN_DIR_SUFFIX and NEXUS_BIN_DIR
#
# 4   3/17/08 9:28a erickson
# PR40307: use thumbnail library
#
# 3   3/8/08 5:14a erickson
# PR40307: update
#
# 2   3/7/08 5:34p erickson
# PR40307: update thumbnail demo
#
# 1   3/5/08 2:54p erickson
# PR40307: initual thumbnail app
#
#
############################################################
# Nexus examples

ifdef COMSPEC
# Any DOS environment
NEXUS_TOP := $(shell cd ../../../nexus && cd)
else
NEXUS_TOP := $(shell cd ../../../nexus; pwd)
endif
LIB=$(NEXUS_TOP)/../BSEAV/lib

NEXUS_PLATFORM ?= $(PLATFORM)
ifndef NEXUS_PLATFORM
$(error NEXUS_PLATFORM is not defined)
endif

# include cross-compiler definitions
include $(NEXUS_TOP)/platforms/$(NEXUS_PLATFORM)/build/platform_app.inc

# single app Makefile
APP = thumbnail

ifeq ($(B_REFSW_OS),vxworks)
# VxWorks needs a wrapper function to call main.
OBJS += vxworks_cmd.o
# We like to use .out for loadable objects.
APP := $(APP).out
endif

.PHONY: api

all: $(APP)
$(APP): api

# For linux builds, link to the correct libraries
ifneq ($(findstring linux,$(B_REFSW_OS)),)
LDFLAGS := -lnexus -L${NEXUS_BIN_DIR} -lpthread
endif

# This builds the settop api
api:
	$(MAKE) -C $(NEXUS_TOP)/build

# This cleans nexus and app
clean: clean_app
	$(MAKE) -C $(NEXUS_TOP)/build clean

clean_app:
	$(RM) $(APP) $(OBJS)

# This is the minimum needed to compile and link with Nexus
CFLAGS += $(NEXUS_CFLAGS) $(addprefix -I,$(NEXUS_APP_INCLUDE_PATHS)) $(addprefix -D,$(NEXUS_APP_DEFINES))

# Always build with debug
CFLAGS += -g

# the thumbnail app only uses bthumbnail_extractor.c, not the whole bthumbnail lib.

CFLAGS += -I$(LIB)/media -I$(LIB)/bfile -I$(LIB)/utils -I$(LIB)/thumbnail

OBJS += main.o thumbnail_demo.o thumbnail_stills.o $(LIB)/bfile/bfile_stdio.o $(LIB)/thumbnail/bthumbnail_extractor.o

# remove implicit rule
%: %.c

%.o: %.c
	@echo [Compile... $<]
	$(Q_)$(CC) -c -o $@ $^ $(CFLAGS)

# link app
$(APP): $(OBJS)
	@echo [Link... $<]
	$(Q_)$(CC) -o $@ $(OBJS) $(LDFLAGS)
	$(CP) $@ ${NEXUS_BIN_DIR}

ifeq ($(SYSTEM),vxworks)
# Explicit rule for building vxworks wrapper app
vxworks_cmd.o: vxworks_cmd.c
	@echo [Compile... $<]
	$(Q_)$(CC) -o $@ $< $(CFLAGS) $(LDFLAGS)
endif

install: all
