obj-y += common/
obj-y += pipe/
obj-y += av/
obj-y += si/
obj-y += channel/
obj-y += epg/
obj-y += sys/
obj-y += output/
obj-y += swup/
obj-y += ringbuffer/
obj-y += mediaserver/

obj-$(CONFIG_PROD_DEVICE_MIC) += mic/

obj-$(CONFIG_PROD_DEVICE_FILE_SYSTEM) += fs/

obj-$(CONFIG_MW_MM_PVR) += recorder/
obj-$(CONFIG_MW_MM_PVR) += playback/
obj-$(CONFIG_MW_MM_PVR) += meta/

obj-$(CONFIG_MW_MM_MEDIA) += mp/
obj-$(CONFIG_MW_TELETEXT) += ttx/
obj-y 						+= download/
obj-$(CONFIG_MW_SUBTITLE) += sbtl/
obj-$(CONFIG_MW_CEC) += cec/
obj-$(CONFIG_MW_LOGCAPTURE) += logcapture/
obj-$(CONFIG_MW_MM_TRANSCODING) += transcoder/

obj-y += cas/


