obj-y += nx_prism_menu_system.o
obj-y += nx_prism_menu_sysinfo.o
obj-y += nx_prism_menu_powermanagement.o
obj-y += nx_prism_menu_powertimer.o
obj-y += nx_prism_menu_powertimersettings.o
obj-y += nx_prism_menu_factory_default.o
obj-y += nx_prism_menu_swup_info.o
obj-y += nx_prism_menu_swup_download.o
obj-y += nx_prism_menu_hdmicec.o

# Additional include path
ccflags-y += -I../../../../../../../make/include

