#!/bin/sh

case "$1" in
    start)
		# Create core dump with executable name and process id
		# Ref.: http://www.linuxhowtos.org/Tips%20and%20Tricks/coredump.htm
		echo "core.%e.%p" > /proc/sys/kernel/core_pattern
		# Remove previouse core dump and log files
		rm -f /core* /APPKIT*
		rm -rf /logsck
		# Enable core dump
		ulimit -c unlimited
		export UVA_DRM_LIB_DIR="/usr/browser/drm/"
		# Run PCD
		exec comma &
		exec dfbmaster &
		exec dama &
		exec umma &
		exec thma &
		exec hama &
		;;
    stop)
		if [ "$VERBOSE" != no ]; then
			log_begin_msg "Stopping Application processes"
		fi
		killall obama
		killall corsair
		;;
    *)
		if [ "$VERBOSE" != no ]; then
			log_success_msg "Usage: /etc/init.d/S90settop {start|stop}"
		fi
		exit 1
		;;
esac

