obj-y		+= base/

obj-$(CONFIG_MW_CI)							+= ci/
obj-$(CONFIG_MW_CAS_NAGRA_OP_SES)			+= ses/
obj-$(CONFIG_MW_CAS_NAGRA)					+= nagra/
obj-$(CONFIG_MW_CAS_VERIMATRIX_IPTV)		+= verimatrix/
obj-$(CONFIG_MW_CAS_CONAX)					+= conax/


obj-y		+= xmgr_copyrightcontrol.o
obj-y		+= pmgr_copyrightcontrol.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

