obj-y += pmgr_mheg.o
obj-y += base/

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xport

# Additional include path
ccflags-y += -I$(OCTO_THIRDPARTY_PORT_DIR)/mheg/local_include