obj-y += homapi_dial.o
obj-y += homapi_dms.o
obj-y += homapi_dmp.o
obj-y += homapi_dmr.o
obj-y += homapi_woonserver.o
obj-y += homapi_airplay.o
obj-y += homapi_satip.o
obj-y += homapi_rc.o

#obj-y += apk_dlna_obama.o

# APPKIT v2 local include path
#ccflags-y += -I$(OCTOTOP_SRC_DIR)/appkit/local_include

