/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_int_id_irq0_aon.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 3/18/11 4:04p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Jan 12 11:02:27 2011
 *                 MD5 Checksum         3b961300f134f65c08a03419e4ead007
 *
 * Compiled with:  RDB Utility          unknown
 *                 RDB Parser           3.0
 *                 generate_int_id.pl   1.0
 *                 Perl Interpreter     5.008005
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7552/rdb/a0/bchp_int_id_irq0_aon.h $
 * 
 * Hydra_Software_Devel/1   3/18/11 4:04p xhuang
 * SW7552-2: sync with CRDB
 *
 ***************************************************************************/

#include "bchp.h"
#include "bchp_irq0_aon.h"

#ifndef BCHP_INT_ID_IRQ0_AON_H__
#define BCHP_INT_ID_IRQ0_AON_H__

#define BCHP_INT_ID_IRQ0_AON_gio_irqen        BCHP_INT_ID_CREATE(BCHP_IRQ0_AON_IRQEN, BCHP_IRQ0_AON_IRQEN_gio_irqen_SHIFT)
#define BCHP_INT_ID_icap_irqen                BCHP_INT_ID_CREATE(BCHP_IRQ0_AON_IRQEN, BCHP_IRQ0_AON_IRQEN_icap_irqen_SHIFT)
#define BCHP_INT_ID_iicd_irqen                BCHP_INT_ID_CREATE(BCHP_IRQ0_AON_IRQEN, BCHP_IRQ0_AON_IRQEN_iicd_irqen_SHIFT)
#define BCHP_INT_ID_kbd1_irqen                BCHP_INT_ID_CREATE(BCHP_IRQ0_AON_IRQEN, BCHP_IRQ0_AON_IRQEN_kbd1_irqen_SHIFT)
#define BCHP_INT_ID_kbd2_irqen                BCHP_INT_ID_CREATE(BCHP_IRQ0_AON_IRQEN, BCHP_IRQ0_AON_IRQEN_kbd2_irqen_SHIFT)
#define BCHP_INT_ID_kbd3_irqen                BCHP_INT_ID_CREATE(BCHP_IRQ0_AON_IRQEN, BCHP_IRQ0_AON_IRQEN_kbd3_irqen_SHIFT)
#define BCHP_INT_ID_ldk_irqen                 BCHP_INT_ID_CREATE(BCHP_IRQ0_AON_IRQEN, BCHP_IRQ0_AON_IRQEN_ldk_irqen_SHIFT)
#define BCHP_INT_ID_spi_irqen                 BCHP_INT_ID_CREATE(BCHP_IRQ0_AON_IRQEN, BCHP_IRQ0_AON_IRQEN_spi_irqen_SHIFT)

#endif /* #ifndef BCHP_INT_ID_IRQ0_AON_H__ */

/* End of File */
