-include ./dirs

ifeq ($(DIRS),)
TARGET = wmdrmstub

SOURCES =                \
	drmdevcert.c drmwmdrmexprevalreal.c drmwmdrmexprfuncreal.c drmwmdrmexprvariablereal.c drmwmdrmlicacqrespreal.c drmwmdrmlicchainreal.c drmwmdrmlicenseparserreal.c drmwmdrmlicevalreal.c drmwmdrmoplreal.c drmwmdrmutilreal.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
