obj-y += na_mgr_irdcmd.o
obj-$(CONFIG_MW_CAS_NAGRA_IRDCMD_MAIL) += na_mgr_irdcmd_mail.o
obj-$(CONFIG_MW_CAS_NAGRA_IRDCMD_POPUP) += na_mgr_irdcmd_popup.o

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas


# Additional include path

