obj-y								+= base/
obj-$(CONFIG_PROD_HMS1000S)			+= eu/
obj-$(CONFIG_PROD_HMSLITE)			+= eu/
obj-$(CONFIG_OP_MIDDLE_EAST)		+= mesat/
obj-$(CONFIG_OP_FREESAT)			+= freesat/
obj-$(CONFIG_PROD_HMX4KBBC)			+= hmx4kbbc/
obj-$(CONFIG_PROD_FVP4000T)			+= ukdtt/

obj-y		+= xmgr_time.o
obj-y		+= pmgr_time.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

