obj-y += str_decompress.o
obj-$(CONFIG_MWC_STRING_DECOMPRESS_HUFFMAN_DTG1) += dtg1_huffman_decompress.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw
# Additional include path

