#--------------------------------------------------------------------------------------
# 다음은 operator, 지역 또는 국가의 공통 사양으로 이루어지는 si 들이다.
#--------------------------------------------------------------------------------------

obj-y += xmgr_model_hms1000s.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr

# Additional include path

