obj-$(CONFIG_MW_CAS_NAGRA_TIVU) += xmgr_cas_na_ppv_tivu_carderror.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
ccflags-y += -I$(OCTO_DIR)/oapi/server/include

# Sub-CAS include path


