obj-y += nx_port_db.o
obj-$(CONFIG_PROD_HMS1000S) += nx_port_db_default_hms1000s.o
obj-$(CONFIG_PROD_HDMINI2) += nx_port_db_default_hdmini2.o
obj-$(CONFIG_PROD_IR5000HD) += nx_port_db_default_ir5000hd.o
obj-$(CONFIG_PROD_HA7100S) += nx_port_db_default_ha7100s.o
obj-$(CONFIG_PROD_M1) += nx_port_db_default_m1.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include
ccflags-y += -I$(NATIVEAPP_PORT_INCLUDE_DIR)/include

# Additional include path
