#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"

const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
	/* GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 00   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 01   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 02   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 03   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 04   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 05   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 06   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 07   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 08   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 09   */ /* NC_GPIO */
	
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 10   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 11   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 12   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 13   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 14   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 15   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 16   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 17   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 18   */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 19   */ /* NC_GPIO */

	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 20   */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 21   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 22   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 23   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 24   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 25   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 26   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 27   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 28   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 29   */

	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 30   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 31   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 32   */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 33   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 34   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 35   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 36   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 37   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 38   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 39   */ /* NC_GPIO */

	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 40   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 41   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 42   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 43   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 44   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 45   */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 46   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 47   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 48   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 49   */ /* NC_GPIO */

	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 50   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 51   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 52   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 53   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 54   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 55   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 56   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 57   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 58   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 59   */ /* NC_GPIO */

	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 60   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 61   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 62   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 63   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 64   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 65   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 66   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 67   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 68   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 69   */ /* NC_GPIO */

	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 70   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 71   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 72   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 73   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 74   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 75   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 76   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 77   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 78   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 79   */

	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 80   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 81   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 82   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 83   */

	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 84   */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 85   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 86   */

	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 87   */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 88   */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 89   */ /* NC_GPIO */

	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 90   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 91   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 92   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 93   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 94   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 95   */ /* gpio 95 is dummy */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 96   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 97   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 98   */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 99   */ /* NC_GPIO */

	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 100  */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 101  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 102  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 103  */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 104  */ /* NC_GPIO */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 105  */

	/* SGPIO */
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 00   */
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 01   */

	/* AON GPIO */
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON GPIO 00  */ /* AUD0_SPDIF*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON GPIO 01   */ /*ENET_LINK*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON GPIO 02   */ /* aon gpio 02 is dummy */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON GPIO 03   */ /*KEY_IN_STBY*/
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON GPIO 04   */ /*ANT_PWR_CHK*/
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON GPIO 05   */ /*ANT_PWR_EN*/
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON GPIO 06   */ /*AUD_#MUTE*/
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON GPIO 07   */ /*WARM_#COLD*/
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON GPIO 08   */ /*LED_RED */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON GPIO 09   */ /*LED_GREEN */

	HUMAX_GPIO_FUNCTION_GPIO,	/* AON GPIO 10   */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON GPIO 11   */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON GPIO 12   */ /*S3_DDR_RST*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON GPIO 13   */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON GPIO 14   */
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON GPIO 15   */ /*SPI_SS0b*/
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON GPIO 16   */ /*SPI_CLK*/
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON GPIO 17   */ /*SPI_MOSI*/
	HUMAX_GPIO_FUNCTION_ALT5,	/* AON GPIO 18   */
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON GPIO 19   */ /*SPI_MISO*/

	HUMAX_GPIO_FUNCTION_NCTP,	/* AON GPIO 20   */

	/* AON SGPIO */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON SGPIO 00   */
	HUMAX_GPIO_FUNCTION_GPIO	/* AON SGPIO 01   */
};

HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
	/* GPIO */
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_18_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_18_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_20_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_20_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_23_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_23_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_24_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_24_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_25_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_25_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_26_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_26_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_27_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_27_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_28_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_28_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_29_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_29_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_30_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_30_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_31_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_31_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_32_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_32_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_41_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_41_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_42_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_42_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_43_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_43_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_44_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_44_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_45_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_45_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_79_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_79_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_80_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_80_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_81_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_81_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_82_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_82_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_83_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_83_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_84_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_84_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_85_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_85_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_86_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_86_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_87_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_87_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_88_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_88_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0}, /* gpio 95 is dummy */
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_101_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_101_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_102_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_102_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, 0, 0},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_105_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_105_SHIFT},

	/* SGPIO */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_00_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_01_SHIFT},

	/* AON GPIO */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, 0, 0},    /* aon gpio 02 is dummy */
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT},
    
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT},
    
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_14_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_SHIFT},

	/* AON SGPIO */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_01_SHIFT}
};

