obj-y									+= ui/

obj-y									+= xmgr_cas_vmx.o
obj-y									+= xmgr_cas_vmx_util.o
obj-y									+= xmgr_cas_vmx_parental_control.o


# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

