-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = meteringcreateresponse

DRM_MODULE_CFLAGS =

SOURCES =                \
	meterrespond.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
