obj-y += svc_epg_event.o
obj-y += svc_epg_event_dama.o
obj-y += svc_epg_query.o
obj-y += svc_epg_manager_dama.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw

# Additional include path
