-include ./dirs

ifeq ($(DIRS),)
TARGET = meteringstub

SOURCES =                \
	meteringutilstub.c drmmeterapistub.c drmmetercertstorestub.c drmmeterimpstub.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
