obj-y += sama.o
obj-y += sama_timer.o
obj-y += sama_schedule.o
obj-y += sama_protocol.o
obj-y += sama_resource.o

obj-y += sama_debug.o

obj-y += base/

obj-$(CONFIG_OP_PVR_BASED_ON_TVANYTIME) += tva/

# include path
ccflags-y += -I$(OCTOSVC_SRC_DIR)/sama/main
ccflags-y += -I$(OCTOSVC_SRC_DIR)/sama/lib

