# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

SHELL = /bin/bash

TARGETS = \
    lib   \

include $(PLAYREADY_DIR)/GNUmakefile.common

