obj-y += base/

ifeq ($(CONFIG_DEBUG),y)
obj-y += cmd_xmgr_live.o
endif
obj-y += pmgr_live.o
obj-y += xmgr_live.o
obj-y += xmgr_live_zap.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr

