/*******************************************************************/
/********************      Header Files    *************************/
/*******************************************************************/

/* global header file */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <ctype.h>
#include <mwc_codepage.h>

#include <octo_common.h>

/* local header file */
#include <isosvc.h>

#define		CH_TBL_0X10_TABLE	1
#define		CH_TBL_0X20_DEFAULT_TABLE	2

/*******************************************************************/
/********************      Debug     ********************/
/*******************************************************************/






/*******************************************************************/
/********************      Global Variables     ********************/
/*******************************************************************/

/* combining diacritical  Marks name*/
/* 0 					*/
/* 1 WITH GRAVE 			*/
/* 2 WITH ACUTE 			*/
/* 3 WITH CIRCUMFLEX 		*/
/* 4 WITH TILDE 			*/
/* 5 WITH MACRON 		*/
/* 6 WITH BREVE 			*/
/* 7 WITH DOT ABOVE 		*/
/* 8 WITH DIAERESIS 		*/
/* 9 					*/
/* 10(A) WITH RING ABOVE 	*/
/* 11(B) WITH CEDILLA 		*/
/* 12(C) 					*/
/* 13(D) WITH DOUBLE ACUTE*/
/* 14(E) WITH OGONEK 		*/
/* 15(F) WITH CARON 		*/

#define	NON_SPACING_CHA_NUM	16	// 15+1

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_A[]=
{
	/* 0 					*/	0x0041,	// LATIN CAPITAL LETTER A
	/* 1 WITH GRAVE 			*/	0x00C0,	// LATIN CAPITAL LETTER A WITH GRAVE
	/* 2 WITH ACUTE 			*/	0x00C1,	// LATIN CAPITAL LETTER A WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x00C2,	// LATIN CAPITAL LETTER A WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x00C3,	// LATIN CAPITAL LETTER A WITH TILDE
	/* 5 WITH MACRON 		*/	0x0100,	// LATIN CAPITAL LETTER A WITH MACRON
	/* 6 WITH BREVE 			*/	0x0102,	// LATIN CAPITAL LETTER A WITH BREVE
	/* 7 WITH DOT ABOVE 		*/	0x0041,	// LATIN CAPITAL LETTER A
	/* 8 WITH DIAERESIS 		*/	0x00C4,	// LATIN CAPITAL LETTER A WITH DIAERESIS
	/* 9 					*/	0x0041,	// LATIN CAPITAL LETTER A
	/* 10(A) WITH RING ABOVE 	*/	0x00C5,	// LATIN CAPITAL LETTER A WITH RING ABOVE
	/* 11(B) WITH CEDILLA 		*/	0x0041,	// LATIN CAPITAL LETTER A
	/* 12(C) 					*/	0x0041,	// LATIN CAPITAL LETTER A
	/* 13(D) WITH DOUBLE ACUTE*/	0x0041,	// LATIN CAPITAL LETTER A
	/* 14(E) WITH OGONEK 		*/	0x0041,	// LATIN CAPITAL LETTER A
	/* 15(F) WITH CARON 		*/	0x0041,	// LATIN CAPITAL LETTER A
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_B[]=
{
	/* 0 					*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 1 WITH GRAVE 			*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 2 WITH ACUTE 			*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 3 WITH CIRCUMFLEX 		*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 4 WITH TILDE 			*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 5 WITH MACRON 		*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 6 WITH BREVE 			*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 7 WITH DOT ABOVE 		*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 8 WITH DIAERESIS 		*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 9 					*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 10(A) WITH RING ABOVE 	*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 11(B) WITH CEDILLA 		*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 12(C) 					*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 13(D) WITH DOUBLE ACUTE*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 14(E) WITH OGONEK 		*/	0x0042,	// LATIN CAPITAL LETTER B
	/* 15(F) WITH CARON 		*/	0x0042,	// LATIN CAPITAL LETTER B
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_C[]=
{
	/* 0 					*/	0x0043,	// LATIN CAPITAL LETTER C
	/* 1 WITH GRAVE 			*/	0x0043,	// LATIN CAPITAL LETTER C
	/* 2 WITH ACUTE 			*/	0x0106,	// LATIN CAPITAL LETTER C WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x0108,	// LATIN CAPITAL LETTER C WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0043,	// LATIN CAPITAL LETTER C
	/* 5 WITH MACRON 		*/	0x0043,	// LATIN CAPITAL LETTER C
	/* 6 WITH BREVE 			*/	0x0043,	// LATIN CAPITAL LETTER C
	/* 7 WITH DOT ABOVE 		*/	0x010A,	// LATIN CAPITAL LETTER C WITH DOT ABOVE
	/* 8 WITH DIAERESIS 		*/	0x0043,	// LATIN CAPITAL LETTER C
	/* 9 					*/	0x0043,	// LATIN CAPITAL LETTER C
	/* 10(A) WITH RING ABOVE 	*/	0x0043,	// LATIN CAPITAL LETTER C
	/* 11(B) WITH CEDILLA 		*/	0x00C7,	// LATIN CAPITAL LETTER C WITH CEDILLA
	/* 12(C) 					*/	0x0043,	// LATIN CAPITAL LETTER C
	/* 13(D) WITH DOUBLE ACUTE*/	0x0043,	// LATIN CAPITAL LETTER C
	/* 14(E) WITH OGONEK 		*/	0x0043,	// LATIN CAPITAL LETTER C
	/* 15(F) WITH CARON 		*/	0x010C,	// LATIN CAPITAL LETTER C WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_D[]=
{
	/* 0 					*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 1 WITH GRAVE 			*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 2 WITH ACUTE 			*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 3 WITH CIRCUMFLEX 		*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 4 WITH TILDE 			*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 5 WITH MACRON 		*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 6 WITH BREVE 			*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 7 WITH DOT ABOVE 		*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 8 WITH DIAERESIS 		*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 9 					*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 10(A) WITH RING ABOVE 	*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 11(B) WITH CEDILLA 		*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 12(C) 					*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 13(D) WITH DOUBLE ACUTE*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 14(E) WITH OGONEK 		*/	0x0044,	// LATIN CAPITAL LETTER D
	/* 15(F) WITH CARON 		*/	0x010E,	// LATIN CAPITAL LETTER D WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_E[]=
{
	/* 0 					*/	0x0045,	// LATIN CAPITAL LETTER E
	/* 1 WITH GRAVE 			*/	0x00C8,	// LATIN CAPITAL LETTER E WITH GRAVE
	/* 2 WITH ACUTE 			*/	0x00C9,	// LATIN CAPITAL LETTER E WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x00CA,	// LATIN CAPITAL LETTER E WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0045,	// LATIN CAPITAL LETTER E
	/* 5 WITH MACRON 		*/	0x0112,	// LATIN CAPITAL LETTER E WITH MACRON
	/* 6 WITH BREVE 			*/	0x0045,	// LATIN CAPITAL LETTER E
	/* 7 WITH DOT ABOVE 		*/	0x0116,	// LATIN CAPITAL LETTER E WITH DOT ABOVE
	/* 8 WITH DIAERESIS 		*/	0x00CB,	// LATIN CAPITAL LETTER E WITH DIAERESIS
	/* 9 					*/	0x0045,	// LATIN CAPITAL LETTER E
	/* 10(A) WITH RING ABOVE 	*/	0x0045,	// LATIN CAPITAL LETTER E
	/* 11(B) WITH CEDILLA 		*/	0x0045,	// LATIN CAPITAL LETTER E
	/* 12(C) 					*/	0x0045,	// LATIN CAPITAL LETTER E
	/* 13(D) WITH DOUBLE ACUTE*/	0x0045,	// LATIN CAPITAL LETTER E
	/* 14(E) WITH OGONEK 		*/	0x0118,	// LATIN CAPITAL LETTER E WITH OGONEK
	/* 15(F) WITH CARON 		*/	0x011A,	// LATIN CAPITAL LETTER E WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_F[]=
{
	/* 0 					*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 1 WITH GRAVE 			*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 2 WITH ACUTE 			*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 3 WITH CIRCUMFLEX 		*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 4 WITH TILDE 			*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 5 WITH MACRON 		*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 6 WITH BREVE 			*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 7 WITH DOT ABOVE 		*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 8 WITH DIAERESIS 		*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 9 					*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 10(A) WITH RING ABOVE 	*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 11(B) WITH CEDILLA 		*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 12(C) 					*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 13(D) WITH DOUBLE ACUTE*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 14(E) WITH OGONEK 		*/	0x0046,	// LATIN CAPITAL LETTER F
	/* 15(F) WITH CARON 		*/	0x0046,	// LATIN CAPITAL LETTER F
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_G[]=
{
	/* 0 					*/	0x0047,	// LATIN CAPITAL LETTER G
	/* 1 WITH GRAVE 			*/	0x0047,	// LATIN CAPITAL LETTER G
	/* 2 WITH ACUTE 			*/	0x0047,	// LATIN CAPITAL LETTER G
	/* 3 WITH CIRCUMFLEX 		*/	0x011C,	// LATIN CAPITAL LETTER G WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0047,	// LATIN CAPITAL LETTER G
	/* 5 WITH MACRON 		*/	0x0047,	// LATIN CAPITAL LETTER G
	/* 6 WITH BREVE 			*/	0x011E,	// LATIN CAPITAL LETTER G WITH BREVE
	/* 7 WITH DOT ABOVE 		*/	0x0120,	// LATIN CAPITAL LETTER G WITH DOT ABOVE
	/* 8 WITH DIAERESIS 		*/	0x0047,	// LATIN CAPITAL LETTER G
	/* 9 					*/	0x0047,	// LATIN CAPITAL LETTER G
	/* 10(A) WITH RING ABOVE 	*/	0x0047,	// LATIN CAPITAL LETTER G
	/* 11(B) WITH CEDILLA 		*/	0x0122,	// LATIN CAPITAL LETTER G WITH CEDILLA
	/* 12(C) 					*/	0x0047,	// LATIN CAPITAL LETTER G
	/* 13(D) WITH DOUBLE ACUTE*/	0x0047,	// LATIN CAPITAL LETTER G
	/* 14(E) WITH OGONEK 		*/	0x0047,	// LATIN CAPITAL LETTER G
	/* 15(F) WITH CARON 		*/	0x0047,	// LATIN CAPITAL LETTER G
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_H[]=
{
	/* 0 					*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 1 WITH GRAVE 			*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 2 WITH ACUTE 			*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 3 WITH CIRCUMFLEX 		*/	0x0124,	// LATIN CAPITAL LETTER H WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 5 WITH MACRON 		*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 6 WITH BREVE 			*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 7 WITH DOT ABOVE 		*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 8 WITH DIAERESIS 		*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 9 					*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 10(A) WITH RING ABOVE 	*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 11(B) WITH CEDILLA 		*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 12(C) 					*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 13(D) WITH DOUBLE ACUTE*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 14(E) WITH OGONEK 		*/	0x0048,	// LATIN CAPITAL LETTER H
	/* 15(F) WITH CARON 		*/	0x0048,	// LATIN CAPITAL LETTER H
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_I[]=
{
	/* 0 					*/	0x0049,	// LATIN CAPITAL LETTER I
	/* 1 WITH GRAVE 			*/	0x00CC,	// LATIN CAPITAL LETTER I WITH GRAVE
	/* 2 WITH ACUTE 			*/	0x00CD,	// LATIN CAPITAL LETTER I WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x00CE,	// LATIN CAPITAL LETTER I WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0128,	// LATIN CAPITAL LETTER I WITH TILDE
	/* 5 WITH MACRON 		*/	0x012A,	// LATIN CAPITAL LETTER I WITH MACRON
	/* 6 WITH BREVE 			*/	0x0049,	// LATIN CAPITAL LETTER I
	/* 7 WITH DOT ABOVE 		*/	0x0130,	// LATIN CAPITAL LETTER I WITH DOT ABOVE
	/* 8 WITH DIAERESIS 		*/	0x00CF,	// LATIN CAPITAL LETTER I WITH DIAERESIS
	/* 9 					*/	0x0049,	// LATIN CAPITAL LETTER I
	/* 10(A) WITH RING ABOVE 	*/	0x0049,	// LATIN CAPITAL LETTER I
	/* 11(B) WITH CEDILLA 		*/	0x0049,	// LATIN CAPITAL LETTER I
	/* 12(C) 					*/	0x0049,	// LATIN CAPITAL LETTER I
	/* 13(D) WITH DOUBLE ACUTE*/	0x0049,	// LATIN CAPITAL LETTER I
	/* 14(E) WITH OGONEK 		*/	0x012E,	// LATIN CAPITAL LETTER I WITH OGONEK
	/* 15(F) WITH CARON 		*/	0x0049,	// LATIN CAPITAL LETTER I
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_J[]=
{
	/* 0 					*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 1 WITH GRAVE 			*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 2 WITH ACUTE 			*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 3 WITH CIRCUMFLEX 		*/	0x0134,	// LATIN CAPITAL LETTER J WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 5 WITH MACRON 		*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 6 WITH BREVE 			*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 7 WITH DOT ABOVE 		*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 8 WITH DIAERESIS 		*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 9 					*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 10(A) WITH RING ABOVE 	*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 11(B) WITH CEDILLA 		*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 12(C) 					*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 13(D) WITH DOUBLE ACUTE*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 14(E) WITH OGONEK 		*/	0x004A,	// LATIN CAPITAL LETTER J
	/* 15(F) WITH CARON 		*/	0x004A,	// LATIN CAPITAL LETTER J
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_K[]=
{
	/* 0 					*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 1 WITH GRAVE 			*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 2 WITH ACUTE 			*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 3 WITH CIRCUMFLEX 		*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 4 WITH TILDE 			*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 5 WITH MACRON 		*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 6 WITH BREVE 			*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 7 WITH DOT ABOVE 		*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 8 WITH DIAERESIS 		*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 9 					*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 10(A) WITH RING ABOVE 	*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 11(B) WITH CEDILLA 		*/	0x0136,	// LATIN CAPITAL LETTER K WITH CEDILLA
	/* 12(C) 					*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 13(D) WITH DOUBLE ACUTE*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 14(E) WITH OGONEK 		*/	0x004B,	// LATIN CAPITAL LETTER K
	/* 15(F) WITH CARON 		*/	0x004B,	// LATIN CAPITAL LETTER K
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_L[]=
{
	/* 0 					*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 1 WITH GRAVE 			*/	0x0139,	// LATIN CAPITAL LETTER L WITH ACUTE
	/* 2 WITH ACUTE 			*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 3 WITH CIRCUMFLEX 		*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 4 WITH TILDE 			*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 5 WITH MACRON 		*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 6 WITH BREVE 			*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 7 WITH DOT ABOVE 		*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 8 WITH DIAERESIS 		*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 9 					*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 10(A) WITH RING ABOVE 	*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 11(B) WITH CEDILLA 		*/	0x013B,	// LATIN CAPITAL LETTER L WITH CEDILLA
	/* 12(C) 					*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 13(D) WITH DOUBLE ACUTE*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 14(E) WITH OGONEK 		*/	0x004C,	// LATIN CAPITAL LETTER L
	/* 15(F) WITH CARON 		*/	0x013D,	// LATIN CAPITAL LETTER L WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_M[]=
{
	/* 0 					*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 1 WITH GRAVE 			*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 2 WITH ACUTE 			*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 3 WITH CIRCUMFLEX 		*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 4 WITH TILDE 			*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 5 WITH MACRON 		*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 6 WITH BREVE 			*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 7 WITH DOT ABOVE 		*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 8 WITH DIAERESIS 		*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 9 					*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 10(A) WITH RING ABOVE 	*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 11(B) WITH CEDILLA 		*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 12(C) 					*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 13(D) WITH DOUBLE ACUTE*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 14(E) WITH OGONEK 		*/	0x004D,	// LATIN CAPITAL LETTER M
	/* 15(F) WITH CARON 		*/	0x004D,	// LATIN CAPITAL LETTER M
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_N[]=
{
	/* 0 					*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 1 WITH GRAVE 			*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 2 WITH ACUTE 			*/	0x0143,	// LATIN CAPITAL LETTER N WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 4 WITH TILDE 			*/	0x00D1,	// LATIN CAPITAL LETTER N WITH TILDE
	/* 5 WITH MACRON 		*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 6 WITH BREVE 			*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 7 WITH DOT ABOVE 		*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 8 WITH DIAERESIS 		*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 9 					*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 10(A) WITH RING ABOVE 	*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 11(B) WITH CEDILLA 		*/	0x0145,	// LATIN CAPITAL LETTER N WITH CEDILLA
	/* 12(C) 					*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 13(D) WITH DOUBLE ACUTE*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 14(E) WITH OGONEK 		*/	0x004E,	// LATIN CAPITAL LETTER N
	/* 15(F) WITH CARON 		*/	0x0147,	// LATIN CAPITAL LETTER N WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_O[]=
{
	/* 0 					*/	0x004F,	// LATIN CAPITAL LETTER O
	/* 1 WITH GRAVE 			*/	0x00D2,	// LATIN CAPITAL LETTER O WITH GRAVE
	/* 2 WITH ACUTE 			*/	0x00D3,	// LATIN CAPITAL LETTER O WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x00D4,	// LATIN CAPITAL LETTER O WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x00D5,	// LATIN CAPITAL LETTER O WITH TILDE
	/* 5 WITH MACRON 		*/	0x014C,	// LATIN CAPITAL LETTER O WITH MACRON
	/* 6 WITH BREVE 			*/	0x004F,	// LATIN CAPITAL LETTER O
	/* 7 WITH DOT ABOVE 		*/	0x004F,	// LATIN CAPITAL LETTER O
	/* 8 WITH DIAERESIS 		*/	0x00D6,	// LATIN CAPITAL LETTER O WITH DIAERESIS
	/* 9 					*/	0x004F,	// LATIN CAPITAL LETTER O
	/* 10(A) WITH RING ABOVE 	*/	0x004F,	// LATIN CAPITAL LETTER O
	/* 11(B) WITH CEDILLA 		*/	0x004F,	// LATIN CAPITAL LETTER O
	/* 12(C) 					*/	0x004F,	// LATIN CAPITAL LETTER O
	/* 13(D) WITH DOUBLE ACUTE*/	0x0150,	// LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
	/* 14(E) WITH OGONEK 		*/	0x004F,	// LATIN CAPITAL LETTER O
	/* 15(F) WITH CARON 		*/	0x004F,	// LATIN CAPITAL LETTER O
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_P[]=
{
	/* 0 					*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 1 WITH GRAVE 			*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 2 WITH ACUTE 			*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 3 WITH CIRCUMFLEX 		*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 4 WITH TILDE 			*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 5 WITH MACRON 		*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 6 WITH BREVE 			*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 7 WITH DOT ABOVE 		*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 8 WITH DIAERESIS 		*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 9 					*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 10(A) WITH RING ABOVE 	*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 11(B) WITH CEDILLA 		*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 12(C) 					*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 13(D) WITH DOUBLE ACUTE*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 14(E) WITH OGONEK 		*/	0x0050,	// LATIN CAPITAL LETTER P
	/* 15(F) WITH CARON 		*/	0x0050,	// LATIN CAPITAL LETTER P
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_Q[]=
{
	/* 0 					*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 1 WITH GRAVE 			*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 2 WITH ACUTE 			*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 3 WITH CIRCUMFLEX 		*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 4 WITH TILDE 			*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 5 WITH MACRON 		*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 6 WITH BREVE 			*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 7 WITH DOT ABOVE 		*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 8 WITH DIAERESIS 		*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 9 					*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 10(A) WITH RING ABOVE 	*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 11(B) WITH CEDILLA 		*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 12(C) 					*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 13(D) WITH DOUBLE ACUTE*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 14(E) WITH OGONEK 		*/	0x0051,	// LATIN CAPITAL LETTER Q
	/* 15(F) WITH CARON 		*/	0x0051,	// LATIN CAPITAL LETTER Q
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_R[]=
{
	/* 0 					*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 1 WITH GRAVE 			*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 2 WITH ACUTE 			*/	0x0154,	// LATIN CAPITAL LETTER R WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 4 WITH TILDE 			*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 5 WITH MACRON 		*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 6 WITH BREVE 			*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 7 WITH DOT ABOVE 		*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 8 WITH DIAERESIS 		*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 9 					*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 10(A) WITH RING ABOVE 	*/	0x0156,	// LATIN CAPITAL LETTER R WITH CEDILLA
	/* 11(B) WITH CEDILLA 		*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 12(C) 					*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 13(D) WITH DOUBLE ACUTE*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 14(E) WITH OGONEK 		*/	0x0052,	// LATIN CAPITAL LETTER R
	/* 15(F) WITH CARON 		*/	0x0158,	// LATIN CAPITAL LETTER R WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_S[]=
{
	/* 0 					*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 1 WITH GRAVE 			*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 2 WITH ACUTE 			*/	0x015A,	// LATIN CAPITAL LETTER S WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x015C,	// LATIN CAPITAL LETTER S WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 5 WITH MACRON 		*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 6 WITH BREVE 			*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 7 WITH DOT ABOVE 		*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 8 WITH DIAERESIS 		*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 9 					*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 10(A) WITH RING ABOVE 	*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 11(B) WITH CEDILLA 		*/	0x015E,	// LATIN CAPITAL LETTER S WITH CEDILLA
	/* 12(C) 					*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 13(D) WITH DOUBLE ACUTE*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 14(E) WITH OGONEK 		*/	0x0053,	// LATIN CAPITAL LETTER S
	/* 15(F) WITH CARON 		*/	0x0160,	// LATIN CAPITAL LETTER S WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_T[]=
{
	/* 0 					*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 1 WITH GRAVE 			*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 2 WITH ACUTE 			*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 3 WITH CIRCUMFLEX 		*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 4 WITH TILDE 			*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 5 WITH MACRON 		*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 6 WITH BREVE 			*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 7 WITH DOT ABOVE 		*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 8 WITH DIAERESIS 		*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 9 					*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 10(A) WITH RING ABOVE 	*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 11(B) WITH CEDILLA 		*/	0x0162,	// LATIN CAPITAL LETTER T WITH CEDILLA
	/* 12(C) 					*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 13(D) WITH DOUBLE ACUTE*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 14(E) WITH OGONEK 		*/	0x0054,	// LATIN CAPITAL LETTER T
	/* 15(F) WITH CARON 		*/	0x0164,	// LATIN CAPITAL LETTER T WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_U[]=
{
	/* 0 					*/	0x0055,	// LATIN CAPITAL LETTER U
	/* 1 WITH GRAVE 			*/	0x00D9,	// LATIN CAPITAL LETTER U WITH GRAVE
	/* 2 WITH ACUTE 			*/	0x00DA,	// LATIN CAPITAL LETTER U WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x00DB,	// LATIN CAPITAL LETTER U WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0168,	// LATIN CAPITAL LETTER U WITH TILDE
	/* 5 WITH MACRON 		*/	0x016A,	// LATIN CAPITAL LETTER U WITH MACRON
	/* 6 WITH BREVE 			*/	0x016C,	// LATIN CAPITAL LETTER U WITH BREVE
	/* 7 WITH DOT ABOVE 		*/	0x0055,	// LATIN CAPITAL LETTER U
	/* 8 WITH DIAERESIS 		*/	0x00DC,	// LATIN CAPITAL LETTER U WITH DIAERESIS
	/* 9 					*/	0x0055,	// LATIN CAPITAL LETTER U
	/* 10(A) WITH RING ABOVE 	*/	0x016E,	// LATIN CAPITAL LETTER U WITH RING ABOVE
	/* 11(B) WITH CEDILLA 		*/	0x0055,	// LATIN CAPITAL LETTER U
	/* 12(C) 					*/	0x0055,	// LATIN CAPITAL LETTER U
	/* 13(D) WITH DOUBLE ACUTE*/	0x0170,	// LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
	/* 14(E) WITH OGONEK 		*/	0x0172,	// LATIN CAPITAL LETTER U WITH OGONEK
	/* 15(F) WITH CARON 		*/	0x0055,	// LATIN CAPITAL LETTER U
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_V[]=
{
	/* 0 					*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 1 WITH GRAVE 			*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 2 WITH ACUTE 			*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 3 WITH CIRCUMFLEX 		*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 4 WITH TILDE 			*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 5 WITH MACRON 		*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 6 WITH BREVE 			*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 7 WITH DOT ABOVE 		*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 8 WITH DIAERESIS 		*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 9 					*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 10(A) WITH RING ABOVE 	*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 11(B) WITH CEDILLA 		*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 12(C) 					*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 13(D) WITH DOUBLE ACUTE*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 14(E) WITH OGONEK 		*/	0x0056,	// LATIN CAPITAL LETTER V
	/* 15(F) WITH CARON 		*/	0x0056,	// LATIN CAPITAL LETTER V
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_W[]=
{
	/* 0 					*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 1 WITH GRAVE 			*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 2 WITH ACUTE 			*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 3 WITH CIRCUMFLEX 		*/	0x0174,	// LATIN CAPITAL LETTER W WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 5 WITH MACRON 		*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 6 WITH BREVE 			*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 7 WITH DOT ABOVE 		*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 8 WITH DIAERESIS 		*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 9 					*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 10(A) WITH RING ABOVE 	*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 11(B) WITH CEDILLA 		*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 12(C) 					*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 13(D) WITH DOUBLE ACUTE*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 14(E) WITH OGONEK 		*/	0x0057,	// LATIN CAPITAL LETTER W
	/* 15(F) WITH CARON 		*/	0x0057,	// LATIN CAPITAL LETTER W
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_X[]=
{
	/* 0 					*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 1 WITH GRAVE 			*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 2 WITH ACUTE 			*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 3 WITH CIRCUMFLEX 		*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 4 WITH TILDE 			*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 5 WITH MACRON 		*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 6 WITH BREVE 			*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 7 WITH DOT ABOVE 		*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 8 WITH DIAERESIS 		*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 9 					*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 10(A) WITH RING ABOVE 	*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 11(B) WITH CEDILLA 		*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 12(C) 					*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 13(D) WITH DOUBLE ACUTE*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 14(E) WITH OGONEK 		*/	0x0058,	// LATIN CAPITAL LETTER X
	/* 15(F) WITH CARON 		*/	0x0058,	// LATIN CAPITAL LETTER X
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_Y[]=
{
	/* 0 					*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 1 WITH GRAVE 			*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 2 WITH ACUTE 			*/	0x00DD,	// LATIN CAPITAL LETTER Y WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x0176,	// LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 5 WITH MACRON 		*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 6 WITH BREVE 			*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 7 WITH DOT ABOVE 		*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 8 WITH DIAERESIS 		*/	0x0178,	// LATIN CAPITAL LETTER Y WITH DIAERESIS
	/* 9 					*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 10(A) WITH RING ABOVE 	*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 11(B) WITH CEDILLA 		*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 12(C) 					*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 13(D) WITH DOUBLE ACUTE*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 14(E) WITH OGONEK 		*/	0x0059,	// LATIN CAPITAL LETTER Y
	/* 15(F) WITH CARON 		*/	0x0059,	// LATIN CAPITAL LETTER Y
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_Z[]=
{
	/* 0 					*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 1 WITH GRAVE 			*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 2 WITH ACUTE 			*/	0x0179,	// LATIN CAPITAL LETTER Z WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 4 WITH TILDE 			*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 5 WITH MACRON 		*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 6 WITH BREVE 			*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 7 WITH DOT ABOVE 		*/	0x017B,	// LATIN CAPITAL LETTER Z WITH DOT ABOVE
	/* 8 WITH DIAERESIS 		*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 9 					*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 10(A) WITH RING ABOVE 	*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 11(B) WITH CEDILLA 		*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 12(C) 					*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 13(D) WITH DOUBLE ACUTE*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 14(E) WITH OGONEK 		*/	0x005A,	// LATIN CAPITAL LETTER Z
	/* 15(F) WITH CARON 		*/	0x017D,	// LATIN CAPITAL LETTER Z WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_A[]=
{
	/* 0 					*/	0x0061,	// LATIN SMALL LETTER A
	/* 1 WITH GRAVE 			*/	0x00E0,	// LATIN SMALL LETTER A WITH GRAVE
	/* 2 WITH ACUTE 			*/	0x00E1,	// LATIN SMALL LETTER A WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x00E2,	// LATIN SMALL LETTER A WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x00E3,	// LATIN SMALL LETTER A WITH TILDE
	/* 5 WITH MACRON 		*/	0x0101,	// LATIN SMALL LETTER A WITH MACRON
	/* 6 WITH BREVE 			*/	0x0103,	// LATIN SMALL LETTER A WITH BREVE
	/* 7 WITH DOT ABOVE 		*/	0x0061,	// LATIN SMALL LETTER A
	/* 8 WITH DIAERESIS 		*/	0x00E4,	// LATIN SMALL LETTER A WITH DIAERESIS
	/* 9 					*/	0x0061,	// LATIN SMALL LETTER A
	/* 10(A) WITH RING ABOVE 	*/	0x00E5,	// LATIN SMALL LETTER A WITH RING ABOVE
	/* 11(B) WITH CEDILLA 		*/	0x0061,	// LATIN SMALL LETTER A
	/* 12(C) 					*/	0x0061,	// LATIN SMALL LETTER A
	/* 13(D) WITH DOUBLE ACUTE*/	0x0061,	// LATIN SMALL LETTER A
	/* 14(E) WITH OGONEK 		*/	0x0105,	// LATIN SMALL LETTER A WITH OGONEK
	/* 15(F) WITH CARON 		*/	0x0061,	// LATIN SMALL LETTER A
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_B[]=
{
	/* 0 					*/	0x0062,	// LATIN SMALL LETTER B
	/* 1 WITH GRAVE 			*/	0x0062,	// LATIN SMALL LETTER B
	/* 2 WITH ACUTE 			*/	0x0062,	// LATIN SMALL LETTER B
	/* 3 WITH CIRCUMFLEX 		*/	0x0062,	// LATIN SMALL LETTER B
	/* 4 WITH TILDE 			*/	0x0062,	// LATIN SMALL LETTER B
	/* 5 WITH MACRON 		*/	0x0062,	// LATIN SMALL LETTER B
	/* 6 WITH BREVE 			*/	0x0062,	// LATIN SMALL LETTER B
	/* 7 WITH DOT ABOVE 		*/	0x0062,	// LATIN SMALL LETTER B
	/* 8 WITH DIAERESIS 		*/	0x0062,	// LATIN SMALL LETTER B
	/* 9 					*/	0x0062,	// LATIN SMALL LETTER B
	/* 10(A) WITH RING ABOVE 	*/	0x0062,	// LATIN SMALL LETTER B
	/* 11(B) WITH CEDILLA 		*/	0x0062,	// LATIN SMALL LETTER B
	/* 12(C) 					*/	0x0062,	// LATIN SMALL LETTER B
	/* 13(D) WITH DOUBLE ACUTE*/	0x0062,	// LATIN SMALL LETTER B
	/* 14(E) WITH OGONEK 		*/	0x0062,	// LATIN SMALL LETTER B
	/* 15(F) WITH CARON 		*/	0x0062,	// LATIN SMALL LETTER B
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_C[]=
{
	/* 0 					*/	0x0063,	// LATIN SMALL LETTER C
	/* 1 WITH GRAVE 			*/	0x0063,	// LATIN SMALL LETTER C
	/* 2 WITH ACUTE 			*/	0x0107,	// LATIN SMALL LETTER C WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x0109,	// LATIN SMALL LETTER C WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0063,	// LATIN SMALL LETTER C
	/* 5 WITH MACRON 		*/	0x0063,	// LATIN SMALL LETTER C
	/* 6 WITH BREVE 			*/	0x0063,	// LATIN SMALL LETTER C
	/* 7 WITH DOT ABOVE 		*/	0x010B,	// LATIN SMALL LETTER C WITH DOT ABOVE
	/* 8 WITH DIAERESIS 		*/	0x0063,	// LATIN SMALL LETTER C
	/* 9 					*/	0x0063,	// LATIN SMALL LETTER C
	/* 10(A) WITH RING ABOVE 	*/	0x0063,	// LATIN SMALL LETTER C
	/* 11(B) WITH CEDILLA 		*/	0x00E7,	// LATIN SMALL LETTER C WITH CEDILLA
	/* 12(C) 					*/	0x0063,	// LATIN SMALL LETTER C
	/* 13(D) WITH DOUBLE ACUTE*/	0x0063,	// LATIN SMALL LETTER C
	/* 14(E) WITH OGONEK 		*/	0x0063,	// LATIN SMALL LETTER C
	/* 15(F) WITH CARON 		*/	0x010D,	// LATIN SMALL LETTER C WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_D[]=
{
	/* 0 					*/	0x0064,	// LATIN SMALL LETTER D
	/* 1 WITH GRAVE 			*/	0x0064,	// LATIN SMALL LETTER D
	/* 2 WITH ACUTE 			*/	0x0064,	// LATIN SMALL LETTER D
	/* 3 WITH CIRCUMFLEX 		*/	0x0064,	// LATIN SMALL LETTER D
	/* 4 WITH TILDE 			*/	0x0064,	// LATIN SMALL LETTER D
	/* 5 WITH MACRON 		*/	0x0064,	// LATIN SMALL LETTER D
	/* 6 WITH BREVE 			*/	0x0064,	// LATIN SMALL LETTER D
	/* 7 WITH DOT ABOVE 		*/	0x0064,	// LATIN SMALL LETTER D
	/* 8 WITH DIAERESIS 		*/	0x0064,	// LATIN SMALL LETTER D
	/* 9 					*/	0x0064,	// LATIN SMALL LETTER D
	/* 10(A) WITH RING ABOVE 	*/	0x0064,	// LATIN SMALL LETTER D
	/* 11(B) WITH CEDILLA 		*/	0x0064,	// LATIN SMALL LETTER D
	/* 12(C) 					*/	0x0064,	// LATIN SMALL LETTER D
	/* 13(D) WITH DOUBLE ACUTE*/	0x0064,	// LATIN SMALL LETTER D
	/* 14(E) WITH OGONEK 		*/	0x0064,	// LATIN SMALL LETTER D
	/* 15(F) WITH CARON 		*/	0x010F,	// LATIN SMALL LETTER D WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_E[]=
{
	/* 0 					*/	0x0065,	// LATIN SMALL LETTER E
	/* 1 WITH GRAVE 			*/	0x00E8,	// LATIN SMALL LETTER E WITH GRAVE
	/* 2 WITH ACUTE 			*/	0x00E9,	// LATIN SMALL LETTER E WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x00EA,	// LATIN SMALL LETTER E WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0065,	// LATIN SMALL LETTER E
	/* 5 WITH MACRON 		*/	0x0113,	// LATIN SMALL LETTER E WITH MACRON
	/* 6 WITH BREVE 			*/	0x0065,	// LATIN SMALL LETTER E
	/* 7 WITH DOT ABOVE 		*/	0x0117,	// LATIN SMALL LETTER E WITH DOT ABOVE
	/* 8 WITH DIAERESIS 		*/	0x00EB,	// LATIN SMALL LETTER E WITH DIAERESIS
	/* 9 					*/	0x0065,	// LATIN SMALL LETTER E
	/* 10(A) WITH RING ABOVE 	*/	0x0065,	// LATIN SMALL LETTER E
	/* 11(B) WITH CEDILLA 		*/	0x0065,	// LATIN SMALL LETTER E
	/* 12(C) 					*/	0x0065,	// LATIN SMALL LETTER E
	/* 13(D) WITH DOUBLE ACUTE*/	0x0065,	// LATIN SMALL LETTER E
	/* 14(E) WITH OGONEK 		*/	0x0119,	// LATIN SMALL LETTER E WITH OGONEK
	/* 15(F) WITH CARON 		*/	0x011B,	// LATIN SMALL LETTER E WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_F[]=
{
	/* 0 					*/	0x0066,	// LATIN SMALL LETTER F
	/* 1 WITH GRAVE 			*/	0x0066,	// LATIN SMALL LETTER F
	/* 2 WITH ACUTE 			*/	0x0066,	// LATIN SMALL LETTER F
	/* 3 WITH CIRCUMFLEX 		*/	0x0066,	// LATIN SMALL LETTER F
	/* 4 WITH TILDE 			*/	0x0066,	// LATIN SMALL LETTER F
	/* 5 WITH MACRON 		*/	0x0066,	// LATIN SMALL LETTER F
	/* 6 WITH BREVE 			*/	0x0066,	// LATIN SMALL LETTER F
	/* 7 WITH DOT ABOVE 		*/	0x0066,	// LATIN SMALL LETTER F
	/* 8 WITH DIAERESIS 		*/	0x0066,	// LATIN SMALL LETTER F
	/* 9 					*/	0x0066,	// LATIN SMALL LETTER F
	/* 10(A) WITH RING ABOVE 	*/	0x0066,	// LATIN SMALL LETTER F
	/* 11(B) WITH CEDILLA 		*/	0x0066,	// LATIN SMALL LETTER F
	/* 12(C) 					*/	0x0066,	// LATIN SMALL LETTER F
	/* 13(D) WITH DOUBLE ACUTE*/	0x0066,	// LATIN SMALL LETTER F
	/* 14(E) WITH OGONEK 		*/	0x0066,	// LATIN SMALL LETTER F
	/* 15(F) WITH CARON 		*/	0x0066,	// LATIN SMALL LETTER F
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_G[]=
{
	/* 0 					*/	0x0067,	// LATIN SMALL LETTER G
	/* 1 WITH GRAVE 			*/	0x0067,	// LATIN SMALL LETTER G
	/* 2 WITH ACUTE 			*/	0x0123,	// LATIN SMALL LETTER G WITH CEDILLA (BUT, for compatibility the representation is not changed, orignally name is small g with acute accent)
	/* 3 WITH CIRCUMFLEX 		*/	0x011D,	// LATIN SMALL LETTER G WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0067,	// LATIN SMALL LETTER G
	/* 5 WITH MACRON 		*/	0x0067,	// LATIN SMALL LETTER G
	/* 6 WITH BREVE 			*/	0x011F,	// LATIN SMALL LETTER G WITH BREVE
	/* 7 WITH DOT ABOVE 		*/	0x0121,	// LATIN SMALL LETTER G WITH DOT ABOVE
	/* 8 WITH DIAERESIS 		*/	0x0067,	// LATIN SMALL LETTER G
	/* 9 					*/	0x0067,	// LATIN SMALL LETTER G
	/* 10(A) WITH RING ABOVE 	*/	0x0067,	// LATIN SMALL LETTER G
	/* 11(B) WITH CEDILLA 		*/	0x0067,	// LATIN SMALL LETTER G
	/* 12(C) 					*/	0x0067,	// LATIN SMALL LETTER G
	/* 13(D) WITH DOUBLE ACUTE*/	0x0067,	// LATIN SMALL LETTER G
	/* 14(E) WITH OGONEK 		*/	0x0067,	// LATIN SMALL LETTER G
	/* 15(F) WITH CARON 		*/	0x0067,	// LATIN SMALL LETTER G
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_H[]=
{
	/* 0 					*/	0x0068,	// LATIN SMALL LETTER H
	/* 1 WITH GRAVE 			*/	0x0068,	// LATIN SMALL LETTER H
	/* 2 WITH ACUTE 			*/	0x0068,	// LATIN SMALL LETTER H
	/* 3 WITH CIRCUMFLEX 		*/	0x0125,	// LATIN SMALL LETTER H WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0068,	// LATIN SMALL LETTER H
	/* 5 WITH MACRON 		*/	0x0068,	// LATIN SMALL LETTER H
	/* 6 WITH BREVE 			*/	0x0068,	// LATIN SMALL LETTER H
	/* 7 WITH DOT ABOVE 		*/	0x0068,	// LATIN SMALL LETTER H
	/* 8 WITH DIAERESIS 		*/	0x0068,	// LATIN SMALL LETTER H
	/* 9 					*/	0x0068,	// LATIN SMALL LETTER H
	/* 10(A) WITH RING ABOVE 	*/	0x0068,	// LATIN SMALL LETTER H
	/* 11(B) WITH CEDILLA 		*/	0x0068,	// LATIN SMALL LETTER H
	/* 12(C) 					*/	0x0068,	// LATIN SMALL LETTER H
	/* 13(D) WITH DOUBLE ACUTE*/	0x0068,	// LATIN SMALL LETTER H
	/* 14(E) WITH OGONEK 		*/	0x0068,	// LATIN SMALL LETTER H
	/* 15(F) WITH CARON 		*/	0x0068,	// LATIN SMALL LETTER H
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_I[]=
{
	/* 0 					*/	0x0069,	// LATIN SMALL LETTER I
	/* 1 WITH GRAVE 			*/	0x00EC,	// LATIN SMALL LETTER I WITH GRAVE
	/* 2 WITH ACUTE 			*/	0x00ED,	// LATIN SMALL LETTER I WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x00EE,	// LATIN SMALL LETTER I WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0129,	// LATIN SMALL LETTER I WITH TILDE
	/* 5 WITH MACRON 		*/	0x012B,	// LATIN SMALL LETTER I WITH MACRON
	/* 6 WITH BREVE 			*/	0x0069,	// LATIN SMALL LETTER I
	/* 7 WITH DOT ABOVE 		*/	0x0069,	// LATIN SMALL LETTER I
	/* 8 WITH DIAERESIS 		*/	0x00EF,	// LATIN SMALL LETTER I WITH DIAERESIS
	/* 9 					*/	0x0069,	// LATIN SMALL LETTER I
	/* 10(A) WITH RING ABOVE 	*/	0x0069,	// LATIN SMALL LETTER I
	/* 11(B) WITH CEDILLA 		*/	0x0069,	// LATIN SMALL LETTER I
	/* 12(C) 					*/	0x0069,	// LATIN SMALL LETTER I
	/* 13(D) WITH DOUBLE ACUTE*/	0x0069,	// LATIN SMALL LETTER I
	/* 14(E) WITH OGONEK 		*/	0x012F,	// LATIN SMALL LETTER I WITH OGONEK
	/* 15(F) WITH CARON 		*/	0x0069,	// LATIN SMALL LETTER I
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_J[]=
{
	/* 0 					*/	0x006A,	// LATIN SMALL LETTER J
	/* 1 WITH GRAVE 			*/	0x006A,	// LATIN SMALL LETTER J
	/* 2 WITH ACUTE 			*/	0x006A,	// LATIN SMALL LETTER J
	/* 3 WITH CIRCUMFLEX 		*/	0x0135,	// LATIN SMALL LETTER J WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x006A,	// LATIN SMALL LETTER J
	/* 5 WITH MACRON 		*/	0x006A,	// LATIN SMALL LETTER J
	/* 6 WITH BREVE 			*/	0x006A,	// LATIN SMALL LETTER J
	/* 7 WITH DOT ABOVE 		*/	0x006A,	// LATIN SMALL LETTER J
	/* 8 WITH DIAERESIS 		*/	0x006A,	// LATIN SMALL LETTER J
	/* 9 					*/	0x006A,	// LATIN SMALL LETTER J
	/* 10(A) WITH RING ABOVE 	*/	0x006A,	// LATIN SMALL LETTER J
	/* 11(B) WITH CEDILLA 		*/	0x006A,	// LATIN SMALL LETTER J
	/* 12(C) 					*/	0x006A,	// LATIN SMALL LETTER J
	/* 13(D) WITH DOUBLE ACUTE*/	0x006A,	// LATIN SMALL LETTER J
	/* 14(E) WITH OGONEK 		*/	0x006A,	// LATIN SMALL LETTER J
	/* 15(F) WITH CARON 		*/	0x006A,	// LATIN SMALL LETTER J
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_K[]=
{
	/* 0 					*/	0x006B,	// LATIN SMALL LETTER K
	/* 1 WITH GRAVE 			*/	0x006B,	// LATIN SMALL LETTER K
	/* 2 WITH ACUTE 			*/	0x006B,	// LATIN SMALL LETTER K
	/* 3 WITH CIRCUMFLEX 		*/	0x006B,	// LATIN SMALL LETTER K
	/* 4 WITH TILDE 			*/	0x006B,	// LATIN SMALL LETTER K
	/* 5 WITH MACRON 		*/	0x006B,	// LATIN SMALL LETTER K
	/* 6 WITH BREVE 			*/	0x006B,	// LATIN SMALL LETTER K
	/* 7 WITH DOT ABOVE 		*/	0x006B,	// LATIN SMALL LETTER K
	/* 8 WITH DIAERESIS 		*/	0x006B,	// LATIN SMALL LETTER K
	/* 9 					*/	0x006B,	// LATIN SMALL LETTER K
	/* 10(A) WITH RING ABOVE 	*/	0x006B,	// LATIN SMALL LETTER K
	/* 11(B) WITH CEDILLA 		*/	0x0137,	// LATIN SMALL LETTER K WITH CEDILLA
	/* 12(C) 					*/	0x006B,	// LATIN SMALL LETTER K
	/* 13(D) WITH DOUBLE ACUTE*/	0x006B,	// LATIN SMALL LETTER K
	/* 14(E) WITH OGONEK 		*/	0x006B,	// LATIN SMALL LETTER K
	/* 15(F) WITH CARON 		*/	0x006B,	// LATIN SMALL LETTER K
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_L[]=
{
	/* 0 					*/	0x006C,	// LATIN SMALL LETTER L
	/* 1 WITH GRAVE 			*/	0x006C,	// LATIN SMALL LETTER L
	/* 2 WITH ACUTE 			*/	0x013A,	// LATIN SMALL LETTER L WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x006C,	// LATIN SMALL LETTER L
	/* 4 WITH TILDE 			*/	0x006C,	// LATIN SMALL LETTER L
	/* 5 WITH MACRON 		*/	0x006C,	// LATIN SMALL LETTER L
	/* 6 WITH BREVE 			*/	0x006C,	// LATIN SMALL LETTER L
	/* 7 WITH DOT ABOVE 		*/	0x006C,	// LATIN SMALL LETTER L
	/* 8 WITH DIAERESIS 		*/	0x006C,	// LATIN SMALL LETTER L
	/* 9 					*/	0x006C,	// LATIN SMALL LETTER L
	/* 10(A) WITH RING ABOVE 	*/	0x006C,	// LATIN SMALL LETTER L
	/* 11(B) WITH CEDILLA 		*/	0x013C,	// LATIN SMALL LETTER L WITH CEDILLA
	/* 12(C) 					*/	0x006C,	// LATIN SMALL LETTER L
	/* 13(D) WITH DOUBLE ACUTE*/	0x006C,	// LATIN SMALL LETTER L
	/* 14(E) WITH OGONEK 		*/	0x006C,	// LATIN SMALL LETTER L
	/* 15(F) WITH CARON 		*/	0x013E,	// LATIN SMALL LETTER L WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_M[]=
{
	/* 0 					*/	0x006D,	// LATIN SMALL LETTER M
	/* 1 WITH GRAVE 			*/	0x006D,	// LATIN SMALL LETTER M
	/* 2 WITH ACUTE 			*/	0x006D,	// LATIN SMALL LETTER M
	/* 3 WITH CIRCUMFLEX 		*/	0x006D,	// LATIN SMALL LETTER M
	/* 4 WITH TILDE 			*/	0x006D,	// LATIN SMALL LETTER M
	/* 5 WITH MACRON 		*/	0x006D,	// LATIN SMALL LETTER M
	/* 6 WITH BREVE 			*/	0x006D,	// LATIN SMALL LETTER M
	/* 7 WITH DOT ABOVE 		*/	0x006D,	// LATIN SMALL LETTER M
	/* 8 WITH DIAERESIS 		*/	0x006D,	// LATIN SMALL LETTER M
	/* 9 					*/	0x006D,	// LATIN SMALL LETTER M
	/* 10(A) WITH RING ABOVE 	*/	0x006D,	// LATIN SMALL LETTER M
	/* 11(B) WITH CEDILLA 		*/	0x006D,	// LATIN SMALL LETTER M
	/* 12(C) 					*/	0x006D,	// LATIN SMALL LETTER M
	/* 13(D) WITH DOUBLE ACUTE*/	0x006D,	// LATIN SMALL LETTER M
	/* 14(E) WITH OGONEK 		*/	0x006D,	// LATIN SMALL LETTER M
	/* 15(F) WITH CARON 		*/	0x006D,	// LATIN SMALL LETTER M
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_N[]=
{
	/* 0 					*/	0x006E,	// LATIN SMALL LETTER N
	/* 1 WITH GRAVE 			*/	0x006E,	// LATIN SMALL LETTER N
	/* 2 WITH ACUTE 			*/	0x0144,	// LATIN SMALL LETTER N WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x006E,	// LATIN SMALL LETTER N
	/* 4 WITH TILDE 			*/	0x00F1,	// LATIN SMALL LETTER N WITH TILDE
	/* 5 WITH MACRON 		*/	0x006E,	// LATIN SMALL LETTER N
	/* 6 WITH BREVE 			*/	0x006E,	// LATIN SMALL LETTER N
	/* 7 WITH DOT ABOVE 		*/	0x006E,	// LATIN SMALL LETTER N
	/* 8 WITH DIAERESIS 		*/	0x006E,	// LATIN SMALL LETTER N
	/* 9 					*/	0x006E,	// LATIN SMALL LETTER N
	/* 10(A) WITH RING ABOVE 	*/	0x006E,	// LATIN SMALL LETTER N
	/* 11(B) WITH CEDILLA 		*/	0x0146,	// LATIN SMALL LETTER N WITH CEDILLA
	/* 12(C) 					*/	0x006E,	// LATIN SMALL LETTER N
	/* 13(D) WITH DOUBLE ACUTE*/	0x006E,	// LATIN SMALL LETTER N
	/* 14(E) WITH OGONEK 		*/	0x006E,	// LATIN SMALL LETTER N
	/* 15(F) WITH CARON 		*/	0x0148,	// LATIN SMALL LETTER N WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_O[]=
{
	/* 0 					*/	0x006F,	// LATIN SMALL LETTER O
	/* 1 WITH GRAVE 			*/	0x00F2,	// LATIN SMALL LETTER O WITH GRAVE
	/* 2 WITH ACUTE 			*/	0x00F3,	// LATIN SMALL LETTER O WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x00F4,	// LATIN SMALL LETTER O WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x00F5,	// LATIN SMALL LETTER O WITH TILDE
	/* 5 WITH MACRON 		*/	0x014D,	// LATIN SMALL LETTER O WITH MACRON
	/* 6 WITH BREVE 			*/	0x006F,	// LATIN SMALL LETTER O
	/* 7 WITH DOT ABOVE 		*/	0x006F,	// LATIN SMALL LETTER O
	/* 8 WITH DIAERESIS 		*/	0x00F6,	// LATIN SMALL LETTER O WITH DIAERESIS
	/* 9 					*/	0x006F,	// LATIN SMALL LETTER O
	/* 10(A) WITH RING ABOVE 	*/	0x006F,	// LATIN SMALL LETTER O
	/* 11(B) WITH CEDILLA 		*/	0x006F,	// LATIN SMALL LETTER O
	/* 12(C) 					*/	0x006F,	// LATIN SMALL LETTER O
	/* 13(D) WITH DOUBLE ACUTE*/	0x0151,	// LATIN SMALL LETTER O WITH DOUBLE ACUTE
	/* 14(E) WITH OGONEK 		*/	0x006F,	// LATIN SMALL LETTER O
	/* 15(F) WITH CARON 		*/	0x006F,	// LATIN SMALL LETTER O
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_P[]=
{
	/* 0 					*/	0x0070,	// LATIN SMALL LETTER P
	/* 1 WITH GRAVE 			*/	0x0070,	// LATIN SMALL LETTER P
	/* 2 WITH ACUTE 			*/	0x0070,	// LATIN SMALL LETTER P
	/* 3 WITH CIRCUMFLEX 		*/	0x0070,	// LATIN SMALL LETTER P
	/* 4 WITH TILDE 			*/	0x0070,	// LATIN SMALL LETTER P
	/* 5 WITH MACRON 		*/	0x0070,	// LATIN SMALL LETTER P
	/* 6 WITH BREVE 			*/	0x0070,	// LATIN SMALL LETTER P
	/* 7 WITH DOT ABOVE 		*/	0x0070,	// LATIN SMALL LETTER P
	/* 8 WITH DIAERESIS 		*/	0x0070,	// LATIN SMALL LETTER P
	/* 9 					*/	0x0070,	// LATIN SMALL LETTER P
	/* 10(A) WITH RING ABOVE 	*/	0x0070,	// LATIN SMALL LETTER P
	/* 11(B) WITH CEDILLA 		*/	0x0070,	// LATIN SMALL LETTER P
	/* 12(C) 					*/	0x0070,	// LATIN SMALL LETTER P
	/* 13(D) WITH DOUBLE ACUTE*/	0x0070,	// LATIN SMALL LETTER P
	/* 14(E) WITH OGONEK 		*/	0x0070,	// LATIN SMALL LETTER P
	/* 15(F) WITH CARON 		*/	0x0070,	// LATIN SMALL LETTER P
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_Q[]=
{
	/* 0 					*/	0x0071,	// LATIN SMALL LETTER Q
	/* 1 WITH GRAVE 			*/	0x0071,	// LATIN SMALL LETTER Q
	/* 2 WITH ACUTE 			*/	0x0071,	// LATIN SMALL LETTER Q
	/* 3 WITH CIRCUMFLEX 		*/	0x0071,	// LATIN SMALL LETTER Q
	/* 4 WITH TILDE 			*/	0x0071,	// LATIN SMALL LETTER Q
	/* 5 WITH MACRON 		*/	0x0071,	// LATIN SMALL LETTER Q
	/* 6 WITH BREVE 			*/	0x0071,	// LATIN SMALL LETTER Q
	/* 7 WITH DOT ABOVE 		*/	0x0071,	// LATIN SMALL LETTER Q
	/* 8 WITH DIAERESIS 		*/	0x0071,	// LATIN SMALL LETTER Q
	/* 9 					*/	0x0071,	// LATIN SMALL LETTER Q
	/* 10(A) WITH RING ABOVE 	*/	0x0071,	// LATIN SMALL LETTER Q
	/* 11(B) WITH CEDILLA 		*/	0x0071,	// LATIN SMALL LETTER Q
	/* 12(C) 					*/	0x0071,	// LATIN SMALL LETTER Q
	/* 13(D) WITH DOUBLE ACUTE*/	0x0071,	// LATIN SMALL LETTER Q
	/* 14(E) WITH OGONEK 		*/	0x0071,	// LATIN SMALL LETTER Q
	/* 15(F) WITH CARON 		*/	0x0071,	// LATIN SMALL LETTER Q
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_R[]=
{
	/* 0 					*/	0x0072,	// LATIN SMALL LETTER R
	/* 1 WITH GRAVE 			*/	0x0072,	// LATIN SMALL LETTER R
	/* 2 WITH ACUTE 			*/	0x0155,	// LATIN SMALL LETTER R WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x0072,	// LATIN SMALL LETTER R
	/* 4 WITH TILDE 			*/	0x0072,	// LATIN SMALL LETTER R
	/* 5 WITH MACRON 		*/	0x0072,	// LATIN SMALL LETTER R
	/* 6 WITH BREVE 			*/	0x0072,	// LATIN SMALL LETTER R
	/* 7 WITH DOT ABOVE 		*/	0x0072,	// LATIN SMALL LETTER R
	/* 8 WITH DIAERESIS 		*/	0x0072,	// LATIN SMALL LETTER R
	/* 9 					*/	0x0072,	// LATIN SMALL LETTER R
	/* 10(A) WITH RING ABOVE 	*/	0x0072,	// LATIN SMALL LETTER R
	/* 11(B) WITH CEDILLA 		*/	0x0157,	// LATIN SMALL LETTER R WITH CEDILLA
	/* 12(C) 					*/	0x0072,	// LATIN SMALL LETTER R
	/* 13(D) WITH DOUBLE ACUTE*/	0x0072,	// LATIN SMALL LETTER R
	/* 14(E) WITH OGONEK 		*/	0x0072,	// LATIN SMALL LETTER R
	/* 15(F) WITH CARON 		*/	0x0159,	// LATIN SMALL LETTER R WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_S[]=
{
	/* 0 					*/	0x0073,	// LATIN SMALL LETTER S
	/* 1 WITH GRAVE 			*/	0x0073,	// LATIN SMALL LETTER S
	/* 2 WITH ACUTE 			*/	0x015B,	// LATIN SMALL LETTER S WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x015D,	// LATIN SMALL LETTER S WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0073,	// LATIN SMALL LETTER S
	/* 5 WITH MACRON 		*/	0x0073,	// LATIN SMALL LETTER S
	/* 6 WITH BREVE 			*/	0x0073,	// LATIN SMALL LETTER S
	/* 7 WITH DOT ABOVE 		*/	0x0073,	// LATIN SMALL LETTER S
	/* 8 WITH DIAERESIS 		*/	0x0073,	// LATIN SMALL LETTER S
	/* 9 					*/	0x0073,	// LATIN SMALL LETTER S
	/* 10(A) WITH RING ABOVE 	*/	0x0073,	// LATIN SMALL LETTER S
	/* 11(B) WITH CEDILLA 		*/	0x015F,	// LATIN SMALL LETTER S WITH CEDILLA
	/* 12(C) 					*/	0x0073,	// LATIN SMALL LETTER S
	/* 13(D) WITH DOUBLE ACUTE*/	0x0073,	// LATIN SMALL LETTER S
	/* 14(E) WITH OGONEK 		*/	0x0073,	// LATIN SMALL LETTER S
	/* 15(F) WITH CARON 		*/	0x0161,	// LATIN SMALL LETTER S WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_T[]=
{
	/* 0 					*/	0x0074,	// LATIN SMALL LETTER T
	/* 1 WITH GRAVE 			*/	0x0074,	// LATIN SMALL LETTER T
	/* 2 WITH ACUTE 			*/	0x0074,	// LATIN SMALL LETTER T
	/* 3 WITH CIRCUMFLEX 		*/	0x0074,	// LATIN SMALL LETTER T
	/* 4 WITH TILDE 			*/	0x0074,	// LATIN SMALL LETTER T
	/* 5 WITH MACRON 		*/	0x0074,	// LATIN SMALL LETTER T
	/* 6 WITH BREVE 			*/	0x0074,	// LATIN SMALL LETTER T
	/* 7 WITH DOT ABOVE 		*/	0x0074,	// LATIN SMALL LETTER T
	/* 8 WITH DIAERESIS 		*/	0x0074,	// LATIN SMALL LETTER T
	/* 9 					*/	0x0074,	// LATIN SMALL LETTER T
	/* 10(A) WITH RING ABOVE 	*/	0x0074,	// LATIN SMALL LETTER T
	/* 11(B) WITH CEDILLA 		*/	0x0163,	// LATIN SMALL LETTER T WITH CEDILLA
	/* 12(C) 					*/	0x0074,	// LATIN SMALL LETTER T
	/* 13(D) WITH DOUBLE ACUTE*/	0x0074,	// LATIN SMALL LETTER T
	/* 14(E) WITH OGONEK 		*/	0x0074,	// LATIN SMALL LETTER T
	/* 15(F) WITH CARON 		*/	0x0165,	// LATIN SMALL LETTER T WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_U[]=
{
	/* 0 					*/	0x0075,	// LATIN SMALL LETTER U
	/* 1 WITH GRAVE 			*/	0x00F9,	// LATIN SMALL LETTER U WITH GRAVE
	/* 2 WITH ACUTE 			*/	0x00FA,	// LATIN SMALL LETTER U WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x00FB,	// LATIN SMALL LETTER U WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0169,	// LATIN SMALL LETTER U WITH TILDE
	/* 5 WITH MACRON 		*/	0x016B,	// LATIN SMALL LETTER U WITH MACRON
	/* 6 WITH BREVE 			*/	0x016D,	// LATIN SMALL LETTER U WITH BREVE
	/* 7 WITH DOT ABOVE 		*/	0x0075,	// LATIN SMALL LETTER U
	/* 8 WITH DIAERESIS 		*/	0x00FC,	// LATIN SMALL LETTER U WITH DIAERESIS
	/* 9 					*/	0x0075,	// LATIN SMALL LETTER U
	/* 10(A) WITH RING ABOVE 	*/	0x016F,	// LATIN SMALL LETTER U WITH RING ABOVE
	/* 11(B) WITH CEDILLA 		*/	0x0075,	// LATIN SMALL LETTER U
	/* 12(C) 					*/	0x0075,	// LATIN SMALL LETTER U
	/* 13(D) WITH DOUBLE ACUTE*/	0x0171,	// LATIN SMALL LETTER U WITH DOUBLE ACUTE
	/* 14(E) WITH OGONEK 		*/	0x0173,	// LATIN SMALL LETTER U WITH OGONEK
	/* 15(F) WITH CARON 		*/	0x0075,	// LATIN SMALL LETTER U
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_V[]=
{
	/* 0 					*/	0x0076,	// LATIN SMALL LETTER V
	/* 1 WITH GRAVE 			*/	0x0076,	// LATIN SMALL LETTER V
	/* 2 WITH ACUTE 			*/	0x0076,	// LATIN SMALL LETTER V
	/* 3 WITH CIRCUMFLEX 		*/	0x0076,	// LATIN SMALL LETTER V
	/* 4 WITH TILDE 			*/	0x0076,	// LATIN SMALL LETTER V
	/* 5 WITH MACRON 		*/	0x0076,	// LATIN SMALL LETTER V
	/* 6 WITH BREVE 			*/	0x0076,	// LATIN SMALL LETTER V
	/* 7 WITH DOT ABOVE 		*/	0x0076,	// LATIN SMALL LETTER V
	/* 8 WITH DIAERESIS 		*/	0x0076,	// LATIN SMALL LETTER V
	/* 9 					*/	0x0076,	// LATIN SMALL LETTER V
	/* 10(A) WITH RING ABOVE 	*/	0x0076,	// LATIN SMALL LETTER V
	/* 11(B) WITH CEDILLA 		*/	0x0076,	// LATIN SMALL LETTER V
	/* 12(C) 					*/	0x0076,	// LATIN SMALL LETTER V
	/* 13(D) WITH DOUBLE ACUTE*/	0x0076,	// LATIN SMALL LETTER V
	/* 14(E) WITH OGONEK 		*/	0x0076,	// LATIN SMALL LETTER V
	/* 15(F) WITH CARON 		*/	0x0076,	// LATIN SMALL LETTER V
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_W[]=
{
	/* 0 					*/	0x0077,	// LATIN SMALL LETTER W
	/* 1 WITH GRAVE 			*/	0x0077,	// LATIN SMALL LETTER W
	/* 2 WITH ACUTE 			*/	0x0077,	// LATIN SMALL LETTER W
	/* 3 WITH CIRCUMFLEX 		*/	0x0175,	// LATIN SMALL LETTER W WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0077,	// LATIN SMALL LETTER W
	/* 5 WITH MACRON 		*/	0x0077,	// LATIN SMALL LETTER W
	/* 6 WITH BREVE 			*/	0x0077,	// LATIN SMALL LETTER W
	/* 7 WITH DOT ABOVE 		*/	0x0077,	// LATIN SMALL LETTER W
	/* 8 WITH DIAERESIS 		*/	0x0077,	// LATIN SMALL LETTER W
	/* 9 					*/	0x0077,	// LATIN SMALL LETTER W
	/* 10(A) WITH RING ABOVE 	*/	0x0077,	// LATIN SMALL LETTER W
	/* 11(B) WITH CEDILLA 		*/	0x0077,	// LATIN SMALL LETTER W
	/* 12(C) 					*/	0x0077,	// LATIN SMALL LETTER W
	/* 13(D) WITH DOUBLE ACUTE*/	0x0077,	// LATIN SMALL LETTER W
	/* 14(E) WITH OGONEK 		*/	0x0077,	// LATIN SMALL LETTER W
	/* 15(F) WITH CARON 		*/	0x0077,	// LATIN SMALL LETTER W
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_X[]=
{
	/* 0 					*/	0x0078,	// LATIN SMALL LETTER X
	/* 1 WITH GRAVE 			*/	0x0078,	// LATIN SMALL LETTER X
	/* 2 WITH ACUTE 			*/	0x0078,	// LATIN SMALL LETTER X
	/* 3 WITH CIRCUMFLEX 		*/	0x0078,	// LATIN SMALL LETTER X
	/* 4 WITH TILDE 			*/	0x0078,	// LATIN SMALL LETTER X
	/* 5 WITH MACRON 		*/	0x0078,	// LATIN SMALL LETTER X
	/* 6 WITH BREVE 			*/	0x0078,	// LATIN SMALL LETTER X
	/* 7 WITH DOT ABOVE 		*/	0x0078,	// LATIN SMALL LETTER X
	/* 8 WITH DIAERESIS 		*/	0x0078,	// LATIN SMALL LETTER X
	/* 9 					*/	0x0078,	// LATIN SMALL LETTER X
	/* 10(A) WITH RING ABOVE 	*/	0x0078,	// LATIN SMALL LETTER X
	/* 11(B) WITH CEDILLA 		*/	0x0078,	// LATIN SMALL LETTER X
	/* 12(C) 					*/	0x0078,	// LATIN SMALL LETTER X
	/* 13(D) WITH DOUBLE ACUTE*/	0x0078,	// LATIN SMALL LETTER X
	/* 14(E) WITH OGONEK 		*/	0x0078,	// LATIN SMALL LETTER X
	/* 15(F) WITH CARON 		*/	0x0078,	// LATIN SMALL LETTER X
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_Y[]=
{
	/* 0 					*/	0x0079,	// LATIN SMALL LETTER Y
	/* 1 WITH GRAVE 			*/	0x0079,	// LATIN SMALL LETTER Y
	/* 2 WITH ACUTE 			*/	0x00FD,	// LATIN SMALL LETTER Y WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x0177,	// LATIN SMALL LETTER Y WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0079,	// LATIN SMALL LETTER Y
	/* 5 WITH MACRON 		*/	0x0079,	// LATIN SMALL LETTER Y
	/* 6 WITH BREVE 			*/	0x0079,	// LATIN SMALL LETTER Y
	/* 7 WITH DOT ABOVE 		*/	0x0079,	// LATIN SMALL LETTER Y
	/* 8 WITH DIAERESIS 		*/	0x00FF,	// LATIN SMALL LETTER Y WITH DIAERESIS
	/* 9 					*/	0x0079,	// LATIN SMALL LETTER Y
	/* 10(A) WITH RING ABOVE 	*/	0x0079,	// LATIN SMALL LETTER Y
	/* 11(B) WITH CEDILLA 		*/	0x0079,	// LATIN SMALL LETTER Y
	/* 12(C) 					*/	0x0079,	// LATIN SMALL LETTER Y
	/* 13(D) WITH DOUBLE ACUTE*/	0x0079,	// LATIN SMALL LETTER Y
	/* 14(E) WITH OGONEK 		*/	0x0079,	// LATIN SMALL LETTER Y
	/* 15(F) WITH CARON 		*/	0x0079,	// LATIN SMALL LETTER Y
};

unsigned short ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_Z[]=
{
	/* 0 					*/	0x007A,	// LATIN SMALL LETTER Z
	/* 1 WITH GRAVE 			*/	0x007A,	// LATIN SMALL LETTER Z
	/* 2 WITH ACUTE 			*/	0x017A,	// LATIN SMALL LETTER Z WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x007A,	// LATIN SMALL LETTER Z
	/* 4 WITH TILDE 			*/	0x007A,	// LATIN SMALL LETTER Z
	/* 5 WITH MACRON 		*/	0x007A,	// LATIN SMALL LETTER Z
	/* 6 WITH BREVE 			*/	0x007A,	// LATIN SMALL LETTER Z
	/* 7 WITH DOT ABOVE 		*/	0x017C,	// LATIN SMALL LETTER Z WITH DOT ABOVE
	/* 8 WITH DIAERESIS 		*/	0x007A,	// LATIN SMALL LETTER Z
	/* 9 					*/	0x007A,	// LATIN SMALL LETTER Z
	/* 10(A) WITH RING ABOVE 	*/	0x007A,	// LATIN SMALL LETTER Z
	/* 11(B) WITH CEDILLA 		*/	0x007A,	// LATIN SMALL LETTER Z
	/* 12(C) 					*/	0x007A,	// LATIN SMALL LETTER Z
	/* 13(D) WITH DOUBLE ACUTE*/	0x007A,	// LATIN SMALL LETTER Z
	/* 14(E) WITH OGONEK 		*/	0x007A,	// LATIN SMALL LETTER Z
	/* 15(F) WITH CARON 		*/	0x017E,	// LATIN SMALL LETTER Z WITH CARON
};

unsigned short ISO6937_UNICODE_TYPEFACE_COMBINE_WITH_SPACE[]=
{
	/* 0 					*/	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// LATIN CAPITAL LETTER A
	/* 1 WITH GRAVE 			*/	0x0300,	// LATIN CAPITAL LETTER A WITH GRAVE
	/* 2 WITH ACUTE 			*/	0x0301,	// LATIN CAPITAL LETTER A WITH ACUTE
	/* 3 WITH CIRCUMFLEX 		*/	0x0302,	// LATIN CAPITAL LETTER A WITH CIRCUMFLEX
	/* 4 WITH TILDE 			*/	0x0303,	// LATIN CAPITAL LETTER A WITH TILDE
	/* 5 WITH MACRON 		*/	0x0304,	// LATIN CAPITAL LETTER A WITH MACRON
	/* 6 WITH BREVE 			*/	0x0306,	// LATIN CAPITAL LETTER A WITH BREVE
	/* 7 WITH DOT ABOVE 		*/	0x0307,	// LATIN CAPITAL LETTER A
	/* 8 WITH DIAERESIS 		*/	0x0308,	// LATIN CAPITAL LETTER A WITH DIAERESIS
	/* 9 					*/	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// LATIN CAPITAL LETTER A
	/* 10(A) WITH RING ABOVE 	*/	0x030A,	// LATIN CAPITAL LETTER A WITH RING ABOVE
	/* 11(B) WITH CEDILLA 		*/	0x0327,	// LATIN CAPITAL LETTER A
	/* 12(C) 					*/	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// LATIN CAPITAL LETTER A
	/* 13(D) WITH DOUBLE ACUTE*/	0x030B,	// LATIN CAPITAL LETTER A
	/* 14(E) WITH OGONEK 		*/	0x0328,	// LATIN CAPITAL LETTER A
	/* 15(F) WITH CARON 		*/	0x030C,	// LATIN CAPITAL LETTER A
};

#define	ALPHA_CASE_NUM	26

unsigned short *ISO6937_COMBINIG_CAPITAL_LETTER[ALPHA_CASE_NUM]=
{
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_A,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_B,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_C,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_D,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_E,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_F,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_G,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_H,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_I,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_J,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_K,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_L,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_M,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_N,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_O,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_P,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_Q,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_R,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_S,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_T,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_U,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_V,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_W,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_X,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_Y,
	ISO6937_UNICODE_TYPEFACE_LATIN_CAPITAL_LETTER_Z,
};

unsigned short *ISO6937_COMBINIG_SMALL_LETTER[ALPHA_CASE_NUM]=
{
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_A,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_B,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_C,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_D,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_E,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_F,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_G,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_H,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_I,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_J,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_K,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_L,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_M,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_N,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_O,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_P,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_Q,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_R,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_S,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_T,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_U,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_V,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_W,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_X,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_Y,
	ISO6937_UNICODE_TYPEFACE_LATIN_SMALL_LETTER_Z,
};



// DejaVu Font에 있는 값으로 셋팅해야 한다.
unsigned short ISO6937_DejaVu_OTHER_TABLE_proto[]=
{
	/* 10/00 (0xA0) */	0x00A0,	// NO-BREAK SPACE
	/* 10/01 (0xA1) */	0x00A1,	// INVERTED EXCLAMATION MARK
	/* 10/02 (0xA2) */	0x00A2,	// CENT SIGN
	/* 10/03 (0xA3) */	0x00A3,	// POUND SIGN
	/* 10/04 (0xA4) */	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// (not used)
	/* 10/05 (0xA5) */	0x00A5,	// YEN SIGN
	/* 10/06 (0xA6) */	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// (not used)
	/* 10/07 (0xA7) */	0x00A7,	// SECTION SIGN
	/* 10/08 (0xA8) */	0x00A4,	// CURRENCY SIGN
	/* 10/09 (0xA9) */	0x2018,	// LEFT SINGLE QUOTATION MARK
	/* 10/10 (0xAA) */	0x201C,	// LEFT DOUBLE QUOTATION MARK
	/* 10/11 (0xAB) */	0x00AB,	// LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
	/* 10/12 (0xAC) */	0x2190,	// LEFTWARDS ARROW (DejaVu only)
	/* 10/13 (0xAD) */	0x2191,	// UPWARDS ARROW (DejaVu only)
	/* 10/14 (0xAE) */	0x2192,	// RIGHTWARDS ARROW (DejaVu only)
	/* 10/15 (0xAF) */	0x2193,	// DOWNWARDS ARROW (DejaVu only)

	/* 11/00 (0xB0) */	0x00B0,	// DEGREE SIGN
	/* 11/01 (0xB1) */	0x00B1,	// PLUS-MINUS SIGN
	/* 11/02 (0xB2) */	0x00B2,	// SUPERSCRIPT TWO
	/* 11/03 (0xB3) */	0x00B3,	// SUPERSCRIPT THREE
	/* 11/04 (0xB4) */	0x00D7,	// MULTIPLICATION SIGN
	/* 11/05 (0xB5) */	0x00B5,	// MICRO SIGN
	/* 11/06 (0xB6) */	0x00B6,	// PILCROW SIGN
	/* 11/07 (0xB7) */	0x00B7,	// MIDDLE DOT
	/* 11/08 (0xB8) */	0x00F7,	// DIVISION SIGN
	/* 11/09 (0xB9) */	0x2019,	// RIGHT SINGLE QUOTATION MARK
	/* 11/10 (0xBA) */	0x201D,	// RIGHT DOUBLE QUOTATION MARK
	/* 11/11 (0xBB) */	0x00BB,	// RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
	/* 11/12 (0xBC) */	0x00BC,	// VULGAR FRACTION ONE QUARTER
	/* 11/13 (0xBD) */	0x00BD,	// VULGAR FRACTION ONE HALF
	/* 11/14 (0xBE) */	0x00BE,	// VULGAR FRACTION THREE QUARTERS
	/* 11/15 (0xBF) */	0x00BF,	// INVERTED QUESTION MARK

	/* 12/00 (0xC0) */	0x2015,	// (not used)
	/* 12/01 (0xC1) */	0x0300,	// non-spacing grave accent (DejaVu only)
	/* 12/02 (0xC2) */	0x0301,	// non-spacing acute accent (DejaVu only)
	/* 12/03 (0xC3) */	0x0302,	// non-spacing circumflex accent (DejaVu only)
	/* 12/04 (0xC4) */	0x0303,	// non-spacing tilde (DejaVu only)
	/* 12/05 (0xC5) */	0x0304,	// non-spacing macron (DejaVu only)
	/* 12/06 (0xC6) */	0x0306,	// non-spacing breve (DejaVu only)
	/* 12/07 (0xC7) */	0x0307,	// non-spacing dot above (DejaVu only)
	/* 12/08 (0xC8) */	0x0308,	// non-spacing diaeresis (DejaVu only)
	/* 12/09 (0xC9) */	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// (not used)
	/* 12/10 (0xCA) */	0x030A,	// non-spacing ring above (DejaVu only)
	/* 12/11 (0xCB) */	0x0327,	// non-spacing cedilla (DejaVu only)
	/* 12/12 (0xCC) */	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// (not used)
	/* 12/13 (0xCD) */	0x030B,	// non-spacing double acute accent (DejaVu only)
	/* 12/14 (0xCE) */	0x0328,	// non-spacing ogonek (DejaVu only)
	/* 12/15 (0xCF) */	0x030C,	// non-spacing caron (DejaVu only)

	/* 13/00 (0xD0) */	0x2015,	// HORIZONTAL BAR
	/* 13/01 (0xD1) */	0x00B9,	// SUPERSCRIPT ONE
	/* 13/02 (0xD2) */	0x00AE,	// REGISTERED SIGN
	/* 13/03 (0xD3) */	0x00A9,	// COPYRIGHT SIGN
	/* 13/04 (0xD4) */	0x2122,	// TRADE MARK SIGN (DejaVu only)
	/* 13/05 (0xD5) */	0x266A,	// EIGHTH NOTE (DejaVu only)
	/* 13/06 (0xD6) */	0x00AC,	// NOT SIGN
	/* 13/07 (0xD7) */	0x00A6,	// BROKEN BAR
	/* 13/08 (0xD8) */	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// (not used)
	/* 13/09 (0xD9) */	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// (not used)
	/* 13/10 (0xDA) */	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// (not used)
	/* 13/11 (0xDB) */	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// (not used)
	/* 13/12 (0xDC) */	0x215B,	// VULGAR FRACTION ONE EIGHTH (DejaVu only)
	/* 13/13 (0xDD) */	0x215C,	// VULGAR FRACTION THREE EIGHTHS (DejaVu only)
	/* 13/14 (0xDE) */	0x215D,	// VULGAR FRACTION FIVE EIGHTHS (DejaVu only)
	/* 13/15 (0xDF) */	0x215E,	// VULGAR FRACTION SEVEN EIGHTHs (DejaVu only)

	/* 14/00 (0xE0) */	0x2126,	// OHM SIGN (DejaVu only)
	/* 14/01 (0xE1) */	0x00C6,	// LATIN CAPITAL LETTER AE
	/* 14/02 (0xE2) */	0x0110,	// LATIN CAPITAL LETTER D WITH STROKE
	/* 14/03 (0xE3) */	0x00AA,	// FEMININE ORDINAL INDICATOR
	/* 14/04 (0xE4) */	0x0126,	// LATIN CAPITAL LETTER H WITH STROKE
	/* 14/05 (0xE5) */	CH_UCS2_USERDEFINE_CODE_IGNORE_CH,	// (not used)
	/* 14/06 (0xE6) */	0x0132,	// LATIN CAPITAL LIGATURE IJ (DejaVu only)
	/* 14/07 (0xE7) */	0x013F,	// LATIN CAPITAL LETTER L WITH MIDDLE DOT (DejaVu only)
	/* 14/08 (0xE8) */	0x0141,	// LATIN CAPITAL LETTER L WITH STROKE
	/* 14/09 (0xE9) */	0x00D8,	// LATIN CAPITAL LETTER O WITH STROKE
	/* 14/10 (0xEA) */	0x0152,	// LATIN CAPITAL LIGATURE OE
	/* 14/11 (0xEB) */	0x00BA,	// MASCULINE ORDINAL INDICATOR
	/* 14/12 (0xEC) */	0x00DE,	// LATIN CAPITAL LETTER THORN
	/* 14/13 (0xED) */	0x0166,	// LATIN CAPITAL LETTER T WITH STROKE
	/* 14/14 (0xEE) */	0x014A,	// LATIN CAPITAL LETTER ENG
	/* 14/15 (0xEF) */	0x0149,	// LATIN SMALL LETTER N PRECEDED BY APOSTROPHE (DejaVu only)

	/* 15/00 (0xF0) */	0x0138,	// LATIN SMALL LETTER KRA
	/* 15/01 (0xF1) */	0x00E6,	// LATIN SMALL LETTER AE
	/* 15/02 (0xF2) */	0x0111,	// LATIN SMALL LETTER D WITH STROKE
	/* 15/03 (0xF3) */	0x00F0,	// LATIN SMALL LETTER ETH
	/* 15/04 (0xF4) */	0x0127,	// LATIN SMALL LETTER H WITH STROKE
	/* 15/05 (0xF5) */	0x0131,	// LATIN SMALL LETTER DOTLESS I
	/* 15/06 (0xF6) */	0x0133,	// LATIN SMALL LETTER LIGATURE IJ (DejaVu only)
	/* 15/07 (0xF7) */	0x0140,	// LATIN SMALL LETTER L WITH MIDDLE DOT (DejaVu only)
	/* 15/08 (0xF8) */	0x0142,	// LATIN SMALL LETTER L WITH STROKE
	/* 15/09 (0xF9) */	0x00F8,	// LATIN SMALL LETTER O WITH STROKE
	/* 15/10 (0xFA) */	0x0153,	// LATIN SMALL LIGATURE OE
	/* 15/11 (0xFB) */	0x00DF,	// LATIN SMALL LETTER SHARP S
	/* 15/12 (0xFC) */	0x00FE,	// LATIN SMALL LETTER THORN
	/* 15/13 (0xFD) */	0x0167,	// LATIN SMALL LETTER T WITH STROKE
	/* 15/14 (0xFE) */	0x014B,	// LATIN SMALL LETTER ENG
	/* 15/15 (0xFF) */	0x00AD,	// SOFT HYPHEN
};

CHARMAPITEM_toUnicode ISO_6937_PAGE01_TO_UNICODE[]=
{
	/* 10/00 */	{0xA0,	0x00A0},	// NO-BREAK SPACE
	/* 10/01 */	{0xA1,	0x00A1},	// INVERTED EXCLAMATION MARK
	/* 10/02 */	{0xA2,	0x00A2},	// CENT SIGN
	/* 10/03 */	{0xA3,	0x00A3},	// POUND SIGN
	/* 10/04 */	{0xA4,	0x20AC},	// EURO SIGN //TODO: standard name check
	/* 10/05 */	{0xA5,	0x00A5},	// YEN SIGN
	/* 10/06 */	{0xA6,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 10/07 */	{0xA7,	0x00A7},	// SECTION SIGN
	/* 10/08 */	{0xA8,	0x00A4},	// CURRENCY SIGN
	/* 10/09 */	{0xA9,	0x2018},	// LEFT SINGLE QUOTATION MARK
	/* 10/10 */	{0xAA,	0x201C},	// LEFT DOUBLE QUOTATION MARK
	/* 10/11 */	{0xAB,	0x00AB},	// LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
	/* 10/12 */	{0xAC,	0x2190},	// LEFTWARDS ARROW (DejaVu only)
	/* 10/13 */	{0xAD,	0x2191},	// UPWARDS ARROW (DejaVu only)
	/* 10/14 */	{0xAE,	0x2192},	// RIGHTWARDS ARROW (DejaVu only)
	/* 10/15 */	{0xAF,	0x2193},	// DOWNWARDS ARROW (DejaVu only)

	/* 11/00 */	{0xB0,	0x00B0},	// DEGREE SIGN
	/* 11/01 */	{0xB1,	0x00B1},	// PLUS-MINUS SIGN
	/* 11/02 */	{0xB2,	0x00B2},	// SUPERSCRIPT TWO
	/* 11/03 */	{0xB3,	0x00B3},	// SUPERSCRIPT THREE
	/* 11/04 */	{0xB4,	0x00D7},	// MULTIPLICATION SIGN
	/* 11/05 */	{0xB5,	0x00B5},	// MICRO SIGN
	/* 11/06 */	{0xB6,	0x00B6},	// PILCROW SIGN
	/* 11/07 */	{0xB7,	0x00B7},	// MIDDLE DOT
	/* 11/08 */	{0xB8,	0x00F7},	// DIVISION SIGN
	/* 11/09 */	{0xB9,	0x2019},	// RIGHT SINGLE QUOTATION MARK
	/* 11/10 */	{0xBA,	0x201D},	// RIGHT DOUBLE QUOTATION MARK
	/* 11/11 */	{0xBB,	0x00BB},	// RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
	/* 11/12 */	{0xBC,	0x00BC},	// VULGAR FRACTION ONE QUARTER
	/* 11/13 */	{0xBD,	0x00BD},	// VULGAR FRACTION ONE HALF
	/* 11/14 */	{0xBE,	0x00BE},	// VULGAR FRACTION THREE QUARTERS
	/* 11/15 */	{0xBF,	0x00BF},	// INVERTED QUESTION MARK

	/* 12/00 */	{0xC0,	0x2015},	// (not used)
	/* 12/01 */	{0xC1,	0x0300},	// non-spacing grave accent (DejaVu only)
	/* 12/02 */	{0xC2,	0x0301},	// non-spacing acute accent (DejaVu only)
	/* 12/03 */	{0xC3,	0x0302},	// non-spacing circumflex accent (DejaVu only)
	/* 12/04 */	{0xC4,	0x0303},	// non-spacing tilde (DejaVu only)
	/* 12/05 */	{0xC5,	0x0304},	// non-spacing macron (DejaVu only)
	/* 12/06 */	{0xC6,	0x0306},	// non-spacing breve (DejaVu only)
	/* 12/07 */	{0xC7,	0x0307},	// non-spacing dot above (DejaVu only)
	/* 12/08 */	{0xC8,	0x0308},	// non-spacing diaeresis (DejaVu only)
	/* 12/09 */	{0xC9,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 12/10 */	{0xCA,	0x030A},	// non-spacing ring above (DejaVu only)
	/* 12/11 */	{0xCB,	0x0327},	// non-spacing cedilla (DejaVu only)
	/* 12/12 */	{0xCC,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 12/13 */	{0xCD,	0x030B},	// non-spacing double acute accent (DejaVu only)
	/* 12/14 */	{0xCE,	0x0328},	// non-spacing ogonek (DejaVu only)
	/* 12/15 */	{0xCF,	0x030C},	// non-spacing caron (DejaVu only)

	/* 13/00 */	{0xD0,	0x2015},	// HORIZONTAL BAR
	/* 13/01 */	{0xD1,	0x00B9},	// SUPERSCRIPT ONE
	/* 13/02 */	{0xD2,	0x00AE},	// REGISTERED SIGN
	/* 13/03 */	{0xD3,	0x00A9},	// COPYRIGHT SIGN
	/* 13/04 */	{0xD4,	0x2122},	// TRADE MARK SIGN (DejaVu only)
	/* 13/05 */	{0xD5,	0x266A},	// EIGHTH NOTE (DejaVu only)
	/* 13/06 */	{0xD6,	0x00AC},	// NOT SIGN
	/* 13/07 */	{0xD7,	0x00A6},	// BROKEN BAR
	/* 13/08 */	{0xD8,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 13/09 */	{0xD9,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 13/10 */	{0xDA,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 13/11 */	{0xDB,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 13/12 */	{0xDC,	0x215B},	// VULGAR FRACTION ONE EIGHTH (DejaVu only)
	/* 13/13 */	{0xDD,	0x215C},	// VULGAR FRACTION THREE EIGHTHS (DejaVu only)
	/* 13/14 */	{0xDE,	0x215D},	// VULGAR FRACTION FIVE EIGHTHS (DejaVu only)
	/* 13/15 */	{0xDF,	0x215E},	// VULGAR FRACTION SEVEN EIGHTHs (DejaVu only)

	/* 14/00 */	{0xE0,	0x2126},	// OHM SIGN (DejaVu only)
	/* 14/01 */	{0xE1,	0x00C6},	// LATIN CAPITAL LETTER AE
	/* 14/02 */	{0xE2,	0x0110},	// LATIN CAPITAL LETTER D WITH STROKE
	/* 14/03 */	{0xE3,	0x00AA},	// FEMININE ORDINAL INDICATOR
	/* 14/04 */	{0xE4,	0x0126},	// LATIN CAPITAL LETTER H WITH STROKE
	/* 14/05 */	{0xE5,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 14/06 */	{0xE6,	0x0132},	// LATIN CAPITAL LIGATURE IJ (DejaVu only)
	/* 14/07 */	{0xE7,	0x013F},	// LATIN CAPITAL LETTER L WITH MIDDLE DOT (DejaVu only)
	/* 14/08 */	{0xE8,	0x0141},	// LATIN CAPITAL LETTER L WITH STROKE
	/* 14/09 */	{0xE9,	0x00D8},	// LATIN CAPITAL LETTER O WITH STROKE
	/* 14/10 */	{0xEA,	0x0152},	// LATIN CAPITAL LIGATURE OE
	/* 14/11 */	{0xEB,	0x00BA},	// MASCULINE ORDINAL INDICATOR
	/* 14/12 */	{0xEC,	0x00DE},	// LATIN CAPITAL LETTER THORN
	/* 14/13 */	{0xED,	0x0166},	// LATIN CAPITAL LETTER T WITH STROKE
	/* 14/14 */	{0xEE,	0x014A},	// LATIN CAPITAL LETTER ENG
	/* 14/15 */	{0xEF,	0x0149},	// LATIN SMALL LETTER N PRECEDED BY APOSTROPHE (DejaVu only)

	/* 15/00 */	{0xF0,	0x0138},	// LATIN SMALL LETTER KRA
	/* 15/01 */	{0xF1,	0x00E6},	// LATIN SMALL LETTER AE
	/* 15/02 */	{0xF2,	0x0111},	// LATIN SMALL LETTER D WITH STROKE
	/* 15/03 */	{0xF3,	0x00F0},	// LATIN SMALL LETTER ETH
	/* 15/04 */	{0xF4,	0x0127},	// LATIN SMALL LETTER H WITH STROKE
	/* 15/05 */	{0xF5,	0x0131},	// LATIN SMALL LETTER DOTLESS I
	/* 15/06 */	{0xF6,	0x0133},	// LATIN SMALL LETTER LIGATURE IJ (DejaVu only)
	/* 15/07 */	{0xF7,	0x0140},	// LATIN SMALL LETTER L WITH MIDDLE DOT (DejaVu only)
	/* 15/08 */	{0xF8,	0x0142},	// LATIN SMALL LETTER L WITH STROKE
	/* 15/09 */	{0xF9,	0x00F8},	// LATIN SMALL LETTER O WITH STROKE
	/* 15/10 */	{0xFA,	0x0153},	// LATIN SMALL LIGATURE OE
	/* 15/11 */	{0xFB,	0x00DF},	// LATIN SMALL LETTER SHARP S
	/* 15/12 */	{0xFC,	0x00FE},	// LATIN SMALL LETTER THORN
	/* 15/13 */	{0xFD,	0x0167},	// LATIN SMALL LETTER T WITH STROKE
	/* 15/14 */	{0xFE,	0x014B},	// LATIN SMALL LETTER ENG
	/* 15/15 */	{0xFF,	0x00AD},	// SOFT HYPHEN
};



/* ETST EN 300468 (v 1.7.1) page 80 Figure A.1 table */
// ISO6937 page01 + EURO Symbol (index:0xA6)
CHARMAPITEM_toUnicode EN300468_FA1_TBL_TO_UNICODE[]=
{
	/* 10/00 */	{0xA0,	0x00A0},	// NO-BREAK SPACE
	/* 10/01 */	{0xA1,	0x00A1},	// INVERTED EXCLAMATION MARK
	/* 10/02 */	{0xA2,	0x00A2},	// CENT SIGN
	/* 10/03 */	{0xA3,	0x00A3},	// POUND SIGN
	/* 10/04 */	{0xA4,	0x20AC},	// EURO SYMBOL //TODO: standard name check
	/* 10/05 */	{0xA5,	0x00A5},	// YEN SIGN
	/* 10/06 */	{0xA6,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 10/07 */	{0xA7,	0x00A7},	// SECTION SIGN
	/* 10/08 */	{0xA8,	0x00A4},	// CURRENCY SIGN
	/* 10/09 */	{0xA9,	0x2018},	// LEFT SINGLE QUOTATION MARK
	/* 10/10 */	{0xAA,	0x201C},	// LEFT DOUBLE QUOTATION MARK
	/* 10/11 */	{0xAB,	0x00AB},	// LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
	/* 10/12 */	{0xAC,	0x2190},	// LEFTWARDS ARROW (DejaVu only)
	/* 10/13 */	{0xAD,	0x2191},	// UPWARDS ARROW (DejaVu only)
	/* 10/14 */	{0xAE,	0x2192},	// RIGHTWARDS ARROW (DejaVu only)
	/* 10/15 */	{0xAF,	0x2193},	// DOWNWARDS ARROW (DejaVu only)

	/* 11/00 */	{0xB0,	0x00B0},	// DEGREE SIGN
	/* 11/01 */	{0xB1,	0x00B1},	// PLUS-MINUS SIGN
	/* 11/02 */	{0xB2,	0x00B2},	// SUPERSCRIPT TWO
	/* 11/03 */	{0xB3,	0x00B3},	// SUPERSCRIPT THREE
	/* 11/04 */	{0xB4,	0x00D7},	// MULTIPLICATION SIGN
	/* 11/05 */	{0xB5,	0x00B5},	// MICRO SIGN
	/* 11/06 */	{0xB6,	0x00B6},	// PILCROW SIGN
	/* 11/07 */	{0xB7,	0x00B7},	// MIDDLE DOT
	/* 11/08 */	{0xB8,	0x00F7},	// DIVISION SIGN
	/* 11/09 */	{0xB9,	0x2019},	// RIGHT SINGLE QUOTATION MARK
	/* 11/10 */	{0xBA,	0x201D},	// RIGHT DOUBLE QUOTATION MARK
	/* 11/11 */	{0xBB,	0x00BB},	// RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
	/* 11/12 */	{0xBC,	0x00BC},	// VULGAR FRACTION ONE QUARTER
	/* 11/13 */	{0xBD,	0x00BD},	// VULGAR FRACTION ONE HALF
	/* 11/14 */	{0xBE,	0x00BE},	// VULGAR FRACTION THREE QUARTERS
	/* 11/15 */	{0xBF,	0x00BF},	// INVERTED QUESTION MARK

	/* 12/00 */	{0xC0,	0x2015},	// (not used)
	/* 12/01 */	{0xC1,	0x0300},	// non-spacing grave accent (DejaVu only)
	/* 12/02 */	{0xC2,	0x0301},	// non-spacing acute accent (DejaVu only)
	/* 12/03 */	{0xC3,	0x0302},	// non-spacing circumflex accent (DejaVu only)
	/* 12/04 */	{0xC4,	0x0303},	// non-spacing tilde (DejaVu only)
	/* 12/05 */	{0xC5,	0x0304},	// non-spacing macron (DejaVu only)
	/* 12/06 */	{0xC6,	0x0306},	// non-spacing breve (DejaVu only)
	/* 12/07 */	{0xC7,	0x0307},	// non-spacing dot above (DejaVu only)
	/* 12/08 */	{0xC8,	0x0308},	// non-spacing diaeresis (DejaVu only)
	/* 12/09 */	{0xC9,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 12/10 */	{0xCA,	0x030A},	// non-spacing ring above (DejaVu only)
	/* 12/11 */	{0xCB,	0x0327},	// non-spacing cedilla (DejaVu only)
	/* 12/12 */	{0xCC,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 12/13 */	{0xCD,	0x030B},	// non-spacing double acute accent (DejaVu only)
	/* 12/14 */	{0xCE,	0x0328},	// non-spacing ogonek (DejaVu only)
	/* 12/15 */	{0xCF,	0x030C},	// non-spacing caron (DejaVu only)

	/* 13/00 */	{0xD0,	0x2015},	// HORIZONTAL BAR
	/* 13/01 */	{0xD1,	0x00B9},	// SUPERSCRIPT ONE
	/* 13/02 */	{0xD2,	0x00AE},	// REGISTERED SIGN
	/* 13/03 */	{0xD3,	0x00A9},	// COPYRIGHT SIGN
	/* 13/04 */	{0xD4,	0x2122},	// TRADE MARK SIGN (DejaVu only)
	/* 13/05 */	{0xD5,	0x266A},	// EIGHTH NOTE (DejaVu only)
	/* 13/06 */	{0xD6,	0x00AC},	// NOT SIGN
	/* 13/07 */	{0xD7,	0x00A6},	// BROKEN BAR
	/* 13/08 */	{0xD8,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 13/09 */	{0xD9,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 13/10 */	{0xDA,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 13/11 */	{0xDB,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 13/12 */	{0xDC,	0x215B},	// VULGAR FRACTION ONE EIGHTH (DejaVu only)
	/* 13/13 */	{0xDD,	0x215C},	// VULGAR FRACTION THREE EIGHTHS (DejaVu only)
	/* 13/14 */	{0xDE,	0x215D},	// VULGAR FRACTION FIVE EIGHTHS (DejaVu only)
	/* 13/15 */	{0xDF,	0x215E},	// VULGAR FRACTION SEVEN EIGHTHs (DejaVu only)

	/* 14/00 */	{0xE0,	0x2126},	// OHM SIGN (DejaVu only)
	/* 14/01 */	{0xE1,	0x00C6},	// LATIN CAPITAL LETTER AE
	/* 14/02 */	{0xE2,	0x0110},	// LATIN CAPITAL LETTER D WITH STROKE
	/* 14/03 */	{0xE3,	0x00AA},	// FEMININE ORDINAL INDICATOR
	/* 14/04 */	{0xE4,	0x0126},	// LATIN CAPITAL LETTER H WITH STROKE
	/* 14/05 */	{0xE5,	CH_UCS2_USERDEFINE_CODE_IGNORE_CH},	// (not used)
	/* 14/06 */	{0xE6,	0x0132},	// LATIN CAPITAL LIGATURE IJ (DejaVu only)
	/* 14/07 */	{0xE7,	0x013F},	// LATIN CAPITAL LETTER L WITH MIDDLE DOT (DejaVu only)
	/* 14/08 */	{0xE8,	0x0141},	// LATIN CAPITAL LETTER L WITH STROKE
	/* 14/09 */	{0xE9,	0x00D8},	// LATIN CAPITAL LETTER O WITH STROKE
	/* 14/10 */	{0xEA,	0x0152},	// LATIN CAPITAL LIGATURE OE
	/* 14/11 */	{0xEB,	0x00BA},	// MASCULINE ORDINAL INDICATOR
	/* 14/12 */	{0xEC,	0x00DE},	// LATIN CAPITAL LETTER THORN
	/* 14/13 */	{0xED,	0x0166},	// LATIN CAPITAL LETTER T WITH STROKE
	/* 14/14 */	{0xEE,	0x014A},	// LATIN CAPITAL LETTER ENG
	/* 14/15 */	{0xEF,	0x0149},	// LATIN SMALL LETTER N PRECEDED BY APOSTROPHE (DejaVu only)

	/* 15/00 */	{0xF0,	0x0138},	// LATIN SMALL LETTER KRA
	/* 15/01 */	{0xF1,	0x00E6},	// LATIN SMALL LETTER AE
	/* 15/02 */	{0xF2,	0x0111},	// LATIN SMALL LETTER D WITH STROKE
	/* 15/03 */	{0xF3,	0x00F0},	// LATIN SMALL LETTER ETH
	/* 15/04 */	{0xF4,	0x0127},	// LATIN SMALL LETTER H WITH STROKE
	/* 15/05 */	{0xF5,	0x0131},	// LATIN SMALL LETTER DOTLESS I
	/* 15/06 */	{0xF6,	0x0133},	// LATIN SMALL LETTER LIGATURE IJ (DejaVu only)
	/* 15/07 */	{0xF7,	0x0140},	// LATIN SMALL LETTER L WITH MIDDLE DOT (DejaVu only)
	/* 15/08 */	{0xF8,	0x0142},	// LATIN SMALL LETTER L WITH STROKE
	/* 15/09 */	{0xF9,	0x00F8},	// LATIN SMALL LETTER O WITH STROKE
	/* 15/10 */	{0xFA,	0x0153},	// LATIN SMALL LIGATURE OE
	/* 15/11 */	{0xFB,	0x00DF},	// LATIN SMALL LETTER SHARP S
	/* 15/12 */	{0xFC,	0x00FE},	// LATIN SMALL LETTER THORN
	/* 15/13 */	{0xFD,	0x0167},	// LATIN SMALL LETTER T WITH STROKE
	/* 15/14 */	{0xFE,	0x014B},	// LATIN SMALL LETTER ENG
	/* 15/15 */	{0xFF,	0x00AD},	// SOFT HYPHEN
};


/*******************************************************************/
/********************      Defines         *************************/
/*******************************************************************/



/*******************************************************************/
/********************      Typedef         *************************/
/*******************************************************************/


/*******************************************************************/
/********************      Static Variables     ********************/
/*******************************************************************/
#define __________________________CODEPAGE_TO_UCS2__________________________________________



#if 0
STATIC HERROR	local_mw_cp_Convert6937ToUCS2(const CH_6937 *str6937, const HUINT16 str6937Len, HUINT16 *usedByte, CH_UCS2 *ucs2Str, HUINT16 *ucs2StrLen)
{
	HUINT16		i=0;
	HUINT16		usDeltaValue=0;
	HUINT16		usConvertedCharacterCount=0;
	HUINT16		usDiacriticalMark=0;
	HUINT8		cDvbCh=0;
	HINT16 		sCodeIndex=0;

	CHARMAPITEM_toUnicode 			*pCurISOmap=NULL;
	ConvEncoding_Err_t	hResErr=ERR_FAIL;

	HxLOG_Assert(str6937);
	HxLOG_Assert(ucs2Str);

	HxLOG_Info("local_font_Convert6937ToUCS2 str6937Len(%d)\n", str6937Len);

	*usedByte=0;
	*ucs2StrLen=0;

	if(str6937Len==0)
	{
		/* check number to converte */
		HxLOG_Info("local_font_Convert6937ToUCS2() error: demand length is Zero -\n");

		return ERR_OK;
	}

	if(str6937==NULL||ucs2Str==NULL)
	{
		/* str6937 storage check */
		HxLOG_Info("local_font_Convert6937ToUCS2 error: storage is NULL\n");

		return ERR_FAIL;
	}

	/* set code page */
	if(str6937[0]>=0x20) //&& (str6937[0]<=0xff))
	{
		pCurISOmap=ISO_6937_PAGE01_TO_UNICODE;
	}
	else if(str6937[0]>0x00&&str6937[0]<=0x1f)
	{
		/* code is in reserved area, ERROR occurred */
		HxLOG_Info("local_font_Convert6937ToUCS2()1 error: NOT supported code page -\n");

		return ERR_NOT_SUPPORTED_CODEPAGE;
	}
	else
	{
		/* here is NULL case, nothing to do */
		return ERR_NULL_CH;
	}

	/* to calc array sCodeIndex using character code */
	usDeltaValue=0x0000|pCurISOmap[0].ucISOCode;

	/* dvb 스트링 길이에 맨앞자리 컨트롤 바이트도 포함? */
	for(i=0; i<str6937Len; i++)
	{
		cDvbCh=str6937[i];

		if(cDvbCh==0x00)
		{
			hResErr=ERR_NULL_CH;
			break;
		}
		else if(cDvbCh<0x20)
		{
			hResErr=ERR_WHITE_CH;
			*(ucs2Str+usConvertedCharacterCount)=cDvbCh;

			continue;
		}
		else if(cDvbCh<0x7f)
		{
			*(ucs2Str+usConvertedCharacterCount)=cDvbCh;
		}
		else if((cDvbCh >= 0x7f) && (cDvbCh <= 0x9f))
		{
			/* nothing to do */
			hResErr=ERR_CONTROL_CH;

			continue;
		}
		else /* 0xa0 ~ 0xff */
		{
			sCodeIndex=cDvbCh-usDeltaValue;
			if(sCodeIndex<0)
			{
				/* it's a control code, 0x7f~0x9f */
				hResErr=ERR_WHITE_CH;

				continue;
			}
			else if((cDvbCh&0xf0)==0xc0)				// dvdCh : 0xc0 ~ 0xCF
			{
				usDiacriticalMark = cDvbCh - 0xC0;		// 0 ~ 15 : 알파벳과 같이 붙는 발음 표기들
				i++;	// next character is needed
				cDvbCh=str6937[i];
				if(cDvbCh>=0x41&&cDvbCh<=0x5A)
				{
					*(ucs2Str+usConvertedCharacterCount)=ISO6937_COMBINIG_CAPITAL_LETTER[cDvbCh-0x41][usDiacriticalMark];
				}
				else if(cDvbCh>=0x61&&cDvbCh<=0x7A)
				{
					*(ucs2Str+usConvertedCharacterCount)=ISO6937_COMBINIG_SMALL_LETTER[cDvbCh-0x61][usDiacriticalMark];
				}
				else
				{
					/* diacritical mark는 x advice가 0이다. */
					i--;
					*(ucs2Str+usConvertedCharacterCount) = ISO6937_UNICODE_TYPEFACE_COMBINE_WITH_SPACE[usDiacriticalMark];
				}
			}
			else
			{
				*(ucs2Str+usConvertedCharacterCount)=pCurISOmap[sCodeIndex].usUNICODE;
			}
		}
		HxLOG_Print("[u+%04x]count[%d]\n", *(ucs2Str+usConvertedCharacterCount), usConvertedCharacterCount);
		hResErr=ERR_OK;
		usConvertedCharacterCount++;
	}

	*usedByte=i;
	*ucs2StrLen=usConvertedCharacterCount;

	HxLOG_Info("local_font_Convert6937ToUCS2() result error(0x%x) -\n", hResErr);

	return hResErr;
}
#endif

STATIC HERROR	local_mw_cp_Convert6937ToUCS2(const CH_1BYTE *pStr6937, const HINT32 nStr6937Len, HINT32 *pnUsedByte, CH_UCS2 *pUCS2Str, HINT32 *pnUCS2StrLen)
{
	HINT32		i = 0;
	HINT32		nConvertedCharacterCount = 0;
	HINT32 		nCodeIndex = 0;
	HINT32		nLocaleCodeLen = 0;
	HBOOL				bIsLocaleCode = FALSE;
	CH_1BYTE			cDvbCh = 0;
	CH_UCS2				usDiacriticalMark = 0;
	ConvEncoding_Err_t	hResErr = ERR_FAIL;

	HxLOG_Assert(pStr6937);
	HxLOG_Assert(pUCS2Str);
	HxLOG_Info("local_mw_cp_Convert6937ToUCS2 nStr6937Len(%d)\n", nStr6937Len);

	if(nStr6937Len == 0)
	{
		/* check number to converte */
		HxLOG_Info("local_mw_cp_Convert6937ToUCS2() error: demand length is Zero -\n");

		return ERR_OK;
	}

	if((pStr6937 == NULL) || (pUCS2Str == NULL))
	{
		/* pStr6937 storage check */
		HxLOG_Info("local_mw_cp_Convert6937ToUCS2 error: storage is NULL\n");

		return ERR_FAIL;
	}

	/* check Locale Code */ /* 처음부터 locale code가 없고 0x20이상이면 8859_1이라고 생각한다. */
	if(! /*NOT*/((pStr6937[0] >= CH_1BYTE_EFFECTIVE_CH_START_VALUE)
		||	((nStr6937Len >= EN300468_LOCALE_CODE_MAX)
		&& (MWC_UTIL_IsEncodingValid(eHxCP_ISO_6937, pStr6937) == TRUE))))
	{
		return ERR_FAIL;
	}

	*pnUsedByte = 0;
	*pnUCS2StrLen = 0;

	/* init */
	nLocaleCodeLen = MWC_UTIL_GetLocaleCodeLen((const HUINT8 *)pStr6937);
	if(nLocaleCodeLen > 0)
	{
		bIsLocaleCode = TRUE;
	}

	/* Character Table 정보를 뺀 그 다음 실제 코드 위치 index from nLocaleCodeLen */
	for(i = nLocaleCodeLen; i < nStr6937Len; i++)
	{
		cDvbCh = pStr6937[i];

		/* 0x00 */
		if(cDvbCh == CH_1BYTE_NULL_CHARACTER)
		{
			hResErr = ERR_NULL_CH;
			break;
		}
		/* 0x01 ~ 0x1F */
		else if(cDvbCh < CH_1BYTE_EFFECTIVE_CH_START_VALUE)
		{
			hResErr = ERR_WHITE_CH;
#if DECODE_CHARACTER_COPY_WHITECH
			pUCS2Str[nConvertedCharacterCount] = cDvbCh;
#else
			continue;
#endif
		}
		/* 0x20 ~ 0x7E */
		else if(cDvbCh <= CH_1BYTE_ASCII_END_VALUE)
		{
			/* ascii position */
			pUCS2Str[nConvertedCharacterCount] = cDvbCh;
		}
		/* 0x7F ~ 0x9F */
		else if((cDvbCh >= CH_1BYTE_USERDEFINE_CODE_START_VALUE) && (cDvbCh <= CH_1BYTE_USERDEFINE_CODE_END_VALUE))
		{
			/* control ch position */
			/* 당장 emphasis 등을 어떤 문자로 바꾸지는 않는다. */
			/* nothing to do */
			hResErr = ERR_USERDEFINE_CH;

			continue;
		}
		/* 0xA0 ~ 0xFF */
		else
		{

			nCodeIndex = cDvbCh - ((CH_UCS2)(0x0000 | EN300468_FA1_TBL_TO_UNICODE[0].ucISOCode));

			if(nCodeIndex < 0)
			{
				/* it's a control code, 0x7f~0x9f */
				hResErr=ERR_WHITE_CH;

				continue;
			}
			else if((cDvbCh & 0xf0) == CH_1BYTE_6937_COMBINE_BYTE_VALUE)				// dvdCh : 0xc0 ~ 0xCF
			{
				usDiacriticalMark = cDvbCh - CH_1BYTE_6937_COMBINE_BYTE_VALUE;		// 0 ~ 15 : 알파벳과 같이 붙는 발음 표기들
				i++;	// next character is needed
				cDvbCh = pStr6937[i];
				if((cDvbCh >= CH_1BYTE_CAPITAL_LETTER_A_VALUE) && (cDvbCh <= CH_1BYTE_CAPITAL_LETTER_Z_VALUE))
				{
					pUCS2Str[nConvertedCharacterCount] = ISO6937_COMBINIG_CAPITAL_LETTER[cDvbCh - CH_1BYTE_CAPITAL_LETTER_A_VALUE][usDiacriticalMark];
				}
				else if((cDvbCh >= CH_1BYTE_SMALL_LETTER_A_VALUE) && (cDvbCh <= CH_1BYTE_SMALL_LETTER_Z_VALUE))
				{
					pUCS2Str[nConvertedCharacterCount] = ISO6937_COMBINIG_SMALL_LETTER[cDvbCh - CH_1BYTE_SMALL_LETTER_A_VALUE][usDiacriticalMark];
				}
				else
				{
					/* diacritical mark는 x advice가 0이다. */
					i--;
					pUCS2Str[nConvertedCharacterCount] = ISO6937_UNICODE_TYPEFACE_COMBINE_WITH_SPACE[usDiacriticalMark];
				}
			}
			else
			{
				/* to calc array nCodeIndex using character code */
				pUCS2Str[nConvertedCharacterCount] = EN300468_FA1_TBL_TO_UNICODE[nCodeIndex].usUNICODE;
			}

#if defined(CONFIG_DEBUG)	/* just debugging */
			if(EN300468_FA1_TBL_TO_UNICODE[nCodeIndex].ucISOCode != cDvbCh)
			{
				//HxLOG_Critical("\n\n");
			}
#endif
		}
		HxLOG_Print("[u+%04x]count[%d]\n", pUCS2Str[nConvertedCharacterCount], nConvertedCharacterCount);
		hResErr = ERR_ENCODING_OK;
		nConvertedCharacterCount++;
	}

	*pnUsedByte = i;
	*pnUCS2StrLen = nConvertedCharacterCount;

	HxLOG_Info("local_mw_cp_Convert6937ToUCS2() result error(0x%x) -\n", hResErr);

	return hResErr;
}


STATIC HERROR	local_mw_cp_Convert300468ToUCS2(const CH_1BYTE *pStr300468, const HINT32 nStr300468Len, HINT32 *pnUsedByte, CH_UCS2 *pUcs2Str, HINT32 *pnUcs2StrLen)
{
	HINT32		i=0;
	HUINT16		usCharStart = 0;
	HUINT16		usDeltaValue=0;
	HUINT16		usConvertedCharacterCount=0;
	HUINT16		usDiacriticalMark=0;
	HUINT8		cDvbCh=0;
	HINT16 		sCodeIndex=0;
	HUINT16		usIsControlCode=0;

	CHARMAPITEM_toUnicode 		*pCurISOmap=NULL;
	ConvEncoding_Err_t			hResErr=ERR_FAIL;

	HINT32						ulEncodingLen = 0;
	eHxCP_CodePage_e				eTextEncoding = eHCodepage_MAX;
	CPContext_t 				*pCPContext = NULL;


	HxLOG_Assert(pStr300468);
	HxLOG_Assert(pUcs2Str);

	HxLOG_Info("local_mw_cp_Convert300468ToUCS2 nStr300468Len(%d)\n", nStr300468Len);

	*pnUsedByte=0;
	*pnUcs2StrLen=0;

	if(nStr300468Len==0)
	{
		/* check number to converte */
		HxLOG_Info("local_mw_cp_Convert300468ToUCS2() error: demand length is Zero -\n");

		return ERR_OK;
	}

	if(pStr300468==NULL||pUcs2Str==NULL)
	{
		/* pStr300468 storage check */
		HxLOG_Info("local_mw_cp_Convert300468ToUCS2 error: storage is NULL\n");

		return ERR_FAIL;
	}


	MWC_UTIL_CodePage_GetEncodingWithLenByLocaleCode(pStr300468, &eTextEncoding, &ulEncodingLen, eHCodepage_MAX);

	switch(eTextEncoding)
	{
	case eHxCP_ISO_JAPAN_SJIS:
	case eHxCP_ISO_JAPAN_JIS:
	case eHxCP_ISO_6937:
	case eHxCP_UNICODE_UTF8:
	case eHxCP_UNICODE_DVB_UTF8:
	case eHxCP_UNICODE_UCS2:
	case eHxCP_WIN_1251:
//	case eHxCP_UNICODE_DVB_UCS2:
		pCPContext = MWC_UTIL_CodePage_GetContext(eTextEncoding);
		if(pCPContext == NULL)
		{
			return ERR_ENCODING_FAIL;
		}

		if(pCPContext->cbConvertCodepageToUCS2 != NULL)
		{
			return pCPContext->cbConvertCodepageToUCS2(pStr300468, nStr300468Len, pnUsedByte, pUcs2Str, pnUcs2StrLen);
		}
	default:
		break;
	}


	if(pStr300468[0]>=0x20) //&& (pStr300468[0]<=0xff))
	{
		pCurISOmap=EN300468_FA1_TBL_TO_UNICODE;
		usIsControlCode = CH_TBL_0X20_DEFAULT_TABLE;
		usCharStart = 0;
	}
	else if(pStr300468[0]>0x00&&pStr300468[0]<=0x1f)
	{
		if(pStr300468[0] <= 0x0B)
		{
			pCurISOmap=MWC_UTIL_CodePage_Get8859toUCS2Table(pStr300468[0]+4);
			if(pCurISOmap == NULL)
			{
				return ERR_FAIL;
			}
			HxLOG_Print("set 8859 page[%d]\n", pStr300468[0]+4);
			usCharStart = 1;
		}
		else if(pStr300468[0]==0x10)
		{
			if(pStr300468[1]==0x00&&nStr300468Len>=3)
			{
				if ((pStr300468[2] >=0x01 && pStr300468[2]<=0x0f))
				{
					pCurISOmap=MWC_UTIL_CodePage_Get8859toUCS2Table(pStr300468[2]);
					if(pCurISOmap == NULL)
					{
						return ERR_FAIL;
					}
					usIsControlCode = CH_TBL_0X10_TABLE;
					usCharStart = 3;
				}
				else
				{
					/* code is in reserved area, ERROR occurred */
					HxLOG_Info("local_mw_cp_Convert300468ToUCS2()2 error: NOT supported code page -\n");

					return ERR_NOT_SUPPORTED_CODEPAGE;
				}
			}
			else
			{
				/* code is in reserved area, ERROR occurred */
				HxLOG_Info("local_mw_cp_Convert300468ToUCS2()3 error: NOT supported code page -\n");

				return ERR_NOT_SUPPORTED_CODEPAGE;
			}
		}
		else if(pStr300468[0] == 0x11)		/* already UCS-2(BMP:Basic MultiLingual Plane) */
		{
			HUINT32	rest = 0;

			*pnUsedByte = nStr300468Len;
			rest = (nStr300468Len - 1) % 2;
			*pnUcs2StrLen = (nStr300468Len - 1 + rest)>>1;	/* delete pStr300468[0] */

			if(rest == 1)
			{
				HxSTD_memcpy(pUcs2Str, (pStr300468+1), (nStr300468Len-1)*sizeof(HUINT8));
				pUcs2Str[*pnUcs2StrLen - 1] = 0x0000;
			}
			else
			{
				HxSTD_memcpy(pUcs2Str, (pStr300468+1), (nStr300468Len-1)*sizeof(HUINT8));
			}

			return ERR_OK;
		}
		else /* 0x0C ~ 0x0F, 0x12 ~ 0x1F, except 0x15 */
		{
			/* code is in reserved area, ERROR occurred */
			HxLOG_Info("local_mw_cp_Convert300468ToUCS2()1 error: NOT supported code page -\n");

			return ERR_NOT_SUPPORTED_CODEPAGE;
		}
	}
	else
	{
		/* here is NULL case, nothing to do */
		return ERR_NULL_CH;
	}

	/* to calc array sCodeIndex using character code */
	usDeltaValue=0x0000|pCurISOmap[0].ucISOCode;

	// usCharStart : Table 정보를 뺀 그 다음 실제 코드 위치
	for(i=usCharStart; i<nStr300468Len; i++)
	{
		cDvbCh=pStr300468[i];

		if(cDvbCh==0x00)
		{
#if 0
			/* for 0x10 table */
			if((usIsControlCode == CH_TBL_0X10_TABLE) && ((i == 1) || (i == 2)))
			{
				/* no convert and eat character */
				hResErr=ERR_CONTROL_CH;
				continue;
			}
			else
			{
#endif
				hResErr=ERR_NULL_CH;
				break;	/* i == 0 first byte: 0x00 */
#if 0
			}
#endif
		}
		else if(cDvbCh<0x20)
		{
			if(i==0)
			{
				/* ch for 8859 character coding table, i = 0, ch < 0x20 */
				hResErr=ERR_CONTROL_CH;
			}
			else
			{
#if DECODE_CHARACTER_COPY_WHITECH
				*(pUcs2Str+usConvertedCharacterCount)=cDvbCh;
#else
				hResErr=ERR_WHITE_CH;
				continue;
#endif
			}
			continue;
		}
		else if(cDvbCh<0x7f)
		{
			/* ascii position */
			*(pUcs2Str+usConvertedCharacterCount)=cDvbCh;
		}
		else if((cDvbCh >= 0x7f) && (cDvbCh <= 0x9f))
		{
#if defined(CONFIG_OP_APS) || defined(CONFIG_OP_SKYD) || defined(CONFIG_OP_KDG)
			if(cDvbCh == 0x80)
			{
				/* 이게 뭔짓인고 하니, 독일에서 euro symbol을 0x80으로 보낸단다.
				그래서 독일향 APS일 경우 0x80을 euro로 정상 처리 한다.
				*/
				*(pUcs2Str+usConvertedCharacterCount) = 0x20AC;	//euro symbol
			}
			else
#endif
			{
				/* control ch position */
				/* 당장 emphasis 등을 어떤 문자로 바꾸지는 않는다. */
				/* nothing to do */
				hResErr=ERR_CONTROL_CH;
			}

			continue;
		}
		else	/* 0xa0 ~ 0xff */
		{
			/* 0xc0 */
			sCodeIndex=cDvbCh-usDeltaValue;
			if((usIsControlCode == CH_TBL_0X20_DEFAULT_TABLE) && ((cDvbCh&0xf0)==0xc0))		// cDvbCh : 0xC0 ~ 0xCF
			{
				usDiacriticalMark = cDvbCh - 0xc0;		// 0 ~ 15 : 알파벳과 같이 붙는 발음 표기들
				i++;	// next character is needed
				cDvbCh=pStr300468[i];
				if(cDvbCh>=0x41&&cDvbCh<=0x5A)
				{
					*(pUcs2Str+usConvertedCharacterCount)=ISO6937_COMBINIG_CAPITAL_LETTER[cDvbCh-0x41][usDiacriticalMark];
				}
				else if(cDvbCh>=0x61&&cDvbCh<=0x7A)
				{
					*(pUcs2Str+usConvertedCharacterCount)=ISO6937_COMBINIG_SMALL_LETTER[cDvbCh-0x61][usDiacriticalMark];
				}
				else
				{
					/* diacritical mark는 x advice가 0이다. */
					i--;
					*(pUcs2Str+usConvertedCharacterCount) = ISO6937_UNICODE_TYPEFACE_COMBINE_WITH_SPACE[usDiacriticalMark];
				}
			}
			else
			{
				/* 0xa0 ~ 0xff, except 0xc0 */
				*(pUcs2Str+usConvertedCharacterCount)=pCurISOmap[sCodeIndex].usUNICODE;
			}
		}
		HxLOG_Print("[u+%04x]count[%d]\n", *(pUcs2Str+usConvertedCharacterCount), usConvertedCharacterCount);
		hResErr=ERR_OK;
		usConvertedCharacterCount++;
	}

	*pnUsedByte=i;
	*pnUcs2StrLen=usConvertedCharacterCount;

	HxLOG_Info("local_mw_cp_Convert300468ToUCS2() result error(0x%x) -\n", hResErr);

	return hResErr;
}


#define __________________________UCS2_TO_CODEPAGE___________________________________________

STATIC HERROR	local_mw_cp_ConvertUCS2To6937(const CH_UCS2 *pSrcUCS2Str, const HINT32 nSrcUCS2StrLen, const HINT32 nBufferLen, HINT32 *pnUsedByte, CH_1BYTE *pDest6937Str, HINT32 *pnDest6937StrLen)
{
	HINT32			iter = 0;
	HINT32			letter_idx = 0, combine_idx = 0;
	HINT32			nNumOfConvertedCh = 0;
	HBOOL			bFound = FALSE;
	CH_1BYTE		szlocaleCode[EN300468_LOCALE_CODE_MAX] = { 0x10, 0x69, 0x37 };

	HxLOG_Assert(pSrcUCS2Str);
	HxLOG_Assert(pDest6937Str);

	HxLOG_Info("local_mw_cp_ConvertUCS2To6937() nSrcUCS2StrLen(%d) +\n", nSrcUCS2StrLen);

	memcpy(pDest6937Str, szlocaleCode, EN300468_LOCALE_CODE_MAX);
	nNumOfConvertedCh = EN300468_LOCALE_CODE_MAX;

	for(iter = 0; iter < nSrcUCS2StrLen; iter++)
	{
		if(pSrcUCS2Str[iter] >= 0x00A0)
		{
			bFound = FALSE;

			for(letter_idx = 0; letter_idx < ALPHA_CASE_NUM; letter_idx++)
			{
				for (combine_idx = 0; combine_idx < NON_SPACING_CHA_NUM; combine_idx++)
				{
					if (ISO6937_COMBINIG_CAPITAL_LETTER[letter_idx][combine_idx] == pSrcUCS2Str[iter])
					{
						pDest6937Str[nNumOfConvertedCh++] = combine_idx + CH_1BYTE_6937_COMBINE_BYTE_VALUE;
						pDest6937Str[nNumOfConvertedCh++] = letter_idx + CH_1BYTE_CAPITAL_LETTER_A_VALUE;
						bFound = TRUE;
						break;
					}

					if (ISO6937_COMBINIG_SMALL_LETTER[letter_idx][combine_idx] == pSrcUCS2Str[iter])
					{
						pDest6937Str[nNumOfConvertedCh++] = combine_idx + CH_1BYTE_6937_COMBINE_BYTE_VALUE;
						pDest6937Str[nNumOfConvertedCh++] = letter_idx + CH_1BYTE_SMALL_LETTER_A_VALUE;
						bFound = TRUE;
						break;

					}
				}

				if(bFound == TRUE)	break;
			}

			if(bFound == TRUE)
			{
				(*pnUsedByte)++;
			}
		}
		else
		{
			pDest6937Str[nNumOfConvertedCh] = (pSrcUCS2Str[iter] & 0x00ff);
			nNumOfConvertedCh++;
			(*pnUsedByte)++;
		}
		if(nBufferLen < *pnUsedByte)
		{
			break;
		}
	}

	*pnDest6937StrLen = nNumOfConvertedCh;

	return ERR_OK;
}


#define __________________________Drawable___________________________________________


STATIC HERROR local_mw_cp_GetDrawableChar6937 (HUINT8 *szString, HUINT32 ulIndex,
												 HUINT8 *szCharWithCode, HUINT32 *pulCharLenWithCode,
												 HUINT8 *szCharOnly, HUINT32 *pulCharLenOnly)
{
	HUINT32		 ulCount, ulCharLen;
	HUINT8		*szPos;

	szPos = szString;

	for (ulCount = 0; ulCount < ulIndex; ulCount++)
	{
		if (szPos[0] == 0xc0)
		{
			szPos++;
		}

		if (szPos[0] == 0x00)
		{
			return ERR_FAIL;
		}

		szPos++;
	}

	if ((szPos[0] == 0x00) || (szPos[0] == 0xC0 && szPos[1] == 0x00))
	{
		return ERR_FAIL;
	}

	ulCharLen = (szPos[0] == 0xC0) ? 2 : 1;


	if (szCharWithCode != NULL)
	{
		HxSTD_memcpy (szCharWithCode, szPos, ulCharLen);
	}

	if (pulCharLenWithCode != NULL)
	{
		*pulCharLenWithCode = ulCharLen;
	}

	if (szCharOnly != NULL)
	{
		HxSTD_memcpy (szCharOnly, szPos, ulCharLen);
	}

	if (pulCharLenOnly != NULL)
	{
		*pulCharLenOnly = ulCharLen;
	}

	return ERR_OK;
}

STATIC HERROR local_mw_cp_CountDrawableCharNum6937 (HUINT8 *szString, HUINT32 *pulCharNum)
{
	HUINT32		 ulCount, ulCharNum;

	for (ulCount = 0, ulCharNum = 0; szString[ulCount] != '\0'; ulCount++)
	{
		if (szString[ulCount] != 0xc0)
		{
			ulCharNum ++;
		}
	}

	*pulCharNum = ulCharNum;
	return ERR_OK;
}


STATIC HERROR local_mw_cp_CountDrawableCharNum300468 (HUINT8 *szString, HUINT32 *pulCharNum)
{
	HINT32			ulCount = 0;
	eHxCP_CodePage_e eEncoding = eHCodepage_MAX;
	HERROR		hErr = ERR_FAIL;
	CPContext_t *pCPContext = NULL;

	MWC_UTIL_CodePage_GetEncodingWithLenByLocaleCode(szString, &eEncoding, &ulCount, eHxCP_ISO_6937);

	pCPContext = MWC_UTIL_CodePage_GetContext(eEncoding);
	if(pCPContext == NULL)
	{
		return ERR_ENCODING_FAIL;
	}

	if(pCPContext->cbCountDrawableCharNum != NULL)
	{
		hErr= pCPContext->cbCountDrawableCharNum(szString+ulCount, pulCharNum);
	}

	return hErr;
}


STATIC HERROR local_mw_cp_GetDrawableChar300468 (HUINT8 *szString, HUINT32 ulIndex,
												   HUINT8 *szCharWithCode, HUINT32 *pulCharLenWithCode,
												   HUINT8 *szCharOnly, HUINT32 *pulCharLenOnly)
{
	HUINT32			ulCharCodeLen = 0, ulCharLen = 0;
	HUINT8			*szPlaneStr = NULL;
	HUINT8			 szCharOut[8];
	HERROR			 hErr = ERR_FAIL;
	eHxCP_CodePage_e	 eTextEncoding = eHCodepage_MAX;
	CPContext_t 	*pCPContext = NULL;

	MWC_UTIL_CodePage_GetEncodingWithLenByLocaleCode(szString, &eTextEncoding, &ulCharCodeLen, eHxCP_ISO_6937);
	szPlaneStr = szString + ulCharCodeLen;

	pCPContext = MWC_UTIL_CodePage_GetContext(eTextEncoding);
	if(pCPContext == NULL)
	{
		return ERR_ENCODING_FAIL;
	}

	if(pCPContext->cbGetDrawableChar != NULL)
	{
		hErr = pCPContext->cbGetDrawableChar(szPlaneStr, ulIndex, NULL, NULL, szCharOut, &ulCharLen);
	}

	if (hErr != ERR_OK)
	{
		return ERR_FAIL;
	}

	// Character Code 포함한 Character
	if (szCharWithCode != NULL)
	{
		if (ulCharCodeLen != 0)
		{
			HxSTD_memcpy (szCharWithCode, szString, ulCharCodeLen);
		}

		HxSTD_memcpy (szCharWithCode + ulCharCodeLen, szCharOut, ulCharLen);
	}

	// Character Code 포함한 Character Length
	if (pulCharLenWithCode != NULL)
	{
		*pulCharLenWithCode = ulCharCodeLen + ulCharLen;
	}

	// Character Code 뺀 Character
	if (szCharOnly != NULL)
	{
		HxSTD_memcpy (szCharOnly, szCharOut, ulCharLen);
	}

	// Character Code 뺀 Character Length
	if (pulCharLenOnly != NULL)
	{
		*pulCharLenOnly = ulCharLen;
	}

	return ERR_OK;
}


#define _________________________EmphasizedString________________________________________


STATIC HERROR local_mw_cp_GetEmphasizedStringFrom6937String (HUINT8 *szSrcStr, HUINT8 *szDstStr)
{
	HBOOL		 bStartMakeEmphasizedCode = FALSE;
	HBOOL		 bEndMakeEmphasizedCode = FALSE;
	HBOOL		 bEmphasis;


	bEmphasis = FALSE;


	while (*szSrcStr != '\0')
	{
		if (bEmphasis == FALSE)
		{
			if (*szSrcStr == CHAR_EMPHASIS_ON)
			{
				bEmphasis = TRUE;
				bStartMakeEmphasizedCode = TRUE;
			}
		}
		else
		{
			if (*szSrcStr == CHAR_EMPHASIS_OFF)
			{
				bEmphasis = FALSE;
				if (bStartMakeEmphasizedCode == TRUE)
				{
					bEndMakeEmphasizedCode = TRUE;
				}
				continue;
			}

			*szDstStr = *szSrcStr;
			szDstStr ++;
		}

		szSrcStr ++;
	}

	/* at least one emphasized word needed */
	if (bStartMakeEmphasizedCode == TRUE && bEndMakeEmphasizedCode == TRUE)
	{
		*szDstStr = '\0';
		return ERR_OK;
	}
	else
	{
		return ERR_FAIL;
	}
}


HERROR local_mw_cp_GetEmphasizedStringFrom300468String (HUINT8 *szSrcStr, HUINT8 *szDstStr)
{
	HERROR		 	hErr = ERR_FAIL;
	HINT32			ulEncodingLen = 0;
	eHxCP_CodePage_e eEncoding = eHCodepage_MAX;
	CPContext_t		*pCPContext = NULL;

	if (szSrcStr == NULL || szDstStr == NULL)	{ return ERR_FAIL; }

	MWC_UTIL_CodePage_GetEncodingWithLenByLocaleCode(szSrcStr, &eEncoding, &ulEncodingLen, eHxCP_ISO_6937);
	if(eEncoding == eHCodepage_MAX)
	{
		goto NO_EMPHASIZED_STRING;
	}

	pCPContext = MWC_UTIL_CodePage_GetContext(eEncoding);
	if(pCPContext == NULL)
	{
		return ERR_ENCODING_FAIL;
	}

	if(pCPContext->cbGetEmphasizedString != NULL)
	{
		HxSTD_memcpy(szDstStr, szSrcStr, ulEncodingLen);
		hErr = pCPContext->cbGetEmphasizedString(szSrcStr + ulEncodingLen, szDstStr + ulEncodingLen);
	}

	if (hErr == ERR_OK)
	{
		return ERR_OK;
	}

NO_EMPHASIZED_STRING :
	MWC_UTIL_DvbStrcpy (szDstStr, szSrcStr);
	return ERR_FAIL;
}


#define _________________________PUBLIC_FUNCTION__________________________________



HERROR MWC_UTIL_CodePage_Register6937With300468(void)
{
	MWC_UTIL_CodePage_Register(eHxCP_ISO_6937,
		local_mw_cp_CountDrawableCharNum6937, local_mw_cp_GetDrawableChar6937,
		local_mw_cp_Convert6937ToUCS2,
		local_mw_cp_ConvertUCS2To6937,
		local_mw_cp_GetEmphasizedStringFrom6937String,
		ISO_6937_PAGE01_TO_UNICODE);

	MWC_UTIL_CodePage_Register(eHxCP_ISO_300468,
		local_mw_cp_CountDrawableCharNum300468, local_mw_cp_GetDrawableChar300468,
		local_mw_cp_Convert300468ToUCS2,
		NULL,
		local_mw_cp_GetEmphasizedStringFrom300468String,
		EN300468_FA1_TBL_TO_UNICODE);

	return ERR_OK;
}

