obj-$(CONFIG_MWC_CODEPAGE_JAPAN) += codepage_jp.o
obj-$(CONFIG_MWC_ARABIC_CHARCODE) += codepage_arabic.o
obj-$(CONFIG_MWC_CODEPAGE_WINCP) += codepage_wincp.o
obj-y += codepage_6937n300468.o
obj-y += codepage_8859.o
obj-y += codepage_ascii.o
obj-y += codepage_ucs2.o
obj-y += codepage_utf8.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw
# Additional include path

