obj-y									+= init/
obj-y									+= antenna/
obj-y									+= actionmanager/
obj-y									+= output/
obj-y									+= svclist/
obj-y									+= tplist/
obj-y									+= live/
obj-y									+= search/
obj-y									+= resourcemap/
obj-y									+= cas/
obj-y									+= epg/
obj-y									+= swup/
obj-y									+= schedule/
obj-$(CONFIG_MW_MULTIMEDIA)				+= pvr/
obj-$(CONFIG_MW_MULTIMEDIA)				+= recorder/
obj-$(CONFIG_MW_MULTIMEDIA)				+= playback/
obj-$(CONFIG_MW_MULTIMEDIA)				+= transcoder/
obj-$(CONFIG_MW_MULTIMEDIA)				+= satip/
obj-$(CONFIG_HOMMA_RC)					+= remotecontrol/
obj-$(CONFIG_MW_MULTIMEDIA)				+= ntls/

obj-y									+= storage/
obj-$(CONFIG_MW_MULTIMEDIA)				+= media/

obj-y									+= logcapture/

obj-$(CONFIG_APCORE_EMM_UPDATE)			+= emmupdate/
obj-y									+= time/
obj-y									+= coldboot/
obj-y									+= frontcontrol/

obj-$(CONFIG_MW_INET_SNMP)				+= snmp_mib/
obj-y									+= setting/
obj-y									+= spec/
obj-y									+= parentalguidance/
obj-y									+= 3rdparty/

obj-$(CONFIG_MW_DYNAMIC_UPDATE)			+= dynamicupdate/
obj-y									+= epgbgtracking/
obj-$(CONFIG_MW_EPG_GATHERING)			+= epggathering/
obj-y									+= liveota/
obj-$(CONFIG_MW_SATRECORD)				+= satrecord/
obj-y									+= param/
obj-y									+= copyrightcontrol/
obj-y									+= models/
obj-$(CONFIG_MW_HDD_FORMAT_JIGSW)		+= hddformatjig/
obj-$(CONFIG_MW_SI_AIT)					+= hbbtv/
