#include "nexus_platform.h"
/*#include "nexus_gpio_module.h"*/
#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"

const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
	/*GPIO*/
/*/////////////   0 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 000 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*//////////////  10 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 010 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 018 #EBI_CS0b */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*//////////////  20 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 020 #EBI_CS2b */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// GPIO 023 SC0_VCC_SEL */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 025 EBI_DATA0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
/*//////////////  30 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 030 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 032 EBI_DATA7 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*//////////////  40 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 040 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 041 #NAND_RE */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 042 #NAND_WE*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 043 NAND_ALE */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 044 NAND_CLE */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 045 NAND_RDY_#BSY*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*//////////////  50 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 050 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 055 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*//////////////  60 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 060 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 065 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*//////////////  70 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 070 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 075 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 079 SC0_VCC */
/*//////////////  80 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 080 SC0_CLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 081 SC0_RST */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 082 SC0_DATA */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 083 SC0_PRES */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// GPIO 084 SC0_AUX_1 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// GPIO 085 SC0_AUX_2 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 086 */
	HUMAX_GPIO_FUNCTION_ALT2,	/*// GPIO 087 DEBUG_TXD */
	HUMAX_GPIO_FUNCTION_ALT2,	/*// GPIO 088 DEBUG_RXD */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*//////////////  90 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 090 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	/****** GPIO 95**** */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*////////////// 100 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 100 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// GPIO 101 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 102 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 103 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 104 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// GPIO 105 */
	/****** GPIO 106*** */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*////////////// 110 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 110 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 115 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*////////////// 120 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 120 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 124 */

/*SGPIOs*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// SGPIO 00 BSC_M0_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// SGPIO 01 BSC_M0_SDA */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// SGPIO 02 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// SGPIO 03 */

/*AON_GPIOs*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 00 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 01 */
	/****** AON_GPIO 02**** */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 03 KEY_POWER */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 04 #AUD_MUTE */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 06 LED_STBY_on */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 07 LED_STBY_off */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */ 
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 10 AON_GP10_STRAP_HIPASS_XTAL */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 11 AON_GP11_XCORE_BIAS_SEL_2 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 13 GP_LNA_SW */
	HUMAX_GPIO_FUNCTION_ALT5,	/*// AON_GPIO 14 USB0_PWRFLT2 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 15 FBO_SCART*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 16 SLB1_SCART*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 17 SLB2_SCART */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */

/*AON_SGPIOs*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* AON_SGPIO 00 BSC_M3_SCL */
	HUMAX_GPIO_FUNCTION_ALT1	/*//  */ /* AON_SGPIO 01 BSC_M3_SDA */
};

HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
	/*GPIO*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_00_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_01_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_02_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_03_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_04_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_05_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_06_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_06_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_07_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_07_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_08_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_08_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_09_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_09_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_10_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_10_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_11_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_11_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_12_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_12_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_13_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_13_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_14_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_14_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_15_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_15_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_16_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_16_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_17_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_17_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_18_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_18_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_19_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_19_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_20_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_20_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_21_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_21_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_22_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_22_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_23_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_23_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_24_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_24_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_25_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_25_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_26_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_26_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_27_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_27_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_28_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_28_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_29_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_29_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_30_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_30_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_31_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_31_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_32_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_32_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_33_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_33_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_34_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_34_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_35_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_35_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_36_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_36_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_37_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_37_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_38_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_38_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_39_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_39_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_40_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_40_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_41_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_41_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_42_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_42_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_43_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_43_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_44_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_44_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_45_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_45_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_46_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_46_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_47_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_47_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_48_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_48_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_49_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_49_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_50_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_50_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_51_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_51_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_52_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_52_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_53_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_53_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_54_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_54_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_55_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_55_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_56_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_56_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_57_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_57_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_58_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_58_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_59_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_59_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_60_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_60_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_61_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_61_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_62_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_62_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_63_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_63_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_64_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_64_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_65_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_65_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_66_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_66_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_67_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_67_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_68_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_68_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_69_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_69_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_70_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_70_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_72_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_72_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_73_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_73_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_74_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_74_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_75_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_75_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_76_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_76_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_77_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_77_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_78_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_78_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_79_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_79_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_80_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_80_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_81_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_81_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_82_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_82_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_83_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_83_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_84_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_84_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_85_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_85_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_86_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_86_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_87_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_87_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_88_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_88_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_89_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_89_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_90_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_90_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_91_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_91_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_92_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_92_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_93_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_93_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_94_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_94_SHIFT},
	/*{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, 0, 0},*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_96_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_96_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_97_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_97_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_98_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_98_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_99_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_99_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_100_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_100_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_101_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_101_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_102_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_102_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_103_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_103_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_104_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_104_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_105_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_105_SHIFT},
	/*{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, 0, 0},*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_107_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_107_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_108_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_108_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_109_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_109_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_110_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_110_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_111_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_111_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_112_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_112_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_113_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_113_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_114_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_114_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_115_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_115_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_116_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_116_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_117_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_117_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_118_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_118_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_119_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_119_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_120_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_120_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_121_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_121_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_122_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_122_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_123_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_123_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_124_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_124_SHIFT},

	 /*SGPIO*/
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_01_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_02_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_03_SHIFT},
	
	/* AON_GPIO and AON_SGPIO */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
	/*{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, 0, 0},*/
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_14_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_01_SHIFT}
};

