obj-y += detect/
obj-y += download/
obj-y += install/

obj-y += mgr_swup_info.o
obj-y += mgr_swup.o
obj-y += mgr_swup_ip.o
obj-y += mgr_swup_usb.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr

# Additional include path
ccflags-y += -I$(OCTO_TVMANAGER_DIR)/include_plugin

