#!/bin/sh

	umount /var/lib/humaxtv
	umount /var/lib/humaxtv_backup
	umount /var/lib/humaxtv_user
	ubidetach -m 7
	ubiformat -y /dev/mtd7
	ubiattach -m 7
	ubimkvol /dev/ubi1 -N dbbackup -s 4MiB
	ubimkvol /dev/ubi1 -N dbdata -s 4MiB
	ubimkvol /dev/ubi1 -N dbuser -s 28MiB	
	ubidetach -m 7
