# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =                 \
    lib                   \
    no_stack_protector    \

include $(PLAYREADY_DIR)/GNUmakefile.common

