#
obj-y += tmbslHCDP.o
obj-y += tmbslHCDP_Advanced.o
obj-y += tmbslHCDP_Instance.o
obj-y += tmbslHCDP_Reg.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/dp10025/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/dp10025/tmbslHCDP/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/dp10025/tmbslHCDP/src

