#
obj-y := i2c/
obj-y += sony_cxd2820_version.o
obj-y += sony_dvb.o
obj-y += sony_dvb_cxd2820.o
obj-y += sony_dvb_demod.o
obj-y += sony_dvb_demod_monitor.o
obj-y += sony_dvb_demod_monitorC.o
obj-y += sony_dvb_demod_monitorT.o
obj-y += sony_dvb_demod_monitorT2.o
obj-y += sony_dvb_i2c.o
obj-y += sony_dvb_math.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/ds2820/include
