obj-$(CONFIG_MW_INET) += nx_prism_menu_network.o
obj-$(CONFIG_MW_INET) += nx_prism_menu_lan.o
obj-$(CONFIG_MW_INET_WLAN) += nx_prism_menu_wlan.o
obj-$(CONFIG_MW_INET) += nx_prism_menu_connection_status.o
# Additional include path
ccflags-y += -I../../../../../../../make/include

