obj-y += nx_core_antenna.o
obj-y += nx_core_sat_tp_data.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include
ccflags-y += -I$(NATIVEAPP_CORE_INCLUDE_DIR)/include

# Additional include path
ccflags-y += -I$(NATIVEAPP_PORT_INCLUDE_DIR)/include