#
obj-y := drvi2c_feusb.o
obj-y += i2c_feusb.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/ds2820/src/i2c
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/ds2820/include