# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

#pass0: $(PLAYREADY_DIR)/../inc/drmbuild_linux.h

#$(PLAYREADY_DIR)/../inc/drmbuild_linux.h: $(PLAYREADY_ROOT)/$(PLAYREADY_PROFILE) $(PLAYREADY_ROOT)/DrmProfileCompileTimeOptions.mk
#	@echo Making $@... 1>&2
#	@perl $(PLAYREADY_DIR)/../profile/make_profile_header.pl $(PLAYREADY_ROOT)/$(PLAYREADY_PROFILE) $(PLAYREADY_ROOT)/DrmProfileCompileTimeOptions.mk $(PLAYREADY_DIR)/../profile/drmprofile_h_template.txt > $(PLAYREADY_DIR)/../inc/drmbuild_linux.h

#clean:
#	@if [ -e $(PLAYREADY_DIR)/../inc/drmbuild_linux.h ]; then \
#		echo Cleaning $(PLAYREADY_DIR)/../inc/drmbuild_linux.h... 1>&2; \
#		rm $(PLAYREADY_DIR)/../inc/drmbuild_linux.h; \
#	fi

include $(PLAYREADY_DIR)/GNUmakefile.common

