/***************************************************************************
 *     Copyright (c) 2005-2013, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * [File Description:]
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/
#ifndef _BWFE_4552_PRIV_H__
#define _BWFE_4552_PRIV_H__

#include "bchp_leap_l1.h"
#include "bchp_aif_mdac_cal_odu_core0.h"
#include "bchp_aif_mdac_cal_odu_core_intr2_0.h"
#include "bchp_aif_mdac_cal_odu_ana.h"
#include "bchp_aif_wb_odu_core0_0.h"
#include "bchp_aif_wb_odu_core_intr2_0_0.h"
#include "bchp_aif_wb_odu_ana_0.h"


#define BWFE_BYPASS_DGS
#define BWFE_BYPASS_LIC
/*#define BWFE_BYPASS_LIC2*/
#define BWFE_BYPASS_INL

#ifndef BWFE_HYBRID_ADC
#define BWFE_BYPASS_EQU
#endif

#define BWFE_G3_BUILD_VERSION 0x01
#define BWFE_NUM_CHANNELS     8     /* 1 input ADC x 8 */
#define BWFE_CHANNELS_MASK    0xFF
#define BWFE_NUM_REF_CHANNELS 1
#define BWFE_NUM_SLICES       2
#define BWFE_NUM_REF_SLICES   1
#define BWFE_NUM_LANES        2
#define BWFE_NUM_DMX_LANES    4
#ifdef BWFE_HYBRID_ADC
#define BWFE_NUM_MDACS        1
#else
#define BWFE_NUM_MDACS        2
#endif
#define BWFE_NUM_LIC_TAPS     16    /* TBD 16 taps per lane, no DCO tap */
#define BWFE_NUM_EQ_TAPS      4
#define BWFE_NUM_ADC_PHASES   8     /* TBD */
#define BWFE_XTAL_FREQ_KHZ    50223

#define BWFE_LIC_L            (BWFE_NUM_SLICES * BWFE_NUM_LANES * BWFE_NUM_DMX_LANES)
#define BWFE_LIC_S            8  /* TBD */

#define BWFE_DEF_FS_ADC_KHZ   5022300  /* Fs_adc = 5000MHz */
#define BWFE_DEF_FC_DPM_KHZ   2478788  /* Fc_dpm = 2478.788MHz */

#define BWFE_DEF_CHAN_HI_FS_ADC_KHZ 5022300  /* Fs_adc = 5022.32MHz */
#define BWFE_DEF_CHAN_LO_FS_ADC_KHZ 3138938  /* Fs_adc = 3138.95MHz */
#define BWFE_DEF_BAND_HI_FS_ADC_KHZ 4821408  /* Fs_adc = 4821.43MHz */
#define BWFE_DEF_BAND_LO_FS_ADC_KHZ 3214272  /* Fs_adc = 3214.29MHz */


/* wfe channel 0 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_0          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_0          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_0        BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* wfe channel 1 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_1          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_1          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_1        BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_0_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* wfe channel 2 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_2          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_2          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_2        BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* wfe channel 3 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_3          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_3          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_3        BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_3  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_3  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_3  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_3  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_1_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* wfe channel 4 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_4          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_4          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_4        BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_4  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_4  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_4  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_4  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* wfe channel 5 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_5          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_5          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_5        BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_5  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_5  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_5  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_5  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_2_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* wfe channel 6 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_6          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_6          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_6        BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_6  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_6  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_6  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_6  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_0_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* wfe channel 7 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_7          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_7          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_7        BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_7  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_7  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_7  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_7  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_WB_WRPR_3_1_INTR_SHIFT, BCHP_AIF_WB_ODU_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* mdac cal channel 0 interrupts */
#define BCHP_INT_ID_MDAC_CAL_TIMER0_0     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_MDAC_CAL_ODU_TOP_INTR_SHIFT, BCHP_AIF_MDAC_CAL_ODU_CORE_INTR2_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_MDAC_CAL_TIMER1_0     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_MDAC_CAL_ODU_TOP_INTR_SHIFT, BCHP_AIF_MDAC_CAL_ODU_CORE_INTR2_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_MDAC_CAL_CLPDTR_PO_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_MDAC_CAL_ODU_TOP_INTR_SHIFT, BCHP_AIF_MDAC_CAL_ODU_CORE_INTR2_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_MDAC_CAL_CLPDTR_PI_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_MDAC_CAL_ODU_TOP_INTR_SHIFT, BCHP_AIF_MDAC_CAL_ODU_CORE_INTR2_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)


/* WFE base registers */
#define BCHP_WFE_CORE_RSTCTL                       BCHP_AIF_WB_ODU_CORE0_0_RSTCTL
#define BCHP_WFE_CORE_HDOFFCTL0                    BCHP_AIF_WB_ODU_CORE0_0_HDOFFCTL0
#define BCHP_WFE_CORE_HDOFFCTL1                    BCHP_AIF_WB_ODU_CORE0_0_HDOFFCTL1
#define BCHP_WFE_CORE_HDOFFCTL2                    BCHP_AIF_WB_ODU_CORE0_0_HDOFFCTL2
#define BCHP_WFE_CORE_HDOFFSTS                     BCHP_AIF_WB_ODU_CORE0_0_HDOFFSTS
#define BCHP_WFE_CORE_DGSCTL2                      BCHP_AIF_WB_ODU_CORE0_0_DGSCTL2
#define BCHP_WFE_CORE_MDACSASTS                    BCHP_AIF_WB_ODU_CORE0_0_MDACSASTS
#define BCHP_WFE_CORE_DOUTCTL                      BCHP_AIF_WB_ODU_CORE0_0_DOUTCTL
//#define BCHP_WFE_CORE_LICCTL1                      BCHP_AIF_WB_SAT_CORE0_0_LICCTL1
//#define BCHP_WFE_CORE_LICCTL2                      BCHP_AIF_WB_SAT_CORE0_0_LICCTL2
//#define BCHP_WFE_CORE_LICCTL3                      BCHP_AIF_WB_SAT_CORE0_0_LICCTL3
//#define BCHP_WFE_CORE_LICCTL4                      BCHP_AIF_WB_SAT_CORE0_0_LICCTL4
//#define BCHP_WFE_CORE_LICCTL5                      BCHP_AIF_WB_SAT_CORE0_0_LICCTL5
//#define BCHP_WFE_CORE_LICCOEFD                     BCHP_AIF_WB_SAT_CORE0_0_LICCOEFD
//#define BCHP_WFE_CORE_LICCOEFA                     BCHP_AIF_WB_SAT_CORE0_0_LICCOEFA
//#define BCHP_WFE_CORE_LICCOEFEN                    BCHP_AIF_WB_SAT_CORE0_0_LICCOEFEN
#define BCHP_WFE_CORE_CORRINSEL                    BCHP_AIF_WB_ODU_CORE0_0_CORRINSEL
#define BCHP_WFE_CORE_CORRCTL                      BCHP_AIF_WB_ODU_CORE0_0_CORRCTL
#define BCHP_WFE_CORE_CORRFCW                      BCHP_AIF_WB_ODU_CORE0_0_CORRFCW
#define BCHP_WFE_CORE_CORRTHR                      BCHP_AIF_WB_ODU_CORE0_0_CORRTHR
#define BCHP_WFE_CORE_CORRFCWEN                    BCHP_AIF_WB_ODU_CORE0_0_CORRFCWEN
#define BCHP_WFE_CORE_CORRLEN0                     BCHP_AIF_WB_ODU_CORE0_0_CORRLEN0
#define BCHP_WFE_CORE_CORRLEN1                     BCHP_AIF_WB_ODU_CORE0_0_CORRLEN1
#define BCHP_WFE_CORE_TIMERCTL0                    BCHP_AIF_WB_ODU_CORE0_0_TIMERCTL0
#define BCHP_WFE_CORE_TIMERCTL1                    BCHP_AIF_WB_ODU_CORE0_0_TIMERCTL1
#define BCHP_WFE_CORE_AGCCTL2                      BCHP_AIF_WB_ODU_CORE0_0_AGCCTL2
#define BCHP_WFE_CORE_AGCDECRATE                   BCHP_AIF_WB_ODU_CORE0_0_AGCDECRATE
#define BCHP_WFE_CORE_AGCCTL1                      BCHP_AIF_WB_ODU_CORE0_0_AGCCTL1
#define BCHP_WFE_CORE_AGCTHRA1                     BCHP_AIF_WB_ODU_CORE0_0_AGCTHRA1
#define BCHP_WFE_CORE_REG_AGC_LF_INT_WDATA         BCHP_AIF_WB_ODU_CORE0_0_REG_AGC_LF_INT_WDATA
#define BCHP_WFE_CORE_REG_AGC_LA_INT_WDATA         BCHP_AIF_WB_ODU_CORE0_0_REG_AGC_LA_INT_WDATA
#define BCHP_WFE_CORE_REG_AGC_CTRL_LF_INT_WDATA    BCHP_AIF_WB_ODU_CORE0_0_REG_AGC_CTRL_LF_INT_WDATA
#define BCHP_WFE_CORE_REG_AGC_CTRL_LA_INT_WDATA    BCHP_AIF_WB_ODU_CORE0_0_REG_AGC_CTRL_LA_INT_WDATA
#define BCHP_WFE_CORE_AGCTHRA2                     BCHP_AIF_WB_ODU_CORE0_0_AGCTHRA2
#define BCHP_WFE_CORE_PGACLKCTL                    BCHP_AIF_WB_ODU_CORE0_0_PGACLKCTL
#define BCHP_WFE_CORE_PGALUTD                      BCHP_AIF_WB_ODU_CORE0_0_PGALUTD
#define BCHP_WFE_CORE_PGALUTA                      BCHP_AIF_WB_ODU_CORE0_0_PGALUTA
#define BCHP_WFE_CORE_NRNOTCHCTL                   BCHP_AIF_WB_ODU_CORE0_0_NRNOTCHCTL
#define BCHP_WFE_CORE_NRAGCTHR                     BCHP_AIF_WB_ODU_CORE0_0_NRAGCTHR
#define BCHP_WFE_CORE_NRDCOCTL_THR                 BCHP_AIF_WB_ODU_CORE0_0_NRDCOCTL_THR
#define BCHP_WFE_CORE_REG_NR_DCO_INT_WDATA_THR     BCHP_AIF_WB_ODU_CORE0_0_REG_NR_DCO_INT_WDATA_THR
#define BCHP_WFE_CORE_CORE_SW_SPARE0               BCHP_AIF_WB_ODU_CORE0_0_CORE_SW_SPARE0
#define BCHP_WFE_CORE_CORE_SW_SPARE1               BCHP_AIF_WB_ODU_CORE0_0_CORE_SW_SPARE1

/* WFE slice registers */
#define BCHP_WFE_CORE_DGSCTL_PI_SLC          BCHP_AIF_WB_ODU_CORE0_0_DGSCTL_PI_SLC0
#define BCHP_WFE_CORE_DGSCTL_PO_SLC          BCHP_AIF_WB_ODU_CORE0_0_DGSCTL_PO_SLC0
#define BCHP_WFE_CORE_DGSCLP_PI_SLC          BCHP_AIF_WB_ODU_CORE0_0_DGSCLP_PI_SLC0
#define BCHP_WFE_CORE_DGSCLP_PO_SLC          BCHP_AIF_WB_ODU_CORE0_0_DGSCLP_PO_SLC0
#define BCHP_WFE_CORE_DGSHIST_PI_SLC         BCHP_AIF_WB_ODU_CORE0_0_DGSHIST_PI_SLC0
#define BCHP_WFE_CORE_DGSHIST_PO_SLC         BCHP_AIF_WB_ODU_CORE0_0_DGSHIST_PO_SLC0
#define BCHP_WFE_CORE_DGSCLPCNT_PI_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSCLPCNT_PI_SLC0
#define BCHP_WFE_CORE_DGSCLPCNT_PO_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSCLPCNT_PO_SLC0
#define BCHP_WFE_CORE_DGSACCUM_PI_SLC        BCHP_AIF_WB_ODU_CORE0_0_DGSACCUM_PI_SLC0
#define BCHP_WFE_CORE_DGSACCUM_PO_SLC        BCHP_AIF_WB_ODU_CORE0_0_DGSACCUM_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT011_PI_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT011_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT010_PI_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT010_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT001_PI_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT001_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT000_PI_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT000_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT111_PI_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT111_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT110_PI_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT110_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT101_PI_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT101_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT100_PI_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT100_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT011_PO_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT011_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT010_PO_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT010_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT001_PO_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT001_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT000_PO_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT000_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT111_PO_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT111_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT110_PO_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT110_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT101_PO_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT101_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT100_PO_SLC       BCHP_AIF_WB_ODU_CORE0_0_DGSLUT100_PO_SLC0
#define BCHP_WFE_CORE_DGSLMS_SLC             BCHP_AIF_WB_ODU_CORE0_0_DGSLMS_SLC0
#define BCHP_WFE_CORE_DGSBGLMS_SLC           BCHP_AIF_WB_ODU_CORE0_0_DGSBGLMS_SLC0
#define BCHP_WFE_CORE_DGSLMSMU_SLC           BCHP_AIF_WB_ODU_CORE0_0_DGSLMSMU_SLC0
#define BCHP_WFE_CORE_DGSCOEFD_SLC           BCHP_AIF_WB_ODU_CORE0_0_DGSCOEFD_SLC0
#define BCHP_WFE_CORE_DGSCOEFA_SLC           BCHP_AIF_WB_ODU_CORE0_0_DGSCOEFA_SLC0
#define BCHP_WFE_CORE_DGSCOEFEN_SLC          BCHP_AIF_WB_ODU_CORE0_0_DGSCOEFEN_SLC0
#define BCHP_WFE_CORE_MDACSA_SLC             BCHP_AIF_WB_ODU_CORE0_0_MDACSA_SLC0
#define BCHP_WFE_CORE_MDACSADU_SLC           BCHP_AIF_WB_ODU_CORE0_0_MDACSADU_SLC0
#define BCHP_WFE_CORE_MDACSAOUT_SLC          BCHP_AIF_WB_ODU_CORE0_0_MDACSAOUT_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX0_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI0_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX0_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI1_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX0_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI0_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX0_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI1_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX1_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI0_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX1_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI1_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX1_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI0_DMX1_PO_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX1_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI1_DMX1_PO_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX2_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI0_DMX2_PI_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX2_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI1_DMX2_PI_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX2_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI0_DMX2_PO_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX2_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI1_DMX2_PO_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX3_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI0_DMX3_PI_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX3_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI1_DMX3_PI_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX3_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI0_DMX3_PO_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX3_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRI1_DMX3_PO_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX0_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ0_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX0_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ1_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX0_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ0_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX0_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ1_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX1_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ0_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX1_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ1_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX1_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ0_DMX1_PO_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX1_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ1_DMX1_PO_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX2_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ0_DMX2_PI_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX2_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ1_DMX2_PI_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX2_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ0_DMX2_PO_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX2_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ1_DMX2_PO_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX3_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ0_DMX3_PI_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX3_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ1_DMX3_PI_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX3_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ0_DMX3_PO_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX3_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRQ1_DMX3_PO_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX0_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP0_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX0_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP1_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX0_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP0_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX0_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP1_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX1_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP0_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX1_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP1_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX1_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP0_DMX1_PO_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX1_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP1_DMX1_PO_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX2_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP0_DMX2_PI_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX2_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP1_DMX2_PI_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX2_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP0_DMX2_PO_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX2_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP1_DMX2_PO_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX3_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP0_DMX3_PI_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX3_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP1_DMX3_PI_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX3_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP0_DMX3_PO_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX3_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_CORRP1_DMX3_PO_SLC0
#define BCHP_WFE_CORE_DGSEPCTL_SLC           BCHP_AIF_WB_ODU_CORE0_0_DGSEPCTL_SLC0
#define BCHP_WFE_CORE_REG_DGSEP_DMX0_PI_SLC_INT_WDATA    BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_DMX0_PI_SLC0_INT_WDATA
#define BCHP_WFE_CORE_REG_DGSEP_DMX0_PO_SLC_INT_WDATA    BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_DMX0_PO_SLC0_INT_WDATA
#define BCHP_WFE_CORE_REG_DGSEP_DMX1_PI_SLC_INT_WDATA    BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_DMX1_PI_SLC0_INT_WDATA
#define BCHP_WFE_CORE_REG_DGSEP_DMX1_PO_SLC_INT_WDATA    BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_DMX1_PO_SLC0_INT_WDATA
#define BCHP_WFE_CORE_REG_DGSEP_DMX2_PI_SLC_INT_WDATA    BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_DMX2_PI_SLC0_INT_WDATA
#define BCHP_WFE_CORE_REG_DGSEP_DMX2_PO_SLC_INT_WDATA    BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_DMX2_PO_SLC0_INT_WDATA
#define BCHP_WFE_CORE_REG_DGSEP_DMX3_PI_SLC_INT_WDATA    BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_DMX3_PI_SLC0_INT_WDATA
#define BCHP_WFE_CORE_REG_DGSEP_DMX3_PO_SLC_INT_WDATA    BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_DMX3_PO_SLC0_INT_WDATA
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX0_PI_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S1_DMX0_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX0_PI_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S2_DMX0_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX0_PO_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S1_DMX0_PO_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX0_PO_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S2_DMX0_PO_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX1_PI_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S1_DMX1_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX1_PI_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S2_DMX1_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX1_PO_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S1_DMX1_PO_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX1_PO_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S2_DMX1_PO_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX2_PI_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S1_DMX2_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX2_PI_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S2_DMX2_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX2_PO_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S1_DMX2_PO_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX2_PO_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S2_DMX2_PO_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX3_PI_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S1_DMX3_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX3_PI_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S2_DMX3_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX3_PO_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S1_DMX3_PO_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX3_PO_SLC_ERRP      BCHP_AIF_WB_ODU_CORE0_0_REG_DGSEP_S2_DMX3_PO_SLC0_ERRP
#define BCHP_WFE_CORE_NRDCOCTL_PI_SLC                    BCHP_AIF_WB_ODU_CORE0_0_NRDCOCTL_PI_SLC0
#define BCHP_WFE_CORE_REG_NR_DCO_INT_WDATA_PI_SLC        BCHP_AIF_WB_ODU_CORE0_0_REG_NR_DCO_INT_WDATA_PI_SLC0
#define BCHP_WFE_CORE_NRDCOCTL_PO_SLC                    BCHP_AIF_WB_ODU_CORE0_0_NRDCOCTL_PO_SLC0
#define BCHP_WFE_CORE_REG_NR_DCO_INT_WDATA_PO_SLC        BCHP_AIF_WB_ODU_CORE0_0_REG_NR_DCO_INT_WDATA_PO_SLC0
#define BCHP_WFE_CORE_NRNOTCHCTL_PI_SLC                  BCHP_AIF_WB_ODU_CORE0_0_NRNOTCHCTL_PI_SLC0
#define BCHP_WFE_CORE_REG_NR_NOTCH_INT_WDATA_PI_SLC      BCHP_AIF_WB_ODU_CORE0_0_REG_NR_NOTCH_INT_WDATA_PI_SLC0
#define BCHP_WFE_CORE_NRNOTCHCTL_PO_SLC                  BCHP_AIF_WB_ODU_CORE0_0_NRNOTCHCTL_PO_SLC0
#define BCHP_WFE_CORE_REG_NR_NOTCH_INT_WDATA_PO_SLC      BCHP_AIF_WB_ODU_CORE0_0_REG_NR_NOTCH_INT_WDATA_PO_SLC0
#define BCHP_WFE_CORE_NRAGCCTL_PI_SLC                    BCHP_AIF_WB_ODU_CORE0_0_NRAGCCTL_PI_SLC0
#define BCHP_WFE_CORE_REG_NR_AGC_LF_INT_WDATA_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_REG_NR_AGC_LF_INT_WDATA_PI_SLC0
#define BCHP_WFE_CORE_REG_NR_AGC_LA_INT_WDATA_PI_SLC     BCHP_AIF_WB_ODU_CORE0_0_REG_NR_AGC_LA_INT_WDATA_PI_SLC0
#define BCHP_WFE_CORE_NRAGCCTL_PO_SLC                    BCHP_AIF_WB_ODU_CORE0_0_NRAGCCTL_PO_SLC0
#define BCHP_WFE_CORE_REG_NR_AGC_LF_INT_WDATA_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_REG_NR_AGC_LF_INT_WDATA_PO_SLC0
#define BCHP_WFE_CORE_REG_NR_AGC_LA_INT_WDATA_PO_SLC     BCHP_AIF_WB_ODU_CORE0_0_REG_NR_AGC_LA_INT_WDATA_PO_SLC0

/* WFE analog base registers */
#define BCHP_WFE_ANA_RFFE_WRITER01              BCHP_AIF_WB_ODU_ANA_0_RFFE0_WRITER01
#define BCHP_WFE_ANA_RFFE_WRITER02              BCHP_AIF_WB_ODU_ANA_0_RFFE0_WRITER02
#define BCHP_WFE_ANA_RFFE_WRITER03              BCHP_AIF_WB_ODU_ANA_0_RFFE0_WRITER03
#define BCHP_WFE_ANA_ADC_CNTL0                  BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL0
#define BCHP_WFE_ANA_ADC_CNTL1                  BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL1
#define BCHP_WFE_ANA_ADC_CNTL2                  BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL2
#define BCHP_WFE_ANA_ADC_CNTL3                  BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL3
#define BCHP_WFE_ANA_ADC_CNTL4                  BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL4
#define BCHP_WFE_ANA_ADC_CNTL5                  BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL5
#define BCHP_WFE_ANA_ADC_CNTL6                  BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL6
#define BCHP_WFE_ANA_ADC_CNTL7                  BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL7
#define BCHP_WFE_ANA_ADC_CNTL8                  BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL8
#define BCHP_WFE_ANA_ADC_CNTL9                  BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL9
#define BCHP_WFE_ANA_ADC_CNTL10                 BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL10
#define BCHP_WFE_ANA_ADC_CNTL11                 BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL11
#define BCHP_WFE_ANA_ADC_CNTL12                 BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL12
#define BCHP_WFE_ANA_ADC_CNTL13                 BCHP_AIF_WB_ODU_ANA_0_ADC0_CNTL13
#define BCHP_WFE_ANA_PLL_CNTL0                  BCHP_AIF_WB_ODU_ANA_0_PLL_CNTL0
#define BCHP_WFE_ANA_PLL_CNTL1                  BCHP_AIF_WB_ODU_ANA_0_PLL_CNTL1
#define BCHP_WFE_ANA_PLL_CNTL2                  BCHP_AIF_WB_ODU_ANA_0_PLL_CNTL2
#define BCHP_WFE_ANA_PLL_CNTL3                  BCHP_AIF_WB_ODU_ANA_0_PLL_CNTL3
#define BCHP_WFE_ANA_PLL_CNTL4                  BCHP_AIF_WB_ODU_ANA_0_PLL_CNTL4
#define BCHP_WFE_ANA_PLL_CNTL5                  BCHP_AIF_WB_ODU_ANA_0_PLL_CNTL5
#define BCHP_WFE_ANA_PLL_CNTL6                  BCHP_AIF_WB_ODU_ANA_0_PLL_CNTL6
#define BCHP_WFE_ANA_PLL_CNTL7                  BCHP_AIF_WB_ODU_ANA_0_PLL_CNTL7
#define BCHP_WFE_ANA_SYS_CNTL                   BCHP_AIF_WB_ODU_ANA_0_SYS_CNTL0 
#define BCHP_WFE_ANA_PLL_STAT                   BCHP_AIF_WB_ODU_ANA_0_PLL_STAT
#define BCHP_WFE_ANA_CLK_CTRL                   BCHP_AIF_WB_ODU_ANA_0_CLK_CTRL_IN0
#define BCHP_WFE_ANA_PGA_GAIN                   BCHP_AIF_WB_ODU_ANA_0_PGA_GAIN_IN0
#define BCHP_WFE_ANA_SW_SPARE0                  BCHP_AIF_WB_ODU_ANA_0_SW_SPARE0
#define BCHP_WFE_ANA_SW_SPARE1                  BCHP_AIF_WB_ODU_ANA_0_SW_SPARE1

/* MDAC_CAL base registers */
#define BCHP_MDAC_CAL_CORE_RSTCTL               BCHP_AIF_MDAC_CAL_ODU_CORE0_RSTCTL
#define BCHP_MDAC_CAL_CORE_HDOFFCTL0            BCHP_AIF_MDAC_CAL_ODU_CORE0_HDOFFCTL0
#define BCHP_MDAC_CAL_CORE_HDOFFCTL1            BCHP_AIF_MDAC_CAL_ODU_CORE0_HDOFFCTL1
#define BCHP_MDAC_CAL_CORE_HDOFFSTS             BCHP_AIF_MDAC_CAL_ODU_CORE0_HDOFFSTS
#define BCHP_MDAC_CAL_CORE_DGSCTL2              BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSCTL2
#define BCHP_MDAC_CAL_CORE_MDACSASTS            BCHP_AIF_MDAC_CAL_ODU_CORE0_MDACSASTS
#define BCHP_MDAC_CAL_CORE_DOUTCTL              BCHP_AIF_MDAC_CAL_ODU_CORE0_DOUTCTL
#define BCHP_MDAC_CAL_CORE_TIMERCTL0            BCHP_AIF_MDAC_CAL_ODU_CORE0_TIMERCTL0
#define BCHP_MDAC_CAL_CORE_TIMERCTL1            BCHP_AIF_MDAC_CAL_ODU_CORE0_TIMERCTL1
#define BCHP_MDAC_CAL_CORE_SW_SPARE0            BCHP_AIF_MDAC_CAL_ODU_CORE0_CORE_SW_SPARE0
#define BCHP_MDAC_CAL_CORE_SW_SPARE1            BCHP_AIF_MDAC_CAL_ODU_CORE0_CORE_SW_SPARE1

/* MDAC_CAL slice registers */
#define BCHP_MDAC_CAL_CORE_DGSCTL_PI_SLC           BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSCTL_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCTL_PO_SLC           BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSCTL_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCLP_PI_SLC           BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSCLP_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCLP_PO_SLC           BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSCLP_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSHIST_PI_SLC          BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSHIST_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSHIST_PO_SLC          BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSHIST_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCLPCNT_PI_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSCLPCNT_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCLPCNT_PO_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSCLPCNT_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSACCUM_PI_SLC         BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSACCUM_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSACCUM_PO_SLC         BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSACCUM_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT011_PI_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT011_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT010_PI_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT010_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT001_PI_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT001_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT000_PI_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT000_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT111_PI_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT111_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT110_PI_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT110_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT101_PI_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT101_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT100_PI_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT100_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT011_PO_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT011_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT010_PO_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT010_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT001_PO_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT001_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT000_PO_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT000_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT111_PO_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT111_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT110_PO_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT110_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT101_PO_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT101_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT100_PO_SLC        BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLUT100_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLMS_SLC              BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLMS_SLC0
#define BCHP_MDAC_CAL_CORE_DGSBGLMS_SLC            BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSBGLMS_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLMSMU_SLC            BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSLMSMU_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCOEFD_SLC            BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSCOEFD_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCOEFA_SLC            BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSCOEFA_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCOEFEN_SLC           BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSCOEFEN_SLC0
#define BCHP_MDAC_CAL_CORE_MDACSA_SLC              BCHP_AIF_MDAC_CAL_ODU_CORE0_MDACSA_SLC0
#define BCHP_MDAC_CAL_CORE_MDACSADU_SLC            BCHP_AIF_MDAC_CAL_ODU_CORE0_MDACSADU_SLC0
#define BCHP_MDAC_CAL_CORE_MDACSAOUT_SLC           BCHP_AIF_MDAC_CAL_ODU_CORE0_MDACSAOUT_SLC0
#define BCHP_MDAC_CAL_CORE_DGSEPCTL_SLC            BCHP_AIF_MDAC_CAL_ODU_CORE0_DGSEPCTL_SLC0
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX0_PI_SLC_INT_WDATA  BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_DMX0_PI_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX0_PO_SLC_INT_WDATA  BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_DMX0_PO_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX1_PI_SLC_INT_WDATA  BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_DMX1_PI_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX1_PO_SLC_INT_WDATA  BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_DMX1_PO_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX2_PI_SLC_INT_WDATA  BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_DMX2_PI_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX2_PO_SLC_INT_WDATA  BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_DMX2_PO_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX3_PI_SLC_INT_WDATA  BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_DMX3_PI_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX3_PO_SLC_INT_WDATA  BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_DMX3_PO_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX0_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S1_DMX0_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX0_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S2_DMX0_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX0_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S1_DMX0_PO_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX0_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S2_DMX0_PO_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX1_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S1_DMX1_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX1_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S2_DMX1_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX1_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S1_DMX1_PO_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX1_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S2_DMX1_PO_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX2_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S1_DMX2_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX2_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S2_DMX2_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX2_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S1_DMX2_PO_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX2_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S2_DMX2_PO_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX3_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S1_DMX3_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX3_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S2_DMX3_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX3_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S1_DMX3_PO_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX3_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_ODU_CORE0_REG_DGSEP_S2_DMX3_PO_SLC0_ERRP

/* MDAC analog base registers */
#define BCHP_MDAC_CAL_ANA_ADC_CNTL0             BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL0
#define BCHP_MDAC_CAL_ANA_ADC_CNTL1             BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL1
#define BCHP_MDAC_CAL_ANA_ADC_CNTL2             BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL2
#define BCHP_MDAC_CAL_ANA_ADC_CNTL3             BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL3
#define BCHP_MDAC_CAL_ANA_ADC_CNTL4             BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL4
#define BCHP_MDAC_CAL_ANA_ADC_CNTL5             BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL5
#define BCHP_MDAC_CAL_ANA_ADC_CNTL6             BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL6
#define BCHP_MDAC_CAL_ANA_ADC_CNTL7             BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL7
#define BCHP_MDAC_CAL_ANA_ADC_CNTL8             BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL8
#define BCHP_MDAC_CAL_ANA_ADC_CNTL9             BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL9
#define BCHP_MDAC_CAL_ANA_ADC_CNTL10            BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL10
#define BCHP_MDAC_CAL_ANA_ADC_CNTL11            BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL11
#define BCHP_MDAC_CAL_ANA_ADC_CNTL12            BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL12
#define BCHP_MDAC_CAL_ANA_ADC_CNTL13            BCHP_AIF_MDAC_CAL_ODU_ANA_ADC0_CNTL13
#define BCHP_MDAC_CAL_ANA_PLL_CNTL0             BCHP_AIF_MDAC_CAL_ODU_ANA_PLL_CNTL0
#define BCHP_MDAC_CAL_ANA_PLL_CNTL1             BCHP_AIF_MDAC_CAL_ODU_ANA_PLL_CNTL1
#define BCHP_MDAC_CAL_ANA_PLL_CNTL2             BCHP_AIF_MDAC_CAL_ODU_ANA_PLL_CNTL2
#define BCHP_MDAC_CAL_ANA_PLL_CNTL3             BCHP_AIF_MDAC_CAL_ODU_ANA_PLL_CNTL3
#define BCHP_MDAC_CAL_ANA_PLL_CNTL4             BCHP_AIF_MDAC_CAL_ODU_ANA_PLL_CNTL4
#define BCHP_MDAC_CAL_ANA_PLL_CNTL5             BCHP_AIF_MDAC_CAL_ODU_ANA_PLL_CNTL5
#define BCHP_MDAC_CAL_ANA_PLL_CNTL6             BCHP_AIF_MDAC_CAL_ODU_ANA_PLL_CNTL6
#define BCHP_MDAC_CAL_ANA_PLL_CNTL7             BCHP_AIF_MDAC_CAL_ODU_ANA_PLL_CNTL7
#define BCHP_MDAC_CAL_ANA_SYS_CNTL              BCHP_AIF_MDAC_CAL_ODU_ANA_SYS_CNTL0
#define BCHP_MDAC_CAL_ANA_PLL_STAT              BCHP_AIF_MDAC_CAL_ODU_ANA_PLL_STAT
#define BCHP_MDAC_CAL_ANA_CLK_CTRL              BCHP_AIF_MDAC_CAL_ODU_ANA_CLK_CTRL
#define BCHP_MDAC_CAL_ANA_SW_SPARE0             BCHP_AIF_MDAC_CAL_ODU_ANA_SW_SPARE0
#define BCHP_MDAC_CAL_ANA_SW_SPARE1             BCHP_AIF_MDAC_CAL_ODU_ANA_SW_SPARE1

#endif /* BWFE_4552_PRIV_H__ */
