#
obj-y += tmddTDA18260Shared.o
obj-y += tmddTDA18260Shared_Instance.o
obj-y += tmddTDA18260Shared_RegAccess.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/tmddTDA18260Shared/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/tmddTDA18260Shared/cfg
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/tmddTDA18260Shared/src