-include ./dirs

ifeq ($(DIRS),)
TARGET = toolscommon

SOURCES =                \
	drmtoolsutils.c drmtoolsasfparser.c drmtoolsmediafile.c drmtoolspkg.c drmtoolsinit.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
