obj-$(CONFIG_MW_CAS_NAGRA) += xom_cas_nagra.o
obj-$(CONFIG_MW_CAS_IRDETO) += xom_cas_irdeto.o
obj-$(CONFIG_MW_CAS_VERIMATRIX) += xom_cas_verimatrix.o
obj-$(CONFIG_MW_CI) += xom_cas_ci.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xoapimgr

# Additional include path
ccflags-y += -I$(OCTO_DIR)/main/oxserver

