#!/bin/sh
RESULT=0

umount /mnt/flash
umount /var/lib/humaxtv
umount /var/lib/humaxtv_backup
RESULT=$(($RESULT + $?))

if [[ $RESULT != 0 ]] ; then
	echo "-----------------------------------------------"
	echo "There are open files in /var/lib/xxx directorys"
	echo "-----------------------------------------------"
	lsof | grep /var/lib
	exit $RESULT
else
	exit 0
fi

