#obj-y += 3kl.o
obj-y += libsoc.o
obj-y += mwapp.o
obj-y += tspktfile.o
obj-y += vmparse.o

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
