#!/bin/sh

. /lib/lsb/init-functions
. /etc/default/rcS

if grep -q "nosettop" /proc/cmdline ; then
	exit 0;
fi

case "$1" in
    start)
		if [ "$VERBOSE" != no ]; then
			log_begin_msg "Starting Application processes"
		fi
		export ipc_cso=10.255.128.211
		export ipc_mediapb=10.255.128.200
		export UVA_DRM_LIB_DIR="/usr/browser/drm/"
		exec /home1/dfbmaster &
		exec /home1/sechdlr/root/home/hamalauncher &
		exec /home1/settop/root/home/hamalauncher &
		/usr/local/bin/lxc-start -n imma -c /dev/null -l FATAL /start.sh &
		/usr/local/bin/lxc-start -n ipepg -c /dev/null -l FATAL /start.sh &
		/usr/local/bin/lxc-start -n mheg -c /dev/null -l FATAL /start.sh &
		/usr/local/bin/lxc-start -n homma -c /dev/null -l FATAL /start.sh &
		/usr/local/bin/lxc-start -n corsair -c /dev/null -l FATAL /start.sh &
		exec /home1/hama
		;;
    stop)
		if [ "$VERBOSE" != no ]; then
			log_begin_msg "Stopping Application processes"
		fi
		killall obama
		killall corsair
		;;
    *)
		if [ "$VERBOSE" != no ]; then
			log_success_msg "Usage: /etc/init.d/S90settop {start|stop}"
		fi
		exit 1
		;;
esac

