obj-$(CONFIG_MW_MM_DLNA_WOON_SERVER) += pl_woons.o

include $(OCTOSVC_SRC_DIR)/homma/main/module/include/Makefile.include.mxlib
#ccflags-$(CONFIG_MW_MM_DLNA_WOON_SERVER) += -I$(THIRDPARTY_DIR)/dlna/mxlib/Ra
