obj-y 						+= model/
obj-y 						+= base/
obj-$(CONFIG_OP_FREESAT) 	+= freesat/
obj-$(CONFIG_OP_ERTELECOM) 	+= ertelecom/

obj-y += xsvc_sys.o
obj-y += psvc_sys.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

