obj-y += xmgr_search_sat_core_action_base.o
obj-y += xmgr_search_sat_connect_action_base.o
obj-y += xmgr_search_sat_findsat_action_base.o
obj-y += xmgr_search_sat_rfinput_detect_base.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

