obj-y += xsvc_cas_vmx_psi_ecm.o
obj-y += xsvc_cas_vmx_psi_emm.o
obj-y += xsvc_cas_vmx_psi_main.o
obj-y += xsvc_cas_vmx_psi_session.o
obj-y += xsvc_cas_vmx_psi_stream.o

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
