gOipfEmul.loadMediaList([
	{
		contentType		: 0,
		fileType		: 1,
		fullPath		: '/media/drive1/Media/Video/Directory1_0',
		hasSubitem		: 0,
		date 			: '2012-11-26',
		duration		: '4800',
		playPosition	: '0',
        thumbnailUrl    : 'images/test/temp_photo/thumb_image1.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: '',
		watched			: 0,
		objectType		: 'folder'
	},
    {
        contentType     : 0,
        fileType        : 1,
        fullPath        : '/media/drive1/Media/Video/long_name_test xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        hasSubitem      : 0,
        date            : '2012-11-26',
        duration        : '4800',
        playPosition    : '0',
        thumbnailUrl    : 'images/test/temp_photo/thumb_image1.jpg',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : '',
        watched         : 0,
        objectType      : 'folder'
    },
    /*
	{
		contentType		: 0,
		fileType		: 1,
		fullPath		: '/media/drive1/Media/Video/Directory1_1',
		hasSubitem		: 0,
		date 			: '2012-11-26',
		duration		: '4800',
		playPosition	: '0',
        thumbnailUrl    : '',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: '',
		watched			: 0,
		objectType		: 'folder'
	},
	*/
	{
		contentType		: 0,
		fileType		: 1,
		fullPath		: '/media/drive1/Media/Video/Directory1_2',
		hasSubitem		: 0,
		date 			: '2012-11-26',
		duration		: '4800',
		playPosition	: '0',
        thumbnailUrl    : 'images/test/temp_photo/thumb_image1.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: '',
		watched			: 0,
		objectType		: 'folder'
	},
	{
		contentType		: 0,
		fileType		: 1,
		fullPath		: '/media/drive1/Media/Video/Directory1_0/Directory2_0',
		hasSubitem		: 0,
		date 			: '2012-11-26',
		duration		: '4800',
		playPosition	: '0',
		thumbnailUrl	: '',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: '',
		watched			: 0,
		objectType		: 'folder'
	},
	{
		contentType		: 0,
		fileType		: 1,
		fullPath		: '/media/drive1/Media/Video/Directory1_0/Directory2_0/Directory3_0',
		hasSubitem		: 0,
		date 			: '2012-11-26',
		duration		: '4800',
		playPosition	: '0',
		thumbnailUrl	: '',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: '',
		watched			: 0,
		objectType		: 'folder'
	}
]);
