gOipfEmul.loadMediaList([
	{
		contentType		: 1,
		fileType		: 0,
		title			: 'music1.mp3',
		fullPath		: '/media/drive1/Media/Music/music1.mp3',
		hasSubitem		: 0,
		date 			: '2012-11-26',
		duration		: 480,
		playPosition	: '0',
		thumbnailUrl	: 'images/test/thum/420_aThum1.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'musician',
		watched			: 0
	},
	{
		contentType		: 1,
		fileType		: 0,
		title			: 'music2.mp3',
		fullPath		: '/media/drive1/Media/Music/music2.mp3',
		hasSubitem		: 0,
		date 			: '2012-11-28',
		duration		: 480,
		playPosition	: '0',
		thumbnailUrl	: 'images/test/thum/420_aThum2.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'adele',
		watched			: 0
	},
	{
		contentType		: 1,
		fileType		: 0,
		title			: 'music3.mp3',
		fullPath		: '/media/drive1/Media/Music/music3.mp3',
		hasSubitem		: 0,
		date 			: '2012-11-26',
		duration		: 480,
		playPosition	: '0',
		thumbnailUrl	: 'images/test/thum/420_aThum3.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'adele',
		watched			: 0
	},
		{
		contentType		: 1,
		fileType		: 0,
		title			: 'music4.mp3',
		fullPath		: '/media/drive1/Media/Music/music4.mp3',
		hasSubitem		: 0,
		date 			: '2012-11-21',
		duration		: 36000,
		playPosition	: '0',
		thumbnailUrl	: 'images/test/thum/420_aThum4.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'adele',
		watched			: 0
	},
		{
		contentType		: 1,
		fileType		: 0,
		title			: 'music5.mp3',
		fullPath		: '/media/drive1/Media/Music/music5.mp3',
		hasSubitem		: 0,
		date 			: '2012-11-26',
		duration		: 154172,
		playPosition	: '0',
		thumbnailUrl	: '',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'adele',
		watched			: 0
	},
	{
		contentType		: 1,
		fileType		: 0,
		title			: 'music7.mp3',
		fullPath		: '/media/drive1/Media/Music/Directory1_0/music7.mp3',
		hasSubitem		: 0,
		date 			: '2012-12-26',
		duration		: 480,
		playPosition	: '0',
		thumbnailUrl	: 'images/test/thum/420_aThum5.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'adele',
		watched			: 0
	},{
		contentType		: 1,
		fileType		: 0,
		title			: 'music8.mp3',
		fullPath		: '/media/drive1/Media/Music/Directory1_0/music8.mp3',
		hasSubitem		: 0,
		date 			: '2012-12-26',
		duration		: 480,
		playPosition	: '0',
		thumbnailUrl	: 'images/test/thum/420_aThum5.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'adele',
		watched			: 0
	},{
		contentType		: 1,
		fileType		: 0,
		title			: 'music9.mp3',
		fullPath		: '/media/drive1/Media/Music/Directory1_0/music9.mp3',
		hasSubitem		: 0,
		date 			: '2012-12-26',
		duration		: 480,
		playPosition	: '0',
		thumbnailUrl	: 'images/test/thum/420_aThum5.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'adele',
		watched			: 0
	},{
		contentType		: 1,
		fileType		: 0,
		title			: 'music10.mp3',
		fullPath		: '/media/drive1/Media/Music/Directory1_0/music10.mp3',
		hasSubitem		: 0,
		date 			: '2012-12-26',
		duration		: 480,
		playPosition	: '0',
		thumbnailUrl	: 'images/test/thum/420_aThum5.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'adele',
		watched			: 0
	},{
		contentType		: 1,
		fileType		: 0,
		title			: 'music11.mp3',
		fullPath		: '/media/drive1/Media/Music/Directory1_0/music11.mp3',
		hasSubitem		: 0,
		date 			: '2012-12-26',
		duration		: 480,
		playPosition	: '0',
		thumbnailUrl	: 'images/test/thum/420_aThum5.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'adele',
		watched			: 0
	},{
		contentType		: 1,
		fileType		: 0,
		title			: 'music12.mp3',
		fullPath		: '/media/drive1/Media/Music/Directory1_0/music12.mp3',
		hasSubitem		: 0,
		date 			: '2012-12-26',
		duration		: 480,
		playPosition	: '0',
		thumbnailUrl	: 'images/test/thum/420_aThum5.jpg',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'adele',
		watched			: 0
	},
	{
		contentType		: 1,
		fileType		: 0,
		title			: 'music7.mp3',
		fullPath		: '/media/drive1/Media/Music/Directory1_0/Directory2_0/Directory3_0/music7.mp3',
		hasSubitem		: 0,
		date 			: '2012-11-26',
		duration		: 480,
		playPosition	: '0',
		thumbnailUrl	: '',
		resolution		: '',
		thumbResolution	: '',
		pictureDate		: '',
		album			: '',
		artist			: 'adele',
		watched			: 0,
	},

    {
        contentType     : 1,
        fileType        : 0,
        title           : 'music2.mp3',
        fullPath        : '/media/drive1/Media/Music/music2.mp3',
        hasSubitem      : 0,
        date            : '2012-11-28',
        duration        : 480,
        playPosition    : '0',
        thumbnailUrl    : 'images/test/thum/420_aThum2.jpg',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : 'adele',
        watched         : 0
    },
    {
        contentType     : 1,
        fileType        : 0,
        title           : 'music3.mp3',
        fullPath        : '/media/drive1/Media/Music/music3.mp3',
        hasSubitem      : 0,
        date            : '2012-11-26',
        duration        : 480,
        playPosition    : '0',
        thumbnailUrl    : 'images/test/thum/420_aThum3.jpg',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : 'adele',
        watched         : 0
    },
        {
        contentType     : 1,
        fileType        : 0,
        title           : 'music4.mp3',
        fullPath        : '/media/drive1/Media/Music/music4.mp3',
        hasSubitem      : 0,
        date            : '2012-11-21',
        duration        : 480,
        playPosition    : '0',
        thumbnailUrl    : 'images/test/thum/420_aThum4.jpg',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : 'adele',
        watched         : 0
    },
        {
        contentType     : 1,
        fileType        : 0,
        title           : 'music5.mp3',
        fullPath        : '/media/drive1/Media/Music/music5.mp3',
        hasSubitem      : 0,
        date            : '2012-11-26',
        duration        : 480,
        playPosition    : '0',
        thumbnailUrl    : '',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : 'adele',
        watched         : 0
    },
    {
        contentType     : 1,
        fileType        : 0,
        title           : 'music7.mp3',
        fullPath        : '/media/drive1/Media/Music/Directory1_0/music7.mp3',
        hasSubitem      : 0,
        date            : '2012-12-26',
        duration        : 480,
        playPosition    : '0',
        thumbnailUrl    : 'images/test/thum/420_aThum5.jpg',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : 'adele',
        watched         : 0
    },{
        contentType     : 1,
        fileType        : 0,
        title           : 'music8.mp3',
        fullPath        : '/media/drive1/Media/Music/Directory1_0/music8.mp3',
        hasSubitem      : 0,
        date            : '2012-12-26',
        duration        : 480,
        playPosition    : '0',
        thumbnailUrl    : 'images/test/thum/420_aThum5.jpg',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : 'adele',
        watched         : 0
    },{
        contentType     : 1,
        fileType        : 0,
        title           : 'music9.mp3',
        fullPath        : '/media/drive1/Media/Music/Directory1_0/music9.mp3',
        hasSubitem      : 0,
        date            : '2012-12-26',
        duration        : 480,
        playPosition    : '0',
        thumbnailUrl    : 'images/test/thum/420_aThum5.jpg',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : 'adele',
        watched         : 0
    },{
        contentType     : 1,
        fileType        : 0,
        title           : 'music10.mp3',
        fullPath        : '/media/drive1/Media/Music/Directory1_0/music10.mp3',
        hasSubitem      : 0,
        date            : '2012-12-26',
        duration        : 480,
        playPosition    : '0',
        thumbnailUrl    : 'images/test/thum/420_aThum5.jpg',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : 'adele',
        watched         : 0
    },{
        contentType     : 1,
        fileType        : 0,
        title           : 'music11.mp3',
        fullPath        : '/media/drive1/Media/Music/Directory1_0/music11.mp3',
        hasSubitem      : 0,
        date            : '2012-12-26',
        duration        : 480,
        playPosition    : '0',
        thumbnailUrl    : 'images/test/thum/420_aThum5.jpg',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : 'adele',
        watched         : 0
    },{
        contentType     : 1,
        fileType        : 0,
        title           : 'music12.mp3',
        fullPath        : '/media/drive1/Media/Music/Directory1_0/music12.mp3',
        hasSubitem      : 0,
        date            : '2012-12-26',
        duration        : 480,
        playPosition    : '0',
        thumbnailUrl    : 'images/test/thum/420_aThum5.jpg',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : 'adele',
        watched         : 0
    },
    {
        contentType     : 1,
        fileType        : 0,
        title           : 'music7.mp3',
        fullPath        : '/media/drive1/Media/Music/Directory1_0/Directory2_0/Directory3_0/music7.mp3',
        hasSubitem      : 0,
        date            : '2012-11-26',
        duration        : 480,
        playPosition    : '0',
        thumbnailUrl    : '',
        resolution      : '',
        thumbResolution : '',
        pictureDate     : '',
        album           : '',
        artist          : 'adele',
        watched         : 0,
    }
]);
