#ifndef __AP_CAS_VA_PREVIEW_COORDINATE_H__
#define __AP_CAS_VA_PREVIEW_COORDINATE_H__

// frame
#define	CAS_VA_PREVIEW_WINDOW_X					0
#define	CAS_VA_PREVIEW_WINDOW_Y					0

#define	CAS_VA_PREVIEW_WINDOW_WIDTH				OSD_SCREEN_WIDTH
#define	CAS_VA_PREVIEW_WINDOW_HEIGHT			OSD_SCREEN_HEIGHT

// background
#define CAS_VA_PREVIEW_BACKGROUND_X				196
#define CAS_VA_PREVIEW_BACKGROUND_Y				36

#define CAS_VA_PREVIEW_BACKGROUND_WIDTH			888
#define CAS_VA_PREVIEW_BACKGROUND_HEIGHT		128

// preview alarm text
#define CAS_VA_PREVIEW_TEXT_X					(CAS_VA_PREVIEW_BACKGROUND_X + 40)
#define CAS_VA_PREVIEW_TEXT_Y					63

#define CAS_VA_PREVIEW_TEXT_WIDTH				808
#define CAS_VA_PREVIEW_TEXT_HEIGHT				30

// elapsed time text
#define CAS_VA_PREVIEW_ELAPSED_TIME_TEXT_X		(CAS_VA_PREVIEW_BACKGROUND_X + 36)
#define CAS_VA_PREVIEW_ELAPSED_TIME_TEXT_Y		(CAS_VA_PREVIEW_BACKGROUND_Y + 70)

#define CAS_VA_PREVIEW_ELAPSED_TIME_TEXT_WIDTH	378
#define CAS_VA_PREVIEW_ELAPSED_TIME_TEXT_HEIGHT	100

// margin
#define CAS_VA_PREVIEW_PROGRESS_MARGIN			6

// process
#define CAS_VA_PREVIEW_PROGRESS_X				(CAS_VA_PREVIEW_ELAPSED_TIME_TEXT_X + CAS_VA_PREVIEW_ELAPSED_TIME_TEXT_WIDTH + CAS_VA_PREVIEW_PROGRESS_MARGIN)
#define CAS_VA_PREVIEW_PROGRESS_Y				(CAS_VA_PREVIEW_BACKGROUND_Y + 81)

#define CAS_VA_PREVIEW_PROGRESS_WIDTH			200
#define CAS_VA_PREVIEW_PROGRESS_HEIGHT			10

#endif /* __AP_CAS_VA_PREVIEW_COORDINATE_H__ */
// End of file
