obj-y += menu/
obj-y += xmgr_cas_va_ui.o
obj-y += xmgr_cas_va_pincode_ui.o
obj-y += xmgr_cas_va_pincode_check_ui.o
obj-y += xmgr_cas_va_preview_ui.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

# Sub-CAS include path
