obj-y += tr069.o
obj-y += cpe_peer.o
obj-y += trport.o
obj-y += trport_db.o
obj-y += trport_gfx.o
obj-y += trport_flash.o

# Additional include path
ccflags-y += -I../../../../make/include
ccflags-y += -I../../../../3rd_party/tr069/include

