obj-y += isosvc.o
#obj-y += mwc_util.o
obj-$(CONFIG_MW_SI_SCHEDULE_TRACKING) += mwc_trackingschedule.o

#obj-y += mwc_codepage.o
#obj-y += codepage/

obj-$(CONFIG_MWC_STRING_DECOMPRESS_300468) += str_decompress/


# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw
# Additional include path
#ccflags-y += -I$(OCTO_TVMANAGER_DIR)/mgr/include
