obj-y += converter/
obj-y += recording/
obj-$(CONFIG_3RD_XML) += xml/
obj-y += upgrade/
obj-y += ramdisk/
obj-y += otl.o

obj-$(CONFIG_DEBUG) += log_report/

# Basic include path
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.pal
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.dlna

# Additional include path

