#######################################
# include
#######################################
# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw

# Additional include path
ccflags-y += -I$(OCTO_TVSERVICE_DIR)/svc/cas/local_include

#######################################
# make
#######################################
obj-y += svc_cas_cmd.o
