#######################################
# include
#######################################
# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw

# Additional include path
ccflags-y += -I$(OCTO_TVSERVICE_DIR)/svc/cas/local_include

#######################################
# make
#######################################
obj-y += svc_cas_mgr_control.o
obj-y += svc_cas_mgr_instance.o
obj-y += svc_cas_mgr_main.o
obj-y += svc_cas_mgr_si.o
obj-y += svc_cas_mgr_scenario.o
obj-y += svc_cas_mgr_debug.o
obj-y += svc_cas_mgr_sc.o

