obj-y += xmgr_epg_rf_base.o
obj-$(CONFIG_APCORE_IP_EPG) += xmgr_epg_ip_humax.o
obj-$(CONFIG_MW_EPG_TVTV) += xmgr_epg_action_tvtv.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path
