#include "nexus_platform.h"
/*#include "nexus_gpio_module.h"*/
#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"
 
const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
	/*/////////////   0 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//0  */  /* N.C */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//1 */  /* N.C */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//2  */ /*GP_7445_RGMII_RXCLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//3 */ /*GP_7445_RGMII_RXDV */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//4  */ /*GP_7445_RGMII_RXD0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//5  */ /*GP_7445_RGMII_RXD1 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//6  */ /*GP_7445_RGMII_RXD2*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//7  */ /*GP_7445_RGMII_RXD3 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//8  */ /*GP_53125_IMP_RXCLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//9  */ /* GP_53125_IMP_RXDV*/
	/*//////////////  10 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//10  */  /*EMAC0_TXD_00 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//11  */  /*EMAC0_TXD_01*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//12  */  /*EMAC0_TXD_02 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//13 */   /*EMAC0_TXD_03*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//14  */  /*N.C */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//15 */  /*N.C */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//16  */  /*N.C*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//17  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//18  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//19  */  /*GP_MTSIF0_CLK */
/*//////////////  20 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//20  */  /*GP_MTSIF0_DATA0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//21  */  /*GP_MTSIF0_SYNC*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//22  */  /*GP_MTSIF0_DATA1*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//23  */  /*N.C*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//24  */  /*GP_MTSIF0_DATA2*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//25  */  /*GP_MTSIF0_DATA3*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//26  */  /*GP_MTSIF0_DATA4 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//27  */  /*GP_MTSIF0_DATA5 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//28  */  /*GP_MTSIF0_DATA6 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//29  */  /*GP_MTSIF0_DATA7 */
	/*//////////////  30 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//30  */  /*GP_MTSIF_ATS_INC */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//31  */  /*GP_MTSIF_ATS_RST */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//32  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//33  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//34  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//35  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//36  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//37  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//38  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//39  */  /*N.C. */
/*//////////////  40 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//40  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//41  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//42  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//43  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//44  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//45  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//46  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//47  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//48  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//49  */ /*GP_SC0_IO */
/*//////////////  50 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT4,	/*//50  */  /*GP_SC0_CLK */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//51  */  /*GP_SC0_RST */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//52 */  /*GP_SC0_PRES */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//53  */  /*GP_SC0_VCC */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//54  */  /*GP_SC0_AUX1 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//55  */  /*GP_SC0_AUX2 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//56  */  /*GP_SC0_VCTRL */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//57  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//58  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//59  */  /*N.C. */
/*//////////////  60 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT3,	/*//60 */  /*TS_CLK */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//61 */  /*TS_DATA*/
	HUMAX_GPIO_FUNCTION_ALT3,	/*//62 */  /*TS_SYNC */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//63*/  /*N.C */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//64*/  /*TS_VALID*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//65*/  /*N.C  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//66*/  /*N.C  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//67*/  /*N.C  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//68*/  /*N.C  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//69*/  /*N.C  */
/*//////////////  70 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//70  */  /*N.C  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//71  */  /*TS_CLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//72  */  /*TS_DATA*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//73  */  /*TS_SYNC*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*//74  */  /*FAN_PWM*//*->*//*GPIO*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//75  */  /*TS_VALID*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//76  */  /*N.C */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//77  */  /*N.C */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//78  */  /*N.C */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//79  */  /*N.C */
	/*//////////////  80 //////////////*/ 
	HUMAX_GPIO_FUNCTION_NCTP,	/*//80  */  /*N.C */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//81  */  /*RF4CE_RXD */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//82  */  /*RF4CE_TXD */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//83  */  /*N.C */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//84  */  /*N.C */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//85  */  /*N.C */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//86  */  /*GP_SC1_IO */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//87  */  /*GP_SC1_CLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//88  */  /*GP_SC1_RST */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//89  */  /*GP_SC1_PRES */
	/*//////////////  90 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//90  */  /*GP_SC1_VCC */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//91  */  /*NDS_SC1_AUX1 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//92  */  /*NDS_SC1_AUX2 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//93  */  /*NDS_SC1_VCTRL */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//94  */  /*N.C.*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//95  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//96  */  /*CPU_MON. */
	HUMAX_GPIO_FUNCTION_ALT6,	/*//97  */  /*TS_SYNC_2 */ 
	HUMAX_GPIO_FUNCTION_GPIO,	/*//98  */  /*FRONT_ISP */ 
	HUMAX_GPIO_FUNCTION_ALT5,	/*//99  */  /*TS_CLK_2 */
	/*////////////// 100 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT5,	/*//100  */  /*TS_DATA2 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//101  */  /*HDD_PWR_CTRL */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//102  */  /*FRONT_RST*/
	HUMAX_GPIO_FUNCTION_ALT3,	/*//103  */  /*TS_VALID2.  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//104  */  /*MxL683_RESET_N_1 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//105  */  /*MxL683_RESET_N_2 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//106  */  /*MxL683_RESET_N_3 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//107  */  /*SPEED_FAN */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//108  */  /*N.C.*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//109  */  /*N.C. */
	/*////////////// 110 //////////////*/	
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /*N.C. */
	
	/*////////////// SGPIO 00 (0~5)//////////////*/	
	HUMAX_GPIO_FUNCTION_ALT1,	/*//0  */  /*I2C_DEMOD3_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//1  */  /*I2C_DEMOD3_SDA */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//2  */  /*N.C */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//3  */  /*N.C */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//4  */  /*N.C */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//5  */  /*N.C */
	
	/*////////////// AON_GPIO 00(0~17)//////////////*/	
	HUMAX_GPIO_FUNCTION_NCTP,	/*//0  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//1  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//2 */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//3  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//4  */ /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//5  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//6  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//7  */  /*N.C.   */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//8  */ /*GP_7445_COM_UART1_TX */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//9  */ /*GP_7445_COM_UART1_RX */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//10  */ /*N.C. */

	HUMAX_GPIO_FUNCTION_NCTP,	/*//11  */  /*N.C.    */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//12  */  /*N.C.    */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//13  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//14  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//15  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//16  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//17  */	/*N.C. */

	/*////////////// AON_SGPIO (0~5)//////////////*/	
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */ /*7445_HDMI_TX_BSC_SCL */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */ /*7445_HDMI_TX_BSC_SDA */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /*I2C_DEMOD1_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /*I2C_DEMOD1_SDA */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /*I2C_DEMOD2_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /*I2C_DEMOD2_SDA */
};

/*************************
*	gpio: 0~111 :112
*	sgpio: 0~5 : 6
*	aon_gpio: 0~17 : 18
*	aon_sgpio: 0~5 : 6
*************************/
HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
     {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_000_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_000_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_001_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_001_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_002_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_002_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_003_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_003_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_004_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_004_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_005_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_005_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_006_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_006_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_007_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_007_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_008_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_008_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_009_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_009_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_010_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_010_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_011_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_011_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_012_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_012_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_013_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_013_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_014_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_014_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_015_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_015_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_016_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_016_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_017_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_017_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_018_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_018_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_019_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_019_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_020_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_020_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_021_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_021_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_022_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_022_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_023_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_023_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_024_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_024_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_025_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_025_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_026_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_026_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_027_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_027_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_028_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_028_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_029_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_029_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_030_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_030_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_031_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_031_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_032_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_032_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_033_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_033_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_034_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_034_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_035_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_035_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_036_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_036_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_037_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_037_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_038_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_038_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_039_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_039_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_040_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_040_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_041_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_041_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_042_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_042_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_043_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_043_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_044_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_044_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_045_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_045_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_046_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_046_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_047_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_047_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_048_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_048_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_049_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_049_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_050_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_050_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_051_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_051_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_052_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_052_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_053_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_053_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_054_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_054_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_055_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_055_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_056_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_056_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_057_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_057_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_058_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_058_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_059_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_059_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_060_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_060_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_061_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_061_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_062_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_062_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_063_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_063_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_064_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_064_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_065_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_065_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_066_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_066_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_067_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_067_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_068_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_068_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_069_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_069_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_070_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_070_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_071_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_071_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_072_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_072_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_073_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_073_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_074_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_074_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_075_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_075_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_076_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_076_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_077_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_077_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_078_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_078_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_079_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_079_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_080_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_080_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_081_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_081_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_082_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_082_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_083_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_083_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_084_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_084_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_085_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_085_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_086_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_086_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_087_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_087_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_088_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_088_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_089_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_089_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_090_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_090_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_091_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_091_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_092_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_092_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_093_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_093_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_094_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_094_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_095_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_095_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_096_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_096_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_097_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_097_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_098_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_098_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_099_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_099_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_100_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_100_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_101_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_101_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_102_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_102_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_103_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_103_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_104_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_104_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_105_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_105_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_106_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_106_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_107_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_107_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_108_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_108_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_109_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_109_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_110_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_110_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_111_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_111_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_00_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_01_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_02_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_03_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_04_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_05_SHIFT},

    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_SHIFT},

    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_SHIFT},

    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT},

    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_02_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_03_SHIFT},
		{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_04_SHIFT},
		{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_05_SHIFT}
};
