obj-y += apk_output_video.o
obj-y += apk_output_audio.o
obj-y += apk_output_hdmi.o
obj-y += apk_output_panel.o
obj-y += apk_output_thermal_protection.o

# APPKIT v2 local include path
ccflags-y += -I$(OCTOTOP_SRC_DIR)/appkit/local_include

