obj-$(CONFIG_PROD_HMS1000S)			+= hms1000s/
obj-$(CONFIG_PROD_HMSLITE)			+= hms1000s/
obj-$(CONFIG_PROD_IR4000HD)			+= ir4000hd/
obj-$(CONFIG_PROD_ICORDPRO)			+= icordpro/
obj-$(CONFIG_PROD_HDNEO)			+= hdneo/
obj-$(CONFIG_PROD_HGS1000S)			+= hgs1000s/
obj-$(CONFIG_PROD_HD9000I)			+= hd9000i/
obj-$(CONFIG_PROD_HMS1000T)			+= hms1000t/
obj-$(CONFIG_PROD_IHDR6100C)		+= ihdr6100c/
obj-$(CONFIG_PROD_FVP4000T)			+= fvp4000t/
obj-$(CONFIG_PROD_HMX4KBBC)			+= hmx4kbbc/
obj-$(CONFIG_PROD_DIGIMAXT2)		+= digimaxt2/
obj-$(CONFIG_PROD_HDFOXIRCONNECT)	+= hdfoxirconnect/
obj-$(CONFIG_PROD_YSR2000)			+= ysr2000/
obj-$(CONFIG_PROD_YS1000)			+= ys1000/
obj-$(CONFIG_PROD_CDIG2000C)			+= cdig2000c/
obj-$(CONFIG_PROD_ROCKYPOM)			+= rockypom/
obj-$(CONFIG_PROD_ROCKYWPOM)			+= rockypom/
obj-$(CONFIG_PROD_HA7100S) 		+= ha7100s/
obj-$(CONFIG_PROD_M1)					+= m1/

obj-y += xmgr_model.o
obj-y += pmgr_model.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr

# Additional include path
