-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = secureclockprocessresponse

DRM_MODULE_CFLAGS =

SOURCES =                \
	 secureclockprocessresponse.c
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
