# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

SRC_DIR = .

include $(PLAYREADY_DIR)/PK_GNUmakefile.common

INCLUDE_DIRS +=                             \
  -I$(_NTROOT)/test/Inc                     \
  -I$(_NTROOT)/test/tOEMImp/$(PLATFORM)/inc \

