#!/bin/sh

	umount /var/lib/humaxtv
	umount /var/lib/humaxtv_backup
	ubidetach -m 7
	ubiformat -y /dev/mtd7
	ubiattach -m 7
	ubimkvol /dev/ubi1 -N dbbackup -s 4MiB
	ubimkvol /dev/ubi1 -N dbdata -s 32MiB
	ubidetach -m 7
