obj-y += xmgr_cas_ci_tune.o
obj-y += xmgr_cas_ci_upgrade.o
obj-y += xmgr_cas_ci_parentalctrl.o
obj-$(CONFIG_MW_CI_PLUS_V_1_3) += xmgr_cas_ci_op.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

