#!/bin/sh

	umount /var/lib/humaxtv
	umount /var/lib/humaxtv_backup
	umount /var/lib/humaxtv_user
	ubidetach -m 4
	ubiformat -y /dev/mtd4
	ubiattach -m 4
	ubimkvol /dev/ubi1 -N dbbackup -s 32MiB
	ubimkvol /dev/ubi1 -N dbdata -s 32MiB
	ubimkvol /dev/ubi1 -N dbuser -s 60MiB		
	ubidetach -m 4

