#
obj-y += tmbslTDA18273.o
obj-y += tmbslTDA18273_Instance.o
obj-y += tmbslTDA18273_RegDef.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18273/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18273/tmbslTDA18273/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18273/tmbslTDA18273/cfg
