/***************************************************************************
 *     Copyright (c) 2003-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bast_7346_priv.h $
 * $brcm_Revision: Hydra_Software_Devel/38 $
 * $brcm_Date: 10/15/12 4:16p $
 *
 * [File Description:]
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/portinginterface/ast/src/g3/7346/bast_7346_priv.h $
 * 
 * Hydra_Software_Devel/38   10/15/12 4:16p enavarro
 * SWSATFE-220: renamed BAST_Gx_BUILD_VERSION to BAST_G3_BUILD_VERSION
 * 
 * Hydra_Software_Devel/37   10/15/12 10:59a enavarro
 * SWSATFE-220: implement BAST_GetVersionInfo()
 * 
 * Hydra_Software_Devel/36   10/8/12 11:09a ronchan
 * SWSATFE-75: incremented minor revision to 0x12
 * 
 * Hydra_Software_Devel/35   9/7/12 9:54a ronchan
 * SWSATFE-214: renamed header file definition
 * 
 * Hydra_Software_Devel/34   8/31/12 3:24p ronchan
 * SWSATFE-75: incremented minor revision to 0x11
 * 
 * Hydra_Software_Devel/33   8/3/12 9:45a ronchan
 * SWSATFE-75: incremented minor revision to 0x10
 * 
 * Hydra_Software_Devel/32   7/19/12 2:25p ronchan
 * SWSATFE-75: incremented minor revision to 0xF
 * 
 * Hydra_Software_Devel/31   5/24/12 2:23p ronchan
 * SWSATFE-75: incremented minor revision to 0xE
 * 
 * Hydra_Software_Devel/30   5/10/12 9:49a ronchan
 * SW7360-13: map cwc shift to channel 0 rdb
 * 
 * Hydra_Software_Devel/29   4/20/12 2:52p ronchan
 * SWSATFE-75: add diseqc almost empty interrupt
 * 
 * Hydra_Software_Devel/28   3/22/12 2:33p ronchan
 * SWSATFE-75: incremented minor revision to 0xD
 * 
 * Hydra_Software_Devel/27   3/13/12 3:48p ronchan
 * SWSATFE-75: incremented minor revision to 0xC
 * 
 * Hydra_Software_Devel/26   2/7/12 2:45p ronchan
 * SWSATFE-75: incremented minor revision to 0xB
 * 
 * Hydra_Software_Devel/25   1/12/12 3:06p ronchan
 * SWSATFE-75: incremented minor revision to 0xA
 * 
 * Hydra_Software_Devel/24   12/14/11 2:38p ronchan
 * SWSATFE-75: incremented minor revision to 0x9
 * 
 * Hydra_Software_Devel/23   12/7/11 4:49p ronchan
 * SWSATFE-75: incremented minor revision to 0x8
 * 
 * Hydra_Software_Devel/22   11/10/11 5:03p ckpark
 * SWSATFE-127: added interrupt for fine frequency estimation
 * 
 * Hydra_Software_Devel/21   11/1/11 3:06p ronchan
 * SWSATFE-75: incremented minor revision to 0x7
 * 
 * Hydra_Software_Devel/20   10/13/11 2:28p ronchan
 * SWSATFE-75: incremented minor revision to 0x6
 * 
 * Hydra_Software_Devel/19   9/16/11 9:51a ronchan
 * SW7358-131: fix value for BCHP_VER
 * 
 * Hydra_Software_Devel/18   9/9/11 10:59a ronchan
 * SW7346-426: add cwc registers for B0
 * 
 * Hydra_Software_Devel/17   8/22/11 2:41p ronchan
 * SW7346-426: removed and renamed TFEC registers for B0
 * 
 * Hydra_Software_Devel/16   8/22/11 2:24p ronchan
 * SW7346-426: redefined FTM PHY ana registers for B0
 * 
 * Hydra_Software_Devel/15   8/22/11 10:59a ronchan
 * SW7346-426: replace notch filters with cw canceller for B0
 * 
 * Hydra_Software_Devel/14   8/17/11 4:32p ronchan
 * SWSATFE-75: incremented minor revision to 0x5
 * 
 * Hydra_Software_Devel/13   7/6/11 12:07p enavarro
 * SWSATFE-130: redefined AFEC lock interrupts to mean HP/AFEC/BERT lock
 * 
 * Hydra_Software_Devel/12   6/30/11 4:41p ckpark
 * SWSATFE-130: rollback previous changes
 * 
 * Hydra_Software_Devel/10   6/6/11 9:44a ckpark
 * SWSATFE-86: added some bchp definitions for compatibility with other g3
 * AST implementations
 * 
 * Hydra_Software_Devel/9   4/18/11 4:26p ronchan
 * SWSATFE-75: incremented minor revision to 0x4
 * 
 * Hydra_Software_Devel/8   4/1/11 8:16a enavarro
 * SWSATFE-86: move BAST_DEFAULT_SAMPLE_FREQ definition in chip-specific
 * file
 * 
 * Hydra_Software_Devel/7   2/24/11 10:42a ronchan
 * SWSATFE-75: incremented minor revision to 0x3
 * 
 * Hydra_Software_Devel/6   2/14/11 10:52a ronchan
 * SWSATFE-75: incremented minor revision to 0x2
 * 
 * Hydra_Software_Devel/5   1/28/11 4:08p ronchan
 * SWSATFE-75: diseqc timers swapped back in rdb
 * 
 * Hydra_Software_Devel/4   12/8/10 2:13p enavarro
 * SWSATFE-75: added turbo sync detect interrupt
 * 
 * Hydra_Software_Devel/3   12/6/10 10:51a enavarro
 * SWSATFE-75: fixed compiler error
 * 
 * Hydra_Software_Devel/2   12/6/10 9:54a ronchan
 * SWSATFE-75: added interrupt bit mapping for multiple channels
 * 
 * Hydra_Software_Devel/1   11/16/10 11:16a ronchan
 * SWSATFE-75: initial version
 *
 ***************************************************************************/
#ifndef _BAST_7346_PRIV_H__
#define _BAST_7346_PRIV_H__               

#include "bchp_afec_0.h"
#include "bchp_afec_1.h"
#include "bchp_afec_global_0.h"
#include "bchp_afec_global_1.h"
#include "bchp_afec_gr_bridge_0.h"
#include "bchp_afec_gr_bridge_1.h"
#include "bchp_afec_intr_ctrl2_0.h"
#include "bchp_afec_intr_ctrl2_1.h"

#include "bchp_sds_agc_0.h"
#include "bchp_sds_agc_1.h"
#include "bchp_sds_bert_0.h"
#include "bchp_sds_bert_1.h"
#include "bchp_sds_bl_0.h"
#include "bchp_sds_bl_1.h"
#include "bchp_sds_cg_0.h"
#include "bchp_sds_cg_1.h"
#include "bchp_sds_cl_0.h"
#include "bchp_sds_cl_1.h"
#include "bchp_sds_dft_0.h"
#include "bchp_sds_dft_1.h"
#include "bchp_sds_dsec_0.h"
#include "bchp_sds_dsec_1.h"
#include "bchp_sds_eq_0.h"
#include "bchp_sds_eq_1.h"
#include "bchp_sds_fe_0.h"
#include "bchp_sds_fe_1.h"
#include "bchp_sds_fec_0.h"
#include "bchp_sds_fec_1.h"
#include "bchp_sds_gr_bridge_0.h"
#include "bchp_sds_gr_bridge_1.h"
#include "bchp_sds_hp_0.h"
#include "bchp_sds_hp_1.h"
#include "bchp_sds_intr2_0_0.h"
#include "bchp_sds_intr2_0_1.h"
#include "bchp_sds_intr2_1_0.h"
#include "bchp_sds_intr2_1_1.h"
#include "bchp_sds_misc_0.h"
#include "bchp_sds_misc_1.h"
#if (BCHP_VER == BCHP_VER_A0)
#include "bchp_sds_ntch_0.h"
#include "bchp_sds_ntch_1.h"
#else
#include "bchp_sds_cwc_0.h"
#include "bchp_sds_cwc_1.h"
#endif
#include "bchp_sds_oi_0.h"
#include "bchp_sds_oi_1.h"
#include "bchp_sds_snr_0.h"
#include "bchp_sds_snr_1.h"
#include "bchp_sds_tuner_0.h"
#include "bchp_sds_tuner_1.h"
#include "bchp_sds_vit_0.h"
#include "bchp_sds_vit_1.h"

#include "bchp_tfec_0.h"
#include "bchp_tfec_1.h"
#include "bchp_tfec_gr_bridge_0.h"
#include "bchp_tfec_gr_bridge_1.h"
#include "bchp_tfec_intr2_0.h"
#include "bchp_tfec_intr2_1.h"
#include "bchp_tfec_misc_0.h"
#include "bchp_tfec_misc_1.h"

#include "bchp_ftm_gr_bridge.h"
#include "bchp_ftm_intr2.h"
#include "bchp_ftm_phy.h"
#include "bchp_ftm_skit.h"
#include "bchp_ftm_uart.h"

#define BAST_G3_BUILD_VERSION 0x13 


#if (BCHP_VER > BCHP_VER_A0)
#include "bchp_ftm_phy_ana.h"
#define BCHP_FTM_PHY_ANA0_0 BCHP_FTM_PHY_ANA_CTL0_0
#define BCHP_FTM_PHY_ANA0_1 BCHP_FTM_PHY_ANA_CTL0_1
#define BCHP_FTM_PHY_ANA1_0 BCHP_FTM_PHY_ANA_CTL1_0
#define BCHP_FTM_PHY_ANA1_1 BCHP_FTM_PHY_ANA_CTL1_1
#endif


#define BAST_G3_MAX_CHANNELS 2
#define BAST_G3_XTAL_FREQ    54000000
#define BAST_G3_CHIP         0x7346

#define BAST_DEFAULT_SAMPLE_FREQ 184500000

/* channel 0 interrupts */
#define BCHP_INT_ID_SDS_LOCK_IS_0               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_IS_0           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_IS_0                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_IS_0               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS1_0             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS2_0             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS3_0             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_SDS_HP_IS_0                 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_0         BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_MI2C_IS_0                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)

#define BCHP_INT_ID_SDS_sar_vol_gt_hi_thrsh_0   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_sar_vol_gt_thresh_SHIFT)
#define BCHP_INT_ID_SDS_sar_vol_lt_lo_thrsh_0   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_sar_vol_lt_thresh_SHIFT)
#define BCHP_INT_ID_DSDN_IS_0                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_done_SHIFT)
#define BCHP_INT_ID_DISEQC_TIMER1_0             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_timer1_SHIFT)
#define BCHP_INT_ID_DISEQC_TIMER2_0             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_timer2_SHIFT)
#define BCHP_INT_ID_DISEQC_tx_fifo_a_empty_0    BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_tx_fifo_a_empty_SHIFT)

#define BCHP_INT_ID_TURBO_LOCK_IS_0             BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_0_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TURBO_NOT_LOCK_IS_0         BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_0_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TURBO_SYNC_0                BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_0_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)

#if 0
#define BCHP_INT_ID_AFEC_LOCK_IS_0              BCHP_INT_ID_CREATE(BCHP_AFEC_INTR_CTRL2_0_CPU_STATUS, BCHP_AFEC_INTR_CTRL2_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_IS_0          BCHP_INT_ID_CREATE(BCHP_AFEC_INTR_CTRL2_0_CPU_STATUS, BCHP_AFEC_INTR_CTRL2_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#else
#define BCHP_INT_ID_AFEC_LOCK_IS_0              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_IS_0          BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#endif

/* channel 1 interrupts */
#define BCHP_INT_ID_SDS_LOCK_IS_1               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_IS_1           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_IS_1                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_IS_1               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS1_1             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS2_1             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS3_1             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_SDS_HP_IS_1                 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_1         BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_MI2C_IS_1                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)

#define BCHP_INT_ID_SDS_sar_vol_gt_hi_thrsh_1   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_sar_vol_gt_thresh_SHIFT)
#define BCHP_INT_ID_SDS_sar_vol_lt_lo_thrsh_1   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_sar_vol_lt_thresh_SHIFT)
#define BCHP_INT_ID_DSDN_IS_1                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_done_SHIFT)
#define BCHP_INT_ID_DISEQC_TIMER1_1             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_timer1_SHIFT)
#define BCHP_INT_ID_DISEQC_TIMER2_1             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_timer2_SHIFT)
#define BCHP_INT_ID_DISEQC_tx_fifo_a_empty_1    BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_INTR2_1_0_CPU_STATUS_dsec_tx_fifo_a_empty_SHIFT)

#define BCHP_INT_ID_TURBO_LOCK_IS_1             BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_1_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TURBO_NOT_LOCK_IS_1         BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_1_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TURBO_SYNC_1                BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_1_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)

#if 1
#define BCHP_INT_ID_AFEC_LOCK_IS_1              BCHP_INT_ID_CREATE(BCHP_AFEC_INTR_CTRL2_1_CPU_STATUS, BCHP_AFEC_INTR_CTRL2_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_IS_1          BCHP_INT_ID_CREATE(BCHP_AFEC_INTR_CTRL2_1_CPU_STATUS, BCHP_AFEC_INTR_CTRL2_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#else
#define BCHP_INT_ID_AFEC_LOCK_IS_1              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_IS_1          BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#endif

/* register definitions for multiple channels */
#define BCHP_AFEC_RST BCHP_AFEC_0_RST
#define BCHP_AFEC_CNTR_CTRL BCHP_AFEC_0_CNTR_CTRL
#define BCHP_AFEC_TEST_CONFIG BCHP_AFEC_0_TEST_CONFIG
#define BCHP_AFEC_ACM_MAX_ITER_OVERIDE BCHP_AFEC_0_ACM_MAX_ITER_OVERIDE
#define BCHP_AFEC_ACM_MODCOD_1 BCHP_AFEC_0_ACM_MODCOD_1
#define BCHP_AFEC_ACM_MODCOD_2 BCHP_AFEC_0_ACM_MODCOD_2
#define BCHP_AFEC_ACM_MODCOD_3 BCHP_AFEC_0_ACM_MODCOD_3
#define BCHP_AFEC_ACM_MODCOD_4 BCHP_AFEC_0_ACM_MODCOD_4
#define BCHP_AFEC_ACM_MODCOD_5 BCHP_AFEC_0_ACM_MODCOD_5
#define BCHP_AFEC_ACM_MODCOD_6 BCHP_AFEC_0_ACM_MODCOD_6
#define BCHP_AFEC_ACM_MODCOD_7 BCHP_AFEC_0_ACM_MODCOD_7
#define BCHP_AFEC_ACM_MODCOD_8 BCHP_AFEC_0_ACM_MODCOD_8
#define BCHP_AFEC_ACM_MODCOD_9 BCHP_AFEC_0_ACM_MODCOD_9
#define BCHP_AFEC_ACM_MODCOD_10 BCHP_AFEC_0_ACM_MODCOD_10
#define BCHP_AFEC_ACM_MODCOD_11 BCHP_AFEC_0_ACM_MODCOD_11
#define BCHP_AFEC_ACM_MODCOD_12 BCHP_AFEC_0_ACM_MODCOD_12
#define BCHP_AFEC_ACM_MODCOD_13 BCHP_AFEC_0_ACM_MODCOD_13
#define BCHP_AFEC_ACM_MODCOD_14 BCHP_AFEC_0_ACM_MODCOD_14
#define BCHP_AFEC_ACM_MODCOD_15 BCHP_AFEC_0_ACM_MODCOD_15
#define BCHP_AFEC_ACM_MODCOD_16 BCHP_AFEC_0_ACM_MODCOD_16
#define BCHP_AFEC_ACM_MODCOD_17 BCHP_AFEC_0_ACM_MODCOD_17
#define BCHP_AFEC_ACM_MODCOD_18 BCHP_AFEC_0_ACM_MODCOD_18
#define BCHP_AFEC_ACM_MODCOD_19 BCHP_AFEC_0_ACM_MODCOD_19
#define BCHP_AFEC_ACM_MODCOD_20 BCHP_AFEC_0_ACM_MODCOD_20
#define BCHP_AFEC_ACM_MODCOD_21 BCHP_AFEC_0_ACM_MODCOD_21
#define BCHP_AFEC_ACM_MODCOD_22 BCHP_AFEC_0_ACM_MODCOD_22
#define BCHP_AFEC_ACM_MODCOD_23 BCHP_AFEC_0_ACM_MODCOD_23
#define BCHP_AFEC_ACM_MODCOD_24 BCHP_AFEC_0_ACM_MODCOD_24
#define BCHP_AFEC_ACM_MODCOD_25 BCHP_AFEC_0_ACM_MODCOD_25
#define BCHP_AFEC_ACM_MODCOD_26 BCHP_AFEC_0_ACM_MODCOD_26
#define BCHP_AFEC_ACM_MODCOD_27 BCHP_AFEC_0_ACM_MODCOD_27
#define BCHP_AFEC_ACM_MODCOD_28 BCHP_AFEC_0_ACM_MODCOD_28
#define BCHP_AFEC_ACM_MODCOD_29_EXT BCHP_AFEC_0_ACM_MODCOD_29_EXT
#define BCHP_AFEC_ACM_MODCOD_29_LDPC0_EXT BCHP_AFEC_0_ACM_MODCOD_29_LDPC0_EXT
#define BCHP_AFEC_ACM_MODCOD_30_EXT BCHP_AFEC_0_ACM_MODCOD_30_EXT
#define BCHP_AFEC_ACM_MODCOD_30_LDPC0_EXT BCHP_AFEC_0_ACM_MODCOD_30_LDPC0_EXT
#define BCHP_AFEC_ACM_MODCOD_31_EXT BCHP_AFEC_0_ACM_MODCOD_31_EXT
#define BCHP_AFEC_ACM_MODCOD_31_LDPC0_EXT BCHP_AFEC_0_ACM_MODCOD_31_LDPC0_EXT
#define BCHP_AFEC_ACM_SYM_CNT_0 BCHP_AFEC_0_ACM_SYM_CNT_0
#define BCHP_AFEC_ACM_SYM_CNT_1 BCHP_AFEC_0_ACM_SYM_CNT_1
#define BCHP_AFEC_ACM_SYM_CNT_2 BCHP_AFEC_0_ACM_SYM_CNT_2
#define BCHP_AFEC_ACM_CYCLE_CNT_0 BCHP_AFEC_0_ACM_CYCLE_CNT_0
#define BCHP_AFEC_ACM_CYCLE_CNT_1 BCHP_AFEC_0_ACM_CYCLE_CNT_1
#define BCHP_AFEC_ACM_CYCLE_CNT_2 BCHP_AFEC_0_ACM_CYCLE_CNT_2
#define BCHP_AFEC_ACM_CYCLE_CNT_3 BCHP_AFEC_0_ACM_CYCLE_CNT_3
#define BCHP_AFEC_ACM_CYCLE_CNT_4 BCHP_AFEC_0_ACM_CYCLE_CNT_4
#define BCHP_AFEC_ACM_MISC_0 BCHP_AFEC_0_ACM_MISC_0
#define BCHP_AFEC_ACM_MISC_1 BCHP_AFEC_0_ACM_MISC_1
#define BCHP_AFEC_ACM_MODCOD_OVERIDE BCHP_AFEC_0_ACM_MODCOD_OVERIDE
#define BCHP_AFEC_ACM_MODCOD_STATS_CONFIG BCHP_AFEC_0_ACM_MODCOD_STATS_CONFIG
#define BCHP_AFEC_ACM_DONT_DEC_CNT BCHP_AFEC_0_ACM_DONT_DEC_CNT
#define BCHP_AFEC_ACM_LDPC_ITER_CNT BCHP_AFEC_0_ACM_LDPC_ITER_CNT
#define BCHP_AFEC_ACM_LDPC_FAIL_CNT BCHP_AFEC_0_ACM_LDPC_FAIL_CNT
#define BCHP_AFEC_ACM_LDPC_FRM_CNT BCHP_AFEC_0_ACM_LDPC_FRM_CNT
#define BCHP_AFEC_LDPC_CONFIG_0 BCHP_AFEC_0_LDPC_CONFIG_0
#define BCHP_AFEC_LDPC_STATUS BCHP_AFEC_0_LDPC_STATUS
#define BCHP_AFEC_LDPC_MET_CRC BCHP_AFEC_0_LDPC_MET_CRC
#define BCHP_AFEC_LDPC_EDGE_CRC BCHP_AFEC_0_LDPC_EDGE_CRC
#define BCHP_AFEC_LDPC_PSL_CTL BCHP_AFEC_0_LDPC_PSL_CTL
#define BCHP_AFEC_LDPC_PSL_INT_THRES BCHP_AFEC_0_LDPC_PSL_INT_THRES
#define BCHP_AFEC_LDPC_PSL_INT BCHP_AFEC_0_LDPC_PSL_INT
#define BCHP_AFEC_LDPC_PSL_AVE BCHP_AFEC_0_LDPC_PSL_AVE
#define BCHP_AFEC_LDPC_PSL_XCS BCHP_AFEC_0_LDPC_PSL_XCS
#define BCHP_AFEC_LDPC_PSL_FILTER BCHP_AFEC_0_LDPC_PSL_FILTER
#define BCHP_AFEC_BCH_TPCTL BCHP_AFEC_0_BCH_TPCTL
#define BCHP_AFEC_BCH_TPSIG BCHP_AFEC_0_BCH_TPSIG
#define BCHP_AFEC_BCH_CTRL BCHP_AFEC_0_BCH_CTRL
#define BCHP_AFEC_BCH_DECNBLK BCHP_AFEC_0_BCH_DECNBLK
#define BCHP_AFEC_BCH_DECCBLK BCHP_AFEC_0_BCH_DECCBLK
#define BCHP_AFEC_BCH_DECBBLK BCHP_AFEC_0_BCH_DECBBLK
#define BCHP_AFEC_BCH_DECCBIT BCHP_AFEC_0_BCH_DECCBIT
#define BCHP_AFEC_BCH_DECMCOR BCHP_AFEC_0_BCH_DECMCOR
#define BCHP_AFEC_BCH_BBHDR0 BCHP_AFEC_0_BCH_BBHDR0
#define BCHP_AFEC_BCH_BBHDR1 BCHP_AFEC_0_BCH_BBHDR1
#define BCHP_AFEC_BCH_BBHDR2 BCHP_AFEC_0_BCH_BBHDR2
#define BCHP_AFEC_BCH_BBHDR3 BCHP_AFEC_0_BCH_BBHDR3
#define BCHP_AFEC_BCH_BBHDR4 BCHP_AFEC_0_BCH_BBHDR4
#define BCHP_AFEC_BCH_BBHDR5 BCHP_AFEC_0_BCH_BBHDR5
#define BCHP_AFEC_BCH_MPLCK BCHP_AFEC_0_BCH_MPLCK
#define BCHP_AFEC_BCH_MPCFG BCHP_AFEC_0_BCH_MPCFG
#define BCHP_AFEC_BCH_SMCFG BCHP_AFEC_0_BCH_SMCFG
#define BCHP_AFEC_GLOBAL_CLK_CNTRL BCHP_AFEC_GLOBAL_0_CLK_CNTRL
#define BCHP_AFEC_GLOBAL_PWR_CNTRL BCHP_AFEC_GLOBAL_0_PWR_CNTRL
#define BCHP_AFEC_GR_BRIDGE_REVISION BCHP_AFEC_GR_BRIDGE_0_REVISION
#define BCHP_AFEC_GR_BRIDGE_CTRL BCHP_AFEC_GR_BRIDGE_0_CTRL
#define BCHP_AFEC_GR_BRIDGE_SW_RESET_0 BCHP_AFEC_GR_BRIDGE_0_SW_RESET_0
#define BCHP_AFEC_GR_BRIDGE_SW_RESET_1 BCHP_AFEC_GR_BRIDGE_0_SW_RESET_1
#define BCHP_AFEC_INTR_CTRL2_CPU_STATUS BCHP_AFEC_INTR_CTRL2_0_CPU_STATUS
#define BCHP_AFEC_INTR_CTRL2_CPU_SET BCHP_AFEC_INTR_CTRL2_0_CPU_SET
#define BCHP_AFEC_INTR_CTRL2_CPU_CLEAR BCHP_AFEC_INTR_CTRL2_0_CPU_CLEAR
#define BCHP_AFEC_INTR_CTRL2_CPU_MASK_STATUS BCHP_AFEC_INTR_CTRL2_0_CPU_MASK_STATUS
#define BCHP_AFEC_INTR_CTRL2_CPU_MASK_SET BCHP_AFEC_INTR_CTRL2_0_CPU_MASK_SET
#define BCHP_AFEC_INTR_CTRL2_CPU_MASK_CLEAR BCHP_AFEC_INTR_CTRL2_0_CPU_MASK_CLEAR
#define BCHP_AFEC_INTR_CTRL2_PCI_STATUS BCHP_AFEC_INTR_CTRL2_0_PCI_STATUS
#define BCHP_AFEC_INTR_CTRL2_PCI_SET BCHP_AFEC_INTR_CTRL2_0_PCI_SET
#define BCHP_AFEC_INTR_CTRL2_PCI_CLEAR BCHP_AFEC_INTR_CTRL2_0_PCI_CLEAR
#define BCHP_AFEC_INTR_CTRL2_PCI_MASK_STATUS BCHP_AFEC_INTR_CTRL2_0_PCI_MASK_STATUS
#define BCHP_AFEC_INTR_CTRL2_PCI_MASK_SET BCHP_AFEC_INTR_CTRL2_0_PCI_MASK_SET
#define BCHP_AFEC_INTR_CTRL2_PCI_MASK_CLEAR BCHP_AFEC_INTR_CTRL2_0_PCI_MASK_CLEAR

#define BCHP_SDS_AGC_AGCCTL BCHP_SDS_AGC_0_AGCCTL
#define BCHP_SDS_AGC_IAGCTH BCHP_SDS_AGC_0_IAGCTH
#define BCHP_SDS_AGC_DSGIN BCHP_SDS_AGC_0_DSGIN
#define BCHP_SDS_AGC_ATHR BCHP_SDS_AGC_0_ATHR
#define BCHP_SDS_AGC_ABW BCHP_SDS_AGC_0_ABW
#define BCHP_SDS_AGC_AII BCHP_SDS_AGC_0_AII
#define BCHP_SDS_AGC_AGI BCHP_SDS_AGC_0_AGI
#define BCHP_SDS_AGC_AIT BCHP_SDS_AGC_0_AIT
#define BCHP_SDS_AGC_AGT BCHP_SDS_AGC_0_AGT
#define BCHP_SDS_AGC_AGCLI BCHP_SDS_AGC_0_AGCLI
#define BCHP_SDS_BERT_BERCTL BCHP_SDS_BERT_0_BERCTL
#define BCHP_SDS_BERT_BEIT BCHP_SDS_BERT_0_BEIT
#define BCHP_SDS_BERT_BERC BCHP_SDS_BERT_0_BERC
#define BCHP_SDS_BERT_BEM1 BCHP_SDS_BERT_0_BEM1
#define BCHP_SDS_BERT_BEM2 BCHP_SDS_BERT_0_BEM2
#define BCHP_SDS_BERT_BEM3 BCHP_SDS_BERT_0_BEM3
#define BCHP_SDS_BERT_BEST BCHP_SDS_BERT_0_BEST
#define BCHP_SDS_BERT_ACMCTL BCHP_SDS_BERT_0_ACMCTL
#define BCHP_SDS_BL_BLPCTL BCHP_SDS_BL_0_BLPCTL
#define BCHP_SDS_BL_PFCTL BCHP_SDS_BL_0_PFCTL
#define BCHP_SDS_BL_BRSW BCHP_SDS_BL_0_BRSW
#define BCHP_SDS_BL_BRLC BCHP_SDS_BL_0_BRLC
#define BCHP_SDS_BL_BRIC BCHP_SDS_BL_0_BRIC
#define BCHP_SDS_BL_BRI BCHP_SDS_BL_0_BRI
#define BCHP_SDS_BL_BFOS BCHP_SDS_BL_0_BFOS
#define BCHP_SDS_BL_BRFO BCHP_SDS_BL_0_BRFO
#define BCHP_SDS_BL_BNCO BCHP_SDS_BL_0_BNCO
#define BCHP_SDS_CG_RSTCTL BCHP_SDS_CG_0_RSTCTL
#define BCHP_SDS_CG_CGDIV00 BCHP_SDS_CG_0_CGDIV00
#define BCHP_SDS_CG_CGDIV01 BCHP_SDS_CG_0_CGDIV01
#define BCHP_SDS_CG_SPLL_NPDIV BCHP_SDS_CG_0_SPLL_NPDIV
#define BCHP_SDS_CG_SPLL_MDIV_CTRL BCHP_SDS_CG_0_SPLL_MDIV_CTRL
#define BCHP_SDS_CG_SPLL_CTRL BCHP_SDS_CG_0_SPLL_CTRL
#define BCHP_SDS_CG_SPLL_SSC_CTRL1 BCHP_SDS_CG_0_SPLL_SSC_CTRL1
#define BCHP_SDS_CG_SPLL_SSC_CTRL0 BCHP_SDS_CG_0_SPLL_SSC_CTRL0
#define BCHP_SDS_CG_SPLL_STATUS BCHP_SDS_CG_0_SPLL_STATUS
#define BCHP_SDS_CG_SPLL_PWRDN_RST BCHP_SDS_CG_0_SPLL_PWRDN_RST
#define BCHP_SDS_CL_CLCTL1 BCHP_SDS_CL_0_CLCTL1
#define BCHP_SDS_CL_CLCTL2 BCHP_SDS_CL_0_CLCTL2
#define BCHP_SDS_CL_FLLC BCHP_SDS_CL_0_FLLC
#define BCHP_SDS_CL_FLLC1 BCHP_SDS_CL_0_FLLC1
#define BCHP_SDS_CL_FLIC BCHP_SDS_CL_0_FLIC
#define BCHP_SDS_CL_FLIC1 BCHP_SDS_CL_0_FLIC1
#define BCHP_SDS_CL_FLSW BCHP_SDS_CL_0_FLSW
#define BCHP_SDS_CL_FLI BCHP_SDS_CL_0_FLI
#define BCHP_SDS_CL_FLIF BCHP_SDS_CL_0_FLIF
#define BCHP_SDS_CL_FLPA BCHP_SDS_CL_0_FLPA
#define BCHP_SDS_CL_FLTD BCHP_SDS_CL_0_FLTD
#define BCHP_SDS_CL_PEEST BCHP_SDS_CL_0_PEEST
#define BCHP_SDS_CL_PLTD BCHP_SDS_CL_0_PLTD
#define BCHP_SDS_CL_PLC BCHP_SDS_CL_0_PLC
#define BCHP_SDS_CL_PLC1 BCHP_SDS_CL_0_PLC1
#define BCHP_SDS_CL_PLSW BCHP_SDS_CL_0_PLSW
#define BCHP_SDS_CL_PLI BCHP_SDS_CL_0_PLI
#define BCHP_SDS_CL_PLPA BCHP_SDS_CL_0_PLPA
#define BCHP_SDS_CL_CRBFD BCHP_SDS_CL_0_CRBFD
#define BCHP_SDS_CL_CLHT BCHP_SDS_CL_0_CLHT
#define BCHP_SDS_CL_CLLT BCHP_SDS_CL_0_CLLT
#define BCHP_SDS_CL_CLLA BCHP_SDS_CL_0_CLLA
#define BCHP_SDS_CL_CLCT BCHP_SDS_CL_0_CLCT
#define BCHP_SDS_CL_CLFFCTL BCHP_SDS_CL_0_CLFFCTL
#define BCHP_SDS_CL_FFLPA BCHP_SDS_CL_0_FFLPA
#define BCHP_SDS_CL_CLFBCTL BCHP_SDS_CL_0_CLFBCTL
#define BCHP_SDS_CL_FBLC BCHP_SDS_CL_0_FBLC
#define BCHP_SDS_CL_FBLI BCHP_SDS_CL_0_FBLI
#define BCHP_SDS_CL_FBPA BCHP_SDS_CL_0_FBPA
#define BCHP_SDS_CL_CLDAFECTL BCHP_SDS_CL_0_CLDAFECTL
#define BCHP_SDS_CL_DAFELI BCHP_SDS_CL_0_DAFELI
#define BCHP_SDS_CL_DAFEINT BCHP_SDS_CL_0_DAFEINT
#define BCHP_SDS_DFT_CTRL0 BCHP_SDS_DFT_0_CTRL0
#define BCHP_SDS_DFT_CTRL1 BCHP_SDS_DFT_0_CTRL1
#define BCHP_SDS_DFT_STATUS BCHP_SDS_DFT_0_STATUS
#define BCHP_SDS_DFT_RANGE_START BCHP_SDS_DFT_0_RANGE_START
#define BCHP_SDS_DFT_RANGE_END BCHP_SDS_DFT_0_RANGE_END
#define BCHP_SDS_DFT_DDFS_FCW BCHP_SDS_DFT_0_DDFS_FCW
#define BCHP_SDS_DFT_PEAK_POW BCHP_SDS_DFT_0_PEAK_POW
#define BCHP_SDS_DFT_PEAK_BIN BCHP_SDS_DFT_0_PEAK_BIN
#define BCHP_SDS_DFT_TOTAL_POW BCHP_SDS_DFT_0_TOTAL_POW
#define BCHP_SDS_DFT_MEM_RADDR BCHP_SDS_DFT_0_MEM_RADDR
#define BCHP_SDS_DFT_MEM_RDATA BCHP_SDS_DFT_0_MEM_RDATA
#define BCHP_SDS_DSEC_DSRST BCHP_SDS_DSEC_0_DSRST
#define BCHP_SDS_DSEC_DSCGDIV BCHP_SDS_DSEC_0_DSCGDIV
#define BCHP_SDS_DSEC_DSCTL00 BCHP_SDS_DSEC_0_DSCTL00
#define BCHP_SDS_DSEC_DSCTL01 BCHP_SDS_DSEC_0_DSCTL01
#define BCHP_SDS_DSEC_DSCTL02 BCHP_SDS_DSEC_0_DSCTL02
#define BCHP_SDS_DSEC_DSCTL03 BCHP_SDS_DSEC_0_DSCTL03
#define BCHP_SDS_DSEC_DSCMD BCHP_SDS_DSEC_0_DSCMD
#define BCHP_SDS_DSEC_DSRPLY BCHP_SDS_DSEC_0_DSRPLY
#define BCHP_SDS_DSEC_DSCMEMADR BCHP_SDS_DSEC_0_DSCMEMADR
#define BCHP_SDS_DSEC_DSCMEMDAT BCHP_SDS_DSEC_0_DSCMEMDAT
#define BCHP_SDS_DSEC_DSFIRCTL BCHP_SDS_DSEC_0_DSFIRCTL
#define BCHP_SDS_DSEC_DS_MISC_CONTROL BCHP_SDS_DSEC_0_DS_MISC_CONTROL
#define BCHP_SDS_DSEC_DS_PARITY BCHP_SDS_DSEC_0_DS_PARITY
#define BCHP_SDS_DSEC_ADCTL BCHP_SDS_DSEC_0_ADCTL
#define BCHP_SDS_DSEC_Q15T BCHP_SDS_DSEC_0_Q15T
#define BCHP_SDS_DSEC_TPWC BCHP_SDS_DSEC_0_TPWC
#define BCHP_SDS_DSEC_RXBT BCHP_SDS_DSEC_0_RXBT
#define BCHP_SDS_DSEC_RXRT BCHP_SDS_DSEC_0_RXRT
#define BCHP_SDS_DSEC_RBDT BCHP_SDS_DSEC_0_RBDT
#define BCHP_SDS_DSEC_SLEW BCHP_SDS_DSEC_0_SLEW
#define BCHP_SDS_DSEC_RERT BCHP_SDS_DSEC_0_RERT
#define BCHP_SDS_DSEC_DSCT BCHP_SDS_DSEC_0_DSCT
#define BCHP_SDS_DSEC_DTCT BCHP_SDS_DSEC_0_DTCT
#define BCHP_SDS_DSEC_DDIO BCHP_SDS_DSEC_0_DDIO
#define BCHP_SDS_DSEC_RTDC1 BCHP_SDS_DSEC_0_RTDC1
#define BCHP_SDS_DSEC_RTDC2 BCHP_SDS_DSEC_0_RTDC2
#define BCHP_SDS_DSEC_TCTL BCHP_SDS_DSEC_0_TCTL
#define BCHP_SDS_DSEC_CICC BCHP_SDS_DSEC_0_CICC
#define BCHP_SDS_DSEC_FCIC BCHP_SDS_DSEC_0_FCIC
#define BCHP_SDS_DSEC_SCIC BCHP_SDS_DSEC_0_SCIC
#define BCHP_SDS_DSEC_TSTM BCHP_SDS_DSEC_0_TSTM
#define BCHP_SDS_DSEC_DST1 BCHP_SDS_DSEC_0_DST1
#define BCHP_SDS_DSEC_DST2 BCHP_SDS_DSEC_0_DST2
#define BCHP_SDS_DSEC_DS_SAR_THRSH BCHP_SDS_DSEC_0_DS_SAR_THRSH
#define BCHP_SDS_DSEC_DS_SAR_DATA_OUT BCHP_SDS_DSEC_0_DS_SAR_DATA_OUT
#define BCHP_SDS_DSEC_DS_SAR_DC_OFFSET BCHP_SDS_DSEC_0_DS_SAR_DC_OFFSET
#define BCHP_SDS_DSEC_DS_SAR_LPF_INT BCHP_SDS_DSEC_0_DS_SAR_LPF_INT
#define BCHP_SDS_DSEC_DS_SAR_CONTROL BCHP_SDS_DSEC_0_DS_SAR_CONTROL
#define BCHP_SDS_DSEC_DS_COMMON_CONTROL BCHP_SDS_DSEC_0_DS_COMMON_CONTROL
#define BCHP_SDS_DSEC_DSTMRCTL BCHP_SDS_DSEC_0_DSTMRCTL
#define BCHP_SDS_DSEC_DSGENTMR1 BCHP_SDS_DSEC_0_DSGENTMR1
#define BCHP_SDS_DSEC_DSGENTMR2 BCHP_SDS_DSEC_0_DSGENTMR2
#define BCHP_SDS_EQ_EQMISCCTL BCHP_SDS_EQ_0_EQMISCCTL
#define BCHP_SDS_EQ_EQFFECTL BCHP_SDS_EQ_0_EQFFECTL
#define BCHP_SDS_EQ_EQCFAD BCHP_SDS_EQ_0_EQCFAD
#define BCHP_SDS_EQ_EQFRZCTL BCHP_SDS_EQ_0_EQFRZCTL
#define BCHP_SDS_EQ_F0B BCHP_SDS_EQ_0_F0B
#define BCHP_SDS_EQ_HD8PSK1 BCHP_SDS_EQ_0_HD8PSK1
#define BCHP_SDS_EQ_HD8PSK2 BCHP_SDS_EQ_0_HD8PSK2
#define BCHP_SDS_EQ_HDQPSK BCHP_SDS_EQ_0_HDQPSK
#define BCHP_SDS_EQ_HD16QAM BCHP_SDS_EQ_0_HD16QAM
#define BCHP_SDS_EQ_CMA BCHP_SDS_EQ_0_CMA
#define BCHP_SDS_EQ_CMATH BCHP_SDS_EQ_0_CMATH
#define BCHP_SDS_EQ_VLCTL BCHP_SDS_EQ_0_VLCTL
#define BCHP_SDS_EQ_VLCI BCHP_SDS_EQ_0_VLCI
#define BCHP_SDS_EQ_VLCQ BCHP_SDS_EQ_0_VLCQ
#define BCHP_SDS_EQ_VCOS BCHP_SDS_EQ_0_VCOS
#define BCHP_SDS_EQ_TSFT BCHP_SDS_EQ_0_TSFT
#define BCHP_SDS_EQ_EQSFT BCHP_SDS_EQ_0_EQSFT
#define BCHP_SDS_EQ_PILOTCTL BCHP_SDS_EQ_0_PILOTCTL
#define BCHP_SDS_EQ_PLDCTL BCHP_SDS_EQ_0_PLDCTL
#define BCHP_SDS_EQ_HDRD BCHP_SDS_EQ_0_HDRD
#define BCHP_SDS_EQ_HDRA BCHP_SDS_EQ_0_HDRA
#define BCHP_SDS_EQ_XSEED BCHP_SDS_EQ_0_XSEED
#define BCHP_SDS_EQ_XTAP1 BCHP_SDS_EQ_0_XTAP1
#define BCHP_SDS_EQ_XTAP2 BCHP_SDS_EQ_0_XTAP2
#define BCHP_SDS_EQ_LUPD BCHP_SDS_EQ_0_LUPD
#define BCHP_SDS_EQ_LUPA BCHP_SDS_EQ_0_LUPA
#define BCHP_SDS_EQ_SDSLEN BCHP_SDS_EQ_0_SDSLEN
#define BCHP_SDS_EQ_SDSIG BCHP_SDS_EQ_0_SDSIG
#define BCHP_SDS_EQ_MGAIND BCHP_SDS_EQ_0_MGAIND
#define BCHP_SDS_EQ_MGAINA BCHP_SDS_EQ_0_MGAINA
#define BCHP_SDS_FE_ADCPCTL BCHP_SDS_FE_0_ADCPCTL
#define BCHP_SDS_FE_DCOCTL BCHP_SDS_FE_0_DCOCTL
#define BCHP_SDS_FE_DCOI BCHP_SDS_FE_0_DCOI
#define BCHP_SDS_FE_IQCTL BCHP_SDS_FE_0_IQCTL
#define BCHP_SDS_FE_IQAEST BCHP_SDS_FE_0_IQAEST
#define BCHP_SDS_FE_IQPEST BCHP_SDS_FE_0_IQPEST
#define BCHP_SDS_FE_MIXCTL BCHP_SDS_FE_0_MIXCTL
#define BCHP_SDS_FE_DSTGCTL BCHP_SDS_FE_0_DSTGCTL
#define BCHP_SDS_FE_FILTCTL BCHP_SDS_FE_0_FILTCTL
#define BCHP_SDS_FE_DFCTL BCHP_SDS_FE_0_DFCTL
#define BCHP_SDS_FE_AGFCTL BCHP_SDS_FE_0_AGFCTL
#define BCHP_SDS_FE_AGF BCHP_SDS_FE_0_AGF
#define BCHP_SDS_FE_AIF BCHP_SDS_FE_0_AIF
#define BCHP_SDS_FE_NVCTL BCHP_SDS_FE_0_NVCTL
#define BCHP_SDS_FEC_FECTL BCHP_SDS_FEC_0_FECTL
#define BCHP_SDS_FEC_FSYN BCHP_SDS_FEC_0_FSYN
#define BCHP_SDS_FEC_FRS BCHP_SDS_FEC_0_FRS
#define BCHP_SDS_FEC_FMOD BCHP_SDS_FEC_0_FMOD
#define BCHP_SDS_FEC_FERR BCHP_SDS_FEC_0_FERR
#define BCHP_SDS_FEC_FRSV BCHP_SDS_FEC_0_FRSV
#define BCHP_SDS_GR_BRIDGE_REVISION BCHP_SDS_GR_BRIDGE_0_REVISION
#define BCHP_SDS_GR_BRIDGE_CTRL BCHP_SDS_GR_BRIDGE_0_CTRL
#define BCHP_SDS_GR_BRIDGE_SW_INIT_0 BCHP_SDS_GR_BRIDGE_0_SW_INIT_0
#define BCHP_SDS_GR_BRIDGE_SW_INIT_1 BCHP_SDS_GR_BRIDGE_0_SW_INIT_1
#define BCHP_SDS_HP_HPCONTROL BCHP_SDS_HP_0_HPCONTROL
#define BCHP_SDS_HP_HPCONFIG BCHP_SDS_HP_0_HPCONFIG
#define BCHP_SDS_HP_FNORM BCHP_SDS_HP_0_FNORM
#define BCHP_SDS_HP_HPOVERRIDE BCHP_SDS_HP_0_HPOVERRIDE
#define BCHP_SDS_HP_FROF1 BCHP_SDS_HP_0_FROF1
#define BCHP_SDS_HP_FROF2 BCHP_SDS_HP_0_FROF2
#define BCHP_SDS_HP_FROF3 BCHP_SDS_HP_0_FROF3
#define BCHP_SDS_HP_FROF1_SW BCHP_SDS_HP_0_FROF1_SW
#define BCHP_SDS_HP_FROF2_SW BCHP_SDS_HP_0_FROF2_SW
#define BCHP_SDS_HP_FROF3_SW BCHP_SDS_HP_0_FROF3_SW
#define BCHP_SDS_HP_M_N_PEAK_VERIFY BCHP_SDS_HP_0_M_N_PEAK_VERIFY
#define BCHP_SDS_HP_M_N_RECEIVER_VERIFY BCHP_SDS_HP_0_M_N_RECEIVER_VERIFY
#define BCHP_SDS_HP_M_N_RECEIVER_LOCK BCHP_SDS_HP_0_M_N_RECEIVER_LOCK
#define BCHP_SDS_HP_DCORR_THRESHOLD BCHP_SDS_HP_0_DCORR_THRESHOLD
#define BCHP_SDS_HP_PLHDRSCR1 BCHP_SDS_HP_0_PLHDRSCR1
#define BCHP_SDS_HP_PLHDRSCR2 BCHP_SDS_HP_0_PLHDRSCR2
#define BCHP_SDS_HP_PLHDRSCR3 BCHP_SDS_HP_0_PLHDRSCR3
#define BCHP_SDS_HP_ACM_CHECK BCHP_SDS_HP_0_ACM_CHECK
#define BCHP_SDS_HP_FRAME_LENGTH_INITIAL BCHP_SDS_HP_0_FRAME_LENGTH_INITIAL
#define BCHP_SDS_HP_FRAME_LENGTH_DUMMY_NORMAL BCHP_SDS_HP_0_FRAME_LENGTH_DUMMY_NORMAL
#define BCHP_SDS_HP_FRAME_LENGTH_QPSK_NORMAL BCHP_SDS_HP_0_FRAME_LENGTH_QPSK_NORMAL
#define BCHP_SDS_HP_FRAME_LENGTH_8PSK_NORMAL BCHP_SDS_HP_0_FRAME_LENGTH_8PSK_NORMAL
#define BCHP_SDS_HP_FRAME_LENGTH_16APSK_NORMAL BCHP_SDS_HP_0_FRAME_LENGTH_16APSK_NORMAL
#define BCHP_SDS_HP_FRAME_LENGTH_32APSK_NORMAL BCHP_SDS_HP_0_FRAME_LENGTH_32APSK_NORMAL
#define BCHP_SDS_HP_FRAME_LENGTH_RESERVED_29_NORMAL BCHP_SDS_HP_0_FRAME_LENGTH_RESERVED_29_NORMAL
#define BCHP_SDS_HP_FRAME_LENGTH_RESERVED_30_NORMAL BCHP_SDS_HP_0_FRAME_LENGTH_RESERVED_30_NORMAL
#define BCHP_SDS_HP_FRAME_LENGTH_RESERVED_31_NORMAL BCHP_SDS_HP_0_FRAME_LENGTH_RESERVED_31_NORMAL
#define BCHP_SDS_HP_FRAME_LENGTH_DUMMY_SHORT BCHP_SDS_HP_0_FRAME_LENGTH_DUMMY_SHORT
#define BCHP_SDS_HP_FRAME_LENGTH_QPSK_SHORT BCHP_SDS_HP_0_FRAME_LENGTH_QPSK_SHORT
#define BCHP_SDS_HP_FRAME_LENGTH_8PSK_SHORT BCHP_SDS_HP_0_FRAME_LENGTH_8PSK_SHORT
#define BCHP_SDS_HP_FRAME_LENGTH_16APSK_SHORT BCHP_SDS_HP_0_FRAME_LENGTH_16APSK_SHORT
#define BCHP_SDS_HP_FRAME_LENGTH_32APSK_SHORT BCHP_SDS_HP_0_FRAME_LENGTH_32APSK_SHORT
#define BCHP_SDS_HP_FRAME_LENGTH_RESERVED_29_SHORT BCHP_SDS_HP_0_FRAME_LENGTH_RESERVED_29_SHORT
#define BCHP_SDS_HP_FRAME_LENGTH_RESERVED_30_SHORT BCHP_SDS_HP_0_FRAME_LENGTH_RESERVED_30_SHORT
#define BCHP_SDS_HP_FRAME_LENGTH_RESERVED_31_SHORT BCHP_SDS_HP_0_FRAME_LENGTH_RESERVED_31_SHORT
#define BCHP_SDS_HP_FRAME_LENGTH_SAMPLE BCHP_SDS_HP_0_FRAME_LENGTH_SAMPLE
#define BCHP_SDS_HP_PEAK_SAMPLE_1_0 BCHP_SDS_HP_0_PEAK_SAMPLE_1_0
#define BCHP_SDS_HP_PEAK_SAMPLE_3_2 BCHP_SDS_HP_0_PEAK_SAMPLE_3_2
#define BCHP_SDS_INTR2_0_CPU_STATUS BCHP_SDS_INTR2_0_0_CPU_STATUS
#define BCHP_SDS_INTR2_0_CPU_SET BCHP_SDS_INTR2_0_0_CPU_SET
#define BCHP_SDS_INTR2_0_CPU_CLEAR BCHP_SDS_INTR2_0_0_CPU_CLEAR
#define BCHP_SDS_INTR2_0_CPU_MASK_STATUS BCHP_SDS_INTR2_0_0_CPU_MASK_STATUS
#define BCHP_SDS_INTR2_0_CPU_MASK_SET BCHP_SDS_INTR2_0_0_CPU_MASK_SET
#define BCHP_SDS_INTR2_0_CPU_MASK_CLEAR BCHP_SDS_INTR2_0_0_CPU_MASK_CLEAR
#define BCHP_SDS_INTR2_0_PCI_STATUS BCHP_SDS_INTR2_0_0_PCI_STATUS
#define BCHP_SDS_INTR2_0_PCI_SET BCHP_SDS_INTR2_0_0_PCI_SET
#define BCHP_SDS_INTR2_0_PCI_CLEAR BCHP_SDS_INTR2_0_0_PCI_CLEAR
#define BCHP_SDS_INTR2_0_PCI_MASK_STATUS BCHP_SDS_INTR2_0_0_PCI_MASK_STATUS
#define BCHP_SDS_INTR2_0_PCI_MASK_SET BCHP_SDS_INTR2_0_0_PCI_MASK_SET
#define BCHP_SDS_INTR2_0_PCI_MASK_CLEAR BCHP_SDS_INTR2_0_0_PCI_MASK_CLEAR
#define BCHP_SDS_INTR2_1_CPU_STATUS BCHP_SDS_INTR2_1_0_CPU_STATUS
#define BCHP_SDS_INTR2_1_CPU_SET BCHP_SDS_INTR2_1_0_CPU_SET
#define BCHP_SDS_INTR2_1_CPU_CLEAR BCHP_SDS_INTR2_1_0_CPU_CLEAR
#define BCHP_SDS_INTR2_1_CPU_MASK_STATUS BCHP_SDS_INTR2_1_0_CPU_MASK_STATUS
#define BCHP_SDS_INTR2_1_CPU_MASK_SET BCHP_SDS_INTR2_1_0_CPU_MASK_SET
#define BCHP_SDS_INTR2_1_CPU_MASK_CLEAR BCHP_SDS_INTR2_1_0_CPU_MASK_CLEAR
#define BCHP_SDS_INTR2_1_PCI_STATUS BCHP_SDS_INTR2_1_0_PCI_STATUS
#define BCHP_SDS_INTR2_1_PCI_SET BCHP_SDS_INTR2_1_0_PCI_SET
#define BCHP_SDS_INTR2_1_PCI_CLEAR BCHP_SDS_INTR2_1_0_PCI_CLEAR
#define BCHP_SDS_INTR2_1_PCI_MASK_STATUS BCHP_SDS_INTR2_1_0_PCI_MASK_STATUS
#define BCHP_SDS_INTR2_1_PCI_MASK_SET BCHP_SDS_INTR2_1_0_PCI_MASK_SET
#define BCHP_SDS_INTR2_1_PCI_MASK_CLEAR BCHP_SDS_INTR2_1_0_PCI_MASK_CLEAR
#define BCHP_SDS_MISC_REVID BCHP_SDS_MISC_0_REVID
#define BCHP_SDS_MISC_IICTL1 BCHP_SDS_MISC_0_IICTL1
#define BCHP_SDS_MISC_IICTL2 BCHP_SDS_MISC_0_IICTL2
#define BCHP_SDS_MISC_IICCNT BCHP_SDS_MISC_0_IICCNT
#define BCHP_SDS_MISC_IICHPA BCHP_SDS_MISC_0_IICHPA
#define BCHP_SDS_MISC_MIICTX1 BCHP_SDS_MISC_0_MIICTX1
#define BCHP_SDS_MISC_MIICTX2 BCHP_SDS_MISC_0_MIICTX2
#define BCHP_SDS_MISC_MIICRX1 BCHP_SDS_MISC_0_MIICRX1
#define BCHP_SDS_MISC_MIICRX2 BCHP_SDS_MISC_0_MIICRX2
#define BCHP_SDS_MISC_MI2CSA BCHP_SDS_MISC_0_MI2CSA
#define BCHP_SDS_MISC_TMRCTL BCHP_SDS_MISC_0_TMRCTL
#define BCHP_SDS_MISC_GENTMR3 BCHP_SDS_MISC_0_GENTMR3
#define BCHP_SDS_MISC_GENTMR2 BCHP_SDS_MISC_0_GENTMR2
#define BCHP_SDS_MISC_GENTMR1 BCHP_SDS_MISC_0_GENTMR1
#define BCHP_SDS_MISC_BERTMR BCHP_SDS_MISC_0_BERTMR
#define BCHP_SDS_MISC_BTMR BCHP_SDS_MISC_0_BTMR
#define BCHP_SDS_MISC_TPDIR BCHP_SDS_MISC_0_TPDIR
#define BCHP_SDS_MISC_TPODS BCHP_SDS_MISC_0_TPODS
#define BCHP_SDS_MISC_TPDS BCHP_SDS_MISC_0_TPDS
#define BCHP_SDS_MISC_TPCTL1 BCHP_SDS_MISC_0_TPCTL1
#define BCHP_SDS_MISC_TPCTL2 BCHP_SDS_MISC_0_TPCTL2
#define BCHP_SDS_MISC_TPCTL3 BCHP_SDS_MISC_0_TPCTL3
#define BCHP_SDS_MISC_TPOUT BCHP_SDS_MISC_0_TPOUT
#define BCHP_SDS_MISC_MISCTL BCHP_SDS_MISC_0_MISCTL
#define BCHP_SDS_MISC_INTR_RAW_STS0 BCHP_SDS_MISC_0_INTR_RAW_STS0
#define BCHP_SDS_MISC_INTR_RAW_STS1 BCHP_SDS_MISC_0_INTR_RAW_STS1
#if (BCHP_VER == BCHP_VER_A0)
#define BCHP_SDS_NTCH_CTRL BCHP_SDS_NTCH_0_CTRL
#define BCHP_SDS_NTCH_FCWADJ_SCL BCHP_SDS_NTCH_0_FCWADJ_SCL
#define BCHP_SDS_NTCH_FCW0 BCHP_SDS_NTCH_0_FCW0
#define BCHP_SDS_NTCH_FCW1 BCHP_SDS_NTCH_0_FCW1
#define BCHP_SDS_NTCH_FCW2 BCHP_SDS_NTCH_0_FCW2
#define BCHP_SDS_NTCH_FCW3 BCHP_SDS_NTCH_0_FCW3
#define BCHP_SDS_NTCH_DCO0_INT BCHP_SDS_NTCH_0_DCO0_INT
#define BCHP_SDS_NTCH_DCO1_INT BCHP_SDS_NTCH_0_DCO1_INT
#define BCHP_SDS_NTCH_DCO2_INT BCHP_SDS_NTCH_0_DCO2_INT
#else
#define BCHP_SDS_CWC_CTRL1 BCHP_SDS_CWC_0_CTRL1
#define BCHP_SDS_CWC_CTRL2 BCHP_SDS_CWC_0_CTRL2
#define BCHP_SDS_CWC_LEAK BCHP_SDS_CWC_0_LEAK
#define BCHP_SDS_CWC_SPUR_FCW1 BCHP_SDS_CWC_0_SPUR_FCW1
#define BCHP_SDS_CWC_SPUR_FCW2 BCHP_SDS_CWC_0_SPUR_FCW2
#define BCHP_SDS_CWC_SPUR_FCW3 BCHP_SDS_CWC_0_SPUR_FCW3
#define BCHP_SDS_CWC_SPUR_FCW4 BCHP_SDS_CWC_0_SPUR_FCW4
#define BCHP_SDS_CWC_SPUR_FCW5 BCHP_SDS_CWC_0_SPUR_FCW5
#define BCHP_SDS_CWC_SPUR_FCW6 BCHP_SDS_CWC_0_SPUR_FCW6
#define BCHP_SDS_CWC_LFC1 BCHP_SDS_CWC_0_LFC1
#define BCHP_SDS_CWC_LFC2 BCHP_SDS_CWC_0_LFC2
#define BCHP_SDS_CWC_LFC3 BCHP_SDS_CWC_0_LFC3
#define BCHP_SDS_CWC_LFC4 BCHP_SDS_CWC_0_LFC4
#define BCHP_SDS_CWC_LFC5 BCHP_SDS_CWC_0_LFC5
#define BCHP_SDS_CWC_LFC6 BCHP_SDS_CWC_0_LFC6
#define BCHP_SDS_CWC_INT1 BCHP_SDS_CWC_0_INT1
#define BCHP_SDS_CWC_INT2 BCHP_SDS_CWC_0_INT2
#define BCHP_SDS_CWC_INT3 BCHP_SDS_CWC_0_INT3
#define BCHP_SDS_CWC_INT4 BCHP_SDS_CWC_0_INT4
#define BCHP_SDS_CWC_INT5 BCHP_SDS_CWC_0_INT5
#define BCHP_SDS_CWC_INT6 BCHP_SDS_CWC_0_INT6
#define BCHP_SDS_CWC_COEFF_RWCTRL BCHP_SDS_CWC_0_COEFF_RWCTRL
#define BCHP_SDS_CWC_COEFF BCHP_SDS_CWC_0_COEFF
#define BCHP_SDS_CWC_FOFS1 BCHP_SDS_CWC_0_FOFS1
#define BCHP_SDS_CWC_FOFS2 BCHP_SDS_CWC_0_FOFS2
#define BCHP_SDS_CWC_FOFS3 BCHP_SDS_CWC_0_FOFS3
#define BCHP_SDS_CWC_FOFS4 BCHP_SDS_CWC_0_FOFS4
#define BCHP_SDS_CWC_FOFS5 BCHP_SDS_CWC_0_FOFS5
#define BCHP_SDS_CWC_FOFS6 BCHP_SDS_CWC_0_FOFS6
#endif
#define BCHP_SDS_OI_OIFCTL00 BCHP_SDS_OI_0_OIFCTL00
#define BCHP_SDS_OI_OIFCTL01 BCHP_SDS_OI_0_OIFCTL01
#define BCHP_SDS_OI_OIFCTL02 BCHP_SDS_OI_0_OIFCTL02
#define BCHP_SDS_OI_OPLL BCHP_SDS_OI_0_OPLL
#define BCHP_SDS_OI_OPLL2 BCHP_SDS_OI_0_OPLL2
#define BCHP_SDS_OI_FERC BCHP_SDS_OI_0_FERC
#define BCHP_SDS_OI_FRC BCHP_SDS_OI_0_FRC
#define BCHP_SDS_OI_OSIGPN BCHP_SDS_OI_0_OSIGPN
#define BCHP_SDS_OI_OSUBD BCHP_SDS_OI_0_OSUBD
#define BCHP_SDS_OI_OCOEF BCHP_SDS_OI_0_OCOEF
#define BCHP_SDS_OI_OFI BCHP_SDS_OI_0_OFI
#define BCHP_SDS_OI_OPLL_NPDIV BCHP_SDS_OI_0_OPLL_NPDIV
#define BCHP_SDS_OI_OPLL_MDIV_CTRL BCHP_SDS_OI_0_OPLL_MDIV_CTRL
#define BCHP_SDS_OI_OPLL_CTRL BCHP_SDS_OI_0_OPLL_CTRL
#define BCHP_SDS_OI_OPLL_SSC_CTRL1 BCHP_SDS_OI_0_OPLL_SSC_CTRL1
#define BCHP_SDS_OI_OPLL_SSC_CTRL0 BCHP_SDS_OI_0_OPLL_SSC_CTRL0
#define BCHP_SDS_OI_OPLL_STATUS BCHP_SDS_OI_0_OPLL_STATUS
#define BCHP_SDS_OI_OPLL_PWRDN_RST BCHP_SDS_OI_0_OPLL_PWRDN_RST
#define BCHP_SDS_SNR_SNRCTL BCHP_SDS_SNR_0_SNRCTL
#define BCHP_SDS_SNR_SNRHT BCHP_SDS_SNR_0_SNRHT
#define BCHP_SDS_SNR_SNRLT BCHP_SDS_SNR_0_SNRLT
#define BCHP_SDS_SNR_SNRE BCHP_SDS_SNR_0_SNRE
#define BCHP_SDS_SNR_SNORETP BCHP_SDS_SNR_0_SNORETP
#define BCHP_SDS_SNR_SNORESP BCHP_SDS_SNR_0_SNORESP
#define BCHP_SDS_SNR_SNORECTL BCHP_SDS_SNR_0_SNORECTL
#define BCHP_SDS_TUNER_DAISY_R01 BCHP_SDS_TUNER_0_DAISY_R01
#define BCHP_SDS_TUNER_BGBIAS_R01 BCHP_SDS_TUNER_0_BGBIAS_R01
#define BCHP_SDS_TUNER_REFPLL_R01 BCHP_SDS_TUNER_0_REFPLL_R01
#define BCHP_SDS_TUNER_REFPLL_R02 BCHP_SDS_TUNER_0_REFPLL_R02
#define BCHP_SDS_TUNER_REFPLL_R03 BCHP_SDS_TUNER_0_REFPLL_R03
#define BCHP_SDS_TUNER_REFPLL_R04 BCHP_SDS_TUNER_0_REFPLL_R04
#define BCHP_SDS_TUNER_ADC_R01 BCHP_SDS_TUNER_0_ADC_R01
#define BCHP_SDS_TUNER_ADC_R02 BCHP_SDS_TUNER_0_ADC_R02
#define BCHP_SDS_TUNER_ADC_R03 BCHP_SDS_TUNER_0_ADC_R03
#define BCHP_SDS_TUNER_ADC_R04 BCHP_SDS_TUNER_0_ADC_R04
#define BCHP_SDS_TUNER_IFPGA_R01 BCHP_SDS_TUNER_0_IFPGA_R01
#define BCHP_SDS_TUNER_LNA_R01 BCHP_SDS_TUNER_0_LNA_R01
#define BCHP_SDS_TUNER_LNA_R02 BCHP_SDS_TUNER_0_LNA_R02
#define BCHP_SDS_TUNER_LO_R01 BCHP_SDS_TUNER_0_LO_R01
#define BCHP_SDS_TUNER_LO_R02 BCHP_SDS_TUNER_0_LO_R02
#define BCHP_SDS_TUNER_LO_R03 BCHP_SDS_TUNER_0_LO_R03
#define BCHP_SDS_TUNER_LO_R04 BCHP_SDS_TUNER_0_LO_R04
#define BCHP_SDS_TUNER_LO_R05 BCHP_SDS_TUNER_0_LO_R05
#define BCHP_SDS_TUNER_LO_R06 BCHP_SDS_TUNER_0_LO_R06
#define BCHP_SDS_TUNER_LO_R07 BCHP_SDS_TUNER_0_LO_R07
#define BCHP_SDS_TUNER_LPF_R01 BCHP_SDS_TUNER_0_LPF_R01
#define BCHP_SDS_TUNER_RFPGA_R01 BCHP_SDS_TUNER_0_RFPGA_R01
#define BCHP_SDS_TUNER_BBAGC_R01 BCHP_SDS_TUNER_0_BBAGC_R01
#define BCHP_SDS_TUNER_BBAGC_R02 BCHP_SDS_TUNER_0_BBAGC_R02
#define BCHP_SDS_TUNER_BBAGC_R03 BCHP_SDS_TUNER_0_BBAGC_R03
#define BCHP_SDS_TUNER_BBAGC_R04 BCHP_SDS_TUNER_0_BBAGC_R04
#define BCHP_SDS_TUNER_BBAGC_R05 BCHP_SDS_TUNER_0_BBAGC_R05
#define BCHP_SDS_TUNER_CALDAC_R01 BCHP_SDS_TUNER_0_CALDAC_R01
#define BCHP_SDS_TUNER_LODDFS_R01 BCHP_SDS_TUNER_0_LODDFS_R01
#define BCHP_SDS_TUNER_LODDFS_R02 BCHP_SDS_TUNER_0_LODDFS_R02
#define BCHP_SDS_TUNER_MXFGA_R01 BCHP_SDS_TUNER_0_MXFGA_R01
#define BCHP_SDS_TUNER_MXFGA_R02 BCHP_SDS_TUNER_0_MXFGA_R02
#define BCHP_SDS_TUNER_POSTDCO_R01 BCHP_SDS_TUNER_0_POSTDCO_R01
#define BCHP_SDS_TUNER_PREDCO_R01 BCHP_SDS_TUNER_0_PREDCO_R01
#define BCHP_SDS_TUNER_RFAGC_R01 BCHP_SDS_TUNER_0_RFAGC_R01
#define BCHP_SDS_TUNER_RFAGC_R02 BCHP_SDS_TUNER_0_RFAGC_R02
#define BCHP_SDS_TUNER_RFAGC_R03 BCHP_SDS_TUNER_0_RFAGC_R03
#define BCHP_SDS_TUNER_RFAGC_R04 BCHP_SDS_TUNER_0_RFAGC_R04
#define BCHP_SDS_TUNER_RFAGC_R05 BCHP_SDS_TUNER_0_RFAGC_R05
#define BCHP_SDS_TUNER_DDFS_R01 BCHP_SDS_TUNER_0_DDFS_R01
#define BCHP_SDS_TUNER_PLLSTAT_R01 BCHP_SDS_TUNER_0_PLLSTAT_R01
#define BCHP_SDS_TUNER_PREDCOI_R01 BCHP_SDS_TUNER_0_PREDCOI_R01
#define BCHP_SDS_TUNER_PREDCOI_R02 BCHP_SDS_TUNER_0_PREDCOI_R02
#define BCHP_SDS_TUNER_PREDCOI_R03 BCHP_SDS_TUNER_0_PREDCOI_R03
#define BCHP_SDS_TUNER_PREDCOI_R04 BCHP_SDS_TUNER_0_PREDCOI_R04
#define BCHP_SDS_TUNER_PREDCOQ_R01 BCHP_SDS_TUNER_0_PREDCOQ_R01
#define BCHP_SDS_TUNER_PREDCOQ_R02 BCHP_SDS_TUNER_0_PREDCOQ_R02
#define BCHP_SDS_TUNER_PREDCOQ_R03 BCHP_SDS_TUNER_0_PREDCOQ_R03
#define BCHP_SDS_TUNER_PREDCOQ_R04 BCHP_SDS_TUNER_0_PREDCOQ_R04
#define BCHP_SDS_TUNER_POSTDCOI_R01 BCHP_SDS_TUNER_0_POSTDCOI_R01
#define BCHP_SDS_TUNER_POSTDCOI_R02 BCHP_SDS_TUNER_0_POSTDCOI_R02
#define BCHP_SDS_TUNER_POSTDCOI_R03 BCHP_SDS_TUNER_0_POSTDCOI_R03
#define BCHP_SDS_TUNER_POSTDCOI_R04 BCHP_SDS_TUNER_0_POSTDCOI_R04
#define BCHP_SDS_TUNER_POSTDCOQ_R01 BCHP_SDS_TUNER_0_POSTDCOQ_R01
#define BCHP_SDS_TUNER_POSTDCOQ_R02 BCHP_SDS_TUNER_0_POSTDCOQ_R02
#define BCHP_SDS_TUNER_POSTDCOQ_R03 BCHP_SDS_TUNER_0_POSTDCOQ_R03
#define BCHP_SDS_TUNER_POSTDCOQ_R04 BCHP_SDS_TUNER_0_POSTDCOQ_R04
#define BCHP_SDS_TUNER_RESET_R01 BCHP_SDS_TUNER_0_RESET_R01
#define BCHP_SDS_TUNER_AGC_IF_CTL BCHP_SDS_TUNER_0_AGC_IF_CTL
#define BCHP_SDS_TUNER_FILCAL_DDFS_CTL BCHP_SDS_TUNER_0_FILCAL_DDFS_CTL
#define BCHP_SDS_TUNER_TPCTL BCHP_SDS_TUNER_0_TPCTL
#define BCHP_SDS_TUNER_PWRUP_COMMON_R01 BCHP_SDS_TUNER_0_PWRUP_COMMON_R01
#define BCHP_SDS_TUNER_PWRUP_R01 BCHP_SDS_TUNER_0_PWRUP_R01
#define BCHP_SDS_VIT_VTCTL BCHP_SDS_VIT_0_VTCTL
#define BCHP_SDS_VIT_V10 BCHP_SDS_VIT_0_V10
#define BCHP_SDS_VIT_V32 BCHP_SDS_VIT_0_V32
#define BCHP_SDS_VIT_V54 BCHP_SDS_VIT_0_V54
#define BCHP_SDS_VIT_V76 BCHP_SDS_VIT_0_V76
#define BCHP_SDS_VIT_VINT BCHP_SDS_VIT_0_VINT
#define BCHP_SDS_VIT_VCNT BCHP_SDS_VIT_0_VCNT
#define BCHP_SDS_VIT_VSTC BCHP_SDS_VIT_0_VSTC
#define BCHP_SDS_VIT_VST BCHP_SDS_VIT_0_VST
#define BCHP_SDS_VIT_VREC BCHP_SDS_VIT_0_VREC
#define BCHP_SDS_VIT_VRCV BCHP_SDS_VIT_0_VRCV
#define BCHP_TFEC_TFECTL BCHP_TFEC_0_TFECTL
#if (BCHP_VER == BCHP_VER_A0)
#define BCHP_TFEC_MEMTM0 BCHP_TFEC_0_MEMTM0
#define BCHP_TFEC_MEMTM1 BCHP_TFEC_0_MEMTM1
#define BCHP_TFEC_MEMTM2 BCHP_TFEC_0_MEMTM2
#define BCHP_TFEC_MEMTM3 BCHP_TFEC_0_MEMTM3
#endif
#define BCHP_TFEC_TNBLK BCHP_TFEC_0_TNBLK
#define BCHP_TFEC_TCBLK BCHP_TFEC_0_TCBLK
#define BCHP_TFEC_TBBLK BCHP_TFEC_0_TBBLK
#define BCHP_TFEC_TCSYM BCHP_TFEC_0_TCSYM
#define BCHP_TFEC_TFMT BCHP_TFEC_0_TFMT
#define BCHP_TFEC_TPAK BCHP_TFEC_0_TPAK
#define BCHP_TFEC_TSSQ BCHP_TFEC_0_TSSQ
#define BCHP_TFEC_TSYN BCHP_TFEC_0_TSYN
#define BCHP_TFEC_TTUR BCHP_TFEC_0_TTUR
#define BCHP_TFEC_TZPK BCHP_TFEC_0_TZPK
#define BCHP_TFEC_TZSY BCHP_TFEC_0_TZSY
#define BCHP_TFEC_TITR BCHP_TFEC_0_TITR
#define BCHP_TFEC_TCIL BCHP_TFEC_0_TCIL
#define BCHP_TFEC_TRSD BCHP_TFEC_0_TRSD
#define BCHP_TFEC_TPN BCHP_TFEC_0_TPN
#define BCHP_TFEC_TSIGCNT BCHP_TFEC_0_TSIGCNT
#define BCHP_TFEC_TSIGITD BCHP_TFEC_0_TSIGITD
#define BCHP_TFEC_TSIGXPT BCHP_TFEC_0_TSIGXPT
#define BCHP_TFEC_TTPCTL BCHP_TFEC_0_TTPCTL
#define BCHP_TFEC_GR_BRIDGE_REVISION BCHP_TFEC_GR_BRIDGE_0_REVISION
#define BCHP_TFEC_GR_BRIDGE_CTRL BCHP_TFEC_GR_BRIDGE_0_CTRL
#define BCHP_TFEC_GR_BRIDGE_SW_INIT_0 BCHP_TFEC_GR_BRIDGE_0_SW_INIT_0
#define BCHP_TFEC_GR_BRIDGE_SW_INIT_1 BCHP_TFEC_GR_BRIDGE_0_SW_INIT_1
#define BCHP_TFEC_INTR2_CPU_STATUS BCHP_TFEC_INTR2_0_CPU_STATUS
#define BCHP_TFEC_INTR2_CPU_SET BCHP_TFEC_INTR2_0_CPU_SET
#define BCHP_TFEC_INTR2_CPU_CLEAR BCHP_TFEC_INTR2_0_CPU_CLEAR
#define BCHP_TFEC_INTR2_CPU_MASK_STATUS BCHP_TFEC_INTR2_0_CPU_MASK_STATUS
#define BCHP_TFEC_INTR2_CPU_MASK_SET BCHP_TFEC_INTR2_0_CPU_MASK_SET
#define BCHP_TFEC_INTR2_CPU_MASK_CLEAR BCHP_TFEC_INTR2_0_CPU_MASK_CLEAR
#define BCHP_TFEC_INTR2_PCI_STATUS BCHP_TFEC_INTR2_0_PCI_STATUS
#define BCHP_TFEC_INTR2_PCI_SET BCHP_TFEC_INTR2_0_PCI_SET
#define BCHP_TFEC_INTR2_PCI_CLEAR BCHP_TFEC_INTR2_0_PCI_CLEAR
#define BCHP_TFEC_INTR2_PCI_MASK_STATUS BCHP_TFEC_INTR2_0_PCI_MASK_STATUS
#define BCHP_TFEC_INTR2_PCI_MASK_SET BCHP_TFEC_INTR2_0_PCI_MASK_SET
#define BCHP_TFEC_INTR2_PCI_MASK_CLEAR BCHP_TFEC_INTR2_0_PCI_MASK_CLEAR
#define BCHP_TFEC_MISC_POST_DIV_CTL BCHP_TFEC_MISC_0_POST_DIV_CTL
#define BCHP_TFEC_MISC_REGF_STBY BCHP_TFEC_MISC_0_REGF_STBY
#if (BCHP_VER == BCHP_VER_A0)
#define BCHP_TFEC_MISC_ROSCCTL BCHP_TFEC_MISC_0_ROSCCTL
#else
#define BCHP_TFEC_MISC_MISCCTL BCHP_TFEC_MISC_0_MISCCTL
#endif

#if (BCHP_VER >= BCHP_VER_B0)
#define BCHP_SDS_CWC_LFC1_LF_CINT_SHIFT   BCHP_SDS_CWC_0_LFC1_LF_CINT_SHIFT 
#define BCHP_SDS_CWC_LFC1_LF_CLIN_SHIFT   BCHP_SDS_CWC_0_LFC1_LF_CLIN_SHIFT 
#endif

/* interrupt bit definitions for multiple channels */
#define BCHP_SDS_INTR2_0_CPU_STATUS_fecii_in_lock_MASK         BCHP_SDS_INTR2_0_0_CPU_STATUS_fecii_in_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_fecii_out_lock_MASK        BCHP_SDS_INTR2_0_0_CPU_STATUS_fecii_out_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_fecii_ov_MASK              BCHP_SDS_INTR2_0_0_CPU_STATUS_fecii_ov_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_vit_in_sync_MASK           BCHP_SDS_INTR2_0_0_CPU_STATUS_vit_in_sync_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_vit_out_sync_MASK          BCHP_SDS_INTR2_0_0_CPU_STATUS_vit_out_sync_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_rvb_in_lock_MASK           BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_rvb_out_lock_MASK          BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_ahb_in_lock_MASK           BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_ahb_out_lock_MASK          BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_mi2c_int_MASK              BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_dft_done_int_MASK          BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_spll_in_lock_MASK          BCHP_SDS_INTR2_0_0_CPU_STATUS_spll_in_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_spll_out_lock_MASK         BCHP_SDS_INTR2_0_0_CPU_STATUS_spll_out_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_opll_in_lock_MASK          BCHP_SDS_INTR2_0_0_CPU_STATUS_opll_in_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_opll_out_lock_MASK         BCHP_SDS_INTR2_0_0_CPU_STATUS_opll_out_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_refpll_out_lock_MASK       BCHP_SDS_INTR2_0_0_CPU_STATUS_refpll_out_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_mixpll_out_lock_MASK       BCHP_SDS_INTR2_0_0_CPU_STATUS_mixpll_out_lock_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_agc_3stage_MASK            BCHP_SDS_INTR2_0_0_CPU_STATUS_agc_3stage_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_gentimer1_int_MASK         BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_gentimer2_int_MASK         BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_gentimer3_int_MASK         BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_bertimer_int_MASK          BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_bclktimer_int_MASK         BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_hp_state_match_MASK        BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_hp_state_change_MASK       BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_hp_pk_smpl_cmlt_MASK       BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_pk_smpl_cmlt_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_hp_reacq_MASK              BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_reacq_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_hp_frof_change_MASK        BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frof_change_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_hp_frame_boundary_MASK     BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_MASK
#define BCHP_SDS_INTR2_0_CPU_STATUS_dafe_loop_ramp_err_MASK    BCHP_SDS_INTR2_0_0_CPU_STATUS_dafe_loop_ramp_err_MASK
#define BCHP_SDS_OI_OPLL_MDIV_CTRL_channel_load_en_MASK        BCHP_SDS_OI_0_OPLL_MDIV_CTRL_channel_load_en_MASK
#define BCHP_SDS_OI_OIFCTL01_loop_en_MASK                      BCHP_SDS_OI_0_OIFCTL01_loop_en_MASK

#endif /* BAST_7346_PRIV_H__ */

