obj-y += homma_bus.o

obj-y += hom_dmp.o
obj-y += hom_dmr.o
obj-y += hom_dms.o

obj-y += hom_woons.o
obj-y += hom_dial.o
obj-y += hom_satip.o

obj-$(CONFIG_HOMMA_AIRPLAY) += hom_airplay.o
obj-$(CONFIG_HOMMA_RC) += hom_rc.o

ccflags-$(CONFIG_MW_MM_DLNA) += -I$(PWD)/include
