obj-y += connection/
obj-y += copycontrol/
obj-y += dscr/
obj-y += psi/
obj-y += ui/
#obj-y += pvr/

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
