obj-$(CONFIG_SUPPORT_NIMA) += napi.o
obj-$(CONFIG_SUPPORT_NIMA) += napi_debug.o
obj-$(CONFIG_SUPPORT_NIMA) += modules/
obj-$(CONFIG_SUPPORT_NIMA) += napi_netconf.o
obj-$(CONFIG_SUPPORT_NIMA) += napi_wifi.o
obj-$(CONFIG_SUPPORT_NIMA) += napi_cm.o
obj-$(CONFIG_SUPPORT_NIMA) += napi_bluetooth.o
obj-$(CONFIG_SUPPORT_NIMA) += napi_pppoe.o
