-include ./dirs

ifeq ($(DIRS),)
TARGET = core

SOURCES =	\
	../drmchain.c \
	../drmcleanstore.c \
	../drmdebug.c \
	../drmembedding.c \
	../drmhdrbuilder.c \
	../drmkeygen.c \
	../drmlicacqresp.c \
	../drmliceval.c \
	../drmrevocation.c \
	../drmsecstore.c \
	../drmint64.c \
	../drmrevocationstore.c \
	../drmsoapxmlutility.c \
	../drmlicacqv3.c \
	../drmbcrlparser.c \
	../drmblobcache.c \
	
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
