-include ./dirs

ifeq ($(DIRS),)
TARGET = symoptreal

SOURCES =                \
	symoptdevicedevcertreal.c symoptlacqreal.c symoptlicreal.c symoptutilreal.c
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
