obj-y += nx_prism_shahid_bg.o
obj-y += nx_prism_shahid_main.o
obj-y += nx_prism_shahid_component.o
obj-y += nx_prism_shahid_detail.o
obj-y += nx_prism_shahid_player.o
obj-y += nx_prism_shahid_stream.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include

# Additional include path
cclfags-y += -IS(NATIVEAPP_UI_INCLUDE_DIR)/include
cclfags-y += -IS(NATIVEAPP_UI_INCLUDE_DIR)/player
ccflags-y += -I$(NATIVEAPP_PORT_INCLUDE_DIR)/include
