obj-$(CONFIG_PROD_DEVICE_FILE_SYSTEM)		+= nx_core_filemgr_storage.o
obj-$(CONFIG_PROD_DEVICE_FILE_SYSTEM)		+= nx_core_filemgr_browser.o
obj-$(CONFIG_PROD_DEVICE_FILE_SYSTEM)		+= nx_core_filemgr_file.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include
ccflags-y += -I$(NATIVEAPP_CORE_INCLUDE_DIR)/include

# Additional include path
ccflags-y += -I$(NATIVEAPP_PORT_INCLUDE_DIR)/include