/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_dma_io2mem_ch_mac_rx_global.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 10/11/11 5:47p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Oct 11 10:53:32 2011
 *                 MD5 Checksum         12f5dd38e0ec050efd2afb0b1c62e9d9
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7435/rdb/a0/bchp_dma_io2mem_ch_mac_rx_global.h $
 * 
 * Hydra_Software_Devel/1   10/11/11 5:47p pntruong
 * SW7435-3: Synced up with central rdb.
 *
 ***************************************************************************/

#ifndef BCHP_DMA_IO2MEM_CH_MAC_RX_GLOBAL_H__
#define BCHP_DMA_IO2MEM_CH_MAC_RX_GLOBAL_H__

/***************************************************************************
 *DMA_IO2MEM_CH_MAC_RX_Global - DMA_IO2MEM_CH registers MAC RX Global
 ***************************************************************************/
#define BCHP_DMA_IO2MEM_CH_MAC_RX_Global_LLM_CMD_ADDR 0x00ff4000 /* LLM Command Address */
#define BCHP_DMA_IO2MEM_CH_MAC_RX_Global_DESC_BASE_ADDR 0x00ff4004 /* The physical base address of the DMA descriptors in memory */
#define BCHP_DMA_IO2MEM_CH_MAC_RX_Global_BUFF_BASE_ADDR 0x00ff4008 /* The physical base address of the buffers in  memory */
#define BCHP_DMA_IO2MEM_CH_MAC_RX_Global_LLM_POOL_PERIOD 0x00ff400c /* "The period for repeatedly issuing a command to LLM in case of a DMA descriptors starvation situation.,The period is in DMA clock cycle units.,Its typical value suppose to match 100us period time" */
#define BCHP_DMA_IO2MEM_CH_MAC_RX_Global_CH_CONTROL 0x00ff4010 /* Channel Control Register */
#define BCHP_DMA_IO2MEM_CH_MAC_RX_Global_DEBUG_REG 0x00ff4014 /* Debug Register */

#endif /* #ifndef BCHP_DMA_IO2MEM_CH_MAC_RX_GLOBAL_H__ */

/* End of File */
