/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_tpcap.h $
 * $brcm_Revision: Hydra_Software_Devel/2 $
 * $brcm_Date: 12/7/11 4:22p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Dec  6 18:45:21 2011
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7435/rdb/a0/bchp_tpcap.h $
 * 
 * Hydra_Software_Devel/2   12/7/11 4:22p mward
 * SW7435-3: Synced up with central rdb.
 *
 ***************************************************************************/

#ifndef BCHP_TPCAP_H__
#define BCHP_TPCAP_H__

/***************************************************************************
 *TPCAP - Registers for the Testport Capture block
 ***************************************************************************/
#define BCHP_TPCAP_CONTROL                       0x00400c00 /* Capture Control Register */
#define BCHP_TPCAP_BLOCK_SELECT                  0x00400c04 /* Functional Block select Register */
#define BCHP_TPCAP_DEST_ADDR                     0x00400c08 /* Destination address Register */
#define BCHP_TPCAP_SIZE                          0x00400c0c /* Capture size Register */
#define BCHP_TPCAP_SIZE_STATUS                   0x00400c10 /* Capture size Status Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0            0x00400c14 /* Input Mux Select 0 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1            0x00400c18 /* Input Mux Select 1 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2            0x00400c1c /* Input Mux Select 2 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3            0x00400c20 /* Input Mux Select 3 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4            0x00400c24 /* Input Mux Select 4 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5            0x00400c28 /* Input Mux Select 5 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6            0x00400c2c /* Input Mux Select 6 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7            0x00400c30 /* Input Mux Select 7 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8            0x00400c34 /* Input Mux Select 8 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9            0x00400c38 /* Input Mux Select 9 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10           0x00400c3c /* Input Mux Select 10 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11           0x00400c40 /* Input Mux Select 11 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12           0x00400c44 /* Input Mux Select 12 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13           0x00400c48 /* Input Mux Select 13 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14           0x00400c4c /* Input Mux Select 14 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15           0x00400c50 /* Input Mux Select 15 Register */
#define BCHP_TPCAP_START_TRIGGER_MASK_HI         0x00400c54 /* Start Trigger Mask High */
#define BCHP_TPCAP_START_TRIGGER_MASK_LO         0x00400c58 /* Start Trigger Mask Low */
#define BCHP_TPCAP_START_TRIGGER_VALUE_HI        0x00400c5c /* Start Trigger Value High */
#define BCHP_TPCAP_START_TRIGGER_VALUE_LO        0x00400c60 /* Start Trigger Value Low */
#define BCHP_TPCAP_STOP_TRIGGER_MASK_HI          0x00400c64 /* Stop Trigger Mask High */
#define BCHP_TPCAP_STOP_TRIGGER_MASK_LO          0x00400c68 /* Stop Trigger Mask Low */
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_HI         0x00400c6c /* Stop Trigger Value High */
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_LO         0x00400c70 /* Stop Trigger Value Low */
#define BCHP_TPCAP_CLKEN_MASK_HI                 0x00400c74 /* Clock Enable Mask High */
#define BCHP_TPCAP_CLKEN_MASK_LO                 0x00400c78 /* Clock Enable Mask Low */
#define BCHP_TPCAP_CLKEN_VALUE_HI                0x00400c7c /* Clock Enable Value High */
#define BCHP_TPCAP_CLKEN_VALUE_LO                0x00400c80 /* Clock Enable Value Low */
#define BCHP_TPCAP_SW_STOP_TRIGGER               0x00400c84 /* SW stop trigger */

/***************************************************************************
 *CONTROL - Capture Control Register
 ***************************************************************************/
/* TPCAP :: CONTROL :: reserved0 [31:17] */
#define BCHP_TPCAP_CONTROL_reserved0_MASK                          0xfffe0000
#define BCHP_TPCAP_CONTROL_reserved0_SHIFT                         17

/* TPCAP :: CONTROL :: LOOP_BACK_ENABLE [16:16] */
#define BCHP_TPCAP_CONTROL_LOOP_BACK_ENABLE_MASK                   0x00010000
#define BCHP_TPCAP_CONTROL_LOOP_BACK_ENABLE_SHIFT                  16

/* TPCAP :: CONTROL :: reserved1 [15:15] */
#define BCHP_TPCAP_CONTROL_reserved1_MASK                          0x00008000
#define BCHP_TPCAP_CONTROL_reserved1_SHIFT                         15

/* TPCAP :: CONTROL :: DEMUX_MODE [14:12] */
#define BCHP_TPCAP_CONTROL_DEMUX_MODE_MASK                         0x00007000
#define BCHP_TPCAP_CONTROL_DEMUX_MODE_SHIFT                        12
#define BCHP_TPCAP_CONTROL_DEMUX_MODE_DEFAULT                      0x00000000

/* TPCAP :: CONTROL :: reserved2 [11:10] */
#define BCHP_TPCAP_CONTROL_reserved2_MASK                          0x00000c00
#define BCHP_TPCAP_CONTROL_reserved2_SHIFT                         10

/* TPCAP :: CONTROL :: CAPT_WIDTH [09:08] */
#define BCHP_TPCAP_CONTROL_CAPT_WIDTH_MASK                         0x00000300
#define BCHP_TPCAP_CONTROL_CAPT_WIDTH_SHIFT                        8
#define BCHP_TPCAP_CONTROL_CAPT_WIDTH_DEFAULT                      0x00000000

/* TPCAP :: CONTROL :: LITTLE_ENDIAN [07:07] */
#define BCHP_TPCAP_CONTROL_LITTLE_ENDIAN_MASK                      0x00000080
#define BCHP_TPCAP_CONTROL_LITTLE_ENDIAN_SHIFT                     7
#define BCHP_TPCAP_CONTROL_LITTLE_ENDIAN_DEFAULT                   0x00000000

/* TPCAP :: CONTROL :: ENA_PTRN_STOP_TRIGGER [06:06] */
#define BCHP_TPCAP_CONTROL_ENA_PTRN_STOP_TRIGGER_MASK              0x00000040
#define BCHP_TPCAP_CONTROL_ENA_PTRN_STOP_TRIGGER_SHIFT             6
#define BCHP_TPCAP_CONTROL_ENA_PTRN_STOP_TRIGGER_DEFAULT           0x00000000

/* TPCAP :: CONTROL :: ENA_CTRL_STOP_TRIGGER [05:05] */
#define BCHP_TPCAP_CONTROL_ENA_CTRL_STOP_TRIGGER_MASK              0x00000020
#define BCHP_TPCAP_CONTROL_ENA_CTRL_STOP_TRIGGER_SHIFT             5
#define BCHP_TPCAP_CONTROL_ENA_CTRL_STOP_TRIGGER_DEFAULT           0x00000000

/* TPCAP :: CONTROL :: ENA_PTRN_START_TRIGGER [04:04] */
#define BCHP_TPCAP_CONTROL_ENA_PTRN_START_TRIGGER_MASK             0x00000010
#define BCHP_TPCAP_CONTROL_ENA_PTRN_START_TRIGGER_SHIFT            4
#define BCHP_TPCAP_CONTROL_ENA_PTRN_START_TRIGGER_DEFAULT          0x00000000

/* TPCAP :: CONTROL :: ENA_CTRL_START_TRIGGER [03:03] */
#define BCHP_TPCAP_CONTROL_ENA_CTRL_START_TRIGGER_MASK             0x00000008
#define BCHP_TPCAP_CONTROL_ENA_CTRL_START_TRIGGER_SHIFT            3
#define BCHP_TPCAP_CONTROL_ENA_CTRL_START_TRIGGER_DEFAULT          0x00000000

/* TPCAP :: CONTROL :: ENA_PTRN_CLK_ENA [02:02] */
#define BCHP_TPCAP_CONTROL_ENA_PTRN_CLK_ENA_MASK                   0x00000004
#define BCHP_TPCAP_CONTROL_ENA_PTRN_CLK_ENA_SHIFT                  2
#define BCHP_TPCAP_CONTROL_ENA_PTRN_CLK_ENA_DEFAULT                0x00000000

/* TPCAP :: CONTROL :: ENA_CTRL_CLK_ENA [01:01] */
#define BCHP_TPCAP_CONTROL_ENA_CTRL_CLK_ENA_MASK                   0x00000002
#define BCHP_TPCAP_CONTROL_ENA_CTRL_CLK_ENA_SHIFT                  1
#define BCHP_TPCAP_CONTROL_ENA_CTRL_CLK_ENA_DEFAULT                0x00000000

/* TPCAP :: CONTROL :: CAPT_ENABLE [00:00] */
#define BCHP_TPCAP_CONTROL_CAPT_ENABLE_MASK                        0x00000001
#define BCHP_TPCAP_CONTROL_CAPT_ENABLE_SHIFT                       0
#define BCHP_TPCAP_CONTROL_CAPT_ENABLE_DEFAULT                     0x00000000

/***************************************************************************
 *BLOCK_SELECT - Functional Block select Register
 ***************************************************************************/
/* TPCAP :: BLOCK_SELECT :: reserved0 [31:03] */
#define BCHP_TPCAP_BLOCK_SELECT_reserved0_MASK                     0xfffffff8
#define BCHP_TPCAP_BLOCK_SELECT_reserved0_SHIFT                    3

/* TPCAP :: BLOCK_SELECT :: encoded_tpcap_en [02:00] */
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_MASK              0x00000007
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_SHIFT             0
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_DEFAULT           0x00000000
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_MOCA              0
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_1          1
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_2          2
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_3          3
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_4          4
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_5          5
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_6          6
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_7          7

/***************************************************************************
 *DEST_ADDR - Destination address Register
 ***************************************************************************/
/* TPCAP :: DEST_ADDR :: DEST_ADDR [31:05] */
#define BCHP_TPCAP_DEST_ADDR_DEST_ADDR_MASK                        0xffffffe0
#define BCHP_TPCAP_DEST_ADDR_DEST_ADDR_SHIFT                       5
#define BCHP_TPCAP_DEST_ADDR_DEST_ADDR_DEFAULT                     0x00000000

/* TPCAP :: DEST_ADDR :: reserved0 [04:00] */
#define BCHP_TPCAP_DEST_ADDR_reserved0_MASK                        0x0000001f
#define BCHP_TPCAP_DEST_ADDR_reserved0_SHIFT                       0

/***************************************************************************
 *SIZE - Capture size Register
 ***************************************************************************/
/* TPCAP :: SIZE :: CAPT_SIZE [31:00] */
#define BCHP_TPCAP_SIZE_CAPT_SIZE_MASK                             0xffffffff
#define BCHP_TPCAP_SIZE_CAPT_SIZE_SHIFT                            0
#define BCHP_TPCAP_SIZE_CAPT_SIZE_DEFAULT                          0x00000000

/***************************************************************************
 *SIZE_STATUS - Capture size Status Register
 ***************************************************************************/
/* TPCAP :: SIZE_STATUS :: CAPT_SIZE_STATUS [31:00] */
#define BCHP_TPCAP_SIZE_STATUS_CAPT_SIZE_STATUS_MASK               0xffffffff
#define BCHP_TPCAP_SIZE_STATUS_CAPT_SIZE_STATUS_SHIFT              0
#define BCHP_TPCAP_SIZE_STATUS_CAPT_SIZE_STATUS_DEFAULT            0x00000000

/***************************************************************************
 *INPUT_MUX_SELECT_0 - Input Mux Select 0 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_0 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_0 :: MUX_DATA_3 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_3_MASK              0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_3_SHIFT             24
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_3_DEFAULT           0x00000003

/* TPCAP :: INPUT_MUX_SELECT_0 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_0 :: MUX_DATA_2 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_2_MASK              0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_2_SHIFT             16
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_2_DEFAULT           0x00000002

/* TPCAP :: INPUT_MUX_SELECT_0 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_0 :: MUX_DATA_1 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_1_MASK              0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_1_SHIFT             8
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_1_DEFAULT           0x00000001

/* TPCAP :: INPUT_MUX_SELECT_0 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_0 :: MUX_DATA_0 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_0_MASK              0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_0_SHIFT             0
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_0_DEFAULT           0x00000000

/***************************************************************************
 *INPUT_MUX_SELECT_1 - Input Mux Select 1 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_1 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_1 :: MUX_DATA_7 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_7_MASK              0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_7_SHIFT             24
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_7_DEFAULT           0x00000007

/* TPCAP :: INPUT_MUX_SELECT_1 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_1 :: MUX_DATA_6 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_6_MASK              0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_6_SHIFT             16
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_6_DEFAULT           0x00000006

/* TPCAP :: INPUT_MUX_SELECT_1 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_1 :: MUX_DATA_5 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_5_MASK              0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_5_SHIFT             8
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_5_DEFAULT           0x00000005

/* TPCAP :: INPUT_MUX_SELECT_1 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_1 :: MUX_DATA_4 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_4_MASK              0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_4_SHIFT             0
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_4_DEFAULT           0x00000004

/***************************************************************************
 *INPUT_MUX_SELECT_2 - Input Mux Select 2 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_2 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_2 :: MUX_DATA_11 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_11_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_11_SHIFT            24
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_11_DEFAULT          0x0000000b

/* TPCAP :: INPUT_MUX_SELECT_2 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_2 :: MUX_DATA_10 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_10_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_10_SHIFT            16
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_10_DEFAULT          0x0000000a

/* TPCAP :: INPUT_MUX_SELECT_2 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_2 :: MUX_DATA_9 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_9_MASK              0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_9_SHIFT             8
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_9_DEFAULT           0x00000009

/* TPCAP :: INPUT_MUX_SELECT_2 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_2 :: MUX_DATA_8 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_8_MASK              0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_8_SHIFT             0
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_8_DEFAULT           0x00000008

/***************************************************************************
 *INPUT_MUX_SELECT_3 - Input Mux Select 3 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_3 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_3 :: MUX_DATA_15 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_15_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_15_SHIFT            24
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_15_DEFAULT          0x0000000f

/* TPCAP :: INPUT_MUX_SELECT_3 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_3 :: MUX_DATA_14 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_14_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_14_SHIFT            16
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_14_DEFAULT          0x0000000e

/* TPCAP :: INPUT_MUX_SELECT_3 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_3 :: MUX_DATA_13 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_13_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_13_SHIFT            8
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_13_DEFAULT          0x0000000d

/* TPCAP :: INPUT_MUX_SELECT_3 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_3 :: MUX_DATA_12 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_12_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_12_SHIFT            0
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_12_DEFAULT          0x0000000c

/***************************************************************************
 *INPUT_MUX_SELECT_4 - Input Mux Select 4 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_4 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_4 :: MUX_DATA_19 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_19_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_19_SHIFT            24
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_19_DEFAULT          0x00000013

/* TPCAP :: INPUT_MUX_SELECT_4 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_4 :: MUX_DATA_18 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_18_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_18_SHIFT            16
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_18_DEFAULT          0x00000012

/* TPCAP :: INPUT_MUX_SELECT_4 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_4 :: MUX_DATA_17 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_17_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_17_SHIFT            8
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_17_DEFAULT          0x00000011

/* TPCAP :: INPUT_MUX_SELECT_4 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_4 :: MUX_DATA_16 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_16_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_16_SHIFT            0
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_16_DEFAULT          0x00000010

/***************************************************************************
 *INPUT_MUX_SELECT_5 - Input Mux Select 5 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_5 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_5 :: MUX_DATA_23 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_23_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_23_SHIFT            24
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_23_DEFAULT          0x00000017

/* TPCAP :: INPUT_MUX_SELECT_5 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_5 :: MUX_DATA_22 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_22_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_22_SHIFT            16
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_22_DEFAULT          0x00000016

/* TPCAP :: INPUT_MUX_SELECT_5 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_5 :: MUX_DATA_21 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_21_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_21_SHIFT            8
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_21_DEFAULT          0x00000015

/* TPCAP :: INPUT_MUX_SELECT_5 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_5 :: MUX_DATA_20 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_20_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_20_SHIFT            0
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_20_DEFAULT          0x00000014

/***************************************************************************
 *INPUT_MUX_SELECT_6 - Input Mux Select 6 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_6 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_6 :: MUX_DATA_27 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_27_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_27_SHIFT            24
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_27_DEFAULT          0x0000001b

/* TPCAP :: INPUT_MUX_SELECT_6 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_6 :: MUX_DATA_26 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_26_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_26_SHIFT            16
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_26_DEFAULT          0x0000001a

/* TPCAP :: INPUT_MUX_SELECT_6 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_6 :: MUX_DATA_25 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_25_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_25_SHIFT            8
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_25_DEFAULT          0x00000019

/* TPCAP :: INPUT_MUX_SELECT_6 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_6 :: MUX_DATA_24 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_24_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_24_SHIFT            0
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_24_DEFAULT          0x00000018

/***************************************************************************
 *INPUT_MUX_SELECT_7 - Input Mux Select 7 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_7 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_7 :: MUX_DATA_31 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_31_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_31_SHIFT            24
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_31_DEFAULT          0x0000001f

/* TPCAP :: INPUT_MUX_SELECT_7 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_7 :: MUX_DATA_30 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_30_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_30_SHIFT            16
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_30_DEFAULT          0x0000001e

/* TPCAP :: INPUT_MUX_SELECT_7 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_7 :: MUX_DATA_29 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_29_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_29_SHIFT            8
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_29_DEFAULT          0x0000001d

/* TPCAP :: INPUT_MUX_SELECT_7 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_7 :: MUX_DATA_28 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_28_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_28_SHIFT            0
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_28_DEFAULT          0x0000001c

/***************************************************************************
 *INPUT_MUX_SELECT_8 - Input Mux Select 8 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_8 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_8 :: MUX_DATA_35 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_35_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_35_SHIFT            24
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_35_DEFAULT          0x00000023

/* TPCAP :: INPUT_MUX_SELECT_8 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_8 :: MUX_DATA_34 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_34_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_34_SHIFT            16
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_34_DEFAULT          0x00000022

/* TPCAP :: INPUT_MUX_SELECT_8 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_8 :: MUX_DATA_33 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_33_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_33_SHIFT            8
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_33_DEFAULT          0x00000021

/* TPCAP :: INPUT_MUX_SELECT_8 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_8 :: MUX_DATA_32 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_32_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_32_SHIFT            0
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_32_DEFAULT          0x00000020

/***************************************************************************
 *INPUT_MUX_SELECT_9 - Input Mux Select 9 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_9 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_9 :: MUX_DATA_39 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_39_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_39_SHIFT            24
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_39_DEFAULT          0x00000027

/* TPCAP :: INPUT_MUX_SELECT_9 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_9 :: MUX_DATA_38 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_38_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_38_SHIFT            16
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_38_DEFAULT          0x00000026

/* TPCAP :: INPUT_MUX_SELECT_9 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_9 :: MUX_DATA_37 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_37_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_37_SHIFT            8
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_37_DEFAULT          0x00000025

/* TPCAP :: INPUT_MUX_SELECT_9 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_9 :: MUX_DATA_36 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_36_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_36_SHIFT            0
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_36_DEFAULT          0x00000024

/***************************************************************************
 *INPUT_MUX_SELECT_10 - Input Mux Select 10 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_10 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_10 :: MUX_DATA_43 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_43_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_43_SHIFT           24
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_43_DEFAULT         0x0000002b

/* TPCAP :: INPUT_MUX_SELECT_10 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_10 :: MUX_DATA_42 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_42_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_42_SHIFT           16
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_42_DEFAULT         0x0000002a

/* TPCAP :: INPUT_MUX_SELECT_10 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_10 :: MUX_DATA_41 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_41_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_41_SHIFT           8
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_41_DEFAULT         0x00000029

/* TPCAP :: INPUT_MUX_SELECT_10 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_10 :: MUX_DATA_40 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_40_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_40_SHIFT           0
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_40_DEFAULT         0x00000028

/***************************************************************************
 *INPUT_MUX_SELECT_11 - Input Mux Select 11 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_11 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_11 :: MUX_DATA_47 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_47_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_47_SHIFT           24
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_47_DEFAULT         0x0000002f

/* TPCAP :: INPUT_MUX_SELECT_11 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_11 :: MUX_DATA_46 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_46_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_46_SHIFT           16
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_46_DEFAULT         0x0000002e

/* TPCAP :: INPUT_MUX_SELECT_11 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_11 :: MUX_DATA_45 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_45_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_45_SHIFT           8
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_45_DEFAULT         0x0000002d

/* TPCAP :: INPUT_MUX_SELECT_11 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_11 :: MUX_DATA_44 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_44_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_44_SHIFT           0
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_44_DEFAULT         0x0000002c

/***************************************************************************
 *INPUT_MUX_SELECT_12 - Input Mux Select 12 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_12 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_12 :: MUX_DATA_51 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_51_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_51_SHIFT           24
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_51_DEFAULT         0x00000033

/* TPCAP :: INPUT_MUX_SELECT_12 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_12 :: MUX_DATA_50 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_50_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_50_SHIFT           16
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_50_DEFAULT         0x00000032

/* TPCAP :: INPUT_MUX_SELECT_12 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_12 :: MUX_DATA_49 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_49_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_49_SHIFT           8
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_49_DEFAULT         0x00000031

/* TPCAP :: INPUT_MUX_SELECT_12 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_12 :: MUX_DATA_48 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_48_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_48_SHIFT           0
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_48_DEFAULT         0x00000030

/***************************************************************************
 *INPUT_MUX_SELECT_13 - Input Mux Select 13 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_13 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_13 :: MUX_DATA_55 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_55_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_55_SHIFT           24
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_55_DEFAULT         0x00000037

/* TPCAP :: INPUT_MUX_SELECT_13 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_13 :: MUX_DATA_54 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_54_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_54_SHIFT           16
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_54_DEFAULT         0x00000036

/* TPCAP :: INPUT_MUX_SELECT_13 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_13 :: MUX_DATA_53 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_53_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_53_SHIFT           8
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_53_DEFAULT         0x00000035

/* TPCAP :: INPUT_MUX_SELECT_13 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_13 :: MUX_DATA_52 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_52_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_52_SHIFT           0
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_52_DEFAULT         0x00000034

/***************************************************************************
 *INPUT_MUX_SELECT_14 - Input Mux Select 14 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_14 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_14 :: MUX_DATA_59 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_59_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_59_SHIFT           24
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_59_DEFAULT         0x0000003b

/* TPCAP :: INPUT_MUX_SELECT_14 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_14 :: MUX_DATA_58 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_58_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_58_SHIFT           16
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_58_DEFAULT         0x0000003a

/* TPCAP :: INPUT_MUX_SELECT_14 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_14 :: MUX_DATA_57 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_57_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_57_SHIFT           8
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_57_DEFAULT         0x00000039

/* TPCAP :: INPUT_MUX_SELECT_14 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_14 :: MUX_DATA_56 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_56_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_56_SHIFT           0
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_56_DEFAULT         0x00000038

/***************************************************************************
 *INPUT_MUX_SELECT_15 - Input Mux Select 15 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_15 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_15 :: MUX_DATA_63 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_63_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_63_SHIFT           24
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_63_DEFAULT         0x0000003f

/* TPCAP :: INPUT_MUX_SELECT_15 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_15 :: MUX_DATA_62 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_62_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_62_SHIFT           16
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_62_DEFAULT         0x0000003e

/* TPCAP :: INPUT_MUX_SELECT_15 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_15 :: MUX_DATA_61 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_61_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_61_SHIFT           8
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_61_DEFAULT         0x0000003d

/* TPCAP :: INPUT_MUX_SELECT_15 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_15 :: MUX_DATA_60 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_60_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_60_SHIFT           0
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_60_DEFAULT         0x0000003c

/***************************************************************************
 *START_TRIGGER_MASK_HI - Start Trigger Mask High
 ***************************************************************************/
/* TPCAP :: START_TRIGGER_MASK_HI :: START_TRIGGER_MASK_HI [31:00] */
#define BCHP_TPCAP_START_TRIGGER_MASK_HI_START_TRIGGER_MASK_HI_MASK 0xffffffff
#define BCHP_TPCAP_START_TRIGGER_MASK_HI_START_TRIGGER_MASK_HI_SHIFT 0
#define BCHP_TPCAP_START_TRIGGER_MASK_HI_START_TRIGGER_MASK_HI_DEFAULT 0xffffffff

/***************************************************************************
 *START_TRIGGER_MASK_LO - Start Trigger Mask Low
 ***************************************************************************/
/* TPCAP :: START_TRIGGER_MASK_LO :: START_TRIGGER_MASK_LO [31:00] */
#define BCHP_TPCAP_START_TRIGGER_MASK_LO_START_TRIGGER_MASK_LO_MASK 0xffffffff
#define BCHP_TPCAP_START_TRIGGER_MASK_LO_START_TRIGGER_MASK_LO_SHIFT 0
#define BCHP_TPCAP_START_TRIGGER_MASK_LO_START_TRIGGER_MASK_LO_DEFAULT 0xffffffff

/***************************************************************************
 *START_TRIGGER_VALUE_HI - Start Trigger Value High
 ***************************************************************************/
/* TPCAP :: START_TRIGGER_VALUE_HI :: START_TRIGGER_VALUE_HI [31:00] */
#define BCHP_TPCAP_START_TRIGGER_VALUE_HI_START_TRIGGER_VALUE_HI_MASK 0xffffffff
#define BCHP_TPCAP_START_TRIGGER_VALUE_HI_START_TRIGGER_VALUE_HI_SHIFT 0
#define BCHP_TPCAP_START_TRIGGER_VALUE_HI_START_TRIGGER_VALUE_HI_DEFAULT 0x00000000

/***************************************************************************
 *START_TRIGGER_VALUE_LO - Start Trigger Value Low
 ***************************************************************************/
/* TPCAP :: START_TRIGGER_VALUE_LO :: START_TRIGGER_VALUE_LO [31:00] */
#define BCHP_TPCAP_START_TRIGGER_VALUE_LO_START_TRIGGER_VALUE_LO_MASK 0xffffffff
#define BCHP_TPCAP_START_TRIGGER_VALUE_LO_START_TRIGGER_VALUE_LO_SHIFT 0
#define BCHP_TPCAP_START_TRIGGER_VALUE_LO_START_TRIGGER_VALUE_LO_DEFAULT 0x00000000

/***************************************************************************
 *STOP_TRIGGER_MASK_HI - Stop Trigger Mask High
 ***************************************************************************/
/* TPCAP :: STOP_TRIGGER_MASK_HI :: STOP_TRIGGER_MASK_HI [31:00] */
#define BCHP_TPCAP_STOP_TRIGGER_MASK_HI_STOP_TRIGGER_MASK_HI_MASK  0xffffffff
#define BCHP_TPCAP_STOP_TRIGGER_MASK_HI_STOP_TRIGGER_MASK_HI_SHIFT 0
#define BCHP_TPCAP_STOP_TRIGGER_MASK_HI_STOP_TRIGGER_MASK_HI_DEFAULT 0xffffffff

/***************************************************************************
 *STOP_TRIGGER_MASK_LO - Stop Trigger Mask Low
 ***************************************************************************/
/* TPCAP :: STOP_TRIGGER_MASK_LO :: STOP_TRIGGER_MASK_LO [31:00] */
#define BCHP_TPCAP_STOP_TRIGGER_MASK_LO_STOP_TRIGGER_MASK_LO_MASK  0xffffffff
#define BCHP_TPCAP_STOP_TRIGGER_MASK_LO_STOP_TRIGGER_MASK_LO_SHIFT 0
#define BCHP_TPCAP_STOP_TRIGGER_MASK_LO_STOP_TRIGGER_MASK_LO_DEFAULT 0xffffffff

/***************************************************************************
 *STOP_TRIGGER_VALUE_HI - Stop Trigger Value High
 ***************************************************************************/
/* TPCAP :: STOP_TRIGGER_VALUE_HI :: STOP_TRIGGER_VALUE_HI [31:00] */
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_HI_STOP_TRIGGER_VALUE_HI_MASK 0xffffffff
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_HI_STOP_TRIGGER_VALUE_HI_SHIFT 0
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_HI_STOP_TRIGGER_VALUE_HI_DEFAULT 0x00000000

/***************************************************************************
 *STOP_TRIGGER_VALUE_LO - Stop Trigger Value Low
 ***************************************************************************/
/* TPCAP :: STOP_TRIGGER_VALUE_LO :: STOP_TRIGGER_VALUE_LO [31:00] */
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_LO_STOP_TRIGGER_VALUE_LO_MASK 0xffffffff
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_LO_STOP_TRIGGER_VALUE_LO_SHIFT 0
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_LO_STOP_TRIGGER_VALUE_LO_DEFAULT 0x00000000

/***************************************************************************
 *CLKEN_MASK_HI - Clock Enable Mask High
 ***************************************************************************/
/* TPCAP :: CLKEN_MASK_HI :: CLKEN_MASK_HI [31:00] */
#define BCHP_TPCAP_CLKEN_MASK_HI_CLKEN_MASK_HI_MASK                0xffffffff
#define BCHP_TPCAP_CLKEN_MASK_HI_CLKEN_MASK_HI_SHIFT               0
#define BCHP_TPCAP_CLKEN_MASK_HI_CLKEN_MASK_HI_DEFAULT             0xffffffff

/***************************************************************************
 *CLKEN_MASK_LO - Clock Enable Mask Low
 ***************************************************************************/
/* TPCAP :: CLKEN_MASK_LO :: CLKEN_MASK_LO [31:00] */
#define BCHP_TPCAP_CLKEN_MASK_LO_CLKEN_MASK_LO_MASK                0xffffffff
#define BCHP_TPCAP_CLKEN_MASK_LO_CLKEN_MASK_LO_SHIFT               0
#define BCHP_TPCAP_CLKEN_MASK_LO_CLKEN_MASK_LO_DEFAULT             0xffffffff

/***************************************************************************
 *CLKEN_VALUE_HI - Clock Enable Value High
 ***************************************************************************/
/* TPCAP :: CLKEN_VALUE_HI :: CLKEN_VALUE_HI [31:00] */
#define BCHP_TPCAP_CLKEN_VALUE_HI_CLKEN_VALUE_HI_MASK              0xffffffff
#define BCHP_TPCAP_CLKEN_VALUE_HI_CLKEN_VALUE_HI_SHIFT             0
#define BCHP_TPCAP_CLKEN_VALUE_HI_CLKEN_VALUE_HI_DEFAULT           0x00000000

/***************************************************************************
 *CLKEN_VALUE_LO - Clock Enable Value Low
 ***************************************************************************/
/* TPCAP :: CLKEN_VALUE_LO :: CLKEN_VALUE_LO [31:00] */
#define BCHP_TPCAP_CLKEN_VALUE_LO_CLKEN_VALUE_LO_MASK              0xffffffff
#define BCHP_TPCAP_CLKEN_VALUE_LO_CLKEN_VALUE_LO_SHIFT             0
#define BCHP_TPCAP_CLKEN_VALUE_LO_CLKEN_VALUE_LO_DEFAULT           0x00000000

/***************************************************************************
 *SW_STOP_TRIGGER - SW stop trigger
 ***************************************************************************/
/* TPCAP :: SW_STOP_TRIGGER :: reserved0 [31:01] */
#define BCHP_TPCAP_SW_STOP_TRIGGER_reserved0_MASK                  0xfffffffe
#define BCHP_TPCAP_SW_STOP_TRIGGER_reserved0_SHIFT                 1

/* TPCAP :: SW_STOP_TRIGGER :: SW_STOP_TRIGGER [00:00] */
#define BCHP_TPCAP_SW_STOP_TRIGGER_SW_STOP_TRIGGER_MASK            0x00000001
#define BCHP_TPCAP_SW_STOP_TRIGGER_SW_STOP_TRIGGER_SHIFT           0
#define BCHP_TPCAP_SW_STOP_TRIGGER_SW_STOP_TRIGGER_DEFAULT         0x00000000

#endif /* #ifndef BCHP_TPCAP_H__ */

/* End of File */
