#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"

const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
/*/////////////   0 ///////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 000 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 001 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 002 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 003 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 004 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 005 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 006 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 007 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 008 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 009 */
/*//////////////  10 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT4,	/* GPIO 010 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 011 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 012 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 013 */
	HUMAX_GPIO_FUNCTION_ALT3,	/* GPIO 014 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 015 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 016 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 017 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 018 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 019 */
/*//////////////  20 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 020 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 021 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 022 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 023 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 024 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 025 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 026 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 027 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 028 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 029 */
/*//////////////  30 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 030 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 031 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 032 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 033 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 034 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 035 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 036 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 037 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 038 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 039 */
/*//////////////  40 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 040 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 041 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 042 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 043 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 044 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 045 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 046 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 047 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 048 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 049 */
/*//////////////  50 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 050 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 051 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 052 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 053 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 054 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 055 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 056 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 057 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 058 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 059 */
/*//////////////  60 //////////////*/
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 060 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 061 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 062 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 063 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 064 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 065 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 066 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 067 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 068 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 069 */
/*//////////////  70 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 070 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 071 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 072 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 073 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 074 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 075 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 076 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 077 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 078 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 079 */
/*//////////////  80 //////////////*/
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 080 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 081 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 082 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 083 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 084 */
	
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 02 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 03 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 04 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 05 */
	
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON_GPIO 00 */
/*//////////////  90 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON_GPIO 01 */
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON_GPIO 02 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 03 */
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON_GPIO 04 */
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON_GPIO 05 */
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON_GPIO 06 */
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON_GPIO 07 */
	HUMAX_GPIO_FUNCTION_ALT4,	/* AON_GPIO 08 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_GPIO 09 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 10 */
/*////////////// 100 //////////////*/
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 11 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 12 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 13 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 14 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 15 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 16 */
	
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_SGPIO 00 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_SGPIO 01 */ 
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_SGPIO 02 */
	HUMAX_GPIO_FUNCTION_NCTP	/* AON_SGPIO 03 */
};

HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_00_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_01_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_02_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_03_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_04_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_05_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_06_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_06_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_07_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_07_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_08_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_08_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_09_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_09_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_10_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_10_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_11_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_11_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_12_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_12_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_13_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_13_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_14_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_14_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_15_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_15_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_16_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_16_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_17_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_17_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_18_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_18_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_19_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_19_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_20_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_20_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_21_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_21_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_22_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_22_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_23_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_23_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_24_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_24_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_25_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_25_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_26_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_26_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_27_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_27_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_28_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_28_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_29_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_29_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_30_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_30_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_31_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_31_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_32_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_32_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_33_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_33_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_34_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_34_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_35_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_35_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_36_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_36_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_37_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_37_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_38_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_38_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_39_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_39_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_40_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_40_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_41_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_41_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_42_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_42_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_43_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_43_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_44_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_44_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_45_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_45_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_46_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_46_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_47_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_47_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_48_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_48_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_49_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_49_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_50_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_50_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_51_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_51_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_52_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_52_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_53_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_53_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_54_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_54_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_55_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_55_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_56_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_56_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_57_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_57_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_58_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_58_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_59_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_59_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_60_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_60_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_61_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_61_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_62_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_62_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_63_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_63_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_64_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_64_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_65_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_65_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_66_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_66_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_67_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_67_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_68_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_68_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_69_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_69_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_70_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_70_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_71_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_71_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_72_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_72_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_73_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_73_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_74_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_74_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_75_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_75_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_76_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_76_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_77_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_77_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_78_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_78_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_79_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_79_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_80_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_80_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_81_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_81_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_82_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_82_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_83_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_83_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_84_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_84_SHIFT},

/* SGPIO */
/*	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_00_SHIFT}, */
/*	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_01_SHIFT}, */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_02_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_03_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_04_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_sgpio_05_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_05_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_10_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_11_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_12_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_13_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_14_SHIFT},
	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_16_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_03_SHIFT}
	
};

