obj-y += umma_fm.o
obj-y += umma_fm_cache.o
obj-y += umma_fm_iface.o
obj-y += umma_fm_tool.o
obj-y += umma_fm_browse.o
obj-y += umma_fm_group.o

# Additional include path
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fm/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fs/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/secure/include
