-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = licenseprocessresponse

DRM_MODULE_CFLAGS =

SOURCES =                \
	licenseprocessresponse.c 
	
endif	
   
include $(DRM_SOURCE_PATH)/default.mak
