/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_itu656_csc_0.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 8/17/11 2:08p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Thu Aug 11 21:59:31 2011
 *                 MD5 Checksum         30eb4d41dba6899590ea7664187e6ba5
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7429/rdb/a0/bchp_itu656_csc_0.h $
 * 
 * Hydra_Software_Devel/1   8/17/11 2:08p pntruong
 * SW7429-2: Initial version.
 *
 ***************************************************************************/

#ifndef BCHP_ITU656_CSC_0_H__
#define BCHP_ITU656_CSC_0_H__

/***************************************************************************
 *ITU656_CSC_0 - ITU 656 Color Space Converter
 ***************************************************************************/
#define BCHP_ITU656_CSC_0_CSC_REV_ID             0x00685a00 /* Revision ID register */
#define BCHP_ITU656_CSC_0_CSC_MODE               0x00685a08 /* Color space converter mode register */
#define BCHP_ITU656_CSC_0_CSC_MIN_MAX            0x00685a0c /* Color space converter min_max clamp register */
#define BCHP_ITU656_CSC_0_CSC_COEFF_C01_C00      0x00685a10 /* Video Encoder Color Matrix coefficients c01 and c00 */
#define BCHP_ITU656_CSC_0_CSC_COEFF_C03_C02      0x00685a14 /* Video Encoder Color Matrix coefficients c03 and c02 */
#define BCHP_ITU656_CSC_0_CSC_COEFF_C11_C10      0x00685a18 /* Video Encoder Color Matrix coefficients c11 and c10 */
#define BCHP_ITU656_CSC_0_CSC_COEFF_C13_C12      0x00685a1c /* Video Encoder Color Matrix coefficients c13 and c12 */
#define BCHP_ITU656_CSC_0_CSC_COEFF_C21_C20      0x00685a20 /* Video Encoder Color Matrix coefficients c21 and c20 */
#define BCHP_ITU656_CSC_0_CSC_COEFF_C23_C22      0x00685a24 /* Video Encoder Color Matrix coefficients c23 and c22 */
#define BCHP_ITU656_CSC_0_DITHER_CONTROL         0x00685a28 /* Color Space Converter Dither Control */
#define BCHP_ITU656_CSC_0_DITHER_LFSR            0x00685a2c /* Color Space Converter Dither LFSR Control */
#define BCHP_ITU656_CSC_0_DITHER_LFSR_INIT       0x00685a30 /* Color Space Converter Dither LFSR Init value and control */

#endif /* #ifndef BCHP_ITU656_CSC_0_H__ */

/* End of File */
