-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = generatemodelcert

DRM_MODULE_CFLAGS =

SOURCES =                \
	 generatemodelcert.c  
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
