obj-$(CONFIG_MW_CH_SATELLITE)	+= base/
obj-y							+= pmgr_antenna.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

