
obj-y += oapi_platform.o

obj-y += meta/
obj-y += media/
obj-y += builder/
obj-y += resource/
obj-y += output/
obj-y += sysinfo/
obj-y += scenario/
obj-y += exe/
obj-y += cas/
obj-y += swupdate/
obj-y += dsmcc/
obj-y += drmagent/
obj-y += extdev/
obj-y += download/

# ---- include path----
ccflags-y += -I$(HLIB_DIR)/include
ccflags-y += -I$(DLIB_DIR)/include
ccflags-y += -I$(OCTO_DIR)/include
ccflags-y += -I$(OCTO_DIR)/api/protocol
ccflags-y += -I$(OCTO_DIR)/main/oxserver/include


