#!/bin/sh

case "$1" in
    start)
		# Create core dump with executable name and process id
		# Ref.: http://www.linuxhowtos.org/Tips%20and%20Tricks/coredump.htm
		echo "core.%e.%p" > /proc/sys/kernel/core_pattern
		# Remove previouse core dump and log files
		rm -f /core*  /*.comm /rpclog.* /*.dump
		
		# Enable core dump
		ulimit -c unlimited
		export UVA_DRM_LIB="/usr/lib/libuvadrmbackendloader.so"
		export UVA_DRM_LIB_DIR="/usr/browser/drm/"
		# 1920x1080 browser
		export CORSAIR_SCREEN_WIDTH="1920"
		export CORSAIR_SCREEN_HEIGHT="1080"
		# Run PCD
		exec dfbmaster &
		exec /home/hamalauncher &		
		exec /home/hama &
		;;
    stop)
		if [ "$VERBOSE" != no ]; then
			log_begin_msg "Stopping Application processes"
		fi
		killall obama
		killall corsair
		;;
    *)
		if [ "$VERBOSE" != no ]; then
			log_success_msg "Usage: /etc/init.d/S90settop {start|stop}"
		fi
		exit 1
		;;
esac

