obj-y += nx_prism_menu_smartcard_info_ir.o
obj-y += nx_prism_menu_conditional_access.o
obj-y += nx_prism_menu_ca_service_list.o
obj-y += nx_prism_menu_ca_service_status.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include

# Additional include path
cclfags-y += -IS(NATIVEAPP_UI_INCLUDE_DIR)/include
ccflags-y += -I$(NATIVEAPP_PORT_INCLUDE_DIR)/include

