-include ./dirs

ifeq ($(DIRS),)
TARGET = contentrevocationreal

SOURCES =                \
	contentrevocationlevlreal.c contentrevocationlicreal.c contentrevocationutilreal.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
