obj-y += otl_hjm.o
obj-y += otl_hjm_scanner.o

###################################
# OCTO flags & include dirs
###################################

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.pal

# Additional include path

