#!/bin/sh

	umount /var/lib/humaxtv
	umount /var/lib/humaxtv_backup
	umount /var/lib/humaxtv_user
	ubidetach -m 10
	ubiformat -y /dev/mtd10
	ubiattach -m 10
	ubimkvol /dev/ubi1 -N dbbackup -s 32MiB
	ubimkvol /dev/ubi1 -N dbdata -s 32MiB
	ubimkvol /dev/ubi1 -N dbuser -s 256MiB	
	ubidetach -m 10
