obj-y					+= pal_param.o
#obj-$(CONFIG_DEBUG)		+= pal_param_cmd.o

# Basic include path
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.pal
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/include
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/pal/include
# Additional include path

