obj-y								+= base/
obj-$(CONFIG_MW_CH_SATELLITE)		+= base_sat/
obj-$(CONFIG_MW_CH_CABLE)			+= base_cab/
obj-$(CONFIG_MW_CH_TERRESTRIAL)		+= base_ter/

obj-$(CONFIG_OP_SES)				+= ses/
obj-$(CONFIG_OP_ERTELECOM)			+= ertelecom/
obj-$(CONFIG_OP_ZIGGO)				+= ziggo/
obj-$(CONFIG_OP_NORDIG)				+= nordig/
obj-$(CONFIG_OP_MBC)				+= mbc/

obj-y		+= xmgr_search.o
obj-y		+= pmgr_search.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

