/***************************************************************************
 *     Copyright (c) 2005-2013, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * [File Description:]
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#ifndef _BWFE_4538_PRIV_H__
#define _BWFE_4538_PRIV_H__

#include "bchp_leap_l1.h"
#include "bchp_aif_mdac_cal_core0.h"
#include "bchp_aif_mdac_cal_core_intr2_0.h"
#include "bchp_aif_mdac_cal_ana_u1.h"
#include "bchp_aif_wb_sat_core0_0.h"
#include "bchp_aif_wb_sat_core_intr2_0_0.h"
#include "bchp_aif_wb_sat_ana_u1_0.h"
#include "bchp_tm.h"
#include "bchp_bac_mspi.h"


//#define BWFE_BYPASS_DGS
#define BWFE_BYPASS_LIC
//#define BWFE_BYPASS_LIC2
#define BWFE_BYPASS_INL
#define BWFE_BYPASS_EQU

#define BWFE_G2_BUILD_VERSION 0x01
#define BWFE_NUM_CHANNELS     4     /* 1 input ADC x 4 */
#define BWFE_CHANNELS_MASK    0xF
#define BWFE_NUM_REF_CHANNELS 1
#define BWFE_NUM_SLICES       4
#define BWFE_NUM_REF_SLICES   1
#define BWFE_NUM_LANES        2
#define BWFE_NUM_DMX_LANES    2
#define BWFE_NUM_MDACS        2
#define BWFE_NUM_LIC_TAPS     16    /* 16 taps per lane, no DCO tap */
#define BWFE_NUM_EQ_TAPS      4
#define BWFE_NUM_ADC_PHASES   8
#define BWFE_XTAL_FREQ_KHZ    54000

#define BWFE_LIC_L            (BWFE_NUM_SLICES * BWFE_NUM_LANES * BWFE_NUM_DMX_LANES)
#define BWFE_LIC_S            8  /* TBD */

#if FS_ADC==4968
#define BWFE_DEF_FS_ADC_KHZ   4968000  /* Fs_adc = 4968MHz */
#else
#define BWFE_DEF_FS_ADC_KHZ   4860000  /* Fs_adc = 4860MHz */
#endif
#define BWFE_DEF_FC_DPM_KHZ   2358000  /* Fc_dpm = 2358MHz */


/* wfe channel 0 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_0          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF0_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_0          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF0_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_0        BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF0_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC3_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF0_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC3_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC2_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF0_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC2_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF0_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF0_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC3_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF0_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC3_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC2_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF0_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC2_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF0_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF0_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* wfe channel 1 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_1          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF1_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_1          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF1_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_1        BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF1_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC3_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF1_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC3_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC2_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF1_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC2_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF1_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF1_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC3_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF1_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC3_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC2_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF1_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC2_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF1_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_1  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF1_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* wfe channel 2 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_2          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF2_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_2          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF2_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_2        BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF2_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC3_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF2_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC3_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC2_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF2_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC2_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF2_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF2_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC3_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF2_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC3_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC2_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF2_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC2_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF2_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_2  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF2_INTR_SHIFT, BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* wfe channel 3 interrupts */
#define BCHP_INT_ID_WFE_TIMER0_3          BINT_LEAP_INT_ID_CREATE((BCHP_LEAP_L1_INTR_W1_STATUS_AIF3_INTR_SHIFT+32), BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_TIMER1_3          BINT_LEAP_INT_ID_CREATE((BCHP_LEAP_L1_INTR_W1_STATUS_AIF3_INTR_SHIFT+32), BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CORRDONE_3        BINT_LEAP_INT_ID_CREATE((BCHP_LEAP_L1_INTR_W1_STATUS_AIF3_INTR_SHIFT+32), BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CORR_CNT_DONE_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC3_3  BINT_LEAP_INT_ID_CREATE((BCHP_LEAP_L1_INTR_W1_STATUS_AIF3_INTR_SHIFT+32), BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC3_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC2_3  BINT_LEAP_INT_ID_CREATE((BCHP_LEAP_L1_INTR_W1_STATUS_AIF3_INTR_SHIFT+32), BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC2_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC1_3  BINT_LEAP_INT_ID_CREATE((BCHP_LEAP_L1_INTR_W1_STATUS_AIF3_INTR_SHIFT+32), BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PO_SLC0_3  BINT_LEAP_INT_ID_CREATE((BCHP_LEAP_L1_INTR_W1_STATUS_AIF3_INTR_SHIFT+32), BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PONG_SLC0_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC3_3  BINT_LEAP_INT_ID_CREATE((BCHP_LEAP_L1_INTR_W1_STATUS_AIF3_INTR_SHIFT+32), BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC3_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC2_3  BINT_LEAP_INT_ID_CREATE((BCHP_LEAP_L1_INTR_W1_STATUS_AIF3_INTR_SHIFT+32), BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC2_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC1_3  BINT_LEAP_INT_ID_CREATE((BCHP_LEAP_L1_INTR_W1_STATUS_AIF3_INTR_SHIFT+32), BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC1_INTR_SHIFT)
#define BCHP_INT_ID_WFE_CLPDTR_PI_SLC0_3  BINT_LEAP_INT_ID_CREATE((BCHP_LEAP_L1_INTR_W1_STATUS_AIF3_INTR_SHIFT+32), BCHP_AIF_WB_SAT_CORE_INTR2_0_0_CPU_STATUS_CLPDTR_PING_SLC0_INTR_SHIFT)

/* mdac cal channel 0 interrupts */
#define BCHP_INT_ID_MDAC_CAL_TIMER0_0     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_MDAC_INTR_SHIFT, BCHP_AIF_MDAC_CAL_CORE_INTR2_0_CPU_MASK_STATUS_TIMER0_INTR_SHIFT)
#define BCHP_INT_ID_MDAC_CAL_TIMER1_0     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_MDAC_INTR_SHIFT, BCHP_AIF_MDAC_CAL_CORE_INTR2_0_CPU_MASK_STATUS_TIMER1_INTR_SHIFT)
#define BCHP_INT_ID_MDAC_CAL_CLPDTR_PO_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_MDAC_INTR_SHIFT, BCHP_AIF_MDAC_CAL_CORE_INTR2_0_CPU_MASK_STATUS_CLPDTR_PONG_INTR_SHIFT)
#define BCHP_INT_ID_MDAC_CAL_CLPDTR_PI_0  BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AIF_MDAC_INTR_SHIFT, BCHP_AIF_MDAC_CAL_CORE_INTR2_0_CPU_MASK_STATUS_CLPDTR_PING_INTR_SHIFT)


/* WFE base registers */
#define BCHP_WFE_CORE_RSTCTL                 BCHP_AIF_WB_SAT_CORE0_0_RSTCTL
#define BCHP_WFE_CORE_HDOFFCTL0              BCHP_AIF_WB_SAT_CORE0_0_HDOFFCTL0
#define BCHP_WFE_CORE_HDOFFCTL1              BCHP_AIF_WB_SAT_CORE0_0_HDOFFCTL1
#define BCHP_WFE_CORE_HDOFFCTL2              BCHP_AIF_WB_SAT_CORE0_0_HDOFFCTL2
#define BCHP_WFE_CORE_HDOFFSTS               BCHP_AIF_WB_SAT_CORE0_0_HDOFFSTS
#define BCHP_WFE_CORE_MDACSASTS              BCHP_AIF_WB_SAT_CORE0_0_MDACSASTS
#define BCHP_WFE_CORE_LICCTL1                BCHP_AIF_WB_SAT_CORE0_0_LICCTL1
#define BCHP_WFE_CORE_LICCTL2                BCHP_AIF_WB_SAT_CORE0_0_LICCTL2
#define BCHP_WFE_CORE_LICCTL3                BCHP_AIF_WB_SAT_CORE0_0_LICCTL3
#define BCHP_WFE_CORE_LICCTL4                BCHP_AIF_WB_SAT_CORE0_0_LICCTL4
#define BCHP_WFE_CORE_LICCTL5                BCHP_AIF_WB_SAT_CORE0_0_LICCTL5
#define BCHP_WFE_CORE_LICCOEFD               BCHP_AIF_WB_SAT_CORE0_0_LICCOEFD
#define BCHP_WFE_CORE_LICCOEFA               BCHP_AIF_WB_SAT_CORE0_0_LICCOEFA
#define BCHP_WFE_CORE_LICCOEFEN              BCHP_AIF_WB_SAT_CORE0_0_LICCOEFEN
#define BCHP_WFE_CORE_CORRINSEL              BCHP_AIF_WB_SAT_CORE0_0_CORRINSEL
#define BCHP_WFE_CORE_CORRCTL                BCHP_AIF_WB_SAT_CORE0_0_CORRCTL
#define BCHP_WFE_CORE_CORRFCW                BCHP_AIF_WB_SAT_CORE0_0_CORRFCW
#define BCHP_WFE_CORE_CORRTHR                BCHP_AIF_WB_SAT_CORE0_0_CORRTHR
#define BCHP_WFE_CORE_CORRFCWEN              BCHP_AIF_WB_SAT_CORE0_0_CORRFCWEN
#define BCHP_WFE_CORE_CORRLEN0               BCHP_AIF_WB_SAT_CORE0_0_CORRLEN0
#define BCHP_WFE_CORE_CORRLEN1               BCHP_AIF_WB_SAT_CORE0_0_CORRLEN1
#define BCHP_WFE_CORE_TIMERCTL0              BCHP_AIF_WB_SAT_CORE0_0_TIMERCTL0
#define BCHP_WFE_CORE_TIMERCTL1              BCHP_AIF_WB_SAT_CORE0_0_TIMERCTL1
#define BCHP_WFE_CORE_AGCCTL2                            BCHP_AIF_WB_SAT_CORE0_0_AGCCTL2
#define BCHP_WFE_CORE_AGCDECRATE                         BCHP_AIF_WB_SAT_CORE0_0_AGCDECRATE
#define BCHP_WFE_CORE_AGCCTL1                            BCHP_AIF_WB_SAT_CORE0_0_AGCCTL1
#define BCHP_WFE_CORE_AGCTHRA1                           BCHP_AIF_WB_SAT_CORE0_0_AGCTHRA1
#define BCHP_WFE_CORE_REG_AGC_LF_INT_WDATA               BCHP_AIF_WB_SAT_CORE0_0_REG_AGC_LF_INT_WDATA
#define BCHP_WFE_CORE_REG_AGC_LA_INT_WDATA               BCHP_AIF_WB_SAT_CORE0_0_REG_AGC_LA_INT_WDATA
#define BCHP_WFE_CORE_REG_AGC_CTRL_LF_INT_WDATA          BCHP_AIF_WB_SAT_CORE0_0_REG_AGC_CTRL_LF_INT_WDATA
#define BCHP_WFE_CORE_REG_AGC_CTRL_LA_INT_WDATA          BCHP_AIF_WB_SAT_CORE0_0_REG_AGC_CTRL_LA_INT_WDATA
#define BCHP_WFE_CORE_AGCTHRA2                           BCHP_AIF_WB_SAT_CORE0_0_AGCTHRA2
#define BCHP_WFE_CORE_NRNOTCHCTL                         BCHP_AIF_WB_SAT_CORE0_0_NRNOTCHCTL
#define BCHP_WFE_CORE_NRAGCTHR                           BCHP_AIF_WB_SAT_CORE0_0_NRAGCTHR
#define BCHP_WFE_CORE_NRDCOCTL_THR                       BCHP_AIF_WB_SAT_CORE0_0_NRDCOCTL_THR
#define BCHP_WFE_CORE_REG_NR_DCO_INT_WDATA_THR           BCHP_AIF_WB_SAT_CORE0_0_REG_NR_DCO_INT_WDATA_THR
#define BCHP_WFE_CORE_CORE_SW_SPARE0                     BCHP_AIF_WB_SAT_CORE0_0_CORE_SW_SPARE0
#define BCHP_WFE_CORE_CORE_SW_SPARE1                     BCHP_AIF_WB_SAT_CORE0_0_CORE_SW_SPARE1

/* WFE slice registers */
#define BCHP_WFE_CORE_DGSCTL_PI_SLC          BCHP_AIF_WB_SAT_CORE0_0_DGSCTL_PI_SLC0
#define BCHP_WFE_CORE_DGSCTL_PO_SLC          BCHP_AIF_WB_SAT_CORE0_0_DGSCTL_PO_SLC0
#define BCHP_WFE_CORE_DGSCLP_PI_SLC          BCHP_AIF_WB_SAT_CORE0_0_DGSCLP_PI_SLC0
#define BCHP_WFE_CORE_DGSCLP_PO_SLC          BCHP_AIF_WB_SAT_CORE0_0_DGSCLP_PO_SLC0
#define BCHP_WFE_CORE_DGSHIST_PI_SLC         BCHP_AIF_WB_SAT_CORE0_0_DGSHIST_PI_SLC0
#define BCHP_WFE_CORE_DGSHIST_PO_SLC         BCHP_AIF_WB_SAT_CORE0_0_DGSHIST_PO_SLC0
#define BCHP_WFE_CORE_DGSCLPCNT_PI_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSCLPCNT_PI_SLC0
#define BCHP_WFE_CORE_DGSCLPCNT_PO_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSCLPCNT_PO_SLC0
#define BCHP_WFE_CORE_DGSACCUM_DMX0_PI_SLC   BCHP_AIF_WB_SAT_CORE0_0_DGSACCUM_DMX0_PI_SLC0
#define BCHP_WFE_CORE_DGSACCUM_DMX0_PO_SLC   BCHP_AIF_WB_SAT_CORE0_0_DGSACCUM_DMX0_PO_SLC0
#define BCHP_WFE_CORE_DGSACCUM_DMX1_PI_SLC   BCHP_AIF_WB_SAT_CORE0_0_DGSACCUM_DMX1_PI_SLC0
#define BCHP_WFE_CORE_DGSACCUM_DMX1_PO_SLC   BCHP_AIF_WB_SAT_CORE0_0_DGSACCUM_DMX1_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT011_PI_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT011_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT010_PI_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT010_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT001_PI_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT001_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT000_PI_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT000_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT111_PI_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT111_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT110_PI_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT110_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT101_PI_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT101_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT100_PI_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT100_PI_SLC0
#define BCHP_WFE_CORE_DGSLUT011_PO_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT011_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT010_PO_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT010_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT001_PO_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT001_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT000_PO_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT000_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT111_PO_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT111_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT110_PO_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT110_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT101_PO_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT101_PO_SLC0
#define BCHP_WFE_CORE_DGSLUT100_PO_SLC       BCHP_AIF_WB_SAT_CORE0_0_DGSLUT100_PO_SLC0
#define BCHP_WFE_CORE_DGSLMS_SLC             BCHP_AIF_WB_SAT_CORE0_0_DGSLMS_SLC0
#define BCHP_WFE_CORE_DGSLMSMU_SLC           BCHP_AIF_WB_SAT_CORE0_0_DGSLMSMU_SLC0
#define BCHP_WFE_CORE_DGSCOEFD_SLC           BCHP_AIF_WB_SAT_CORE0_0_DGSCOEFD_SLC0
#define BCHP_WFE_CORE_DGSCOEFA_SLC           BCHP_AIF_WB_SAT_CORE0_0_DGSCOEFA_SLC0
#define BCHP_WFE_CORE_DGSCOEFEN_SLC          BCHP_AIF_WB_SAT_CORE0_0_DGSCOEFEN_SLC0
#define BCHP_WFE_CORE_MDACSA_SLC             BCHP_AIF_WB_SAT_CORE0_0_MDACSA_SLC0
#define BCHP_WFE_CORE_MDACSADU_SLC           BCHP_AIF_WB_SAT_CORE0_0_MDACSADU_SLC0
#define BCHP_WFE_CORE_MDACSAOUT_SLC          BCHP_AIF_WB_SAT_CORE0_0_MDACSAOUT_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX0_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRI0_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX0_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRI1_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX0_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRI0_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX0_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRI1_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX1_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRI0_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX1_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRI1_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRI0_DMX1_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRI0_DMX1_PO_SLC0
#define BCHP_WFE_CORE_CORRI1_DMX1_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRI1_DMX1_PO_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX0_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRQ0_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX0_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRQ1_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX0_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRQ0_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX0_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRQ1_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX1_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRQ0_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX1_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRQ1_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRQ0_DMX1_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRQ0_DMX1_PO_SLC0
#define BCHP_WFE_CORE_CORRQ1_DMX1_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRQ1_DMX1_PO_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX0_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRP0_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX0_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRP1_DMX0_PI_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX0_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRP0_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX0_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRP1_DMX0_PO_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX1_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRP0_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX1_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRP1_DMX1_PI_SLC0
#define BCHP_WFE_CORE_CORRP0_DMX1_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRP0_DMX1_PO_SLC0
#define BCHP_WFE_CORE_CORRP1_DMX1_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_CORRP1_DMX1_PO_SLC0
#define BCHP_WFE_CORE_DGSEPCTL_SLC           BCHP_AIF_WB_SAT_CORE0_0_DGSEPCTL_SLC0
#define BCHP_WFE_CORE_REG_DGSEP_DMX0_PI_SLC_INT_WDATA    BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_DMX0_PI_SLC0_INT_WDATA
#define BCHP_WFE_CORE_REG_DGSEP_DMX0_PO_SLC_INT_WDATA    BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_DMX0_PO_SLC0_INT_WDATA
#define BCHP_WFE_CORE_REG_DGSEP_DMX1_PI_SLC_INT_WDATA    BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_DMX1_PI_SLC0_INT_WDATA
#define BCHP_WFE_CORE_REG_DGSEP_DMX1_PO_SLC_INT_WDATA    BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_DMX1_PO_SLC0_INT_WDATA	
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX0_PI_SLC_ERRP      BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_S1_DMX0_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX0_PI_SLC_ERRP      BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_S2_DMX0_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX0_PO_SLC_ERRP      BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_S1_DMX0_PO_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX0_PO_SLC_ERRP      BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_S2_DMX0_PO_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX1_PI_SLC_ERRP      BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_S1_DMX1_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX1_PI_SLC_ERRP      BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_S2_DMX1_PI_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S1_DMX1_PO_SLC_ERRP      BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_S1_DMX1_PO_SLC0_ERRP
#define BCHP_WFE_CORE_REG_DGSEP_S2_DMX1_PO_SLC_ERRP      BCHP_AIF_WB_SAT_CORE0_0_REG_DGSEP_S2_DMX1_PO_SLC0_ERRP
#define BCHP_WFE_CORE_NRDCOCTL_PI_SLC                    BCHP_AIF_WB_SAT_CORE0_0_NRDCOCTL_PI_SLC0
#define BCHP_WFE_CORE_REG_NR_DCO_INT_WDATA_PI_SLC        BCHP_AIF_WB_SAT_CORE0_0_REG_NR_DCO_INT_WDATA_PI_SLC0
#define BCHP_WFE_CORE_NRDCOCTL_PO_SLC                    BCHP_AIF_WB_SAT_CORE0_0_NRDCOCTL_PO_SLC0
#define BCHP_WFE_CORE_REG_NR_DCO_INT_WDATA_PO_SLC        BCHP_AIF_WB_SAT_CORE0_0_REG_NR_DCO_INT_WDATA_PO_SLC0
#define BCHP_WFE_CORE_NRNOTCHCTL_PI_SLC                  BCHP_AIF_WB_SAT_CORE0_0_NRNOTCHCTL_PI_SLC0
#define BCHP_WFE_CORE_REG_NR_NOTCH_INT_WDATA_PI_SLC      BCHP_AIF_WB_SAT_CORE0_0_REG_NR_NOTCH_INT_WDATA_PI_SLC0
#define BCHP_WFE_CORE_NRNOTCHCTL_PO_SLC                  BCHP_AIF_WB_SAT_CORE0_0_NRNOTCHCTL_PO_SLC0
#define BCHP_WFE_CORE_REG_NR_NOTCH_INT_WDATA_PO_SLC      BCHP_AIF_WB_SAT_CORE0_0_REG_NR_NOTCH_INT_WDATA_PO_SLC0
#define BCHP_WFE_CORE_NRAGCCTL_PI_SLC                    BCHP_AIF_WB_SAT_CORE0_0_NRAGCCTL_PI_SLC0
#define BCHP_WFE_CORE_REG_NR_AGC_LF_INT_WDATA_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_REG_NR_AGC_LF_INT_WDATA_PI_SLC0
#define BCHP_WFE_CORE_REG_NR_AGC_LA_INT_WDATA_PI_SLC     BCHP_AIF_WB_SAT_CORE0_0_REG_NR_AGC_LA_INT_WDATA_PI_SLC0
#define BCHP_WFE_CORE_NRAGCCTL_PO_SLC                    BCHP_AIF_WB_SAT_CORE0_0_NRAGCCTL_PO_SLC0
#define BCHP_WFE_CORE_REG_NR_AGC_LF_INT_WDATA_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_REG_NR_AGC_LF_INT_WDATA_PO_SLC0
#define BCHP_WFE_CORE_REG_NR_AGC_LA_INT_WDATA_PO_SLC     BCHP_AIF_WB_SAT_CORE0_0_REG_NR_AGC_LA_INT_WDATA_PO_SLC0

/* WFE analog base registers */
#define BCHP_WFE_ANA_ADC_CNTL0                     BCHP_AIF_WB_SAT_ANA_U1_0_ADC_CNTL0
#define BCHP_WFE_ANA_ADC_CNTL1                     BCHP_AIF_WB_SAT_ANA_U1_0_ADC_CNTL1
#define BCHP_WFE_ANA_ADC_CNTL2                     BCHP_AIF_WB_SAT_ANA_U1_0_ADC_CNTL2
#define BCHP_WFE_ANA_ADC_CNTL3                     BCHP_AIF_WB_SAT_ANA_U1_0_ADC_CNTL3
#define BCHP_WFE_ANA_DPM_CNTL0_IN                  BCHP_AIF_WB_SAT_ANA_U1_0_DPM_CNTL0_IN0
#define BCHP_WFE_ANA_DPM_CNTL1_IN                  BCHP_AIF_WB_SAT_ANA_U1_0_DPM_CNTL1_IN0
#define BCHP_WFE_ANA_DPM_PLL_CNTL0_IN              BCHP_AIF_WB_SAT_ANA_U1_0_DPM_PLL_CNTL0_IN0
#define BCHP_WFE_ANA_DPM_PLL_CNTL1_IN              BCHP_AIF_WB_SAT_ANA_U1_0_DPM_PLL_CNTL1_IN0
#define BCHP_WFE_ANA_DPM_PLL_CNTL2_IN              BCHP_AIF_WB_SAT_ANA_U1_0_DPM_PLL_CNTL2_IN0
#define BCHP_WFE_ANA_RFFE_CNTL0_IN                 BCHP_AIF_WB_SAT_ANA_U1_0_RFFE_CNTL0_IN0
#define BCHP_WFE_ANA_RFFE_CNTL1_IN                 BCHP_AIF_WB_SAT_ANA_U1_0_RFFE_CNTL1_IN0
#define BCHP_WFE_ANA_WBADC_CAL_CNTL_IN             BCHP_AIF_WB_SAT_ANA_U1_0_WBADC_CAL_CNTL_IN0
#define BCHP_WFE_ANA_WBADC_SYS_CNTL_IN             BCHP_AIF_WB_SAT_ANA_U1_0_WBADC_SYS_CNTL_IN0
#define BCHP_WFE_ANA_WBADC_TIMING_CNTL1_IN         BCHP_AIF_WB_SAT_ANA_U1_0_WBADC_TIMING_CNTL1_IN0
#define BCHP_WFE_ANA_WBADC_TIMING_CNTL_IN          BCHP_AIF_WB_SAT_ANA_U1_0_WBADC_TIMING_CNTL_IN0
#define BCHP_WFE_ANA_WBADC_TOP_CNTL_IN             BCHP_AIF_WB_SAT_ANA_U1_0_WBADC_TOP_CNTL_IN0
#define BCHP_WFE_ANA_CLK_CTRL_IN                   BCHP_AIF_WB_SAT_ANA_U1_0_CLK_CTRL_IN0
#define BCHP_WFE_ANA_PGA_GAIN_IN                   BCHP_AIF_WB_SAT_ANA_U1_0_PGA_GAIN_IN0
#define BCHP_WFE_ANA_SW_SPARE0                     BCHP_AIF_WB_SAT_ANA_U1_0_SW_SPARE0
#define BCHP_WFE_ANA_SW_SPARE1                     BCHP_AIF_WB_SAT_ANA_U1_0_SW_SPARE1

/* MDAC_CAL base registers */
#define BCHP_MDAC_CAL_CORE_RSTCTL                  BCHP_AIF_MDAC_CAL_CORE0_RSTCTL
#define BCHP_MDAC_CAL_CORE_HDOFFCTL0               BCHP_AIF_MDAC_CAL_CORE0_HDOFFCTL0
#define BCHP_MDAC_CAL_CORE_HDOFFCTL1               BCHP_AIF_MDAC_CAL_CORE0_HDOFFCTL1
#define BCHP_MDAC_CAL_CORE_HDOFFSTS                BCHP_AIF_MDAC_CAL_CORE0_HDOFFSTS
#define BCHP_MDAC_CAL_CORE_MDACSASTS               BCHP_AIF_MDAC_CAL_CORE0_MDACSASTS
#define BCHP_MDAC_CAL_CORE_DOUTCTL                 BCHP_AIF_MDAC_CAL_CORE0_DOUTCTL
#define BCHP_MDAC_CAL_CORE_TIMERCTL0               BCHP_AIF_MDAC_CAL_CORE0_TIMERCTL0
#define BCHP_MDAC_CAL_CORE_TIMERCTL1               BCHP_AIF_MDAC_CAL_CORE0_TIMERCTL1

/* MDAC_CAL slice registers */
#define BCHP_MDAC_CAL_CORE_DGSCTL_PI_SLC           BCHP_AIF_MDAC_CAL_CORE0_DGSCTL_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCTL_PO_SLC           BCHP_AIF_MDAC_CAL_CORE0_DGSCTL_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCLP_PI_SLC           BCHP_AIF_MDAC_CAL_CORE0_DGSCLP_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCLP_PO_SLC           BCHP_AIF_MDAC_CAL_CORE0_DGSCLP_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSHIST_PI_SLC          BCHP_AIF_MDAC_CAL_CORE0_DGSHIST_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSHIST_PO_SLC          BCHP_AIF_MDAC_CAL_CORE0_DGSHIST_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCLPCNT_PI_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSCLPCNT_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCLPCNT_PO_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSCLPCNT_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSACCUM_DMX0_PI_SLC    BCHP_AIF_MDAC_CAL_CORE0_DGSACCUM_DMX0_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSACCUM_DMX0_PO_SLC    BCHP_AIF_MDAC_CAL_CORE0_DGSACCUM_DMX0_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSACCUM_DMX1_PI_SLC    BCHP_AIF_MDAC_CAL_CORE0_DGSACCUM_DMX1_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSACCUM_DMX1_PO_SLC    BCHP_AIF_MDAC_CAL_CORE0_DGSACCUM_DMX1_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT011_PI_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT011_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT010_PI_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT010_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT001_PI_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT001_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT000_PI_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT000_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT111_PI_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT111_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT110_PI_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT110_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT101_PI_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT101_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT100_PI_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT100_PI_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT011_PO_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT011_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT010_PO_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT010_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT001_PO_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT001_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT000_PO_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT000_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT111_PO_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT111_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT110_PO_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT110_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT101_PO_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT101_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLUT100_PO_SLC        BCHP_AIF_MDAC_CAL_CORE0_DGSLUT100_PO_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLMS_SLC              BCHP_AIF_MDAC_CAL_CORE0_DGSLMS_SLC0
#define BCHP_MDAC_CAL_CORE_DGSLMSMU_SLC            BCHP_AIF_MDAC_CAL_CORE0_DGSLMSMU_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCOEFD_SLC            BCHP_AIF_MDAC_CAL_CORE0_DGSCOEFD_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCOEFA_SLC            BCHP_AIF_MDAC_CAL_CORE0_DGSCOEFA_SLC0
#define BCHP_MDAC_CAL_CORE_DGSCOEFEN_SLC           BCHP_AIF_MDAC_CAL_CORE0_DGSCOEFEN_SLC0
#define BCHP_MDAC_CAL_CORE_MDACSA_SLC              BCHP_AIF_MDAC_CAL_CORE0_MDACSA_SLC0
#define BCHP_MDAC_CAL_CORE_MDACSADU_SLC            BCHP_AIF_MDAC_CAL_CORE0_MDACSADU_SLC0
#define BCHP_MDAC_CAL_CORE_MDACSAOUT_SLC           BCHP_AIF_MDAC_CAL_CORE0_MDACSAOUT_SLC0
#define BCHP_MDAC_CAL_CORE_DGSEPCTL_SLC            BCHP_AIF_MDAC_CAL_CORE0_DGSEPCTL_SLC0
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX0_PI_SLC_INT_WDATA  BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_DMX0_PI_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX0_PO_SLC_INT_WDATA	BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_DMX0_PO_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX1_PI_SLC_INT_WDATA  BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_DMX1_PI_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_DMX1_PO_SLC_INT_WDATA  BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_DMX1_PO_SLC0_INT_WDATA
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX0_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_S1_DMX0_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX0_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_S2_DMX0_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX0_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_S1_DMX0_PO_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX0_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_S2_DMX0_PO_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX1_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_S1_DMX1_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX1_PI_SLC_ERRP    BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_S2_DMX1_PI_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S1_DMX1_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_S1_DMX1_PO_SLC0_ERRP
#define BCHP_MDAC_CAL_CORE_REG_DGSEP_S2_DMX1_PO_SLC_ERRP    BCHP_AIF_MDAC_CAL_CORE0_REG_DGSEP_S2_DMX1_PO_SLC0_ERRP

/* MDAC analog base registers */
#define BCHP_MDAC_CAL_ANA_ADC_CNTL0                BCHP_AIF_MDAC_CAL_ANA_U1_ADC_CNTL0
#define BCHP_MDAC_CAL_ANA_ADC_CNTL1                BCHP_AIF_MDAC_CAL_ANA_U1_ADC_CNTL1
#define BCHP_MDAC_CAL_ANA_ADC_CNTL2                BCHP_AIF_MDAC_CAL_ANA_U1_ADC_CNTL2
#define BCHP_MDAC_CAL_ANA_ADC_CNTL3                BCHP_AIF_MDAC_CAL_ANA_U1_ADC_CNTL3
#define BCHP_MDAC_CAL_ANA_WBADC_CAL_CNTL_IN        BCHP_AIF_MDAC_CAL_ANA_U1_WBADC_CAL_CNTL_IN0
#define BCHP_MDAC_CAL_ANA_WBADC_SYS_CNTL_IN        BCHP_AIF_MDAC_CAL_ANA_U1_WBADC_SYS_CNTL_IN0
#define BCHP_MDAC_CAL_ANA_WBADC_TIMING_CNTL_IN     BCHP_AIF_MDAC_CAL_ANA_U1_WBADC_TIMING_CNTL_IN0
#define BCHP_MDAC_CAL_ANA_WBADC_TOP_CNTL_IN        BCHP_AIF_MDAC_CAL_ANA_U1_WBADC_TOP_CNTL_IN0
#define BCHP_MDAC_CAL_ANA_CLK_CTRL_IN              BCHP_AIF_MDAC_CAL_ANA_U1_CLK_CTRL_IN0
#define BCHP_MDAC_CAL_ANA_SW_SPARE0                BCHP_AIF_MDAC_CAL_ANA_U1_SW_SPARE0
#define BCHP_MDAC_CAL_ANA_SW_SPARE1                BCHP_AIF_MDAC_CAL_ANA_U1_SW_SPARE1

#endif /* BWFE_4538_PRIV_H__ */
