#!/bin/sh
# Start all init scripts in /etc/init.d
# executing them in numerical order.
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Source defaults.
. /etc/default/rcS
export VERBOSE

# Trap CTRL-C &c only int this shell so we can interrupt subprocesses.
trap ":" INT QUIT TSTP

steps=$(echo /etc/init.d/S??*)

for i in $steps
do
     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.source)
	    source $i
	    ;;     
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

