-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = secureclockgeneratechallenge

DRM_MODULE_CFLAGS =

SOURCES =                \
	 secureclockgeneratechallenge.c
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
