
#ifndef __OPLVIDEOBROADCASTHANDLEDEF_H__
#define __OPLVIDEOBROADCASTHANDLEDEF_H__

/******************************************************************
	Define
******************************************************************/
#define OPLRECORDER_MAX_RECORDID_LEN					2048

/******************************************************************
	Enum
 ******************************************************************/
typedef enum {
	OPLBROADCAST_CHANNEL_ERROR_CHANNEL_NOT_SUPPORTED	= 0,
	OPLBROADCAST_CHANNEL_ERROR_CANNOT_TUNE,
	OPLBROADCAST_CHANNEL_ERROR_TUNER_LOCK,
	OPLBROADCAST_CHANNEL_ERROR_PARENTAL_LOCK,
	OPLBROADCAST_CHANNEL_ERROR_ENCRYPTED_CHANNEL,
	OPLBROADCAST_CHANNEL_ERROR_UNKNOWN_CHANNEL,
	OPLBROADCAST_CHANNEL_ERROR_CHANNEL_SWITCH_INTERRUPTED,
	OPLBROADCAST_CHANNEL_ERROR_CANNOT_TUNE_DUETO_RECORD,
	OPLBROADCAST_CHANNEL_ERROR_CANNOT_RESOLVE_IP_CHANNEL,
	OPLBROADCAST_CHANNEL_ERROR_BANDWIDTH,
	OPLBROADCAST_CHANNEL_ERROR_CANNOT_SUPPORT_CHANNEL_LIST,
	OPLBROADCAST_CHANNEL_ERROR_INSUFFICIENT_RESOURCE,
	OPLBROADCAST_CHANNEL_ERROR_NOT_FOUND_IN_TRANSPORT,
	/*humax 확장 start*/
	OPLBROADCAST_CHANNEL_ERROR_MOTOR_MOVING,
	OPLBROADCAST_CHANNEL_ERROR_CAS_BLOCK,
	OPLBROADCAST_CHANNEL_ERROR_PIN_DENIED,
	OPLBROADCAST_CHANNEL_ERROR_AV_UNDERRUN,
	OPLBROADCAST_CHANNEL_ERROR_HDMI_BLOCK,
	OPLBROADCAST_CHANNEL_ERROR_7DAY_TIMER_BLOCK,
	OPLBROADCAST_CHANNEL_ERROR_NO_VIDEO,
	OPLBROADCAST_CHANNEL_ERROR_NO_AV,
	OPLBROADCAST_CHANNEL_ERROR_NOT_RUNNING,
	OPLBROADCAST_CHANNEL_ERROR_NO_EIT,
	OPLBROADCAST_CHANNEL_ERROR_5_TIMES_PIN_FAIL,
	OPLBROADCAST_CHANNEL_ERROR_60DAY_FTA_LIMIT,
	OPLBROADCAST_CHANNEL_ERROR_EMPTY_CHANNEL,
	OPLBROADCAST_CHANNEL_ERROR_NOK_ANTENNA,
	OPLBROADCAST_CHANNEL_ERROR_NO_ERROR,
	/*humax 확장 End*/

	OPLBROADCAST_CHANNEL_ERROR_UNDEFINED					= 100,
	/*JLabs 확장 start*/
	OPLBROADCAST_CHANNEL_ERROR_TSMF_LOW					= 400,
	OPLBROADCAST_CHANNEL_ERROR_NO_SERVICE_IN_PAT			= 500,
	OPLBROADCAST_CHANNEL_ERROR_PMT_TIMEOUT					= 501,
	OPLBROADCAST_CHANNEL_ERROR_NO_PAT_IN_TEMP_SVC			= 502,
	OPLBROADCAST_CHANNEL_ERROR_PAT_TIMEOUT					= 503,
	/*JLabs 확장 End*/

	/* Humax 확장 */
	OPLBROADCAST_CHANNEL_ERROR_NOERROR						= 2000,

	OPLBROADCAST_CHANNEL_ERROR_ENDOFCASE
	/* Humax End */
} eOplPlaybackError;

typedef enum {
	OPLBROADCAST_PLAY_STATE_UNREALIZED			= 0,
	OPLBROADCAST_PLAY_STATE_CONNECTING			= 1,
	OPLBROADCAST_PLAY_STATE_PRESENTING			= 2,
	OPLBROADCAST_PLAY_STATE_STOPPED				= 3
} OplBroadcastPlayState_e;

typedef enum
{
	OPLBROADCAST_SESSION_STATE_INITIALIZED		= 0,
	OPLBROADCAST_SESSION_STATE_STARTED,
}OplBroadcastSessionState_e;

typedef enum {
	OPLBROADCAST_EVENT_TYPE_CHANNEL_CHANGE_ERROR		= 0,
	OPLBROADCAST_EVENT_TYPE_PLAYSTATE_CHANGE			= 1,
	OPLBROADCAST_EVENT_TYPE_CHANNEL_CHANGE_SUCCEED		= 2,
	OPLBROADCAST_EVENT_TYPE_FULLSCREEN_CHANGE			= 3,
	OPLBROADCAST_EVENT_TYPE_PARENTAL_RATING_CHANGE		= 4,
	OPLBROADCAST_EVENT_TYPE_PARENTAL_RATING_ERROR		= 5,
	OPLBROADCAST_EVENT_TYPE_PROGRAMMES_CHANGED			= 6,
	OPLBROADCAST_EVENT_TYPE_PLAY_SPEED_CHANGED			= 7,
	OPLBROADCAST_EVENT_TYPE_PLAY_SPEEDS_ARRAY_CHANGED	= 8,
	OPLBROADCAST_EVENT_TYPE_PLAY_POSITION_CHANGED		= 9,
	OPLBROADCAST_EVENT_TYPE_RECORDING_EVENT				= 10,
	OPLBROADCAST_EVENT_TYPE_DRM_RIGHTS_ERROR_EVENT		= 11,
	OPLBROADCAST_EVENT_TYPE_CAS_MESSAGE_EVENT			= 13,
	OPLBROADCAST_EVENT_TYPE_CAS_UI_TRIGGERED			= 14,
	OPLBROADCAST_EVENT_TYPE_CAS_BC_DRM_ERROR_NOTIFY	= 15,
	OPLBROADCAST_EVENT_TYPE_CAS_BC_EMM_AUTO_DISP_MSG_NOTIFY	= 16,
	OPLBROADCAST_EVENT_TYPE_CAS_BC_CA_LINK_MSG_NOTIFY 	= 17,
	OPLBROADCAST_EVENT_TYPE_MAIL_NEW_MEESAGE_EVENT		= 18,
	OPLBROADCAST_EVENT_TYPE_EVENT_RELAY_NOTIFY			= 19,
	OPLBROADCAST_EVENT_TYPE_EWS_NOTIFY					= 20,
	OPLBROADCAST_EVENT_TYPE_BML_START					= 21,
	OPLBROADCAST_EVENT_TYPE_BML_END						= 22,
	OPLBROADCAST_EVENT_TYPE_CAS_BC_BS_CONTROL_START	= 23,
	OPLBROADCAST_EVENT_TYPE_BML_VOD						= 24,
	OPLBROADCAST_EVENT_TYPE_SUPPORTED_PLAY_SPEED_CHANGED	= 25,
	OPLBROADCAST_EVENT_TYPE_TRICK_RESTRICT_MODE_CHANGED	= 26,
	OPLBROADCAST_EVENT_TYPE_SI_RCT_CHANGED				= 27,
	OPLBROADCAST_EVENT_TYPE_NCD_CHANGED				= 28,
	OPLBROADCAST_EVENT_TYPE_REQUEST_PINCODE				= 29,
	OPLBROADCAST_EVENT_TYPE_MHEG_REQUEST_TUNE			= 30,
	OPLBROADCAST_EVENT_TYPE_MHEG_INTERRUPTIBLE			= 31,
	OPLBROADCAST_EVENT_TYPE_TSR_STATE_CHANGED			= 34,
	OPLBROADCAST_EVENT_TYPE_SELECTED_COMPONENT_CHANGE_VIDEO		= 35,
	OPLBROADCAST_EVENT_TYPE_SELECTED_COMPONENT_CHANGE_AUDIO		= 36,
	OPLBROADCAST_EVENT_TYPE_SELECTED_COMPONENT_CHANGE_SUBTITLE	= 37
} eOplBroadcastEventType;

typedef enum {
	/* no license, consumption of the content is blocked. */
	OPLBROADCAST_DRM_RIGHTS_NO_LICENSE		= 0,
	/* invalid license, consumption of the content is blocked. */
	OPLBROADCAST_DRM_RIGHTS_INVALID_LICENSE,
	/* valid license, consumption of the content is unblocked. */
	OPLBROADCAST_DRM_RIGHTS_VALID_LICENSE,
} eOplBroadcastDrmRightsError;

typedef enum {
	OPLBROADCAST_TRICK_MODE_NORESTRICT = 0,
	OPLBROADCAST_TRICK_MODE_NOSKIP_FF2X = 1,
	OPLBROADCAST_TRICK_MODE_NOSKIP_FF4X = 2,
	OPLBROADCAST_TRICK_MODE_NOSKIP_FF8X = 3,
	OPLBROADCAST_TRICK_MODE_NOSKIP_JUMP_FF = 7
} OplBroadcastTrickRestrictMode_e;	/* SES extension */

/******************************************************************
	Typedef
******************************************************************/

typedef void OPL_AutoDispMsg_t;

typedef void (*OplBroadcastListener_t)(void *hBroadcast, eOplBroadcastEventType eEventType);
typedef void (*OplBroadcastCAMessageListener_t)(const void *hBroadcast, const char *pszMessage);

#endif // __OPLVIDEOBROADCASTHANDLEDEF_H__
