obj-y += va_fs_api.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.pal
# Additional include path
