obj-$(CONFIG_PROD_ICORDPRO)			+= xmgr_copyrightcontrol_icordpro.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

