obj-y += hama_main.o
obj-y += hama.o
obj-y += hama_handler.o
obj-y += hama_instance.o
obj-y += hama_sawman.o
obj-y += hama_tool.o
obj-y += hama_debug.o
obj-y += hama_registry.o
obj-y += scenario.o

# Additional include path
ccflags-y += -I../../make/include
