-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = meteringgeneratechallenge

DRM_MODULE_CFLAGS =

SOURCES =                \
	meterview.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
