# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =   \
    real    \

include $(PLAYREADY_DIR)/GNUmakefile.common

