#!/bin/sh

	umount /var/lib/humaxtv
	umount /var/lib/humaxtv_backup
	umount /var/lib/humaxtv_user
	ubidetach -m 5
	ubiformat -y /dev/mtd5
	ubiattach -m 5
	ubimkvol /dev/ubi2 -N dbbackup -s 58MiB
	ubimkvol /dev/ubi2 -N dbdata -s 16MiB
	ubimkvol /dev/ubi2 -N dbuser -s 16MiB	
	ubidetach -m 5
