
obj-y += oapi_output_video.o
obj-y += oapi_output_audio.o
obj-y += oapi_output_hdmi.o
obj-y += oapi_output_panel.o
obj-y += oapi_output_thermal_protection.o

# ---- include path----
ccflags-y += -I$(HLIB_DIR)/include
ccflags-y += -I$(DLIB_DIR)/include
ccflags-y += -I$(OCTO_DIR)/include
ccflags-y += -I$(OCTO_DIR)/api/protocol
ccflags-y += -I$(OCTO_DIR)/main/oxserver/include


