#!/bin/sh

	umount /var/lib/humaxtv
	umount /var/lib/humaxtv_backup
	umount /var/lib/humaxtv_user
	ubidetach -m 6
	ubiformat -y /dev/mtd6
	ubiattach -m 6
	ubimkvol /dev/ubi1 -N dbbackup -s 16MiB
	ubimkvol /dev/ubi1 -N dbdata -s 16MiB
	ubimkvol /dev/ubi1 -N dbuser -s 58MiB	
	ubidetach -m 6
