obj-$(CONFIG_MW_CAS_NAGRA_RCS) += xmgr_cas_na_ppv_rcs_banner.o
obj-$(CONFIG_MW_CAS_NAGRA_RCS) += xmgr_cas_na_ppv_rcs_buyingpopup.o
obj-$(CONFIG_MW_CAS_NAGRA_RCS) += xmgr_cas_na_ppv_rcs_event_detailinfo.o
obj-$(CONFIG_MW_CAS_NAGRA_RCS) += xmgr_cas_na_ppv_rcs_carderror.o
obj-$(CONFIG_MW_CAS_NAGRA_RCS) += xmgr_cas_na_ppv_rcs_ppvinfopopup.o
obj-$(CONFIG_MW_CAS_NAGRA_RCS) += xmgr_cas_na_ppv_rcs_creditpopup.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
ccflags-y += -I$(OCTO_DIR)/oapi/server/include

# Sub-CAS include path

