############################################################
#     Copyright (c) 2003-2012, Broadcom Corporation
#     All Rights Reserved
#     Confidential Property of Broadcom Corporation
#
#  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
#  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
#  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
#
# $brcm_Workfile: bfec.inc $
# $brcm_Revision: Hydra_Software_Devel/1 $
# $brcm_Date: 9/27/12 3:25p $
#
# Module Description:
#
# Revision History:
#
# Created: 09/25/2012 by Michael Phillips
#
# $brcm_Log: /magnum/commonutils/fec/bfec.inc $
# 
# Hydra_Software_Devel/1   9/27/12 3:25p mphillip
# SW3461-274: Merge new FEC module to /main/Hydra_Software_Devel
# 
# Hydra_Software_Devel/SW3461-274/1   9/25/12 3:58p mphillip
# SW3461-274: Initial version.
# 
# 
#
############################################################

#
# Conditional Options for this Makefile
#
# N/A
#

# Define this module
MAGNUM_MODULES += BFEC

BFEC_INCLUDES += $(MAGNUM)/commonutils/fec/include

#
# End of file
#
