/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_bld_decode_vp8_xfrm_0.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 8/17/11 12:03p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Thu Aug 11 21:47:04 2011
 *                 MD5 Checksum         30eb4d41dba6899590ea7664187e6ba5
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7429/rdb/a0/bchp_bld_decode_vp8_xfrm_0.h $
 * 
 * Hydra_Software_Devel/1   8/17/11 12:03p pntruong
 * SW7429-2: Initial version.
 *
 ***************************************************************************/

#ifndef BCHP_BLD_DECODE_VP8_XFRM_0_H__
#define BCHP_BLD_DECODE_VP8_XFRM_0_H__

/***************************************************************************
 *BLD_DECODE_VP8_XFRM_0
 ***************************************************************************/
#define BCHP_BLD_DECODE_VP8_XFRM_0_REG_VP8_IXFM_QUANT_YY 0x00100600 /* VP8 YY Quantization Factor */
#define BCHP_BLD_DECODE_VP8_XFRM_0_REG_VP8_IXFM_QUANT_Y 0x00100604 /* VP8 Y  Quantization Factor */
#define BCHP_BLD_DECODE_VP8_XFRM_0_REG_VP8_IXFM_QUANT_UV 0x00100608 /* VP8 UV Quantization Factor */
#define BCHP_BLD_DECODE_VP8_XFRM_0_REG_VP8_IXFM_END 0x0010060c /* REG_VP8_IXFM_END */

#endif /* #ifndef BCHP_BLD_DECODE_VP8_XFRM_0_H__ */

/* End of File */
