#
obj-y += tmbslHCDP/src/
obj-y += tmbslTDA10025/cfg/
obj-y += tmbslTDA10025/src/
obj-y += drv_channel_tda10025.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/dp10025/
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/dp10025/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/dp10025/tmbslTDA10025/inc

inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260

