
obj-y += om_cas_subcas.o
obj-y += om_cas_mmi.o
obj-y += om_cas_action.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.oapimgr
# Additional include path
ccflags-y += -I$(OCTO_DIR)/oapi/lib
ccflags-y += -I$(OCTO_DIR)/oapi/server
ccflags-y += -I$(OCTO_DIR)/oapi
ccflags-y += -I$(OCTO_DIR)/oapi/protocol
ccflags-y += -I$(OCTO_DIR)/main/oxserver
ccflags-y += -I$(OCTO_TVMANAGER_DIR)/om/include_plugin

