##### anual action Procedures #####
# Only one procedure shall be linked:
obj-y += xmgr_action_si_ntvplus.o

##### End of 'anual action Procedures' #####

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

