obj-y += xmgr_cas_cx_menu.o
# obj-y += xmgr_cas_cx_about.o
# obj-y += xmgr_cas_cx_statuslist.o
# obj-y += xmgr_cas_cx_maturity_rate.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

# Sub-CAS include path
