/**********************************************************************************************
	OCTO 2.0 Global Version Description
	----
	make obama will parse current file, make it to binary and write it to flash for S/W update
	/root/etc/moduleversion.json will be included each module version.
 **********************************************************************************************/

#ifndef	__OCTO20_VERSION_H__
#define	__OCTO20_VERSION_H__

#if	defined(CONFIG_PROD_HDR1000S)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"HDR-1000S"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"UKSFAA"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x000019		//	0.00.23
	#define	SYSTEM_ID						(HCHAR*)"809C.7D00"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"01 AUG 2012"

	#define	SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"
#elif	defined(CONFIG_PROD_HMS1000S)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"HMS-1000S"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"DESFAB"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x010101		//	1.01.00
	#define	SYSTEM_ID						(HCHAR*)"809C.5010"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"15 NOV 2013"

	#define	SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"
#elif	defined(CONFIG_PROD_IR4000HD)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"IR4000HD"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"MESIBE"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x000008		//	0.00.08
	#define	SYSTEM_ID						(HCHAR*)"809C.3040"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"24 JAN 2014"
#elif	defined(CONFIG_PROD_ICORDPRO)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"ICORDPRO"
	#define 	SYSTEM_MODEL_NAME_NEO		(HCHAR*)"ICORDNEO"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"DESNAD"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x01001F		//	1.00.31
	#define	SYSTEM_ID						(HCHAR*)"809C.5020"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"18 MAY 2015"

	#define	SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"
#elif	defined(CONFIG_PROD_HDNEO)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"HD NEO"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"DESNAF"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x010000		//	1.00.00
	#define	SYSTEM_ID						(HCHAR*)"9010.7D54"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"22 MAR 2015"

	#define	SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"
#elif	defined(CONFIG_PROD_HGS1000S)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"HGS-1000S"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"DESNAG"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x005A19		//	0.90.25
	#define	SYSTEM_ID						(HCHAR*)"9010.7D73"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"19 JAN 2016"

	#define	SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"
#elif	defined(CONFIG_PROD_HD9000I)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"HD 9000i"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"RUCNAA"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x00030a		//	0.00.01
	#define	SYSTEM_ID						(HCHAR*)"8050.8700"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"07 Mar 2014"

	#define	SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"
#elif	defined(CONFIG_PROD_HMS1000T)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"HMS-1000T"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"AUTFAC"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x000007		//	0.00.07
	#define	SYSTEM_ID						(HCHAR*)"9010.7D03"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"23 JAN 2014"

//	#define	SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"
#elif	defined(CONFIG_PROD_IHDR6100C)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"IHDR-6100C"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"AAAAAA"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x000000		//	0.00.00
	#define	SYSTEM_ID						(HCHAR*)"0000.0000"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"15 NOV 2013"

//	#define	SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"
#elif	defined(CONFIG_PROD_FVP4000T)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"FVP-4000T"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"UKTFAE"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x010336		//	1.03.54
	#define	SYSTEM_ID						(HCHAR*)"9010.7D31"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"25 MAY 2022"

	//	#define SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"
#elif	defined(CONFIG_PROD_HMX4KBBC)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"HMX-4KBBC"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"BT-POC"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x000014		//	0.00.01
	#define	SYSTEM_ID						(HCHAR*)"0000.0000"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"18 JUL 2014"

//	#define	SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"
#elif	defined(CONFIG_PROD_DIGIMAXT2)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"DIGIMAX T2"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"AAAAAA" // for test (swkim_p) : TODO
	#define	SYSTEM_APP_VERSION				(HUINT32)0x000001		//	0.00.01
	#define	SYSTEM_ID						(HCHAR*)"0000.0000"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"10 JUN 2014"

	//	#define SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"
#elif	defined(CONFIG_PROD_HDFOXIRCONNECT)
	#define SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define SYSTEM_MODEL_NAME				(HCHAR*)"HDFOXIRCONNECT"
	#define SYSTEM_APP_VER_HEAD 			(HCHAR*)"MESIBE"
	#define SYSTEM_APP_VERSION				(HUINT32)0x000001		//	0.00.08
	#define SYSTEM_ID						(HCHAR*)"0000.0000"
	#define SYSTEM_UPDATE_DATE				(HCHAR*)"12 JUNE 2014"

#elif	defined(CONFIG_PROD_YSR2000)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"YSR-2000"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"DKCXAB"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x010005		//	0.00.03
	#define	SYSTEM_ID						(HCHAR*)"9010.7D33"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"3 MAR 2016"

#elif	defined(CONFIG_PROD_YS1000)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"YS-1000"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"DKCXAA"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x010005		//	0.00.03
	#define	SYSTEM_ID						(HCHAR*)"9010.7D32"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"3 MAR 2016"

#elif	defined(CONFIG_PROD_CDIG2000C)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"CDIG-2000C/R"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"SECCAC"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x000020
	#define	SYSTEM_ID						(HCHAR*)"9010.7D50"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"11 SEP 2015"

#elif	defined(CONFIG_PROD_ROCKYPOM) || defined(CONFIG_PROD_ROCKYWPOM)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"Rokey-PoM"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"SECCAC"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x000001
	#define	SYSTEM_ID						(HCHAR*)"9010.7D50"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"22 FEB 2015"

#elif	defined(CONFIG_PROD_HMSLITE)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"HMS-LITE"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"DESFAB"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x000001		//	0.00.01
	#define	SYSTEM_ID						(HCHAR*)"9010.7D51"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"21 NOV 2014"

	#define	SYSTEM_CIPLUS_VERSION			(HCHAR*)"1.00.00\0"

#elif	defined(CONFIG_PROD_HA7100S)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"HA7-100S"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"SASNAA"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x000004		//	0.00.04
	#define	SYSTEM_ID						(HCHAR*)"9010.7D7E"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"23 FEB 2016"

#elif	defined(CONFIG_PROD_M1)
	#define	SYSTEM_MODEL_NAME_PREFIX		(HCHAR*)""
	#define	SYSTEM_MODEL_NAME				(HCHAR*)"M1/ME"
	#define	SYSTEM_APP_VER_HEAD				(HCHAR*)"MESIDA"
	#define	SYSTEM_APP_VERSION				(HUINT32)0x000001		//	0.00.01
	#define	SYSTEM_ID						(HCHAR*)"9010.7D80"
	#define	SYSTEM_UPDATE_DATE				(HCHAR*)"23 OCT 2015"

#else
	#error	"Model name is not defined!!!"
#endif

#endif

