obj-y += va_pi_api.o
#obj-y += va_pi_adapt.o
#obj-y += va_pi_mw_adapt.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
