/***************************************************************************
*     (c)2008-2010 Broadcom Corporation
*  
*  This program is the proprietary software of Broadcom Corporation and/or its licensors,
*  and may only be used, duplicated, modified or distributed pursuant to the terms and
*  conditions of a separate, written license agreement executed between you and Broadcom
*  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
*  no license (express or implied), right to use, or waiver of any kind with respect to the
*  Software, and Broadcom expressly reserves all rights in and to the Software and all
*  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
*  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
*  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.  
*   
*  Except as expressly set forth in the Authorized License,
*   
*  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
*  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
*  and to use this information only in connection with your use of Broadcom integrated circuit products.
*   
*  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS" 
*  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR 
*  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO 
*  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES 
*  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, 
*  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION 
*  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF 
*  USE OR PERFORMANCE OF THE SOFTWARE.
*  
*  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS 
*  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR 
*  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR 
*  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF 
*  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT 
*  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE 
*  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF 
*  ANY LIMITED REMEDY.
 *
 * $brcm_Workfile: nexus_gpio_table.c $
 * $brcm_Revision: 2 $
 * $brcm_Date: 12/7/10 12:07p $
 * 
 * Module Description:
 * 
 * Revision History:
 * 
 * $brcm_Log: /nexus/modules/gpio/7468/src/nexus_gpio_table.c $
 * 
 * 2   12/7/10 12:07p randyjew
 * SW7408-146: Adding Nexus gpio modifications to 7468
 * 
 * 1   12/1/09 1:46p randyjew
 * SW7468-6: Add 7468 support
 * 
 * 1   12/1/09 1:39p randyjew
 * SW7468-6: Add 7468 support
 * 
* 
* API Description:
*   API name: Gpio
*    Specific APIs related to Gpio Control.
*
* Revision History:
*
***************************************************************************/
#include "nexus_gpio_module.h"
#include "bchp_sun_top_ctrl.h"
#include "bchp_gio.h"
#include "priv/nexus_core.h"

BDBG_MODULE(nexus_gpio_table);

typedef struct NEXUS_GpioTable
{
    uint32_t addr;
    unsigned mask;
    unsigned shift;
} NEXUS_GpioTable;

NEXUS_GpioTable g_gpioTable[NEXUS_NUM_GPIO_PINS] = {
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_00_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_01_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_02_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_03_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_04_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_05_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_06_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_06_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_07_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_07_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_08_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_08_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_09_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_09_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_10_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_10_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_11_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_11_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_12_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_12_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_13_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_13_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_14_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_14_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_15_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_15_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_16_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_16_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_17_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_17_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_18_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_18_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_19_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_19_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_20_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_20_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_21_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_21_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_22_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_22_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_23_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_23_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_24_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_24_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_25_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_25_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_26_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_26_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_27_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_27_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_28_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_28_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_29_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_29_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_30_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_30_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_31_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_31_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_32_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_32_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_33_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_33_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_34_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_34_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_35_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_35_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_36_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_36_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_37_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_37_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_38_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_38_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_39_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_39_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_40_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_40_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_41_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_41_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_42_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_42_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_43_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_43_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_44_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_44_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_45_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_45_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_46_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_46_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_47_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_47_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_48_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_48_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_49_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_49_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_50_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_50_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_51_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_51_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_52_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_52_SHIFT}
  
};

NEXUS_GpioTable g_sgpioTable[NEXUS_NUM_SGPIO_PINS] = {
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_sgpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_sgpio_00_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_sgpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_sgpio_01_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_sgpio_02_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_sgpio_03_SHIFT}
};

/* These functions must be implemented per-chip */
NEXUS_Error NEXUS_Gpio_P_GetPinMux(NEXUS_GpioType type, unsigned pin, uint32_t *pAddr, uint32_t *pMask, unsigned *pShift )
{
    NEXUS_GpioTable *pEntry=NULL;
    if ( type == NEXUS_GpioType_eSpecial ) {
        if ( pin >= NEXUS_NUM_SGPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        pEntry = g_sgpioTable+pin;
    }
    else if ( type == NEXUS_GpioType_eStandard ) {
        if ( pin >= NEXUS_NUM_GPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        pEntry = g_gpioTable+pin;
    }
    else {
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }
    *pAddr = pEntry->addr;
    *pMask = pEntry->mask;
    *pShift = pEntry->shift;
    return 0;
}

NEXUS_Error NEXUS_Gpio_P_CheckPinmux(NEXUS_GpioType type, unsigned pin)
{
    uint32_t addr, mask, shift, val;
    NEXUS_Error rc;
    
    rc = NEXUS_Gpio_P_GetPinMux(type, pin, &addr, &mask, &shift);
    if (rc) return BERR_TRACE(rc);

    val = BREG_Read32(g_pCoreHandles->reg, addr);
    /* this code assumes a pinmux value of 0 is GPIO */
    if ( val & mask ) {
        /* Pin is not configured as GPIO */
        BDBG_ERR(("Pin mux register for %s %u is not properly configured - value %u should be 0",
                  (type == NEXUS_GpioType_eSpecial)?"sgpio":"gpio", pin, val>>shift));
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }

    return BERR_SUCCESS;
}



NEXUS_Error NEXUS_Gpio_P_GetPinData(NEXUS_GpioType type, unsigned pin, uint32_t *pAddress, uint32_t *pShift)
{

    if ( type == NEXUS_GpioType_eSpecial )
    {
        if ( pin >= NEXUS_NUM_SGPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        else
        {
            /* SGPIO Pins 3..0 are in ODEN_EXT */
            *pAddress = BCHP_GIO_ODEN_EXT;
            *pShift = pin;
        }
    }
    else if( type == NEXUS_GpioType_eStandard )
    {
        if ( pin < 32 )
        {
            /* GPIO Pins 31..0 are in ODEN_LO */
            *pAddress = BCHP_GIO_ODEN_LO;
            *pShift = pin;
        }
        else if ( pin < 53 )
        {
            /* GPIO Pins 52..32 are in ODEN_HI */
            *pAddress = BCHP_GIO_ODEN_HI;
            *pShift = pin-32;
        }
        else
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
    }
    else {
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }

    return BERR_SUCCESS;
}

