gOipfEmul.createAVComponentCollection([{
		"componentTag": 1,
		"pid": 1,
		"type": 1,
		"encoding": "",
		"encrypted": true,
		"has_aspectRatio": true,
		"aspectRatio": 1,
		"language": "eng",
		"audioDescription": true,
		"audioChannels": 1,
		"subType": 2,
		"language2" : "swe"
	},{
		"componentTag": 2,
		"pid": 2,
		"type": 1,
		"encoding": "",
		"encrypted": true,
		"has_aspectRatio": true,
		"aspectRatio": 1,
		"language": "eng",
		"audioDescription": true,
		"audioChannels": 1,
		"subType": 6,
		"language2" : " "
	},{
		"componentTag": 3,
		"pid": 3,
		"type": 1,
		"encoding": "",
		"encrypted": true,
		"has_aspectRatio": true,
		"aspectRatio": 1,
		"language": "wel",
		"audioDescription": true,
		"audioChannels": 1,
        "subType": 3,
        "language2" : " "
	},{
		"componentTag": 4,
		"pid": 4,
		"type": 1,
		"encoding": "",
		"encrypted": true,
		"has_aspectRatio": true,
		"aspectRatio": 1,
		"language": "wel",
		"audioDescription": true,
		"audioChannels": 1,
        "subType": 3,
        "language2" : " "
	},{
		"componentTag": 5,
		"pid": 5,
		"type": 1,
		"encoding": "",
		"encrypted": true,
		"has_aspectRatio": true,
		"aspectRatio": 1,
		"language": "gla",
		"audioDescription": true,
		"audioChannels": 1,
        "subType": 3,
        "language2" : " "
	},{
		"componentTag": 6,
		"pid": 6,
		"type": 1,
		"encoding": "",
		"encrypted": true,
		"has_aspectRatio": true,
		"aspectRatio": 1,
		"language": "gle",
		"audioDescription": true,
		"audioChannels": 1,
        "subType": 3,
        "language2" : " "
	},{
		"componentTag": 7,
		"pid": 7,
		"type": 1,
		"encoding": "",
		"encrypted": true,
		"has_aspectRatio": true,
		"aspectRatio": 1,
		"language": "gle",
		"audioDescription": true,
		"audioChannels": 1,
        "subType": 3,
        "language2" : " "
	},{
		"componentTag": 8,
		"pid": 7,
		"type": 0,
		"encoding": "euc-kr",
		"encrypted": true,
		"has_aspectRatio": true,
		"aspectRatio": 1,
		"audioDescription": true,
		"audioChannels": 1,
        "subType": 3,
        "language2" : " "
	},
	{
		"componentTag": 9,
		"pid": 8,
		"type": 2,
		"encoding": "",
		"encrypted": true,
		"has_aspectRatio": true,
		"aspectRatio": 1,
		"language": "eng",
		"audioDescription": true,
		"audioChannels": 1,
        "subType": 201, // DVB
        "language2" : " "
	},
    {
        "componentTag": 9,
        "pid": 8,
        "type": 2,
        "encoding": "",
        "encrypted": true,
        "has_aspectRatio": true,
        "aspectRatio": 1,
        "language": "ger",
        "audioDescription": true,
        "audioChannels": 1,
        "subType": 202, // EBU
        "language2" : " "
    },
	{
		"componentTag": 9,
		"pid": 9,
		"type": 3,
		"encoding": "",
		"encrypted": true,
		"has_aspectRatio": true,
		"aspectRatio": 1,
		"language": "kor",
		"audioDescription": true,
		"audioChannels": 1,
        "subType": 3,
        "language2" : " "
	},
	{
		"componentTag": 9,
		"pid": 10,
		"type": 4,
		"encoding": "",
		"encrypted": true,
		"has_aspectRatio": true,
		"aspectRatio": 1,
		"language": "eng",
		"audioDescription": true,
		"audioChannels": 1,
        "subType": 3,
        "language2" : " "
	}
]);

