gOipfEmul.processRecList( {
    "meta" : {
        "target" : "reclist",
        "request_id" : 159,
        "accesscode" : 95910368,
        "property" : {
            "reclist" : {
                "cur cmd" : "do_get",
                "sync" : false,
                "scan url" : "/mnt/hd2/My Video/",
                "scaned rec items" : [{
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                },{
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                },{
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                },{
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                },{
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                },{
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                },{
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                },{
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                },{
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                },{
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                },          {
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                }, {
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1351779337,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                }, {
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1452779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                }, {
                    "url" : "HPVR://mnt/hd3/My Video/2The Weakest Link_20120509_144.hmt",
                    "display name" : "TEST 1",
                    "thumbnail" : "",
                    "start time" : 1352779237,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_incompleted", //"rec_sts_start",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 7222,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs": ['WWW.CHANNEL4.COM/60050'],
                    "copyControl" : "no further copy"
                }, {
                    "url" : "HPVR://mnt/hd3/My Video/2.1TESTFILE_20120501_2244.hmt",
                    "display name" : "TEST 2",
                    "thumbnail" : "",
                    "start time" : 1351759137,
                    "duration" : 60,
                    "org duration" : 0,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 25,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : true,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 1204,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/2.1TESTFILE_20120101_2245.hmt",
                    "display name" : "TEST 3",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/3.png",
                    "start time" : 1357290712,
                    "duration" : 60,
                    "org duration" : 0,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_hddfull",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 25,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : true,
                    "blocked" : true,
                    "svc name" : "",
                    "svc type" : "not supported",
                    "svc UId" : 1111,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy prohibited"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/BBC HD Preview_20120511_1138.hmt",
                    "display name" : "BBC HD Preview",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/0.png",
                    "start time" : 1352743441,
                    "duration" : 219,
                    "org duration" : 36000,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : true,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : true,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "BBC HD",
                    "svc type" : "tv",
                    "svc UId" : 273,
                    "svc video type" : "hd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "programmeID" : "dvb://2.802.1b1c;46535;;273",
                    "event" : {
                        "starttime" : 1336712400,
                        "duration" : 36000,
                        "contentnibble" : 1917845504,
                        "usernibble" : 1701990400,
                        "text" : "Preview of upcoming programmes in HD from the BBC: live sport, national events, landmark drama, world-class documentaries and more. The BBC as you have never experienced it before. [S]",
                        "seriesid" : ""
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy prohibited"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Beyond Belief_ Fact or Fiction_20120510_1612.hmt",
                    "display name" : "Beyond Belief: Fact or Fiction - series A/1",
                    "thumbnail" : "",
                    "start time" : 1352728732,
                    "duration" : 30,
                    "org duration" : 3600,
                    "status" : "rec_sts_incompleted",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : true,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "CBS Reality",
                    "svc type" : "tv",
                    "svc UId" : 1111,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336662000,
                        "duration" : 3600,
                        "contentnibble" : 1850278016,
                        "usernibble" : 544098560,
                        "text" : "In this episode, the spectre of a notorious gunslinger haunts a modern-day police officer, and a mysterious drifter disappears after he helps a couple whose marriage is in trouble.",
                        "seriesid" : "WWW.CHELLOZONE.COM/2519"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Beyond Belief_ Fact or Fiction_20120510_1700.hmt",
                    "display name" : "Beyond Belief: Fact or Fiction - series D/1",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/1.png",
                    "start time" : 1352901549,
                    "duration" : 289,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : true,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "CBS Reality",
                    "svc type" : "tv",
                    "svc UId" : 1111,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336665600,
                        "duration" : 3600,
                        "contentnibble" : 128,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : "WWW.CHELLOZONE.CO.UK/2519"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/CSI_20120510_1538.hmt",
                    "display name" : "CSI - series B/1",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/2.png",
                    "start time" : 1352814640,
                    "duration" : 39,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : true,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "CBS Drama",
                    "svc type" : "tv",
                    "svc UId" : 284,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336658400,
                        "duration" : 3600,
                        "contentnibble" : 1850277936,
                        "usernibble" : 1986939136,
                        "text" : "Investigators from the LAPD unravel clues to solve brutal murder cases. A woman is kidnapped while shopping. Grissom finds graffiti that claims five are already dead. S1, Ep11/23",
                        "seriesid" : "WWW.CHELLOZONE.COM/23234"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/CSI_20120511_1159.hmt",
                    "display name" : "CSI - series B/2",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/3.png",
                    "start time" : 1352987536,
                    "duration" : 4489,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded", //"rec_sts_recording",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : true,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "CBS Drama",
                    "svc type" : "tv",
                    "svc UId" : 284,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336737600,
                        "duration" : 3600,
                        "contentnibble" : 1816330288,
                        "usernibble" : 1634484992,
                        "text" : "Classic US drama about the Ewing family, who thrive in the oil and cattle-ranching industries. JR realises his mother may be in grave danger when he snoops into someone's past. S6, Ep160",
                        "seriesid" : "WWW.CHELLOZONE.COM/23234"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Lift Every Voice_20120510_1615.hmt",
                    "display name" : "Lift Every Voice",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/4.png",
                    "start time" : 1351865715,
                    "duration" : 379,
                    "org duration" : 1800,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : false,
                    "last view time" : 20,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : true,
                    "blocked" : false,
                    "svc name" : "BET+1",
                    "svc type" : "tv",
                    "svc UId" : 273,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336662000,
                        "duration" : 1800,
                        "contentnibble" : 1750335584,
                        "usernibble" : 1768444928,
                        "text" : "This uplifting contemporary show features moving interviews and videos with artists that are passionate about their ministries and their craft.",
                        "seriesid" : "WWW.BET.COM/780173"
                    },
                    "discId" : "5678",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/New Cowboy Builders_20120510_1535.hmt",
                    "display name" : "New Cowboy Builders",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/5.png",
                    "start time" : 1336660521,
                    "duration" : 79,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : false,
                    "last view time" : 48,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : true,
                    "blocked" : false,
                    "svc name" : "5* +1",
                    "svc type" : "tv",
                    "svc UId" : 270,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336658400,
                        "duration" : 3600,
                        "contentnibble" : 1866727472,
                        "usernibble" : 1836008448,
                        "text" : "Dom Littlewood and Melinda Messenger track down terrible tradesmen. The duo take on a builder who seems to be making a habit of leaving people's homes half finished (6/9). [S]",
                        "seriesid" : "WWW.CHANNEL5.COM/RASI"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Paramedics_20120510_1550.hmt",
                    "display name" : "Paramedics",
                    "thumbnail" : "",
                    "start time" : 1336661408,
                    "duration" : 30,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "CBS Reality",
                    "svc type" : "tv",
                    "svc UId" : 261,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336658400,
                        "duration" : 3600,
                        "contentnibble" : 1917255808,
                        "usernibble" : 1769096960,
                        "text" : "Gripping real life series featuring medical emergencies. A man suffers a horrendous head wound after falling 150 feet down an embankment. Meanwhile, a woman's legs are crushed in a head on collision.",
                        "seriesid" : ""
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Spotlight_20120510_1606.hmt",
                    "display name" : "Spotlight",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/6.png",
                    "start time" : 1336662397,
                    "duration" : 1800000,
                    "org duration" : 1800000,
                    "status" : "rec_sts_incompleted",
                    "end reason" : "rec_end_drm",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "BET",
                    "svc type" : "tv",
                    "svc UId" : 243,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336662000,
                        "duration" : 180000,
                        "contentnibble" : 1766719520,
                        "usernibble" : 1734954496,
                        "text" : "Nigeria's biggest artists from multiple genres of Hip Hop, Afro-Beat and R&B.",
                        "seriesid" : "WWW.BET.COM/71282"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Star Trek_ The Next Generation_20120510_2000.hmt",
                    "display name" : "Star Trek: The Next Generation",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/7.png",
                    "start time" : 1336676418,
                    "duration" : 0,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded", //"rec_sts_start",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "CBS Action",
                    "svc type" : "tv",
                    "svc UId" : 240,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                },{
                    "url" : "HPVR://mnt/hd2/My Video/Weatherview.hmt",
                    "display name" : "Weatherview",
                    "thumbnail" : "",
                    "start time" : 1348556401,
                    "duration" : 60,
                    "org duration" : 0,
                    "status" : "rec_sts_recorded", //"rec_sts_start",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "BBC 1 London",
                    "svc type" : "not supported",
                    "svc UId" : 238,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/David Walliams Big Swim.hmt",
                    "display name" : "David Walliams Big Swim",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/8.png",
                    "start time" : 1336732717,
                    "duration" : 219,
                    "org duration" : 36000,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : true,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "BBC 1 London",
                    "svc type" : "tv",
                    "svc UId" : 238,
                    "svc video type" : "hd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336712400,
                        "duration" : 36000,
                        "contentnibble" : 1917845504,
                        "usernibble" : 1701990400,
                        "text" : "Preview of upcoming programmes in HD from the BBC: live sport, national events, landmark drama, world-class documentaries and more. The BBC as you have never experienced it before. [S]",
                        "seriesid" : ""
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Sport Relief 2012.hmt",
                    "display name" : "Sport Relief 2012 - series D/2",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/9.png",
                    "start time" : 1353074384,
                    "duration" : 30,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : true,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "CBS Reality",
                    "svc type" : "tv",
                    "svc UId" : 1111,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336662000,
                        "duration" : 3600,
                        "contentnibble" : 1850278016,
                        "usernibble" : 544098560,
                        "text" : "In this episode, the spectre of a notorious gunslinger haunts a modern-day police officer, and a mysterious drifter disappears after he helps a couple whose marriage is in trouble.",
                        "seriesid" : "WWW.CHELLOZONE.COM/2519"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/BBC London News.hmt",
                    "display name" : "BBC London News - series A/2",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/0.png",
                    "start time" : 1353333687,
                    "duration" : 289,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : true,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "CBS Reality",
                    "svc type" : "tv",
                    "svc UId" : 1111,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336665600,
                        "duration" : 3600,
                        "contentnibble" : 128,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : "WWW.CHELLOZONE.CO.UK/2519"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Prank Patrol Down Under.hmt",
                    "display name" : "Prank Patrol Down Under",
                    "thumbnail" : "",
                    "start time" : 1348556402,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_recorded", //"rec_sts_start",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "England",
                    "svc type" : "not supported",
                    "svc UId" : 240,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Pixelface.hmt",
                    "display name" : "Pixelface",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/1.png",
                    "start time" : 1336732717,
                    "duration" : 219,
                    "org duration" : 36000,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : true,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "England",
                    "svc type" : "tv",
                    "svc UId" : 240,
                    "svc video type" : "hd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336712400,
                        "duration" : 36000,
                        "contentnibble" : 1917845504,
                        "usernibble" : 1701990400,
                        "text" : "Preview of upcoming programmes in HD from the BBC: live sport, national events, landmark drama, world-class documentaries and more. The BBC as you have never experienced it before. [S]",
                        "seriesid" : ""
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "no further copy"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/The Scooby-Doo Show.hmt",
                    "display name" : "The Scooby-Doo Show - series A/3",
                    "thumbnail" : "",
                    "start time" : 1353506511,
                    "duration" : 30,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : true,
                    "last view time" : 15,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : true,
                    "blocked" : false,
                    "svc name" : "CBS Reality",
                    "svc type" : "tv",
                    "svc UId" : 1111,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336662000,
                        "duration" : 3600,
                        "contentnibble" : 1850278016,
                        "usernibble" : 544098560,
                        "text" : "In this episode, the spectre of a notorious gunslinger haunts a modern-day police officer, and a mysterious drifter disappears after he helps a couple whose marriage is in trouble.",
                        "seriesid" : "WWW.CHELLOZONE.COM/2519"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Dennis & Gnasher.hmt",
                    "display name" : "Dennis & Gnasher - series D/3",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/2.png",
                    "start time" : 1353679337,
                    "duration" : 289,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : true,
                    "last view time" : 5,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : true,
                    "blocked" : true,
                    "svc name" : "CBS Reality",
                    "svc type" : "tv",
                    "svc UId" : 1111,
                    "svc video type" : "sd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336665600,
                        "duration" : 3600,
                        "contentnibble" : 128,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : "WWW.CHELLOZONE.CO.UK/2519"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Dennis & Gnasher.hmt",
                    "display name" : "Dennis & Gnasher - series D/4",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/3.png",
                    "start time" : 1353689324,
                    "duration" : 289,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : true,
                    "last view time" : 5,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : true,
                    "blocked" : true,
                    "svc name" : "ITV1 Central W",
                    "svc type" : "not supported",
                    "svc UId" : 237,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336665600,
                        "duration" : 3600,
                        "contentnibble" : 128,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : "WWW.CHELLOZONE.CO.UK/2519"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Dennis & Gnasher.hmt",
                    "display name" : "Dennis & Gnasher - series D/5",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/4.png",
                    "start time" : 1353691624,
                    "duration" : 289,
                    "org duration" : 3600,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : true,
                    "last view time" : 5,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : true,
                    "blocked" : true,
                    "svc name" : "ITV1 Central W",
                    "svc type" : "not supported",
                    "svc UId" : 237,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336665600,
                        "duration" : 3600,
                        "contentnibble" : 128,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : "WWW.CHELLOZONE.CO.UK/2519"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Almost Naked Animals.hmt",
                    "display name" : "Almost Naked Animals",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/3.png",
                    "start time" : 1348556405,
                    "duration" : 0,
                    "org duration" : 0,
                    "status" : "rec_sts_recorded", //"rec_sts_start",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : false,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : true,
                    "svc name" : "ITV1 Central W",
                    "svc type" : "not supported",
                    "svc UId" : 237,
                    "svc video type" : "all",
                    "svc cas type" : "not supported",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 0,
                        "duration" : 0,
                        "contentnibble" : 0,
                        "usernibble" : 0,
                        "text" : "",
                        "seriesid" : ""
                    },
                    "locked" : true,
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Hannah Montana.hmt",
                    "display name" : "Hannah Montana",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/4.png",
                    "start time" : 1348560001,
                    "duration" : 219,
                    "org duration" : 36000,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : true,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : false,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "ITV1 Central W",
                    "svc type" : "tv",
                    "svc UId" : 237,
                    "svc video type" : "hd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336712400,
                        "duration" : 36000,
                        "contentnibble" : 1917845504,
                        "usernibble" : 1701990400,
                        "text" : "Preview of upcoming programmes in HD from the BBC: live sport, national events, landmark drama, world-class documentaries and more. The BBC as you have never experienced it before. [S]",
                        "seriesid" : ""
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Die magsichen Zahnfeen_20121111_1830.hjm",
                    "display name" : "Die magsichen Zahnfeen - series C/1",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/5.png",
                    "start time" : 1353161032,
                    "duration" : 219,
                    "org duration" : 36000,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : true,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : true,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "ITV1 Central W",
                    "svc type" : "tv",
                    "svc UId" : 237,
                    "svc video type" : "hd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336712400,
                        "duration" : 36000,
                        "contentnibble" : 1917845504,
                        "usernibble" : 1701990400,
                        "text" : "Preview of upcoming programmes in HD from the BBC: live sport, national events, landmark drama, world-class documentaries and more. The BBC as you have never experienced it before. [S]",
                        "seriesid" : "77"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Hannah Montana1.hmt",
                    "display name" : "Geschichten aus der Gruft - series C/2",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/6.png",
                    "start time" : 1353247614,
                    "duration" : 219,
                    "org duration" : 36000,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : true,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : true,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "ITV1 Central W",
                    "svc type" : "tv",
                    "svc UId" : 237,
                    "svc video type" : "hd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336712400,
                        "duration" : 36000,
                        "contentnibble" : 1917845504,
                        "usernibble" : 1701990400,
                        "text" : "Preview of upcoming programmes in HD from the BBC: live sport, national events, landmark drama, world-class documentaries and more. The BBC as you have never experienced it before. [S]",
                        "seriesid" : "77"
                    },
                    "discId" : "1234",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Good Night, and Good Luck - Der Fall McCarthy_20121111_0044.hjm",
                    "display name" : "ABC - series Z/1",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/7.png",
                    "start time" : 1352655050,
                    "duration" : 219,
                    "org duration" : 36000,
                    "status" : "rec_sts_recorded",
                    "end reason" : "rec_end_nofail",
                    "scrambled" : true,
                    "encrypted" : false,
                    "eventbased" : false,
                    "seriesrec" : true,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "ITV1 Central W",
                    "svc type" : "tv",
                    "svc UId" : 237,
                    "svc video type" : "hd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336712400,
                        "duration" : 36000,
                        "contentnibble" : 1917845504,
                        "usernibble" : 1701990400,
                        "text" : "Preview of upcoming programmes in HD from the BBC: live sport, national events, landmark drama, world-class documentaries and more. The BBC as you have never experienced it before. [S]",
                        "seriesid" : "333"
                    },
                    "discId" : "5678",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }, {
                    "url" : "HPVR://mnt/hd2/My Video/Good Night, and Good Luck - Der Fall McCarthy_20121111_0027.hjm",
                    "display name" : "ABC - series Z/2",
                    "thumbnail" : "images/test/thum/ibc_temp/scheduleView/8.png",
                    "start time" : 1352741434,
                    "duration" : 219,
                    "org duration" : 36000,
                    "status" : "rec_sts_incompleted",
                    "end reason" : "rec_end_nohdd",
                    "scrambled" : true,
                    "encrypted" : false,
                    "eventbased" : true,
                    "seriesrec" : true,
                    "last view time" : 0,
                    "userlock" : false,
                    "autodeleted" : false,
                    "played" : false,
                    "blocked" : false,
                    "svc name" : "ITV1 Central W",
                    "svc type" : "tv",
                    "svc UId" : 237,
                    "svc video type" : "hd",
                    "svc cas type" : "fta",
                    "numofbookmark" : 0,
                    "event" : {
                        "starttime" : 1336712400,
                        "duration" : 36000,
                        "contentnibble" : 1917845504,
                        "usernibble" : 1701990400,
                        "text" : "Preview of upcoming programmes in HD from the BBC: live sport, national events, landmark drama, world-class documentaries and more. The BBC as you have never experienced it before. [S]",
                        "seriesid" : "333"
                    },
                    "discId" : "5678",
                    "groupCRIDs" : [],
                    "copyControl" : "copy ok"
                }],
                "request fail items" : [{
                    "url" : "HPVR://mnt/hd2/Tsr/2.hmt"
                }],
                "cmd run" : 0,
                "cmd done" : 1,
                "number of scaned items" : 11,
                "number of requested items" : 1,
                "number of request done items" : 1
            }
        }
    }
});
