#!/bin/sh

	umount /var/lib/humaxtv
	umount /var/lib/humaxtv_backup
	umount /var/lib/humaxtv_user
	umount /var/lib/humaxtv_data
	umount /var/lib/humaxtv_ext2	
	ubidetach -m 4
	ubiformat -y /dev/mtd4
	ubiattach -m 4
	ubimkvol /dev/ubi1 -N dbbackup -s 16MiB
	ubimkvol /dev/ubi1 -N dbdata -s 16MiB
	ubimkvol /dev/ubi1 -N dbuser -s 58MiB
	ubimkvol /dev/ubi1 -N dbuserext	-s 115MiB	
	ubimkvol /dev/ubi1 -N dbuserext2 -s 115MiB	
	ubidetach -m 4
