/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 
 * Tue Mar 31 22:54:36 2009
 */
#define AUTOCONF_INCLUDED
#define CONFIG_RCU_KEY_GREEN 0
#define CONFIG_RCU_KEY_PAUSE 0
#define CONFIG_RCU_KEY_RIGHT 0
#define CONFIG_RCU_KEY_VOLUP 0
#define CONFIG_RCU_KEY_OK 0
#define CONFIG_SW_VERSION "00.01"
#define CONFIG_RCU_KEY_UP 0
#define CONFIG_LOADER_VERSION "00.01"
#define CONFIG_SMARTCARD_SHEET_POSITION 1
#define CONFIG_RCU_KEY_CHDOWN 0
#define CONFIG_RCU_KEY_RED 0
#define CONFIG_RCU_KEY_YELLOW 0
#define CONFIG_TOTAL_SHEET_NUMBER 2
#define CONFIG_SMARTCARD_INPUT 1
#define CONFIG_PRODUCT_NAME "Kraken"
#define CONFIG_RCU_KEY_BACK 0
#define CONFIG_RCU_KEY_STANDBY 0
#define CONFIG_SMARTCARD_ENABLE 1
#define CONFIG_RCU_KEY_TVRADIO 0
#define CONFIG_RCU_KEY_VFORMAT 0
#define CONFIG_RCU_KEY_BLUE 0
#define CONFIG_RCU_KEY_VOLDOWN 0
#define CONFIG_RCU_KEY_LEFT 0
#define CONFIG_RCU_KEY_INFO 0
#define CONFIG_RCU_KEY_0 0
#define CONFIG_RCU_KEY_CHUP 0
#define CONFIG_RCU_KEY_1 0
#define CONFIG_RCU_KEY_2 0
#define CONFIG_RCU_KEY_3 0
#define CONFIG_RCU_KEY_4 0
#define CONFIG_RCU_KEY_5 0
#define CONFIG_RCU_KEY_MENU 0
#define CONFIG_RCU_KEY_6 0
#define CONFIG_RCU_KEY_7 0
#define CONFIG_RCU_KEY_8 0
#define CONFIG_RCU_KEY_DOWN 0
#define CONFIG_RCU_KEY_9 0
#define CONFIG_RCU_KEY_EXIT 0
#define CONFIG_RCU_KEY_MUTE 0
#define CONFIG_RCU_KEY_LIST 0
#define CONFIG_UNAME_RELEASE "2.6.18-92.el5xen"
#define CONFIG_TV_STANDARD_OUTPUT_PAL 1
#define CONFIG_SMARTCARD_CELL_POSITION 1
#define CONFIG_RCU_KEY_BMAIL 0
#define CONFIG_RCU_KEY_GUIDE 0
