obj-y	+= base/
obj-y	+= models/

obj-y	+= pdb_param.o
obj-y	+= xdb_param.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xdb

# Additional include path
ccflags-y += -I$(OCTO_DB_DIR)/param/local_include

