# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =  \
        pr \

include $(PLAYREADY_DIR)/GNUmakefile.common

