#!/bin/sh

#mount pseudo terminal slave
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts -ogid=$TTYGRP,mode=$TTYMODE

if [ -e /usr/sbin/telnetd ] ; then
     echo "Starting telnet daemon"
     /usr/sbin/telnetd -l /bin/sh &
fi


eth1_1_ipaddr=$(echo `ifconfig eth1:1 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`)
echo eth1_1_ipaddr=$eth1_1_ipaddr
if [ "x$eth1_1_ipaddr" != "x" ]; then
     echo "eth1:1 already has ipaddr: $eth1_1_ipaddr"
else
     ifconfig eth1:1 169.254.119.5 netmask 255.255.255.0 up
     echo "eth1:1 has ipaddr: 169.254.119.5"
fi

#eth1_2_ipaddr=$(echo `ifconfig eth1:2 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`)
#echo eth1_2_ipaddr=$eth1_2_ipaddr
#if [ "x$eth1_2_ipaddr" != "x" ]; then
#     echo "eth1:2 already has ipaddr: $eth1_2_ipaddr"
#else
#     ifconfig eth1:2 192.168.1.100 netmask 255.255.255.0 up
#     echo "eth1:2 has ipaddr: 192.168.1.100"
#fi
