/***************************************************************************
 *     Copyright (c) 1999-2007, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_avd_intr2_1.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 7/23/07 1:33p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Mon Jul 23 11:59:13 2007
 *                 MD5 Checksum         61f9c4d8dcdcd06017506dddbf23f434
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008004
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7400/rdb/d0/bchp_avd_intr2_1.h $
 * 
 * Hydra_Software_Devel/1   7/23/07 1:33p maivu
 * PR 32842: Initial revision
 *
 ***************************************************************************/

#ifndef BCHP_AVD_INTR2_1_H__
#define BCHP_AVD_INTR2_1_H__

/***************************************************************************
 *AVD_INTR2_1
 ***************************************************************************/
#define BCHP_AVD_INTR2_1_CPU_STATUS              0x00f00000 /* CPU interrupt Status Register */
#define BCHP_AVD_INTR2_1_CPU_SET                 0x00f00004 /* CPU interrupt Set Register */
#define BCHP_AVD_INTR2_1_CPU_CLEAR               0x00f00008 /* CPU interrupt Clear Register */
#define BCHP_AVD_INTR2_1_CPU_MASK_STATUS         0x00f0000c /* CPU interrupt Mask Status Register */
#define BCHP_AVD_INTR2_1_CPU_MASK_SET            0x00f00010 /* CPU interrupt Mask Set Register */
#define BCHP_AVD_INTR2_1_CPU_MASK_CLEAR          0x00f00014 /* CPU interrupt Mask Clear Register */
#define BCHP_AVD_INTR2_1_PCI_STATUS              0x00f00018 /* PCI interrupt Status Register */
#define BCHP_AVD_INTR2_1_PCI_SET                 0x00f0001c /* PCI interrupt Set Register */
#define BCHP_AVD_INTR2_1_PCI_CLEAR               0x00f00020 /* PCI interrupt Clear Register */
#define BCHP_AVD_INTR2_1_PCI_MASK_STATUS         0x00f00024 /* PCI interrupt Mask Status Register */
#define BCHP_AVD_INTR2_1_PCI_MASK_SET            0x00f00028 /* PCI interrupt Mask Set Register */
#define BCHP_AVD_INTR2_1_PCI_MASK_CLEAR          0x00f0002c /* PCI interrupt Mask Clear Register */

#endif /* #ifndef BCHP_AVD_INTR2_1_H__ */

/* End of File */
