/***************************************************************************
 *     Copyright (c) 1999-2007, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_scl_3.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 7/23/07 4:13p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Mon Jul 23 11:54:31 2007
 *                 MD5 Checksum         61f9c4d8dcdcd06017506dddbf23f434
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008004
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7400/rdb/d0/bchp_scl_3.h $
 * 
 * Hydra_Software_Devel/1   7/23/07 4:13p maivu
 * PR 32842: Initial revision
 *
 ***************************************************************************/

#ifndef BCHP_SCL_3_H__
#define BCHP_SCL_3_H__

/***************************************************************************
 *SCL_3 - Video SD Scaler 3 Registers
 ***************************************************************************/
#define BCHP_SCL_3_REVISION_ID                   0x00120c00 /* Scaler Revision register */
#define BCHP_SCL_3_TOP_CONTROL                   0x00120c04 /* Scaler Top Level Control register */
#define BCHP_SCL_3_VERT_CONTROL                  0x00120c08 /* Video Vertical Scaler Control register */
#define BCHP_SCL_3_HORIZ_CONTROL                 0x00120c0c /* Video Horizontal Scaler Control register */
#define BCHP_SCL_3_BVB_IN_SIZE                   0x00120c10 /* BVB Input Picture Size Information */
#define BCHP_SCL_3_PIC_OFFSET                    0x00120c14 /* BVB Input Picture OFFSET Information */
#define BCHP_SCL_3_SRC_PIC_SIZE                  0x00120c18 /* Scaler Source Picture Size Information */
#define BCHP_SCL_3_DEST_PIC_SIZE                 0x00120c1c /* Scaler Destination Picture Size Information */
#define BCHP_SCL_3_SRC_PIC_VERT_PAN_SCAN         0x00120c20 /* Scaler Source Picture Vertical Pan/Scan Information */
#define BCHP_SCL_3_VERT_FIR_SRC_PIC_OFFSET       0x00120c24 /* Vertical 4 Taps Poly-Phase Filter Source Picture Offset */
#define BCHP_SCL_3_VERT_FIR_SRC_PIC_STEP         0x00120c28 /* Vertical 4 Taps Poly-Phase Filter Source Picture Stepping Size */
#define BCHP_SCL_3_SRC_PIC_HORIZ_PAN_SCAN        0x00120c2c /* Scaler Source Picture Horizontal Pan/Scan Information */
#define BCHP_SCL_3_HORIZ_FIR_LUMA_SRC_PIC_OFFSET 0x00120c30 /* Horizontal 8 Taps Poly-Phase Filter Source Picture Luma Offset */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_SRC_PIC_OFFSET 0x00120c34 /* Horizontal 8 Taps Poly-Phase Filter Source Picture Chroma Offset */
#define BCHP_SCL_3_HORIZ_FIR_INIT_PHASE_ACC      0x00120c38 /* Horizontal 8 Taps Poly-Phase Filter Inital Phase Accumulate Value */
#define BCHP_SCL_3_HORIZ_FIR_INIT_STEP           0x00120c3c /* Horizontal Poly-Phase Filter Initial Stepping Size for Region 0 */
#define BCHP_SCL_3_HORIZ_FIR_DEST_PIC_REGION_0_STEP_DELTA 0x00120c40 /* Horizontal Poly-Phase Filter Picture Delta Increment for Region 0 Stepping Size */
#define BCHP_SCL_3_HORIZ_FIR_DEST_PIC_REGION_2_STEP_DELTA 0x00120c44 /* Horizontal Poly-Phase Filter Picture Delta Increment for Region 2 Stepping Size */
#define BCHP_SCL_3_HORIZ_DEST_PIC_REGION_0_END   0x00120c48 /* Horizontal Poly-Phase Filter Destination Region 0 Ending Position */
#define BCHP_SCL_3_HORIZ_DEST_PIC_REGION_1_END   0x00120c4c /* Horizontal Poly-Phase Filter Destination Region 1 Ending Position */
#define BCHP_SCL_3_HORIZ_DEST_PIC_REGION_2_END   0x00120c50 /* Horizontal Poly-Phase Filter Destination Region 2 Ending Position */
#define BCHP_SCL_3_ENABLE                        0x00120c54 /* Video Scaler Enable */
#define BCHP_SCL_3_TEST_PORT_CONTROL             0x00120c80 /* Testportl control register */
#define BCHP_SCL_3_TEST_PORT_DATA                0x00120c84 /* Testport data register */
#define BCHP_SCL_3_SCRATCH_0                     0x00120c88 /* Scaler Scratch register 0 */
#define BCHP_SCL_3_SCRATCH_1                     0x00120c8c /* Scaler Scratch register 1 */
#define BCHP_SCL_3_BVB_IN_STATUS_CLEAR           0x00120ca0 /* Scaler Broadcom Video Bus Input Status Clear */
#define BCHP_SCL_3_BVB_IN_STATUS                 0x00120ca4 /* Scaler Broadcom Video Bus Input Status */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE0_00_01   0x00120e80 /* Vertical Scaler Poly-Phase Filter Phase 0 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE0_02_03   0x00120e84 /* Vertical Scaler Poly-Phase Filter Phase 0 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE1_00_01   0x00120e88 /* Vertical Scaler Poly-Phase Filter Phase 1 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE1_02_03   0x00120e8c /* Vertical Scaler Poly-Phase Filter Phase 1 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE2_00_01   0x00120e90 /* Vertical Scaler Poly-Phase Filter Phase 2 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE2_02_03   0x00120e94 /* Vertical Scaler Poly-Phase Filter Phase 2 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE3_00_01   0x00120e98 /* Vertical Scaler Poly-Phase Filter Phase 3 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE3_02_03   0x00120e9c /* Vertical Scaler Poly-Phase Filter Phase 3 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE4_00_01   0x00120ea0 /* Vertical Scaler Poly-Phase Filter Phase 4 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE4_02_03   0x00120ea4 /* Vertical Scaler Poly-Phase Filter Phase 4 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE5_00_01   0x00120ea8 /* Vertical Scaler Poly-Phase Filter Phase 5 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE5_02_03   0x00120eac /* Vertical Scaler Poly-Phase Filter Phase 5 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE6_00_01   0x00120eb0 /* Vertical Scaler Poly-Phase Filter Phase 6 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE6_02_03   0x00120eb4 /* Vertical Scaler Poly-Phase Filter Phase 6 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE7_00_01   0x00120eb8 /* Vertical Scaler Poly-Phase Filter Phase 7 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_COEFF_PHASE7_02_03   0x00120ebc /* Vertical Scaler Poly-Phase Filter Phase 7 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE0_00_01 0x00120ec0 /* Vertical Scaler Poly-Phase Filter Phase 0 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE0_02_03 0x00120ec4 /* Vertical Scaler Poly-Phase Filter Phase 0 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE1_00_01 0x00120ec8 /* Vertical Scaler Poly-Phase Filter Phase 1 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE1_02_03 0x00120ecc /* Vertical Scaler Poly-Phase Filter Phase 1 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE2_00_01 0x00120ed0 /* Vertical Scaler Poly-Phase Filter Phase 2 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE2_02_03 0x00120ed4 /* Vertical Scaler Poly-Phase Filter Phase 2 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE3_00_01 0x00120ed8 /* Vertical Scaler Poly-Phase Filter Phase 3 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE3_02_03 0x00120edc /* Vertical Scaler Poly-Phase Filter Phase 3 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE4_00_01 0x00120ee0 /* Vertical Scaler Poly-Phase Filter Phase 4 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE4_02_03 0x00120ee4 /* Vertical Scaler Poly-Phase Filter Phase 4 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE5_00_01 0x00120ee8 /* Vertical Scaler Poly-Phase Filter Phase 5 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE5_02_03 0x00120eec /* Vertical Scaler Poly-Phase Filter Phase 5 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE6_00_01 0x00120ef0 /* Vertical Scaler Poly-Phase Filter Phase 6 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE6_02_03 0x00120ef4 /* Vertical Scaler Poly-Phase Filter Phase 6 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE7_00_01 0x00120ef8 /* Vertical Scaler Poly-Phase Filter Phase 7 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_VERT_FIR_CHROMA_COEFF_PHASE7_02_03 0x00120efc /* Vertical Scaler Poly-Phase Filter Phase 7 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE0_00_01  0x00120f00 /* Horizontal Scaler Poly-Phase Filter Phase 0 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE0_02_03  0x00120f04 /* Horizontal Scaler Poly-Phase Filter Phase 0 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE0_04_05  0x00120f08 /* Horizontal Scaler Poly-Phase Filter Phase 0 Tap 4 and 5 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE0_06_07  0x00120f0c /* Horizontal Scaler Poly-Phase Filter Phase 0 Tap 6 and 7 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE1_00_01  0x00120f10 /* Horizontal Scaler Poly-Phase Filter Phase 1 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE1_02_03  0x00120f14 /* Horizontal Scaler Poly-Phase Filter Phase 1 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE1_04_05  0x00120f18 /* Horizontal Scaler Poly-Phase Filter Phase 1 Tap 4 and 5 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE1_06_07  0x00120f1c /* Horizontal Scaler Poly-Phase Filter Phase 1 Tap 6 and 7 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE2_00_01  0x00120f20 /* Horizontal Scaler Poly-Phase Filter Phase 2 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE2_02_03  0x00120f24 /* Horizontal Scaler Poly-Phase Filter Phase 2 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE2_04_05  0x00120f28 /* Horizontal Scaler Poly-Phase Filter Phase 2 Tap 4 and 5 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE2_06_07  0x00120f2c /* Horizontal Scaler Poly-Phase Filter Phase 2 Tap 6 and 7 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE3_00_01  0x00120f30 /* Horizontal Scaler Poly-Phase Filter Phase 3 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE3_02_03  0x00120f34 /* Horizontal Scaler Poly-Phase Filter Phase 3 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE3_04_05  0x00120f38 /* Horizontal Scaler Poly-Phase Filter Phase 3 Tap 4 and 5 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE3_06_07  0x00120f3c /* Horizontal Scaler Poly-Phase Filter Phase 3 Tap 6 and 7 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE4_00_01  0x00120f40 /* Horizontal Scaler Poly-Phase Filter Phase 4 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE4_02_03  0x00120f44 /* Horizontal Scaler Poly-Phase Filter Phase 4 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE4_04_05  0x00120f48 /* Horizontal Scaler Poly-Phase Filter Phase 4 Tap 4 and 5 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE4_06_07  0x00120f4c /* Horizontal Scaler Poly-Phase Filter Phase 4 Tap 6 and 7 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE5_00_01  0x00120f50 /* Horizontal Scaler Poly-Phase Filter Phase 5 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE5_02_03  0x00120f54 /* Horizontal Scaler Poly-Phase Filter Phase 5 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE5_04_05  0x00120f58 /* Horizontal Scaler Poly-Phase Filter Phase 5 Tap 4 and 5 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE5_06_07  0x00120f5c /* Horizontal Scaler Poly-Phase Filter Phase 5 Tap 6 and 7 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE6_00_01  0x00120f60 /* Horizontal Scaler Poly-Phase Filter Phase 6 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE6_02_03  0x00120f64 /* Horizontal Scaler Poly-Phase Filter Phase 6 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE6_04_05  0x00120f68 /* Horizontal Scaler Poly-Phase Filter Phase 6 Tap 4 and 5 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE6_06_07  0x00120f6c /* Horizontal Scaler Poly-Phase Filter Phase 6 Tap 6 and 7 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE7_00_01  0x00120f70 /* Horizontal Scaler Poly-Phase Filter Phase 7 Tap 0 and 1 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE7_02_03  0x00120f74 /* Horizontal Scaler Poly-Phase Filter Phase 7 Tap 2 and 3 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE7_04_05  0x00120f78 /* Horizontal Scaler Poly-Phase Filter Phase 7 Tap 4 and 5 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_COEFF_PHASE7_06_07  0x00120f7c /* Horizontal Scaler Poly-Phase Filter Phase 7 Tap 6 and 7 Luma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE0_00_01 0x00120f80 /* Horizontal Scaler Poly-Phase Filter Phase 0 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE0_02_03 0x00120f84 /* Horizontal Scaler Poly-Phase Filter Phase 0 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE0_04_05 0x00120f88 /* Horizontal Scaler Poly-Phase Filter Phase 0 Tap 4 and 5 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE0_06_07 0x00120f8c /* Horizontal Scaler Poly-Phase Filter Phase 0 Tap 6 and 7 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE1_00_01 0x00120f90 /* Horizontal Scaler Poly-Phase Filter Phase 1 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE1_02_03 0x00120f94 /* Horizontal Scaler Poly-Phase Filter Phase 1 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE1_04_05 0x00120f98 /* Horizontal Scaler Poly-Phase Filter Phase 1 Tap 4 and 5 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE1_06_07 0x00120f9c /* Horizontal Scaler Poly-Phase Filter Phase 1 Tap 6 and 7 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE2_00_01 0x00120fa0 /* Horizontal Scaler Poly-Phase Filter Phase 2 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE2_02_03 0x00120fa4 /* Horizontal Scaler Poly-Phase Filter Phase 2 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE2_04_05 0x00120fa8 /* Horizontal Scaler Poly-Phase Filter Phase 2 Tap 4 and 5 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE2_06_07 0x00120fac /* Horizontal Scaler Poly-Phase Filter Phase 2 Tap 6 and 7 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE3_00_01 0x00120fb0 /* Horizontal Scaler Poly-Phase Filter Phase 3 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE3_02_03 0x00120fb4 /* Horizontal Scaler Poly-Phase Filter Phase 3 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE3_04_05 0x00120fb8 /* Horizontal Scaler Poly-Phase Filter Phase 3 Tap 4 and 5 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE3_06_07 0x00120fbc /* Horizontal Scaler Poly-Phase Filter Phase 3 Tap 6 and 7 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE4_00_01 0x00120fc0 /* Horizontal Scaler Poly-Phase Filter Phase 4 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE4_02_03 0x00120fc4 /* Horizontal Scaler Poly-Phase Filter Phase 4 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE4_04_05 0x00120fc8 /* Horizontal Scaler Poly-Phase Filter Phase 4 Tap 4 and 5 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE4_06_07 0x00120fcc /* Horizontal Scaler Poly-Phase Filter Phase 4 Tap 6 and 7 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE5_00_01 0x00120fd0 /* Horizontal Scaler Poly-Phase Filter Phase 5 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE5_02_03 0x00120fd4 /* Horizontal Scaler Poly-Phase Filter Phase 5 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE5_04_05 0x00120fd8 /* Horizontal Scaler Poly-Phase Filter Phase 5 Tap 4 and 5 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE5_06_07 0x00120fdc /* Horizontal Scaler Poly-Phase Filter Phase 5 Tap 6 and 7 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE6_00_01 0x00120fe0 /* Horizontal Scaler Poly-Phase Filter Phase 6 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE6_02_03 0x00120fe4 /* Horizontal Scaler Poly-Phase Filter Phase 6 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE6_04_05 0x00120fe8 /* Horizontal Scaler Poly-Phase Filter Phase 6 Tap 4 and 5 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE6_06_07 0x00120fec /* Horizontal Scaler Poly-Phase Filter Phase 6 Tap 6 and 7 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE7_00_01 0x00120ff0 /* Horizontal Scaler Poly-Phase Filter Phase 7 Tap 0 and 1 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE7_02_03 0x00120ff4 /* Horizontal Scaler Poly-Phase Filter Phase 7 Tap 2 and 3 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE7_04_05 0x00120ff8 /* Horizontal Scaler Poly-Phase Filter Phase 7 Tap 4 and 5 Chroma Coefficients */
#define BCHP_SCL_3_HORIZ_FIR_CHROMA_COEFF_PHASE7_06_07 0x00120ffc /* Horizontal Scaler Poly-Phase Filter Phase 7 Tap 6 and 7 Chroma Coefficients */

#endif /* #ifndef BCHP_SCL_3_H__ */

/* End of File */
