#include "nexus_platform.h"
/*#include "nexus_gpio_module.h"*/
#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"

const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
	/*/////////////   0 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 000 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	/*//////////////  10 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /* GPIO 010 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	/*//////////////  20 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /* GPIO 020 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	/*//////////////  30 //////////////*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */  /* GPIO 030 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
/*//////////////  40 //////////////*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */ /* GPIO 040 */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
/*//////////////  50 //////////////*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */ /* GPIO 050 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
/*//////////////  60 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* GPIO 060 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
/*//////////////  70 //////////////*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */ /* GPIO 070 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	/*//////////////  80 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */ /* GPIO 080 */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	/*//////////////  90 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* GPIO 090 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* GPIO 098 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* GPIO 099 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */ 
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */ /* GPIO 102 */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */ /* GPIO 103 */
	/*////////////// 100 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */ /* GPIO 104 */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */ /* GPIO 110 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* SGPIO 00 I2C M2 demod 1 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* SGPIO 01 I2C M2 demod 1 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* SGPIO 02 I2C M3 demod 3 */
	/*////////////// 110 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* SGPIO 03 I2C M3 demod 3 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */ /* AON_GPIO 00 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */ 
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */ /* AON_GPIO 07 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */
	/*////////////// 120 //////////////*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */ /* AON_GPIO 09 */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */ /* AON_GPIO 17 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* AON_SGPIO 00 */
	/*////////////// 130 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* AON_SGPIO 01 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* AON_SGPIO 02 I2C M1 demod 0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* AON_SGPIO 03 I2C M1 demod 0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* SGPIO 04 I2C M4 demod 4*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* SGPIO 05 I2C M4 demod 4*/
};

HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_000_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_000_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_001_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_001_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_002_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_002_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_003_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_003_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_004_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_004_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_005_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_005_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_006_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_006_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_007_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_007_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_008_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_008_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_009_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_009_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_010_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_010_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_011_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_011_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_012_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_012_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_013_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_013_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_014_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_014_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_015_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_015_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_016_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_016_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_017_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_017_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_018_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_018_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_019_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_019_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_020_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_020_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_021_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_021_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_022_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_022_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_023_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_023_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_024_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_024_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_025_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_025_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_026_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_026_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_027_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_027_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_028_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_028_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_029_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_029_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_030_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_030_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_031_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_031_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_032_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_032_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_033_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_033_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_034_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_034_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_035_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_035_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_036_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_036_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_037_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_037_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_038_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_038_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_039_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_039_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_040_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_040_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_041_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_041_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_042_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_042_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_043_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_043_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_044_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_044_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_045_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_045_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_046_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_046_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_047_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_047_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_048_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_048_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_049_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_049_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_050_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_050_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_051_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_051_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_052_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_052_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_053_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_053_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_054_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_054_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_055_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_055_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_056_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_056_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_057_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_057_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_058_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_058_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_059_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_059_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_060_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_060_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_061_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_061_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_062_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_062_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_063_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_063_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_064_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_064_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_065_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_065_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_066_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_066_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_067_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_067_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_068_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_068_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_069_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_069_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_070_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_070_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_071_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_071_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_072_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_072_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_073_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_073_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_074_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_074_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_075_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_075_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_076_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_076_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_077_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_077_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_078_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_078_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_079_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_079_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_080_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_080_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_081_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_081_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_082_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_082_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_083_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_083_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_084_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_084_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_085_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_085_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_086_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_086_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_087_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_087_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_088_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_088_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_089_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_089_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_090_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_090_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_091_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_091_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_092_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_092_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_093_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_093_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_094_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_094_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_095_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_095_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_096_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_096_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_097_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_097_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_098_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_098_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_099_MASK,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_099_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_100_MASK,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_100_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_101_MASK,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_101_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_102_MASK,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_102_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_103_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_103_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_104_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_104_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_105_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_105_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_106_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_106_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_107_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_107_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_108_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_108_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_109_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_109_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_110_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_110_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_00_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_01_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_02_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_03_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_SHIFT},
	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_SHIFT},
	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_SHIFT},
	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_05_SHIFT},
	
};

