obj-$(CONFIG_MW_CAS_NAGRA_OP_SES)				+= ses/
obj-$(CONFIG_MW_CAS_NAGRA_RCS)				+= rcs/
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)			+= mset/
obj-$(CONFIG_MW_CAS_NAGRA_TIVU)				+= tivu/

obj-y										+= menu/
obj-y 										+= xmgr_cas_na_ui.o
obj-y										+= xmgr_cas_na_pincode_ui.o

obj-$(CONFIG_MW_CAS_NAGRA_IRDCMD_MAIL)		+= xmgr_cas_na_irdcmd_mail.o
obj-$(CONFIG_MW_CAS_NAGRA_IRDCMD_FINGER)	+= xmgr_cas_na_irdcmd_fingerprint.o
obj-$(CONFIG_MW_CAS_NAGRA_IRDCMD_PINCTL)	+= xmgr_cas_na_irdcmd_pincode.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

# Sub-CAS include path
