/***************************************************************************
 *     Copyright (c) 1999-2008, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_cap_3.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 1/9/08 10:08a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Jan  9 08:58:41 2008
 *                 MD5 Checksum         847dc12a9d71c4c68a648bbf19a883e3
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7400/rdb/e0/bchp_cap_3.h $
 * 
 * Hydra_Software_Devel/1   1/9/08 10:08a rpan
 * PR38572: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_CAP_3_H__
#define BCHP_CAP_3_H__

/***************************************************************************
 *CAP_3 - Capture 0 Registers
 ***************************************************************************/
#define BCHP_CAP_3_REVISION                      0x00140600 /* Capture Engine Revision ID */
#define BCHP_CAP_3_PIC_SIZE                      0x00140604 /* Capture Vertical and Horizontal Size */
#define BCHP_CAP_3_CTRL                          0x00140608 /* Capture Control */
#define BCHP_CAP_3_MSTART                        0x0014060c /* Capture Memory Buffer Starting Address */
#define BCHP_CAP_3_PITCH                         0x00140610 /* Capture Memory Buffer Pitch */
#define BCHP_CAP_3_BYTE_ORDER                    0x00140614 /* Capture Byte Order Control */
#define BCHP_CAP_3_TRIG_CTRL                     0x00140618 /* Capture RDMA Trigger Control */
#define BCHP_CAP_3_BVB_TRIG_0_CFG                0x0014061c /* Capture BVB Trigger 0 Configuration */
#define BCHP_CAP_3_BVB_TRIG_1_CFG                0x00140620 /* Capture BVB Trigger 1 Configuration */
#define BCHP_CAP_3_LINE_CMP_TRIG_0_CFG           0x00140624 /* Capture Line Compare Trigger 0 Configuration */
#define BCHP_CAP_3_LINE_CMP_TRIG_1_CFG           0x00140628 /* Capture Line Compare Trigger 1 Configuration */
#define BCHP_CAP_3_RX_CTRL                       0x0014062c /* Capture BVB Receiver Control */
#define BCHP_CAP_3_STATUS                        0x00140630 /* Capture Engine Status */
#define BCHP_CAP_3_BVB_STATUS                    0x00140634 /* Capture BVB Status */
#define BCHP_CAP_3_BVB_STATUS_CLEAR              0x00140638 /* Capture BVB Status Clear */
#define BCHP_CAP_3_FIFO_STATUS                   0x0014063c /* Capture FIFO Status */
#define BCHP_CAP_3_FIFO_STATUS_CLEAR             0x00140640 /* Capture FIFO Status Clear */
#define BCHP_CAP_3_PIC_OFFSET                    0x00140644 /* Capture Vertical and Horizontal Start Offset */
#define BCHP_CAP_3_BVB_IN_SIZE                   0x00140648 /* Capture BVB Source Vertical and Horizontal Size */
#define BCHP_CAP_3_SCRATCH                       0x0014064c /* Scratch Register */

#endif /* #ifndef BCHP_CAP_3_H__ */

/* End of File */
