/***************************************************************************
 *     Copyright (c) 1999-2008, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_vcxo_1_rm.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 1/9/08 11:55a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Jan  9 08:56:36 2008
 *                 MD5 Checksum         847dc12a9d71c4c68a648bbf19a883e3
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7400/rdb/e0/bchp_vcxo_1_rm.h $
 * 
 * Hydra_Software_Devel/1   1/9/08 11:55a rpan
 * PR38572: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_VCXO_1_RM_H__
#define BCHP_VCXO_1_RM_H__

/***************************************************************************
 *VCXO_1_RM - VCXO 1 Rate Manager
 ***************************************************************************/
#define BCHP_VCXO_1_RM_CONTROL                   0x00041300 /* Rate Manager Controls */
#define BCHP_VCXO_1_RM_RATE_RATIO                0x00041304 /* Rate Manager Output Rate Setting I */
#define BCHP_VCXO_1_RM_SAMPLE_INC                0x00041308 /* Rate Manager Output Rate Setting II */
#define BCHP_VCXO_1_RM_PHASE_INC                 0x0004130c /* Rate Manager NCO Phase Increment */
#define BCHP_VCXO_1_RM_INTEGRATOR                0x00041310 /* Loop Filter Integrator Value */
#define BCHP_VCXO_1_RM_OFFSET                    0x00041314 /* Rate Manager Output Formatting */
#define BCHP_VCXO_1_RM_FORMAT                    0x00041318 /* Rate Manager Output Formatting */

#endif /* #ifndef BCHP_VCXO_1_RM_H__ */

/* End of File */
