obj-y += umma.o
obj-y += umma_rpcprotocol.o

obj-y += module/

# Additional include path
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fm/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fs/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/hotplug/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/smbc/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/smbs/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/ftps/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/secure/include
