# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =       \
    commonlib   \
    parserlib   \
    builderlib  \

include $(PLAYREADY_DIR)/GNUmakefile.common

