/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_vice2_arcss_ess_flag_intr2_1.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 1/17/12 5:42p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Jan 17 13:26:47 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7425/rdb/b2/bchp_vice2_arcss_ess_flag_intr2_1.h $
 * 
 * Hydra_Software_Devel/1   1/17/12 5:42p vanessah
 * SW7425-2202: add B2 headers
 *
 ***************************************************************************/

#ifndef BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_H__
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_H__

/***************************************************************************
 *VICE2_ARCSS_ESS_FLAG_INTR2_1 - VICE2 ARCSS_ESS Flag Controller 1
 ***************************************************************************/
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_STATUS 0x00750400 /* Soft interrupt Status Register */
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_SET    0x00750404 /* Soft interrupt Set Register */
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_CLEAR  0x00750408 /* Soft interrupt Clear Register */
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_MASK_STATUS 0x0075040c /* Soft interrupt Mask Status Register */
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_MASK_SET 0x00750410 /* Soft interrupt Mask Set Register */
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_MASK_CLEAR 0x00750414 /* Soft interrupt Mask Clear Register */

/***************************************************************************
 *RESERVED%i - RESERVED
 ***************************************************************************/
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_RESERVEDi_ARRAY_BASE     0x00750418
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_RESERVEDi_ARRAY_START    0
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_RESERVEDi_ARRAY_END      5
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_RESERVEDi_ARRAY_ELEMENT_SIZE 32

/***************************************************************************
 *RESERVED%i - RESERVED
 ***************************************************************************/
/* VICE2_ARCSS_ESS_FLAG_INTR2_1 :: RESERVEDi :: RESERVED [31:00] */
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_RESERVEDi_RESERVED_MASK  0xffffffff
#define BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_RESERVEDi_RESERVED_SHIFT 0


#endif /* #ifndef BCHP_VICE2_ARCSS_ESS_FLAG_INTR2_1_H__ */

/* End of File */
