/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_reg_cabac2bins_1.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 1/17/12 4:38p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Jan 17 13:26:48 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7425/rdb/b2/bchp_reg_cabac2bins_1.h $
 * 
 * Hydra_Software_Devel/1   1/17/12 4:38p vanessah
 * SW7425-2202: add B2 headers
 *
 ***************************************************************************/

#ifndef BCHP_REG_CABAC2BINS_1_H__
#define BCHP_REG_CABAC2BINS_1_H__

/***************************************************************************
 *REG_CABAC2BINS_1
 ***************************************************************************/
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_IMG__CTX_LAST 0x00000bbc /* REG_CABAC2BINS_IMG__CTX_LAST */
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_CONTEXT_TABLE_BASE_ADDR 0x00000bd0 /* REG_CABAC2BINS_CONTEXT_TABLE_BASE_ADDR */
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_END_END 0x00000bfc /* REG_CABAC2BINS_END_END */

/***************************************************************************
 *REG_CABAC2BINS_IMG__CTX_LAST - REG_CABAC2BINS_IMG__CTX_LAST
 ***************************************************************************/
/* REG_CABAC2BINS_1 :: REG_CABAC2BINS_IMG__CTX_LAST :: reserved0 [31:09] */
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_IMG__CTX_LAST_reserved0_MASK 0xfffffe00
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_IMG__CTX_LAST_reserved0_SHIFT 9

/* REG_CABAC2BINS_1 :: REG_CABAC2BINS_IMG__CTX_LAST :: CtxLast [08:00] */
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_IMG__CTX_LAST_CtxLast_MASK 0x000001ff
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_IMG__CTX_LAST_CtxLast_SHIFT 0

/***************************************************************************
 *REG_CABAC2BINS_CONTEXT_TABLE_BASE_ADDR - REG_CABAC2BINS_CONTEXT_TABLE_BASE_ADDR
 ***************************************************************************/
/* REG_CABAC2BINS_1 :: REG_CABAC2BINS_CONTEXT_TABLE_BASE_ADDR :: Addr [31:04] */
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_CONTEXT_TABLE_BASE_ADDR_Addr_MASK 0xfffffff0
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_CONTEXT_TABLE_BASE_ADDR_Addr_SHIFT 4

/* REG_CABAC2BINS_1 :: REG_CABAC2BINS_CONTEXT_TABLE_BASE_ADDR :: reserved0 [03:00] */
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_CONTEXT_TABLE_BASE_ADDR_reserved0_MASK 0x0000000f
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_CONTEXT_TABLE_BASE_ADDR_reserved0_SHIFT 0

/***************************************************************************
 *REG_CABAC2BINS_END_END - REG_CABAC2BINS_END_END
 ***************************************************************************/
/* REG_CABAC2BINS_1 :: REG_CABAC2BINS_END_END :: reserved0 [31:00] */
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_END_END_reserved0_MASK 0xffffffff
#define BCHP_REG_CABAC2BINS_1_REG_CABAC2BINS_END_END_reserved0_SHIFT 0

#endif /* #ifndef BCHP_REG_CABAC2BINS_1_H__ */

/* End of File */
