-include ./dirs

ifeq ($(DIRS),)
TARGET = domainreal

SOURCES =                \
	drmdomainapi.c drmdomainimp.c drmdomainkeyxmrparser.c drmdomainstore.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
