obj-y += pal_crypt.o
obj-y += pal_cipher.o
obj-y += pal_cipher_bn_lib.o
obj-y += pal_cipher_md5_lib.o
obj-y += pal_cipher_mpi_lib.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.pal
# Additional include path
ccflags-y += -I$(THIRDPARTY_DIR)/crypt/include

