#include "nexus_platform.h"
/*#include "nexus_gpio_module.h"*/
#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"
 
const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
	/*/////////////   0 ///////////////*/
	HUMAX_GPIO_FUNCTION_ALT2,	/*//0  */  /* GP_ENET_LINK */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//1 */  /* GP_ENET_ACTIVITY */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//2  */ /*	GP_7445_RGMII_RXCLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//3 */ /*GP_7445_RGMII_RXDV */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//4  */ /*GP_7445_RGMII_RXD0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//5  */ /*GP_7445_RGMII_RXD1 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//6  */ /*GP_7445_RGMII_RXD2*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//7  */ /*GP_7445_RGMII_RXD3 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//8  */ /*GP_53125_IMP_RXCLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//9  */ /* GP_53125_IMP_RXDV*/
	/*//////////////  10 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//10  */  /*GP_53125_IMP_RXD0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//11  */  /*GP_53125_IMP_RXD1*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//12  */  /*GP_53125_IMP_RXD2 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//13 */  /*GP_53125_IMP_RXD3 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//14  */  /*GP_53125_MDIO */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//15 */  /*GP_53125_MDC */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//16  */  /*GP_53125_IRQ_N*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//17  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//18  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//19  */  /*GP_MTSIF0_CLK */
/*//////////////  20 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//20  */  /*GP_MTSIF0_DATA0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//21  */  /*GP_MTSIF0_SYNC*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//22  */  /*GP_MTSIF0_DATA*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*//23  */  /*N.C.    - GP_MTSIF0_VALID*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//24  */  /*GP_MTSIF0_DATA2*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//25  */  /*GP_MTSIF0_DATA3*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//26  */  /*GP_MTSIF0_DATA4 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//27  */  /*GP_MTSIF0_DATA5 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//28  */  /*GP_MTSIF0_DATA6 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//29  */  /*GP_MTSIF0_DATA7 */
	/*//////////////  30 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//30  */  /*GP_MTSIF_ATS_INC */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//31  */  /*GP_MTSIF_ATS_RST */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//32  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//33  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//34  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//35  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//36  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//37  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//38  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//39  */  /*N.C. */
/*//////////////  40 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//40  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//41  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//42  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//43  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//44  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//45  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//46  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//47  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//48  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//49  */ /*GP_SC0_IO */
/*//////////////  50 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT4,	/*//50  */  /*GP_SC0_CLK */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//51  */  /*GP_SC0_RST */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//52 */  /*GP_SC0_PRES */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//53  */  /*GP_SC0_VCC */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//54  */  /*GP_SC0_AUX1 */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//55  */  /*GP_SC0_AUX2 */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//56  */  /*GP_SC0_VCTRL */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//57  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//58  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//59  */  /*N.C. */
/*//////////////  60 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*GP_MTSIF1_CLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*GP_MTSIF1_DATA0*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*GP_MTSIF1_SYNC */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*GP_MTSIF1_DATA1 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /*N.C.   - GP_MTSIF1_VALID */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*GP_MTSIF1_DATA2 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*GP_MTSIF1_DATA3 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*GP_MTSIF1_DATA4 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*GP_MTSIF1_DATA5 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*GP_MTSIF1_DATA6 */
/*//////////////  70 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//70  */  /*GP_MTSIF1_DATA7 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//71  */  /*FAN_SPEED */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//72  */  /*GP_7445_DEBUG_UART6_TX */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//73  */  /*GP_7445_DEBUG_UART6_RX */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//74  */  /*FAN_PWM */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//75  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//76  */  /*GP_SDIO0_CMD */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//77  */  /*GP_SDIO0_WPROT */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//78  */  /*GP_SDIO0_PWR0 */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//79  */  /*GP_SDIO0_CLK */
	/*//////////////  80 //////////////*/ 
	HUMAX_GPIO_FUNCTION_ALT2,	/*//80  */  /*GP_SDIO0_D0 */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//81  */  /*GP_SDIO0_D1 */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//82  */  /*GP_SDIO0_D2 */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//83  */  /*GP_SDIO0_D3 */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//84  */  /*GP_SDIO0_PRES */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//85  */  /*GP_SDIO0_LED */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//86  */  /*GP_SC1_IO */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//87  */  /*GP_SC1_CLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//88  */  /*GP_SC1_RST */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//89  */  /*GP_SC1_PRES */
	/*//////////////  90 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//90  */  /*GP_SC1_VCC */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//91  */  /*NDS_SC1_AUX1 */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//92  */  /*NDS_SC1_AUX2 */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//93  */  /*NDS_SC1_VCTRL */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//94  */  /*GPIO_DAUGHTER_3 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//95  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//96  */  /*N.C. */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//97  */  /*GP_RF4CE_INT */ 
	HUMAX_GPIO_FUNCTION_GPIO,	/*//98  */  /*GP_RF4CE_WKUP */ 
	HUMAX_GPIO_FUNCTION_GPIO,	/*//99  */  /*GP_RF4CE_RST */
	/*////////////// 100 //////////////*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*//100  */  /*GPIO_DAUGHTER_0 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//101  */  /*HDD_PWR_CTRL */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//102  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//103  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//104  */  /*AUDIO_MUTE */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//105  */  /*NFC_IRQ */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//106  */  /*NFC_MODE */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//107  */  /*NFC_ASK_OOK */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//108  */  /*NFC_SYS_CLK*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*//109  */  /*GPIO_DAUGHTER_1 */
	/*////////////// 110 //////////////*/	
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /*N.C.  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  */  /*GPIO_DAUGHTER_2 */
	
	/*////////////// SGPIO 00 (0~5)//////////////*/	
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*7445_HDMI_TX_BSC_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*7445_HDMI_TX_BSC_SDA */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*7445_HDMI_RX_BSC_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*7445_HDMI_RX_BSC_SDA */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*7445_BSC_M2_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */  /*7445_BSC_M2_SDA */
	
	/*////////////// AON_GPIO 00(0~17)//////////////*/	
	HUMAX_GPIO_FUNCTION_GPIO,	/*//0  */  /*7445_WAKE_N */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//1  */  /*BT_WOW_N */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//2 */ /*43526_WIFI_RST_N */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//3  */ /*PCIE_WIFI_WOW_N */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//4  */ /*N.C.  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//5  */ /*NFC_SPI_SS_N */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//6  */ /*53125_SPI_SS_N */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//7  */  /*N.C.   */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//8  */ /*GP_7445_COM_UART0_TX */
	HUMAX_GPIO_FUNCTION_ALT2,	/*//9  */ /*GP_7445_COM_UART0_RX */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//10  */ /*AON_GPIO10_MOCA_LINK */

	HUMAX_GPIO_FUNCTION_NCTP,	/*//11  */  /*N.C.    */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//12  */  /*N.C.    */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//13  */ /*7445_SPI_SCK */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//14  */ /*7445_SPI_MOSI */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//15  */ /*7445_SPI_MISO */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//16  */ /*N.C. */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//17  */	/*N.C. */

	/*////////////// AON_SGPIO (0~5)//////////////*/	
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /*7445_BSC_M3_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /*7445_BSC_M3_SDA */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /*7445_BSC_M4_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /*7445_BSC_M4_SDA */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /*7445_MOCA_BSC_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /*7445_MOCA_BSC_SDA */
};

/*************************
*	gpio: 0~111 :112
*	sgpio: 0~5 : 6
*	aon_gpio: 0~17 : 18
*	aon_sgpio: 0~5 : 6
*************************/
HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_000_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_000_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_001_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_001_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_002_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_002_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_003_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_003_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_004_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_004_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_005_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_005_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_006_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_006_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_007_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_007_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_008_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_008_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_009_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_009_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_010_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_010_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_011_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_011_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_012_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_012_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_013_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_013_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_014_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_014_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_015_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_015_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_016_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_016_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_017_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_017_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_018_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_018_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_019_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_019_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_020_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_020_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_021_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_021_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_022_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_022_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_023_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_023_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_024_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_024_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_025_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_025_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_026_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_026_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_027_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_027_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_028_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_028_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_029_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_029_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_030_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_030_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_031_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_031_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_032_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_032_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_033_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_033_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_034_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_034_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_035_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_035_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_036_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_036_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_037_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_037_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_038_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_038_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_039_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_039_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_040_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_040_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_041_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_041_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_042_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_042_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_043_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_043_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_044_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_044_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_045_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_045_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_046_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_046_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_047_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_047_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_048_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_048_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_049_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_049_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_050_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_050_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_051_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_051_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_052_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_052_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_053_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_053_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_054_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_054_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_055_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_055_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_056_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_056_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_057_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_057_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_058_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_058_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_059_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_059_SHIFT},            
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_060_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_060_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_061_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_061_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_062_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_062_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_063_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_063_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_064_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_064_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_065_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_065_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_066_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_066_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_067_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_067_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_068_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_068_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_069_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_069_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_070_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_070_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_071_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_071_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_072_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_072_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_073_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_073_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_074_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_074_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_075_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_075_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_076_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_076_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_077_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_077_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_078_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_078_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_079_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_079_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_080_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_080_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_081_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_081_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_082_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_082_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_083_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_083_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_084_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_084_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_085_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_085_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_086_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_086_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_087_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_087_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_088_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_088_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_089_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_089_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_090_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_090_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_091_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_091_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_092_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_092_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_093_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_093_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_094_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_094_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_095_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_095_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_096_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_096_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_097_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_097_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_098_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_098_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_099_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_099_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_100_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_100_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_101_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_101_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_102_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_102_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_103_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_103_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_104_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_104_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_105_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_105_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_106_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_106_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_107_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_107_SHIFT},        
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_108_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_108_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_109_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_109_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_110_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_110_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_111_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_111_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_00_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_01_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_sgpio_02_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_sgpio_03_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_sgpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_sgpio_04_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_sgpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_sgpio_05_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_05_SHIFT}
    };
