#include "nexus_platform.h"
/*#include "nexus_gpio_module.h"*/
#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"

const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 000 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 001 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 002 */ /* NC */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 003 */ /* WL_REG_ON */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 004 */ /* BT_REG_ON */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 005 */ /* BCM45204_RESET# */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 006 */ /* BCM45204_IRQ# */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 007 */ /* NC */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 008 */ /* BT_DISABLE# */ 
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 009 */ /* NC */

	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 010 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 011 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 012 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 013 */ /* NC */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 014 */ /* WL_PCIE_WAKE# */ 
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 015 */ /* WL_DISABLE# */ 
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 016 */ /* CI_IRQ# */ 
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 017 */ /* CI_CD1# */ 
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 018 */ /* CI_CD2# */ 
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 019 */ /* MTSIF0_CLK */
	
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 020 */ /* MTSIF0_DATA0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 021 */ /* MTSIF0_SYNC */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 022 */ /* MTSIF0_DATA1 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 023 */ /* NC */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 024 */ /* MTSIF0_DATA2 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 025 */ /* MTSIF0_DATA3 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 026 */ /* MTSIF0_DATA4 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 027 */ /* MTSIF0_DATA5 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 028 */ /* MTSIF0_DATA6 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 029 */ /* MTSIF0_DATA7 */
	
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 030 */ /* MTSIF_ATS_INC */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 031 */ /* MTSIF_ATS_RST */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 032 */ /* TP1977 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 033 */ /* TP1978 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 034 */ /* SPI_M_SCK */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 035 */ /* SPI_M_MISO */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 036 */ /* SPI_M_MOSI */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 037 */ /* SPI_M_SS0# */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 038 */ /* CI2CHIP_MISTRT */ 
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 039 */ /* CI2CHIP_MIVAL */
	
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 040 */ /* CI2CHIP_MDI0 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 041 */ /* CI2CHIP_MDI1 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 042 */ /* CI2CHIP_MDI2 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 043 */ /* CI2CHIP_MDI3 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 044 */ /* CI2CHIP_MDI4 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 045 */ /* CI2CHIP_MDI5 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 046 */ /* CI2CHIP_MDI6 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 047 */ /* CI2CHIP_MDI7 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 048 */ /* CI2CHIP_MICLK */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 049 */ /* CHIP2CI_MOVAL */
	
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 050 */ /* CHIP2CI_MOSTRT */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 051 */ /* CHIP2CI_MDO0 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 052 */ /* CHIP2CI_MDO1 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 053 */ /* CHIP2CI_MDO2 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 054 */ /* CHIP2CI_MDO3 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 055 */ /* CHIP2CI_MDO4 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 056 */ /* CHIP2CI_MDO5 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 057 */ /* CHIP2CI_MDO6 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 058 */ /* CHIP2CI_MDO7 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 059 */ /* CHIP2CI_MOCLK */
	
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 060 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 061 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 062 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 063 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 064 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 065 */ /* NC */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 066 */ /* CI_RESET */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 067 */ /* CI_POWER */
	HUMAX_GPIO_FUNCTION_ALT3,	/* GPIO 068 */ /* UART_RXD_1 */
	HUMAX_GPIO_FUNCTION_ALT3,	/* GPIO 069 */ /* UART_TXD_1 */
	
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 070 */ /* HDD_PWR */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 071 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 072 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 073 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 074 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 075 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 076 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 077 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 078 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 079 */ /* NC */
	
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 080 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 081 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 082 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 083 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 084 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 085 */ /* NC */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 086 */ /* SC1_IO */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 087 */ /* SC1_CLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 088 */ /* SC1_RST# */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 089 */ /* SC1_DET */
	
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 090 */ /* SC1_VON# */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 091 */ /* SC1_AUX1 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 092 */ /* SC1_AUX2 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 093 */ /* SC1_VSEL */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 094 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 095 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 096 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 097 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 098 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 099 */ /* NC */
	
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 100 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 101 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 102 */ /* NC */ 
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 103 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 104 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 105 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 106 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 107 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 108 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 109 */ /* STRAP_GP109_STRAP_RSVD */
	
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 110 */ /* TP1004 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 111 */ /* TP1100 */
	
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 00 */ /* LNBP1_SCL */ 
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 01 */ /* LNBP1_SDA */ 
	HUMAX_GPIO_FUNCTION_NCTP,	/* SGPIO 02 */ /* PU */ 
	HUMAX_GPIO_FUNCTION_NCTP,	/* SGPIO 03 */ /* PU */
	HUMAX_GPIO_FUNCTION_NCTP,	/* SGPIO 04 */ /* PU */
	HUMAX_GPIO_FUNCTION_NCTP,	/* SGPIO 05 */ /* PU */
	
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 00 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 01 */ /* NC */	
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 02 */ /* S2_ON */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 03 */ /* KEY_IN_STBY */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 04 */ /* STRAP_AGP04 */
	HUMAX_GPIO_FUNCTION_ALT3,	/* AON_GPIO 05 */ /* STRAP_AGP05_SS1# */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 06 */ /* STRAP_AGP06 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 07 */ /* STRAP_AGP07 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 08 */ /* STRAP_AGP08 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 09 */ /* WIFI_HOST_WAKE# */ 
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 10 */ /* BT_HOST_WAKE# */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 11 */ /* STRAP_AGP11 */	
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 12 */ /* TP6997 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* AON_GPIO 13 */ /* BT_UART_RX */
	HUMAX_GPIO_FUNCTION_ALT2,	/* AON_GPIO 14 */ /* STRAP_BT_UART_TX */
	HUMAX_GPIO_FUNCTION_ALT2,	/* AON_GPIO 15 */ /* BT_UART_CTS */
	HUMAX_GPIO_FUNCTION_ALT2,	/* AON_GPIO 16 */ /* STRAP_BT_UART_RTS */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 17 */ /* TP6755 */
	
	HUMAX_GPIO_FUNCTION_ALT2,	/* AON_SGPIO 00 */ /* HDMI_TX_SCL */
	HUMAX_GPIO_FUNCTION_ALT2,	/* AON_SGPIO 01 */ /* HDMI_TX_SDA */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_SGPIO 02 */ /* PU*/ 
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_SGPIO 03 */ /* PU */ 	
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_SGPIO 04 */ /* LNBP0_SCL */ 
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_SGPIO 05 */ /* LNBP1_SDA */ 
};
/*************************
*       gpio: 0~111 :112
*       sgpio: 0~5 : 6
*       aon_gpio: 0~17 : 18
*       aon_sgpio: 0~5 : 6
*************************/
HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
	/* GPIO 000 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_000_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_000_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_001_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_001_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_002_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_002_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_003_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_003_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_004_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_004_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_005_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_005_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_006_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_006_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_007_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_007_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_008_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_008_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_009_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_009_SHIFT},
	/* GPIO 010 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_010_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_010_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_011_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_011_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_012_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_012_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_013_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_013_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_014_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_014_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_015_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_015_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_016_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_016_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_017_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_017_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_018_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_018_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_019_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_019_SHIFT},	
	/* GPIO 020 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_020_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_020_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_021_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_021_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_022_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_022_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_023_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_023_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_024_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_024_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_025_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_025_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_026_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_026_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_027_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_027_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_028_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_028_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_029_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_029_SHIFT},
	/* GPIO 030 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_030_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_030_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_031_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_031_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_032_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_032_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_033_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_033_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_034_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_034_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_035_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_035_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_036_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_036_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_037_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_037_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_038_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_038_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_039_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_039_SHIFT},
	/* GPIO 040 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_040_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_040_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_041_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_041_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_042_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_042_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_043_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_043_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_044_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_044_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_045_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_045_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_046_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_046_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_047_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_047_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_048_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_048_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_049_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_049_SHIFT},
	/* GPIO 050 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_050_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_050_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_051_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_051_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_052_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_052_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_053_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_053_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_054_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_054_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_055_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_055_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_056_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_056_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_057_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_057_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_058_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_058_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_059_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_059_SHIFT},	
	/* GPIO 060 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_060_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_060_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_061_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_061_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_062_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_062_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_063_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_063_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_064_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_064_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_065_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_065_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_066_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_066_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_067_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_067_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_068_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_068_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_069_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_069_SHIFT},
	/* GPIO 070 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_070_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_070_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_071_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_071_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_072_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_072_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_073_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_073_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_074_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_074_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_075_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_075_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_076_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_076_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_077_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_077_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_078_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_078_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_079_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_079_SHIFT},
	/* GPIO 080 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_080_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_080_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_081_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_081_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_082_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_082_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_083_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_083_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_084_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_084_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_085_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_085_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_086_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_086_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_087_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_087_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_088_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_088_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_089_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_089_SHIFT},
	/* GPIO 090 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_090_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_090_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_091_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_091_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_092_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_092_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_093_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_093_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_094_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_094_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_095_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_095_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_096_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_096_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_097_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_097_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_098_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_098_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_099_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_099_SHIFT},
	/* GPIO 100 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20,  BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_100_MASK,  BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_100_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20,  BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_101_MASK,  BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_101_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20,  BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_102_MASK,  BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_102_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_103_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_103_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_104_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_104_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_105_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_105_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_106_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_106_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_107_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_107_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_108_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_108_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_109_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_109_SHIFT},
	/* GPIO 110 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_110_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_110_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_111_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_111_SHIFT},
	/* SGPIO 000 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_00_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_01_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_02_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_03_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_04_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_05_SHIFT},
	/* AON_GPIO 000 */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_SHIFT},	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_SHIFT},	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT},
	/* AON_SGPIO 000 */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_SHIFT},	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_05_SHIFT},	
};

