/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.brcm.scalar.conf $
 */
#ifndef DOCSDEVSOFTWARE_H
#define DOCSDEVSOFTWARE_H

config_require(bcmV2)

    /*
     * function declarations 
     */
     void            init_docsDevSoftware(void);
     Netsnmp_Node_Handler do_docsDevSwFilename;
     Netsnmp_Node_Handler get_docsDevSwOperStatus;
     Netsnmp_Node_Handler do_docsDevSwAdminStatus;
     Netsnmp_Node_Handler get_docsDevSwCurrentVers;
     Netsnmp_Node_Handler do_docsDevSwServer;

#endif                          /* DOCSDEVSOFTWARE_H */
