/*
 * Note: this file originally auto-generated by mib2c using
 *        mib2c.brcm.iterate.conf 2003/6/16 turcotte
 */
#ifndef DOCSIFCMMACTABLE_H
#define DOCSIFCMMACTABLE_H

/*
 * function declarations 
 */
void            init_docsIfCmMacTable(void);
void            initialize_table_docsIfCmMacTable(void);
Netsnmp_Node_Handler docsIfCmMacTable_handler;


/*
 * column number definitions for table docsIfCmMacTable 
 */
#define COLUMN_DOCSIFCMCMTSADDRESS		1
#define COLUMN_DOCSIFCMCAPABILITIES		2
#define COLUMN_DOCSIFCMRANGINGRESPTIMEOUT		3
#define COLUMN_DOCSIFCMRANGINGTIMEOUT		4
#endif                          /* DOCSIFCMMACTABLE_H */
