obj-y += db_param.o
obj-y += db_param_default.o
obj-y += db_param_table.o
obj-y += db_param_cache.o
obj-y += db_param_dama.o
obj-y += db_param_registry.o
obj-y += db_param_migration.o
obj-y += db_param_keeping_item.o

# Basic include path

# Additional include path
ccflags-y += -I$(OCTO_DB_DIR)/include_plugin
ccflags-y += -I$(OCTO_DB_DIR)/local_include
ccflags-y += -I$(OCTO_DB_DIR)/include


