##############################################################################
#
# Copyright (c) 2004-2009 Broadcom Corporation
#
# This program is the proprietary software of Broadcom Corporation and/or
# its licensors, and may only be used, duplicated, modified or distributed
# pursuant to the terms and conditions of a separate, written license
# agreement executed between you and Broadcom (an "Authorized License").
# Except as set forth in an Authorized License, Broadcom grants no license
# (express or implied), right to use, or waiver of any kind with respect to
# the Software, and Broadcom expressly reserves all rights in and to the
# Software and all intellectual property rights therein.  IF YOU HAVE NO
# AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
# AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
# SOFTWARE.  
#
# Except as expressly set forth in the Authorized License,
#
# 1.     This program, including its structure, sequence and organization,
# constitutes the valuable trade secrets of Broadcom, and you shall use all
# reasonable efforts to protect the confidentiality thereof, and to use this
# information only in connection with your use of Broadcom integrated circuit
# products.
#
# 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
# "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
# OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
# RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
# IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
# A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
# ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
# THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
#
# 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
# OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
# INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
# RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
# HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
# EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
# WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
# FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
#
##############################################################################

############################################################################
##                 V2 COMPONENT INCLUDES 
############################################################################

# Ip Helpers
BCM_SOCKET_SUPPORT=1
BCM_TFTP_SUPPORT=0
BCM_DHCPC_SUPPORT=0
BCM_TOD_SUPPORT=0
BCM_CONSOLE_SUPPORT=0
BCM_DHCPS_SUPPORT=0
BCM_PING_SUPPORT=0
BCM_PING_CONSOLE_SUPPORT=0
BCM_PACKET_GENERATOR_SUPPORT=0
BCM_V2_DHCP_SUPPORT=0

ifeq ($(BCM_REDUCED_IMAGE_SIZE), 1)
  BCM_PACKET_GENERATOR_SUPPORT=0
  BCM_PING_CONSOLE_SUPPORT=0
  BCM_CONSOLE_SUPPORT=0
endif


# Non Vol
ifeq ($(BCM_NONVOL_SUPPORT),1)
  ADDED_CFLAGS   += -DBCM_NONVOL_SUPPORT=1
  BCM_NONVOLDEV_SUPPORT=1
endif

# Forwarder
BCM_FORWARDER_SUPPORT=0

# Operating System 
BCM_MSGQ_SUPPORT=1

# HAL Support
BCM_BASICHALIF_SUPPORT=0
BCM_IPHALIF_SUPPORT=0
ENET_HAL_INCLUDED=0

# Program Store
BCM_PROGRAMSTORE_SUPPORT=0

# Miscellaneous
BCM_LOGO_SUPPORT=1


ifeq ($(BCM_BASICHALIF_SUPPORT),1)
  DSGCC_OBJS     += HalIf.o HalIfFactory.o NiHalIf.o Snoop.o \
                    PacketLoggingSnoop.o InterfaceCounters.o \
                    PacketSwitchBridgingHalIf.o
  ADDED_CFLAGS   += -DBCM_BASICHALIF_SUPPORT=1
endif

ifeq ($(BPI_SUPPORT_HARDWARE),1)
  DSGCC_OBJS     += SecureHalIf.o                         
endif

ifeq ($(BCM_IPHALIF_SUPPORT),1)
  DSGCC_OBJS     += BaseIpHalIf.o $(OS_PREFIX)IpHalIf.o IpStackManager.o \
                    IpRoutingFilterSnoop.o
  ADDED_CFLAGS   += -DBCM_IPHALIF_SUPPORT=1
endif

ifeq ($(USB_HAL_INCLUDED),1)
  DSGCC_OBJS     += UsbNiHalIf.o
  ADDED_CFLAGS   += -DUSB_HAL_INCLUDED=1
endif

ifeq ($(ENET_HAL_INCLUDED),1)
  DSGCC_OBJS     += EthernetNiHalIf.o
  ADDED_CFLAGS   += -DENET_HAL_INCLUDED=1
endif

ifeq ($(HPNA_HAL_INCLUDED),1)
  DSGCC_OBJS     += HpnaNiHalIf.o
  ADDED_CFLAGS   += -DHPNA_HAL_INCLUDED=1
endif

ifeq ($(BCM_SOCKET_SUPPORT),1)
  DSGCC_OBJS     += BcmSocket.o $(OS_PREFIX)Socket.o SocketFactory.o SocketSet.o 
  ADDED_CFLAGS   += -DBCM_SOCKET_SUPPORT=1
endif

ifeq ($(BCM_PING_SUPPORT),1)
  DSGCC_OBJS     += PingThread.o  
  ADDED_CFLAGS   += -DBCM_PING_SUPPORT=1
endif

ifeq ($(BCM_DHCPC_SUPPORT),1)
  ADDED_CFLAGS   +=  -DBCM_DHCPC_SUPPORT=1
endif

ifeq ($(MANAGE_SWITCH_INCLUDED),1)
  DSGCC_OBJS     += ManageSwitchSnoop.o EthManageSwitchInterfaceCounters.o 
  ADDED_CFLAGS   += -DMANAGED_SWITCH_INCLUDED=1
endif

#DPullen - I don't think we can add/remove this conditionally
#because the IP stacks require it.  Maybe this just needs to
#be carried along with BCM_IPHALIF_SUPPORT...
ifeq ($(BCM_V2_DHCP_SUPPORT),1)
  DSGCC_OBJS     +=  DhcpLeaseSettings.o \
        DhcpPacket.o \
        DhcpClientId.o \
        DhcpClientLease.o \
        DhcpClientIf.o \
        DhcpClientThread.o \
        DhcpClientSnoop.o \
	DhcpOptionsRfc2132.o
  ADDED_CFLAGS   +=  -DBCM_V2_DHCP_SUPPORT=1
endif

ifeq ($(BCM_TOD_SUPPORT),1)
  DSGCC_OBJS     +=  TimeOfDayThread.o
  ADDED_CFLAGS   +=  -DBCM_TOD_SUPPORT=1
endif

ifeq ($(BCM_TFTP_SUPPORT),1)
  DSGCC_OBJS     +=  $(OS_PREFIX)Tftp.o Tftp.o
  ADDED_CFLAGS   +=  -DBCM_TFTP_SUPPORT=1
endif


ifeq ($(BCM_TELNET_SUPPORT),1)
  DSGCC_OBJS     += TelnetThread.o TelnetThreadIpStackEventACT.o
  ADDED_CFLAGS   +=  -DBCM_TELNET_SUPPORT=1
endif

ADDED_CFLAGS   +=  -DBCM_KERBEROS_SUPPORT=$(BCM_KERBEROS_SUPPORT)






############################################################################
##                 CONSOLE SUPPORT  
############################################################################
ifeq ($(BCM_CONSOLE_SUPPORT),1)
DSGCC_OBJS +=  TerminalConsoleThread.o \
        $(OS_PREFIX)TerminalConsoleThread.o \
        ConsoleThread.o \
        Command.o \
        CommandTable.o \
        MainCommandTable.o  \
        BuiltInCommandTable.o \
        BitmaskCommandParameter.o \
        BoolCommandParameter.o \
        FlagCommandParameter.o \
        IpAddressCommandParameter.o \
        MacAddressCommandParameter.o \
        SignedIntCommandParameter.o \
        StringCommandParameter.o \
        UnsignedIntCommandParameter.o \
        CommandParameter.o \
        CommandParameterList.o \
        StringSetCommandParameter.o \
        FloatCommandParameter.o

ifeq ($(BCM_TELNET_SUPPORT),1)
  ifeq "$(TARGETOS)" "vxWorks"
    DSGCC_OBJS += VxRemoteTerminalConsoleThread.o
  endif
endif

ifeq ($(BCM_CONSOLE_SUPPORT),1)
  DSGCC_OBJS +=  CallTraceCommandTable.o \
        MsgLogSettingsCommandTable.o  
		

   ifeq ($(BCM_NONVOL_SUPPORT),1)  
	  DSGCC_OBJS +=  CmAppCompositeNonVolCommandTable.o \
					 CmAppNonVolCommandTable.o \
					 NonVolSettingsCommandTable.o
	endif
          
  ifeq ($(BCM_BASICHALIF_SUPPORT),1)
    DSGCC_OBJS += HalIfNonVolSettingsCommandTable.o \
        SnoopCommandTable.o
  endif
                     
  ifeq ($(ENET_HAL_INCLUDED),1)
    DSGCC_OBJS     += EnetHalCommandTable.o    
  endif
  
  ifeq ($(WIFI80211_HAL_INCLUDED),1)
    DSGCC_OBJS     += WiFi80211CommandTable.o    
  endif
  
  ifeq ($(USB_HAL_INCLUDED),1)
    DSGCC_OBJS     += UsbHalCommandTable.o     
  endif
  
  ifeq ($(HPNA_HAL_INCLUDED),1)
    DSGCC_OBJS     += HpnaHalCommandTable.o     
  endif
  
  ifeq ($(BCM_IPHALIF_SUPPORT),1)
    DSGCC_OBJS     += IpHalCommandTable.o     
  endif
  
  ifeq ($(BCM_FORWARDER_SUPPORT),1)
    DSGCC_OBJS     += ForwarderCommandTable.o     
  endif
  
  ifeq ($(BCM_TELNET_SUPPORT),1)
    DSGCC_OBJS     += RemoteAccessCommandTable.o
  endif
  
  ifeq ($(BCM_PACKET_GENERATOR_SUPPORT),1)
    DSGCC_OBJS     += PacketGeneratorHalCommandTable.o     
  endif
  
  ifeq ($(BCM_PING_CONSOLE_SUPPORT),1)
    DSGCC_OBJS     += PingCommandTable.o 
    ADDED_CFLAGS   += -DBCM_PING_CONSOLE_SUPPORT=1
  endif
  
  ADDED_CFLAGS   +=  -DBCM_CONSOLE_SUPPORT=1 

endif
endif

############################################################################
##                 END CONSOLE SUPPORT  
############################################################################

ifeq ($(BCM_NONVOL_SUPPORT),1)
  DSGCC_OBJS     +=  CmAppCompositeNonVolSettings.o \
        CmAppNonVolSettings.o \
        CompositeNonVolSettings.o \
        UnrecognizedNonVolSettings.o \
        NonVolSettings.o 
  ADDED_CFLAGS   += -DBCM_NONVOL_SUPPORT=1
endif

ifeq ($(BCM_FORWARDER_SUPPORT),1)
  DSGCC_OBJS     += PacketSwitch.o \
        Forwarder.o
  ADDED_CFLAGS   += -DBCM_FORWARDER_SUPPORT=1
endif

ifeq ($(BCM_MSGQ_SUPPORT),1)
  DSGCC_OBJS     += MessageQueue.o \
        $(OS_PREFIX)MessageQueue.o 
  ADDED_CFLAGS   += -DBCM_MSGQ_SUPPORT=1
endif


ifeq ($(BCM_PROGRAMSTORE_SUPPORT),1)
  DSGCC_OBJS += ProgramStoreDevice.o \
        ProgramStoreDeviceDriverBridge.o \
        BootloaderStoreDevice.o \
        BootloaderStoreDeviceDriverBridge.o
  ADDED_CFLAGS   += -DBCM_PROGRAMSTORE_SUPPORT=1
  ADDED_CFLAGS   += -DPROGRAM_STORE_SIGNATURE=$(PROGRAM_STORE_SIGNATURE)
endif

ifeq ($(BCM_NONVOLDEV_SUPPORT),1)
  DSGCC_OBJS     +=  NonVolDevice.o \
		     NonVolSettingsAccessLock.o
  ADDED_CFLAGS   += -DBCM_NONVOLDEV_SUPPORT=1
endif

ifeq ($(BCM_LOGO_SUPPORT),1)
  DSGCC_OBJS     +=  CompanyLogo.o  
  ADDED_CFLAGS   += -DBCM_LOGO_SUPPORT=1
endif

ifeq ($(BCM_PACKET_GENERATOR_SUPPORT),1)
  DSGCC_OBJS     += PacketGeneratorThread.o \
        PacketGeneratorHalIf.o 
  ADDED_CFLAGS    += -DBCM_PACKET_GENERATOR_SUPPORT=1
endif

############################################################################
##                 END V2 COMPONENT INCLUDES 
############################################################################


