
obj-y += db_svc_idmanager.o
obj-y += db_svc_table.o

obj-y += db_svc_antenna.o
obj-y += db_svc_group.o
obj-y += db_svc_network.o
obj-y += db_svc_provider.o
obj-y += db_svc_service.o
obj-y += db_svc_transponder.o
obj-y += db_svc_bouquet.o

obj-y += db_svc_manager.o
obj-y += db_svc_svcprech.o
obj-y += db_svc.o

# Basic include path

# Additional include path
ccflags-y += -I$(OCTO_DB_DIR)/include_plugin
ccflags-y += -I$(OCTO_DB_DIR)/local_include
ccflags-y += -I$(OCTO_DB_DIR)/svcmanager/local_include


