#
obj-y += tmbslTDA18275.o
obj-y += tmbslTDA18275_Instance.o
obj-y += tmbslTDA18275_RegDef.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18275/inc
#inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18275/tmbslTDA18275/inc
#inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18275/tmbslTDA18275/cfg

#obj-y += SemcoAPI_TDA18275.o
