obj-y									+= init/
obj-y									+= antenna/
obj-y									+= actionmanager/
obj-y									+= time/
obj-y									+= cas/
obj-y									+= live/
obj-y									+= epg/
obj-$(CONFIG_MW_MM_PVR)					+= recorder/
obj-$(CONFIG_MW_MM_PVR)					+= playback/
obj-$(CONFIG_MW_MM_PVR)					+= pvr/
obj-$(CONFIG_MW_MM_PVR)					+= satip/
obj-$(CONFIG_HOMMA_RC)					+= remotecontrol/
obj-$(CONFIG_MW_MM_PVR)					+= ntls/
obj-y									+= search/
obj-y									+= swup/
#obj-y									+= download/

obj-$(CONFIG_MW_MM_TRANSCODING)			+= transcoder/
obj-$(CONFIG_APCORE_EMM_UPDATE)			+= emmupdate/
obj-$(CONFIG_MW_INET_SNMP)				+= snmp_mib/
obj-$(CONFIG_MW_MM_MEDIA)						+= media/
obj-y									+= coldboot/
obj-y									+= frontcontrol/
obj-y									+= setting/
obj-y									+= tplist/
obj-y									+= spec/
obj-y									+= parentalguidance/
obj-y									+= svclist/
obj-y									+= output/
obj-y									+= schedule/
obj-y									+= models/

obj-$(CONFIG_MW_DYNAMIC_UPDATE)			+= dynamicupdate/
obj-y									+= epgbgtracking/
obj-$(CONFIG_MW_EPG_GATHERING)			+= epggathering/
obj-y									+= liveota/
obj-$(CONFIG_MW_SATRECORD)				+= satrecord/
obj-y									+= param/
obj-y									+= copyrightcontrol/

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

