# set space
SPACE :=
SPACE +=

TOOLCHAIN_VERSION=$(shell echo $(CONFIG_TOOLCHAIN_PATH) | cut -f 2 -d "-")
TOOLCHAIN_MAJOR=$(shell echo $(TOOLCHAIN_VERSION) | cut -f 1 -d ".")
TOOLCHAIN_MINOR=$(shell echo $(TOOLCHAIN_VERSION) | cut -f 2 -d ".")

ifeq ($(CONFIG_ARM),y)
B_REFSW_ARCH=arm-linux
else
ifeq ($(CONFIG_MIPS),y)
ifeq ($(CONFIG_OS_UCOS),y)
# Mips and uC/OS doesn't use B_REFSW_ARCH.
else
B_REFSW_ARCH=mipsel-linux
endif
endif
endif

BCM_FIX	= HUMAX_PLATFORM_BASE	#Default Define

NEXUS_TOP=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus
-include $(NEXUS_TOP)/../bcm_environment.config

DEVICE_CONFIG_DIR := $(HUMAX_WORK_DIR)/product_config/platform/sdk/driver
FLASHMAP_CONFIG_DIR := $(HUMAX_WORK_DIR)/product_config/flashmap
RAMMAP_CONFIG_DIR := $(HUMAX_WORK_DIR)/product_config/rammap

KERNEL_CONFIG_DIR := $(HUMAX_PRODUCT_CONFIG_DIR)/platform/sdk/os/kernel
ROOTFS_CONFIG_DIR := $(HUMAX_PRODUCT_CONFIG_DIR)/platform/sdk/os/rootfs
KERNEL_DIR := $(HUMAX_WORK_DIR)/platform/sdk/os/kernel
ROOTFS_DIR := $(HUMAX_WORK_DIR)/platform/sdk/os/rootfs

PROVISIONING_TOOL_DIR := $(HUMAX_WORK_DIR)/platform/sdk/sagesw/provisioningtool
SAGESW_MAINAPP_DIR := $(HUMAX_WORK_DIR)/platform/sdk/sagesw/main

HUMAX_DRIVER_AUTOCONF=$(HUMAX_MAKE_DIR)/$(CONFIG_PRODUCT_NAME)/autoconf.h

NEXUS_CONFIG := BCM_FIX="$(strip $(BCM_FIX))"
NEXUS_CONFIG += INC_AUTOCONF=$(HUMAX_DRIVER_AUTOCONF)
NEXUS_CONFIG += HUMAX_PLATFORM_BASE=y
NEXUS_CONFIG += LINUX=$(KERNEL_DIR)
NEXUS_CONFIG += LINUX_INC=$(KERNEL_DIR)/include
NEXUS_CONFIG += PLATFORM=$(PLATFORM)
NEXUS_CONFIG += BCHP_VER=$(BCHP_VER)
NEXUS_CONFIG += $(subst CONFIG_BRCM_MOD_,,$(shell cat $(HUMAX_PLATFORM_CONFIG_DIR)/.config | grep "^CONFIG_BRCM_MOD"))
NEXUS_CONFIG += $(subst $(SPACE)is not set,=n,$(subst \# CONFIG_BRCM_MOD_,,$(shell cat $(HUMAX_PLATFORM_CONFIG_DIR)/.config | grep "^\#\ CONFIG_BRCM_MOD")))
NEXUS_CONFIG += $(subst CONFIG_BRCM_PATCH_,,$(shell cat $(HUMAX_PLATFORM_CONFIG_DIR)/.config | grep "^CONFIG_BRCM_PATCH"))
NEXUS_CONFIG += $(subst $(SPACE)is not set,=n,$(subst \# CONFIG_BRCM_PATCH_,,$(shell cat $(HUMAX_PLATFORM_CONFIG_DIR)/.config | grep "^\#\ CONFIG_BRCM_PATCH")))

ifneq ($(B_REFSW_ARCH),)
NEXUS_CONFIG += B_REFSW_ARCH=$(B_REFSW_ARCH)
endif

ifneq ($(B_REFSW_OS),)
NEXUS_CONFIG += B_REFSW_OS=$(B_REFSW_OS)
endif

ifeq ($(CONFIG_BCM_UART),y)
NEXUS_CONFIG+=CONFIG_BCM_UART=y
endif

ifneq ($(CONFIG_BCM_GRAPHICS3D),)
NEXUS_CONFIG += V3D_SUPPORT=y
else
NEXUS_CONFIG += V3D_SUPPORT=n
endif

ifneq ($(CONFIG_CABLE_MODEM),)
ifeq ($(PLATFORM),97445)
ifeq ($(CONFIG_PLATFORM_DB3383),y)
NEXUS_CONFIG += NEXUS_USE_7445_VMS_SFF=y
NEXUS_CONFIG += NEXUS_PLATFORM_7445_CABLE=y
NEXUS_CONFIG += NEXUS_FRONTEND_3383=y
NEXUS_CONFIG += NEXUS_PLATFORM_DOCSIS_OOB_SUPPORT=y
NEXUS_CONFIG += NEXUS_PLATFORM_DOCSIS_IB_SUPPORT=y
endif
else ifeq ($(PLATFORM),97425)
NEXUS_CONFIG += NEXUS_PLATFORM_7425_CABLE=y
NEXUS_CONFIG += NEXUS_ENABLE_7425_CABLE=y
NEXUS_CONFIG += NEXUS_USE_7425_VMS_SFF=y
NEXUS_CONFIG += NEXUS_PLATFORM_DOCSIS_OOB_SUPPORT=y
NEXUS_CONFIG += NEXUS_PLATFORM_DOCSIS_IB_SUPPORT=y
endif
NEXUS_CONFIG += RAP_DRA_SUPPORT=y
NEXUS_CONFIG += RAP_DTSHD_SUPPORT=y
NEXUS_CONFIG += RAP_DTSBROADCAST_SUPPORT=y
NEXUS_CONFIG += BCM_FIX="HUMAX_PLATFORM_BASE FIX_MAD_BOUNDARY HUMAX_PLATFORM_TRINITY"
endif

ifneq ($(CONFIG_MEDIA20),)
NEXUS_CONFIG += CONFIG_MEDIA20=y
endif

ifneq ($(CONFIG_PLAYREADY_25),)
NEXUS_CONFIG += CONFIG_PLAYREADY_25=y
ifeq ($(CONFIG_SECURITY_EXTENSION),y)
NEXUS_CONFIG += CONFIG_SECURITY_EXTENSION=y
endif
endif

ifeq ($(CONFIG_OS_LINUX),y)
ifeq ($(CONFIG_DEVICE_MODE_KERNEL),y)
NEXUS_CONFIG += MODE=proxy
endif
endif

ifeq ($(CONFIG_CALYPSO),y)
NEXUS_CONFIG += CONFIG_CALYPSO=y
endif

BCM_CHIP=$(shell echo $(PLATFORM) | sed 's/.\(.*\)/\1/')

# Enable OTPMSP
ifeq ($(shell expr $(NEXUS_SECURITY_TREE) "<" SECURITY_TREE_1401),1)
NEXUS_CONFIG += BHSM_OTPMSP=ON
NEXUS_CONFIG += BHSM_KEYLADDER=ON
endif
ifneq ($(CONFIG_CAS_NAME),)
NEXUS_CONFIG += CUST=$(CONFIG_CAS_NAME)
else
NEXUS_CONFIG += CUST=GENERIC3A
endif

ifeq ($(CONFIG_SECURITY_EXTENSION),y)
	ifeq (1, 0)
	
	else ifeq ($(shell expr $(NEXUS_SECURITY_TREE) ">=" SECURITY_TREE_1501),1)
		NEXUS_CONFIG += HSM_SOURCE_AVAILABLE=y
		NEXUS_CONFIG += NEXUS_COMMON_CRYPTO_SUPPORT=y
		NEXUS_CONFIG += AEGIS_USERCMD_SUPPORT=y
		NEXUS_CONFIG += BSP_M2M_EXT_KEY_IV_SUPPORT=ON
		NEXUS_CONFIG += NEXUS_SECURITY_HSMRAWCMD_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/rawcommand/rawcmd_ext.inc

		ifeq ($(CONFIG_TEMP_M1),y)
			NEXUS_CONFIG += OTPMSP_SUPPORT=y
			NEXUS_CONFIG += NEXUS_SECURITY_OTPMSP_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/otpmsp/otpmsp_ext.inc
		endif

		ifeq ($(CONFIG_CAS_NA_NOCS_3X),y)
			NEXUS_CONFIG += HSM_SOURCE_AVAILABLE=y
			NEXUS_CONFIG += BHSM_OTPMSP=ON
			NEXUS_CONFIG += BHSM_KEYLADDER=ON
			NEXUS_CONFIG += SECURERAWCMD_SUPPORT=y
			NEXUS_CONFIG += KEYLADDER_SUPPORT=y
			NEXUS_CONFIG += OTPMSP_SUPPORT=y
			NEXUS_CONFIG += AEGIS_USERCMD_SUPPORT=y
			NEXUS_CONFIG += USERCMD_SUPPORT=y
			NEXUS_CONFIG += OTPID_SUPPORT=y
			ifeq ($(CONFIG_CAS_NA),y)
				NEXUS_CONFIG += NEXUS_SECURITY_HSMRAWCMD_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/rawcommand/rawcmd_ext.inc
				NEXUS_CONFIG += NEXUS_SECURITY_OTPMSP_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/otpmsp/otpmsp_ext.inc
			endif
		endif

		ifeq ($(CONFIG_SECURITY_REGION_VERIFICATION),y)
			NEXUS_CONFIG += REGION_VERIFICATION_SUPPORT=y
			NEXUS_CONFIG += SECURERAWCMD_SUPPORT=y
			NEXUS_CONFIG += RAVE_REGION_VERIFICATION_SUPPORT=y
			NEXUS_CONFIG += AUDIO_REGION_VERIFICATION_SUPPORT=y
			NEXUS_CONFIG += VIDEO_REGION_VERIFICATION_SUPPORT=y
			NEXUS_CONFIG += VICE_REGION_VERIFICATION_SUPPORT=y
			NEXUS_CONFIG += SID_REGION_VERIFICATION_SUPPORT=y
			NEXUS_CONFIG += NEXUS_SECURITY_RAVE_VERIFICATION=y
			NEXUS_CONFIG += NEXUS_SECURITY_SIGNATURE_FILE_DISCRIMINATOR=$(addprefix _,$(CONFIG_PRODUCT_NAME))
			ifeq ($(CONFIG_SECURITY_REGION_VERIFICATION_DUMP_FW),y)
				NEXUS_CONFIG += NEXUS_DUMP_RAVE_BIN=ON
				NEXUS_CONFIG += NEXUS_DUMP_SID_BIN=ON
				NEXUS_CONFIG += NEXUS_DUMP_RAP_BIN=ON
				NEXUS_CONFIG += NEXUS_DUMP_AVD_BIN=ON
				NEXUS_CONFIG += NEXUS_DUMP_VICE_BIN=ON
			endif
		endif
	else ifeq ($(shell expr $(NEXUS_SECURITY_TREE) "==" SECURITY_TREE_1401),1)
		ifeq ($(CONFIG_CAS_NA_NOCS_3X),y)
			NEXUS_CONFIG += HSM_SOURCE_AVAILABLE=y
			NEXUS_CONFIG += BHSM_OTPMSP=ON
			NEXUS_CONFIG += BHSM_KEYLADDER=ON
			NEXUS_CONFIG += SECURERAWCMD_SUPPORT=y
			NEXUS_CONFIG += KEYLADDER_SUPPORT=y
			NEXUS_CONFIG += OTPMSP_SUPPORT=y
			NEXUS_CONFIG += AEGIS_USERCMD_SUPPORT=y
			NEXUS_CONFIG += USERCMD_SUPPORT=y
			NEXUS_CONFIG += OTPID_SUPPORT=y
			ifeq ($(CONFIG_CAS_NA),y)
				NEXUS_CONFIG += NEXUS_SECURITY_HSMRAWCMD_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/rawcommand/rawcmd_ext.inc
				NEXUS_CONFIG += NEXUS_SECURITY_OTPMSP_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/otpmsp/otpmsp_ext.inc
			endif
		else
			NEXUS_CONFIG += NEXUS_COMMON_CRYPTO_SUPPORT=y
			NEXUS_CONFIG += BSP_M2M_EXT_KEY_IV_SUPPORT=ON
			NEXUS_CONFIG += AEGIS_USERCMD_SUPPORT=y
			NEXUS_CONFIG += NEXUS_EXTRA_SECLIBS_FILES=libnexus_security.a
		endif
	else ifeq ($(shell expr $(NEXUS_SECURITY_TREE) ">=" SECURITY_TREE_1304),1)
		NEXUS_CONFIG += NEXUS_COMMON_CRYPTO_SUPPORT=y
		NEXUS_CONFIG += BSP_M2M_EXT_KEY_IV_SUPPORT=ON
		NEXUS_CONFIG += AEGIS_USERCMD_SUPPORT=y
		NEXUS_CONFIG += NEXUS_EXTRA_SECLIBS_FILES=libnexus_security.a
	else ifeq ($(shell expr $(NEXUS_SECURITY_TREE) ">=" SECURITY_TREE_1303),1)
		NEXUS_CONFIG += KEYLADDER_SUPPORT=y
		NEXUS_CONFIG += OTPMSP_SUPPORT=y
		NEXUS_CONFIG += USERCMD_SUPPORT=y
		ifeq ($(CONFIG_CAS_NA),y)
			NEXUS_CONFIG += NEXUS_SECURITY_HSMRAWCMD_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/rawcommand/rawcmd_ext.inc
		endif
	else ifeq ($(shell expr $(NEXUS_SECURITY_TREE) ">=" SECURITY_TREE_1290),1)
		NEXUS_CONFIG += NEXUS_SECURITY_KEYLADDER_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/keyladder/keyladder_ext.inc
		NEXUS_CONFIG += NEXUS_SECURITY_OTPMSP_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/otpmsp/otpmsp_ext.inc
		NEXUS_CONFIG += NEXUS_SECURITY_USERCMD_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/usercmd/usercmd_ext.inc
		NEXUS_CONFIG += NEXUS_SECURITY_HSMRAWCMD_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/rawcommand/rawcmd_ext.inc
	else ifeq ($(NEXUS_SECURITY_TREE), SECURITY_TREE_1000)
		NEXUS_CONFIG += NEXUS_SECURITY_KEYLADDER_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/keyladder/keyladder_ext.inc
		NEXUS_CONFIG += NEXUS_SECURITY_OTPMSP_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/otpmsp/otpmsp_ext.inc
		NEXUS_CONFIG += NEXUS_SECURITY_USERCMD_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/usercmd/usercmd_ext.inc
		ifeq ($(CONFIG_CAS_NA),y)
			NEXUS_CONFIG += HSM_SOURCE_AVAILABLE=y
			NEXUS_CONFIG += BSP_SC_VALUE_SUPPORT=ON
			NEXUS_CONFIG += BSP_M2M_EXT_KEY_IV_SUPPORT=ON
			NEXUS_CONFIG += BRCM_ROOT=/REFSW_RELEASE_97358_2012129
		endif
	else
		NEXUS_CONFIG += NEXUS_SECURITY_KEYLADDER_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/keyladder/$(BCM_CHIP)/keyladder_ext.inc
		NEXUS_CONFIG += NEXUS_SECURITY_OTPMSP_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/otpmsp/$(BCM_CHIP)/otpmsp_ext.inc
		NEXUS_CONFIG += NEXUS_SECURITY_USERCMD_EXTENSION_INC=$(HUMAX_WORK_DIR)/platform/sdk/driver/nexus/extensions/security/usercmd/$(BCM_CHIP)/usercmd_ext.inc
	endif
endif

ifneq ($(CONFIG_PVR),y)
NEXUS_CONFIG+=NEXUS_FILE_SUPPORT=n
NEXUS_CONFIG+=NEXUS_PLAYBACK_SUPPORT=n
NEXUS_CONFIG+=NEXUS_RECORD_SUPPORT=n
endif

ifneq ($(CONFIG_HDMI_IN),y)
NEXUS_CONFIG+=NEXUS_HDMI_INPUT_SUPPORT=n
endif

ifneq ($(CONFIG_TRANSCODER),y)
NEXUS_CONFIG+=NEXUS_VIDEO_ENCODER_SUPPORT=n
NEXUS_CONFIG+=NEXUS_STREAM_MUX_SUPPORT=n
NEXUS_CONFIG+=NEXUS_FILE_MUX_SUPPORT=n
else
NEXUS_CONFIG+=VIDEO_ENCODER_SUPPORT=y
endif

ifneq ($(CONFIG_HDMI_CEC),y)
NEXUS_CONFIG+=NEXUS_CEC_SUPPORT=n
endif

ifneq ($(CONFIG_SMARTCARD),y)
NEXUS_CONFIG+=NEXUS_SMARTCARD_SUPPORT=n
endif

ifneq ($(CONFIG_AUDIO_DECODER),y)
NEXUS_CONFIG+=NEXUS_AUDIO_SUPPORT=n
NEXUS_CONFIG+=NEXUS_SYNC_CHANNEL_SUPPORT=n
NEXUS_CONFIG+=NEXUS_ASTM_SUPPORT=n
NEXUS_CONFIG+=NEXUS_SIMPLE_DECODER_SUPPORT=n
endif

ifneq ($(CONFIG_VIDEO_DECODER),y)
ifeq ($(CONFIG_OS_UCOS),y)
NEXUS_CONFIG+=NEXUS_VIDEO_DECODER_SUPPORT=n
else
#NEXUS_CONFIG+=NEXUS_VIDEO_DECODER_SUPPORT=n
endif
NEXUS_CONFIG+=NEXUS_PICTURE_DECODER_SUPPORT=n
endif

ifneq ($(CONFIG_VIDEO_DISPLAY),y)
NEXUS_CONFIG+=NEXUS_HDMI_OUTPUT_SUPPORT=n
NEXUS_CONFIG+=NEXUS_HDMI_DVO_SUPPORT=n
NEXUS_CONFIG+=NEXUS_SURFACE_SUPPORT=n
NEXUS_CONFIG+=NEXUS_DISPLAY_SUPPORT=n
NEXUS_CONFIG+=NEXUS_GRAPHICS2D_SUPPORT=n
NEXUS_CONFIG+=NEXUS_SURFACE_COMPOSITOR_SUPPORT=n
endif

ifneq ($(CONFIG_CRYPTO),y)
ifneq ($(CONFIG_HDCP),y)
ifneq ($(CONFIG_DSC),y)
NEXUS_CONFIG+=NEXUS_SECURITY_SUPPORT=n
endif
endif
endif

ifeq ($(CONFIG_HDCP_22),y)
NEXUS_CONFIG+=SAGE_SUPPORT=y
endif

ifeq ($(CONFIG_BRCM_MOD_MSDRM_PRDY_25_SUPPORT),y)
NEXUS_CONFIG+=MSDRM_PRDY_SDK_VERSION="2.5"
NEXUS_CONFIG+=MSDRM_PRDY_SUPPORT=y
endif


#ifneq ($(CONFIG_XXX),y)
#NEXUS_CONFIG+=NEXUS_TRANSPORT_SUPPORT=n
#NEXUS_CONFIG+=NEXUS_DMA_SUPPORT=n
#NEXUS_CONFIG+=NEXUS_INPUT_ROUTER_SUPPORT=n
#NEXUS_CONFIG+=NEXUS_UART_SUPPORT=n
#endif

#ifeq ($(CONFIG_ABCD),y)
#NEXUS_CONFIG+=V3D_SUPPORT=y
#NEXUS_CONFIG+=NSK2_SUPPORT=y
#NEXUS_CONFIG+=NSK2_EMM_SUPPORT=y
#NEXUS_CONFIG+=NSK2_ECM_SUPPORT=y
#NEXUS_CONFIG+=NSK2_SMARTCARD_SUPPORT=y
#NEXUS_CONFIG+=NEXUS_DVB_CI_SUPPORT=y
#NEXUS_CONFIG+=NEXUS_TOUCHPAD_SUPPORT=y
#NEXUS_CONFIG+=NEXUS_TEMP_MONITOR_SUPPORT=y
#NEXUS_CONFIG+=MSDRM_PRDY_SUPPORT=y
#NEXUS_CONFIG+=GL_SUPPORT=y
#NEXUS_CONFIG+=SAGE_SUPPORT=y
#NEXUS_CONFIG+=NEXUS_MPOD_SUPPORT=y
#endif


#ifeq ($(CONFIG_LXC),y)
#NEXUS_CONFIG += NEXUS_WEBCPU=y
#endif

ifeq ($(CONFIG_OS_UCOS),y)
NEXUS_CONFIG += NEXUS_SERVER_SUPPORT=n
endif

# parse the Linux Makefile
LINUX_VERSION = $(shell grep -m 1 '^VERSION = ' $(KERNEL_DIR)/Makefile | awk '{print $$3}')
LINUX_PATCHLEVEL = $(shell grep -m 1 '^PATCHLEVEL = ' $(KERNEL_DIR)/Makefile | awk '{print $$3}')
LINUX_SUBLEVEL = $(shell grep -m 1 '^SUBLEVEL = ' $(KERNEL_DIR)/Makefile | awk '{print $$3}')
LINUX_EXTRAVERSION = $(shell grep -m 1 '^EXTRAVERSION = ' $(KERNEL_DIR)/Makefile | awk '{print $$3}')

KERNELRELEASE=`cat $(HUMAX_WORK_DIR)/platform/sdk/os/kernel/include/config/kernel.release | awk '{ print $1 }'`
NEXUS_MOD_PREFIX=lib/modules/$(KERNELRELEASE)/bcm$(BCM_CHIP)

ifeq ($(shell expr $(NEXUS_TREE) ">=" TREE_1303),1)
	NEXUS_OBJ_DIR = $(NEXUS_TOP)/../obj.$(PLATFORM)/BSEAV/linux/driver/usermode
else
	NEXUS_OBJ_DIR = $(HUMAX_WORK_DIR)/platform/sdk/driver/BSEAV/linux/driver/build/$(PLATFORM)
endif

ifeq ($(shell expr $(NEXUS_TREE) ">=" TREE_1401),1)
	NEXUS_UMDRIVER_DIR = $(HUMAX_WORK_DIR)/platform/sdk/driver/BSEAV/linux/driver/build
else
	NEXUS_UMDRIVER_DIR = $(HUMAX_WORK_DIR)/platform/sdk/driver/BSEAV/linux/driver/build/$(PLATFORM)
endif

ifeq ($(CONFIG_DEVICE_MODE_USER),y)
	ifeq ($(CONFIG_PRODUCT_DEVICE_DEBUG_LOG),y)
		NEXUS_MOD = $(NEXUS_OBJ_DIR)/$(B_REFSW_ARCH).debug/bcmdriver.ko
	else
		NEXUS_MOD = $(NEXUS_OBJ_DIR)/$(B_REFSW_ARCH).release/bcmdriver.ko
	endif
else
	NEXUS_MOD = $(NEXUS_TOP)/bin/nexus.ko
endif

ifeq ($(shell expr $(NEXUS_TREE) ">=" TREE_1501),1)
ifeq ($(CONFIG_ARM),y)
	ifeq ($(CONFIG_DEVICE_MODE_USER),y)
		ifeq ($(CONFIG_PRODUCT_DEVICE_DEBUG_LOG),y)
			NEXUS_MOD += $(NEXUS_OBJ_DIR)/../wakeup/$(B_REFSW_ARCH).debug/wakeup_drv.ko
		else
			NEXUS_MOD += $(NEXUS_OBJ_DIR)/../wakeup/$(B_REFSW_ARCH).release/wakeup_drv.ko
		endif
	else
		NEXUS_MOD += $(NEXUS_TOP)/bin/wakeup_drv.ko
	endif
endif
endif

ifeq ($(CONFIG_DEVICE_LIB_STATIC),y)
SHAREABLE :=n
export SHAREABLE
NEXUS_LIB := $(NEXUS_TOP)/bin/libnexus.a $(NEXUS_TOP)/bin/libmagnum.a
else
NEXUS_LIB := $(NEXUS_TOP)/bin/libnexus.so
ifeq ($(CONFIG_DEVICE_MODE_USER),y)
ifeq ($(CONFIG_PRODUCT_IMAGE_OCTO),y)
else
NEXUS_LIB += $(NEXUS_TOP)/bin/libnexus_client.so
endif
endif
endif

ifeq ($(CONFIG_CAS_NA),y)
NEXUS_NOCS_LIB = $(NEXUS_TOP)/bin/libnocs.a
endif

ifeq ($(CONFIG_CAS_BCSD),y)
NEXUS_BCSD_LIB = $(NEXUS_TOP)/bin/libbcsd.a
endif

################################################################################

TARGET_CONFIG	:= \
		CROSS=$(HUMAX_CROSS) \
		AR=$(HUMAX_CROSS)ar \
		LD=$(HUMAX_CROSS)ld \
		NM=$(HUMAX_CROSS)nm \
		CC=$(HUMAX_CROSS)gcc \
		GCC=$(HUMAX_CROSS)gcc \
		CXX=$(HUMAX_CROSS)g++ \
		RANLIB=$(HUMAX_CROSS)ranlib \
		STRIP=$(HUMAX_CROSS)strip
UCLIBC_DIR := $(HUMAX_UCLIBC_OLD_DIR)/sys-root
UCLIBC_OLD_DIR := $(HUMAX_UCLIBC_OLD_DIR)
UCLIBC := $(UCLIBC_DIR)/lib/ld-uClibc* \
		$(UCLIBC_DIR)/lib/libuClibc*.so \
		$(UCLIBC_DIR)/lib/libubacktrace*.so* 
ifeq ($(shell expr $(TOOLCHAIN_MAJOR) ">" 4),1)
UCLIBC := $(UCLIBC_DIR)/lib/ld-* \
		$(UCLIBC_DIR)/lib/libc-2.18* \
		$(UCLIBC_DIR)/lib/libnss_dns*so* \
		$(UCLIBC_DIR)/lib/libnss_files*so* \
		$(UCLIBC_DIR)/lib/libresolv*so*
else
	ifeq ($(shell expr $(TOOLCHAIN_MAJOR) "==" 4),1)
		ifeq ($(shell expr $(TOOLCHAIN_MINOR) ">=" 8),1)
			UCLIBC := $(UCLIBC_DIR)/lib/ld-* \
			$(UCLIBC_DIR)/lib/ld.so.* \
			$(UCLIBC_DIR)/lib/libc-2.18* \
			$(UCLIBC_DIR)/lib/libnss_dns*so* \
			$(UCLIBC_DIR)/lib/libnss_files*so* \
			$(UCLIBC_DIR)/lib/libresolv*so*

		endif
	endif
endif	
	UCLIBC += $(UCLIBC_OLD_DIR)/lib/libgcc_s.so* \
	$(UCLIBC_DIR)/lib/libcrypt*.so*\
	$(UCLIBC_DIR)/lib/libdl*so*\
	$(UCLIBC_DIR)/lib/libnsl*so*\
	$(UCLIBC_DIR)/lib/libc.so*\
	$(UCLIBC_DIR)/lib/libm*.so*\
	$(UCLIBC_DIR)/lib/libpthread*.so*\
	$(UCLIBC_DIR)/lib/librt*.so*\
	$(UCLIBC_DIR)/lib/libthread_db*.so*\
	$(UCLIBC_OLD_DIR)/lib/libssp*.so*

ifeq ($(CONFIG_PRODUCT_IMAGE_DEBUG),y)
ifeq ($(CONFIG_ASAN),y)
	UCLIBC +=$(UCLIBC_OLD_DIR)/lib/libasan*.so*
endif
endif

ifeq ($(CONFIG_LXC),y)
	UCLIBC += $(UCLIBC_DIR)/lib/libutil*.so*
endif

UCLIBC_STRIP := $(UCLIBC_OLD_DIR)/lib/libstdc++*.so*

ifeq ($(CONFIG_PRODUCT_IMAGE_DEBUG),y)
CFLAGS_KERNEL = -DHUMAX_PLATFORM_BASE -DHUMAX_PLATFORM_DEBUG
else ifeq ($(CONFIG_PRODUCT_IMAGE_HWTEST),y)
CFLAGS_KERNEL = -DHUMAX_PLATFORM_BASE -DHUMAX_PLATFORM_DEBUG
else
CFLAGS_KERNEL = -DHUMAX_PLATFORM_BASE -DHUMAX_PLATFORM_RELEASE
endif

-include $(HUMAX_MAKE_DIR)/.crc_config
ifeq ($(CONFIG_PRODUCT_IMAGE_HWTEST),y)
ifeq ($(CONFIG_CRC_AUTOTEST),y)
CFLAGS_KERNEL += -DCONFIG_CRC_AUTOTEST
endif
endif
-include $(HUMAX_MAKE_DIR)/.mem_config
ifeq ($(CONFIG_PRODUCT_IMAGE_HWTEST),y)
ifeq ($(CONFIG_MEM_AUTOTEST),y)
CFLAGS_KERNEL += -DCONFIG_MEM_AUTOTEST
endif
endif

CFLAGS_MODULE = $(CFLAGS_KERNEL)
CFLAGS_MODULE += -DMODULE

ifeq ($(CONFIG_SERIAL_PORT),y)
SERIAL_PORT_NUMBER = $(subst ",,$(strip $(CONFIG_SERIAL_PORT_NUMBER)))#")
CFLAGS_KERNEL += -DCONFIG_TTY_NUM=$(SERIAL_PORT_NUMBER)
else
CFLAGS_KERNEL += -DCONFIG_TTY_NUM=2
endif

ifneq ($(subst OS_MEM_120M,,$(CONFIG_MODULE_NAME)), $(CONFIG_MODULE_NAME))
CFLAGS_KERNEL += -DOS_MEM_120M
endif

ifneq ($(CONFIG_PRODUCT_DI_DEBUG_LOG),)
else ifneq ($(CONFIG_PRODUCT_IMAGE_FACTORY),)
else
CFLAGS_KERNEL += -DCONFIG_DISABLE_ALL_TRACE_IN_CONSOLE
endif

HUMAX_MODIFY_KERNEL = CFLAGS_KERNEL="$(CFLAGS_KERNEL)"
HUMAX_MODIFY_MODULE = CFLAGS_MODULE="$(CFLAGS_MODULE)"


################################################################################

ifeq ($(CONFIG_OS_UCOS),y)
NEXUS_BSU_CONFIG := BCM_FIX="$(strip $(BCM_FIX))"
NEXUS_BSU_CONFIG += INC_AUTOCONF=$(HUMAX_DRIVER_AUTOCONF)
NEXUS_BSU_CONFIG += LINUX=$(KERNEL_DIR)
NEXUS_BSU_CONFIG += LINUX_INC=$(KERNEL_DIR)/include
NEXUS_BSU_CONFIG += PLATFORM=$(PLATFORM)
NEXUS_BSU_CONFIG += BCHP_VER=$(BCHP_VER)
NEXUS_BSU_CONFIG += TOOLCHAIN_PATH=$(CONFIG_BSU_TOOLCHAINS)
#NEXUS_BSU_CONFIG += HUMAX_PLATFORM_BASE=y

BOOTLOADER_CONFIG := HUMAX_PLATFORM_BASE=y

ifeq ($(CONFIG_PRODUCT_IMAGE_DEBUG),y)
BOOTLOADER_CONFIG += HUMAX_PLATFORM_DEBUG=y
else
BOOTLOADER_CONFIG += HUMAX_PLATFORM_RELEASE=y
endif


ifeq ($(CONFIG_ARM),y)
BOOTLOADER_CONFIG += CFG=$(HUMAX_PRODUCT_CONFIG_DIR)/bootloader/bolt/platform.cfg

BOOTLOADER_TARGET = BOLT

BOOTLOADER_BUILD_COMMAND = $(CONFIG_CHIP)$(shell awk 'BEGIN{print tolower("$(BCHP_VER)")}')

NEXUS_BSU_CONFIG += B_REFSW_ARCH=$(B_REFSW_ARCH)
NEXUS_BSU_CONFIG += NEXUS_PLATFORM=$(PLATFORM)
NEXUS_BSU_CONFIG += BCHP_CHIP=$(BCM_CHIP)
else
ifeq ($(CONFIG_MIPS),y)
BOOTLOADER_CONFIG += $(CONFIG_BOOTLOADER_BUILD_OPT)
BOOTLOADER_CONFIG += TOOLCHAIN_PATH=$(CONFIG_BOOTLOADER_TOOLCHAINS)

BOOTLOADER_TARGET = CFE$(CONFIG_BOOTLOADER_BUILD_DIR)

BOOTLOADER_BUILD_COMMAND = $(BOOTLOADER_CFE_BUILD_OPT)

NEXUS_BSU_CONFIG += NEXUS_PLATFORM=$(PLATFORM)
NEXUS_BSU_CONFIG += BCHP_CHIP=$(BCM_CHIP)
NEXUS_BSU_CONFIG += TOOLCHAIN_PATH=/opt/toolchains/sde5
endif
endif
endif


