obj-y += otl_log_report.o

###################################
# OCTO flags & include dirs
###################################

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.pal
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.dlna

# Additional include path
