# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =       \
    baseimpl    \
    base        \
    hsm         \

include $(PLAYREADY_DIR)/GNUmakefile.common

