obj-y += base/
obj-y += models/

obj-y	+= psvc_epg.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
#include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path
ccflags-y += -I$(OCTO_TVSERVICE_DIR)/svc/epg/local_include

