#!/bin/bash

# - File:   makenetsnmplibs.bat
# - Author: T Clack

if [ "$1" == "clean" ] ; then
   # ====================================================================
   #	Clean The libnetsnmpagnet.a Lib
   # ====================================================================
   cd agent
   make -f makefile_brcm clean
   cd ..
   
   # ====================================================================
   #	Clean The libnetsnmphelpers.a Lib
   # ====================================================================
   cd agent/helpers
   make -f makefile_brcm clean
   cd ../..
   
   # ====================================================================
   #	Clean The libnetsnmpmibs.a Lib
   # ====================================================================
   cd agent/mibgroup
   make -f makefile_brcm clean
   cd ../.. 
    
   # ====================================================================
   #	Clean The libnetsnmp.a Lib
   # ====================================================================
   cd snmplib
   make -f makefile_brcm clean
   cd .. 
else
   # ====================================================================
   #	Make The libnetsnmpagent.a Lib
   # ====================================================================
   cd agent
   make -f makefile_brcm
   cd ..
   
   # ====================================================================
   #	Make The libnetsnmphelpers.a Lib
   # ====================================================================
   cd agent/helpers
   make -f makefile_brcm
   cd ../..
   
   # ====================================================================
   #	Make The libnetsnmpmibs.a Lib
   # ====================================================================
   cd agent/mibgroup
   make -f makefile_brcm
   cd ../.. 
    
   # ====================================================================
   #	Make The libnetsnmp.a Lib
   # ====================================================================
   cd snmplib
   make -f makefile_brcm
   cd .. 
fi

