#obj-$(CONFIG_DEBUG) += bc_nsc_provider_Test_Stream.o
#obj-$(CONFIG_DEBUG) += bc_nsc_vendor_Test_Stream.o
obj-y += bc_nsc_provider_Test_Stream.o
obj-y += bc_nsc_vendor_Test_Stream.o

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
