#!/bin/sh

. /lib/lsb/init-functions
. /etc/default/rcS
if [ "$VERBOSE" != no ]; then
	log_begin_msg "Creating LXC..."
fi

set -x

#chown settop:settop /var/lib/humaxtv
#chown settop:settop -R /var/lib/humaxtv/cas
#chown hama:hama /var/lib/humaxtv/registry.reg
#chown dama:dama /var/lib/humaxtv/dlogger/*

#newmount --make-shared /media 
#mount  --rbind /mnt /mnt
#newmount --make-rshared /mnt

mkfs.ext4 /dev/mtdblock1
mkdir -p /home/lxc/rootfs
mkdir -p /home/lxc/cache/lxc
mkdir -p /home/lxc/lib/lxc

/usr/local/bin/lxc-create -n imma -f /home/imma/config 
/usr/local/bin/lxc-create -n corsair -f /home/corsair/config 
/usr/local/bin/lxc-create -n homma -f /home/homma/config 
/usr/local/bin/lxc-create -n ipepg -f /home/ipepg/config
/usr/local/bin/lxc-create -n mheg -f /home/mheg/config

brctl addbr br0
brctl setfd br0 0
ifconfig br0 10.255.128.200 netmask 255.255.255.0 promisc up
/usr/local/sbin/iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
echo 1 > /proc/sys/net/ipv4/ip_forward

# MC Packet 
ifconfig eth0 promisc
/usr/local/sbin/smcroute -d
/usr/local/sbin/smcroute -a eth0 0.0.0.0 239.255.255.250 br0
/usr/local/sbin/smcroute -a br0 10.255.128.213 239.255.255.250 eth0

# Bonjour
/usr/local/sbin/mdns-repeater eth0 br0

# UPnP
/usr/local/sbin/iptables -t mangle -A PREROUTING -d 224.0.0.0/240.0.0.0 -j TTL --ttl-inc 1
/usr/local/sbin/iptables -t nat -A PREROUTING -p udp -i eth0 --dport dlna-start:dlna-end -j DNAT --to 10.255.128.213

#DMS
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 50001 -j DNAT --to 10.255.128.213:50001
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 9000 -j DNAT --to 10.255.128.213:9000
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 9001 -j DNAT --to 10.255.128.213:9001
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 9002 -j DNAT --to 10.255.128.213:9002

# DMP loopback error 2014-04-01
#/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i br0 --dport 9000 -j DNAT --to 10.255.128.213:9000
#/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i br0 --dport 9001 -j DNAT --to 10.255.128.213:9001
#/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i br0 --dport 9002 -j DNAT --to 10.255.128.213:9002

#DMR
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 55200 -j DNAT --to 10.255.128.213:55200

#DIAL
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 56789 -j DNAT --to 10.255.128.213:56789
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 56790 -j DNAT --to 10.255.128.213:56790

#SATIP
/usr/local/sbin/iptables -t nat -A PREROUTING -p udp -i eth0 --dport satip-ssdp -j DNAT --to 10.255.128.213:49554
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 554 -j DNAT --to 10.255.128.213:50554
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 50555 -j DNAT --to 10.255.128.213:50555

#AirPlay
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 36667 -j DNAT --to 10.255.128.213:36667
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 36666 -j DNAT --to 10.255.128.213:36666
/usr/local/sbin/iptables -t nat -A PREROUTING -p udp -i eth0 --dport airtunes-start:airtunes-end -j DNAT --to 10.255.128.211

# etc
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 80 -j DNAT --to 10.255.128.213:80
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 8080 -j DNAT --to 10.255.128.213:8080
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 443 -j DNAT --to 10.255.128.213:443

