#include "nexus_platform.h"
/*#include "nexus_gpio_module.h"*/
#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"

const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 000 */ /* ENET_LINK */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 001 */ /* ENET_ACTIVITY */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 002 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 003 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 004 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 005 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 006 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 007 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 008 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 009 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 010 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 011 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 012 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 013 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 014 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 015 */ /* NC */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 016 */ /* MTSIF0_CLK */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 017 */ /* MTSIF0_DATA0 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 018 */ /* MTSIF0_SYNC */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 019 */ /* MTSIF0_DATA1 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 020 */ /* NC */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 021 */ /* MTSIF0_DATA2 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 022 */ /* MTSIF0_DATA3 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 023 */ /* MTSIF0_DATA4 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 024 */ /* MTSIF0_DATA5 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 025 */ /* MTSIF_ATS_RST */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 026 */ /* MTSIF0_DATA6 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 027 */ /* MTSIF0_DATA7 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 028 */ /* 3124_IRQ_N */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 029 */ /* NC */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 030 */ /* 3124_RST_N */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 031 */ /* HDD_PWR_CTRL_2 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 032 */ /* RF4CE_SCLK */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 033 */ /* RF4CE_MOSI */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 034 */ /* RF4CE_MISO */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 035 */ /* RF4CE_SS0 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 036 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 037 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 038 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 039 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 040 */ /* NC */
	HUMAX_GPIO_FUNCTION_ALT4,	/* GPIO 041 */ /* UART2_RX */
	HUMAX_GPIO_FUNCTION_ALT4,	/* GPIO 042 */ /* UART2_TX */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 043 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 044 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 045 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 046 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 047 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 048 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 049 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 050 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 051 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 052 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 053 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 054 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 055 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 056 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 057 */ /* NC */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 058 */ /* MTSIF_ATS_INC_058 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 059 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 060 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 061 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 062 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 063 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 064 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 065 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 066 */ /* NC */
	HUMAX_GPIO_FUNCTION_ALT4,	/* GPIO 067 */ /* UART1_RX */
	HUMAX_GPIO_FUNCTION_ALT4,	/* GPIO 068 */ /* UART1_TX */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 069 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 070 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 071 */ /* NC */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 072 */ /* SDIO_CMD */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 073 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 074 */ /* NC */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 075 */ /* SDIO_CLK */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 076 */ /* SDIO_DATA0 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 077 */ /* SDIO_DATA1 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 078 */ /* SDIO_DATA2 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 079 */ /* SDIO_DATA3 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 080 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 081 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 082 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 083 */ /* NC */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 084 */ /* RF4CE_WAKEUP */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 085 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 086 */ /* NC */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 087 */ /* MOCA_ACTIVITY */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 088 */ /* MOCA_LINK */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 089 */ /* LED_PWM */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 090 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 091 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 092 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 093 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 094 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 095 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 096 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 097 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 098 */ /* NC */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 099 */ /* GP099 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 100 */ /* GP100 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 101 */ /* GP101 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 102 */ /* GP102 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 103 */ /* GP103 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 104 */ /* GP104 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 105 */ /* GP105 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 106 */ /* GP106 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 107 */ /* GP107 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 108 */ /* GP108 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 109 */ /* GP109 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 110 */ /* GP110 */
	HUMAX_GPIO_FUNCTION_GPIO,	/* SGPIO 00 */ /* D3.3V */
	HUMAX_GPIO_FUNCTION_GPIO,	/* SGPIO 01 */ /* D3.3V */
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 02 */ /* BSC_M3_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 03 */ /* BSC_M3_SDA */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 00 */ /* NC */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 01 */ /* STB_KEY_IN */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 02 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 03 */ /* NC */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 04 */ /* AUDIO_HW_MUTE_N */
	HUMAX_GPIO_FUNCTION_ALT2,	/* AON_GPIO 05 */ /* UART0_RX */
	HUMAX_GPIO_FUNCTION_ALT2,	/* AON_GPIO 06 */ /* UART0_TX */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 07 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 08 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 09 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 10 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 11 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 12 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 13 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 14 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 15 */ /* NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 16 */ /* NC */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 17 */ /* AON_DDR_CTRL */
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_SGPIO 00 */ /* BSC_M0_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_SGPIO 01 */ /* BSC_M0_SDA */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_SGPIO 02 */ /* D3.3V */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_SGPIO 03 */ /* D3.3V */
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_SGPIO 04 */ /* BSC_M4_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_SGPIO 05 */ /* BSC_M4_SDA */
};

HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
	/* GPIO 000 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_000_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_000_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_001_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_001_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_002_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_002_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_003_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_003_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_004_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_004_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_005_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_005_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_006_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_006_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_007_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_007_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_008_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_008_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_009_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_009_SHIFT},
	/* GPIO 010 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_010_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_010_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_011_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_011_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_012_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_012_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_013_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_013_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_014_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_014_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_015_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_015_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_016_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_016_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_017_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_017_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_018_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_018_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_019_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_019_SHIFT},	
	/* GPIO 020 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_020_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_020_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_021_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_021_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_022_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_022_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_023_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_023_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_024_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_024_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_025_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_025_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_026_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_026_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_027_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_027_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_028_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_028_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_029_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_029_SHIFT},
	/* GPIO 030 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_030_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_030_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_031_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_031_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_032_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_032_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_033_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_033_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_034_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_034_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_035_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_035_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_036_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_036_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_037_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_037_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_038_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_038_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_039_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_039_SHIFT},
	/* GPIO 040 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_040_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_040_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_041_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_041_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_042_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_042_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_043_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_043_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_044_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_044_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_045_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_045_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_046_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_046_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_047_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_047_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_048_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_048_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_049_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_049_SHIFT},
	/* GPIO 050 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_050_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_050_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_051_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_051_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_052_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_052_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_053_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_053_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_054_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_054_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_055_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_055_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_056_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_056_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_057_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_057_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_058_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_058_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_059_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_059_SHIFT},	
	/* GPIO 060 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_060_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_060_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_061_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_061_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_062_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_062_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_063_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_063_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_064_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_064_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_065_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_065_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_066_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_066_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_067_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_067_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_068_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_068_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_069_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_069_SHIFT},
	/* GPIO 070 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_070_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_070_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_071_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_071_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_072_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_072_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_073_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_073_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_074_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_074_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_075_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_075_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_076_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_076_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_077_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_077_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_078_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_078_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_079_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_079_SHIFT},
	/* GPIO 080 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_080_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_080_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_081_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_081_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_082_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_082_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_083_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_083_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_084_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_084_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_085_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_085_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_086_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_086_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_087_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_087_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_088_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_088_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_089_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_089_SHIFT},
	/* GPIO 090 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_090_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_090_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_091_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_091_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_092_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_092_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_093_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_093_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_094_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_094_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_095_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_095_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_096_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_096_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_097_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_097_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_098_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_098_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_099_MASK,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_099_SHIFT},
	/* GPIO 100 */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_100_MASK,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_100_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_101_MASK,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_101_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_102_MASK,  BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_gpio_102_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_103_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_103_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_104_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_104_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_105_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_105_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_106_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_106_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_107_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_107_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_108_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_108_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_109_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_109_SHIFT},
	/* GPIO 110 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_110_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_110_SHIFT},
	/* SGPIO 000 */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_00_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_01_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_02_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_sgpio_03_SHIFT},
	/* AON_GPIO 000 */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_07_SHIFT},	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_15_SHIFT},	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT},
	/* AON_SGPIO 000 */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_SHIFT},	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_05_SHIFT},	
};

