# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

ifeq "$(DRM_BUILD_PROFILE)" "950"
TARGETS =     \
    stub      \
    external
else
TARGETS =     \
    real      \
    external
endif

include $(PLAYREADY_DIR)/GNUmakefile.common

