obj-y += opensrc/

obj-y += port_itk_main.o
obj-y += port_itk_os.o
obj-y += port_itk_console.o
obj-y += port_itk_display.o
obj-y += port_itk_image.o
obj-y += port_itk_audioclip.o
obj-y += port_itk_pipeline.o
obj-y += port_itk_bitmap.o
obj-y += port_itk_service.o
obj-y += port_itk_avstream.o
obj-y += port_itk_misc.o
obj-y += port_itk_font.o
obj-y += port_itk_http.o
obj-y += port_itk_crypto.o
obj-y += port_itk_zlib.o
obj-y += port_itk_nvs.o
obj-y += port_itk_dsmccfs.o
obj-y += port_itk_dvr.o
obj-y += port_itk_appmmi.o
obj-y += port_itk_demux.o
obj-y += port_itk_bitmap.o
# Additional include path
