obj-y += nx_prism_menu_hidden_main.o
obj-$(CONFIG_APUI_SET_HIDDEN_INFO_FUSING_INFO) += nx_prism_menu_hidden_fusinginfo.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include

# Additional include path
cclfags-y += -IS(NATIVEAPP_UI_INCLUDE_DIR)/include
ccflags-y += -I$(NATIVEAPP_PORT_INCLUDE_DIR)/include
