
obj-$(CONFIG_SUPPORT_UMMA_SAMBA_CLIENT) += umma_smbc.o

# Additional include path
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/smbc/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fm/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/smbs/include
