obj-y += apk_filemgr.o
obj-y += apk_filemgr_browse.o
obj-y += apk_filemgr_group.o
obj-y += apk_filemgr_storage.o
obj-y += apk_filemgr_sambaclient.o
obj-y += apk_filemgr_sambaserver.o
obj-y += apk_filemgr_ftpserver.o

# APPKIT v2 local include path
ccflags-y += -I$(OCTOTOP_SRC_DIR)/appkit/local_include

