obj-y += nx_port_meta_antenna.o
obj-y += nx_port_meta_query.o
obj-y += nx_port_meta_record.o
obj-y += nx_port_meta_service.o
obj-y += nx_port_meta_schedule.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include
ccflags-y += -I$(NATIVEAPP_PORT_INCLUDE_DIR)/include

# Additional include path
