#######################################
# include
#######################################
# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw

# Additional include path
ccflags-y += -I$(OCTO_TVSERVICE_DIR)/svc/cas/local_include

#######################################
# make
#######################################
obj-y += silib/
obj-y += svc_cas_mgr_svc_port.o
obj-y += svc_cas_mgr_pal_port.o

