-include ./dirs

ifeq ($(DIRS),)
TARGET = antirollbackclockstub

SOURCES =                \
	antirollbackclockutilstub.c antirollbackclockimplstub.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
