/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_vf_1.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 4/4/11 2:36p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Apr  1 16:39:07 2011
 *                 MD5 Checksum         d03d08c4839c3311c9d35c4cd5e10373
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7344/rdb/b0/bchp_vf_1.h $
 * 
 * Hydra_Software_Devel/1   4/4/11 2:36p albertl
 * SW7344-40: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_VF_1_H__
#define BCHP_VF_1_H__

/***************************************************************************
 *VF_1 - Video Formatter VF_1
 ***************************************************************************/
#define BCHP_VF_1_VF_REV_ID                      0x00183200 /* Revision ID register */
#define BCHP_VF_1_FORMAT_ADDER                   0x00183208 /* Video formatter adder register */
#define BCHP_VF_1_MISC                           0x0018320c /* Miscellaneous register */
#define BCHP_VF_1_NEG_SYNC_VALUES                0x00183210 /* Negative Sync and Blank amplitude register */
#define BCHP_VF_1_POS_SYNC_VALUES                0x00183214 /* Positive Sync amplitude register */
#define BCHP_VF_1_SYNC_TRANS_0                   0x00183218 /* Sync pulse transition 0 register */
#define BCHP_VF_1_SYNC_TRANS_1                   0x0018321c /* Sync pulse transition 1 register */
#define BCHP_VF_1_CH0_TAP1                       0x00183220 /* Channel 0 band-limiting filter (taps 1  & 19) */
#define BCHP_VF_1_CH0_TAP2                       0x00183224 /* Channel 0 band-limiting filter (taps 2  & 18) */
#define BCHP_VF_1_CH0_TAP3                       0x00183228 /* Channel 0 band-limiting filter (taps 3  & 17) */
#define BCHP_VF_1_CH0_TAP4                       0x0018322c /* Channel 0 band-limiting filter (taps 4  & 16) */
#define BCHP_VF_1_CH0_TAP5                       0x00183230 /* Channel 0 band-limiting filter (taps 5  & 15) */
#define BCHP_VF_1_CH0_TAP6                       0x00183234 /* Channel 0 band-limiting filter (taps 6  & 14) */
#define BCHP_VF_1_CH0_TAP7                       0x00183238 /* Channel 0 band-limiting filter (taps 7  & 13) */
#define BCHP_VF_1_CH0_TAP8                       0x0018323c /* Channel 0 band-limiting filter (taps 8  & 12) */
#define BCHP_VF_1_CH0_TAP9                       0x00183240 /* Channel 0 band-limiting filter (taps 9  & 11) */
#define BCHP_VF_1_CH0_TAP10                      0x00183244 /* Channel 0 band-limiting filter (tap 10  ) */
#define BCHP_VF_1_CH1_TAP1                       0x00183248 /* Channel 1 band-limiting filter (taps 1  & 19) */
#define BCHP_VF_1_CH1_TAP2                       0x0018324c /* Channel 1 band-limiting filter (taps 2  & 18) */
#define BCHP_VF_1_CH1_TAP3                       0x00183250 /* Channel 1 band-limiting filter (taps 3  & 17) */
#define BCHP_VF_1_CH1_TAP4                       0x00183254 /* Channel 1 band-limiting filter (taps 4  & 16) */
#define BCHP_VF_1_CH1_TAP5                       0x00183258 /* Channel 1 band-limiting filter (taps 5  & 15) */
#define BCHP_VF_1_CH1_TAP6                       0x0018325c /* Channel 1 band-limiting filter (taps 6  & 14) */
#define BCHP_VF_1_CH1_TAP7                       0x00183260 /* Channel 1 band-limiting filter (taps 7  & 13) */
#define BCHP_VF_1_CH1_TAP8                       0x00183264 /* Channel 1 band-limiting filter (taps 8  & 12) */
#define BCHP_VF_1_CH1_TAP9                       0x00183268 /* Channel 1 band-limiting filter (taps 9  & 11) */
#define BCHP_VF_1_CH1_TAP10                      0x0018326c /* Channel 1 band-limiting filter (tap 10  ) */
#define BCHP_VF_1_CH2_TAP1                       0x00183270 /* Channel 2 band-limiting filter (taps 1  & 19) */
#define BCHP_VF_1_CH2_TAP2                       0x00183274 /* Channel 2 band-limiting filter (taps 2  & 18) */
#define BCHP_VF_1_CH2_TAP3                       0x00183278 /* Channel 2 band-limiting filter (taps 3  & 17) */
#define BCHP_VF_1_CH2_TAP4                       0x0018327c /* Channel 2 band-limiting filter (taps 4  & 16) */
#define BCHP_VF_1_CH2_TAP5                       0x00183280 /* Channel 2 band-limiting filter (taps 5  & 15) */
#define BCHP_VF_1_CH2_TAP6                       0x00183284 /* Channel 2 band-limiting filter (taps 6  & 14) */
#define BCHP_VF_1_CH2_TAP7                       0x00183288 /* Channel 2 band-limiting filter (taps 7  & 13) */
#define BCHP_VF_1_CH2_TAP8                       0x0018328c /* Channel 2 band-limiting filter (taps 8  & 12) */
#define BCHP_VF_1_CH2_TAP9                       0x00183290 /* Channel 2 band-limiting filter (taps 9  & 11) */
#define BCHP_VF_1_CH2_TAP10                      0x00183294 /* Channel 2 band-limiting filter (tap 10  ) */
#define BCHP_VF_1_BVB_STATUS                     0x00183298 /* VEC's BVB Status Register */
#define BCHP_VF_1_SHAPER                         0x0018329c /* VEC's Shaper Register */
#define BCHP_VF_1_VIDEOBUS_SA_CONFIG             0x00183304 /* VIDEO-BUS SA CONFIGURATION REGISTER */
#define BCHP_VF_1_VIDEOBUS_SA_CH0_STATUS         0x00183308 /* VIDEO-BUS CHANNEL0 SA  STATUS REGISTER */
#define BCHP_VF_1_VIDEOBUS_SA_CH1_STATUS         0x0018330c /* VIDEO-BUS CHANNEL1 SA  STATUS REGISTER */
#define BCHP_VF_1_VIDEOBUS_SA_CH2_STATUS         0x00183310 /* VIDEO-BUS CHANNEL2 SA  STATUS REGISTER */
#define BCHP_VF_1_CONTROLBUS_SA_CONFIG           0x00183314 /* CONTROL-BUS SA CONFIGURATION REGISTER */
#define BCHP_VF_1_CONTROLBUS_SA_STATUS           0x00183318 /* CONTROL-BUS SA STATUS REGISTER */
#define BCHP_VF_1_ENVELOPE_GENERATOR             0x0018331c /* ENVELOPE GENERATOR CONTROL REGISTER */
#define BCHP_VF_1_NEG_SYNC_AMPLITUDE_EXTN        0x00183320 /* Negative Sync amplitude extension register */
#define BCHP_VF_1_POS_SYNC_AMPLITUDE_EXTN        0x00183324 /* Positive Sync amplitude extension register */
#define BCHP_VF_1_AV_SHIFT                       0x00183328 /* AV Shift register */
#define BCHP_VF_1_DRAIN_PIXELS_SCART             0x0018332c /* Drain Pixels register */
#define BCHP_VF_1_NEGATIVE_LIMIT                 0x00183330 /* Negative limit register */
#define BCHP_VF_1_NEGATIVE_LIMIT_EXTN            0x00183334 /* Negative limit register */

#endif /* #ifndef BCHP_VF_1_H__ */

/* End of File */
