obj-$(CONFIG_MW_CAS_NAGRA_OP_SES) += xmgr_cas_na_ses_ui.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

# Sub-CAS include path

