#--------------------------------------------------------------------------------------
# 기능단위로 나눠지는 부분들
#--------------------------------------------------------------------------------------

obj-$(CONFIG_PROD_HMS1000S)	+= xsvc_sys_hms1000s.o
obj-$(CONFIG_PROD_HB1000S)	+= xsvc_sys_hb1000s.o
obj-$(CONFIG_PROD_HD9000I)	+= xsvc_sys_hd9000i.o
obj-$(CONFIG_PROD_ICORDPRO)	+= xsvc_sys_icordpro.o
obj-$(CONFIG_PROD_HDNEO)	+= xsvc_sys_hdneo.o
obj-$(CONFIG_PROD_HGS1000S)	+= xsvc_sys_hgs1000s.o
obj-$(CONFIG_PROD_CDIG2000C)	+= xsvc_sys_cdig2000c.o
obj-$(CONFIG_PROD_YSR2000)	+= xsvc_sys_ysr2000.o
obj-$(CONFIG_PROD_YS1000)	+= xsvc_sys_ys1000.o
obj-$(CONFIG_PROD_HA7100S)	+= xsvc_sys_ha7100s.o
obj-$(CONFIG_PROD_M1)	+= xsvc_sys_m1.o
obj-$(CONFIG_PROD_FVP4000T)	+= xsvc_sys_fvp4000t.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc

# Additional include path

