/******************************************************************************
* $Workfile:$
* $Modtime:$
* Author :
* description :		 Factory Application Test Parameters
*
* Copyright (c) 2008 by Humax Co., Ltd.
* All right reserved
******************************************************************************/

/******************************************************************************
* header and definitions
******************************************************************************/
#include "fai_common.h"
#include "fai_testparams.h"
#include "fai_app_config.h"
#include "fai_channel.h"
#include "fai_av.h"
#include "fai_video.h"
#include "fai_audio.h"
#include "fai_scart.h"
#include "fai_hdmi.h"
#include "fai_rf.h"
#include "fai_ci.h"
#include "fai_sc.h"
#include "fai_flash.h"
#include "fai_eeprom.h"
#include "fai_panel.h"
#include "fai_fkey.h"
#include "fai_rcu.h"
#include "fai_usb.h"
#include "fai_ethernet.h"
#include "fai_hdd.h"
#include "fai_modem.h"
#include "fai_fan.h"
#include "fai_clock.h"
#include "fai_mes.h"
#include "fai_system.h"
#include "fai_irb.h"
#include "fai_wifi.h"
#include "fai_tmd.h"
#include "fdi_key.h"
#include "fai_cablemodem.h"
#include "fai_mmc.h"
#include "fai_bluetooth.h" //add junkh 2015.03.06

/* model specific configuration header */
#include "factorysw_config.h"

/******************************************************************************
* Definitions, typdef & const data
******************************************************************************/

/******************************************************************************
* Global variables and structures
******************************************************************************/
/* global variables and structures */

/******************************************************************************
* External variables and functions
******************************************************************************/
/* external variables  and functions */

/******************************************************************************
* Static variables and structures
******************************************************************************/
/* static variables and structures */

/******************************************************************************
* Static function prototypes
******************************************************************************/
/* static function prototypes */

/******************************************************************************
* OSD Test Parameters
******************************************************************************/
/*
 * RCU Test Fucntion Table
 */
OSDTESTPARAM_T g_atAllTestParamTable[TOTAL_OSD_TEST_PARAM] =
{
#if (MES_DOWNLOAD_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	MES_DOWNLOAD_UI_SHEET,
	MES_DOWNLOAD_UI_CELL,
	MES_DOWNLOAD_UI_INPUT,
	"MES Download",
	FAI_MES_Download_UI,
#endif
#if (DEFAULT_SETTING_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	DEFAULT_SETTING_UI_SHEET,
	DEFAULT_SETTING_UI_CELL,
	DEFAULT_SETTING_UI_INPUT,
	"Default\nSetting",
	FAI_SYSTEM_DefaultSetting_UI,
#endif
#if (SAT_SD_LOCK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SAT_SD_LOCK_UI_SHEET,
	SAT_SD_LOCK_UI_CELL,
	SAT_SD_LOCK_UI_INPUT,
	"Satellite\nSD A/V Play",
	FAI_AV_S_PlaySD_UI,
#endif
#if (SAT_HD_LOCK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SAT_HD_LOCK_UI_SHEET,
	SAT_HD_LOCK_UI_CELL,
	SAT_HD_LOCK_UI_INPUT,
	"Satellite\nHD A/V Play",
	FAI_AV_S_PlayHD_UI,
#endif
#if (CAB_SD_LOCK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_SD_LOCK_UI_SHEET,
	CAB_SD_LOCK_UI_CELL,
	CAB_SD_LOCK_UI_INPUT,
	"Cable\nSD A/V Play",
	FAI_AV_C_PlaySD_UI,
#endif
#if (CAB_HD_LOCK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_HD_LOCK_UI_SHEET,
	CAB_HD_LOCK_UI_CELL,
	CAB_HD_LOCK_UI_INPUT,
	"Cable\nHD A/V Play",
	FAI_AV_C_PlayHD_UI,
#endif
#if (TER_SD_LOCK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	TER_SD_LOCK_UI_SHEET,
	TER_SD_LOCK_UI_CELL,
	TER_SD_LOCK_UI_INPUT,
	"Terrestrial\nSD A/V Play",
	FAI_AV_T_PlaySD_UI,
#endif
#if (TER_HD_LOCK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	TER_HD_LOCK_UI_SHEET,
	TER_HD_LOCK_UI_CELL,
	TER_HD_LOCK_UI_INPUT,
	"Terrestrial\nHD A/V Play",
	FAI_AV_T_PlayHD_UI,
#endif
#if (TER2_HD_LOCK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	TER2_HD_LOCK_UI_SHEET,
	TER2_HD_LOCK_UI_CELL,
	TER2_HD_LOCK_UI_INPUT,
	"Terrestrial2\nHD A/V Play",
	FAI_AV_T2_PlayHD_UI,
#endif
#if (SWM_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SWM_UI_SHEET,
	SWM_UI_CELL,
	SWM_UI_INPUT,
	"SWM Test",
	NULL,
#endif
#if (SAT_CH_PERFORMANCE_TUNER0_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SAT_CH_PERFORMANCE_TUNER0_UI_SHEET,
	SAT_CH_PERFORMANCE_TUNER0_UI_CELL,
	SAT_CH_PERFORMANCE_TUNER0_UI_INPUT,
	"Satellite\nBER T0 Test",
	FAI_CHANNEL_S_PerformanceTuner0_UI,
#endif
#if (SAT_CH_PERFORMANCE_TUNER1_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SAT_CH_PERFORMANCE_TUNER1_UI_SHEET,
	SAT_CH_PERFORMANCE_TUNER1_UI_CELL,
	SAT_CH_PERFORMANCE_TUNER1_UI_INPUT,
	"Satellite\nBER T1 Test",
	FAI_CHANNEL_S_PerformanceTuner1_UI,
#endif
#if (CAB_CH_PERFORMANCE_TUNER0_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_CH_PERFORMANCE_TUNER0_UI_SHEET,
	CAB_CH_PERFORMANCE_TUNER0_UI_CELL,
	CAB_CH_PERFORMANCE_TUNER0_UI_INPUT,
	"Cable\nBER T0 Test",
	FAI_CHANNEL_C_PerformanceTuner0_UI,
#endif
#if (CAB_CH_PERFORMANCE_TUNER1_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_CH_PERFORMANCE_TUNER1_UI_SHEET,
	CAB_CH_PERFORMANCE_TUNER1_UI_CELL,
	CAB_CH_PERFORMANCE_TUNER1_UI_INPUT,
	"Cable\nBER T1 Test",
	FAI_CHANNEL_C_PerformanceTuner1_UI,
#endif
#if (CAB_CH_PERFORMANCE_TUNER_UI0_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_CH_PERFORMANCE_TUNER_UI0_SHEET,
	CAB_CH_PERFORMANCE_TUNER_UI0_CELL,
	CAB_CH_PERFORMANCE_TUNER_UI0_INPUT,
	CAB_CH_PERFORMANCE_TUNER_UI0_STRING,
	FAI_CHANNEL_C_PerformanceTuner_UI0,
#endif
#if (CAB_CH_PERFORMANCE_TUNER_UI1_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_CH_PERFORMANCE_TUNER_UI1_SHEET,
	CAB_CH_PERFORMANCE_TUNER_UI1_CELL,
	CAB_CH_PERFORMANCE_TUNER_UI1_INPUT,
	CAB_CH_PERFORMANCE_TUNER_UI1_STRING,
	FAI_CHANNEL_C_PerformanceTuner_UI1,
#endif
#if (CAB_CH_PERFORMANCE_TUNER_UI2_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_CH_PERFORMANCE_TUNER_UI2_SHEET,
	CAB_CH_PERFORMANCE_TUNER_UI2_CELL,
	CAB_CH_PERFORMANCE_TUNER_UI2_INPUT,
	CAB_CH_PERFORMANCE_TUNER_UI2_STRING,
	FAI_CHANNEL_C_PerformanceTuner_UI2,
#endif
#if (CAB_CH_PERFORMANCE_TUNER_UI3_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_CH_PERFORMANCE_TUNER_UI3_SHEET,
	CAB_CH_PERFORMANCE_TUNER_UI3_CELL,
	CAB_CH_PERFORMANCE_TUNER_UI3_INPUT,
	CAB_CH_PERFORMANCE_TUNER_UI3_STRING,
	FAI_CHANNEL_C_PerformanceTuner_UI3,
#endif
#if (CAB_CH_PERFORMANCE_TUNER_UI4_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_CH_PERFORMANCE_TUNER_UI4_SHEET,
	CAB_CH_PERFORMANCE_TUNER_UI4_CELL,
	CAB_CH_PERFORMANCE_TUNER_UI4_INPUT,
	CAB_CH_PERFORMANCE_TUNER_UI4_STRING,
	FAI_CHANNEL_C_PerformanceTuner_UI4,
#endif
#if (CAB_CH_PERFORMANCE_TUNER_UI5_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_CH_PERFORMANCE_TUNER_UI5_SHEET,
	CAB_CH_PERFORMANCE_TUNER_UI5_CELL,
	CAB_CH_PERFORMANCE_TUNER_UI5_INPUT,
	CAB_CH_PERFORMANCE_TUNER_UI5_STRING,
	FAI_CHANNEL_C_PerformanceTuner_UI5,
#endif
#if (CAB_CH_PERFORMANCE_TUNER_UI6_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_CH_PERFORMANCE_TUNER_UI6_SHEET,
	CAB_CH_PERFORMANCE_TUNER_UI6_CELL,
	CAB_CH_PERFORMANCE_TUNER_UI6_INPUT,
	CAB_CH_PERFORMANCE_TUNER_UI6_STRING,
	FAI_CHANNEL_C_PerformanceTuner_UI6,
#endif
#if (CAB_CH_PERFORMANCE_TUNER_UI7_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_CH_PERFORMANCE_TUNER_UI7_SHEET,
	CAB_CH_PERFORMANCE_TUNER_UI7_CELL,
	CAB_CH_PERFORMANCE_TUNER_UI7_INPUT,
	CAB_CH_PERFORMANCE_TUNER_UI7_STRING,
	FAI_CHANNEL_C_PerformanceTuner_UI7,
#endif
#if (TER_CH_PERFORMANCE_TUNER0_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	TER_CH_PERFORMANCE_TUNER0_UI_SHEET,
	TER_CH_PERFORMANCE_TUNER0_UI_CELL,
	TER_CH_PERFORMANCE_TUNER0_UI_INPUT,
	"Terrestrial\nBER T0 Test",
	FAI_CHANNEL_T_PerformanceTuner0_UI,
#endif
#if (TER_CH_PERFORMANCE_TUNER1_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	TER_CH_PERFORMANCE_TUNER1_UI_SHEET,
	TER_CH_PERFORMANCE_TUNER1_UI_CELL,
	TER_CH_PERFORMANCE_TUNER1_UI_INPUT,
	"Terrestrial\nBER T1 Test",
	FAI_CHANNEL_T_PerformanceTuner1_UI,
#endif
#if (IP_SD_STREAMING_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	IP_SD_STREAMING_UI_SHEET,
	IP_SD_STREAMING_UI_CELL,
	IP_SD_STREAMING_INPUT,
	"IP Streaming\nSD A/V Play",
	NULL,
#endif
#if (IP_HD_STREAMING_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	IP_HD_STREAMING_UI_SHEET,
	IP_HD_STREAMING_UI_CELL,
	IP_HD_STREAMING_INPUT,
	"IP Streaming\nHD A/V Play",
	NULL,
#endif
#if (COLORBAR_BEEP_ONOFF_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	COLORBAR_BEEP_ONOFF_UI_SHEET,
	COLORBAR_BEEP_ONOFF_UI_CELL,
	COLORBAR_BEEP_ONOFF_UI_INPUT,
	"Colorbar\n&Beep",
	FAI_AV_ColorbarBeepTest_UI,
#endif
#if (SCART_TV_BYPASS_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SCART_TV_BYPASS_UI_SHEET,
	SCART_TV_BYPASS_UI_CELL,
	SCART_TV_BYPASS_UI_INPUT,
	"TV SCART\nBypass",
	FAI_SCART_TvBypass_UI,
#endif
#if (SCART_VCR_BYPASS_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SCART_VCR_BYPASS_UI_SHEET,
	SCART_VCR_BYPASS_UI_CELL,
	SCART_VCR_BYPASS_UI_INPUT,
	"VCR SCART\nBypass",
	FAI_SCART_VcrBypass_UI,
#endif
#if (HW_AUDIO_MUTE_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	HW_AUDIO_MUTE_UI_SHEET,
	HW_AUDIO_MUTE_UI_CELL,
	HW_AUDIO_MUTE_UI_INPUT,
	"H/W Audio\nMute",
	FAI_AUDIO_HwMute_UI,
#endif
#if (FLASH_CHECK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	FLASH_CHECK_UI_SHEET,
	FLASH_CHECK_UI_CELL,
	FLASH_CHECK_UI_INPUT,
	"Flash Compare\nTest",
	FAI_FLASH_DataCompare_UI,
#endif
#if (FLASH_CRC_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	FLASH_CRC_UI_SHEET,
	FLASH_CRC_UI_CELL,
	FLASH_CRC_UI_INPUT,
	"Flash Crc\nTest",
	FAI_FLASH_FlashCRC_UI,
#endif
#if (EMMC_DOWNLOAD_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	EMMC_DOWNLOAD_UI_SHEET,
	EMMC_DOWNLOAD_UI_CELL,
	EMMC_DOWNLOAD_UI_INPUT,
	"eMMC SW\nDownload",
	FAI_FLASH_eMMCDownload_UI,
#endif	
#if (SDCARD_DETECT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SDCARD_DETECT_UI_SHEET,
	SDCARD_DETECT_UI_CELL,
	SDCARD_DETECT_UI_INPUT,
	"SDCARD&SN\nDetect",
	NULL,	
#endif
#if (NAND_DOWNLOAD_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	NAND_DOWNLOAD_UI_SHEET,
	NAND_DOWNLOAD_UI_CELL,
	NAND_DOWNLOAD_UI_INPUT,
	"NAND SW\nDownload",
	FAI_FLASH_NandDownload_UI,
#endif
#if (EEPROM_INIT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	EEPROM_INIT_UI_SHEET,
	EEPROM_INIT_UI_CELL,
	EEPROM_INIT_UI_INPUT,
	"EEPROM Init",
	FAI_EEPROM_Initialize_UI,
#endif
#if (EEPROM_ERASE_ALL_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	EEPROM_ERASE_ALL_UI_SHEET,
	EEPROM_ERASE_ALL_UI_CELL,
	EEPROM_ERASE_ALL_UI_INPUT,
	"EEPROM Erase",
	FAI_EEPROM_EraseAll_UI,
#endif
#if (TV_LINK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	TV_LINK_UI_SHEET,
	TV_LINK_UI_CELL,
	TV_LINK_UI_INPUT,
	"TV Link",
	NULL,
#endif
#if (TEMPERATURE_SENSOR_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	TEMPERATURE_SENSOR_UI_SHEET,
	TEMPERATURE_SENSOR_UI_CELL,
	TEMPERATURE_SENSOR_UI_INPUT,
	"Temp Sensor",
	NULL,
#endif
#if (IRB_BLASTER_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	IRB_BLASTER_UI_SHEET,
	IRB_BLASTER_UI_CELL,
	IRB_BLASTER_UI_INPUT,
	"IR Blaster",
	FAI_IRB_KeyLoopBack_UI,
#endif
#if (FLASH_ERASE_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	FLASH_ERASE_UI_SHEET,
	FLASH_ERASE_UI_CELL,
	FLASH_ERASE_UI_INPUT,
	"Flash Erase",
	NULL,
#endif
#if (SMARTCARD_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SMARTCARD_UI_SHEET,
	SMARTCARD_UI_CELL,
	SMARTCARD_UI_INPUT,
	"Smart Card\nDetection\nTest",
	NULL,
#endif
#if (CI_DETECTION_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CI_DETECTION_UI_SHEET,
	CI_DETECTION_UI_CELL,
	CI_DETECTION_UI_INPUT,
	"CI detection\nTest",
	NULL,
#endif
#if (SAT_CI_LOCK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SAT_CI_LOCK_UI_SHEET,
	SAT_CI_LOCK_UI_CELL,
	SAT_CI_LOCK_UI_INPUT,
	"CI TS locking\nTest",
	FAI_AV_S_CI_AvTest_UI,
#endif
#if (CAB_CI_LOCK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CAB_CI_LOCK_UI_SHEET,
	CAB_CI_LOCK_UI_CELL,
	CAB_CI_LOCK_UI_INPUT,
	"CI TS locking\nTest",
	FAI_AV_C_CI_AvTest_UI,
#endif
#if (TER_CI_LOCK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	TER_CI_LOCK_UI_SHEET,
	TER_CI_LOCK_UI_CELL,
	TER_CI_LOCK_UI_INPUT,
	"CI TS locking\nTest",
	FAI_AV_T_CI_AvTest_UI,
#endif
#if (ETHERNET_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	ETHERNET_UI_SHEET,
	ETHERNET_UI_CELL,
	ETHERNET_UI_INPUT,
	"Ethernet Test",
	FAI_ETHERNET_Test_UI,
#endif
#if (HDD_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	HDD_UI_SHEET,
	HDD_UI_CELL,
	HDD_UI_INPUT,
	"HDD Test",
	FAI_HDD_Test_UI,
#endif
#if (USB_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	USB_UI_SHEET,
	USB_UI_CELL,
	USB_UI_INPUT,
	"USB Test",
	FAI_USB_Test_UI,
#endif
#if (USB_EXT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	USB_EXT_UI_SHEET,
	USB_EXT_UI_CELL,
	USB_EXT_UI_INPUT,
	"USB3 Test",
	FAI_USB_EXT_Test_UI,
#endif

#if (MODEM_LINE_VOLT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	MODEM_LINE_VOLT_UI_SHEET,
	MODEM_LINE_VOLT_UI_CELL,
	MODEM_LINE_VOLT_UI_INPUT,
	"Modem Voltage",
	FAI_MODEM_VoltageCheck_UI,
#endif
#if (MODEM_CALL_21_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	MODEM_CALL_21_UI_SHEET,
	MODEM_CALL_21_UI_CELL,
	MODEM_CALL_21_UI_INPUT,
	"Modem\nPort 21",
	FAI_MODEM_Communication_UI,
#endif
#if (MODEM_CALL_23_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	MODEM_CALL_23_UI_SHEET,
	MODEM_CALL_23_UI_CELL,
	MODEM_CALL_23_UI_INPUT,
	"Modem\nPort 23",
	FAI_MODEM_Communication_UI,
#endif
#if (FAN_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	FAN_UI_SHEET,
	FAN_UI_CELL,
	FAN_UI_INPUT,
	"FAN On/Off",
	FAI_FAN_OnOff_UI,
#endif
#if (CABLE_MODEM_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CABLE_MODEM_UI_SHEET,
	CABLE_MODEM_UI_CELL,
	CABLE_MODEM_UI_INPUT,
	"Cable Modem",
	NULL,
#endif
#if (SERIAL_COMM_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	DEFAULT_PIN_OPEN_CHECK_UI_SHEET,
	DEFAULT_PIN_OPEN_CHECK_UI_CELL,
	DEFAULT_PIN_OPEN_CHECK_UI_INPUT,
	"Default Pin\nOpen Check",
	NULL,
#endif
#if (EXTERNAL_SATA_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	EXTERNAL_SATA_UI_SHEET,
	EXTERNAL_SATA_UI_CELL,
	EXTERNAL_SATA_UI_INPUT,
	"Ext SATA\nTest",
	NULL,
#endif
#if (MOCA_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	MOCA_UI_SHEET,
	MOCA_UI_CELL,
	MOCA_UI_INPUT,
	"MoCA Test",
	NULL,
#endif
#if (LNB_VOLT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	LNB_VOLT_UI_SHEET,
	LNB_VOLT_UI_CELL,
	LNB_VOLT_UI_INPUT,
	"LNB Test",
	FAI_CHANNEL_S_LNBOutput_UI,
#endif
#if (SCART_OUTPUT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SCART_OUTPUT_UI_SHEET,
	SCART_OUTPUT_UI_CELL,
	SCART_OUTPUT_UI_INPUT,
	"SCART Voltage\nTest",
	FAI_SCART_Output_UI,
#endif
#if (TER_CH_ANT_VOLT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	TER_CH_ANT_VOLT_UI_SHEET,
	TER_CH_ANT_VOLT_UI_CELL,
	TER_CH_ANT_VOLT_UI_INPUT,
	"ANT Power\nTest",
	FAI_CHANNEL_T_AntennaVolt_UI,
#endif
#if (DCONNECTOR_SVIDEO_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	DCONNECTOR_SVIDEO_UI_SHEET,
	DCONNECTOR_SVIDEO_UI_CELL,
	DCONNECTOR_SVIDEO_UI_INPUT,
	"D port \nVoltage",
	FAI_VIDEO_DConnectorOutput_UI,
#endif
#if (FRONT_DISPLAY_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	FRONT_DISPLAY_UI_SHEET,
	FRONT_DISPLAY_UI_CELL,
	FRONT_DISPLAY_UI_INPUT,
	"Front All\nDisplay\nOn/Off",
	FAI_PANEL_Test_UI,
#endif
#if (POWER_CONTROL_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	POWER_CONTROL_UI_SHEET,
	POWER_CONTROL_UI_CELL,
	POWER_CONTROL_UI_INPUT,
	"POWER Control",
	FAI_SYSTEM_PowerCtrl_UI,
#endif
#if (DOOR_SENSOR_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	DOOR_SENSOR_UI_SHEET,
	DOOR_SENSOR_UI_CELL,
	DOOR_SENSOR_UI_INPUT,
	"Door Sensor",
	NULL,
#endif
#if (MIC_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	MIC_UI_SHEET,
	MIC_UI_CELL,
	MIC_UI_INPUT,
	"MIC Test",
	NULL,
#endif
#if (RF_RCU_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	RF_RCU_UI_SHEET,
	RF_RCU_UI_CELL,
	RF_RCU_UI_INPUT,
	"RF RCU Test",
	NULL,
#endif
#if (SW_RESET_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	SW_RESET_UI_SHEET,
	SW_RESET_UI_CELL,
	SW_RESET_UI_INPUT,
	"S/W Reset",
	FAI_SYSTEM_SWReset_UI,
#endif
#if (VIDEO_MODE_SELECT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	VIDEO_MODE_SELECT_UI_SHEET,
	VIDEO_MODE_SELECT_UI_CELL,
	VIDEO_MODE_SELECT_UI_INPUT,
	"Video Mode\nSelect",
	NULL,
#endif
#if (AUDIO_DETECTION_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	AUDIO_DETECTION_UI_SHEET,
	AUDIO_DETECTION_UI_CELL,
	AUDIO_DETECTION_UI_INPUT,
	"Audio Detection\nTest",
	NULL,
#endif
#if (MPU_DOWNLOAD_PATH_CHECK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	MPU_DOWNLOAD_PATH_CHECK_UI_SHEET,
	MPU_DOWNLOAD_PATH_CHECK_UI_CELL,
	MPU_DOWNLOAD_PATH_CHECK_UI_INPUT,
	"MPU DN Path\nCheck",
	NULL,
#endif
#if (VIDEO_RESOLUTION_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	VIDEO_RESOLUTION_UI_SHEET,
	VIDEO_RESOLUTION_UI_CELL,
	VIDEO_RESOLUTION_UI_INPUT,
	"Video Resolution",
	NULL,
#endif
#if (CPU_CORE_VOLT_CHECK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CPU_CORE_VOLT_CHECK_UI_SHEET,
	CPU_CORE_VOLT_CHECK_UI_CELL,
	CPU_CORE_VOLT_CHECK_UI_INPUT,
	"CPU Core\nVoltage Check",
	NULL,
#endif
#if (HDMI_HDCP_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	HDMI_HDCP_UI_SHEET,
	HDMI_HDCP_UI_CELL,
	HDMI_HDCP_UI_INPUT,
	"HDCP Test",
	FAI_HDMI_EnableHDCP_UI,
#endif
#if (CSC_VALIDATION_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CSC_VALIDATION_UI_SHEET,
	CSC_VALIDATION_UI_CELL,
	CSC_VALIDATION_UI_INPUT,
	"CSC VAlidation\nTest",
	NULL,
#endif
#if (CIPLUS_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	CIPLUS_UI_SHEET,
	CIPLUS_UI_CELL,
	CIPLUS_UI_INPUT,
	"CI+ Test",
	FAI_SYSTEM_CiPlusCheck_UI,
#endif
#if (DTCP_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	DTCP_UI_SHEET,
	DTCP_UI_CELL,
	DTCP_UI_INPUT,
	"DTCP Test",
	FAI_SYSTEM_DTCPCheck_UI,
#endif
#if (INFORMATION_OSD_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	INFORMATION_OSD_UI_SHEET,
	INFORMATION_OSD_UI_CELL,
	INFORMATION_OSD_UI_INPUT,
	"Information",
	FAI_SYSTEM_DisplayInfo_UI,
#endif
#if (HDDFORMAT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	HDDFORMAT_UI_SHEET,
	HDDFORMAT_UI_CELL,
	HDDFORMAT_UI_INPUT,
	"HDD Format",
	FAI_HDD_Format_UI,
#endif

#if (MMC_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	MMC_UI_SHEET,
	MMC_UI_CELL,
	MMC_UI_INPUT,
	"SD Card Test\n& Format",
	FAI_MMC_Test_UI,
#endif
#if (WIFI_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	WIFI_UI_SHEET,
	WIFI_UI_CELL,
	WIFI_UI_INPUT,
	"WIFI Test",
#if (PRODUCT_YSR2000==YES)
#if ( WIFI_MODULE_TYPE == WIFI_MODULE_QT3490)
	FAI_WIFI_QT3940_RSSITest_UI,
#else
	FAI_WIFI_RSSITest_UI,
#endif
#endif
#endif
#if (BLUETOOTH_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	BLUETOOTH_UI_SHEET,
	BLUETOOTH_UI_CELL,
	BLUETOOTH_UI_INPUT,
	"BLUETOOTH\nTest",
	FAI_BLUETOOTH_Test_UI,
#endif
#if(WIFI_CONDUCT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_RCU,
	WIFI_CONDUCT_UI_SHEET,
	WIFI_CONDUCT_UI_CELL,
	WIFI_CONDUCT_UI_INPUT,
	"WIFI\nConducted\nSetup",
	FAI_WIFI_Bridge_Setup_For_Conducted_Test_UI,
#endif
/*
 * front key test
 */
#if (FKEY_STANDBY_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_STANDBY_UI_SHEET,
	FKEY_STANDBY_UI_CELL,
	FRONT_KEY_POWER,
	"STBY",
	FAI_FKEY_Standby,
#endif
#if (FKEY_GUIDE_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_GUIDE_UI_SHEET,
	FKEY_GUIDE_UI_CELL,
	FRONT_KEY_GUIDE,
	"GUID",
	FAI_FKEY_Guide,
#endif
#if (FKEY_OK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_OK_UI_SHEET,
	FKEY_OK_UI_CELL,
	FRONT_KEY_OK,
	"OK",
	FAI_FKEY_Ok,
#endif
#if (FKEY_CHUP_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_CHUP_UI_SHEET,
	FKEY_CHUP_UI_CELL,
	FRONT_KEY_CHUP,
	"CHUP",
	FAI_FKEY_ChUp,
#endif
#if (FKEY_CHDOWN_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_CHDOWN_UI_SHEET,
	FKEY_CHDOWN_UI_CELL,
	FRONT_KEY_CHDOWN,
	"CHDN",
	FAI_FKEY_ChDown,
#endif
#if (FKEY_VOLUP_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_VOLUP_UI_SHEET,
	FKEY_VOLUP_UI_CELL,
	FRONT_KEY_VOLUP,
	"VOUP",
	FAI_FKEY_VolUp,
#endif
#if (FKEY_VOLDOWN_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_VOLDOWN_UI_SHEET,
	FKEY_VOLDOWN_UI_CELL,
	FRONT_KEY_VOLDOWN,
	"VODN",
	FAI_FKEY_VolDown,
#endif
#if (FKEY_TVRADIO_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_TVRADIO_UI_SHEET,
	FKEY_TVRADIO_UI_CELL,
	FRONT_KEY_TVRADIO,
	"TVRD",
	FAI_FKEY_TvRadio,
#endif
#if (FKEY_PLAY_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_PLAY_UI_SHEET,
	FKEY_PLAY_UI_CELL,
	FRONT_KEY_PLAY,
	"PLAY",
	FAI_FKEY_Play,
#endif
#if (FKEY_INFO_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_INFO_UI_SHEET,
	FKEY_INFO_UI_CELL,
	FRONT_KEY_INFO,
	"INFO",
	FAI_FKEY_Info,
#endif
#if (FKEY_WPS_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_WPS_UI_SHEET,
	FKEY_WPS_UI_CELL,
	FRONT_KEY_WPS,
	"WPS",
	FAI_FKEY_WPS,
#endif
#if (FKEY_NETWORK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_NETWORK_UI_SHEET,
	FKEY_NETWORK_UI_CELL,
	FRONT_KEY_NETWORK,
	"NET",
	FAI_FKEY_Network,
#endif
#if (FKEY_UP_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_UP_UI_SHEET,
	FKEY_UP_UI_CELL,
	FRONT_KEY_UP,
	"UP",
	FAI_FKEY_Up,
#endif
#if (FKEY_DOWN_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_DOWN_UI_SHEET,
	FKEY_DOWN_UI_CELL,
	FRONT_KEY_DOWN,
	"DOWN",
	FAI_FKEY_Down,
#endif
#if (FKEY_LEFT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_LEFT_UI_SHEET,
	FKEY_LEFT_UI_CELL,
	FRONT_KEY_LEFT,
	"LEFT",
	FAI_FKEY_Left,
#endif
#if (FKEY_RIGHT_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_RIGHT_UI_SHEET,
	FKEY_RIGHT_UI_CELL,
	FRONT_KEY_RIGHT,
	"RIGT",
	FAI_FKEY_Right,
#endif
#if (FKEY_MENU_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_MENU_UI_SHEET,
	FKEY_MENU_UI_CELL,
	FRONT_KEY_MENU,
	"MENU",
	FAI_FKEY_Menu,
#endif
#if (FKEY_BACK_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_BACK_UI_SHEET,
	FKEY_BACK_UI_CELL,
	FRONT_KEY_BACK,
	"BACK",
	FAI_FKEY_Back,
#endif
#if (FKEY_SWRESET_UI_ENABLE==YES)
	TEST_INPUT_TYPE_FKEY,
	FKEY_SWRESET_UI_SHEET,
	FKEY_SWRESET_UI_CELL,
	FRONT_KEY_SW_REBOOT,
	"RESET",
	FAI_FKEY_SwReset,
#endif

};
/*
 * Execute Test Param Table
 */
OSDTESTPARAM_T *g_atExeTestParamTable[TOTAL_SHEET_NUMBER*PP_TOTAL_MENU_NUM];

/*
 * TMD Test Function Table
 */
FAI_TMDTESTPARAM_T g_stTmdTestItemTable[MAX_TMD_TEST_ITEM] =
{
#if (CHANNEL_SAT_LNB_OUTPUT_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x01, 0x81,
	FALSE,
	FAI_CHANNEL_S_LNBOutput,
#endif
#if (CHANNEL_SAT_USED4CHANNEL_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x01, 0x02,
	TRUE,
	FAI_CHANNEL_S_RequestLockFor4Ch,
#endif
#if (CHANNEL_SAT_LOCK_FOR_PERFORMANCE_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x01, 0x03,
	TRUE,
	FAI_CHANNEL_S_PerformanceCheck,
#endif
#if (CHANNEL_SAT_LNB_BYPASS_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x01, 0x84,
	FALSE,
	FAI_CHANNEL_S_LNBBypass,
#endif
#if (CHANNEL_SAT_SWM_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x01, 0x05,
	FALSE,
	NULL,
#endif
#if (CHANNEL_TER_CH_ANT_VOLT_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x02, 0x81,
	FALSE,
	FAI_CHANNEL_T_AntennaVolt,
#endif
#if (CHANNEL_TER_LOCK_REQUEST_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x02, 0x02,
	TRUE,
	FAI_CHANNEL_T_RequestLock,
#endif
#if (CHANNEL_TER_LOCK_FOR_PERFORMANCE_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x02, 0x03,
	TRUE,
	FAI_CHANNEL_T_PerformanceCheck,
#endif
#if (CHANNEL_CAB_LOCK_REQUEST_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x03, 0x01,
	TRUE,
	FAI_CHANNEL_C_RequestLock,
#endif
#if (CHANNEL_CAB_LOCK_FOR_PERFORMANCE_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x03, 0x02,
	TRUE,
	FAI_CHANNEL_C_PerformanceCheck,
#endif
#if (AVPLAY_PLAY_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x04, 0x81,
	FALSE,
	FAI_AV_Play,
#endif
#if (AVPLAY_CI_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x04, 0x82,
	FALSE,
	FAI_CI_Test,
#endif
#if (AVPLAY_QUICK_PLAY_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x04, 0x83,
	FALSE,
	FAI_AV_QuickPlay,
#endif
#if defined(AVPLAY_QUICK_PLAY_WITH_DISEQC_ENABLE) && (AVPLAY_QUICK_PLAY_WITH_DISEQC_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x04, 0x84,
	FALSE,
	NULL,
#endif
#if (AVPLAY_STOP_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x04, 0x85,
	FALSE,
	FAI_AV_Stop,
#endif
#if (MOCA_ARP_COMM_ENABLE==YES)
	FAI_CATEGORY_CHANNEL, 0x05, 0x01,
	FALSE,
	NULL,
	FAI_CATEGORY_CHANNEL, 0x05, 0x02,
	FALSE,
	NULL,
#endif
#if (COLORBAR_BEEP_ONOFF_ENABLE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x01, 0x81,
	FALSE,
	FAI_AV_ColorbarBeep,
#endif
#if (SCART_OUTPUT_ENABLE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x02, 0x81,
	FALSE,
	FAI_SCART_Output,
#endif
#if (SCART_BYPASS_ENABLE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x02, 0x82,
	FALSE,
	FAI_SCART_Bypass,
#endif
#if (SVIDEO_OUTPUT_ENABLE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x03, 0x81,
	FALSE,
	FAI_VIDEO_SVideoOutput,
#endif
#if (COMPOSITE_AUDIO_DECTION_ENABLE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x04, 0x81,
	FALSE,
	FAI_VIDEO_CompositeAudioDetection,
#endif
#if defined(RF_OUTPUT_ENABLE) && (RF_OUTPUT_ENABLE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x06, 0x81,
	FALSE,
	FAI_RF_Output,
#endif
#if (RF_OUTPUT_CHANNEL_CHECK_ENABLE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x06, 0x82,
	FALSE,
	FAI_RF_CheckOutputChannel,
#endif
#if (DCONNECTOR_OUTPUT_ENABLE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x07, 0x81,
	FALSE,
	FAI_VIDEO_DConnectorOutput,
#endif
#if (HDMI_CEC_ENALBE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x08, 0x81,
	FALSE,
	FAI_HDMI_Cec,
#endif
#if (HDMI_HDCP_ENABLE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x08, 0x02,
	FALSE,
	FAI_HDMI_EnableHdcp,
	FAI_CATEGORY_AV_OUTPUT, 0x08, 0x83,/*HDMI DDC TEST*/
	FALSE,
	NULL,
#endif
#if (HW_AUDIO_MUTE_OUTPUT_ENABLE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x09, 0x81,
	FALSE,
	FAI_AUDIO_HwMute,
#endif
#if(RESOLUTION_CHANGE_ENABLE==YES)
	FAI_CATEGORY_AV_OUTPUT, 0x0A, 0x8B,
	FALSE,
	FAI_AV_SetDisplayStandard,
#endif
#if (FRONT_KEY_ENABLE==YES)
	FAI_CATEGORY_FRONT_PANEL, 0x01, 0x01,
	TRUE,
	FAI_FKEY_SetTestKey,
#endif
#if (FRONT_LED_ONOFF_ENABLE==YES)
	FAI_CATEGORY_FRONT_PANEL, 0x02, 0x81,
	FALSE,
	FAI_PANEL_LEDCtrl,
#endif
#if (FRONT_DISPLAY_ONOFF_ENABLE==YES)
	FAI_CATEGORY_FRONT_PANEL, 0x03, 0x81,
	FALSE,
	FAI_PANEL_DisplayCtrl,
#endif
#if (FRONT_IR_LOOP_ENABLE==YES)
	FAI_CATEGORY_FRONT_PANEL, 0x04, 0x01,/* IR Sensor Cable Loop*/
	FALSE,
	NULL,
#endif
#if (FRONT_RCU_ENABLE==YES)
	FAI_CATEGORY_FRONT_PANEL, 0x04, 0x02,
	TRUE,
	FAI_RCU_SetTestKey,
#endif
#if (FLASH_DATA_COMPARE_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x01, 0x01,
	FALSE,
	FAI_FLASH_DataCompare,
#endif
#if (FLASH_CRC_CHECK_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x01, 0x02,
	FALSE,
	FAI_FLASH_CrcCheck,
#endif
#if (FLASH_PATTERN_TEST_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x01, 0x03,
	FALSE,
	FAI_FLASH_PatternTest,
#endif
#if (NAND_DOWNLOAD_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x01, 0x05,
	FALSE,
	FAI_FLASH_NandDownload,
#endif
#if (EMMC_DOWNLOAD_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x01, 0x05,
	FALSE,
	FAI_FLASH_eMMCDownload,
#endif
#if (NAND_BAD_BLOCK_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x01, 0x06,
	FALSE,
	FAI_FLASH_BadBlock,
#endif
#if (EEPROM_ERASE_ALL_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x02, 0x01,
	FALSE,
	FAI_EEPROM_EraseAll,
#endif
#if (EEPROM_ERASE_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x02, 0x02,
	FALSE,
	FAI_EEPROM_Erase,
#endif
#if (EEPROM_TEST_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x02, 0x03,
	FALSE,
	FAI_EEPROM_Test,
#endif
#if (EEPROM_INIT_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x02, 0x04,
	FALSE,
	FAI_EEPROM_Initialize,
#endif
#if (HDD_FORMAT_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x03, 0x01,
	FALSE,
	FAI_HDD_Format,
#endif
#if (HDD_DATA_COMPARE_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x03, 0x02,
	FALSE,
	FAI_HDD_DataCompare,
#endif
#if (HDD_GET_INFO_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x03, 0x03,
	FALSE,
	FAI_HDD_GetInfo,
#endif
#if (HDD_SET_PARKING_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x03, 0x04,
	FALSE,
	FAI_HDD_SetParking,
#endif
#if (HDD_DEFECT_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x03, 0x05,
	FALSE,
	FAI_HDD_Defect,
#endif
#if (HDD_READ_POH_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x03, 0x06,
	FALSE,
	FAI_HDD_ReadPOH,
#endif
#if (HDD_SMART_SHORTDST_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x03, 0x07,
	FALSE,
	FAI_HDD_Smart_ShortDST,
#endif
#if (DDR_PATTERN_TEST_ENABLE==YES)
	FAI_CATEGORY_MEMORY, 0x04, 0x01,
	FALSE,
	FAI_DDR_PatternTest,
#endif
#if (ETHERNET_ARP_CHECK_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x01, 0x01,
	FALSE,
	FAI_ETHERNET_ARPCheck,
#endif
#if (MMC_SD_CARD_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x11, 0x84,
	FALSE,
	FAI_MMC_File_Read,
	FAI_CATEGORY_PERIPHERAL, 0x11, 0x85,
	FALSE,
	FAI_MMC_File_Write,
	FAI_CATEGORY_PERIPHERAL, 0x11, 0x86,
	FALSE,
	FAI_MMC_File_Delete,
	FAI_CATEGORY_PERIPHERAL, 0x11, 0x87,
	FALSE,
	FAI_MMC_UploadInfo,	
	FAI_CATEGORY_PERIPHERAL, 0x11, 0x01,
	FALSE,
	FAI_MMC_Format,	
#endif
#if (MODEM_LINE_VOLT_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x02, 0x01,
	FALSE,
	FAI_MODEM_VoltageCheck,
#endif
#if (MODEM_CALL_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x02, 0x02,
	FALSE,
	FAI_MODEM_Communication,
#endif
#if (SMARTCARD_ATR_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x03, 0x81,
	FALSE,
	FAI_SC_AtrCheck,
#endif
#if (USB_DEVICE_DECTION_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x04, 0x01,
	FALSE,
	FAI_USB_Detection,
#endif
#if (FAN_SPEED_CONTROL_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x05, 0x01,
	FALSE,
	FAI_FAN_SpeedCtrl,
#endif
#if (RF_RCU_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x06, 0x81,
	FALSE,
	NULL,
#endif
#if (IR_RCU_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x06, 0x82,
	FALSE,
	NULL,
#endif
#if (TEMPERATURE_SENSOR_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x08, 0x81,
	FALSE,
	FAI_SYSTEM_GetTemperature,
#endif
#if (CABLE_MODEM_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x09, 0x01,
	FALSE,
	FAI_CABLEMODEM_Check,
#endif
#if (DEFAULT_DECTION_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x0B, 0x81,
	FALSE,
	NULL,
#endif
#if (CPU_TYPE_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x0C, 0x81,
	FALSE,
	NULL,
#endif
#if (MPU_DN_PATH_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x0D, 0x81,
	FALSE,
	NULL,
#endif
#if (WIFI_QT3940_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x0F, 0x06,
	FALSE,
	FAI_WIFI_QT3940_AssocSSID,
	FAI_CATEGORY_PERIPHERAL, 0x0F, 0x09,
	FALSE,
	FAI_WIFI_QT3940_ReadRSSI,
#endif
#if (WIFI_RSSI_ENABLE==YES)					/*sgkim4*/
		FAI_CATEGORY_PERIPHERAL, 0x0F, 0x06,
		FALSE,
		FAI_WIFI_SSID,
		FAI_CATEGORY_PERIPHERAL, 0x0F, 0x09,
		FALSE,
		FAI_WIFI_RSSI,
#endif
#if (WIFI_THROUGHPUT_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x0F, 0x03,
	FALSE,
	FAI_WIFI_ThroughputSetup,
	FAI_CATEGORY_PERIPHERAL, 0x0F, 0x04,
	FALSE,
	FAI_WIFI_ThroughputTest,
#endif
#if (BT_DISCOVERY_ENABLE==YES)
		FAI_CATEGORY_PERIPHERAL, 0x0E, 0x01,
		FALSE,
		FAI_BLUETOOTH_TEST_TMD,
#endif
#if (RF4CE_RSSI_CHECK_ENABLE==YES)
	FAI_CATEGORY_PERIPHERAL, 0x10, 0x06,
	FALSE,
	FAI_SYSTEM_CheckRf4ceRssi,
#endif
#if (MES_DOWNLOAD_MODE_ENABLE==YES)
	FAI_CATEGORY_SYSTEM, 0x01, 0x81,
	FALSE,
	FAI_MES_Start,
#endif
#if (DEFAULT_SETTING_ENABLE==YES)
	FAI_CATEGORY_SYSTEM, 0x02, 0x81,
	FALSE,
	FAI_SYSTEM_DefaultSetting,
#endif
#if (SYSINFO_GET_SW_VERSION_ENABLE==YES)
	FAI_CATEGORY_SYSTEM, 0x03, 0x81,
	FALSE,
	FAI_SYSTEM_GetSWVersion,
#endif
#if (SYSINFO_GET_UPLOAD_INFO_ENABLE==YES)
	FAI_CATEGORY_SYSTEM, 0x03, 0x82,
	FALSE,
	FAI_SYSTEM_GetUploadInfo,
#endif
#if (SYSINFO_GET_SECURITY_INFO_ENABLE==YES)
	FAI_CATEGORY_SYSTEM, 0x03, 0x83,
	FALSE,
	FAI_SYSTEM_GetSecurityInfo,
#endif
#if (SYSINFO_OFF==YES)
	FAI_CATEGORY_SYSTEM, 0x03, 0x84,
	FALSE,
	FAI_SYSTEM_InformationOff,
#endif
/*
 * disabled by dcchung
 *
#if (SYSINFO_RID_SCN_CHECK_ENABLE==YES)
	0x20, 0x03, 0x84,
	NULL,
#endif
*/
#if (SYSINFO_DTCP_TEST_ENABLE==YES)
	FAI_CATEGORY_SYSTEM, 0x03, 0x86,
	FALSE,
	FAI_SYSTEM_DTCPCheck,
#endif

/*
#if (SYSINFO_CHECK_CIPLUS_KEY_ENABLE==YES)
	FAI_CATEGORY_SYSTEM, 0x03, 0x86,
	FALSE,
	FAI_SYSTEM_CiPlusCheck,
#endif

#if (SYSINFO_CSC_VALIDATION_ENABLE==YES)
	FAI_CATEGORY_SYSTEM, 0x03, 0x87,
	FALSE,
	NULL,
#endif
*/
#if (POWER_SW_RESET_ENABLE==YES)
	FAI_CATEGORY_SYSTEM, 0x04, 0x81,
	FALSE,
	FAI_SYSTEM_SWReset,
#endif
#if (POWER_CONTROL_ENABLE==YES)
	FAI_CATEGORY_SYSTEM, 0x04, 0x82,
	FALSE,
	FAI_SYSTEM_PowerCtrl,
#endif
#if (CHANGE_SHEET_ENABLE==YES)
	FAI_CATEGORY_SYSTEM, 0x05, 0x81,
	FALSE,
	FAI_SYSTEM_ChangeSheet,
#endif
};

/*
 * OSD Menu Position Table
 */
#if defined(APP_MENU_5_4)
POSITION_T g_atTestMenuPositionFor5x4[TOTAL_OSD_TEST_PARAM] =
{
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*0, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*0,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*1, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*0,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*2, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*0,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*3, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*0,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*4, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*0,

	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*0, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*1,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*1, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*1,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*2, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*1,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*3, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*1,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*4, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*1,

	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*0, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*2,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*1, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*2,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*2, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*2,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*3, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*2,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*4, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*2,

	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*0, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*3,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*1, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*3,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*2, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*3,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*3, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*3,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*4, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*3,

	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*0, MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*1, MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*2, MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*3, MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*4, MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*5, MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*6, MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*7, MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*8, MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*9, MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW)
};
#else
POSITION_T g_atTestMenuPositionFor4x4[TOTAL_OSD_TEST_PARAM] =
{
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*0, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*0,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*1, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*0,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*2, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*0,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*3, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*0,

	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*0, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*1,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*1, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*1,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*2, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*1,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*3, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*1,

	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*0, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*2,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*1, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*2,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*2, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*2,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*3, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*2,

	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*0, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*3,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*1, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*3,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*2, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*3,
	PP_TEST_MENU_START_X+(PP_TEST_MENU_WIDTH+MENU_HOR_TAB)*3, MENU_VER_TAB+(PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*3,

	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*0, MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*1,	MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*2,	MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*3,	MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*4,	MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*5,	MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*6,	MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*7,	MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*8,	MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW),
	PP_TEST_MENU_START_X+(PP_KEY_MENU_WIDTH+MENU_HOR_TAB)*9,	MENU_VER_TAB+((PP_TEST_MENU_HEIGHT+MENU_VER_TAB)*PP_TEST_MENU_LOW)
};
#endif

/*
 * Rcu와 맵핑된 문자열 테이블
 */
RCU2STR_T g_atRCU2StrTable[TOTAL_RCU_KEY] =
{
	RCU_KEY_0, "0",
	RCU_KEY_1, "1",
	RCU_KEY_2, "2",
	RCU_KEY_3, "3",
	RCU_KEY_4, "4",
	RCU_KEY_5, "5",
	RCU_KEY_6, "6",
	RCU_KEY_7, "7",
	RCU_KEY_8, "8",
	RCU_KEY_9, "9",
	RCU_KEY_11, "11",
	RCU_KEY_12, "12",
	RCU_KEY_UP, "UP",
	RCU_KEY_DOWN, "DOWN",
	RCU_KEY_LEFT, "LEFT",
	RCU_KEY_RIGHT, "RIGHT",
	RCU_KEY_OK, "OK",
	RCU_KEY_EXIT, "EXIT",
	RCU_KEY_BACK, "BACK",
	RCU_KEY_STANDBY, "STBY",
	RCU_KEY_MENU, "MENU",
	RCU_KEY_VOLUP, "VOL+",
	RCU_KEY_VOLDOWN, "VOL-",
	RCU_KEY_CHUP, "CH+",
	RCU_KEY_CHDOWN, "CH-",
	RCU_KEY_LAST, "PREV CH",
	RCU_KEY_MUTE, "MUTE",
	RCU_KEY_RED, "RED",
	RCU_KEY_GREEN, "GREEN",
	RCU_KEY_YELLOW, "YELLOW",
	RCU_KEY_BLUE, "BLUE",
	RCU_KEY_INFO, "INFO",
	RCU_KEY_TVRADIO, "TV/RADIO",
	RCU_KEY_PAUSE, "PAUSE",
	RCU_KEY_VOLUP, "VOL+",
	RCU_KEY_GUIDE, "GUIDE",
	RCU_KEY_VFORMAT, "VFORMAT",
	RCU_KEY_LIST, "LIST",
	RCU_KEY_INOUT, "IN/OUT",
	RCU_KEY_PREV, "PREV",
	RCU_KEY_SOURCE, "SOURCE",
	RCU_KEY_DATA, "D",
	RCU_KEY_DT, "DT",
	RCU_KEY_BS, "BS",
	RCU_KEY_CATV, "CATV",
};

/*
 * Front Key와 맵핑된 문자열 테이블
 */
RCU2STR_T g_atFKey2StrTable[TOTAL_FRONT_KEY] =
{
	FRONT_KEY_UP, 		"UP",
	FRONT_KEY_DOWN, 		"DOWN",
	FRONT_KEY_LEFT, 		"LEFT",
	FRONT_KEY_RIGHT,		"RIGT",
	FRONT_KEY_OK, 		"OK",
	FRONT_KEY_MENU, 		"MENU",
	FRONT_KEY_POWER, 	"STBY",
	FRONT_KEY_GUIDE, 	"GUID",
	FRONT_KEY_CHUP, 		"CHUP",
	FRONT_KEY_CHDOWN, 	"CHDN",
	FRONT_KEY_VOLUP, 	"VOUP",
	FRONT_KEY_VOLDOWN, 	"VODN",
	FRONT_KEY_TVRADIO, 	"TVRD",
	FRONT_KEY_PLAY, 		"PLAY",
	FRONT_KEY_INFO, 		"INFO",
#if defined(CONFIG_DI10)
	FRONT_KEY_REC,		"REC",
	FRONT_KEY_HDD_DISC,	"DISC",
	FRONT_KEY_LIST,		"LIST",
#endif
#if defined(CONFIG_DI20)
	FRONT_KEY_WPS, 		"WPS",
	FRONT_KEY_NETWORK, "NET",
#endif	
	FRONT_KEY_BACK, 		"BACK",
	FRONT_KEY_STOP,		"STOP",
	FRONT_KEY_EJECT,		"EJECT"
};

/******************************************************************************
* function : RCUCode2Str
* description :
* input :
* output :
* return :
* 기타 참고자료 및 파일
******************************************************************************/
char *RCUCode2Str(int nCode)
{
	int i;

	if( nCode == RCU_KEY_NONE )
	{
		return NULL;
	}

	for( i = 0; i < TOTAL_RCU_KEY; i++ )
	{
		if( g_atRCU2StrTable[i].nRcuKeyCode == nCode )
		{
			return g_atRCU2StrTable[i].pcRcuStr;
		}
	}
	return NULL;
}

/******************************************************************************
* function : FKeyCode2Str
* description :
* input :
* output :
* return :
* 기타 참고자료 및 파일
******************************************************************************/
char *FKeyCode2Str(int nCode)
{
	int i;

	if( nCode == RCU_KEY_NONE )
	{
		return NULL;
	}

	for( i = 0; i < TOTAL_FRONT_KEY; i++ )
	{
		if( g_atFKey2StrTable[i].nRcuKeyCode == nCode )
		{
			return g_atFKey2StrTable[i].pcRcuStr;
		}
	}
	return NULL;
}

