obj-y += obama_init.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw

# Additional include path
ccflags-y += -I$(HLIB_DIR)/include
ccflags-y += -I$(OCTO_DIR)/main/db/include

