
#ifndef	__OM_COMMON_H__
#define	__OM_COMMON_H__


// mgr에서도 이 header 를 볼 경우가 생길 수 있기 때문에 여기에 위치함. (즉 om(xom) -> mgr(xmgr) 로 가는 msg들)
// 추후 모듈별로 이러한 msg가 많아지면, header 분리.
enum
{
	eOEVT_METASVCLIST		= eOEVT_METASVCLIST_START,

	eOEVT_METASVCLIST_CHECK_DB_INIT
};


enum
{
	eOEVT_LCNUPDATE		= eOEVT_LCNUPDATE_START,

	eOEVT_LCNUPDATE_SAVE_FAIL,
	eOEVT_LCNUPDATE_GET_INFO
};

enum
{
	eOEVT_CAS				= eOEVT_CAS_START,

	// CI Plust related.
	// TODO: x 계열로 분리 고려해야 한다.
	eOEVT_CAS_CI_REQUESTFILEORDATA,
	eOEVT_CAS_CI_REQUESTAPPABORT,
        // Nova for multiscreen
	eOEVT_CAS_NA_NOVA_DRMSETPARAMETER,
	eOEVT_CAS_NA_NOVA_DRMRELEASE,
	eOEVT_CAS_NA_NOVA_DRMSETNOTIFIER,
	eOEVT_CAS_NA_NOVA_CASERVICEUSAGERULES,
	eOEVT_CAS_NA_NOVA_CAPLATFORMUSAGERULES,
};

enum
{
	eOEVT_METARECLIST				= 	eOEVT_METARECLIST_START,
	eOEVT_METARECLIST_REQUEST_AUTO_DELETE,
	eOEVT_METARECLIST_PROCESS_AUTO_DELETE,
	eOEVT_METARECLIST_UPDATE_AUTO_DELETE_LIST,
	eOEVT_METARECLIST_REFRESH_AUTO_DELETE_LIST,
};

#define STORAGE_SIZE_FOR_HD_PER_HOUR (4)
#define STORAGE_SIZE_FOR_SD_PER_HOUR (1.5)



#endif


