/*
 * (c) 1997-2015 Netflix, Inc.  All content herein is protected by
 * U.S. copyright and other applicable intellectual property laws and
 * may not be copied without the express permission of Netflix, Inc.,
 * which reserves all rights.  Reuse of any of this content for any
 * purpose without the permission of Netflix, Inc. is strictly
 * prohibited.
 */

#include "AppThread.h"
using namespace netflix;

DEFINE_THREAD(SMAPS_COLLECTOR, 0);

DEFINE_THREAD(GIBBON_CONSOLE, 0);
DEFINE_THREAD(GIBBON_SURFACE_LOADER, 0, 128*1024);
DEFINE_THREAD(GIBBON_ANIMATION, 70, 128*1024);
DEFINE_THREAD(GIBBON_FLIP, 70, 0);
DEFINE_THREAD(GIBBON_MAIN, 70, 5*1024*1024);
DEFINE_THREAD(GIBBON_SURFACE_CONTROLLER, 70);
DEFINE_THREAD(NBPD_MONGOOSE, 0);
DEFINE_THREAD(GIBBON_REMOTESCREEN_SERVER, 70);
DEFINE_THREAD(GIBBON_REMOTESCREEN_CONNECTION, 70);
DEFINE_THREAD(GIBBON_REMOTESCREEN_CONNECTION_WRITER, 70);
DEFINE_THREAD(GIBBON_SHUTDOWN, 0, 0);

DEFINE_THREAD(REFERENCE_DPI_ALSA_AUDIO, 0);
DEFINE_THREAD(REFERENCE_DPI_NETWORKMONITOR, 40, 32*1024);
DEFINE_THREAD(REFERENCE_DPI_SYSTEM, 80, 128*1024);
DEFINE_THREAD(REFERENCE_DPI_DUMMY_AUDIO, 0);
DEFINE_THREAD(REFERENCE_DPI_VIDEO_DISPLAY, 80, 32*1024);
DEFINE_THREAD(REFERENCE_DPI_VIDEO_DECODER, 85, 32*1024);
DEFINE_THREAD(REFERENCE_DPI_AUDIO_DECODER, 80);
DEFINE_THREAD(SKELETON_DPI_VIDEO_DECODER, 85, 32*1024);
DEFINE_THREAD(SKELETON_DPI_AUDIO_DECODER, 80);
DEFINE_THREAD(REFERENCE_DPI_TEXTTOSPEECH, 0);
DEFINE_THREAD(REFERENCE_DPI_TEXTTOSPEECH_AUDIO, 0);
DEFINE_THREAD(SINK_DPI_AV, 0, 32*1024);
