-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = syncgeneratelicensechallenges

DRM_MODULE_CFLAGS = 

SOURCES =                \
	syncgeneratelicensechallenges.c 
	
endif	
   
include $(DRM_SOURCE_PATH)/default.mak
