obj-y += ../../main/

obj-y += test_cwmp.o
obj-y += test_hcwmp_engine.o


ccflags-y += -I$(THIRDPARTY_DIR)/CUnit/include
ccflags-y += -I$(THIRDPARTY_DIR)/tr069/include
ccflags-y += -I$(REMA_MAIN_DIR)/include
ccflags-y += -I$(REMA_MAIN_DIR)/
ccflags-y += -I$(OCTOSVC_SRC_DIR)/rema/unitary_test/

