obj-y += pmgr_snmp_mib.o
#obj-y += xmgr_snmp_mib.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
# ccflags-y += -I$(OCTO_TVMANAGER_DIR)/ap_core/include

