obj-y += pal_key.o

# Basic include path
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.pal
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/pal/include
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/include
# Additional include path

