/**@@@+++@@@@******************************************************************
**
** Microsoft (r) PlayReady (r)
** Copyright (c) Microsoft Corporation. All rights reserved.
**
***@@@---@@@@******************************************************************
*/

#include <drmtypes.h>
#include <drmactivationconstants.h>

ENTER_PK_NAMESPACE_CODE;

/*
** ---------------------------------------------------------------
** XML strings used in the construction of an activation challenge
** ---------------------------------------------------------------
*/

/* "ActivateResult/payload/primaryPayload" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchActivationResponsePrimaryPayloadPath [] = { INIT_CHAR_OBFUS('A'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('R'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('P'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrActivationResponsePrimaryPayloadPath =
    CREATE_DRM_ANSI_STRING_EX( g_rgchActivationResponsePrimaryPayloadPath, 37 );

/* "ActivateResult/payload/auxilaryPayloadUrl" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchActivationResponseAuxPayloadUrlPath [] = { INIT_CHAR_OBFUS('A'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('R'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('P'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('U'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrActivationResponseAuxPayloadUrlPath =
    CREATE_DRM_ANSI_STRING_EX( g_rgchActivationResponseAuxPayloadUrlPath, 41 );

/* "ActivateResponse" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchActivationResponseTag [] = { INIT_CHAR_OBFUS('A'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('R'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrActivationResponseTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchActivationResponseTag, 16 );

/* "ActivateResult" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchActivationResultTag [] = { INIT_CHAR_OBFUS('A'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('R'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrActivationResultTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchActivationResultTag, 14 );

/* "auxilaryPayloadUrl" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchauxilaryPayloadUrlTag [] = { INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('P'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('U'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrauxilaryPayloadUrlTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchauxilaryPayloadUrlTag, 18 );

/* "Activate" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchActivationRequestTag [] = { INIT_CHAR_OBFUS('A'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrActivationRequestTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchActivationRequestTag, 8 );

/* "http://schemas.microsoft.com/PlayReady/ActivationService/v1" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchActivationServiceNamespaceV1AttribValue [] = { INIT_CHAR_OBFUS('h'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('h'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('.'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('f'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('.'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('P'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('R'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('A'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('S'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('1'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrActivationServiceNamespaceV1AttribValue =
    CREATE_DRM_ANSI_STRING_EX( g_rgchActivationServiceNamespaceV1AttribValue, 59 );

/* "clientSdkVersion" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchclientSdkVersionTag [] = { INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('S'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('k'), INIT_CHAR_OBFUS('V'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrclientSdkVersionTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchclientSdkVersionTag, 16 );

/* "clientSdkType" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchclientSdkTypeTag [] = { INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('S'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('k'), INIT_CHAR_OBFUS('T'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrclientSdkTypeTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchclientSdkTypeTag, 13 );

/* "platform" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchplatformTag [] = { INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('f'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrplatformTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchplatformTag, 8 );

/* "tid" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchtidTag [] = { INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrtidTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchtidTag, 3 );

/* "payload" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchpayloadTag [] = { INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrpayloadTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchpayloadTag, 7 );

/* "primaryPayload" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchprimaryPayloadTag [] = { INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('P'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrprimaryPayloadTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchprimaryPayloadTag, 14 );

/* "auxilaryPayload" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchauxilaryPayloadTag [] = { INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('P'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrauxilaryPayloadTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchauxilaryPayloadTag, 15 );

/* "wsdl:service" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchwsdlServiceTag [] = { INIT_CHAR_OBFUS('w'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrwsdlServiceTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchwsdlServiceTag, 12 );

/* "name" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchnameAttribute [] = { INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrnameAttribute =
    CREATE_DRM_ANSI_STRING_EX( g_rgchnameAttribute, 4 );

/* "WsHandler" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchwsdlServiceNameAttributeValue [] = { INIT_CHAR_OBFUS('W'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('H'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrwsdlServiceNameAttributeValue =
    CREATE_DRM_ANSI_STRING_EX( g_rgchwsdlServiceNameAttributeValue, 9 );

/* "wsdl:port" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchwsdlPortTag [] = { INIT_CHAR_OBFUS('w'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrwsdlPortTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchwsdlPortTag, 9 );

/* "WsHandlerHttpPost" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchwsdlPortNameAttributeValue [] = { INIT_CHAR_OBFUS('W'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('H'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('H'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('P'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrwsdlPortNameAttributeValue =
    CREATE_DRM_ANSI_STRING_EX( g_rgchwsdlPortNameAttributeValue, 17 );

/* "http:address" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchhttpAddressTag [] = { INIT_CHAR_OBFUS('h'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrhttpAddressTag =
    CREATE_DRM_ANSI_STRING_EX( g_rgchhttpAddressTag, 12 );

/* "location" */
DRM_STR_CONST DRM_EXPORT_VAR DRM_CHAR g_rgchlocationAttributeName [] = { INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('\0')};
const DRM_EXPORT_VAR DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrlocationAttributeName =
    CREATE_DRM_ANSI_STRING_EX( g_rgchlocationAttributeName, 8 );

EXIT_PK_NAMESPACE_CODE;
