/**@@@+++@@@@******************************************************************
**
** Microsoft (r) PlayReady (r)
** Copyright (c) Microsoft Corporation. All rights reserved.
**
***@@@---@@@@******************************************************************
*/

#include <drmtypes.h>
#include <drmsoapxmlconstants.h>

ENTER_PK_NAMESPACE_CODE;

/*
** -------------------------------------------------------------------
** XML strings used in the parsing of status code from server response
** -------------------------------------------------------------------
*/
/* "detail/Exception" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPExceptionRootPath [] = { INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('E'), INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPExceptionRootPath = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPExceptionRootPath, 16 );


/* "detail/Signature" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPExceptionSignaturePath [] = { INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('S'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('g'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPExceptionSignaturePath = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPExceptionSignaturePath, 16 );


/* "detail/Exception/StatusCode" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPStatusCodePath [] = { INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('E'), INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('S'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('C'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPStatusCodePath = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPStatusCodePath, 27 );

/* "detail/Exception/CustomData" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPExceptionCustomDataPath [] = { INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('E'), INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('C'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('D'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPExceptionCustomDataPath = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPExceptionCustomDataPath, 27 );

/* "CustomData" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPGARDCustomDataPath [] = { INIT_CHAR_OBFUS('C'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('D'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPGARDCustomDataPath = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPGARDCustomDataPath, 10 );


/* "RedirectUrl" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPGARDRedirectUrlPath [] = { INIT_CHAR_OBFUS('R'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('U'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPGARDRedirectUrlPath = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPGARDRedirectUrlPath, 11 );


/* "ServiceId" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPGARDServiceIdPath [] = { INIT_CHAR_OBFUS('S'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('I'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPGARDServiceIdPath = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPGARDServiceIdPath, 9 );


/* "AccountId" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPGARDAccountIdPath [] = { INIT_CHAR_OBFUS('A'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('I'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPGARDAccountIdPath = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPGARDAccountIdPath, 9 );



/*
** -----------------------------------------------------
** XML strings used in the construction of SOAP envelope
** -----------------------------------------------------
*/
/* "<?xml version= 1.0  encoding= utf-8 ?>" */
DRM_STR_CONST DRM_CHAR g_rgchXMLRootTag [] = { INIT_CHAR_OBFUS('<'), INIT_CHAR_OBFUS('?'), INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS(' '), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('='), INIT_CHAR_OBFUS('"'), INIT_CHAR_OBFUS('1'), INIT_CHAR_OBFUS('.'), INIT_CHAR_OBFUS('0'), INIT_CHAR_OBFUS('"'), INIT_CHAR_OBFUS(' '), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('g'), INIT_CHAR_OBFUS('='), INIT_CHAR_OBFUS('"'), INIT_CHAR_OBFUS('u'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('f'), INIT_CHAR_OBFUS('-'), INIT_CHAR_OBFUS('8'), INIT_CHAR_OBFUS('"'), INIT_CHAR_OBFUS('?'), INIT_CHAR_OBFUS('>'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrXMLRootTag = CREATE_DRM_ANSI_STRING_EX( g_rgchXMLRootTag, 38 );


/* "soap:Envelope" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPEnvelopeTag [] = { INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('E'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPEnvelopeTag = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPEnvelopeTag, 13 );

/* "s:Envelope" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPEnvelopeAbbrevTag [] = { INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('E'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPEnvelopeAbbrevTag = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPEnvelopeAbbrevTag, 10 );

/* "soap:Body" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPBodyTag [] = { INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('B'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPBodyTag = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPBodyTag, 9 );

/* "s:Body" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPBodyAbbrevTag [] = { INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('B'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('y'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPBodyAbbrevTag = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPBodyAbbrevTag, 6 );



/* "xmlns:xsi" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPEnvelopeAttrib1Name [] = { INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPEnvelopeAttrib1Name = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPEnvelopeAttrib1Name, 9 );

/* "http://www.w3.org/2001/XMLSchema-instance" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPEnvelopeAttrib1Value [] = { INIT_CHAR_OBFUS('h'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('w'), INIT_CHAR_OBFUS('w'), INIT_CHAR_OBFUS('w'), INIT_CHAR_OBFUS('.'), INIT_CHAR_OBFUS('w'), INIT_CHAR_OBFUS('3'), INIT_CHAR_OBFUS('.'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('g'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('2'), INIT_CHAR_OBFUS('0'), INIT_CHAR_OBFUS('0'), INIT_CHAR_OBFUS('1'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('X'), INIT_CHAR_OBFUS('M'), INIT_CHAR_OBFUS('L'), INIT_CHAR_OBFUS('S'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('h'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('-'), INIT_CHAR_OBFUS('i'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPEnvelopeAttrib1Value = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPEnvelopeAttrib1Value, 41 );


/* "xmlns:xsd" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPEnvelopeAttrib2Name [] = { INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('d'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPEnvelopeAttrib2Name = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPEnvelopeAttrib2Name, 9 );

/* "http://www.w3.org/2001/XMLSchema" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPEnvelopeAttrib2Value [] = { INIT_CHAR_OBFUS('h'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('w'), INIT_CHAR_OBFUS('w'), INIT_CHAR_OBFUS('w'), INIT_CHAR_OBFUS('.'), INIT_CHAR_OBFUS('w'), INIT_CHAR_OBFUS('3'), INIT_CHAR_OBFUS('.'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('g'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('2'), INIT_CHAR_OBFUS('0'), INIT_CHAR_OBFUS('0'), INIT_CHAR_OBFUS('1'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('X'), INIT_CHAR_OBFUS('M'), INIT_CHAR_OBFUS('L'), INIT_CHAR_OBFUS('S'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('h'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPEnvelopeAttrib2Value = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPEnvelopeAttrib2Value, 32 );


/* "xmlns:soap" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPEnvelopeAttrib3Name [] = { INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPEnvelopeAttrib3Name = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPEnvelopeAttrib3Name, 10 );

/* "http://schemas.xmlsoap.org/soap/envelope/" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPEnvelopeAttrib3Value [] = { INIT_CHAR_OBFUS('h'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('t'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('h'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('.'), INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('.'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('g'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('n'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS('o'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('/'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPEnvelopeAttrib3Value = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPEnvelopeAttrib3Value, 41 );

/* "xml:space" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPPreserveSpaceAttribName [] = { INIT_CHAR_OBFUS('x'), INIT_CHAR_OBFUS('m'), INIT_CHAR_OBFUS('l'), INIT_CHAR_OBFUS(':'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('a'), INIT_CHAR_OBFUS('c'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPPreserveSpaceAttribName = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPPreserveSpaceAttribName, 9 );

/* "preserve" */
DRM_STR_CONST DRM_CHAR g_rgchSOAPPreserveSpaceAttribValue [] = { INIT_CHAR_OBFUS('p'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('s'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('r'), INIT_CHAR_OBFUS('v'), INIT_CHAR_OBFUS('e'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrSOAPPreserveSpaceAttribValue = CREATE_DRM_ANSI_STRING_EX( g_rgchSOAPPreserveSpaceAttribValue, 8 );

/*
** -------------------------------------------------------
** XML strings used in the construction of ClientInfo node
** -------------------------------------------------------
*/
DRM_STR_CONST                DRM_CHAR       g_rgchReqTagClientInfo                       [] = { INIT_CHAR_OBFUS('C'), INIT_CHAR_OBFUS('L'), INIT_CHAR_OBFUS('I'), INIT_CHAR_OBFUS('E'), INIT_CHAR_OBFUS('N'), INIT_CHAR_OBFUS('T'), INIT_CHAR_OBFUS('I'), INIT_CHAR_OBFUS('N'), INIT_CHAR_OBFUS('F'), INIT_CHAR_OBFUS('O'), INIT_CHAR_OBFUS('\0')};
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrReqTagClientInfo                     = CREATE_DRM_ANSI_STRING_EX( g_rgchReqTagClientInfo, 10);

DRM_STR_CONST                DRM_CHAR       g_rgchReqTagClientVersion                    [] = { INIT_CHAR_OBFUS('C'), INIT_CHAR_OBFUS('L'), INIT_CHAR_OBFUS('I'), INIT_CHAR_OBFUS('E'), INIT_CHAR_OBFUS('N'), INIT_CHAR_OBFUS('T'), INIT_CHAR_OBFUS('V'), INIT_CHAR_OBFUS('E'), INIT_CHAR_OBFUS('R'), INIT_CHAR_OBFUS('S'), INIT_CHAR_OBFUS('I'), INIT_CHAR_OBFUS('O'), INIT_CHAR_OBFUS('N'), INIT_CHAR_OBFUS('\0')};    /* ODD count */
const DRM_DISCARDABLE DRM_ANSI_CONST_STRING g_dastrReqTagClientVersion                  = CREATE_DRM_ANSI_STRING_EX( g_rgchReqTagClientVersion, 13);

EXIT_PK_NAMESPACE_CODE;

