obj-y += apk_network.o
obj-y += apk_network_wifi.o
obj-y += apk_network_netconfig.o
obj-y += apk_network_dhcpserver.o
obj-y += apk_network_cablemodem.o
obj-y += apk_network_bluetooth.o
obj-y += apk_network_pppoe.o
obj-y += apk_network_concheck.o


ccflags-y += -I$(OCTOTOP_SRC_DIR)/appkit/local_include
ccflags-y += -I$(OCTOTOP_SRC_DIR)/service/nima/include
ccflags-y += -I$(OCTOTOP_SRC_DIR)/service/nima/include/modules

