obj-y += ir_main.o
obj-y += ir_mgr.o
obj-y += ir_api.o
obj-y += ir_evt.o
obj-y += ir_nvr.o
obj-y += ir_msg.o

obj-y += control/
obj-y += module/
obj-y += os/
obj-y += sup/
obj-y += util/
obj-y += vd/

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path