obj-y += mempool.o
obj-y += timeconv.o
obj-y += ttx_decoder.o
obj-y += ttx_errchk.o
obj-y += ttx_top.o
obj-y += ttx_drcs.o
obj-y += ttx_charmap.o
obj-y += ttx_graphics.o
obj-y += teletext.o
obj-y += nx_prism_teletext.o
obj-y += nx_prism_teletextui.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include

# Additional include path
ccflags-y += -I$(NATIVEAPP_UI_INCLUDE_DIR)/teletext/include
cclfags-y += -IS(NATIVEAPP_UI_INCLUDE_DIR)/include
ccflags-y += -I$(NATIVEAPP_PORT_INCLUDE_DIR)/include