obj-y += nx_prism_system_rsv.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include

# Additional include path
cclfags-y += -IS(NATIVEAPP_UI_INCLUDE_DIR)/include
ccflags-y += -I$(NATIVEAPP_PORT_INCLUDE_DIR)/include