-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = meteringsigncertificate

DRM_MODULE_CFLAGS =

SOURCES =                \
	metercert.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
