obj-y += ap_mheg_ib_mgr.o
obj-y += pmgr_mhegib.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xport

# Additional include path
ccflags-y += -I$(OCTO_THIRDPARTY_PORT_DIR)/mhegib/local_include