-include ./dirs

ifeq ($(DIRS),)
TARGET = secureclockreal

SOURCES =                \
	secureclockutil.c secureclockrequest.c secureclockresponse.c secureclockmanager.c
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
