/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on              Thu Feb 20 15:33:52 2014
 *                 Full Compile MD5 Checksum 1766fea499add5f6ee91330ef96d35c5
 *                   (minus title and desc)
 *                 MD5 Checksum              4c358fb5b94802f03aec82d8df2c9afa
 *
 * Compiled with:  RDB Utility               combo_header.pl
 *                 RDB Parser                3.0
 *                 unknown                   unknown
 *                 Perl Interpreter          5.008008
 *                 Operating System          linux
 *
 *
 ***************************************************************************/



/****************************************************************************
 ***************************************************************************/

#ifndef BCHP_SDS_DFT_5_H__
#define BCHP_SDS_DFT_5_H__

/***************************************************************************
 *SDS_DFT_5 - SDS DFT Register Set
 ***************************************************************************/
#define BCHP_SDS_DFT_5_CTRL0                     0x04500580 /* DFT Control 0 */
#define BCHP_SDS_DFT_5_CTRL1                     0x04500584 /* DFT Control 1 */
#define BCHP_SDS_DFT_5_STATUS                    0x04500588 /* DFT Status */
#define BCHP_SDS_DFT_5_RANGE_START               0x0450058c /* DFT Starting Bin */
#define BCHP_SDS_DFT_5_RANGE_END                 0x04500590 /* DFT Ending Bin */
#define BCHP_SDS_DFT_5_DDFS_FCW                  0x04500594 /* DFT DDFS Frequency Control Word */
#define BCHP_SDS_DFT_5_PEAK_POW                  0x04500598 /* DFT Peak Power */
#define BCHP_SDS_DFT_5_PEAK_BIN                  0x0450059c /* DFT Peak Bin */
#define BCHP_SDS_DFT_5_TOTAL_POW                 0x045005a0 /* DFT Total Power */
#define BCHP_SDS_DFT_5_MEM_RADDR                 0x045005a4 /* DFT Bin Memory Read Address */
#define BCHP_SDS_DFT_5_MEM_RDATA                 0x045005a8 /* DFT Bin Memory Read Data */

#endif /* #ifndef BCHP_SDS_DFT_5_H__ */

/* End of File */
