/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on              Thu Feb 20 15:33:52 2014
 *                 Full Compile MD5 Checksum 1766fea499add5f6ee91330ef96d35c5
 *                   (minus title and desc)
 *                 MD5 Checksum              4c358fb5b94802f03aec82d8df2c9afa
 *
 * Compiled with:  RDB Utility               combo_header.pl
 *                 RDB Parser                3.0
 *                 unknown                   unknown
 *                 Perl Interpreter          5.008008
 *                 Operating System          linux
 *
 *
 ***************************************************************************/



/****************************************************************************
 ***************************************************************************/

#ifndef BCHP_SDS_CG_6_H__
#define BCHP_SDS_CG_6_H__

/***************************************************************************
 *SDS_CG_6 - SDS Clockgen Register Set
 ***************************************************************************/
#define BCHP_SDS_CG_6_RSTCTL                     0x04600000 /* Reset Control */
#define BCHP_SDS_CG_6_CGDIV00                    0x04600010 /* Clock Generator Divider register 0 (Formerly,CGDIV4,CGDIV3,CGDIV7[7:4],CGMISC,CGCTRL) */
#define BCHP_SDS_CG_6_CGDIV01                    0x04600014 /* Clock Generator Divider register 1 (Formerly,CGDIV11,CGDIV10,CGDIV9,CGDIV8) */
#define BCHP_SDS_CG_6_SPLL_NPDIV                 0x04600020 /* Sample Clock PLL Feedback Divider Control */
#define BCHP_SDS_CG_6_SPLL_MDIV_CTRL             0x04600024 /* Sample Clock PLL Post-divider Control */
#define BCHP_SDS_CG_6_SPLL_CTRL                  0x04600028 /* Sample Clock PLL Control */
#define BCHP_SDS_CG_6_SPLL_SSC_CTRL1             0x0460002c /* Sample Clock PLL Spread Spectrum Control 1 */
#define BCHP_SDS_CG_6_SPLL_SSC_CTRL0             0x04600030 /* Sample Clock PLL Spread Spectrum Control 0 */
#define BCHP_SDS_CG_6_SPLL_STATUS                0x04600034 /* Sample Clock PLL Status */
#define BCHP_SDS_CG_6_SPLL_PWRDN_RST             0x04600038 /* Sample Clock PLL Power Down and Reset Control */
#define BCHP_SDS_CG_6_PMCG_CTL                   0x0460003c /* Per Module Clock Gating Control */

#endif /* #ifndef BCHP_SDS_CG_6_H__ */

/* End of File */
