obj-y += channel/
obj-y += general/
obj-$(CONFIG_MW_INET) += network/
obj-$(CONFIG_MW_MM_PVR) += pvr/
obj-y += system/
obj-$(CONFIG_APUI_SET_HIDDEN_INFO) += hidden/

obj-y += nx_prism_menu_contents.o
obj-y += nx_prism_menu_settings.o
obj-y += nx_prism_menu_items.o
obj-y += nx_prism_menu_config.o

# Additional include path
ccflags-y += -I../../../../../../../make/include

