/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_sds_oi_0.h $
 * $brcm_Revision: Hydra_Software_Devel/2 $
 * $brcm_Date: 2/4/11 4:19p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Feb  4 12:05:11 2011
 *                 MD5 Checksum         651635341c0017dd0a351cfe3d5e51fe
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/4528/rdb/a0/bchp_sds_oi_0.h $
 * 
 * Hydra_Software_Devel/2   2/4/11 4:19p ronchan
 * HW4528-2: sync up with local RDB
 *
 ***************************************************************************/

#ifndef BCHP_SDS_OI_0_H__
#define BCHP_SDS_OI_0_H__

/***************************************************************************
 *SDS_OI_0 - SDS Output Interface Register Set 0
 ***************************************************************************/
#define BCHP_SDS_OI_0_OIFCTL00                   0x000b0480 /* Output Interface Control 00 (Formerly, OIFCTL2,OIFCTL,PSCTL) */
#define BCHP_SDS_OI_0_OIFCTL01                   0x000b0484 /* Output Interface Control 01 (Formerly, OIFCTL4,OIFCTL3[15:0]) */
#define BCHP_SDS_OI_0_OIFCTL02                   0x000b0488 /* Output Interface Control 02 (Formerly, OIFCTL5) */
#define BCHP_SDS_OI_0_OPLL                       0x000b048c /* Output Interface NCO clock rate numerator */
#define BCHP_SDS_OI_0_OPLL2                      0x000b0490 /* Output Interface NCO clock rate delta */
#define BCHP_SDS_OI_0_FERC                       0x000b0494 /* Output Interface MPEG frame error counter */
#define BCHP_SDS_OI_0_FRC                        0x000b0498 /* Output Interface MPEG frame counter */
#define BCHP_SDS_OI_0_OSIGPN                     0x000b049c /* Output Interface signature analyzer */
#define BCHP_SDS_OI_0_OSUBD                      0x000b04a0 /* Output Interface PLL Sub-divider control */
#define BCHP_SDS_OI_0_OCOEF                      0x000b04a4 /* Output Interface Loop Filter Coefficient */
#define BCHP_SDS_OI_0_OFI                        0x000b04a8 /* Output Interface Loop Filter Integrator */
#define BCHP_SDS_OI_0_OPLL_NPDIV                 0x000b04b0 /* Output Interface PLL Feedback Divider Control */
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL             0x000b04b4 /* Output Interface PLL Post-divider Control */
#define BCHP_SDS_OI_0_OPLL_CTRL                  0x000b04b8 /* Output Interface PLL Control */
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL1             0x000b04bc /* Output Interface PLL Spread Spectrum Control 1 */
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL0             0x000b04c0 /* Output Interface PLL Spread Spectrum Control 0 */
#define BCHP_SDS_OI_0_OPLL_STATUS                0x000b04c4 /* Output Interface PLL Status */
#define BCHP_SDS_OI_0_OPLL_PWRDN_RST             0x000b04c8 /* Output Interface PLL Power Down and Reset Control */

/***************************************************************************
 *OIFCTL00 - Output Interface Control 00 (Formerly, OIFCTL2,OIFCTL,PSCTL)
 ***************************************************************************/
/* SDS_OI_0 :: OIFCTL00 :: reserved0 [31:24] */
#define BCHP_SDS_OI_0_OIFCTL00_reserved0_MASK                      0xff000000
#define BCHP_SDS_OI_0_OIFCTL00_reserved0_SHIFT                     24

/* SDS_OI_0 :: OIFCTL00 :: delh [23:23] */
#define BCHP_SDS_OI_0_OIFCTL00_delh_MASK                           0x00800000
#define BCHP_SDS_OI_0_OIFCTL00_delh_SHIFT                          23

/* SDS_OI_0 :: OIFCTL00 :: head4 [22:22] */
#define BCHP_SDS_OI_0_OIFCTL00_head4_MASK                          0x00400000
#define BCHP_SDS_OI_0_OIFCTL00_head4_SHIFT                         22

/* SDS_OI_0 :: OIFCTL00 :: sync1 [21:21] */
#define BCHP_SDS_OI_0_OIFCTL00_sync1_MASK                          0x00200000
#define BCHP_SDS_OI_0_OIFCTL00_sync1_SHIFT                         21

/* SDS_OI_0 :: OIFCTL00 :: pfc_insert_en [20:20] */
#define BCHP_SDS_OI_0_OIFCTL00_pfc_insert_en_MASK                  0x00100000
#define BCHP_SDS_OI_0_OIFCTL00_pfc_insert_en_SHIFT                 20

/* SDS_OI_0 :: OIFCTL00 :: pwrdown [19:19] */
#define BCHP_SDS_OI_0_OIFCTL00_pwrdown_MASK                        0x00080000
#define BCHP_SDS_OI_0_OIFCTL00_pwrdown_SHIFT                       19

/* SDS_OI_0 :: OIFCTL00 :: clrdata [18:18] */
#define BCHP_SDS_OI_0_OIFCTL00_clrdata_MASK                        0x00040000
#define BCHP_SDS_OI_0_OIFCTL00_clrdata_SHIFT                       18

/* SDS_OI_0 :: OIFCTL00 :: dither_en [17:17] */
#define BCHP_SDS_OI_0_OIFCTL00_dither_en_MASK                      0x00020000
#define BCHP_SDS_OI_0_OIFCTL00_dither_en_SHIFT                     17

/* SDS_OI_0 :: OIFCTL00 :: sense [16:16] */
#define BCHP_SDS_OI_0_OIFCTL00_sense_MASK                          0x00010000
#define BCHP_SDS_OI_0_OIFCTL00_sense_SHIFT                         16

/* SDS_OI_0 :: OIFCTL00 :: fec_sel [15:15] */
#define BCHP_SDS_OI_0_OIFCTL00_fec_sel_MASK                        0x00008000
#define BCHP_SDS_OI_0_OIFCTL00_fec_sel_SHIFT                       15

/* SDS_OI_0 :: OIFCTL00 :: err_clksup [14:14] */
#define BCHP_SDS_OI_0_OIFCTL00_err_clksup_MASK                     0x00004000
#define BCHP_SDS_OI_0_OIFCTL00_err_clksup_SHIFT                    14

/* SDS_OI_0 :: OIFCTL00 :: reserved_for_eco1 [13:13] */
#define BCHP_SDS_OI_0_OIFCTL00_reserved_for_eco1_MASK              0x00002000
#define BCHP_SDS_OI_0_OIFCTL00_reserved_for_eco1_SHIFT             13

/* SDS_OI_0 :: OIFCTL00 :: errsyncsup [12:12] */
#define BCHP_SDS_OI_0_OIFCTL00_errsyncsup_MASK                     0x00001000
#define BCHP_SDS_OI_0_OIFCTL00_errsyncsup_SHIFT                    12

/* SDS_OI_0 :: OIFCTL00 :: datainv [11:11] */
#define BCHP_SDS_OI_0_OIFCTL00_datainv_MASK                        0x00000800
#define BCHP_SDS_OI_0_OIFCTL00_datainv_SHIFT                       11

/* SDS_OI_0 :: OIFCTL00 :: xbert [10:10] */
#define BCHP_SDS_OI_0_OIFCTL00_xbert_MASK                          0x00000400
#define BCHP_SDS_OI_0_OIFCTL00_xbert_SHIFT                         10

/* SDS_OI_0 :: OIFCTL00 :: over_clking_mode [09:09] */
#define BCHP_SDS_OI_0_OIFCTL00_over_clking_mode_MASK               0x00000200
#define BCHP_SDS_OI_0_OIFCTL00_over_clking_mode_SHIFT              9

/* SDS_OI_0 :: OIFCTL00 :: tfec_afec_sel [08:08] */
#define BCHP_SDS_OI_0_OIFCTL00_tfec_afec_sel_MASK                  0x00000100
#define BCHP_SDS_OI_0_OIFCTL00_tfec_afec_sel_SHIFT                 8

/* SDS_OI_0 :: OIFCTL00 :: errinv [07:07] */
#define BCHP_SDS_OI_0_OIFCTL00_errinv_MASK                         0x00000080
#define BCHP_SDS_OI_0_OIFCTL00_errinv_SHIFT                        7

/* SDS_OI_0 :: OIFCTL00 :: syncinv [06:06] */
#define BCHP_SDS_OI_0_OIFCTL00_syncinv_MASK                        0x00000040
#define BCHP_SDS_OI_0_OIFCTL00_syncinv_SHIFT                       6

/* SDS_OI_0 :: OIFCTL00 :: vldinv [05:05] */
#define BCHP_SDS_OI_0_OIFCTL00_vldinv_MASK                         0x00000020
#define BCHP_SDS_OI_0_OIFCTL00_vldinv_SHIFT                        5

/* SDS_OI_0 :: OIFCTL00 :: clksup [04:04] */
#define BCHP_SDS_OI_0_OIFCTL00_clksup_MASK                         0x00000010
#define BCHP_SDS_OI_0_OIFCTL00_clksup_SHIFT                        4

/* SDS_OI_0 :: OIFCTL00 :: clkinv [03:03] */
#define BCHP_SDS_OI_0_OIFCTL00_clkinv_MASK                         0x00000008
#define BCHP_SDS_OI_0_OIFCTL00_clkinv_SHIFT                        3

/* SDS_OI_0 :: OIFCTL00 :: freeze [02:02] */
#define BCHP_SDS_OI_0_OIFCTL00_freeze_MASK                         0x00000004
#define BCHP_SDS_OI_0_OIFCTL00_freeze_SHIFT                        2

/* SDS_OI_0 :: OIFCTL00 :: serial [01:01] */
#define BCHP_SDS_OI_0_OIFCTL00_serial_MASK                         0x00000002
#define BCHP_SDS_OI_0_OIFCTL00_serial_SHIFT                        1

/* SDS_OI_0 :: OIFCTL00 :: reset [00:00] */
#define BCHP_SDS_OI_0_OIFCTL00_reset_MASK                          0x00000001
#define BCHP_SDS_OI_0_OIFCTL00_reset_SHIFT                         0

/***************************************************************************
 *OIFCTL01 - Output Interface Control 01 (Formerly, OIFCTL4,OIFCTL3[15:0])
 ***************************************************************************/
/* SDS_OI_0 :: OIFCTL01 :: reserved0 [31:24] */
#define BCHP_SDS_OI_0_OIFCTL01_reserved0_MASK                      0xff000000
#define BCHP_SDS_OI_0_OIFCTL01_reserved0_SHIFT                     24

/* SDS_OI_0 :: OIFCTL01 :: xbyp_en [23:23] */
#define BCHP_SDS_OI_0_OIFCTL01_xbyp_en_MASK                        0x00800000
#define BCHP_SDS_OI_0_OIFCTL01_xbyp_en_SHIFT                       23

/* SDS_OI_0 :: OIFCTL01 :: mpeg_frame_snap [22:22] */
#define BCHP_SDS_OI_0_OIFCTL01_mpeg_frame_snap_MASK                0x00400000
#define BCHP_SDS_OI_0_OIFCTL01_mpeg_frame_snap_SHIFT               22

/* SDS_OI_0 :: OIFCTL01 :: mpeg_frame_reset [21:21] */
#define BCHP_SDS_OI_0_OIFCTL01_mpeg_frame_reset_MASK               0x00200000
#define BCHP_SDS_OI_0_OIFCTL01_mpeg_frame_reset_SHIFT              21

/* SDS_OI_0 :: OIFCTL01 :: oif_sigpn_set [20:20] */
#define BCHP_SDS_OI_0_OIFCTL01_oif_sigpn_set_MASK                  0x00100000
#define BCHP_SDS_OI_0_OIFCTL01_oif_sigpn_set_SHIFT                 20

/* SDS_OI_0 :: OIFCTL01 :: rfreeze [19:19] */
#define BCHP_SDS_OI_0_OIFCTL01_rfreeze_MASK                        0x00080000
#define BCHP_SDS_OI_0_OIFCTL01_rfreeze_SHIFT                       19

/* SDS_OI_0 :: OIFCTL01 :: xbert_decphs [18:18] */
#define BCHP_SDS_OI_0_OIFCTL01_xbert_decphs_MASK                   0x00040000
#define BCHP_SDS_OI_0_OIFCTL01_xbert_decphs_SHIFT                  18

/* SDS_OI_0 :: OIFCTL01 :: reserved_for_eco1 [17:17] */
#define BCHP_SDS_OI_0_OIFCTL01_reserved_for_eco1_MASK              0x00020000
#define BCHP_SDS_OI_0_OIFCTL01_reserved_for_eco1_SHIFT             17

/* SDS_OI_0 :: OIFCTL01 :: xbert_dec2 [16:16] */
#define BCHP_SDS_OI_0_OIFCTL01_xbert_dec2_MASK                     0x00010000
#define BCHP_SDS_OI_0_OIFCTL01_xbert_dec2_SHIFT                    16

/* SDS_OI_0 :: OIFCTL01 :: reserved_for_eco2 [15:15] */
#define BCHP_SDS_OI_0_OIFCTL01_reserved_for_eco2_MASK              0x00008000
#define BCHP_SDS_OI_0_OIFCTL01_reserved_for_eco2_SHIFT             15

/* SDS_OI_0 :: OIFCTL01 :: opll_byt_clk_sel [14:13] */
#define BCHP_SDS_OI_0_OIFCTL01_opll_byt_clk_sel_MASK               0x00006000
#define BCHP_SDS_OI_0_OIFCTL01_opll_byt_clk_sel_SHIFT              13

/* SDS_OI_0 :: OIFCTL01 :: out_data_dec [12:11] */
#define BCHP_SDS_OI_0_OIFCTL01_out_data_dec_MASK                   0x00001800
#define BCHP_SDS_OI_0_OIFCTL01_out_data_dec_SHIFT                  11

/* SDS_OI_0 :: OIFCTL01 :: loop_en [10:10] */
#define BCHP_SDS_OI_0_OIFCTL01_loop_en_MASK                        0x00000400
#define BCHP_SDS_OI_0_OIFCTL01_loop_en_SHIFT                       10

/* SDS_OI_0 :: OIFCTL01 :: byt_clk_sel [09:08] */
#define BCHP_SDS_OI_0_OIFCTL01_byt_clk_sel_MASK                    0x00000300
#define BCHP_SDS_OI_0_OIFCTL01_byt_clk_sel_SHIFT                   8

/* SDS_OI_0 :: OIFCTL01 :: reserved_for_eco3 [07:07] */
#define BCHP_SDS_OI_0_OIFCTL01_reserved_for_eco3_MASK              0x00000080
#define BCHP_SDS_OI_0_OIFCTL01_reserved_for_eco3_SHIFT             7

/* SDS_OI_0 :: OIFCTL01 :: wfreeze_psvalid_off [06:06] */
#define BCHP_SDS_OI_0_OIFCTL01_wfreeze_psvalid_off_MASK            0x00000040
#define BCHP_SDS_OI_0_OIFCTL01_wfreeze_psvalid_off_SHIFT           6

/* SDS_OI_0 :: OIFCTL01 :: reserved_for_eco4 [05:05] */
#define BCHP_SDS_OI_0_OIFCTL01_reserved_for_eco4_MASK              0x00000020
#define BCHP_SDS_OI_0_OIFCTL01_reserved_for_eco4_SHIFT             5

/* SDS_OI_0 :: OIFCTL01 :: opll_byp [04:04] */
#define BCHP_SDS_OI_0_OIFCTL01_opll_byp_MASK                       0x00000010
#define BCHP_SDS_OI_0_OIFCTL01_opll_byp_SHIFT                      4

/* SDS_OI_0 :: OIFCTL01 :: wfreeze [03:03] */
#define BCHP_SDS_OI_0_OIFCTL01_wfreeze_MASK                        0x00000008
#define BCHP_SDS_OI_0_OIFCTL01_wfreeze_SHIFT                       3

/* SDS_OI_0 :: OIFCTL01 :: oifbyp [02:02] */
#define BCHP_SDS_OI_0_OIFCTL01_oifbyp_MASK                         0x00000004
#define BCHP_SDS_OI_0_OIFCTL01_oifbyp_SHIFT                        2

/* SDS_OI_0 :: OIFCTL01 :: oc_rst [01:01] */
#define BCHP_SDS_OI_0_OIFCTL01_oc_rst_MASK                         0x00000002
#define BCHP_SDS_OI_0_OIFCTL01_oc_rst_SHIFT                        1

/* SDS_OI_0 :: OIFCTL01 :: reserved_for_eco5 [00:00] */
#define BCHP_SDS_OI_0_OIFCTL01_reserved_for_eco5_MASK              0x00000001
#define BCHP_SDS_OI_0_OIFCTL01_reserved_for_eco5_SHIFT             0

/***************************************************************************
 *OIFCTL02 - Output Interface Control 02 (Formerly, OIFCTL5)
 ***************************************************************************/
/* SDS_OI_0 :: OIFCTL02 :: reserved0 [31:24] */
#define BCHP_SDS_OI_0_OIFCTL02_reserved0_MASK                      0xff000000
#define BCHP_SDS_OI_0_OIFCTL02_reserved0_SHIFT                     24

/* SDS_OI_0 :: OIFCTL02 :: ps_clk_dly_sel [23:20] */
#define BCHP_SDS_OI_0_OIFCTL02_ps_clk_dly_sel_MASK                 0x00f00000
#define BCHP_SDS_OI_0_OIFCTL02_ps_clk_dly_sel_SHIFT                20

/* SDS_OI_0 :: OIFCTL02 :: ps_sync_dly_sel [19:16] */
#define BCHP_SDS_OI_0_OIFCTL02_ps_sync_dly_sel_MASK                0x000f0000
#define BCHP_SDS_OI_0_OIFCTL02_ps_sync_dly_sel_SHIFT               16

/* SDS_OI_0 :: OIFCTL02 :: ps_valid_dly_sel [15:12] */
#define BCHP_SDS_OI_0_OIFCTL02_ps_valid_dly_sel_MASK               0x0000f000
#define BCHP_SDS_OI_0_OIFCTL02_ps_valid_dly_sel_SHIFT              12

/* SDS_OI_0 :: OIFCTL02 :: ps_err_dly_sel [11:08] */
#define BCHP_SDS_OI_0_OIFCTL02_ps_err_dly_sel_MASK                 0x00000f00
#define BCHP_SDS_OI_0_OIFCTL02_ps_err_dly_sel_SHIFT                8

/* SDS_OI_0 :: OIFCTL02 :: ps_dat7_1_dly_sel [07:04] */
#define BCHP_SDS_OI_0_OIFCTL02_ps_dat7_1_dly_sel_MASK              0x000000f0
#define BCHP_SDS_OI_0_OIFCTL02_ps_dat7_1_dly_sel_SHIFT             4

/* SDS_OI_0 :: OIFCTL02 :: ps_dat0_dly_sel [03:00] */
#define BCHP_SDS_OI_0_OIFCTL02_ps_dat0_dly_sel_MASK                0x0000000f
#define BCHP_SDS_OI_0_OIFCTL02_ps_dat0_dly_sel_SHIFT               0

/***************************************************************************
 *OPLL - Output Interface NCO clock rate numerator
 ***************************************************************************/
/* SDS_OI_0 :: OPLL :: numerator [31:00] */
#define BCHP_SDS_OI_0_OPLL_numerator_MASK                          0xffffffff
#define BCHP_SDS_OI_0_OPLL_numerator_SHIFT                         0

/***************************************************************************
 *OPLL2 - Output Interface NCO clock rate delta
 ***************************************************************************/
/* SDS_OI_0 :: OPLL2 :: delta [31:00] */
#define BCHP_SDS_OI_0_OPLL2_delta_MASK                             0xffffffff
#define BCHP_SDS_OI_0_OPLL2_delta_SHIFT                            0

/***************************************************************************
 *FERC - Output Interface MPEG frame error counter
 ***************************************************************************/
/* SDS_OI_0 :: FERC :: mpeg_errcnt [31:00] */
#define BCHP_SDS_OI_0_FERC_mpeg_errcnt_MASK                        0xffffffff
#define BCHP_SDS_OI_0_FERC_mpeg_errcnt_SHIFT                       0

/***************************************************************************
 *FRC - Output Interface MPEG frame counter
 ***************************************************************************/
/* SDS_OI_0 :: FRC :: mpeg_cnt [31:00] */
#define BCHP_SDS_OI_0_FRC_mpeg_cnt_MASK                            0xffffffff
#define BCHP_SDS_OI_0_FRC_mpeg_cnt_SHIFT                           0

/***************************************************************************
 *OSIGPN - Output Interface signature analyzer
 ***************************************************************************/
/* SDS_OI_0 :: OSIGPN :: OSIGPN [31:00] */
#define BCHP_SDS_OI_0_OSIGPN_OSIGPN_MASK                           0xffffffff
#define BCHP_SDS_OI_0_OSIGPN_OSIGPN_SHIFT                          0

/***************************************************************************
 *OSUBD - Output Interface PLL Sub-divider control
 ***************************************************************************/
/* SDS_OI_0 :: OSUBD :: reserved0 [31:08] */
#define BCHP_SDS_OI_0_OSUBD_reserved0_MASK                         0xffffff00
#define BCHP_SDS_OI_0_OSUBD_reserved0_SHIFT                        8

/* SDS_OI_0 :: OSUBD :: reserved_for_eco1 [07:07] */
#define BCHP_SDS_OI_0_OSUBD_reserved_for_eco1_MASK                 0x00000080
#define BCHP_SDS_OI_0_OSUBD_reserved_for_eco1_SHIFT                7

/* SDS_OI_0 :: OSUBD :: low_baud [06:06] */
#define BCHP_SDS_OI_0_OSUBD_low_baud_MASK                          0x00000040
#define BCHP_SDS_OI_0_OSUBD_low_baud_SHIFT                         6

/* SDS_OI_0 :: OSUBD :: reserved_for_eco2 [05:05] */
#define BCHP_SDS_OI_0_OSUBD_reserved_for_eco2_MASK                 0x00000020
#define BCHP_SDS_OI_0_OSUBD_reserved_for_eco2_SHIFT                5

/* SDS_OI_0 :: OSUBD :: subd_ratio [04:00] */
#define BCHP_SDS_OI_0_OSUBD_subd_ratio_MASK                        0x0000001f
#define BCHP_SDS_OI_0_OSUBD_subd_ratio_SHIFT                       0

/***************************************************************************
 *OCOEF - Output Interface Loop Filter Coefficient
 ***************************************************************************/
/* SDS_OI_0 :: OCOEF :: oif_k1 [31:28] */
#define BCHP_SDS_OI_0_OCOEF_oif_k1_MASK                            0xf0000000
#define BCHP_SDS_OI_0_OCOEF_oif_k1_SHIFT                           28

/* SDS_OI_0 :: OCOEF :: oif_k0 [27:24] */
#define BCHP_SDS_OI_0_OCOEF_oif_k0_MASK                            0x0f000000
#define BCHP_SDS_OI_0_OCOEF_oif_k0_SHIFT                           24

/* SDS_OI_0 :: OCOEF :: reserved0 [23:00] */
#define BCHP_SDS_OI_0_OCOEF_reserved0_MASK                         0x00ffffff
#define BCHP_SDS_OI_0_OCOEF_reserved0_SHIFT                        0

/***************************************************************************
 *OFI - Output Interface Loop Filter Integrator
 ***************************************************************************/
/* SDS_OI_0 :: OFI :: reserved0 [31:29] */
#define BCHP_SDS_OI_0_OFI_reserved0_MASK                           0xe0000000
#define BCHP_SDS_OI_0_OFI_reserved0_SHIFT                          29

/* SDS_OI_0 :: OFI :: oif_int [28:00] */
#define BCHP_SDS_OI_0_OFI_oif_int_MASK                             0x1fffffff
#define BCHP_SDS_OI_0_OFI_oif_int_SHIFT                            0

/***************************************************************************
 *OPLL_NPDIV - Output Interface PLL Feedback Divider Control
 ***************************************************************************/
/* SDS_OI_0 :: OPLL_NPDIV :: ndiv_int [31:24] */
#define BCHP_SDS_OI_0_OPLL_NPDIV_ndiv_int_MASK                     0xff000000
#define BCHP_SDS_OI_0_OPLL_NPDIV_ndiv_int_SHIFT                    24

/* SDS_OI_0 :: OPLL_NPDIV :: ndiv_frac [23:04] */
#define BCHP_SDS_OI_0_OPLL_NPDIV_ndiv_frac_MASK                    0x00fffff0
#define BCHP_SDS_OI_0_OPLL_NPDIV_ndiv_frac_SHIFT                   4

/* SDS_OI_0 :: OPLL_NPDIV :: reserved_for_eco0 [03:03] */
#define BCHP_SDS_OI_0_OPLL_NPDIV_reserved_for_eco0_MASK            0x00000008
#define BCHP_SDS_OI_0_OPLL_NPDIV_reserved_for_eco0_SHIFT           3

/* SDS_OI_0 :: OPLL_NPDIV :: pdiv [02:00] */
#define BCHP_SDS_OI_0_OPLL_NPDIV_pdiv_MASK                         0x00000007
#define BCHP_SDS_OI_0_OPLL_NPDIV_pdiv_SHIFT                        0

/***************************************************************************
 *OPLL_MDIV_CTRL - Output Interface PLL Post-divider Control
 ***************************************************************************/
/* SDS_OI_0 :: OPLL_MDIV_CTRL :: reserved0 [31:20] */
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_reserved0_MASK                0xfff00000
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_reserved0_SHIFT               20

/* SDS_OI_0 :: OPLL_MDIV_CTRL :: pll_ctrl_msb [19:11] */
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_pll_ctrl_msb_MASK             0x000ff800
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_pll_ctrl_msb_SHIFT            11

/* SDS_OI_0 :: OPLL_MDIV_CTRL :: channel_en [10:10] */
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_channel_en_MASK               0x00000400
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_channel_en_SHIFT              10

/* SDS_OI_0 :: OPLL_MDIV_CTRL :: channel_hold [09:09] */
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_channel_hold_MASK             0x00000200
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_channel_hold_SHIFT            9

/* SDS_OI_0 :: OPLL_MDIV_CTRL :: channel_load_en [08:08] */
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_channel_load_en_MASK          0x00000100
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_channel_load_en_SHIFT         8

/* SDS_OI_0 :: OPLL_MDIV_CTRL :: mdiv [07:00] */
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_mdiv_MASK                     0x000000ff
#define BCHP_SDS_OI_0_OPLL_MDIV_CTRL_mdiv_SHIFT                    0

/***************************************************************************
 *OPLL_CTRL - Output Interface PLL Control
 ***************************************************************************/
/* SDS_OI_0 :: OPLL_CTRL :: Kp [31:28] */
#define BCHP_SDS_OI_0_OPLL_CTRL_Kp_MASK                            0xf0000000
#define BCHP_SDS_OI_0_OPLL_CTRL_Kp_SHIFT                           28

/* SDS_OI_0 :: OPLL_CTRL :: Ki [27:25] */
#define BCHP_SDS_OI_0_OPLL_CTRL_Ki_MASK                            0x0e000000
#define BCHP_SDS_OI_0_OPLL_CTRL_Ki_SHIFT                           25

/* SDS_OI_0 :: OPLL_CTRL :: Ka [24:22] */
#define BCHP_SDS_OI_0_OPLL_CTRL_Ka_MASK                            0x01c00000
#define BCHP_SDS_OI_0_OPLL_CTRL_Ka_SHIFT                           22

/* SDS_OI_0 :: OPLL_CTRL :: refclk_sel [21:21] */
#define BCHP_SDS_OI_0_OPLL_CTRL_refclk_sel_MASK                    0x00200000
#define BCHP_SDS_OI_0_OPLL_CTRL_refclk_sel_SHIFT                   21

/* SDS_OI_0 :: OPLL_CTRL :: pll_ctrl [20:00] */
#define BCHP_SDS_OI_0_OPLL_CTRL_pll_ctrl_MASK                      0x001fffff
#define BCHP_SDS_OI_0_OPLL_CTRL_pll_ctrl_SHIFT                     0

/***************************************************************************
 *OPLL_SSC_CTRL1 - Output Interface PLL Spread Spectrum Control 1
 ***************************************************************************/
/* SDS_OI_0 :: OPLL_SSC_CTRL1 :: reserved0 [31:16] */
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL1_reserved0_MASK                0xffff0000
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL1_reserved0_SHIFT               16

/* SDS_OI_0 :: OPLL_SSC_CTRL1 :: ssc_step [15:00] */
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL1_ssc_step_MASK                 0x0000ffff
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL1_ssc_step_SHIFT                0

/***************************************************************************
 *OPLL_SSC_CTRL0 - Output Interface PLL Spread Spectrum Control 0
 ***************************************************************************/
/* SDS_OI_0 :: OPLL_SSC_CTRL0 :: reserved0 [31:24] */
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL0_reserved0_MASK                0xff000000
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL0_reserved0_SHIFT               24

/* SDS_OI_0 :: OPLL_SSC_CTRL0 :: reserved_for_eco1 [23:23] */
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL0_reserved_for_eco1_MASK        0x00800000
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL0_reserved_for_eco1_SHIFT       23

/* SDS_OI_0 :: OPLL_SSC_CTRL0 :: ssc_mode [22:22] */
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL0_ssc_mode_MASK                 0x00400000
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL0_ssc_mode_SHIFT                22

/* SDS_OI_0 :: OPLL_SSC_CTRL0 :: ssc_limit [21:00] */
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL0_ssc_limit_MASK                0x003fffff
#define BCHP_SDS_OI_0_OPLL_SSC_CTRL0_ssc_limit_SHIFT               0

/***************************************************************************
 *OPLL_STATUS - Output Interface PLL Status
 ***************************************************************************/
/* SDS_OI_0 :: OPLL_STATUS :: reserved0 [31:13] */
#define BCHP_SDS_OI_0_OPLL_STATUS_reserved0_MASK                   0xffffe000
#define BCHP_SDS_OI_0_OPLL_STATUS_reserved0_SHIFT                  13

/* SDS_OI_0 :: OPLL_STATUS :: lock [12:12] */
#define BCHP_SDS_OI_0_OPLL_STATUS_lock_MASK                        0x00001000
#define BCHP_SDS_OI_0_OPLL_STATUS_lock_SHIFT                       12

/* SDS_OI_0 :: OPLL_STATUS :: stat_out [11:00] */
#define BCHP_SDS_OI_0_OPLL_STATUS_stat_out_MASK                    0x00000fff
#define BCHP_SDS_OI_0_OPLL_STATUS_stat_out_SHIFT                   0

/***************************************************************************
 *OPLL_PWRDN_RST - Output Interface PLL Power Down and Reset Control
 ***************************************************************************/
/* SDS_OI_0 :: OPLL_PWRDN_RST :: reserved0 [31:08] */
#define BCHP_SDS_OI_0_OPLL_PWRDN_RST_reserved0_MASK                0xffffff00
#define BCHP_SDS_OI_0_OPLL_PWRDN_RST_reserved0_SHIFT               8

/* SDS_OI_0 :: OPLL_PWRDN_RST :: reserved_for_eco1 [07:03] */
#define BCHP_SDS_OI_0_OPLL_PWRDN_RST_reserved_for_eco1_MASK        0x000000f8
#define BCHP_SDS_OI_0_OPLL_PWRDN_RST_reserved_for_eco1_SHIFT       3

/* SDS_OI_0 :: OPLL_PWRDN_RST :: pwrdn [02:02] */
#define BCHP_SDS_OI_0_OPLL_PWRDN_RST_pwrdn_MASK                    0x00000004
#define BCHP_SDS_OI_0_OPLL_PWRDN_RST_pwrdn_SHIFT                   2

/* SDS_OI_0 :: OPLL_PWRDN_RST :: dreset [01:01] */
#define BCHP_SDS_OI_0_OPLL_PWRDN_RST_dreset_MASK                   0x00000002
#define BCHP_SDS_OI_0_OPLL_PWRDN_RST_dreset_SHIFT                  1

/* SDS_OI_0 :: OPLL_PWRDN_RST :: areset [00:00] */
#define BCHP_SDS_OI_0_OPLL_PWRDN_RST_areset_MASK                   0x00000001
#define BCHP_SDS_OI_0_OPLL_PWRDN_RST_areset_SHIFT                  0

#endif /* #ifndef BCHP_SDS_OI_0_H__ */

/* End of File */
