/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_sds_ntch_0.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 1/13/11 8:05a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Jan 12 18:40:52 2011
 *                 MD5 Checksum         6e6727f6c827233acdd395c9a9032c98
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/4528/rdb/a0/bchp_sds_ntch_0.h $
 * 
 * Hydra_Software_Devel/1   1/13/11 8:05a pntruong
 * HW4528-2: Synced up with central rdb.
 *
 ***************************************************************************/

#ifndef BCHP_SDS_NTCH_0_H__
#define BCHP_SDS_NTCH_0_H__

/***************************************************************************
 *SDS_NTCH_0 - SDS Notch Filter Register Set 0
 ***************************************************************************/
#define BCHP_SDS_NTCH_0_CTRL                     0x000b05c0 /* Notch Filter Controb */
#define BCHP_SDS_NTCH_0_FCWADJ_SCL               0x000b05c4 /* Notch Filter FCW Adjustment Scale */
#define BCHP_SDS_NTCH_0_FCW0                     0x000b05c8 /* Notch Filter 0 DDFS Frequency Control Word */
#define BCHP_SDS_NTCH_0_FCW1                     0x000b05cc /* Notch Filter 1 DDFS Frequency Control Word */
#define BCHP_SDS_NTCH_0_FCW2                     0x000b05d0 /* Notch Filter 2 DDFS Frequency Control Word */
#define BCHP_SDS_NTCH_0_FCW3                     0x000b05d4 /* Notch Filter DDFS Combined Frequency Control Word */
#define BCHP_SDS_NTCH_0_DCO0_INT                 0x000b05d8 /* Notch Filter 0 BB DC Canceller Loop Integrator */
#define BCHP_SDS_NTCH_0_DCO1_INT                 0x000b05dc /* Notch Filter 1 BB DC Canceller Loop Integrator */
#define BCHP_SDS_NTCH_0_DCO2_INT                 0x000b05e0 /* Notch Filter 2 BB DC Canceller Loop Integrator */

/***************************************************************************
 *CTRL - Notch Filter Controb
 ***************************************************************************/
/* SDS_NTCH_0 :: CTRL :: reserved0 [31:13] */
#define BCHP_SDS_NTCH_0_CTRL_reserved0_MASK                        0xffffe000
#define BCHP_SDS_NTCH_0_CTRL_reserved0_SHIFT                       13

/* SDS_NTCH_0 :: CTRL :: notch_in_sel [12:12] */
#define BCHP_SDS_NTCH_0_CTRL_notch_in_sel_MASK                     0x00001000
#define BCHP_SDS_NTCH_0_CTRL_notch_in_sel_SHIFT                    12

/* SDS_NTCH_0 :: CTRL :: frz_notch2 [11:11] */
#define BCHP_SDS_NTCH_0_CTRL_frz_notch2_MASK                       0x00000800
#define BCHP_SDS_NTCH_0_CTRL_frz_notch2_SHIFT                      11

/* SDS_NTCH_0 :: CTRL :: frz_notch1 [10:10] */
#define BCHP_SDS_NTCH_0_CTRL_frz_notch1_MASK                       0x00000400
#define BCHP_SDS_NTCH_0_CTRL_frz_notch1_SHIFT                      10

/* SDS_NTCH_0 :: CTRL :: frz_notch0 [09:09] */
#define BCHP_SDS_NTCH_0_CTRL_frz_notch0_MASK                       0x00000200
#define BCHP_SDS_NTCH_0_CTRL_frz_notch0_SHIFT                      9

/* SDS_NTCH_0 :: CTRL :: frz_notch_ddfs [08:08] */
#define BCHP_SDS_NTCH_0_CTRL_frz_notch_ddfs_MASK                   0x00000100
#define BCHP_SDS_NTCH_0_CTRL_frz_notch_ddfs_SHIFT                  8

/* SDS_NTCH_0 :: CTRL :: notch_fcw_adj_en [07:07] */
#define BCHP_SDS_NTCH_0_CTRL_notch_fcw_adj_en_MASK                 0x00000080
#define BCHP_SDS_NTCH_0_CTRL_notch_fcw_adj_en_SHIFT                7

/* SDS_NTCH_0 :: CTRL :: byp_notch_2x [06:06] */
#define BCHP_SDS_NTCH_0_CTRL_byp_notch_2x_MASK                     0x00000040
#define BCHP_SDS_NTCH_0_CTRL_byp_notch_2x_SHIFT                    6

/* SDS_NTCH_0 :: CTRL :: byp_notch_dtpath [05:05] */
#define BCHP_SDS_NTCH_0_CTRL_byp_notch_dtpath_MASK                 0x00000020
#define BCHP_SDS_NTCH_0_CTRL_byp_notch_dtpath_SHIFT                5

/* SDS_NTCH_0 :: CTRL :: byp_notch [04:04] */
#define BCHP_SDS_NTCH_0_CTRL_byp_notch_MASK                        0x00000010
#define BCHP_SDS_NTCH_0_CTRL_byp_notch_SHIFT                       4

/* SDS_NTCH_0 :: CTRL :: notch_bbdc_rst [03:03] */
#define BCHP_SDS_NTCH_0_CTRL_notch_bbdc_rst_MASK                   0x00000008
#define BCHP_SDS_NTCH_0_CTRL_notch_bbdc_rst_SHIFT                  3

/* SDS_NTCH_0 :: CTRL :: notch_ddfs_rst [02:02] */
#define BCHP_SDS_NTCH_0_CTRL_notch_ddfs_rst_MASK                   0x00000004
#define BCHP_SDS_NTCH_0_CTRL_notch_ddfs_rst_SHIFT                  2

/* SDS_NTCH_0 :: CTRL :: notch_ctrl_rst [01:01] */
#define BCHP_SDS_NTCH_0_CTRL_notch_ctrl_rst_MASK                   0x00000002
#define BCHP_SDS_NTCH_0_CTRL_notch_ctrl_rst_SHIFT                  1

/* SDS_NTCH_0 :: CTRL :: notch_rst [00:00] */
#define BCHP_SDS_NTCH_0_CTRL_notch_rst_MASK                        0x00000001
#define BCHP_SDS_NTCH_0_CTRL_notch_rst_SHIFT                       0

/***************************************************************************
 *FCWADJ_SCL - Notch Filter FCW Adjustment Scale
 ***************************************************************************/
/* SDS_NTCH_0 :: FCWADJ_SCL :: reserved0 [31:30] */
#define BCHP_SDS_NTCH_0_FCWADJ_SCL_reserved0_MASK                  0xc0000000
#define BCHP_SDS_NTCH_0_FCWADJ_SCL_reserved0_SHIFT                 30

/* SDS_NTCH_0 :: FCWADJ_SCL :: notch_fcwadj_scale [29:00] */
#define BCHP_SDS_NTCH_0_FCWADJ_SCL_notch_fcwadj_scale_MASK         0x3fffffff
#define BCHP_SDS_NTCH_0_FCWADJ_SCL_notch_fcwadj_scale_SHIFT        0

/***************************************************************************
 *FCW0 - Notch Filter 0 DDFS Frequency Control Word
 ***************************************************************************/
/* SDS_NTCH_0 :: FCW0 :: notch_width0 [31:28] */
#define BCHP_SDS_NTCH_0_FCW0_notch_width0_MASK                     0xf0000000
#define BCHP_SDS_NTCH_0_FCW0_notch_width0_SHIFT                    28

/* SDS_NTCH_0 :: FCW0 :: notch_depth0 [27:24] */
#define BCHP_SDS_NTCH_0_FCW0_notch_depth0_MASK                     0x0f000000
#define BCHP_SDS_NTCH_0_FCW0_notch_depth0_SHIFT                    24

/* SDS_NTCH_0 :: FCW0 :: reserved_for_eco0 [23:20] */
#define BCHP_SDS_NTCH_0_FCW0_reserved_for_eco0_MASK                0x00f00000
#define BCHP_SDS_NTCH_0_FCW0_reserved_for_eco0_SHIFT               20

/* SDS_NTCH_0 :: FCW0 :: notch_fcw0 [19:00] */
#define BCHP_SDS_NTCH_0_FCW0_notch_fcw0_MASK                       0x000fffff
#define BCHP_SDS_NTCH_0_FCW0_notch_fcw0_SHIFT                      0

/***************************************************************************
 *FCW1 - Notch Filter 1 DDFS Frequency Control Word
 ***************************************************************************/
/* SDS_NTCH_0 :: FCW1 :: notch_width1 [31:28] */
#define BCHP_SDS_NTCH_0_FCW1_notch_width1_MASK                     0xf0000000
#define BCHP_SDS_NTCH_0_FCW1_notch_width1_SHIFT                    28

/* SDS_NTCH_0 :: FCW1 :: notch_depth1 [27:24] */
#define BCHP_SDS_NTCH_0_FCW1_notch_depth1_MASK                     0x0f000000
#define BCHP_SDS_NTCH_0_FCW1_notch_depth1_SHIFT                    24

/* SDS_NTCH_0 :: FCW1 :: reserved_for_eco0 [23:20] */
#define BCHP_SDS_NTCH_0_FCW1_reserved_for_eco0_MASK                0x00f00000
#define BCHP_SDS_NTCH_0_FCW1_reserved_for_eco0_SHIFT               20

/* SDS_NTCH_0 :: FCW1 :: notch_fcw1 [19:00] */
#define BCHP_SDS_NTCH_0_FCW1_notch_fcw1_MASK                       0x000fffff
#define BCHP_SDS_NTCH_0_FCW1_notch_fcw1_SHIFT                      0

/***************************************************************************
 *FCW2 - Notch Filter 2 DDFS Frequency Control Word
 ***************************************************************************/
/* SDS_NTCH_0 :: FCW2 :: notch_width2 [31:28] */
#define BCHP_SDS_NTCH_0_FCW2_notch_width2_MASK                     0xf0000000
#define BCHP_SDS_NTCH_0_FCW2_notch_width2_SHIFT                    28

/* SDS_NTCH_0 :: FCW2 :: notch_depth2 [27:24] */
#define BCHP_SDS_NTCH_0_FCW2_notch_depth2_MASK                     0x0f000000
#define BCHP_SDS_NTCH_0_FCW2_notch_depth2_SHIFT                    24

/* SDS_NTCH_0 :: FCW2 :: reserved_for_eco0 [23:20] */
#define BCHP_SDS_NTCH_0_FCW2_reserved_for_eco0_MASK                0x00f00000
#define BCHP_SDS_NTCH_0_FCW2_reserved_for_eco0_SHIFT               20

/* SDS_NTCH_0 :: FCW2 :: notch_fcw2 [19:00] */
#define BCHP_SDS_NTCH_0_FCW2_notch_fcw2_MASK                       0x000fffff
#define BCHP_SDS_NTCH_0_FCW2_notch_fcw2_SHIFT                      0

/***************************************************************************
 *FCW3 - Notch Filter DDFS Combined Frequency Control Word
 ***************************************************************************/
/* SDS_NTCH_0 :: FCW3 :: reserved0 [31:20] */
#define BCHP_SDS_NTCH_0_FCW3_reserved0_MASK                        0xfff00000
#define BCHP_SDS_NTCH_0_FCW3_reserved0_SHIFT                       20

/* SDS_NTCH_0 :: FCW3 :: notch_fcw3 [19:00] */
#define BCHP_SDS_NTCH_0_FCW3_notch_fcw3_MASK                       0x000fffff
#define BCHP_SDS_NTCH_0_FCW3_notch_fcw3_SHIFT                      0

/***************************************************************************
 *DCO0_INT - Notch Filter 0 BB DC Canceller Loop Integrator
 ***************************************************************************/
/* SDS_NTCH_0 :: DCO0_INT :: notch_dco0_int_i [31:16] */
#define BCHP_SDS_NTCH_0_DCO0_INT_notch_dco0_int_i_MASK             0xffff0000
#define BCHP_SDS_NTCH_0_DCO0_INT_notch_dco0_int_i_SHIFT            16

/* SDS_NTCH_0 :: DCO0_INT :: notch_dco0_int_q [15:00] */
#define BCHP_SDS_NTCH_0_DCO0_INT_notch_dco0_int_q_MASK             0x0000ffff
#define BCHP_SDS_NTCH_0_DCO0_INT_notch_dco0_int_q_SHIFT            0

/***************************************************************************
 *DCO1_INT - Notch Filter 1 BB DC Canceller Loop Integrator
 ***************************************************************************/
/* SDS_NTCH_0 :: DCO1_INT :: notch_dco1_int_i [31:16] */
#define BCHP_SDS_NTCH_0_DCO1_INT_notch_dco1_int_i_MASK             0xffff0000
#define BCHP_SDS_NTCH_0_DCO1_INT_notch_dco1_int_i_SHIFT            16

/* SDS_NTCH_0 :: DCO1_INT :: notch_dco1_int_q [15:00] */
#define BCHP_SDS_NTCH_0_DCO1_INT_notch_dco1_int_q_MASK             0x0000ffff
#define BCHP_SDS_NTCH_0_DCO1_INT_notch_dco1_int_q_SHIFT            0

/***************************************************************************
 *DCO2_INT - Notch Filter 2 BB DC Canceller Loop Integrator
 ***************************************************************************/
/* SDS_NTCH_0 :: DCO2_INT :: notch_dco2_int_i [31:16] */
#define BCHP_SDS_NTCH_0_DCO2_INT_notch_dco2_int_i_MASK             0xffff0000
#define BCHP_SDS_NTCH_0_DCO2_INT_notch_dco2_int_i_SHIFT            16

/* SDS_NTCH_0 :: DCO2_INT :: notch_dco2_int_q [15:00] */
#define BCHP_SDS_NTCH_0_DCO2_INT_notch_dco2_int_q_MASK             0x0000ffff
#define BCHP_SDS_NTCH_0_DCO2_INT_notch_dco2_int_q_SHIFT            0

#endif /* #ifndef BCHP_SDS_NTCH_0_H__ */

/* End of File */
