obj-$(CONFIG_APUI_SET_RECORDING_UI_DISPLAY) += nx_prism_menu_storage.o
obj-$(CONFIG_APUI_SET_RECORDING_UI_DISPLAY) += nx_prism_menu_pvr.o
obj-$(CONFIG_APUI_SET_RECORDING_UI_DISPLAY) += nx_prism_menu_storage_device_setting.o
obj-$(CONFIG_APUI_SET_RECORDING_UI_DISPLAY) += nx_prism_menu_ipepg.o
obj-$(CONFIG_APUI_SET_RECORDING_UI_DISPLAY) += nx_prism_menu_playback_option.o
obj-$(CONFIG_SUPPORT_IPEPG_APP) += nx_prism_menu_record_option.o
obj-$(CONFIG_APUI_SET_RECORDING_UI_DISPLAY) += nx_prism_menu_remote_record.o

# Additional include path
ccflags-y += -I../../../../../../../make/include

