#
obj-y += tmddTDA18260Stream.o
obj-y += tmddTDA18260Stream_Instance.o
obj-y += tmddTDA18260Stream_RegAccess.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/tmddTDA18260Stream/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/tmddTDA18260Stream/cfg     
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/tmddTDA18260Stream/src

#HUMAX_EXTRA_CFLAG += -DPRDY_ROBUSTNESS=1
HUMAX_EXTRA_CFLAG += -D_TMDD_TDA18260_REGMAP_DEFINED
