-include ./dirs

ifeq ($(DIRS),)
TARGET = ndtasf

SOURCES =                \
	drmndtasf.c drmorderedlist.c ndtasfdrm.c ndtasf_internal.c ndtasfguids.c asfsample.c mux.c muxstream.c sendwindow.c leakybucket.c packetwriter.c asfmediabuffer.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
