obj-y	+= mgr_tplist.o
obj-y	+= mgr_tplist_tsinfo.o
obj-y	+= mgr_tplist_tuneinfo.o
obj-y	+= mgr_tplist_default_sat.o
obj-y	+= mgr_tplist_default_cab.o
obj-y	+= mgr_tplist_default_ter.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr

# Additional include path
ccflags-y += -I$(OCTO_TVMANAGER_DIR)/include_plugin

