obj-y += dmx/
obj-y += dscr/
obj-y += fs/
obj-y += main/
obj-y += nvm/
obj-y += os/
obj-y += pi/
obj-y += ctrl/
obj-$(CONFIG_MW_CAS_VIACCESS_PVR) += pvr/
obj-$(CONFIG_MW_CAS_VIACCESS_NET) += net/
obj-y += sc/
obj-y += schip/
obj-y += ui/

obj-y += vamgr_main.o
obj-y += vamgr_action.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
