obj-y += core/
obj-y += dal/

obj-y += cxmgr_main.o
obj-y += cxmgr_action.o
obj-y += conax_ctrl.o
obj-$(CONFIG_DEBUG) += cxmgr_cmd.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

