obj-y += va_ui_api.o
obj-y += va_ui_adapt.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw
# Additional include path
