obj-y += svc_cas_si_retrieve.o
obj-y += svc_cas_si_rawmgr.o
obj-y += svc_cas_si_semiparser.o
obj-y += svc_cas_si_desmgr.o
obj-y += svc_cas_si_desparse.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw

# Additional include path
ccflags-y += -I$(OCTO_TVSERVICE_DIR)/svc/cas/local_include

