obj-y += control/
obj-y += dal/
obj-y += mgr/
obj-y += op/

obj-y += nagra_mgr.o
obj-y += xsvc_cas_na.o

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
