-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = licenseviewstore

DRM_MODULE_CFLAGS =

SOURCES =                \
	licenseviewstore.c 
	
endif	
   
include $(DRM_SOURCE_PATH)/default.mak
