# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =  \
    hash   \
    hmac   \
    sha1   \
    sha256 \

include $(PLAYREADY_DIR)/GNUmakefile.common

