obj-y += antenna/
obj-y += av/
obj-y += channel/
obj-$(CONFIG_SUPPORT_NIMA) += contents/
obj-y += filemgr/
obj-y += metadata/
obj-y += search/
obj-y += schedule/
obj-y += system/
obj-$(CONFIG_MW_MM_PVR) += record/
obj-y += media/
obj-y += player/
obj-$(CONFIG_MW_INET) += network/
obj-y += panel/
obj-$(CONFIG_MW_CAS) += cas/
obj-$(CONFIG_MW_MM_DLNA) += dlna/

obj-y += nx_core.o

# Basic include path
# Additional include path
