obj-y += ci_cc_cipher_bn_lib.o
obj-y += ci_cc_cipher_mpi_lib.o
obj-y += ci_cc_cipher.o
obj-y += ci_cc_x509_asn_lib.o
obj-y += ci_cc_x509.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

