/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_decode_cpuaux_0.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 1/24/12 4:41p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Mon Jan 23 14:23:48 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7231/rdb/b2/bchp_decode_cpuaux_0.h $
 * 
 * Hydra_Software_Devel/1   1/24/12 4:41p katrep
 * SW7231-1:rdb header files for 7231B2
 *
 ***************************************************************************/

#ifndef BCHP_DECODE_CPUAUX_0_H__
#define BCHP_DECODE_CPUAUX_0_H__

/***************************************************************************
 *DECODE_CPUAUX_0
 ***************************************************************************/
#define BCHP_DECODE_CPUAUX_0_CPUAUX_REG          0x00045000 /* CPUAUX_REG */
#define BCHP_DECODE_CPUAUX_0_CPUAUX_END          0x00045ffc /* CPUAUX_END */

/***************************************************************************
 *CPUAUX_REG - CPUAUX_REG
 ***************************************************************************/
/* DECODE_CPUAUX_0 :: CPUAUX_REG :: Addr [31:00] */
#define BCHP_DECODE_CPUAUX_0_CPUAUX_REG_Addr_MASK                  0xffffffff
#define BCHP_DECODE_CPUAUX_0_CPUAUX_REG_Addr_SHIFT                 0

/***************************************************************************
 *CPUAUX_END - CPUAUX_END
 ***************************************************************************/
/* DECODE_CPUAUX_0 :: CPUAUX_END :: reserved0 [31:00] */
#define BCHP_DECODE_CPUAUX_0_CPUAUX_END_reserved0_MASK             0xffffffff
#define BCHP_DECODE_CPUAUX_0_CPUAUX_END_reserved0_SHIFT            0

#endif /* #ifndef BCHP_DECODE_CPUAUX_0_H__ */

/* End of File */
