/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_sys_top_ctrl_sec.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 1/24/12 4:47p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Mon Jan 23 14:23:47 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7231/rdb/b2/bchp_sys_top_ctrl_sec.h $
 * 
 * Hydra_Software_Devel/1   1/24/12 4:47p katrep
 * SW7231-1:rdb header files for 7231B2
 *
 ***************************************************************************/

#ifndef BCHP_SYS_TOP_CTRL_SEC_H__
#define BCHP_SYS_TOP_CTRL_SEC_H__

/***************************************************************************
 *SYS_TOP_CTRL_SEC - Top Control secure registers
 ***************************************************************************/
#define BCHP_SYS_TOP_CTRL_SEC_RSV_S              0x0040e700 /* RESERVED */
#define BCHP_SYS_TOP_CTRL_SEC_RSV_E              0x0040e704 /* RESERVED */

/***************************************************************************
 *RSV_S - RESERVED
 ***************************************************************************/
/* SYS_TOP_CTRL_SEC :: RSV_S :: reserved0 [31:00] */
#define BCHP_SYS_TOP_CTRL_SEC_RSV_S_reserved0_MASK                 0xffffffff
#define BCHP_SYS_TOP_CTRL_SEC_RSV_S_reserved0_SHIFT                0

/***************************************************************************
 *RSV_E - RESERVED
 ***************************************************************************/
/* SYS_TOP_CTRL_SEC :: RSV_E :: reserved0 [31:00] */
#define BCHP_SYS_TOP_CTRL_SEC_RSV_E_reserved0_MASK                 0xffffffff
#define BCHP_SYS_TOP_CTRL_SEC_RSV_E_reserved0_SHIFT                0

#endif /* #ifndef BCHP_SYS_TOP_CTRL_SEC_H__ */

/* End of File */
