/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_uartb.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 1/24/12 4:47p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Mon Jan 23 14:23:48 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7231/rdb/b2/bchp_uartb.h $
 * 
 * Hydra_Software_Devel/1   1/24/12 4:47p katrep
 * SW7231-1:rdb header files for 7231B2
 *
 ***************************************************************************/

#ifndef BCHP_UARTB_H__
#define BCHP_UARTB_H__

/***************************************************************************
 *UARTB - UART B
 ***************************************************************************/
#define BCHP_UARTB_RBR                           0x00406940 /* Receive Buffer Register */
#define BCHP_UARTB_THR                           0x00406940 /* Transmit Holding Register */
#define BCHP_UARTB_DLH                           0x00406944 /* Divisor Latch High */
#define BCHP_UARTB_DLL                           0x00406940 /* Divisor Latch Low */
#define BCHP_UARTB_IER                           0x00406944 /* Interrupt Enable Register */
#define BCHP_UARTB_IIR                           0x00406948 /* Interrupt Identity Register */
#define BCHP_UARTB_FCR                           0x00406948 /* FIFO Control Register */
#define BCHP_UARTB_LCR                           0x0040694c /* Line Control Register */
#define BCHP_UARTB_MCR                           0x00406950 /* Modem Control Register */
#define BCHP_UARTB_LSR                           0x00406954 /* Line Status Register */
#define BCHP_UARTB_MSR                           0x00406958 /* Modem Status Register */
#define BCHP_UARTB_SCR                           0x0040695c /* Scratchpad Register */

#endif /* #ifndef BCHP_UARTB_H__ */

/* End of File */
