obj-y += xdb_svc_base.o
obj-y += xdb_svc_dama_adapter_base.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xdb

# Additional include path
ccflags-y += -I$(OCTO_DB_DIR)/svcmanager/local_include
ccflags-y += -I$(OCTO_DB_PLUGIN_DIR)/svcmanager/local_include

