/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_sata_port0_ctrl.h $
 * $brcm_Revision: Hydra_Software_Devel/2 $
 * $brcm_Date: 6/22/11 6:13p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Jun 22 15:27:42 2011
 *                 MD5 Checksum         4c7f7c173e488659edce1ceafec7f9f4
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7231/rdb/a0/bchp_sata_port0_ctrl.h $
 * 
 * Hydra_Software_Devel/2   6/22/11 6:13p pntruong
 * SW7231-196: Synced with central rdb.
 *
 ***************************************************************************/

#ifndef BCHP_SATA_PORT0_CTRL_H__
#define BCHP_SATA_PORT0_CTRL_H__

/***************************************************************************
 *SATA_PORT0_CTRL - Port0 Ctrl Registers
 ***************************************************************************/
#define BCHP_SATA_PORT0_CTRL_PCTRL0              0x00181700 /* SATA3 PORT Control0 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL1              0x00181704 /* SATA3 PORT Control1 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL2              0x00181708 /* SATA3 PORT Control2 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL3              0x0018170c /* SATA3 PORT Control3 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL4              0x00181710 /* SATA3 PORT Control4 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL5              0x00181714 /* SATA3 PORT Control5 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL6              0x00181718 /* SATA3 PORT Control6 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL7              0x0018171c /* SATA3 PORT Control7 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL8              0x00181720 /* SATA3 PORT Control8 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL9              0x00181724 /* SATA3 PORT Control9 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL10             0x00181728 /* SATA3 PORT Control10 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL11             0x0018172c /* SATA3 PORT Control11 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL12             0x00181730 /* SATA3 PORT Control12 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL13             0x00181734 /* SATA3 PORT Control13 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL14             0x00181738 /* SATA3 PORT Control14 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL15             0x0018173c /* SATA3 PORT Control15 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL16             0x00181740 /* SATA3 PORT Control16 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL17             0x00181744 /* SATA3 PORT Control17 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL18             0x00181748 /* SATA3 PORT Control18 Register */
#define BCHP_SATA_PORT0_CTRL_PCTRL19             0x0018174c /* SATA3 PORT Control19 Register */

/***************************************************************************
 *PCTRL0 - SATA3 PORT Control0 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL0 :: PCTRL0 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL0_PCTRL0_MASK                    0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL0_PCTRL0_SHIFT                   0
#define BCHP_SATA_PORT0_CTRL_PCTRL0_PCTRL0_DEFAULT                 134250432

/***************************************************************************
 *PCTRL1 - SATA3 PORT Control1 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL1 :: PCTRL1 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL1_PCTRL1_MASK                    0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL1_PCTRL1_SHIFT                   0
#define BCHP_SATA_PORT0_CTRL_PCTRL1_PCTRL1_DEFAULT                 375808

/***************************************************************************
 *PCTRL2 - SATA3 PORT Control2 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL2 :: PCTRL2 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL2_PCTRL2_MASK                    0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL2_PCTRL2_SHIFT                   0
#define BCHP_SATA_PORT0_CTRL_PCTRL2_PCTRL2_DEFAULT                 375808

/***************************************************************************
 *PCTRL3 - SATA3 PORT Control3 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL3 :: PCTRL3 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL3_PCTRL3_MASK                    0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL3_PCTRL3_SHIFT                   0
#define BCHP_SATA_PORT0_CTRL_PCTRL3_PCTRL3_DEFAULT                 939526658

/***************************************************************************
 *PCTRL4 - SATA3 PORT Control4 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL4 :: PCTRL4 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL4_PCTRL4_MASK                    0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL4_PCTRL4_SHIFT                   0
#define BCHP_SATA_PORT0_CTRL_PCTRL4_PCTRL4_DEFAULT                 84082304

/***************************************************************************
 *PCTRL5 - SATA3 PORT Control5 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL5 :: PCTRL5 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL5_PCTRL5_MASK                    0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL5_PCTRL5_SHIFT                   0
#define BCHP_SATA_PORT0_CTRL_PCTRL5_PCTRL5_DEFAULT                 1077947280

/***************************************************************************
 *PCTRL6 - SATA3 PORT Control6 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL6 :: PCTRL6 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL6_PCTRL6_MASK                    0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL6_PCTRL6_SHIFT                   0
#define BCHP_SATA_PORT0_CTRL_PCTRL6_PCTRL6_DEFAULT                 0

/***************************************************************************
 *PCTRL7 - SATA3 PORT Control7 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL7 :: PCTRL7 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL7_PCTRL7_MASK                    0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL7_PCTRL7_SHIFT                   0
#define BCHP_SATA_PORT0_CTRL_PCTRL7_PCTRL7_DEFAULT                 0

/***************************************************************************
 *PCTRL8 - SATA3 PORT Control8 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL8 :: PCTRL8 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL8_PCTRL8_MASK                    0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL8_PCTRL8_SHIFT                   0
#define BCHP_SATA_PORT0_CTRL_PCTRL8_PCTRL8_DEFAULT                 0

/***************************************************************************
 *PCTRL9 - SATA3 PORT Control9 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL9 :: PCTRL9 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL9_PCTRL9_MASK                    0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL9_PCTRL9_SHIFT                   0
#define BCHP_SATA_PORT0_CTRL_PCTRL9_PCTRL9_DEFAULT                 0

/***************************************************************************
 *PCTRL10 - SATA3 PORT Control10 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL10 :: PCTRL10 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL10_PCTRL10_MASK                  0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL10_PCTRL10_SHIFT                 0
#define BCHP_SATA_PORT0_CTRL_PCTRL10_PCTRL10_DEFAULT               0

/***************************************************************************
 *PCTRL11 - SATA3 PORT Control11 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL11 :: PCTRL11 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL11_PCTRL11_MASK                  0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL11_PCTRL11_SHIFT                 0
#define BCHP_SATA_PORT0_CTRL_PCTRL11_PCTRL11_DEFAULT               0

/***************************************************************************
 *PCTRL12 - SATA3 PORT Control12 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL12 :: PCTRL12 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL12_PCTRL12_MASK                  0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL12_PCTRL12_SHIFT                 0
#define BCHP_SATA_PORT0_CTRL_PCTRL12_PCTRL12_DEFAULT               0

/***************************************************************************
 *PCTRL13 - SATA3 PORT Control13 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL13 :: PCTRL13 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL13_PCTRL13_MASK                  0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL13_PCTRL13_SHIFT                 0
#define BCHP_SATA_PORT0_CTRL_PCTRL13_PCTRL13_DEFAULT               0

/***************************************************************************
 *PCTRL14 - SATA3 PORT Control14 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL14 :: PCTRL14 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL14_PCTRL14_MASK                  0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL14_PCTRL14_SHIFT                 0
#define BCHP_SATA_PORT0_CTRL_PCTRL14_PCTRL14_DEFAULT               0

/***************************************************************************
 *PCTRL15 - SATA3 PORT Control15 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL15 :: PCTRL15 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL15_PCTRL15_MASK                  0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL15_PCTRL15_SHIFT                 0
#define BCHP_SATA_PORT0_CTRL_PCTRL15_PCTRL15_DEFAULT               0

/***************************************************************************
 *PCTRL16 - SATA3 PORT Control16 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL16 :: PCTRL16 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL16_PCTRL16_MASK                  0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL16_PCTRL16_SHIFT                 0
#define BCHP_SATA_PORT0_CTRL_PCTRL16_PCTRL16_DEFAULT               0

/***************************************************************************
 *PCTRL17 - SATA3 PORT Control17 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL17 :: PCTRL17 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL17_PCTRL17_MASK                  0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL17_PCTRL17_SHIFT                 0
#define BCHP_SATA_PORT0_CTRL_PCTRL17_PCTRL17_DEFAULT               0

/***************************************************************************
 *PCTRL18 - SATA3 PORT Control18 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL18 :: PCTRL18 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL18_PCTRL18_MASK                  0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL18_PCTRL18_SHIFT                 0
#define BCHP_SATA_PORT0_CTRL_PCTRL18_PCTRL18_DEFAULT               0

/***************************************************************************
 *PCTRL19 - SATA3 PORT Control19 Register
 ***************************************************************************/
/* SATA_PORT0_CTRL :: PCTRL19 :: PCTRL19 [31:00] */
#define BCHP_SATA_PORT0_CTRL_PCTRL19_PCTRL19_MASK                  0xffffffff
#define BCHP_SATA_PORT0_CTRL_PCTRL19_PCTRL19_SHIFT                 0
#define BCHP_SATA_PORT0_CTRL_PCTRL19_PCTRL19_DEFAULT               0

#endif /* #ifndef BCHP_SATA_PORT0_CTRL_H__ */

/* End of File */
