# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

SRC_DIR = ..

PLAYREADY_TEST=1
include $(_NTROOT)/PK/WMDRM-MD/PK_GNUmakefile.common

