/*
 * module to include the modules relavent to the docsis mib(s) 
 */

config_require(docsis/docsDevBase)
config_require(docsis/docsDevNmAccessTable)
config_require(docsis/docsDevSoftware)
config_require(docsis/docsDevServer)
config_require(docsis/docsDevEvent)
config_require(docsis/docsDevEvControlTable)
config_require(docsis/docsDevEventTable)
config_require(docsis/docsDevFilter)
config_require(docsis/docsDevFilterLLCTable)
config_require(docsis/docsDevFilterIpTable)
config_require(docsis/docsDevFilterPolicyTable)
config_require(docsis/docsDevFilterTosTable)
config_require(docsis/docsDevCpe)
config_require(docsis/docsDevCpeTable)
config_require(docsis/docsIfDownstreamChannelTable)
config_require(docsis/docsIfUpstreamChannelTable)
config_require(docsis/docsIfQosProfileTable)
config_require(docsis/docsIfSignalQualityTable)
config_require(docsis/docsIfCmMacTable)
config_require(docsis/docsIfCmStatusTable)
config_require(docsis/docsIfCmServiceTable)
config_require(docsis/docsBpiCmBaseTable)
config_require(docsis/docsBpiCmTEKTable)
