# File: drivers/net/bcmbcmpci/Makefile
#
#
#  Copyright (c) 2005-2009 Broadcom Corporation
#
#  This program is the proprietary software of Broadcom Corporation and/or
#  its licensors, and may only be used, duplicated, modified or distributed
#  pursuant to the terms and conditions of a separate, written license
#  agreement executed between you and Broadcom (an "Authorized License").
#  Except as set forth in an Authorized License, Broadcom grants no license
#  (express or implied), right to use, or waiver of any kind with respect to
#  the Software, and Broadcom expressly reserves all rights in and to the
#  Software and all intellectual property rights therein.  IF YOU HAVE NO
#  AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
#  AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
#  SOFTWARE.
#
#  Except as expressly set forth in the Authorized License,
#
#  1.     This program, including its structure, sequence and organization,
#  constitutes the valuable trade secrets of Broadcom, and you shall use all
#  reasonable efforts to protect the confidentiality thereof, and to use this
#  information only in connection with your use of Broadcom integrated circuit
#  products.
#
#  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
#  "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
#  OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
#  RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
#  IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
#  A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
#  ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
#  THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
#
#  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
#  OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
#  INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
#  RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
#  HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
#  EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
#  WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
#  FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
#
#***************************************************************************
#
# $Id$
#
# mtd driver for OCAP partitions. The kernel provides a single mtd partition
# and this driver is handling the OCAP related subpartitions.
# Applies to 2.6.18-6.6 or later kernel
# 
#
#

#obj-y := bcmpcieth.o
obj-m := bcm$(DEVICE)eth.o
bcm$(DEVICE)eth-objs := bcm7xxxPciEnet.o

#-DDUMP_DATA -- dump data
#-DUSE_BH -- use bottom half
#-DUSE_PROC -- display ethernet driver internal info
# for debug only EXTRA_CFLAGS += -I. -DDUMP_TRACE -DDUMP_DATA
#EXTRA_CFLAGS += -I. -DUSE_PROC -DDUMP_TRACE -DDUMP_DATA -DBCM$(CHIPID)
EXTRA_CFLAGS += -I. -DUSE_PROC -DBCM$(CHIPID)
ifeq ($(FFT_SUPPORT), 1)
EXTRA_CFLAGS += -DFFT_SUPPORT
endif
ifeq ($(LED_SUPPORT), 1)
EXTRA_CFLAGS += -DLED_SUPPORT
endif
ifeq ($(use_writesize), 1)
EXTRA_CFLAGS += -DUSE_WRITESIZE
endif


ifeq ($(MTDOCAP_DRIVER), 1)
obj-m += mtdocap.o
endif
