# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =    \
    parsers  \
    AES      \
    bignum   \
    cbc      \
    cipher   \
    des      \
    DevStore \
    ecc      \
    hal      \
    keyfile  \
    lib      \
    md5      \
    pkcrypto \
    profile  \
    rc4      \
    RSA      \
    sha      \

include $(PLAYREADY_DIR)/GNUmakefile.common

