/***************************************************************************
*     (c)2008-2010 Broadcom Corporation
*  
*  This program is the proprietary software of Broadcom Corporation and/or its licensors,
*  and may only be used, duplicated, modified or distributed pursuant to the terms and
*  conditions of a separate, written license agreement executed between you and Broadcom
*  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
*  no license (express or implied), right to use, or waiver of any kind with respect to the
*  Software, and Broadcom expressly reserves all rights in and to the Software and all
*  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
*  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
*  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.  
*   
*  Except as expressly set forth in the Authorized License,
*   
*  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
*  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
*  and to use this information only in connection with your use of Broadcom integrated circuit products.
*   
*  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS" 
*  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR 
*  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO 
*  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES 
*  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, 
*  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION 
*  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF 
*  USE OR PERFORMANCE OF THE SOFTWARE.
*  
*  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS 
*  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR 
*  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR 
*  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF 
*  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT 
*  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE 
*  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF 
*  ANY LIMITED REMEDY.
 *
 * $brcm_Workfile: nexus_gpio_table.c $
 * $brcm_Revision: 2 $
 * $brcm_Date: 12/8/10 5:27p $
 * 
 * Module Description:
 * 
 * Revision History:
 * 
 * $brcm_Log: /nexus/modules/gpio/7420/src/nexus_gpio_table.c $
 * 
 * 2   12/8/10 5:27p spothana
 * SW7408-146: NEXUS GPIO should export the pin mux register address, mask
 *  and shift
 * 
 * 1   11/23/08 3:10p nickh
 * PR48963:
* 
* API Description:
*   API name: Gpio
*    Specific APIs related to Gpio Control.
*
* Revision History:
*
* 2   2/20/08 9:38a erickson
* PR39765: static analysis fix
*
* 1   1/18/08 2:21p jgarrett
* PR 38808: Merging to main branch
*
* Nexus_Devel/3   11/30/07 11:08a jgarrett
* PR 37801: Adjusting register offsets
*
* Nexus_Devel/2   11/26/07 11:56a erickson
* PR37423: fix 7400 gpio
*
* Nexus_Devel/1   11/26/07 9:45a erickson
* PR37423: gpio update
*
***************************************************************************/
#include "nexus_gpio_module.h"
#include "bchp_sun_top_ctrl.h"
#include "bchp_gio.h"
#include "priv/nexus_core.h"

BDBG_MODULE(nexus_gpio_table);

typedef struct NEXUS_GpioTable
{
    uint32_t addr;
    unsigned mask;
    unsigned shift;
} NEXUS_GpioTable;

NEXUS_GpioTable g_gpioTable[NEXUS_NUM_GPIO_PINS] = {
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_000_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_000_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_001_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_001_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_002_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_002_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_003_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_003_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_004_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_004_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_005_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_005_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_006_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_006_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_007_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_007_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_008_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_008_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_009_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_009_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_010_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_010_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_011_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_011_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_012_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_012_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_013_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_013_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_014_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_014_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_015_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_015_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_016_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_016_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_017_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_017_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_018_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_018_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_019_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_019_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_020_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_020_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_021_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_021_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_022_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_022_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_023_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_023_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_024_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_024_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_025_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_025_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_026_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_026_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_027_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_027_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_028_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_028_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_029_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_029_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_030_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_030_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_031_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_031_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_032_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_032_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_033_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_033_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_034_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_034_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_035_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_035_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_036_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_036_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_037_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_037_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_038_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_038_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_039_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_039_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_040_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_040_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_041_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_041_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_042_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_042_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_043_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_043_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_044_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_044_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_045_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_045_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_046_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_046_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_047_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_047_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_048_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_048_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_049_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_049_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_050_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_050_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_051_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_051_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_052_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_052_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_053_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_053_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_054_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_054_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_055_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_055_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_056_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_056_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_057_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_057_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_058_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_058_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_059_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_059_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_060_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_060_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_061_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_061_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_062_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_062_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_063_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_063_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_064_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_064_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_065_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_065_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_066_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_066_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_067_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_067_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_068_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_068_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_069_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_069_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_070_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_070_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_071_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_071_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_072_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_072_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_073_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_073_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_074_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_074_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_075_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_075_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_076_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_076_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_077_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_077_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_078_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_078_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_079_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_079_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_080_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_080_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_081_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_081_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_082_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_082_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_083_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_083_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_084_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_084_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_085_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_085_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_086_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_086_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_087_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_087_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_088_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_088_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_089_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_089_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_090_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_090_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_091_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_091_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_092_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_092_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_093_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_093_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_094_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_094_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_095_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_095_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_096_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_096_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_097_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_097_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_098_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_098_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_099_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_099_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_100_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_100_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_101_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_101_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_102_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_102_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_103_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_19_gpio_103_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_104_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_104_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_105_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_105_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_106_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_106_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_107_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_107_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_108_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_108_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_109_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_109_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_110_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_110_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_111_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_20_gpio_111_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_112_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_gpio_112_SHIFT},
};

NEXUS_GpioTable g_sgpioTable[NEXUS_NUM_SGPIO_PINS] = {
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_00_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_01_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_02_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_03_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_04_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_05_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_06_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_21_sgpio_06_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_07_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_07_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_08_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_08_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_09_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_22_sgpio_09_SHIFT}
};

/* These functions must be implemented per-chip */
NEXUS_Error NEXUS_Gpio_P_GetPinMux(NEXUS_GpioType type, unsigned pin, uint32_t *pAddr, uint32_t *pMask, unsigned *pShift )
{
    NEXUS_GpioTable *pEntry=NULL;
    if ( type == NEXUS_GpioType_eSpecial ) {
        if ( pin >= NEXUS_NUM_SGPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        pEntry = g_sgpioTable+pin;
    }
    else if ( type == NEXUS_GpioType_eStandard ) {
        if ( pin >= NEXUS_NUM_GPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        pEntry = g_gpioTable+pin;
    }
    else {
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }
    *pAddr = pEntry->addr;
    *pMask = pEntry->mask;
    *pShift = pEntry->shift;
    return 0;
}

NEXUS_Error NEXUS_Gpio_P_CheckPinmux(NEXUS_GpioType type, unsigned pin)
{
    NEXUS_GpioTable *pEntry=NULL;
    uint32_t val;

    BDBG_ASSERT(type < NEXUS_GpioType_eMax);

    if ( type == NEXUS_GpioType_eSpecial )
    {
        if ( pin >= NEXUS_NUM_SGPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        pEntry = g_sgpioTable+pin;
    }
    else
    {
        if ( pin >= NEXUS_NUM_GPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        pEntry = g_gpioTable+pin;
    }

    val = BREG_Read32(g_pCoreHandles->reg, pEntry->addr);
    if ( val & pEntry->mask )
    {
        /* Pin is not configured as GPIO */
        BDBG_ERR(("Pin mux register for %s %u is not properly configured - value %u should be 0",
                  (type == NEXUS_GpioType_eSpecial)?"sgpio":"gpio", pin, val>>pEntry->shift));
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }

    return BERR_SUCCESS;
}

NEXUS_Error NEXUS_Gpio_P_GetPinData(NEXUS_GpioType type, unsigned pin, uint32_t *pAddress, uint32_t *pShift)
{
    BDBG_ASSERT(type < NEXUS_GpioType_eMax);

    if ( type == NEXUS_GpioType_eSpecial )
    {
        if ( pin >= NEXUS_NUM_SGPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        else
        {
            /* SGPIO Pins 9..0 are in ODEN_EXT */
            *pAddress = BCHP_GIO_ODEN_EXT;
            *pShift = pin;
        }
    }
    else
    {
        if ( pin < 32 )
        {
            /* GPIO Pins 31..0 are in ODEN_LO */
            *pAddress = BCHP_GIO_ODEN_LO;
            *pShift = pin;
        }
        else if ( pin < 64 )
        {
            /* GPIO Pins 63..32 are in ODEN_HI */
            *pAddress = BCHP_GIO_ODEN_HI;
            *pShift = pin-32;
        }
        else if ( pin < 86 )
        {
            /* GPIO Pins 85..64 are in ODEN_EXT, above sgpio bits */
            *pAddress = BCHP_GIO_ODEN_EXT;
            *pShift = (pin-64)+NEXUS_NUM_SGPIO_PINS;
        }
        else if ( pin < 113 )
        {
            /* GPIO Pins 112..86 are in ODEN_EXT_HI */
            *pAddress = BCHP_GIO_ODEN_EXT_HI;
            *pShift = (pin-86);
        }
        else
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
    }

    return BERR_SUCCESS;
}

