obj-y += mgr_output.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr
# Additional include path

# Additional include path
ccflags-y += -I$(OCTO_TVMANAGER_DIR)/include_plugin

