-include ./dirs

ifeq ($(DIRS),)
TARGET = antirollbackclockreal

SOURCES =                \
	antirollbackclockutilreal.c antirollbackclockimplreal.c
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
