-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = meteringprocessresponse

DRM_MODULE_CFLAGS =

SOURCES =                \
	meterresponse.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
