obj-$(CONFIG_MW_CAS_NAGRA_OP_SES) += ses/
obj-$(CONFIG_MW_CAS_NAGRA_OP_ert) += ert/

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
