obj-$(CONFIG_MW_CAS_VERIMATRIX) += control/
obj-$(CONFIG_MW_CAS_VERIMATRIX) += dmx/
obj-$(CONFIG_MW_CAS_VERIMATRIX) += dscr/
obj-$(CONFIG_MW_CAS_VERIMATRIX) += psi/
obj-$(CONFIG_MW_CAS_VERIMATRIX) += pvr/
obj-$(CONFIG_MW_CAS_VERIMATRIX) += viewright/
obj-$(CONFIG_MW_CAS_VERIMATRIX) += ui/
obj-$(CONFIG_MW_CAS_VERIMATRIX_DVB) += sc/
obj-$(CONFIG_MW_CAS_VERIMATRIX) += xsvc_cas_vmx_main.o
obj-$(CONFIG_MW_CAS_VERIMATRIX) += xsvc_cas_vmx_action.o

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path