obj-y += common/
obj-y += STB/
obj-y += storage/
obj-y += network/

obj-y += RDM_Device.o
obj-y += RDM_STB.o
obj-y += RDM_Storage.o
obj-y += RDM_Vender.o

ccflags-y += -I$(THIRDPARTY_DIR)/cwmp/include
ccflags-y += -I$(REMA_MAIN_DIR)/datamodel/common
ccflags-y += -I$(REMA_MAIN_DIR)/datamodel/STB
ccflags-y += -I$(REMA_MAIN_DIR)/datamodel/storage
ccflags-y += -I$(REMA_MAIN_DIR)/
ccflags-y += -I$(REMA_MAIN_DIR)/module

