
obj-y += oapi_meta_record.o
obj-y += oapi_meta_service.o
obj-y += oapi_meta_antenna.o

# ---- include path----
ccflags-y += -I$(HLIB_DIR)/include
ccflags-y += -I$(DLIB_DIR)/include
ccflags-y += -I$(OCTO_DIR)/include
ccflags-y += -I$(OCTO_DIR)/api/protocol
ccflags-y += -I$(OCTO_DIR)/main/oxserver/include


