obj-y += copycontrol/
obj-y += psi/
obj-y += sc/
obj-y += ui/
obj-y += dscr/

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
