obj-y += nx_prism_keyboard.o
obj-y += nx_prism_simplekeyboard.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include

# Additional include path
cclfags-y += -I$(NATIVEAPP_UI_INCLUDE_DIR)/include


