obj-y += apk_cas_nagra.o
obj-y += apk_cas_irdeto.o
obj-y += apk_cas_verimatrix.o
obj-y += apk_cas_mmi.o
obj-y += apk_cas_ci.o
obj-y += apk_cas_action.o

# APPKIT v2 local include path
ccflags-y += -I$(OCTOTOP_SRC_DIR)/appkit/local_include

