obj-y										+= base/
obj-$(CONFIG_OP_UK_DTT)		+= ukdtt/
obj-$(CONFIG_OP_TDC)		+= tdc/
obj-y += pmgr_output.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

