############################################################
#     (c)2003-2012 Broadcom Corporation
#
#  This program is the proprietary software of Broadcom Corporation and/or its licensors,
#  and may only be used, duplicated, modified or distributed pursuant to the terms and
#  conditions of a separate, written license agreement executed between you and Broadcom
#  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
#  no license (express or implied), right to use, or waiver of any kind with respect to the
#  Software, and Broadcom expressly reserves all rights in and to the Software and all
#  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
#  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
#  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
#
#  Except as expressly set forth in the Authorized License,
#
#  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
#  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
#  and to use this information only in connection with your use of Broadcom integrated circuit products.
#
#  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
#  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
#  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
#  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
#  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
#  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
#  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
#  USE OR PERFORMANCE OF THE SOFTWARE.
#
#  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
#  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
#  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
#  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
#  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
#  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
#  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
#  ANY LIMITED REMEDY.
#
# $brcm_Workfile: b_os_lib.inc $
# $brcm_Revision: 5 $
# $brcm_Date: 8/20/12 9:47a $
#
# Module Description:
#   This file defines the sources, include paths, and defintions required
#   to use this library
#
# Revision History:
#
# Created: 03/05/2007 by Jon Garrett
#
# $brcm_Log: /nexus/lib/os/b_os_lib.inc $
# 
# 5   8/20/12 9:47a erickson
# SW7435-235: remove symlinks and duplicate code
# 
# 4   9/16/09 1:43p erickson
# SW7400-2511: add B_REFSW_ or NEXUS_ namespace to build variables
#
# 3   3/31/08 1:13p jgarrett
# PR 41043: Making time routines public, adding message queues
#
# 2   3/10/08 8:54p jgarrett
# PR 40306: adding time
#
# 1   3/10/08 1:57p jgarrett
# PR 40306: Adding oslib
#
############################################################

#
# Conditional options for this makefile
#
# None at this time
#

#
# Identify this library
#
B_LIBS += B_OS_LIB

#
# Define source files in this library
#
B_OS_LIB_SOURCES += \
                    $(B_LIB_TOP)/os/src/$(B_REFSW_OS)/b_os_lib.c \
                    $(B_LIB_TOP)/os/src/$(B_REFSW_OS)/b_os_message_queue.c \
                    $(B_LIB_TOP)/os/src/$(B_REFSW_OS)/b_os_mutex.c \
                    $(B_LIB_TOP)/os/src/$(B_REFSW_OS)/b_os_thread.c \
                    $(B_LIB_TOP)/os/src/$(B_REFSW_OS)/b_os_time.c
                    
# generic source
B_OS_LIB_SOURCES += \
                    $(B_LIB_TOP)/os/src/b_os_event.c \
                    $(B_LIB_TOP)/os/src/b_os_memory.c \
                    $(B_LIB_TOP)/os/src/b_os_scheduler.c
#
# Define public include path(s) for this library
#
B_OS_LIB_PUBLIC_INCLUDES += $(B_LIB_TOP)/os/include \
                            $(B_LIB_TOP)/os/include/$(B_REFSW_OS)

#
# Define private include path(s) for this library
#
B_OS_LIB_PRIVATE_INCLUDES += $(B_LIB_TOP)/os/src \
                             $(B_LIB_TOP)/os/src/$(B_REFSW_OS)

#
# Define other libs that this library is dependent upon.
# This will check for cyclic dependencies and setup include paths
#
#B_OS_LIB_DEPENDENCIES := ## N/A for this library

#
# Define extra C definitions
#
#B_OS_LIB_DEFINES += ## N/A for this library

#
# Define possible options - this is only for debug purposes, it does _not_ actually define them.
#
#B_OS_LIB_OPTIONS += ## N/A for this library

