obj-y += svc_epg_db_raw_lib.o
obj-y += svc_epg_db_raw_service.o
obj-y += svc_epg_db_raw_section.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw

# Additional include path

