obj-y += plugins/

obj-y += rest_datatype.o
obj-y += rest_datatype_channel.o
obj-y += rest_datatype_player.o
obj-y += rest_datatype_recorder.o
obj-y += rest_datatype_epg.o
obj-y += rest_datatype_schedule.o
obj-y += rest_datatype_scan.o
obj-y += rest_datatype_record.o
obj-y += rest_datatype_sysenv.o
obj-y += rest_datatype_settings.o
obj-y += rest_datatype_tuner.o

ccflags-y += -I$(NODEBINDER_SRC_DIR)/local_include
ccflags-y += -I$(NODEBINDER_SRC_DIR)/datatype/plugins/local_include

