obj-$(CONFIG_MW_CAS_NAGRA_IRDCMD) += irdcmd/
obj-$(CONFIG_MW_CAS_NAGRA_FEATURE_PPV) += ppv/

obj-y += na_mgr_cak_mgr.o
obj-y += na_mgr_cak_svc.o
obj-y += na_mgr_cak_ext.o
obj-$(CONFIG_MW_CAS_NAGRA_DALTEST) += na_mgr_cak_test.o
obj-$(CONFIG_MW_CAS_NAGRA_PRM) += na_mgr_dvl_mgr.o
obj-$(CONFIG_MW_CAS_NAGRA_DALAPI_7_1_ABOVE) += na_ca_session_mgr.o

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas


# Additional include path

