obj-y += oapi_drmagent.o

# Basic include path
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.oapimgr

# ---- include path----
ccflags-y += -I$(HLIB_DIR)/include
ccflags-y += -I$(DLIB_DIR)/include
ccflags-y += -I$(OCTO_DIR)/include
ccflags-y += -I$(OCTO_DIR)/api/protocol
ccflags-y += -I$(OCTO_DIR)/main/oxserver/include


