#
obj-y += tmbslTDA18260.o
obj-y += tmbslTDA18260_Instance.o
obj-y += tmbslTDA18260_LoDetuning.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/tmbslTDA18260/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/tmbslTDA18260/cfg    

inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/tmddTDA18260Stream/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/tn18260/tmddTDA18260Shared/inc