obj-y += rema_DMO_Storage_PhysicalMedium.o
obj-y += rema_DMO_Storage_LogicalVolume.o

ccflags-y += -I$(THIRDPARTY_DIR)/cwmp/include
ccflags-y += -I$(REMA_MAIN_DIR)/
ccflags-y += -I$(REMA_MAIN_DIR)/module
