obj-y += ui/
obj-y += xmgr_cas_va.o
obj-y += xmgr_cas_va_util.o
obj-y += xmgr_cas_va_sc.o
obj-y += xmgr_cas_va_adapt.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

