-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = generatekeypair

DRM_MODULE_CFLAGS =

SOURCES =                \
	generatekeypair.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
