#!/bin/sh

	umount /var/lib/humaxtv
	umount /var/lib/humaxtv_backup
	umount /var/lib/humaxtv_user
	ubidetach -m 5
	ubiattach -m 5
	mount -t ubifs ubi2:dbdata /var/lib/humaxtv
	mount -t ubifs ubi2:dbbackup /var/lib/humaxtv_backup
	mount -t ubifs ubi2:dbuser /var/lib/humaxtv_user
