#!/bin/sh
RESULT=0

umount /var/lib/humaxtv
RESULT=$(($RESULT + $?))

umount /var/lib/humaxtv_backup
RESULT=$(($RESULT + $?))

umount /var/lib/humaxtv_user
RESULT=$(($RESULT + $?))

if [[ $RESULT != 0 ]] ; then
	echo "-----------------------------------------------"
	echo "There are open files in /var/lib/xxx directorys"
	echo "-----------------------------------------------"
	lsof | grep /var/lib
	exit $RESULT
else
	exit 0
fi

