/***************************************************************************
 *     Copyright (c) 1999-2010, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_wse_1.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 1/25/10 10:15p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jan 22 20:27:53 2010
 *                 MD5 Checksum         a2d1f2163f65e87d228a0fb491cb442d
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7125/rdb/c0/bchp_wse_1.h $
 * 
 * Hydra_Software_Devel/1   1/25/10 10:15p albertl
 * SW7125-177: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_WSE_1_H__
#define BCHP_WSE_1_H__

/***************************************************************************
 *WSE_1 - WSE_1 registers
 ***************************************************************************/
#define BCHP_WSE_1_control                       0x00888704 /* WSS Control Register */
#define BCHP_WSE_1_wss_data                      0x00888708 /* WSS & VPS Data 0 Register */
#define BCHP_WSE_1_vps_data_1                    0x0088870c /* VPS Data 1 Register */
#define BCHP_WSE_1_vps_control                   0x00888710 /* VPS Control Register */
#define BCHP_WSE_1_revid                         0x00888714 /* WSS Revision ID register */

#endif /* #ifndef BCHP_WSE_1_H__ */

/* End of File */
