/***************************************************************************
 *     Copyright (c) 1999-2010, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_ds_tuner_core_gen_0_1.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 1/25/10 8:12p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Jan 22 20:20:31 2010
 *                 MD5 Checksum         a2d1f2163f65e87d228a0fb491cb442d
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7125/rdb/c0/bchp_ds_tuner_core_gen_0_1.h $
 * 
 * Hydra_Software_Devel/1   1/25/10 8:12p albertl
 * SW7125-177: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_DS_TUNER_CORE_GEN_0_1_H__
#define BCHP_DS_TUNER_CORE_GEN_0_1_H__

/***************************************************************************
 *DS_TUNER_CORE_GEN_0_1 - Tuner Core General Registers 0 1
 ***************************************************************************/
#define BCHP_DS_TUNER_CORE_GEN_0_1_CTRL_0        0x04c54000 /* Tuner Core General Control 0 Register */
#define BCHP_DS_TUNER_CORE_GEN_0_1_IQAMP         0x04c54010 /* I/Q Imbalance Amplitude Control */
#define BCHP_DS_TUNER_CORE_GEN_0_1_IQPHS         0x04c54014 /* I/Q Imbalance Phase Control */
#define BCHP_DS_TUNER_CORE_GEN_0_1_IQAMPI        0x04c54018 /* I/Q Imbalance Amplitude Estimator Integrator */
#define BCHP_DS_TUNER_CORE_GEN_0_1_IQPHSI        0x04c5401c /* I/Q Imbalance Phase Estimator Integrator */

#endif /* #ifndef BCHP_DS_TUNER_CORE_GEN_0_1_H__ */

/* End of File */
