/***************************************************************************
 *     Copyright (c) 2003-2013, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#include "bstd.h"
#include "bchp.h"
#include "bkni.h"
#include "bmxt_priv.h"
#include "bmxt.h"
#if (!BMXT_REG_SUPPORT)
#include "bmxt_4538_demod_xpt_fe.h"
#else
#include "bchp_demod_xpt_fe.h"
#endif
#if BMXT_HAB_SUPPORT
#include "bhab.h"
#endif
#if BMXT_RPC_SUPPORT
#include "brpc.h"
#if BMXT_3383_SUPPORT
#include "brpc_3255.h"
#else
#include "brpc_docsis.h"
#endif
#endif

BDBG_MODULE(bmxt_4538);

#include "bmxt_common.c"

#ifndef BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1
#define BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_MINI_PID_PARSER1_TB_CTRL1
#define BCHP_DEMOD_XPT_FE_MINI_PID_PARSER1_TB_CTRL1 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_LATCH_SYNC_COUNT_INTO_TIMESTAMP_MASK
#define BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_LATCH_SYNC_COUNT_INTO_TIMESTAMP_MASK 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_LATCH_SYNC_COUNT_INTO_TIMESTAMP_SHIFT
#define BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_LATCH_SYNC_COUNT_INTO_TIMESTAMP_SHIFT 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_TBG_PRI_BAND_NUM_MASK
#define BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_TBG_PRI_BAND_NUM_MASK 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_TBG_PRI_BAND_NUM_SHIFT
#define BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_TBG_PRI_BAND_NUM_SHIFT 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_TB_ENABLE_MASK
#define BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_TB_ENABLE_MASK 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_TB_ENABLE_SHIFT
#define BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1_TB_ENABLE_SHIFT 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL1
#define BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL1 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL1_TB_MARKER_TAG_MASK
#define BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL1_TB_MARKER_TAG_MASK 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL1_TB_MARKER_TAG_SHIFT
#define BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL1_TB_MARKER_TAG_SHIFT 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL2
#define BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL2 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL2_MARKER_PID_VALUE_MASK
#define BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL2_MARKER_PID_VALUE_MASK 0
#endif
#ifndef BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL2_MARKER_PID_VALUE_SHIFT
#define BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL2_MARKER_PID_VALUE_SHIFT 0
#endif

BERR_Code BMXT_4538_P_GetDefaultSettings(BMXT_Settings *pSettings)
{
    return BMXT_P_GetDefaultSettings_common(pSettings);
}

BERR_Code BMXT_4538_Open(BMXT_Handle *pHandle, BCHP_Handle hChp, BREG_Handle hReg, const BMXT_Settings *pSettings)
{
    return BMXT_Open_common(pHandle, hChp, hReg, pSettings);
}

void BMXT_4538_Close(BMXT_Handle handle)
{
    BMXT_Close_common(handle);
}

BERR_Code BMXT_4538_GetMtsifStatus(BMXT_Handle handle, BMXT_MtsifStatus *pStatus)
{
    return BMXT_GetMtsifStatus_common(handle, pStatus);
}

BERR_Code BMXT_4538_GetInputBandStatus(BMXT_Handle handle, BMXT_InputBandStatus *pStatus)
{
    return BMXT_GetInputBandStatus_common(handle, pStatus);
}

BERR_Code BMXT_4538_GetParserConfig(BMXT_Handle handle, unsigned parserNum, BMXT_ParserConfig *pConfig)
{
    return BMXT_GetParserConfig_common(handle, parserNum, pConfig);
}

BERR_Code BMXT_4538_SetParserConfig(BMXT_Handle handle, unsigned parserNum, const BMXT_ParserConfig *pConfig)
{
    return BMXT_SetParserConfig_common(handle, parserNum, pConfig);
}

BERR_Code BMXT_4538_GetParserMapping(BMXT_Handle handle, BMXT_ParserBandMapping *pMapping)
{
    return BMXT_GetParserMapping_common(handle, pMapping);
}

BERR_Code BMXT_4538_SetParserMapping(BMXT_Handle handle, const BMXT_ParserBandMapping *pMapping)
{
    return BMXT_SetParserMapping_common(handle, pMapping);
}

BERR_Code BMXT_4538_GetInputBandConfig(BMXT_Handle handle, unsigned bandNum, BMXT_InputBandConfig *pConfig)
{
    return BMXT_GetInputBandConfig_common(handle, bandNum, pConfig);
}

BERR_Code BMXT_4538_SetInputBandConfig(BMXT_Handle handle, unsigned bandNum, const BMXT_InputBandConfig *pConfig)
{
    return BMXT_SetInputBandConfig_common(handle, bandNum, pConfig);
}

uint32_t BMXT_4538_ReadIntStatusRegister(BMXT_Handle handle, BMXT_IntReg intReg)
{
    return BMXT_ReadIntStatusRegister_common(handle, intReg);
}

/****************************************************************
TSMF APIs
****************************************************************/

BERR_Code BMXT_4538_TSMF_GetFldVerifyConfig(BMXT_Handle handle, unsigned tsmfNum, BMXT_TSMFFldVerifyConfig *pConfig)
{
    return BMXT_TSMF_GetFldVerifyConfig_common(handle, tsmfNum, pConfig);
}

BERR_Code BMXT_4538_TSMF_SetFldVerifyConfig(BMXT_Handle handle, unsigned tsmfNum, const BMXT_TSMFFldVerifyConfig *pConfig)
{
    return BMXT_TSMF_SetFldVerifyConfig_common(handle, tsmfNum, pConfig);
}

BERR_Code BMXT_4538_TSMF_EnableAutoMode(BMXT_Handle handle, BMXT_TSMFInputSel input, unsigned tsmfNum, uint8_t relativeTsNum)
{
    return BMXT_TSMF_EnableAutoMode_common(handle, input, tsmfNum, relativeTsNum);
}

BERR_Code BMXT_4538_TSMF_EnableSemiAutoMode(BMXT_Handle handle, BMXT_TSMFInputSel input, unsigned tsmfNum, uint32_t slotMapLo, uint32_t slotMapHi, uint8_t relativeTsNum)
{
    return BMXT_TSMF_EnableSemiAutoMode_common(handle, input, tsmfNum, slotMapLo, slotMapHi, relativeTsNum);
}

BERR_Code BMXT_4538_TSMF_DisableTsmf(BMXT_Handle handle, unsigned tsmfNum)
{
    return BMXT_TSMF_DisableTsmf_common(handle, tsmfNum);
}

BERR_Code BMXT_4538_TSMF_SetParserConfig(BMXT_Handle handle, unsigned parserNum, unsigned tsmfNum, bool enable)
{
    return BMXT_TSMF_SetParserConfig_common(handle, parserNum, tsmfNum, enable);
}

/****************************************************************
Power APIs
****************************************************************/

void BMXT_4538_GetPowerSaverSettings(BMXT_Handle handle, BMXT_PowerSaverSettings *pSettings)
{
    BMXT_GetPowerSaverSettings_common(handle, pSettings);
}

BERR_Code BMXT_4538_SetPowerSaverSettings(BMXT_Handle handle, const BMXT_PowerSaverSettings *pSettings)
{
    return BMXT_SetPowerSaverSettings_common(handle, pSettings);
}

/****************************************************************
TBG APIs
****************************************************************/

/* no function ptr redirection for bonding-related functions */
#define PARSER_TB_CTRL_STEP (BCHP_DEMOD_XPT_FE_MINI_PID_PARSER1_TB_CTRL1 - BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1)

BERR_Code BMXT_Tbg_GetParserConfig(BMXT_Handle handle, unsigned parserNum, BMXT_Tbg_ParserConfig *pConfig)
{
    uint32_t addr, reg;
    BDBG_ASSERT(handle);
    BDBG_ASSERT(pConfig);

    if (parserNum >= handle->num.pbTbg) {
        BDBG_ERR(("ParserNum %lu is out of range!", parserNum));
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }

    addr = BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1 + parserNum * PARSER_TB_CTRL_STEP;
    reg = BMXT_RegRead32(handle, addr);
    pConfig->latchSyncCount = BCHP_GET_FIELD_DATA(reg, DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1, LATCH_SYNC_COUNT_INTO_TIMESTAMP);
    pConfig->primaryBandNum = BCHP_GET_FIELD_DATA(reg, DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1, TBG_PRI_BAND_NUM);
    pConfig->enable = BCHP_GET_FIELD_DATA(reg, DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1, TB_ENABLE);

    return BERR_SUCCESS;
}

BERR_Code BMXT_Tbg_SetParserConfig(BMXT_Handle handle, unsigned parserNum, const BMXT_Tbg_ParserConfig *pConfig)
{
    uint32_t addr, reg;
    BDBG_ASSERT(handle);
    BDBG_ASSERT(pConfig);

    if (parserNum >= handle->num.pbTbg) {
        BDBG_ERR(("ParserNum %lu is out of range!", parserNum));
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }

    addr = BCHP_DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1 + parserNum * PARSER_TB_CTRL_STEP;
    BDBG_MSG(("TBG: PB%u: latch %u, priBand %u, enable %u ", parserNum, pConfig->latchSyncCount, pConfig->primaryBandNum, pConfig->enable));
    reg = BMXT_RegRead32(handle, addr);
    BCHP_SET_FIELD_DATA(reg, DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1, LATCH_SYNC_COUNT_INTO_TIMESTAMP, pConfig->latchSyncCount);
    BCHP_SET_FIELD_DATA(reg, DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1, TBG_PRI_BAND_NUM, pConfig->primaryBandNum);
    BCHP_SET_FIELD_DATA(reg, DEMOD_XPT_FE_MINI_PID_PARSER0_TB_CTRL1, TB_ENABLE, pConfig->enable);
    BMXT_RegWrite32(handle, addr, reg);

    return BERR_SUCCESS;
}

BERR_Code BMXT_Tbg_GetGlobalConfig(BMXT_Handle handle, BMXT_Tbg_GlobalConfig *pConfig)
{
    uint32_t reg;
    BDBG_ASSERT(handle);
    BDBG_ASSERT(pConfig);

    if (handle->num.pbTbg==0) {
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }

    reg = BMXT_RegRead32(handle, BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL1);
    pConfig->markerTag = BCHP_GET_FIELD_DATA(reg, DEMOD_XPT_FE_TB_GLOBAL_CTRL1, TB_MARKER_TAG);

    reg = BMXT_RegRead32(handle, BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL2);
    pConfig->markerPidValue = BCHP_GET_FIELD_DATA(reg, DEMOD_XPT_FE_TB_GLOBAL_CTRL2, MARKER_PID_VALUE);

#if BMXT_HAB_SUPPORT
{
    BMXT_Chip chip = handle->settings.chip;
    BHAB_Handle hab = handle->hHab;
    uint32_t temp_val, val = 0;
    BERR_Code rc;

    if (BMXT_IS_HAB_BASED(chip)) {
        /* make direct HAB call, instead of calling BMXT_RegRead32 wrapper */
        switch (chip) {
            case BMXT_Chip_e4538:
                reg = 0x90820; /* BCHP_JTAG_OTP_GENERAL_STATUS_3 */
                rc = BHAB_ReadRegister(hab, reg, &val);
                if (rc!=BERR_SUCCESS) {
                    rc = BERR_TRACE(rc);
                    goto done;
                }
                break;
            case BMXT_Chip_e45216:
                reg = 0x692103c; /* BCHP_JTAG_OTP_GENERAL_STATUS_10 */
                rc = BHAB_ReadRegister(hab, reg, &temp_val);
                if (rc!=BERR_SUCCESS) {
                    rc = BERR_TRACE(rc);
                    goto done;
                }
                val = (temp_val & 0x03ffffff);

                reg = 0x6921040; /* BCHP_JTAG_OTP_GENERAL_STATUS_11 */
                rc = BHAB_ReadRegister(hab, reg, &temp_val);
                if (rc!=BERR_SUCCESS) {
                    rc = BERR_TRACE(rc);
                    goto done;
                }
                val |= ((temp_val & 0x3f) << 26);
                break;
            default: BERR_TRACE(BERR_INVALID_PARAMETER); goto done;
        }
    }
    pConfig->markerFeedId = val;
}
done:
#endif
    return BERR_SUCCESS;
}

BERR_Code BMXT_Tbg_SetGlobalConfig(BMXT_Handle handle, const BMXT_Tbg_GlobalConfig *pConfig)
{
    uint32_t reg;
    BDBG_ASSERT(handle);
    BDBG_ASSERT(pConfig);

    if (handle->num.pbTbg==0) {
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }

    reg = BMXT_RegRead32(handle, BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL1);
    BCHP_SET_FIELD_DATA(reg, DEMOD_XPT_FE_TB_GLOBAL_CTRL1, TB_MARKER_TAG, pConfig->markerTag);
    BMXT_RegWrite32(handle, BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL1, reg);

    reg = BMXT_RegRead32(handle, BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL2);
    BCHP_SET_FIELD_DATA(reg, DEMOD_XPT_FE_TB_GLOBAL_CTRL2, MARKER_PID_VALUE, pConfig->markerPidValue);
    BMXT_RegWrite32(handle, BCHP_DEMOD_XPT_FE_TB_GLOBAL_CTRL2, reg);

    return BERR_SUCCESS;
}

/****************************************************************
Debug
****************************************************************/

#define MAKE_REG(name) BCHP_##name
#define MAKE_STR(name) #name
#define PRINT_REG(name) BKNI_Printf("%-s = %08x\n", MAKE_STR(name), BMXT_RegRead32(handle, MAKE_REG(name)))

void BMXT_4538_P_RegDump(BMXT_Handle handle, unsigned param)
{
    /* param==1 prints a small subset */
    if (param!=1) {
        PRINT_REG(DEMOD_XPT_FE_FE_CTRL);
        PRINT_REG(DEMOD_XPT_FE_PWR_CTRL);
        PRINT_REG(DEMOD_XPT_FE_MAX_PID_CHANNEL);
        PRINT_REG(DEMOD_XPT_FE_IB_SYNC_DETECT_CTRL);
        PRINT_REG(DEMOD_XPT_FE_INTR_STATUS0_REG);
        PRINT_REG(DEMOD_XPT_FE_INTR_STATUS1_REG);
        PRINT_REG(DEMOD_XPT_FE_INTR_STATUS2_REG);
        PRINT_REG(DEMOD_XPT_FE_INTR_STATUS0_REG_EN);
        PRINT_REG(DEMOD_XPT_FE_INTR_STATUS1_REG_EN);
        PRINT_REG(DEMOD_XPT_FE_INTR_STATUS2_REG_EN);
        PRINT_REG(DEMOD_XPT_FE_TSMF_INTR_STATUS0_REG);
        PRINT_REG(DEMOD_XPT_FE_TSMF_INTR_STATUS0_REG_EN);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX_INTR_STATUS0_REG);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX_INTR_STATUS0_REG_EN);
        PRINT_REG(DEMOD_XPT_FE_PARSERS_TSMF_FRAME_ERROR_INTR_STATUS0_REG);
        PRINT_REG(DEMOD_XPT_FE_PARSERS_TSMF_SYNC_ERROR_INTR_STATUS0_REG);
        PRINT_REG(DEMOD_XPT_FE_PARSERS_INBUFF_OVFL_ERROR_INTR_STATUS0_REG);
        PRINT_REG(DEMOD_XPT_FE_PARSERS_TSMF_FRAME_ERROR_INTR_STATUS0_REG_EN);
        PRINT_REG(DEMOD_XPT_FE_PARSERS_TSMF_SYNC_ERROR_INTR_STATUS0_REG_EN);
        PRINT_REG(DEMOD_XPT_FE_PARSERS_INBUFF_OVFL_ERROR_INTR_STATUS0_REG_EN);
        PRINT_REG(DEMOD_XPT_FE_PARSER_BAND0_BAND31_SRC);
        PRINT_REG(DEMOD_XPT_FE_PARSER_BAND0_BAND15_MTSIF_RX_SRC);
        PRINT_REG(DEMOD_XPT_FE_PARSER_BAND16_BAND31_MTSIF_RX_SRC);
        PRINT_REG(DEMOD_XPT_FE_ATS_COUNTER_CTRL);
        PRINT_REG(DEMOD_XPT_FE_ATS_TS_MOD300);
        PRINT_REG(DEMOD_XPT_FE_ATS_TS_BINARY);
        PRINT_REG(DEMOD_XPT_FE_TV_STATUS_0);
        PRINT_REG(DEMOD_XPT_FE_TV_STATUS_1);
        PRINT_REG(DEMOD_XPT_FE_TV_STATUS_2);
        PRINT_REG(DEMOD_XPT_FE_TV_STATUS_3);
        PRINT_REG(DEMOD_XPT_FE_TV_STATUS_4);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX_TV_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB0_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB0_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB1_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB1_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB2_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB2_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB3_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB3_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB4_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB4_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB5_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB5_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB6_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB6_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB7_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB7_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB8_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB8_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB9_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB9_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB10_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB10_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB11_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB11_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB12_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB12_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB13_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB13_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB14_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB14_SYNC_COUNT);
        PRINT_REG(DEMOD_XPT_FE_IB15_CTRL);
        PRINT_REG(DEMOD_XPT_FE_IB15_SYNC_COUNT);
    }
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER0_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER0_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER1_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER1_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER2_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER2_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER3_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER3_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER4_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER4_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER5_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER5_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER6_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER6_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER7_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER7_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER8_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER8_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER9_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER9_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER10_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER10_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER11_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER11_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER12_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER12_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER13_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER13_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER14_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER14_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER15_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER15_CTRL2);
#ifdef BCHP_DEMOD_XPT_FE_MINI_PID_PARSER16_CTRL1
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER16_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER16_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER17_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER17_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER18_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER18_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER19_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER19_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER20_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER20_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER21_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER21_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER22_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER22_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER23_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER23_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER24_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER24_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER25_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER25_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER26_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER26_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER27_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER27_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER28_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER28_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER29_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER29_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER30_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER30_CTRL2);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER31_CTRL1);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER31_CTRL2);
#endif
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER0_TO_PARSER3_BAND_ID);
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER4_TO_PARSER7_BAND_ID);
#ifdef BCHP_DEMOD_XPT_FE_MINI_PID_PARSER8_TO_PARSER11_BAND_ID
    PRINT_REG(DEMOD_XPT_FE_MINI_PID_PARSER8_TO_PARSER11_BAND_ID);
#endif
    if (param!=1) {
        PRINT_REG(DEMOD_XPT_FE_TSMF0_CTRL);
        PRINT_REG(DEMOD_XPT_FE_TSMF0_SLOT_MAP_LO);
        PRINT_REG(DEMOD_XPT_FE_TSMF0_SLOT_MAP_HI);
        PRINT_REG(DEMOD_XPT_FE_TSMF0_STATUS);
        PRINT_REG(DEMOD_XPT_FE_TSMF1_CTRL);
        PRINT_REG(DEMOD_XPT_FE_TSMF1_SLOT_MAP_LO);
        PRINT_REG(DEMOD_XPT_FE_TSMF1_SLOT_MAP_HI);
        PRINT_REG(DEMOD_XPT_FE_TSMF1_STATUS);
        PRINT_REG(DEMOD_XPT_FE_TSMF2_CTRL);
        PRINT_REG(DEMOD_XPT_FE_TSMF2_SLOT_MAP_LO);
        PRINT_REG(DEMOD_XPT_FE_TSMF2_SLOT_MAP_HI);
        PRINT_REG(DEMOD_XPT_FE_TSMF2_STATUS);
        PRINT_REG(DEMOD_XPT_FE_TSMF3_CTRL);
        PRINT_REG(DEMOD_XPT_FE_TSMF3_SLOT_MAP_LO);
        PRINT_REG(DEMOD_XPT_FE_TSMF3_SLOT_MAP_HI);
        PRINT_REG(DEMOD_XPT_FE_TSMF3_STATUS);
        PRINT_REG(DEMOD_XPT_FE_TSMF4_CTRL);
        PRINT_REG(DEMOD_XPT_FE_TSMF4_SLOT_MAP_LO);
        PRINT_REG(DEMOD_XPT_FE_TSMF4_SLOT_MAP_HI);
        PRINT_REG(DEMOD_XPT_FE_TSMF4_STATUS);
        PRINT_REG(DEMOD_XPT_FE_TSMF5_CTRL);
        PRINT_REG(DEMOD_XPT_FE_TSMF5_SLOT_MAP_LO);
        PRINT_REG(DEMOD_XPT_FE_TSMF5_SLOT_MAP_HI);
        PRINT_REG(DEMOD_XPT_FE_TSMF5_STATUS);
        PRINT_REG(DEMOD_XPT_FE_TSMF6_CTRL);
        PRINT_REG(DEMOD_XPT_FE_TSMF6_SLOT_MAP_LO);
        PRINT_REG(DEMOD_XPT_FE_TSMF6_SLOT_MAP_HI);
        PRINT_REG(DEMOD_XPT_FE_TSMF6_STATUS);
        PRINT_REG(DEMOD_XPT_FE_TSMF7_CTRL);
        PRINT_REG(DEMOD_XPT_FE_TSMF7_SLOT_MAP_LO);
        PRINT_REG(DEMOD_XPT_FE_TSMF7_SLOT_MAP_HI);
        PRINT_REG(DEMOD_XPT_FE_TSMF7_STATUS);
#ifdef BCHP_DEMOD_XPT_FE_TSMF8_CTRL
        PRINT_REG(DEMOD_XPT_FE_TSMF8_CTRL);
        PRINT_REG(DEMOD_XPT_FE_TSMF8_SLOT_MAP_LO);
        PRINT_REG(DEMOD_XPT_FE_TSMF8_SLOT_MAP_HI);
        PRINT_REG(DEMOD_XPT_FE_TSMF8_STATUS);
        PRINT_REG(DEMOD_XPT_FE_TSMF9_CTRL);
        PRINT_REG(DEMOD_XPT_FE_TSMF9_SLOT_MAP_LO);
        PRINT_REG(DEMOD_XPT_FE_TSMF9_SLOT_MAP_HI);
        PRINT_REG(DEMOD_XPT_FE_TSMF9_STATUS);
#endif
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_CTRL1);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_SECRET_WORD);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND0_BAND31_ID_DROP);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND0_BAND3_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND4_BAND7_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND8_BAND11_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND12_BAND15_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND16_BAND19_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND20_BAND23_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND24_BAND27_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND28_BAND31_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND32_BAND35_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND36_BAND39_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND40_BAND43_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND44_BAND47_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND48_BAND51_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND52_BAND55_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND56_BAND59_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_BAND60_BAND63_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_RX0_PKT_BAND0_BAND31_DETECT);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_CTRL1);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BLOCK_OUT);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_STATUS);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_SECRET_WORD);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND0_BAND3_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND4_BAND7_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND8_BAND11_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND12_BAND15_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND16_BAND19_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND20_BAND23_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND24_BAND27_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND28_BAND31_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND32_BAND35_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND36_BAND39_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND40_BAND43_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND44_BAND47_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND48_BAND51_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND52_BAND55_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND56_BAND59_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX0_BAND60_BAND63_ID);
#ifdef BCHP_DEMOD_XPT_FE_MTSIF_TX1_CTRL1
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_CTRL1);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BLOCK_OUT);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_STATUS);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_SECRET_WORD);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND0_BAND3_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND4_BAND7_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND8_BAND11_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND12_BAND15_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND16_BAND19_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND20_BAND23_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND24_BAND27_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND28_BAND31_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND32_BAND35_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND36_BAND39_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND40_BAND43_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND44_BAND47_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND48_BAND51_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND52_BAND55_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND56_BAND59_ID);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_TX1_BAND60_BAND63_ID);
#endif
#ifdef BCHP_DEMOD_XPT_FE_MTSIF_LEGACY_CTRL
        PRINT_REG(DEMOD_XPT_FE_MTSIF_LEGACY_CTRL);
        PRINT_REG(DEMOD_XPT_FE_MTSIF_LEGACY_STATUS);
#endif
    }

    if (param!=1) {
        unsigned i;
        BKNI_Printf("DEMOD_XPT_FE_PID_TABLE[0..255]\n");
        for (i=0; i<255; i++) {
            BKNI_Printf("[%3u] %08x\n", i, BMXT_RegRead32(handle, BCHP_DEMOD_XPT_FE_PID_TABLE_i_ARRAY_BASE + (4*i)));
        }
        BKNI_Printf("DEMOD_XPT_FE_SPID_TABLE[0..255]\n");
        for (i=0; i<255; i++) {
            BKNI_Printf("[%3u] %08x\n", i, BMXT_RegRead32(handle, BCHP_DEMOD_XPT_FE_SPID_TABLE_i_ARRAY_BASE + (4*i)));
        }
    }
}
