obj-y += apk_meta_record.o
obj-y += apk_meta_schedule.o
obj-y += apk_meta_service.o
obj-y += apk_meta_antenna.o
obj-y += apk_meta_query.o
obj-y += apk_meta_search.o
obj-y += apk_meta_mail.o

#obj-y += dummy_meta_schedule.o

# APPKIT v2 local include path
ccflags-y += -I$(OCTOTOP_SRC_DIR)/appkit/local_include

