obj-y += nx_prism_menu_general.o
obj-y += nx_prism_menu_language.o
obj-y += nx_prism_menu_time.o
obj-y += nx_prism_menu_video.o
obj-y += nx_prism_menu_audio.o
obj-y += nx_prism_menu_parentalcontrol.o
obj-y += nx_prism_menu_osd.o
obj-y += nx_prism_menu_audiolipsync.o

# Additional include path
ccflags-y += -I../../../../../../../make/include

