obj-$(CONFIG_MW_DOWNLOAD_OTA_IMAGE) += ota/
obj-$(CONFIG_MW_SI_AIT) += hbbtv/
obj-$(CONFIG_MW_DOWNLOAD_SAT_RECORD) += satrecord/
obj-y += models/

obj-y += xsvc_download.o
obj-y += xsvc_download_si.o
obj-y += psvc_download.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

