/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_mmisc.h $
 * $brcm_Revision: Hydra_Software_Devel/3 $
 * $brcm_Date: 12/12/11 3:17p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Mon Dec 12 12:00:26 2011
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7346/rdb/b0/bchp_mmisc.h $
 * 
 * Hydra_Software_Devel/3   12/12/11 3:17p pntruong
 * SW7346-143: Resynced with central rdb.
 *
 ***************************************************************************/

#ifndef BCHP_MMISC_H__
#define BCHP_MMISC_H__

/***************************************************************************
 *MMISC - BVN Middle Control Registers
 ***************************************************************************/
#define BCHP_MMISC_SW_INIT                       0x00622800 /* BVN Middle Soft Init */
#define BCHP_MMISC_TEST_PORT_SEL                 0x00622804 /* BVN Middle Test Port Select */
#define BCHP_MMISC_TEST_PORT_DATA                0x00622808 /* BVN Middle Test Port Status */
#define BCHP_MMISC_BVNM_CLOCK_CTRL               0x00622820 /* BVN Middle clock control register */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT        0x0062280c /* BVN Video Network Switch Frontend Channels Init */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT        0x00622810 /* BVN Video Network Switch Backend Channels Init */
#define BCHP_MMISC_SCRATCH_0                     0x00622814 /* Scratch Register */

/***************************************************************************
 *SW_INIT - BVN Middle Soft Init
 ***************************************************************************/
/* MMISC :: SW_INIT :: reserved0 [31:30] */
#define BCHP_MMISC_SW_INIT_reserved0_MASK                          0xc0000000
#define BCHP_MMISC_SW_INIT_reserved0_SHIFT                         30

/* MMISC :: SW_INIT :: DNR_0 [29:29] */
#define BCHP_MMISC_SW_INIT_DNR_0_MASK                              0x20000000
#define BCHP_MMISC_SW_INIT_DNR_0_SHIFT                             29
#define BCHP_MMISC_SW_INIT_DNR_0_DEFAULT                           0x00000000

/* MMISC :: SW_INIT :: reserved1 [28:26] */
#define BCHP_MMISC_SW_INIT_reserved1_MASK                          0x1c000000
#define BCHP_MMISC_SW_INIT_reserved1_SHIFT                         26

/* MMISC :: SW_INIT :: LBOX_1 [25:25] */
#define BCHP_MMISC_SW_INIT_LBOX_1_MASK                             0x02000000
#define BCHP_MMISC_SW_INIT_LBOX_1_SHIFT                            25
#define BCHP_MMISC_SW_INIT_LBOX_1_DEFAULT                          0x00000000

/* MMISC :: SW_INIT :: LBOX_0 [24:24] */
#define BCHP_MMISC_SW_INIT_LBOX_0_MASK                             0x01000000
#define BCHP_MMISC_SW_INIT_LBOX_0_SHIFT                            24
#define BCHP_MMISC_SW_INIT_LBOX_0_DEFAULT                          0x00000000

/* MMISC :: SW_INIT :: reserved2 [23:21] */
#define BCHP_MMISC_SW_INIT_reserved2_MASK                          0x00e00000
#define BCHP_MMISC_SW_INIT_reserved2_SHIFT                         21

/* MMISC :: SW_INIT :: MVP_0 [20:20] */
#define BCHP_MMISC_SW_INIT_MVP_0_MASK                              0x00100000
#define BCHP_MMISC_SW_INIT_MVP_0_SHIFT                             20
#define BCHP_MMISC_SW_INIT_MVP_0_DEFAULT                           0x00000000

/* MMISC :: SW_INIT :: reserved3 [19:10] */
#define BCHP_MMISC_SW_INIT_reserved3_MASK                          0x000ffc00
#define BCHP_MMISC_SW_INIT_reserved3_SHIFT                         10

/* MMISC :: SW_INIT :: VNET_B [09:09] */
#define BCHP_MMISC_SW_INIT_VNET_B_MASK                             0x00000200
#define BCHP_MMISC_SW_INIT_VNET_B_SHIFT                            9
#define BCHP_MMISC_SW_INIT_VNET_B_DEFAULT                          0x00000000

/* MMISC :: SW_INIT :: VNET_F [08:08] */
#define BCHP_MMISC_SW_INIT_VNET_F_MASK                             0x00000100
#define BCHP_MMISC_SW_INIT_VNET_F_SHIFT                            8
#define BCHP_MMISC_SW_INIT_VNET_F_DEFAULT                          0x00000000

/* MMISC :: SW_INIT :: reserved4 [07:04] */
#define BCHP_MMISC_SW_INIT_reserved4_MASK                          0x000000f0
#define BCHP_MMISC_SW_INIT_reserved4_SHIFT                         4

/* MMISC :: SW_INIT :: SCL_3 [03:03] */
#define BCHP_MMISC_SW_INIT_SCL_3_MASK                              0x00000008
#define BCHP_MMISC_SW_INIT_SCL_3_SHIFT                             3
#define BCHP_MMISC_SW_INIT_SCL_3_DEFAULT                           0x00000000

/* MMISC :: SW_INIT :: SCL_2 [02:02] */
#define BCHP_MMISC_SW_INIT_SCL_2_MASK                              0x00000004
#define BCHP_MMISC_SW_INIT_SCL_2_SHIFT                             2
#define BCHP_MMISC_SW_INIT_SCL_2_DEFAULT                           0x00000000

/* MMISC :: SW_INIT :: SCL_1 [01:01] */
#define BCHP_MMISC_SW_INIT_SCL_1_MASK                              0x00000002
#define BCHP_MMISC_SW_INIT_SCL_1_SHIFT                             1
#define BCHP_MMISC_SW_INIT_SCL_1_DEFAULT                           0x00000000

/* MMISC :: SW_INIT :: SCL_0 [00:00] */
#define BCHP_MMISC_SW_INIT_SCL_0_MASK                              0x00000001
#define BCHP_MMISC_SW_INIT_SCL_0_SHIFT                             0
#define BCHP_MMISC_SW_INIT_SCL_0_DEFAULT                           0x00000000

/***************************************************************************
 *TEST_PORT_SEL - BVN Middle Test Port Select
 ***************************************************************************/
/* MMISC :: TEST_PORT_SEL :: reserved0 [31:02] */
#define BCHP_MMISC_TEST_PORT_SEL_reserved0_MASK                    0xfffffffc
#define BCHP_MMISC_TEST_PORT_SEL_reserved0_SHIFT                   2

/* MMISC :: TEST_PORT_SEL :: TEST_PORT_SEL [01:00] */
#define BCHP_MMISC_TEST_PORT_SEL_TEST_PORT_SEL_MASK                0x00000003
#define BCHP_MMISC_TEST_PORT_SEL_TEST_PORT_SEL_SHIFT               0
#define BCHP_MMISC_TEST_PORT_SEL_TEST_PORT_SEL_DEFAULT             0x00000000
#define BCHP_MMISC_TEST_PORT_SEL_TEST_PORT_SEL_TP_OUT_3            3
#define BCHP_MMISC_TEST_PORT_SEL_TEST_PORT_SEL_TP_OUT_2            2
#define BCHP_MMISC_TEST_PORT_SEL_TEST_PORT_SEL_TP_OUT_1            1
#define BCHP_MMISC_TEST_PORT_SEL_TEST_PORT_SEL_TP_OUT_0            0

/***************************************************************************
 *TEST_PORT_DATA - BVN Middle Test Port Status
 ***************************************************************************/
/* MMISC :: TEST_PORT_DATA :: TEST_PORT_DATA [31:00] */
#define BCHP_MMISC_TEST_PORT_DATA_TEST_PORT_DATA_MASK              0xffffffff
#define BCHP_MMISC_TEST_PORT_DATA_TEST_PORT_DATA_SHIFT             0
#define BCHP_MMISC_TEST_PORT_DATA_TEST_PORT_DATA_DEFAULT           0x00000000

/***************************************************************************
 *BVNM_CLOCK_CTRL - BVN Middle clock control register
 ***************************************************************************/
/* MMISC :: BVNM_CLOCK_CTRL :: reserved0 [31:01] */
#define BCHP_MMISC_BVNM_CLOCK_CTRL_reserved0_MASK                  0xfffffffe
#define BCHP_MMISC_BVNM_CLOCK_CTRL_reserved0_SHIFT                 1

/* MMISC :: BVNM_CLOCK_CTRL :: CLK_FREE_RUN_MODE [00:00] */
#define BCHP_MMISC_BVNM_CLOCK_CTRL_CLK_FREE_RUN_MODE_MASK          0x00000001
#define BCHP_MMISC_BVNM_CLOCK_CTRL_CLK_FREE_RUN_MODE_SHIFT         0
#define BCHP_MMISC_BVNM_CLOCK_CTRL_CLK_FREE_RUN_MODE_DEFAULT       0x00000000

/***************************************************************************
 *VNET_F_CHANNEL_SW_INIT - BVN Video Network Switch Frontend Channels Init
 ***************************************************************************/
/* MMISC :: VNET_F_CHANNEL_SW_INIT :: reserved0 [31:10] */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_reserved0_MASK           0xfffffc00
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_reserved0_SHIFT          10

/* MMISC :: VNET_F_CHANNEL_SW_INIT :: LOOP_1 [09:09] */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_LOOP_1_MASK              0x00000200
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_LOOP_1_SHIFT             9
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_LOOP_1_DEFAULT           0x00000000

/* MMISC :: VNET_F_CHANNEL_SW_INIT :: LOOP_0 [08:08] */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_LOOP_0_MASK              0x00000100
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_LOOP_0_SHIFT             8
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_LOOP_0_DEFAULT           0x00000000

/* MMISC :: VNET_F_CHANNEL_SW_INIT :: reserved1 [07:07] */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_reserved1_MASK           0x00000080
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_reserved1_SHIFT          7

/* MMISC :: VNET_F_CHANNEL_SW_INIT :: DVI_0 [06:06] */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_DVI_0_MASK               0x00000040
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_DVI_0_SHIFT              6
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_DVI_0_DEFAULT            0x00000000

/* MMISC :: VNET_F_CHANNEL_SW_INIT :: VFD_3 [05:05] */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_3_MASK               0x00000020
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_3_SHIFT              5
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_3_DEFAULT            0x00000000

/* MMISC :: VNET_F_CHANNEL_SW_INIT :: VFD_2 [04:04] */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_2_MASK               0x00000010
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_2_SHIFT              4
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_2_DEFAULT            0x00000000

/* MMISC :: VNET_F_CHANNEL_SW_INIT :: VFD_1 [03:03] */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_1_MASK               0x00000008
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_1_SHIFT              3
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_1_DEFAULT            0x00000000

/* MMISC :: VNET_F_CHANNEL_SW_INIT :: VFD_0 [02:02] */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_0_MASK               0x00000004
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_0_SHIFT              2
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_VFD_0_DEFAULT            0x00000000

/* MMISC :: VNET_F_CHANNEL_SW_INIT :: MFD_1 [01:01] */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_MFD_1_MASK               0x00000002
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_MFD_1_SHIFT              1
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_MFD_1_DEFAULT            0x00000000

/* MMISC :: VNET_F_CHANNEL_SW_INIT :: MFD_0 [00:00] */
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_MFD_0_MASK               0x00000001
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_MFD_0_SHIFT              0
#define BCHP_MMISC_VNET_F_CHANNEL_SW_INIT_MFD_0_DEFAULT            0x00000000

/***************************************************************************
 *VNET_B_CHANNEL_SW_INIT - BVN Video Network Switch Backend Channels Init
 ***************************************************************************/
/* MMISC :: VNET_B_CHANNEL_SW_INIT :: reserved0 [31:12] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_reserved0_MASK           0xfffff000
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_reserved0_SHIFT          12

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: DNR_0 [11:11] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_DNR_0_MASK               0x00000800
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_DNR_0_SHIFT              11
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_DNR_0_DEFAULT            0x00000000

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: FCH_5 [10:10] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_5_MASK               0x00000400
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_5_SHIFT              10
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_5_DEFAULT            0x00000000

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: FCH_4 [09:09] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_4_MASK               0x00000200
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_4_SHIFT              9
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_4_DEFAULT            0x00000000

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: FCH_3 [08:08] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_3_MASK               0x00000100
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_3_SHIFT              8
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_3_DEFAULT            0x00000000

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: FCH_2 [07:07] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_2_MASK               0x00000080
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_2_SHIFT              7
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_2_DEFAULT            0x00000000

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: FCH_1 [06:06] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_1_MASK               0x00000040
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_1_SHIFT              6
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_1_DEFAULT            0x00000000

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: FCH_0 [05:05] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_0_MASK               0x00000020
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_0_SHIFT              5
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_FCH_0_DEFAULT            0x00000000

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: MVP_0 [04:04] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_MVP_0_MASK               0x00000010
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_MVP_0_SHIFT              4
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_MVP_0_DEFAULT            0x00000000

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: SCL_3 [03:03] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_3_MASK               0x00000008
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_3_SHIFT              3
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_3_DEFAULT            0x00000000

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: SCL_2 [02:02] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_2_MASK               0x00000004
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_2_SHIFT              2
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_2_DEFAULT            0x00000000

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: SCL_1 [01:01] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_1_MASK               0x00000002
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_1_SHIFT              1
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_1_DEFAULT            0x00000000

/* MMISC :: VNET_B_CHANNEL_SW_INIT :: SCL_0 [00:00] */
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_0_MASK               0x00000001
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_0_SHIFT              0
#define BCHP_MMISC_VNET_B_CHANNEL_SW_INIT_SCL_0_DEFAULT            0x00000000

/***************************************************************************
 *SCRATCH_0 - Scratch Register
 ***************************************************************************/
/* MMISC :: SCRATCH_0 :: VALUE [31:00] */
#define BCHP_MMISC_SCRATCH_0_VALUE_MASK                            0xffffffff
#define BCHP_MMISC_SCRATCH_0_VALUE_SHIFT                           0
#define BCHP_MMISC_SCRATCH_0_VALUE_DEFAULT                         0x00000000

#endif /* #ifndef BCHP_MMISC_H__ */

/* End of File */
