
obj-$(CONFIG_MW_LOGCAPTURE) += mgr_logcapture.o
obj-$(CONFIG_MW_LOGCAPTURE) += mgr_logcapture_flushdata.o


# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr
# Additional include path

