############################################################
#     (c)2003-2008 Broadcom Corporation
#  
#  This program is the proprietary software of Broadcom Corporation and/or its licensors,
#  and may only be used, duplicated, modified or distributed pursuant to the terms and
#  conditions of a separate, written license agreement executed between you and Broadcom
#  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
#  no license (express or implied), right to use, or waiver of any kind with respect to the
#  Software, and Broadcom expressly reserves all rights in and to the Software and all
#  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
#  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
#  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.  
#   
#  Except as expressly set forth in the Authorized License,
#   
#  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
#  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
#  and to use this information only in connection with your use of Broadcom integrated circuit products.
#   
#  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS" 
#  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR 
#  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO 
#  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES 
#  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, 
#  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION 
#  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF 
#  USE OR PERFORMANCE OF THE SOFTWARE.
#  
#  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS 
#  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR 
#  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR 
#  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF 
#  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT 
#  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE 
#  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF 
#  ANY LIMITED REMEDY.
# 
# $brcm_Workfile: Makefile $
# $brcm_Revision: Hydra_Software_Devel/3 $
# $brcm_Date: 11/7/08 3:01p $
#
# Module Description:
#   This file defines the rules to build the PSIP library
#
# Revision History:
#
# Created: 03/26/2008 by Darren Tokushige
#
# $brcm_Log: /rockford/lib/psip/Makefile $
# 
# Hydra_Software_Devel/3   11/7/08 3:01p jrubio
# PR48782: fix linking for psip library
# 
# Hydra_Software_Devel/2   10/6/08 1:45p tokushig
# PR42421: fix memory deallocation on error conditions (check all
# pointers before freeing memory)
# 
# Hydra_Software_Devel/1   9/16/08 7:35p cttok
# PR46977: imported from nexus
# 
# 2   6/30/08 5:04p tokushig
# PR42421: add mpeg2_ts_parse directory as a clearcase symbolic link.
#  update psip makefiles to match.
# 
# 1   5/2/08 6:11p tokushig
# PR42421: add PSIP application library
# 
############################################################

ifdef COMSPEC
# Any DOS environment
B_LIB_TOP := $(shell cd ../../../nexus/lib && cd)
B_PSIP_TOP := $(shell cd ../../lib/psip &&  cd )
BSEAV := $(shell cd ../../../BSEAV && cd)
else
BSEAV := $(shell cd ../../../BSEAV; pwd)
B_LIB_TOP := $(shell cd ../../../nexus/lib; pwd)
B_PSIP_TOP := $(shell cd ../../lib/psip; pwd)
endif
B_MPEG2_TS_PARSE := $(BSEAV)/lib/mpeg2_ts_parse

# Include library definitions
include $(B_LIB_TOP)/build/b_lib_defs.inc

# Include module sources
# Note: You must also include any dependent libraries here also.
include b_psip_lib.inc
include $(B_LIB_TOP)/os/b_os_lib.inc

# Instruct build system to build only this library and name it libb_psip
B_BUILD_LIBS := B_PSIP_LIB
B_LIB_OUTPUT_NAME := b_psip

# Include library rules
include $(B_LIB_TOP)/build/b_lib_rules.inc

