obj-y := di_pump.o

ifeq ($(CONFIG_BRCM_MOD_MSDRM_PRDY_25_SUPPORT),y)
HUMAX_EXTRA_CFLAG += -I$(HUMAX_WORK_DIR)/platform/sdk/driver/magnum/syslib/sagelib/include
HUMAX_EXTRA_CFLAG += -I$(HUMAX_WORK_DIR)/platform/sdk/driver/BSEAV/lib/security/sage/srai/include
endif
