-include ./dirs

ifeq ($(DIRS),)
TARGET = wmdrmreal

SOURCES =                \
	drmdevcertstub.c drmwmdrmexprevalstub.c drmwmdrmexprfuncstub.c drmwmdrmexprvariablestub.c drmwmdrmlicacqrespstub.c drmwmdrmlicchainstub.c drmwmdrmlicenseparserstub.c drmwmdrmlicevalstub.c drmwmdrmoplstub.c drmwmdrmutilstub.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
