obj-y += va_main.o
obj-y += va_util.o
obj-y += va_prot_api.o
#obj-y += va_test.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
