obj-$(CONFIG_APUI_SET_MEDIA_UI_DISPLAY) += nx_prism_media.o
obj-$(CONFIG_APUI_SET_MEDIA_UI_DISPLAY) += nx_prism_media_type_select.o

# Additional include path
ccflags-y += -I../../../../../../../make/include

