#!/bin/sh

MODULES_FILE=/etc/default/modules
. /lib/lsb/init-functions
. /etc/default/rcS
if [ "$VERBOSE" != no ]; then
	log_begin_msg 'Loading modules...'
fi

convert_params() {
    if [ "$1" = mac2addr ]; then
	for cmd in $(cat /proc/cmdline)
	do
	    case "$cmd" in
	    *$1*) 
		args=$cmd
		return 0 ;;
            esac
	done
	args=
    fi
}

grep '^[^#]' $MODULES_FILE | \
while read module args; do
    [ "$module" ] || continue
    convert_params $args
    if [ "$VERBOSE" != no ]; then
		log_begin_msg "Trying module $module"
		if modprobe $module $args >/dev/null 2>&1; then
		    log_end_msg 0
		else
		    log_end_msg 1 || true
		fi
    else
	modprobe $module $args >/dev/null 2>&1 || true
    fi
done

convert_params mac2addr
ifconfig bcm0 down
ifconfig bcm0 hw ether $mac2addr
