obj-y += pl_streaming_init.o
obj-y += pl_streaming.o
obj-y += pl_streaming_callback.o
obj-y += pl_streaming_resource.o
obj-y += pl_streaming_receive.o
obj-y += pl_streaming_context.o
obj-y += pl_streaming_debug.o
obj-y += pl_streaming_uds.o

obj-y += util/
obj-y += mode/

export HOMMA_STREAMING_PATH
HOMMA_STREAMING_PATH = $(OCTOSVC_SRC_DIR)/homma/main/module/common/streaming
#extern HOMMA_STREAMING_PATH = $(PWD)

# Basic include path
include $(HOMMA_STREAMING_PATH)/Makefile.include.streaming
# Additional include path


