-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = synclistgeneratechallenge

DRM_MODULE_CFLAGS =

SOURCES =                \
	synclistgeneratechallenge.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
