# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =      \
    lib        \
    bcm			\
    test       \
    trace      \

include $(PLAYREADY_DIR)/GNUmakefile.common

