obj-y += api68k.o
obj-y += apiask.o
obj-y += apiroman.o
obj-y += askdic.o
obj-y += autab.o
obj-y += connect.o
obj-y += dic_main.o
obj-y += dic_page.o
obj-y += dic_temp.o
obj-y += fword.o
obj-y += henkan.o	
obj-y += kouho.o
obj-y += mean.o
obj-y += memory.o
obj-y += prefer.o
obj-y += rmtype.o
obj-y += roman.o
obj-y += rometab.o
obj-y += select.o
obj-y += imeapi.o

# Basic include path
# Additional include path
