obj-y += mempool.o
obj-y += timeconv.o
obj-y += ttx_decoder.o
obj-y += ttx_errchk.o
obj-y += ttx_top.o
obj-y += ttx_drcs.o
obj-y += ttx_charmap.o
obj-y += ttx_graphics.o
obj-y += teletext.o
obj-y += ap_teletext.o
obj-y += ap_teletextui.o

ccflags-y += -I../../../../../make/include -I../../../make/include
