obj-y += nx_prism_util.o
obj-$(CONFIG_APUI_SKIN_COLOR_BASE) += nx_prism_skin_alpha.o
obj-$(CONFIG_APUI_SKIN_COLOR_MBC) += nx_prism_skin_mbc.o
obj-$(CONFIG_PROD_LANG_ARABIC) += nx_prism_arabic_support.o
obj-y += nx_prism_resource.o
obj-y += nx_prism_spec.o

# Additional include path
ccflags-y += -I../../../../../../make/include

