obj-y += nx_prism_schedule.o
obj-y += nx_prism_schedule_add.o
obj-y += nx_prism_schedule_option.o
obj-y += nx_prism_schedule_repeatdialog.o

# Additional include path
ccflags-y += -I../../../../../../../make/include
