# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

ifneq "" "$(LINUX_BUILD)"

TARGETS =     \
    common    \

else
# Mac

TARGETS =     \
    common    \
    drmviewer \

endif

include $(PLAYREADY_DIR)/GNUmakefile.common

