obj-y += satsa_sci.o
obj-y += satsa_sci_adapt.o
obj-y += satsa_sci_protocol_t1.o
obj-y += satsa_ui_adapt.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
ccflags-y += -I$(THIRDPARTY_DIR)/mhp/alticaptor/include
