obj-$(CONFIG_PROD_BASE7356)			+= xsvc_cas_init_base7356.o
obj-$(CONFIG_PROD_HDR1000S)			+= xsvc_cas_init_hdr1000s.o
obj-$(CONFIG_PROD_HMS1000S)			+= xsvc_cas_init_hms1000s.o
obj-$(CONFIG_PROD_HMSLITE)			+= xsvc_cas_init_hms1000s.o
obj-$(CONFIG_PROD_ICORDPRO)			+= xsvc_cas_init_icordpro.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

