/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_aud_fmm_iop_ctrl.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 4/13/11 3:52p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Apr 13 13:12:49 2011
 *                 MD5 Checksum         5014fc6b805cdf8eed48fe0da9f96997
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7231/rdb/b0/bchp_aud_fmm_iop_ctrl.h $
 * 
 * Hydra_Software_Devel/1   4/13/11 3:52p albertl
 * SW7231-123: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_AUD_FMM_IOP_CTRL_H__
#define BCHP_AUD_FMM_IOP_CTRL_H__

/***************************************************************************
 *AUD_FMM_IOP_CTRL - IOP Control
 ***************************************************************************/
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0         0x008b80c0 /* Serial Input Configuration */

/***************************************************************************
 *CAP_CFG%i - Capture configuration
 ***************************************************************************/
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_ARRAY_BASE                  0x008b8000
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_ARRAY_START                 0
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_ARRAY_END                   4
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_ARRAY_ELEMENT_SIZE          32

/***************************************************************************
 *CAP_CFG%i - Capture configuration
 ***************************************************************************/
/* AUD_FMM_IOP_CTRL :: CAP_CFGi :: reserved0 [31:11] */
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_reserved0_MASK              0xfffff800
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_reserved0_SHIFT             11

/* AUD_FMM_IOP_CTRL :: CAP_CFGi :: GROUP [10:08] */
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_GROUP_MASK                  0x00000700
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_GROUP_SHIFT                 8
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_GROUP_DEFAULT               0

/* AUD_FMM_IOP_CTRL :: CAP_CFGi :: reserved1 [07:02] */
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_reserved1_MASK              0x000000fc
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_reserved1_SHIFT             2

/* AUD_FMM_IOP_CTRL :: CAP_CFGi :: IGNORE_FIRST_OVERFLOW [01:01] */
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_IGNORE_FIRST_OVERFLOW_MASK  0x00000002
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_IGNORE_FIRST_OVERFLOW_SHIFT 1
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_IGNORE_FIRST_OVERFLOW_DEFAULT 1
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_IGNORE_FIRST_OVERFLOW_Ignore 1
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_IGNORE_FIRST_OVERFLOW_Dont_ignore 0

/* AUD_FMM_IOP_CTRL :: CAP_CFGi :: ENA [00:00] */
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_ENA_MASK                    0x00000001
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_ENA_SHIFT                   0
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_ENA_DEFAULT                 0
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_ENA_Enable                  1
#define BCHP_AUD_FMM_IOP_CTRL_CAP_CFGi_ENA_Disable                 0


/***************************************************************************
 *LOOPBACK_CFG%i - Loopback configuration
 ***************************************************************************/
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_ARRAY_BASE             0x008b8040
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_ARRAY_START            0
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_ARRAY_END              3
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_ARRAY_ELEMENT_SIZE     32

/***************************************************************************
 *LOOPBACK_CFG%i - Loopback configuration
 ***************************************************************************/
/* AUD_FMM_IOP_CTRL :: LOOPBACK_CFGi :: reserved0 [31:06] */
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_reserved0_MASK         0xffffffc0
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_reserved0_SHIFT        6

/* AUD_FMM_IOP_CTRL :: LOOPBACK_CFGi :: INS_NOACK [05:05] */
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_INS_NOACK_MASK         0x00000020
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_INS_NOACK_SHIFT        5
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_INS_NOACK_DEFAULT      0
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_INS_NOACK_Enable       1
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_INS_NOACK_Disable      0

/* AUD_FMM_IOP_CTRL :: LOOPBACK_CFGi :: IGNORE_FIRST_UNDERFLOW [04:04] */
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_IGNORE_FIRST_UNDERFLOW_MASK 0x00000010
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_IGNORE_FIRST_UNDERFLOW_SHIFT 4
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_IGNORE_FIRST_UNDERFLOW_DEFAULT 1
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_IGNORE_FIRST_UNDERFLOW_Ignore 1
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_IGNORE_FIRST_UNDERFLOW_Dont_ignore 0

/* AUD_FMM_IOP_CTRL :: LOOPBACK_CFGi :: INSERT_CTL [03:02] */
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_INSERT_CTL_MASK        0x0000000c
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_INSERT_CTL_SHIFT       2
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_INSERT_CTL_DEFAULT     0
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_INSERT_CTL_Repeat      3
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_INSERT_CTL_Insert_zero 2
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_INSERT_CTL_No_insert   0

/* AUD_FMM_IOP_CTRL :: LOOPBACK_CFGi :: TMG_SRC_SEL [01:00] */
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_TMG_SRC_SEL_MASK       0x00000003
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_TMG_SRC_SEL_SHIFT      0
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_TMG_SRC_SEL_DEFAULT    0
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_TMG_SRC_SEL_Fs0        0
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_TMG_SRC_SEL_Fs1        1
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_TMG_SRC_SEL_Fs2        2
#define BCHP_AUD_FMM_IOP_CTRL_LOOPBACK_CFGi_TMG_SRC_SEL_Fs3        3


/***************************************************************************
 *DUMMYSINK_CFG%i - Dummy sink configuration
 ***************************************************************************/
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_ARRAY_BASE            0x008b8080
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_ARRAY_START           0
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_ARRAY_END             3
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_ARRAY_ELEMENT_SIZE    32

/***************************************************************************
 *DUMMYSINK_CFG%i - Dummy sink configuration
 ***************************************************************************/
/* AUD_FMM_IOP_CTRL :: DUMMYSINK_CFGi :: reserved0 [31:10] */
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_reserved0_MASK        0xfffffc00
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_reserved0_SHIFT       10

/* AUD_FMM_IOP_CTRL :: DUMMYSINK_CFGi :: GROUP [09:08] */
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_GROUP_MASK            0x00000300
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_GROUP_SHIFT           8
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_GROUP_DEFAULT         0

/* AUD_FMM_IOP_CTRL :: DUMMYSINK_CFGi :: reserved1 [07:06] */
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_reserved1_MASK        0x000000c0
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_reserved1_SHIFT       6

/* AUD_FMM_IOP_CTRL :: DUMMYSINK_CFGi :: TMG_SRC_SEL [05:04] */
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_TMG_SRC_SEL_MASK      0x00000030
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_TMG_SRC_SEL_SHIFT     4
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_TMG_SRC_SEL_DEFAULT   0
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_TMG_SRC_SEL_Fs0       0
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_TMG_SRC_SEL_Fs1       1
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_TMG_SRC_SEL_Fs2       2
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_TMG_SRC_SEL_Fs3       3

/* AUD_FMM_IOP_CTRL :: DUMMYSINK_CFGi :: reserved2 [03:01] */
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_reserved2_MASK        0x0000000e
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_reserved2_SHIFT       1

/* AUD_FMM_IOP_CTRL :: DUMMYSINK_CFGi :: ENA [00:00] */
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_ENA_MASK              0x00000001
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_ENA_SHIFT             0
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_ENA_DEFAULT           0
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_ENA_Enable            1
#define BCHP_AUD_FMM_IOP_CTRL_DUMMYSINK_CFGi_ENA_Disable           0


/***************************************************************************
 *I2SIN_CFG0 - Serial Input Configuration
 ***************************************************************************/
/* AUD_FMM_IOP_CTRL :: I2SIN_CFG0 :: reserved0 [31:12] */
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_reserved0_MASK            0xfffff000
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_reserved0_SHIFT           12

/* AUD_FMM_IOP_CTRL :: I2SIN_CFG0 :: DATA_JUSTIFICATION [11:11] */
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_DATA_JUSTIFICATION_MASK   0x00000800
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_DATA_JUSTIFICATION_SHIFT  11
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_DATA_JUSTIFICATION_DEFAULT 0
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_DATA_JUSTIFICATION_LSB    1
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_DATA_JUSTIFICATION_MSB    0

/* AUD_FMM_IOP_CTRL :: I2SIN_CFG0 :: DATA_ALIGNMENT [10:10] */
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_DATA_ALIGNMENT_MASK       0x00000400
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_DATA_ALIGNMENT_SHIFT      10
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_DATA_ALIGNMENT_DEFAULT    1
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_DATA_ALIGNMENT_Delayed    1
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_DATA_ALIGNMENT_Aligned    0

/* AUD_FMM_IOP_CTRL :: I2SIN_CFG0 :: SCLK_POLARITY [09:09] */
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_SCLK_POLARITY_MASK        0x00000200
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_SCLK_POLARITY_SHIFT       9
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_SCLK_POLARITY_DEFAULT     0
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_SCLK_POLARITY_Rising_aligned_with_sdata 1
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_SCLK_POLARITY_Falling_aligned_with_sdata 0

/* AUD_FMM_IOP_CTRL :: I2SIN_CFG0 :: LRCK_POLARITY [08:08] */
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_LRCK_POLARITY_MASK        0x00000100
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_LRCK_POLARITY_SHIFT       8
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_LRCK_POLARITY_DEFAULT     0
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_LRCK_POLARITY_High_for_left 1
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_LRCK_POLARITY_Low_for_left 0

/* AUD_FMM_IOP_CTRL :: I2SIN_CFG0 :: reserved1 [07:05] */
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_reserved1_MASK            0x000000e0
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_reserved1_SHIFT           5

/* AUD_FMM_IOP_CTRL :: I2SIN_CFG0 :: BITS_PER_SAMPLE [04:00] */
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_BITS_PER_SAMPLE_MASK      0x0000001f
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_BITS_PER_SAMPLE_SHIFT     0
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_BITS_PER_SAMPLE_DEFAULT   0
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_BITS_PER_SAMPLE_Bitwidth32 0
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_BITS_PER_SAMPLE_Bitwidth24 24
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_BITS_PER_SAMPLE_Bitwidth20 20
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_BITS_PER_SAMPLE_Bitwidth18 18
#define BCHP_AUD_FMM_IOP_CTRL_I2SIN_CFG0_BITS_PER_SAMPLE_Bitwidth16 16

/***************************************************************************
 *FCI_CFG%i - FCI configuration
 ***************************************************************************/
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_ARRAY_BASE                  0x008b8100
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_ARRAY_START                 0
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_ARRAY_END                   17
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_ARRAY_ELEMENT_SIZE          32

/***************************************************************************
 *FCI_CFG%i - FCI configuration
 ***************************************************************************/
/* AUD_FMM_IOP_CTRL :: FCI_CFGi :: reserved0 [31:20] */
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_reserved0_MASK              0xfff00000
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_reserved0_SHIFT             20

/* AUD_FMM_IOP_CTRL :: FCI_CFGi :: STREAM_BIT_RESOLUTION [19:16] */
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_MASK  0x000f0000
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_SHIFT 16
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_DEFAULT 8
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_Res_16_Bit 0
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_Res_17_Bit 1
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_Res_18_Bit 2
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_Res_19_Bit 3
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_Res_20_Bit 4
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_Res_21_Bit 5
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_Res_22_Bit 6
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_Res_23_Bit 7
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_STREAM_BIT_RESOLUTION_Res_24_Bit 8

/* AUD_FMM_IOP_CTRL :: FCI_CFGi :: reserved1 [15:14] */
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_reserved1_MASK              0x0000c000
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_reserved1_SHIFT             14

/* AUD_FMM_IOP_CTRL :: FCI_CFGi :: INIT_SM [13:13] */
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_INIT_SM_MASK                0x00002000
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_INIT_SM_SHIFT               13
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_INIT_SM_DEFAULT             0
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_INIT_SM_Init                1
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_INIT_SM_Normal              0

/* AUD_FMM_IOP_CTRL :: FCI_CFGi :: INS_INVAL [12:12] */
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_INS_INVAL_MASK              0x00001000
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_INS_INVAL_SHIFT             12
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_INS_INVAL_DEFAULT           0
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_INS_INVAL_Invalid           1
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_INS_INVAL_Valid             0

/* AUD_FMM_IOP_CTRL :: FCI_CFGi :: reserved2 [11:10] */
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_reserved2_MASK              0x00000c00
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_reserved2_SHIFT             10

/* AUD_FMM_IOP_CTRL :: FCI_CFGi :: ID [09:00] */
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_ID_MASK                     0x000003ff
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_ID_SHIFT                    0
#define BCHP_AUD_FMM_IOP_CTRL_FCI_CFGi_ID_DEFAULT                  0


#endif /* #ifndef BCHP_AUD_FMM_IOP_CTRL_H__ */

/* End of File */
