/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_xpt_secure_bus_if.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 6/22/11 4:58p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Jun 22 16:11:55 2011
 *                 MD5 Checksum         f1fe9dd101680af6476d6b0b4e1d855e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7231/rdb/b0/bchp_xpt_secure_bus_if.h $
 * 
 * Hydra_Software_Devel/1   6/22/11 4:58p pntruong
 * SW7231-196: Synced with central rdb.
 *
 ***************************************************************************/

#ifndef BCHP_XPT_SECURE_BUS_IF_H__
#define BCHP_XPT_SECURE_BUS_IF_H__

/***************************************************************************
 *XPT_SECURE_BUS_IF - XPT Security  Control Registers
 ***************************************************************************/
#define BCHP_XPT_SECURE_BUS_IF_DUMMY             0x00a3f000 /* Dummy Register */

/***************************************************************************
 *DUMMY - Dummy Register
 ***************************************************************************/
/* XPT_SECURE_BUS_IF :: DUMMY :: reserved0 [31:00] */
#define BCHP_XPT_SECURE_BUS_IF_DUMMY_reserved0_MASK                0xffffffff
#define BCHP_XPT_SECURE_BUS_IF_DUMMY_reserved0_SHIFT               0

#endif /* #ifndef BCHP_XPT_SECURE_BUS_IF_H__ */

/* End of File */
