

#ifndef	__DB_PARAM_H__
#define	__DB_PARAM_H__

/*******************************************************************/
/********************      Header Files    *************************/
/*******************************************************************/
#include <octo_common.h>

/*******************************************************************/
/********************      Macro Definition     ********************/
/*******************************************************************/
#define DbParam_UNDEFINED			"undefined"

/*******************************************************************/
/********************      Typedef         *************************/
/*******************************************************************/
typedef enum
{
	eDB_PARAM_TYPE_Int		= 0,
	eDB_PARAM_TYPE_String,
	eDB_PARAM_TYPE_Enum,
	eDB_PARAM_TYPE_Bin,
	eDB_PARAM_TYPE_Max
} DbParam_Type_e;

/** @brief DB PARAM Item Enum */
/*	ITEM NAME, which includes Operator's Name or Specification Name is Not Allowed.
 *  Will Be Removed without Notification!!!!!
 *  e.g) eDB_PARAM_ITEM_KDG_XXX
 *  e.g) eDB_PARAM_ITEM_ZIGGO_XXX
 *  e.g) eDB_PARAM_ITEM_DTG_XXX
 *  e.g) eDB_PARAM_ITEM_NORDIG_XXX
 */
typedef enum
{
	eDB_PARAM_ITEM_UNKNOWN = 0,

	eDB_PARAM_ITEM_OPERATOR_TYPE,						/**< DxOperator_e		*/
	eDB_PARAM_ITEM_LANG_MAIN,							/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_EVENT,							/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_EVENT1,							/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_AUDIO0, 						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_AUDIO1,							/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_AUDIO2, 						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_AUDIO3, 						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_AUDIO4, 						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_AUDIO5, 						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_AUDIO6, 						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_AUDIO7, 						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_SUBTITLE0,						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_SUBTITLE1,						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_SUBTITLE2,						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_SUBTITLE3,						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_SUBTITLE4,						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_SUBTITLE5,						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_SUBTITLE6,						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_LANG_SUBTITLE7,						/**< HxLANG_Id_e		*/
	eDB_PARAM_ITEM_HARDOFHEARING,						/**< HBOOL				*/
	eDB_PARAM_ITEM_MATURITYRATING,						/**< DxRatingAge_e		*/
	eDB_PARAM_ITEM_SKIPFORWARDSEC,						/**< HUINT32		ulSkipForwardSec	*/
	eDB_PARAM_ITEM_INSTANTREPLAYSEC,					/**< HUINT32		ulInstantReplaySec	*/
	eDB_PARAM_ITEM_COUNTRY_ID, 							/**< HxCountry_e	eCountryId 		*/
	eDB_PARAM_ITEM_AUDIO_DESCRIPTION,					/**< HBOOL			bAudioDescription	*/
	eDB_PARAM_ITEM_PINCODE,								/**< HCHAR  		*pszPinCode			*/
	eDB_PARAM_ITEM_PADDINGTIME_START,					/**< HUINT32 ulPaddingTimeStart		*/
	eDB_PARAM_ITEM_PADDINGTIME_STOP,					/**< HUINT32 ulPaddingTimeStop		*/
	eDB_PARAM_ITEM_TSR_ONOFF,							/**< HBOOL bOn		*/
	eDB_PARAM_ITEM_AUTO_DELETE,							/**< HBOOL bOn		*/
	eDB_PARAM_ITEM_STEREO_SELECT,						/**< DxStereoSelect_e eStereoSelect		*/
	eDB_PARAM_ITEM_DUALMONO_SELECT,						/**< DxDualMonoSelect_e eDualMonoSelect		*/
	eDB_PARAM_ITEM_HDMI_AUDIO_FORMAT,					/**< DxDigitalAudioFormat_e eDigitalAudioFormat		*/
	eDB_PARAM_ITEM_SPDIF_AUDIO_FORMAT,					/**< DxDigitalAudioFormat_e eDigitalAudioFormat		*/
	eDB_PARAM_ITEM_LIPSYNC_DELAY,						/**< HUINT32 ulDelay_msec		*/
	eDB_PARAM_ITEM_LAST_VOLUME,							/**< HUINT32 ulVolume		*/
	eDB_PARAM_ITEM_INVISIBLE_SEARCH,					/**< HBOOL bInvisibleSearch		*/
	eDB_PARAM_ITEM_POSTCODE,							/**< 		*/
	eDB_PARAM_ITEM_ANT_CONN_TYPE,						/**< DxAntennaConnection_e eAntConn	*/
	eDB_PARAM_ITEM_GUIDANCE_POLICY,						/**< DxGuidancePolicy_e	eGPolicy */
	eDB_PARAM_ITEM_CHANNEL_SETUP_PIN,					/**< HBOOL bSettup */
	eDB_PARAM_ITEM_ADULTCHANNELS,						/**< DxAdultChannelType_e eAdultChannel */
	eDB_PARAM_ITEM_SUBTITLE_SETTING,					/**< HBOOL	bSubtitle	*/
	eDB_PARAM_ITEM_HDMI_CEC_ENABLE,						/**< HBOOL	bCecEnable */
	eDB_PARAM_ITEM_DAYLIGHT_SAVING,						/**< HBOOL 	bEnable */
	eDB_PARAM_ITEM_VIRTUAL_SECURECW_SETTING,			/**< HBOOL 	bOn	*/
	eDB_PARAM_ITEM_UPDATE_TIME_ON_SPECIFIC_TP,			/**< HBOOL 	bEnable */
	eDB_PARAM_ITEM_2ND_INT_HDD_UUID,					/**< HCHAR			*pszUuid */
	eDB_PARAM_ITEM_TVSCART_FORMAT,						/**< DxScartFormat_e eScartFormat 	*/
	eDB_PARAM_ITEM_VCRSCART_FORMAT,						/**< DxScartFormat_e eScartFormat 	*/
	eDB_PARAM_ITEM_SCART_PATH,							/**< DxScartPath_e eScartPath 	*/
	eDB_PARAM_ITEM_TV_ASPECTRATIO,						/**< DxAspectRatio_e eTvAspectRatio 	*/
	eDB_PARAM_ITEM_DFC_SELECT,							/**< DxDfcSelect_e eDfcSelect	*/
	eDB_PARAM_ITEM_RESOLUTION_SELECT,					/**< DxResolutionSelect_e eResolutionSelect	*/
	eDB_PARAM_ITEM_BACKGROUND_COLOR_R,					/**< HUINT8	ucR	*/
	eDB_PARAM_ITEM_BACKGROUND_COLOR_G,					/**< HUINT8	ucG	*/
	eDB_PARAM_ITEM_BACKGROUND_COLOR_B,					/**< HUINT8 ucB */
	eDB_PARAM_ITEM_3D_SELECT,							/**< DxHdmi3DSelect_e e3DSelect */

	eDB_PARAM_ITEM_SWUPDATE_VERSION,

	eDB_PARAM_ITEM_GMT_OFFSET_MINUTES,					/**	HUINT32 nGmtOffset  */ 	//	eDxSETUP_SYSTEM_GMT_OFFSET_MINUTES
	eDB_PARAM_ITEM_TIME_REGION_ID,						/**	HUINT32 nItemValue	*/	//	eDxSETUP_SYSTEM_TIME_REGION_ID

	eDB_PARAM_ITEM_ANTSET_ANTENNATYPE,					/**< DbSvc_UiAntType_e */ //	eDxSETUP_SYSTEM_ANTSET_ANTENNATYPE
	eDB_PARAM_ITEM_ANTSET_SAT_TUNER01,					/**< (HINT32)ulAntIdx  */ //	eDxSETUP_SYSTEM_ANTSET_SAT_TUNER01
	eDB_PARAM_ITEM_ANTSET_SAT_TUNER02,					/**< (HINT32)ulAntIdx  */ //	eDxSETUP_SYSTEM_ANTSET_SAT_TUNER02
	eDB_PARAM_ITEM_ANTSET_SAT_TUNER03,					/**< (HINT32)ulAntIdx  */ //	eDxSETUP_SYSTEM_ANTSET_SAT_TUNER03
	eDB_PARAM_ITEM_SRCH_TPSELECTION,					/**< Binary    */ 			//	eDxSETUP_SYSTEM_SRCH_TPSELECTION

	eDB_PARAM_ITEM_MOTORSET_LNBFREQ, 					/**< (HUINT32)ulLnbFreq	 */ //	eDxSETUP_SYSTEM_MOTORSET_LNBFREQ
	eDB_PARAM_ITEM_MOTORSET_LNBPOWER,					/**< (HBOOL)bLnbPower	 */ //	eDxSETUP_SYSTEM_MOTORSET_LNBPOWER
	eDB_PARAM_ITEM_MOTORSET_MOTORTYPE,					/**< DxSAT_DiseqcVer_e */	//	eDxSETUP_SYSTEM_MOTORSET_MOTORTYPE
	eDB_PARAM_ITEM_POSITIONSET_SATTYPE,					/**< SVC_SatType_t */		//	eDxSETUP_SYSTEM_POSITIONSET_SATTYPE
	eDB_PARAM_ITEM_POSITIONSET_MOTORDRIVE,				/**< CH_MotorDriveMode_t */	//	eDxSETUP_SYSTEM_POSITIONSET_MOTORDRIVE
	eDB_PARAM_ITEM_POSITIONSET_DRIVESIZE,				/**< HUINT32 ulDriveSize */	//	eDxSETUP_SYSTEM_POSITIONSET_DRIVESIZE

	eDB_PARAM_ITEM_LIMITSET_MOTORLIMIT,					/**< HBOOL bLimitOnOff */	//	eDxSETUP_SYSTEM_LIMITSET_MOTORLIMIT
	eDB_PARAM_ITEM_LIMITSET_LIMITPOS,					/**< HBOOL bLimitOnOff */	//	eDxSETUP_SYSTEM_LIMITSET_LIMITPOS
	eDB_PARAM_ITEM_SAT_TUNER_SELECTION,					/**< HUINT32 ulTunerId */	//	eDxSETUP_SYSTEM_SAT_TUNER_SELECTION
	eDB_PARAM_ITEM_SAT_SRCH_ALL_ANT,					/**< HBOOL bSrchAllAnt */	//	eDxSETUP_SYSTEM_SAT_SRCH_ALL_ANT
	eDB_PARAM_ITEM_SAT_TRANSPONDER,						/**< HUINT32 ulTpIndex */	//  eDxSETUP_SYSTEM_SAT_TRANSPONDER
	eDB_PARAM_ITEM_SAT_NETWORK_SRCH,					/**< HUINT32 ulNetwork */	//	eDxSETUP_SYSTEM_SAT_NETWORK_SRCH

	eDB_PARAM_ITEM_SAT_CAFREE_TYPE,						/**< HUINT32 ulCasType */	//	eDxSETUP_SYSTEM_SAT_CAFREE_TYPE
	eDB_PARAM_ITEM_SAT_CHANNEL_TYPE,					/**< HUINT32 ulChType */	//	eDxSETUP_SYSTEM_SAT_CHANNEL_TYPE
	eDB_PARAM_ITEM_SAT_SEARCH_MODE,						/**< HUINT32 ulSearchMode *///	eDxSETUP_SYSTEM_SAT_SEARCH_MODE
	eDB_PARAM_ITEM_TER_SRCH_CHANNEL,					/**< HUINT8	ucChanNum */	//	eDxSETUP_SYSTEM_TER_SRCH_CHANNEL
	eDB_PARAM_ITEM_TER_SRCH_FREQUENCY,					/**< HUINT32 ulFreq	*/		//	eDxSETUP_SYSTEM_TER_SRCH_FREQUENCY
	eDB_PARAM_ITEM_TER_SRCH_BANDWIDTH,					/**< DxTer_BandWidth_e	*/	//	eDxSETUP_SYSTEM_TER_SRCH_BANDWIDTH
	eDB_PARAM_ITEM_TER_SRCH_NETSEARCH,					/**< HUINT32 ulNetwork	*/	//	eDxSETUP_SYSTEM_TER_SRCH_NETSEARCH
	eDB_PARAM_ITEM_TER_SRCH_NETWORKID,					/**< HUINT32 ulNetId */		//	eDxSETUP_SYSTEM_TER_SRCH_NETWORKID
	eDB_PARAM_ITEM_TER_SRCH_POWER,						/**< (HUINT8)nVal */		//	eDxSETUP_SYSTEM_TER_SRCH_POWER
	eDB_PARAM_ITEM_TER_SRCH_TRANSMISSION,				/**< DxTer_System_e */		//	eDxSETUP_SYSTEM_TER_SRCH_TRANSMISSION
	eDB_PARAM_ITEM_CAB_SRCH_TUNERID,					/**< HUINT32 ulTunerId */	//	eDxSETUP_SYSTEM_CAB_SRCH_TUNERID
	eDB_PARAM_ITEM_CAB_SRCH_NETSEARCH,					/**< HUINT32 ulNetwork */	//	eDxSETUP_SYSTEM_CAB_SRCH_NETSEARCH
	eDB_PARAM_ITEM_CAB_SRCH_CAFREE_TYPE,				/**< HUINT32 ulCasType */	//	eDxSETUP_SYSTEM_CAB_SRCH_CAFREE_TYPE
	eDB_PARAM_ITEM_CAB_SRCH_CHANNEL_TYPE,				/**< HUINT32 ulChType */	//	eDxSETUP_SYSTEM_CAB_SRCH_CHANNEL_TYPE
	eDB_PARAM_ITEM_CAB_SRCH_FREQUENCY,					/**< HUINT32 ulFreq */		//	eDxSETUP_SYSTEM_CAB_SRCH_FREQUENCY
	eDB_PARAM_ITEM_CAB_SRCH_SYMBOL_RATE,				/**< HUINT32 ulSR */		//	eDxSETUP_SYSTEM_CAB_SRCH_SYMBOL_RATE
	eDB_PARAM_ITEM_CAB_SRCH_MODULATION,					/**< HUINT32 ulCon */		//	eDxSETUP_SYSTEM_CAB_SRCH_MODULATION
	eDB_PARAM_ITEM_CAB_SRCH_NETWORK_ID,					/**< HUINT32 ulNetworkId */	//	eDxSETUP_SYSTEM_CAB_SRCH_NETWORK_ID
	eDB_PARAM_ITEM_CAB_LINEAR_SRCH_STARTFREQUENCY,		/**< HUINT32 ulFreq */		//	eDxSETUP_SYSTEM_CAB_LINEAR_SRCH_STARTFREQUENCY
	eDB_PARAM_ITEM_CAB_LINEAR_SRCH_STOPFREQUENCY,		/**< HUINT32 pulFreq */		//	eDxSETUP_SYSTEM_CAB_LINEAR_SRCH_STOPFREQUENCY
	eDB_PARAM_ITEM_CAB_LINEAR_SRCH_STEP,				/**< HUINT32 ulStep */		//	eDxSETUP_SYSTEM_CAB_LINEAR_SRCH_STEP
	eDB_PARAM_ITEM_CAB_LINEAR_SRCH_MODULATION,			/**< HUINT32 ulCon */		//	eDxSETUP_SYSTEM_CAB_LINEAR_SRCH_MODULATION
	eDB_PARAM_ITEM_CAB_LINEAR_SRCH_SYMBOL_RATE,			/**< HUINT32 ulSR */		//	eDxSETUP_SYSTEM_CAB_LINEAR_SRCH_SYMBOL_RATE
	eDB_PARAM_ITEM_CAB_SRCH_NETWORK_SRCH_MODE,			/**< HUINT32 ulSearchMode *///	eDxSETUP_SYSTEM_CAB_SRCH_NETWORK_SRCH_MODE

	eDB_PARAM_ITEM_MAN_TP_FREQUENCY,					/**< HUINT32 ulFrequency */	//	eDxSETUP_SYSTEM_MAN_TP_FREQUENCY
	eDB_PARAM_ITEM_MAN_TP_SYMBOLRATE,					/**< HUINT32 ulSymbolRate  *///	eDxSETUP_SYSTEM_MAN_TP_SYMBOLRATE
	eDB_PARAM_ITEM_MAN_TP_POLARIZATION,					/**< DxSat_Polarization_e *///	eDxSETUP_SYSTEM_MAN_TP_POLARIZATION
	eDB_PARAM_ITEM_MAN_TP_FEC,							/**< DxSat_CodeRate_e */	//	eDxSETUP_SYSTEM_MAN_TP_FEC
	eDB_PARAM_ITEM_MAN_TP_TRANSSPEC,					/**< DxSat_TransportSpec_e *///	eDxSETUP_SYSTEM_MAN_TP_TRANSSPEC
	eDB_PARAM_ITEM_MAN_TP_MODULATION,					/**< DxSat_PskModulation_e *///	eDxSETUP_SYSTEM_MAN_TP_MODULATION
	eDB_PARAM_ITEM_MAN_TP_PILOT,						/**< DxSat_Pilot_e */		//	eDxSETUP_SYSTEM_MAN_TP_PILOT
	eDB_PARAM_ITEM_MOTOR_USER_LONGITUDE,				/**< HINT32 nLongitude */	//	eDxSETUP_SYSTEM_MOTOR_USER_LONGITUDE

	eDB_PARAM_ITEM_TVTV_ENABLE,							/**< HBOOL bTvtvEnable */	//	eDxSETUP_SYSTEM_TVTV_ENABLE
	eDB_PARAM_ITEM_TVTV_DOWNTYPE,						/**< HBOOL bUpdateTime */	//	eDxSETUP_SYSTEM_TVTV_DOWNTYPE
	eDB_PARAM_ITEM_MY_LONGITUDE,						/**< HINT32 nLongitude */	//	eDxSETUP_USER_MY_LONGITUDE
	eDB_PARAM_ITEM_MY_LATITUDE,							/**< HINT32 nLatitude */	//	eDxSETUP_USER_MY_LATITUDE
	eDB_PARAM_ITEM_CUR_SVC,								/**< Handle_t hCurSvc */	//	eDxSETUP_USER_CUR_SVC

	eDB_PARAM_ITEM_USER_PINCODE,						/**< Text */				//	eDxSETUP_USER_PINCODE

	eDB_PARAM_ITEM_REGION_CODE,							/**< HUINT32 sg_RegionCode *///	eDxSETUP_USER_REGION_CODE

	eDB_PARAM_ITEM_BOUQUET_ID,							/**< HUINT32 sg_BouquetId *///	eDxSETUP_USER_BOUQUET_ID


	eDB_PARAM_ITEM_HOME_TP_INFO_1,						/**< Binary */				//	eDxSETUP_USER_HOME_TP_INFO_1
	eDB_PARAM_ITEM_HOME_TP_INFO_2,						/**< Binary */				//	eDxSETUP_USER_HOME_TP_INFO_2
	eDB_PARAM_ITEM_HOME_TP_INFO_3,						/**< Binary */				//	eDxSETUP_USER_HOME_TP_INFO_3

	eDB_PARAM_ITEM_BAT_INFO,							/**< HUINT32 nNewCrcOfCrc *///	eDxSETUP_USER_BAT_INFO
	eDB_PARAM_ITEM_LAST_TV_SVC,							/**< Handle_t hSvc */		//	eDxSETUP_USER_LAST_TV_SVC
	eDB_PARAM_ITEM_LAST_RADIO_SVC,						/**< Handle_t hSvc */		//	eDxSETUP_USER_LAST_RADIO_SVC


	eDB_PARAM_ITEM_UPC_7DAY_TIMEDATA,					/**< UNIXTIME ulSavedTime *///	eDxSETUP_USER_UPC_7DAY_TIMEDATA

	eDB_PARAM_ITEM_OTA_DETECT_INFO,						/**< Binary */				//	eDxSETUP_USER_OTA_DETECT_INFO

	eDB_PARAM_ITEM_OTA_FLAG,							/**< (HINT32)TRUE */		//	eDxSETUP_USER_OTA_FLAG
	eDB_PARAM_ITEM_OTA_USERCANCELLED_VER,				/**< HUINT32 ulCanceledVer *///	eDxSETUP_USER_OTA_USERCANCELLED_VER
	eDB_PARAM_ITEM_OTA_USERCANCELLED_TYPE,				/**< HUINT16 usCanceledType *///eDxSETUP_USER_OTA_USERCANCELLED_TYPE

	eDB_PARAM_ITEM_OTA_TSINFO,							/**< Binary */				//	eDxSETUP_USER_OTA_TSINFO
	eDB_PARAM_ITEM_OTA_OTAINFO,							/**< Binary */				//	eDxSETUP_USER_OTA_OTAINFO
	eDB_PARAM_ITEM_OTA_DOWNLOADEDINFO,					/**< Binary */				//	eDxSETUP_USER_OTA_DOWNLOADEDINFO
	eDB_PARAM_ITEM_OTA_EMERGENCYINFO,					/**< Binary */				//	eDxSETUP_USER_OTA_EMERGENCYINFO
	eDB_PARAM_ITEM_OTA_SCHEDULEINFO,					/**< Binary */				//	eDxSETUP_USER_OTA_SCHEDULEINFO

	eDB_PARAM_ITEM_OTA_RETRYCOUNT,						/**< HINT32	nCount */		//	eDxSETUP_USER_OTA_RETRYCOUNT
	eDB_PARAM_ITEM_OTA_RETRYVER,						/**< HUINT32 ulRetryOtaVer *///	eDxSETUP_USER_OTA_RETRYVER
	eDB_PARAM_ITEM_OTA_RETRYTYPE,						/**< HUINT16 usRetryOtaType *///eDxSETUP_USER_OTA_RETRYTYPE
	eDB_PARAM_ITEM_OTA_WAKEUP_FLAG,						/**< HINT32		nValue */	//	eDxSETUP_USER_OTA_WAKEUP_FLAG
	eDB_PARAM_ITEM_ANTENNA_SORT_METHOD,					/**< MgrTplist_SatSortMethod_e */// eDxSETUP_USER_ANTENNA_SORT_METHOD

	eDB_PARAM_ITEM_PVR_DEFAULT_HDD_UUID,				/**< Text */				//	eDxSETUP_USER_PVR_DEFAULT_HDD_UUID

	eDB_PARAM_ITEM_HOME_CHANNEL,						/**< Binary */				//	eDxSETUP_USER_HOME_CHANNEL

	eDB_PARAM_ITEM_REGULAR_AUTO_UPDATE_SUCCESS,			/**< Regular_Auto_Update_Success_t */	//	eDxSETUP_SYSTEM_REGULAR_AUTO_UPDATE_SUCCESS
	eDB_PARAM_ITEM_ADULT_CHANNEL,						/**< int value */						//	eDxSETUP_SYSTEM_ADULT_CHANNEL
	eDB_PARAM_ITEM_GUIDANCE_CHANNEL_GENRE,				/**< HINT32	nVal */						//	eDxSETUP_SYSTEM_GUIDANCE_CHANNEL_GENRE

	eDB_PARAM_ITEM_NIT_TS_LOOP_CRC32,					/**< HUINT32 ulNewCrc32 */				//	eDxSETUP_USER_NIT_TS_LOOP_CRC32
	eDB_PARAM_ITEM_FAV_CHNUM_ORDER,						/**< HINT32 nValue */					//	eDxSETUP_SYSTEM_FAV_CHNUM_ORDER
	eDB_PARAM_ITEM_DYNAMIC_UPDATE_SETTING,				/**< HINT32 nItemValue */				//	eDxSETUP_SYSTEM_DYNAMIC_UPDATE_SETTING
	eDB_PARAM_ITEM_CABLE_SEARCH_MODE,					/**< HUINT32 ulSearchMode */			//	eDxSETUP_SYSTEM_CABLE_SEARCH_MODE

	eDB_PARAM_ITEM_SI_MODE,								/**< HUINT32 ulSearchMode */			//	eDxSETUP_USER_FSAT_SI_MODE		// Factory Item

	eDB_PARAM_ITEM_SVCLISTID,							// eDxSETUP_SYSTEM_SES_SVCLISTID,
	eDB_PARAM_ITEM_SVCLISTVER,							// eDxSETUP_SYSTEM_SES_SVCLISTVER,
	eDB_PARAM_ITEM_SVCLISTNAME,							// eDxSETUP_SYSTEM_SES_SVCLISTNAME,
	eDB_PARAM_ITEM_TVNUM,								// eDxSETUP_SYSTEM_SES_TVNUM,
	eDB_PARAM_ITEM_RADIONUM,							// eDxSETUP_SYSTEM_SES_RADIONUM,
	eDB_PARAM_ITEM_LASTCHECKEDTIME,						// eDxSETUP_SYSTEM_SES_LASTCHECKEDTIME,
	eDB_PARAM_ITEM_LASTUPDATEDTIME,						// eDxSETUP_SYSTEM_SES_LASTUPDATEDTIME,
	eDB_PARAM_ITEM_REPLACESVC_NUM,						// eDxSETUP_SYSTEM_SES_REPLACESVC_NUM,
	eDB_PARAM_ITEM_REPLACESVC_ITEMS,					// eDxSETUP_SYSTEM_SES_REPLACESVC_ITEMS,
	eDB_PARAM_ITEM_NEWSVC_NUM,							// eDxSETUP_SYSTEM_SES_NEWSVC_NUM,
	eDB_PARAM_ITEM_NEWSVC_ITEMS,						// eDxSETUP_SYSTEM_SES_NEWSVC_ITEMS,
	eDB_PARAM_ITEM_SCINSERTED,							// eDxSETUP_SYSTEM_SES_SCINSERTED,
	eDB_PARAM_ITEM_REPLACELATER_NUM,					// eDxSETUP_SYSTEM_SES_REPLACELATER_NUM,
	eDB_PARAM_ITEM_REPLACELATER_ITEMS,					// eDxSETUP_SYSTEM_SES_REPLACELATER_ITEMS,
	eDB_PARAM_ITEM_COLDBOOT_RESULT,						// eDxSETUP_SYSTEM_SES_COLDBOOT_RESULT,
	eDB_PARAM_ITEM_SATREC_DETECTINFO,					// eDxSETUP_SYSTEM_SES_SATREC_DETECTINFO,
	eDB_PARAM_ITEM_SATREC_FBDVERSION,					// eDxSETUP_SYSTEM_SES_SATREC_FBDVERSION,
	eDB_PARAM_ITEM_SATREC_BDVERSION,					// eDxSETUP_SYSTEM_SES_SATREC_BDVERSION,
	eDB_PARAM_ITEM_SATREC_RECEIVERID,					///**< HINT32	receverid */
	eDB_PARAM_ITEM_SATREC_UPDATE_INTERVAL,				//**< HINT32	receverid */
	eDB_PARAM_ITEM_OLDPREPAIDRIGHT,						// eDxSETUP_SYSTEM_SES_OLDPREPAIDRIGHT,
	eDB_PARAM_ITEM_EM36_OPEN,							// eDxSETUP_SYSTEM_SES_EM36_OPEN,
	eDB_PARAM_ITEM_SC_OLD_SN,							// eDxSETUP_SYSTEM_SES_SC_OLD_SN,
	eDB_PARAM_ITEM_DESCRAMBLEONOFF, 					/**< HBOOL bOn		*/

	eDB_PARAM_ITEM_BATUPDATEONOFF,						//
	eDB_PARAM_ITEM_NITLCNUPDATEONOFF,                    //

	// ASO : Analog Switch Off
	eDB_PARAM_ITEM_ASO_NOTIFY_FLAG,						/*HBOOL 	bNotify */							//eDxSETUP_USER_ASO_NOTIFY_FLAG
	eDB_PARAM_ITEM_ASO_NETWORK_CHANGE_INFO, 			/*< Binary */								// eDxSETUP_USER_ASO_NETWORK_CHANGE_INFO
	eDB_PARAM_ITEM_ASO_NETWORK_MSG_INFO, 				/*< Binary */								// eDxSETUP_USER_ASO_ASO_NETWORK_MSG_INFO
	eDB_PARAM_ITEM_ASO_LAST_SCAN_TIME,					/** UNIXTIME ulLastScanTime */				// eDxSETUP_USER_ASO_LAST_SCAN_TIME
	eDB_PARAM_ITEM_REGION_NAMEINFO_CNT,					/* HUINT32 ulCount */						// eDxSETUP_USER_REGION_NAMEINFO_CNT
	eDB_PARAM_ITEM_REGION_NAMEINFO,						/* <Binary */								// eDxSETUP_USER_REGION_NAMEINFO_PTR
	eDB_PARAM_ITEM_DISPLAY_CRID_SETTING, 				/* <HBOOL bOnOff >*/						// eDxSETUP_SYSTEM_DISPLAY_CRID_SETTING

	eDB_PARAM_ITEM_ANTENNA_POWER,						/**< HINT32 nItemValue */					//	eDxSETUP_SYSTEM_ANTENNA_POWER
	eDB_PARAM_ITEM_LAST_MIC_VOLUME,						/**< HUINT32 ulMicVolume		*/
	eDB_PARAM_ITEM_MAX
} DbParam_Item_e;

/*******************************************************************/
/********************      Global Variables     ********************/
/*******************************************************************/

/*******************************************************************/
/********************      Public Functions     ********************/
/*******************************************************************/

HERROR	DB_PARAM_LoadDefault(HBOOL bKeepFactoryValue); /**< TRUE면 생산 공정에서 설정된 값들 유지, FALSE면 factory reset */
void	DB_PARAM_Close(void);
HERROR	DB_PARAM_Sync(void);
HERROR	DB_PARAM_RemoveCache(void);

HERROR	DB_PARAM_SetItem (DbParam_Item_e eItem, HUINT32 ulData, HUINT32 ulParam);
HERROR	DB_PARAM_GetItem (DbParam_Item_e eItem, HUINT32 *pulData, HUINT32 ulParam);
HERROR	DB_PARAM_GetItemType (DbParam_Item_e eItem, DbParam_Type_e *peDataType);
HERROR	DB_PARAM_GetDefaultItem (DbParam_Item_e eItem, HUINT32 *pulData);

HBOOL	DB_PARAM_KeepingItemFinished (void);
HBOOL	DB_PARAM_KeepingItemAllTableRemoved (void *pvKeepingItemContext, HUINT32 ulType);
HERROR	DB_PARAM_KeepingItemWrite (void *pvKeepingItemContext);


#endif /* __DB_PARAM_H__ */

