/***************************************************************************
 *     Copyright (c) 2005-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * [File Description:]
 *
 * Revision History:
 *
 * $brcm_Log: $
 * 
 ***************************************************************************/

#ifndef _BWFE_4550_H__
#define _BWFE_4550_H__

#include "bchp_odu_wfe_core0_0.h"
#include "bchp_odu_wfe_core_intr2_0_0.h"
#include "bchp_odu_wfe_ana_u7_0.h"
#include "bchp_tm.h"


//#define BWFE_BYPASS_LIC
//#define BWFE_BYPASS_DGS
//#define BWFE_BYPASS_INL
//#define BWFE_BYPASS_EQU

#define BWFE_MAJOR_VERSION 0x01
#define BWFE_MINOR_VERSION 0x04
#define BWFE_NUM_CHANNELS  14    /* 7 input ADC x 2 */
#define BWFE_NUM_LANES     4     /* excluding 2 ref lanes */
#define BWFE_NUM_LIC_TAPS  17    /* 16 taps per lane + DCO tap */
#define BWFE_NUM_EQ_TAPS   3
#define BWFE_XTAL_FREQ_KHZ 54000

#define BWFE_REF_LANE0     BWFE_NUM_LANES
#define BWFE_REF_LANE1     (BWFE_NUM_LANES + 1)
#define BWFE_NUM_SLICES    (BWFE_NUM_LANES / 2 + 1)   /* 2 lanes per slice + 1 ref slice */

#define BWFE_DEF_FS_ADC_KHZ   1800000  /* Fs_adc = 1800MHz */

/* WFE base registers */
#define BCHP_WFE_CORE_HDOFFCTL0              BCHP_ODU_WFE_CORE0_0_HDOFFCTL0
#define BCHP_WFE_CORE_HDOFFCTL1              BCHP_ODU_WFE_CORE0_0_HDOFFCTL1
#define BCHP_WFE_CORE_HDOFFSTS               BCHP_ODU_WFE_CORE0_0_HDOFFSTS
#define BCHP_WFE_CORE_DGSCTL_LN0             BCHP_ODU_WFE_CORE0_0_DGSCTL_LN0
#define BCHP_WFE_CORE_DGSCTL_LN1             BCHP_ODU_WFE_CORE0_0_DGSCTL_LN1
#define BCHP_WFE_CORE_DGSCTL_LN2             BCHP_ODU_WFE_CORE0_0_DGSCTL_LN2
#define BCHP_WFE_CORE_DGSCTL_LN3             BCHP_ODU_WFE_CORE0_0_DGSCTL_LN3
#define BCHP_WFE_CORE_DGSCTL_REF0            BCHP_ODU_WFE_CORE0_0_DGSCTL_REF0
#define BCHP_WFE_CORE_DGSCTL_REF1            BCHP_ODU_WFE_CORE0_0_DGSCTL_REF1
#define BCHP_WFE_CORE_DGSCLP_LN0             BCHP_ODU_WFE_CORE0_0_DGSCLP_LN0
#define BCHP_WFE_CORE_DGSCLP_LN1             BCHP_ODU_WFE_CORE0_0_DGSCLP_LN1
#define BCHP_WFE_CORE_DGSCLP_LN2             BCHP_ODU_WFE_CORE0_0_DGSCLP_LN2
#define BCHP_WFE_CORE_DGSCLP_LN3             BCHP_ODU_WFE_CORE0_0_DGSCLP_LN3
#define BCHP_WFE_CORE_DGSCLP_REF0            BCHP_ODU_WFE_CORE0_0_DGSCLP_REF0
#define BCHP_WFE_CORE_DGSCLP_REF1            BCHP_ODU_WFE_CORE0_0_DGSCLP_REF1
#define BCHP_WFE_CORE_DGSHIST_LN0            BCHP_ODU_WFE_CORE0_0_DGSHIST_LN0
#define BCHP_WFE_CORE_DGSHIST_LN1            BCHP_ODU_WFE_CORE0_0_DGSHIST_LN1
#define BCHP_WFE_CORE_DGSHIST_LN2            BCHP_ODU_WFE_CORE0_0_DGSHIST_LN2
#define BCHP_WFE_CORE_DGSHIST_LN3            BCHP_ODU_WFE_CORE0_0_DGSHIST_LN3
#define BCHP_WFE_CORE_DGSHIST_REF0           BCHP_ODU_WFE_CORE0_0_DGSHIST_REF0
#define BCHP_WFE_CORE_DGSHIST_REF1           BCHP_ODU_WFE_CORE0_0_DGSHIST_REF1
#define BCHP_WFE_CORE_DGSCLPCNT_LN0          BCHP_ODU_WFE_CORE0_0_DGSCLPCNT_LN0
#define BCHP_WFE_CORE_DGSCLPCNT_LN1          BCHP_ODU_WFE_CORE0_0_DGSCLPCNT_LN1
#define BCHP_WFE_CORE_DGSCLPCNT_LN2          BCHP_ODU_WFE_CORE0_0_DGSCLPCNT_LN2
#define BCHP_WFE_CORE_DGSCLPCNT_LN3          BCHP_ODU_WFE_CORE0_0_DGSCLPCNT_LN3
#define BCHP_WFE_CORE_DGSCLPCNT_REF0         BCHP_ODU_WFE_CORE0_0_DGSCLPCNT_REF0
#define BCHP_WFE_CORE_DGSCLPCNT_REF1         BCHP_ODU_WFE_CORE0_0_DGSCLPCNT_REF1
#define BCHP_WFE_CORE_DGSACCUM_LN0           BCHP_ODU_WFE_CORE0_0_DGSACCUM_LN0
#define BCHP_WFE_CORE_DGSACCUM_LN1           BCHP_ODU_WFE_CORE0_0_DGSACCUM_LN1
#define BCHP_WFE_CORE_DGSACCUM_LN2           BCHP_ODU_WFE_CORE0_0_DGSACCUM_LN2
#define BCHP_WFE_CORE_DGSACCUM_LN3           BCHP_ODU_WFE_CORE0_0_DGSACCUM_LN3
#define BCHP_WFE_CORE_DGSACCUM_REF0          BCHP_ODU_WFE_CORE0_0_DGSACCUM_REF0
#define BCHP_WFE_CORE_DGSACCUM_REF1          BCHP_ODU_WFE_CORE0_0_DGSACCUM_REF1
#define BCHP_WFE_CORE_DGSLUT011_LN0          BCHP_ODU_WFE_CORE0_0_DGSLUT011_LN0
#define BCHP_WFE_CORE_DGSLUT010_LN0          BCHP_ODU_WFE_CORE0_0_DGSLUT010_LN0
#define BCHP_WFE_CORE_DGSLUT001_LN0          BCHP_ODU_WFE_CORE0_0_DGSLUT001_LN0
#define BCHP_WFE_CORE_DGSLUT000_LN0          BCHP_ODU_WFE_CORE0_0_DGSLUT000_LN0
#define BCHP_WFE_CORE_DGSLUT111_LN0          BCHP_ODU_WFE_CORE0_0_DGSLUT111_LN0
#define BCHP_WFE_CORE_DGSLUT110_LN0          BCHP_ODU_WFE_CORE0_0_DGSLUT110_LN0
#define BCHP_WFE_CORE_DGSLUT101_LN0          BCHP_ODU_WFE_CORE0_0_DGSLUT101_LN0
#define BCHP_WFE_CORE_DGSLUT011_LN1          BCHP_ODU_WFE_CORE0_0_DGSLUT011_LN1
#define BCHP_WFE_CORE_DGSLUT010_LN1          BCHP_ODU_WFE_CORE0_0_DGSLUT010_LN1
#define BCHP_WFE_CORE_DGSLUT001_LN1          BCHP_ODU_WFE_CORE0_0_DGSLUT001_LN1
#define BCHP_WFE_CORE_DGSLUT000_LN1          BCHP_ODU_WFE_CORE0_0_DGSLUT000_LN1
#define BCHP_WFE_CORE_DGSLUT111_LN1          BCHP_ODU_WFE_CORE0_0_DGSLUT111_LN1
#define BCHP_WFE_CORE_DGSLUT110_LN1          BCHP_ODU_WFE_CORE0_0_DGSLUT110_LN1
#define BCHP_WFE_CORE_DGSLUT101_LN1          BCHP_ODU_WFE_CORE0_0_DGSLUT101_LN1
#define BCHP_WFE_CORE_DGSLUT011_LN2          BCHP_ODU_WFE_CORE0_0_DGSLUT011_LN2
#define BCHP_WFE_CORE_DGSLUT010_LN2          BCHP_ODU_WFE_CORE0_0_DGSLUT010_LN2
#define BCHP_WFE_CORE_DGSLUT001_LN2          BCHP_ODU_WFE_CORE0_0_DGSLUT001_LN2
#define BCHP_WFE_CORE_DGSLUT000_LN2          BCHP_ODU_WFE_CORE0_0_DGSLUT000_LN2
#define BCHP_WFE_CORE_DGSLUT111_LN2          BCHP_ODU_WFE_CORE0_0_DGSLUT111_LN2
#define BCHP_WFE_CORE_DGSLUT110_LN2          BCHP_ODU_WFE_CORE0_0_DGSLUT110_LN2
#define BCHP_WFE_CORE_DGSLUT101_LN2          BCHP_ODU_WFE_CORE0_0_DGSLUT101_LN2
#define BCHP_WFE_CORE_DGSLUT011_LN3          BCHP_ODU_WFE_CORE0_0_DGSLUT011_LN3
#define BCHP_WFE_CORE_DGSLUT010_LN3          BCHP_ODU_WFE_CORE0_0_DGSLUT010_LN3
#define BCHP_WFE_CORE_DGSLUT001_LN3          BCHP_ODU_WFE_CORE0_0_DGSLUT001_LN3
#define BCHP_WFE_CORE_DGSLUT000_LN3          BCHP_ODU_WFE_CORE0_0_DGSLUT000_LN3
#define BCHP_WFE_CORE_DGSLUT111_LN3          BCHP_ODU_WFE_CORE0_0_DGSLUT111_LN3
#define BCHP_WFE_CORE_DGSLUT110_LN3          BCHP_ODU_WFE_CORE0_0_DGSLUT110_LN3
#define BCHP_WFE_CORE_DGSLUT101_LN3          BCHP_ODU_WFE_CORE0_0_DGSLUT101_LN3
#define BCHP_WFE_CORE_DGSLUT011_REF0         BCHP_ODU_WFE_CORE0_0_DGSLUT011_REF0
#define BCHP_WFE_CORE_DGSLUT010_REF0         BCHP_ODU_WFE_CORE0_0_DGSLUT010_REF0
#define BCHP_WFE_CORE_DGSLUT001_REF0         BCHP_ODU_WFE_CORE0_0_DGSLUT001_REF0
#define BCHP_WFE_CORE_DGSLUT000_REF0         BCHP_ODU_WFE_CORE0_0_DGSLUT000_REF0
#define BCHP_WFE_CORE_DGSLUT111_REF0         BCHP_ODU_WFE_CORE0_0_DGSLUT111_REF0
#define BCHP_WFE_CORE_DGSLUT110_REF0         BCHP_ODU_WFE_CORE0_0_DGSLUT110_REF0
#define BCHP_WFE_CORE_DGSLUT101_REF0         BCHP_ODU_WFE_CORE0_0_DGSLUT101_REF0
#define BCHP_WFE_CORE_DGSLUT011_REF1         BCHP_ODU_WFE_CORE0_0_DGSLUT011_REF1
#define BCHP_WFE_CORE_DGSLUT010_REF1         BCHP_ODU_WFE_CORE0_0_DGSLUT010_REF1
#define BCHP_WFE_CORE_DGSLUT001_REF1         BCHP_ODU_WFE_CORE0_0_DGSLUT001_REF1
#define BCHP_WFE_CORE_DGSLUT000_REF1         BCHP_ODU_WFE_CORE0_0_DGSLUT000_REF1
#define BCHP_WFE_CORE_DGSLUT111_REF1         BCHP_ODU_WFE_CORE0_0_DGSLUT111_REF1
#define BCHP_WFE_CORE_DGSLUT110_REF1         BCHP_ODU_WFE_CORE0_0_DGSLUT110_REF1
#define BCHP_WFE_CORE_DGSLUT101_REF1         BCHP_ODU_WFE_CORE0_0_DGSLUT101_REF1
#define BCHP_WFE_CORE_DGSLMS_PAIR0           BCHP_ODU_WFE_CORE0_0_DGSLMS_PAIR0
#define BCHP_WFE_CORE_DGSLMS_PAIR1           BCHP_ODU_WFE_CORE0_0_DGSLMS_PAIR1
#define BCHP_WFE_CORE_DGSLMS_REF             BCHP_ODU_WFE_CORE0_0_DGSLMS_REF
#define BCHP_WFE_CORE_DGSCOEFD_PAIR0         BCHP_ODU_WFE_CORE0_0_DGSCOEFD_PAIR0
#define BCHP_WFE_CORE_DGSCOEFA_PAIR0         BCHP_ODU_WFE_CORE0_0_DGSCOEFA_PAIR0
#define BCHP_WFE_CORE_DGSCOEFD_PAIR1         BCHP_ODU_WFE_CORE0_0_DGSCOEFD_PAIR1
#define BCHP_WFE_CORE_DGSCOEFA_PAIR1         BCHP_ODU_WFE_CORE0_0_DGSCOEFA_PAIR1
#define BCHP_WFE_CORE_DGSCOEFD_REF           BCHP_ODU_WFE_CORE0_0_DGSCOEFD_REF
#define BCHP_WFE_CORE_DGSCOEFA_REF           BCHP_ODU_WFE_CORE0_0_DGSCOEFA_REF
#define BCHP_WFE_CORE_LICCTL1                BCHP_ODU_WFE_CORE0_0_LICCTL1
#define BCHP_WFE_CORE_LICCTL2                BCHP_ODU_WFE_CORE0_0_LICCTL2
#define BCHP_WFE_CORE_LICDCO0                BCHP_ODU_WFE_CORE0_0_LICDCO0
#define BCHP_WFE_CORE_LICDCO1                BCHP_ODU_WFE_CORE0_0_LICDCO1
#define BCHP_WFE_CORE_LICCOEFD               BCHP_ODU_WFE_CORE0_0_LICCOEFD
#define BCHP_WFE_CORE_LICCOEFA               BCHP_ODU_WFE_CORE0_0_LICCOEFA
#define BCHP_WFE_CORE_AGCCTL2                BCHP_ODU_WFE_CORE0_0_AGCCTL2
#define BCHP_WFE_CORE_AGCCTL1                BCHP_ODU_WFE_CORE0_0_AGCCTL1
#define BCHP_WFE_CORE_REG_AGC_LF_INT_WDATA   BCHP_ODU_WFE_CORE0_0_REG_AGC_LF_INT_WDATA
#define BCHP_WFE_CORE_REG_AGC_LA_INT_WDATA   BCHP_ODU_WFE_CORE0_0_REG_AGC_LA_INT_WDATA

/* WFE lane registers */
#define BCHP_WFE_CORE_DGSCTL_LN        BCHP_ODU_WFE_CORE0_0_DGSCTL_LN0
#define BCHP_WFE_CORE_DGSCLP_LN        BCHP_ODU_WFE_CORE0_0_DGSCLP_LN0
#define BCHP_WFE_CORE_DGSHIST_LN       BCHP_ODU_WFE_CORE0_0_DGSHIST_LN0
#define BCHP_WFE_CORE_DGSCLPCNT_LN     BCHP_ODU_WFE_CORE0_0_DGSCLPCNT_LN0
#define BCHP_WFE_CORE_DGSACCUM_LN      BCHP_ODU_WFE_CORE0_0_DGSACCUM_LN0
#define BCHP_WFE_CORE_DGSLUT011_LN     BCHP_ODU_WFE_CORE0_0_DGSLUT011_LN0
#define BCHP_WFE_CORE_DGSLUT010_LN     BCHP_ODU_WFE_CORE0_0_DGSLUT010_LN0
#define BCHP_WFE_CORE_DGSLUT001_LN     BCHP_ODU_WFE_CORE0_0_DGSLUT001_LN0
#define BCHP_WFE_CORE_DGSLUT000_LN     BCHP_ODU_WFE_CORE0_0_DGSLUT000_LN0
#define BCHP_WFE_CORE_DGSLUT111_LN     BCHP_ODU_WFE_CORE0_0_DGSLUT111_LN0
#define BCHP_WFE_CORE_DGSLUT110_LN     BCHP_ODU_WFE_CORE0_0_DGSLUT110_LN0
#define BCHP_WFE_CORE_DGSLUT101_LN     BCHP_ODU_WFE_CORE0_0_DGSLUT101_LN0

/* WBADC base registers */
#define BCHP_WFE_ANA_U7_RFFE_SIGR01_IN          BCHP_ODU_WFE_ANA_U7_0_RFFE_SIGR01_IN0
#define BCHP_WFE_ANA_U7_RFFE_WRITER01_IN        BCHP_ODU_WFE_ANA_U7_0_RFFE_WRITER01_IN0
#define BCHP_WFE_ANA_U7_ADC_CNTL0               BCHP_ODU_WFE_ANA_U7_0_ADC_CNTL0
#define BCHP_WFE_ANA_U7_ADC_CNTL1               BCHP_ODU_WFE_ANA_U7_0_ADC_CNTL1
#define BCHP_WFE_ANA_U7_ADC_CNTL2               BCHP_ODU_WFE_ANA_U7_0_ADC_CNTL2
#define BCHP_WFE_ANA_U7_ADC_CNTL3               BCHP_ODU_WFE_ANA_U7_0_ADC_CNTL3
#define BCHP_WFE_ANA_U7_WBADC_CAL_CNTL_IN       BCHP_ODU_WFE_ANA_U7_0_WBADC_CAL_CNTL_IN0
#define BCHP_WFE_ANA_U7_WBADC_SYS_CNTL_IN       BCHP_ODU_WFE_ANA_U7_0_WBADC_SYS_CNTL_IN0
#define BCHP_WFE_ANA_U7_WBADC_TIMING_CNTL_IN    BCHP_ODU_WFE_ANA_U7_0_WBADC_TIMING_CNTL_IN0
#define BCHP_WFE_ANA_U7_WBADC_TOP_CNTL_IN       BCHP_ODU_WFE_ANA_U7_0_WBADC_TOP_CNTL_IN0
#define BCHP_WFE_ANA_U7_REG_CTRL                BCHP_ODU_WFE_ANA_U7_0_REG_CTRL
#define BCHP_WFE_ANA_U7_SW_SPARE0               BCHP_ODU_WFE_ANA_U7_0_SW_SPARE0
#define BCHP_WFE_ANA_U7_SW_SPARE1               BCHP_ODU_WFE_ANA_U7_0_SW_SPARE1

#endif /* BWFE_4550_H__ */
