obj-y += mhegib_main.o

obj-y += ib/

# Additional include path
ccflags-y += -I$(HUMAX_TOP_DIR)/apps/make/include
ccflags-y += -I$(HUMAX_TOP_DIR)/apps/humaxtv/hlib/include
ccflags-y += -I$(HUMAX_TOP_DIR)/apps/humaxtv/dlibs/datalibs/include
ccflags-y += -I$(HUMAX_TOP_DIR)/apps/humaxtv/octo/include
ccflags-y += -I$(HUMAX_TOP_DIR)/apps/humaxtv/appkit/base
ccflags-y += -I$(HUMAX_TOP_DIR)/apps/humaxtv/hama/include
ccflags-y += -I$(HUMAX_TOP_DIR)/apps/humaxtv/application/mlib/include

