obj-y += vmx_vr_iptvh_ecm.o
obj-y += vmx_vr_iptvh_emm.o
obj-y += vmx_vr_iptvh_psi_mgr.o

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
