/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_aud_fmm_bf_esr0_d0.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 9/14/09 3:52p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Sep 11 19:45:11 2009
 *                 MD5 Checksum         957f01e03a68c1766fd2e8ad6484f5f9
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7468/rdb/a0/bchp_aud_fmm_bf_esr0_d0.h $
 * 
 * Hydra_Software_Devel/1   9/14/09 3:52p albertl
 * SW7468-3: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_AUD_FMM_BF_ESR0_D0_H__
#define BCHP_AUD_FMM_BF_ESR0_D0_H__

/***************************************************************************
 *AUD_FMM_BF_ESR0_D0 - FMM-BF Error Status 0 (for DSP0)
 ***************************************************************************/
#define BCHP_AUD_FMM_BF_ESR0_D0_STATUS           0x00391100 /* Error Status Register */
#define BCHP_AUD_FMM_BF_ESR0_D0_STATUS_SET       0x00391104 /* Error Set Register */
#define BCHP_AUD_FMM_BF_ESR0_D0_STATUS_CLEAR     0x00391108 /* Error Clear Register */
#define BCHP_AUD_FMM_BF_ESR0_D0_MASK             0x0039110c /* Mask Status Register */
#define BCHP_AUD_FMM_BF_ESR0_D0_MASK_SET         0x00391110 /* Mask Set Register */
#define BCHP_AUD_FMM_BF_ESR0_D0_MASK_CLEAR       0x00391114 /* Mask Clear Register */

#endif /* #ifndef BCHP_AUD_FMM_BF_ESR0_D0_H__ */

/* End of File */
