#!/bin/sh

	umount /var/lib/humaxtv
	umount /var/lib/humaxtv_backup
	umount /var/lib/humaxtv_user
	ubidetach -m 3
	ubiformat -y /dev/mtd3
	ubiattach -m 3
	ubimkvol /dev/ubi2 -N dbbackup -s 92MiB
	ubimkvol /dev/ubi2 -N dbdata -s 32MiB
	ubimkvol /dev/ubi2 -N dbuser -s 768MiB	
	ubidetach -m 3
