obj-y += pl_dms.o
obj-y += pl_dms_scan.o
obj-y += pl_dms_scan_epg.o
obj-y += pl_dms_scan_pvr.o
obj-y += pl_dms_scan_media.o
obj-y += pl_dms_fsop.o

# DLNA 3rd-party include path
include $(OCTOSVC_SRC_DIR)/homma/main/module/include/Makefile.include.mxlib
#ccflags-y += -I$(THIRDPARTY_DIR)/dlna/mxlib/transcoder/transcoder_Control
#ccflags-y += -I$(THIRDPARTY_DIR)/dlna/mxlib/transcoder/transcoderWrapper_HMS_HW
