-include ./dirs

ifeq ($(DIRS),)
TARGET = licensesyncstub

SOURCES =                \
	licensesyncutilstub.c drmgensyncchallengestub.c drmsyncstorestub.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
