/**************************************************************************************/
/**
 * @file bplinit.c
 *
 * Initialization
 *
 * @author  ipm(@humaxdigital.com)
 * @date    2012/09/24
 * @attention   Copyright (c) 2012 Humax - All rights reserved.
 *
 **************************************************************************************
 **/

#include "bpldb.h"

#include "vkernel.h"
#include "hlib.h"
#include "apk.h"

/*********************************************************************************
 * Static functions
 *********************************************************************************/

/*********************************************************************************
 * Interfaces
 *********************************************************************************/
BPLStatus	BPL_DB_Default(void)
{
#if	defined(CONFIG_OP_FREESAT)
	APK_DB_SetInt(USERDB_SUBTITLE_DISPLAY, 0);
	APK_DB_SetInt(USERDB_SUBTITLE_FONT, 1);
	APK_DB_SetInt(USERDB_RECORDING_TSR_ONOFF, TRUE);
	APK_DB_SetInt(USERDB_RECORDING_SKIP_FORWARD_TIME, 120);
	APK_DB_SetInt(USERDB_RECORDING_INSTANT_REPLAY_TIME, 15);

	APK_DB_SetInt(USERDB_SYSTEM_AUDIO_BLEEP, 1);
	APK_DB_SetInt(USERDB_SYSTEM_AUTOMATIC_POWER_DOWN, 1);
	APK_DB_SetInt(USERDB_SYSTEM_STANDBY_MODE, 1);
	APK_DB_SetInt(USERDB_DLNA_DMS_ACTIVATION, 1);
	APK_DB_SetInt(USERDB_FTP_LAUNCH, 0);
	APK_DB_SetInt(USERDB_RECORDING_DESCRAMBLE_ONOFF, FALSE);
#elif defined(CONFIG_OP_JAPAN)
	APK_DB_SetInt(USERDB_SUBTITLE_DISPLAY, 0);
	APK_DB_SetInt(USERDB_SUBTITLE_FONT, 0);
	APK_DB_SetInt(USERDB_RECORDING_TSR_ONOFF, FALSE);
	APK_DB_SetInt(USERDB_DLNA_DMS_ACTIVATION, FALSE);
	APK_DB_SetInt(USERDB_JLABS_TUNING_RANGE, eTuningRange_TV);
	APK_DB_SetInt(USERDB_JLABS_TIMEBAR_DISP_MODE, eTimebarDispMode_Mini);
	APK_DB_SetInt(USERDB_JLABS_I_PLATE_DISP_ENABLE, TRUE);
	APK_DB_SetInt(USERDB_RECORDING_DESCRAMBLE_ONOFF, FALSE);
#elif defined(CONFIG_OP_MIDDLE_EAST)
	APK_DB_SetInt(USERDB_SUBTITLE_DISPLAY, 1);
	APK_DB_SetInt(USERDB_SUBTITLE_FONT, 1);
	APK_DB_SetInt(USERDB_RECORDING_TSR_ONOFF, FALSE);
	APK_DB_SetInt(USERDB_SCREENDISP_INFO_DISP_TIME, 5);

#if defined(CONFIG_PROD_IR4100HD)
	APK_DB_SetInt(USERDB_IPEPG_ONOFF, TRUE);
	APK_DB_SetInt(USERDB_THUMBNAIL_ONOFF, TRUE);
#else
	APK_DB_SetInt(USERDB_IPEPG_ONOFF, FALSE);
	APK_DB_SetInt(USERDB_THUMBNAIL_ONOFF, FALSE);
#endif
	APK_DB_SetInt(USERDB_RP_ONOFF, FALSE);
	APK_DB_SetInt(USERDB_RP_PERIOD_START, 28800);
	APK_DB_SetInt(USERDB_RP_PERIOD_END, 79200);

	APK_DB_SetInt(USERDB_RP_INTERVAL, 1800);
	APK_DB_SetInt(USERDB_RP_REG_CODE, 0);
	APK_DB_SetInt(USERDB_SERIES_PLAYBACK, FALSE);
#if defined(CONFIG_PROD_IR4100HD)
    APK_DB_SetInt(USERDB_DLNA_DMS_ACTIVATION, TRUE);
#else
	APK_DB_SetInt(USERDB_DLNA_DMS_ACTIVATION, FALSE);
#endif
	APK_DB_SetInt(USERDB_WOONSERVER_ACTIVATION, FALSE);
#if defined(CONFIG_PROD_IR4000HD) || defined(CONFIG_PROD_IR4100HD)
	APK_DB_SetInt(USERDB_DLNA_DMR_ACTIVATION, TRUE);
#else
	APK_DB_SetInt(USERDB_DLNA_DMR_ACTIVATION, FALSE);
#endif
	APK_DB_SetInt(USERDB_RECORDING_DESCRAMBLE_ONOFF, FALSE);
#elif defined(CONFIG_OP_ERTELECOM)
	// default: HMS-1000T 기준 작성
	APK_DB_SetInt(USERDB_SUBTITLE_DISPLAY, 0);
	APK_DB_SetInt(USERDB_SUBTITLE_FONT, 1);
	APK_DB_SetInt(USERDB_RECORDING_TSR_ONOFF, TRUE);
	APK_DB_SetInt(USERDB_SCREENDISP_INFO_DISP_TIME, 5);

	APK_DB_SetInt(USERDB_IPEPG_ONOFF, FALSE);
	APK_DB_SetInt(USERDB_RP_ONOFF, FALSE);
	APK_DB_SetInt(USERDB_RP_PERIOD_START, 28800);
	APK_DB_SetInt(USERDB_RP_PERIOD_END, 79200);

	APK_DB_SetInt(USERDB_RP_INTERVAL, 1800);
	APK_DB_SetInt(USERDB_RP_REG_CODE, 0);
	APK_DB_SetInt(USERDB_SERIES_PLAYBACK, FALSE);
	APK_DB_SetInt(USERDB_DLNA_DMS_ACTIVATION, FALSE);
	APK_DB_SetInt(USERDB_WOONSERVER_ACTIVATION, FALSE);
	APK_DB_SetInt(USERDB_DLNA_DMR_ACTIVATION, FALSE);
	APK_DB_SetInt(USERDB_RECORDING_DESCRAMBLE_ONOFF, FALSE);
#elif defined(CONFIG_OP_UK_DTT)
	APK_DB_SetInt(USERDB_SUBTITLE_DISPLAY, FALSE);
	APK_DB_SetInt(USERDB_HARD_OF_HEARING,FALSE);
	APK_DB_SetInt(USERDB_AUDIO_AUDIO_DESCRIPTION, FALSE);
	APK_DB_SetInt(USERDB_SUBTITLE_FONT, 1);
	APK_DB_SetInt(USERDB_RECORDING_TSR_ONOFF, TRUE);
	APK_DB_SetInt(USERDB_SCREENDISP_INFO_DISP_TIME, 5);

	APK_DB_SetInt(USERDB_IPEPG_ONOFF, TRUE);
	APK_DB_SetInt(USERDB_RP_ONOFF, FALSE);
	APK_DB_SetInt(USERDB_RP_PERIOD_START, 28800);
	APK_DB_SetInt(USERDB_RP_PERIOD_END, 79200);

	APK_DB_SetInt(USERDB_RP_INTERVAL, 1800);
	APK_DB_SetInt(USERDB_RP_REG_CODE, 0);
	APK_DB_SetInt(USERDB_SERIES_PLAYBACK, TRUE);
	APK_DB_SetInt(USERDB_DLNA_DMS_ACTIVATION, FALSE);	/* Default value of Network Server is changed to FALSE on FVP-4000T */
	APK_DB_SetInt(USERDB_DLNA_DMR_ACTIVATION, FALSE);	/* Default value of Network Server is changed to FALSE on FVP-4000T */
	APK_DB_SetInt(USERDB_DLNA_DIAL_ACTIVATION, TRUE);	/* Default value of DIAL is changed to TRUE on FVP-4000T */
	APK_DB_SetInt(USERDB_DLNA_SATIP_ACTIVATION, TRUE);
	APK_DB_SetInt(USERDB_AIRPLAY_ACTIVATION, TRUE);      /* HMS PH2 base: always enabled, regardless of the network server on/off state */
	APK_DB_SetInt(USERDB_WOONSERVER_ACTIVATION, TRUE);
	APK_DB_SetInt(USERDB_DLNA_SATIP_ACTIVATION, TRUE);
	APK_DB_SetInt(USERDB_SAMBACLIENT_ACTIVATION, FALSE); /* unsupported feature */
	APK_DB_SetInt(USERDB_SAMBASERVER_ACTIVATION, FALSE); /* HMS PH2 base: default-off */
	APK_DB_SetInt(USERDB_FTPSERVER_ACTIVATION, FALSE);   /* HMS PH2 base: default-off */

	APK_DB_SetInt(USERDB_TVTVEPG_LASTUPDATETIME, 0);
	APK_DB_SetInt(USERDB_RECORDING_AUTODELETE_ONOFF, FALSE);
	APK_DB_SetInt(USERDB_RECORDING_DESCRAMBLE_ONOFF, TRUE);
	APK_DB_SetInt(USERDB_INIT_HUMAX_TVPORTAL, TRUE);
#else
	// default: HMS-1000T 기준 작성
	APK_DB_SetInt(USERDB_SUBTITLE_DISPLAY, 0);
	APK_DB_SetInt(USERDB_SUBTITLE_FONT, 1);
	APK_DB_SetInt(USERDB_RECORDING_TSR_ONOFF, TRUE);
	APK_DB_SetInt(USERDB_SCREENDISP_INFO_DISP_TIME, 5);

	APK_DB_SetInt(USERDB_IPEPG_ONOFF, TRUE);
	APK_DB_SetInt(USERDB_RP_ONOFF, FALSE);
	APK_DB_SetInt(USERDB_RP_PERIOD_START, 28800);
	APK_DB_SetInt(USERDB_RP_PERIOD_END, 79200);

	APK_DB_SetInt(USERDB_RP_INTERVAL, 1800);
	APK_DB_SetInt(USERDB_RP_REG_CODE, 0);
	APK_DB_SetInt(USERDB_SERIES_PLAYBACK, TRUE);
	APK_DB_SetInt(USERDB_DLNA_DMS_ACTIVATION, TRUE);
	APK_DB_SetInt(USERDB_DLNA_DMR_ACTIVATION, TRUE);
	APK_DB_SetInt(USERDB_DLNA_DIAL_ACTIVATION, FALSE);   /* HMS PH2 base: default disabled(by webapp), because the "youtube" app registration process */
	APK_DB_SetInt(USERDB_DLNA_SATIP_ACTIVATION, TRUE);
	APK_DB_SetInt(USERDB_AIRPLAY_ACTIVATION, TRUE);      /* HMS PH2 base: always enabled, regardless of the network server on/off state */
	APK_DB_SetInt(USERDB_WOONSERVER_ACTIVATION, TRUE);
	APK_DB_SetInt(USERDB_DLNA_SATIP_ACTIVATION, TRUE);
	APK_DB_SetInt(USERDB_SAMBACLIENT_ACTIVATION, FALSE); /* unsupported feature */
	APK_DB_SetInt(USERDB_SAMBASERVER_ACTIVATION, FALSE); /* HMS PH2 base: default-off */
	APK_DB_SetInt(USERDB_FTPSERVER_ACTIVATION, FALSE);   /* HMS PH2 base: default-off */

	APK_DB_SetInt(USERDB_TVTVEPG_LASTUPDATETIME, 0);
	APK_DB_SetInt(USERDB_RECORDING_AUTODELETE_ONOFF, FALSE);
#if defined(CONFIG_PROD_HMS1000S) || defined(CONFIG_PROD_HMSLITE) || defined(CONFIG_PROD_FVP4000T)
	APK_DB_SetInt(USERDB_RECORDING_DESCRAMBLE_ONOFF, TRUE);
#else
	APK_DB_SetInt(USERDB_RECORDING_DESCRAMBLE_ONOFF, FALSE);
#endif

#if defined(CONFIG_OP_AUS_DTT)
	APK_DB_SetInt(USERDB_HBBTV_ENABLE, FALSE);
#elif defined(CONFIG_PROD_HMS1000S) || defined(CONFIG_PROD_HMSLITE)
	APK_DB_SetInt(USERDB_HBBTV_ENABLE, TRUE);
#endif

#if defined(CONFIG_OP_TELENOR)
	APK_DB_SetInt(USERDB_HARD_OF_HEARING, FALSE);
#endif

#if defined(CONFIG_OP_TDC)
	APK_DB_SetInt(USERDB_AUDIO_AUDIO_DESCRIPTION, FALSE);
	APK_DB_SetInt(USERDB_HARD_OF_HEARING, FALSE);
#endif

#if defined(CONFIG_OP_SES)
	APK_DB_SetInt(USERDB_SATRECORD_INTERVAL, 0);
	APK_DB_SetInt(USERDB_SATRECORD_PRIORITY, 0);
	APK_DB_SetInt(USERDB_SATIP_NOTIFICATION_ONOFF, FALSE);
	APK_DB_SetInt(USERDB_NO_OTA_ACTION, FALSE);
	APK_DB_SetStr(USERDB_NO_OTA_SWVER, "");
	APK_DB_SetInt(USERDB_LATER_OTA_COUNT, 0);
#endif
#endif

	return BPL_STATUS_OK;
}
