obj-y += umma_hotplug.o

# Additional include path
ccflags-y += -I$(OCTOSVC_SRC_DIR)/thma/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fs/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fs/pal/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/secure/include
