-include ./dirs

ifeq ($(DIRS),)
TARGET = oem_ansi_test

SOURCES =                \
	../oemdebug.c ../oemimpl.c ../oemfileio.c ../oeminfo.c ../oemtime.c ../oemprofile.c ../oemcriticalsection.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
