obj-y += nx_prism_component_drawer.o
obj-y += nx_prism_component_popuplist.o
obj-y += nx_prism_component_inputdialog.o
obj-y += nx_prism_component_pindialog.o
obj-y += nx_prism_component_timedialog.o
obj-$(CONFIG_MW_INET) += nx_prism_component_ipdialog.o
obj-$(CONFIG_MW_INET_WLAN) += nx_prism_component_hidden_ap_dialog.o

# Additional include path
ccflags-y += -I../../../../../../../make/include


