obj-$(CONFIG_STREAMING_SATIP_TARA) += xmgr_satip_tara.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr

# Additional include path
ccflags-y += -I$(OCTO_TVMANAGER_PLUGIN_DIR)/xmgr/satip/local_include
