#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"

const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
/*				0 			*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 000 - NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 001 - NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 002 - NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 003 - NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 004 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 005 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 006 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 007 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 008 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 009 - NC  */
/*				10 			*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 010 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 011 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 012 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 013 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 014 - NC  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 015 - EBI_WAIT  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 016 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 017 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 018 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 019 - NC  */
/*				20 			*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 020 - EBI_CS0_N  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 021 - EBI_CS1_N  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 022 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 023 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 024 - NC  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 025 - EBI_DATA0  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 026 - EBI_DATA1  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 027 - EBI_DATA2  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 028 - EBI_DATA3  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 029 - EBI_DATA4  */
/*				30 			*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 030 - EBI_DATA5  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 031 - EBI_DATA6  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 032 - EBI_DATA7  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 033 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 034 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 035 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 036 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 037 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 038 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 039 - NC  */
/*				40 			*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 040 - NC  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 041 - EBI_RD_N  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 042 - EBI_WE0_N  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 043 - EBI_DS_N  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 044 - EBI_TS_N  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 045 - NAND_RDY_BSY_N  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 046 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 047 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 048 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 049 - NC  */
/*				50 			*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 050 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 051 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 052 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 053 - NC  */
	HUMAX_GPIO_FUNCTION_ALT3,	/* GPIO 054 - 3461B_1_TS_CLK */
	HUMAX_GPIO_FUNCTION_ALT3,	/* GPIO 055 - 3461B_1_TS_SYNC */
	HUMAX_GPIO_FUNCTION_ALT3,	/* GPIO 056 - 3461B_1_TS_DATA_0 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 057 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 058 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 059 - NC  */
/*				60 			*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 060 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 061 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 062 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 063 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 064 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 065 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 066 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 067 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 068 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 069 - NC  */
/*				70 			*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 070 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 071 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 072 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 073 - NC  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 074 - HDD_PWR_CTRL */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 075 - HW_MUTE */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 076 - SLB1_SCART */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 077 - SLB2_SCART */
	HUMAX_GPIO_FUNCTION_ALT4,	/* GPIO 078 - LED_BLUE_CTRL */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 079 - NC  */
/*				80 			*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 080 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 081 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 082 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 083 - NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 084 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 085 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 086 - NC  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 087 - 3461_TS_CLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 088 - 3461_TS_DATA_0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 089 - 3461_TS_SYNC */
/*				90			*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 090 - 3461_TS_VALID */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 091 - CH_RESET_0 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 092 - UART_TXD_0 */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 093 - UART_RXD_0 */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 094 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 095 - NC  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 096 - FRONT_UART2_TX */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 097 - FRONT_UART2_RX */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 098 - EXT_IRQ2 */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 099 - SF_WP_N */
/*				100			*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 100 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 101 - NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 102 - NC */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 103 - NC */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 104 - 3461B_TS_VALID */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 105 - CH_RESET_SLAVE */ 
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 106 - USB0_PWRON */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 107 - USB1_PWRON */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 108 - USB2_PWRON */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 109 - USB3_PWRON */
/*				110			*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 110 - USB0_PWRFLT */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 111 - USB1_PWRFLT */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 112 - USB2_PWRFLT */	
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 113 - USB3_PWRFLT */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 114 - ENET_ACT  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 115 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 116 - NC  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 117 - ANT_PWR_CHK  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 118 - ANT_PWR_EN  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 119 - NC  */
/*				120			*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 120 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 121 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 122 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 123 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 124 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 125 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 126 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 127 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 128 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 129 - NC */
/*				130			*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 130 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 131 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 132 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 133 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 134 - NC  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 135 - NC  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 136 - NC  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* GPIO 137 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 138 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 139 - NC  */
/*				140			*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 140 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 141 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 142 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 143 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 144 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 145 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 146 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 147 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 148 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 149 - NC  */
/*				150			*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 00 - NC  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 01 - NC  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 02 - BSC_M4_SCL(Tuner Slave)*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* SGPIO 03 - BSC_M4_SDA(Tuner Slave)*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_GPIO 00 - AUD0_SPDIF */
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_GPIO 01 - ENET_LINK */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 02 - NC  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 03 - STBY_KEY_IN  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 04 - AON_LED_POWER  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 05 - AON_LED_STBY  */
/*				160			*/
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 06 - WARM_#COLD ?? */
	HUMAX_GPIO_FUNCTION_ALT5,	/* AON_GPIO 07 - AON_GPIO_3461_SPI_MISO  */
	HUMAX_GPIO_FUNCTION_ALT5,	/* AON_GPIO 08 - AON_GPIO_3461B_SPI_SSB  */
	HUMAX_GPIO_FUNCTION_ALT5,	/* AON_GPIO 09 - AON_GPIO_3461_SPI_MOSI  */
	HUMAX_GPIO_FUNCTION_ALT2,	/* AON_GPIO 10 - SC_VCC_1 */
	HUMAX_GPIO_FUNCTION_ALT5,	/* AON_GPIO 11 - SPI_M_SCK */	
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 12 - VOL+_KEY  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 13 - CH+_KEY  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 14 - CH-_KEY  */
	HUMAX_GPIO_FUNCTION_ALT5,	/* AON_GPIO 15 - AON_GPIO_3461_SPI_SSB  */
/*				170			*/
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 16 - VOL-_KEY  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 17 - FLASH_WP_N */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 18 - AON_LED_ON  */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 19 - S3_DDR_RST  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 20 - S3_HDMI_CEC  */
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_SGPIO 00 - BSC_M0_SCL(Tuner Master)*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_SGPIO 01 - BSC_M0_SDA(Tuner Master)*/ 
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_SGPIO 02 - NC  */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_SGPIO 03 - NC */
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_SGPIO 04 - HDMI_M2_SCL(HDMI)*/ 
/*				180			*/
	HUMAX_GPIO_FUNCTION_ALT1	/* AON_SGPIO 05 - HDMI_M2_SDA(HDMI)*/
};

HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
/*	00	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_000_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_000_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_001_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_001_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_002_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_002_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_003_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_003_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_004_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_004_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_005_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_005_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_006_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_006_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_007_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_007_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_008_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_008_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_009_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_009_SHIFT},
/*	10	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_010_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_010_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_011_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_011_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_012_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_012_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_013_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_013_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_014_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_014_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_015_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_015_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_016_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_016_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_017_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_017_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_018_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_018_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_019_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_019_SHIFT},
/*	20	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_020_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_020_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_021_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_021_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_022_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_022_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_023_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_023_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_024_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_024_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_025_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_025_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_026_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_026_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_027_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_027_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_028_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_028_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_029_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_029_SHIFT},
/*	30	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_030_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_030_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_031_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_031_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_032_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_032_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_033_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_033_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_034_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_034_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_035_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_035_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_036_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_036_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_037_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_037_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_038_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_038_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_039_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_039_SHIFT},
/*	40	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_040_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_040_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_041_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_041_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_042_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_042_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_043_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_043_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_044_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_044_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_045_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_045_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_046_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_046_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_047_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_047_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_048_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_048_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_049_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_049_SHIFT},
/*	50	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_050_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_050_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_051_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_051_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_052_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_052_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_053_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_053_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_054_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_054_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_055_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_055_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_056_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_056_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_057_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_057_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_058_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_058_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_059_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_059_SHIFT},
/*	60	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_060_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_060_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_061_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_061_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_062_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_062_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_063_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_063_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_064_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_064_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_065_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_065_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_066_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_066_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_067_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_067_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_068_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_068_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_069_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_069_SHIFT},
/*	70	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_070_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_070_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_071_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_071_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_072_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_072_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_073_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_073_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_074_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_074_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_075_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_075_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_076_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_076_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_077_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_077_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_078_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_078_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_079_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_079_SHIFT},
/*	80	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_080_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_080_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_081_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_081_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_082_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_082_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_083_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_083_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_084_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_084_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_085_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_085_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_086_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_086_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_087_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_087_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_088_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_088_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_089_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_089_SHIFT},
/*	90	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_090_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_090_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_091_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_091_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_092_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_092_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_093_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_093_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_094_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_094_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_095_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_095_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_096_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_096_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_097_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_097_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_098_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_098_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_099_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_099_SHIFT},
/*	100	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, 0, 0},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_101_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_101_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_102_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_102_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_103_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_103_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_104_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_104_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_105_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_105_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_106_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_106_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_107_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_107_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_108_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_108_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_109_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_109_SHIFT},
/*	110	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_110_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_110_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_111_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_111_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_112_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_112_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_113_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_113_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_114_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_114_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, 0, 0},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_116_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_116_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_117_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_117_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_118_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_118_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, 0, 0},
/*	120	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, 0, 0},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, 0, 0},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_122_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_122_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_123_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_123_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_124_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_124_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_125_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_125_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_126_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_126_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_127_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_127_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_128_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_128_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_129_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_129_SHIFT},
/*	130	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_130_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_130_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_131_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_131_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_132_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_132_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_133_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_133_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_134_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_134_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_135_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_135_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_136_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_136_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_137_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_137_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_138_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_138_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_139_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_139_SHIFT},
/*	140	*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_140_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_16_gpio_140_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_141_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_141_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_142_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_142_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_143_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_143_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_144_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_144_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_145_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_145_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_146_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_146_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_147_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_147_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_148_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_17_gpio_148_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_149_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_gpio_149_SHIFT},
/*	Number of GPIOs 145 = 150 - 5(100, 115, 119, 120, 121)	*/

/*	150	*/

/* SGPIO */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_00_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_01_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_02_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_18_sgpio_03_SHIFT},
/*	Number of SGPIOs 4	*/

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT},
/*	160	*/	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
/*	AON GPIO 10	*/
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT},
	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_14_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_SHIFT},
/*	170 */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_SHIFT},
/*	 Number of AON GPIOs 21	*/

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},
	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_01_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_02_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_04_SHIFT},
/*	180	*/
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_05_SHIFT}
/*	Number of AON SGPIOs 6	*/
	
};

