#ifndef __HUMAX_I2C_BUS_INDEX_H__
#define __HUMAX_I2C_BUS_INDEX_H__

#if defined(CONFIG_I2C_MAP_FOR_2TUNER)
#define I2C_CHANNEL_CHANNEL		1
#define I2C_CHANNEL_CHANNEL2	-1
#define I2C_CHANNEL_HDMI		0
#else
#define I2C_CHANNEL_CHANNEL		1
#define I2C_CHANNEL_HDMI		0
#endif
#endif
