obj-y += apk_main.o
obj-y += apk_event.o
obj-y += apk_datastreamer.o
obj-y += media/
obj-y += builder/
obj-y += resource/
obj-y += meta/
obj-y += output/
obj-y += filemgr/
obj-y += extdev/
obj-y += sysinfo/
obj-y += scenario/
obj-y += exe/
obj-y += cas/
obj-y += db/
obj-y += power/
obj-y += swupdate/
obj-y += dsmcc/
obj-y += dlna/
obj-y += airplay/
obj-y += network/
obj-y += drmagent/
obj-y += download/

# APPKIT v2 local include path
ccflags-y += -I$(OCTOTOP_SRC_DIR)/appkit/local_include

