obj-y += nx_prism_dialogue_msg.o
obj-y += nx_prism_dialogue_no_service.o
obj-y += nx_prism_not_available.o
obj-y += nx_prism_dialogue_rsv_noti.o
obj-y += nx_prism_dialogue_rsv_conflict.o

obj-$(CONFIG_MW_MM_PVR) += nx_prism_response_record_start.o
obj-$(CONFIG_MW_MM_PVR) += nx_prism_response_record_stop.o

# Additional include path
ccflags-y += -I../../../../../../../make/include


