#ifndef __xmgr_cas_NaSMART_INFO_COORDINATE_H__
#define __xmgr_cas_NaSMART_INFO_COORDINATE_H__

#include <settings.h>
#include <util_dslib.h>

#define	CAS_NA_SC_INFO_APP_WINDOW_WIDTH		OSD_SCREEN_WIDTH
#define	CAS_NA_SC_INFO_APP_WINDOW_HEIGHT	OSD_SCREEN_HEIGHT
#define	CAS_NA_SC_INFO_APP_WINDOW_X			0
#define	CAS_NA_SC_INFO_APP_WINDOW_Y			0

#define NASCINFO_CARD_STATUS_ID			(eMenuFrame_Window_SystemStatus + 0x0001)

#define	NASCINFO_ITEM_LINESPACE			48

#define	NASCINFO_CURSOR_X					250
#define	NASCINFO_CURSOR_W				640

#define	NASCINFO_CURSOR_Y1				145
#define	NASCINFO_CURSOR_Y2				(NASCINFO_CURSOR_Y1 + NASCINFO_ITEM_LINESPACE)
#define	NASCINFO_CURSOR_Y3				(NASCINFO_CURSOR_Y2 + NASCINFO_ITEM_LINESPACE)
#define	NASCINFO_CURSOR_Y4				(NASCINFO_CURSOR_Y3 + NASCINFO_ITEM_LINESPACE)
#define	NASCINFO_CURSOR_Y5				(NASCINFO_CURSOR_Y4 + NASCINFO_ITEM_LINESPACE)
#define	NASCINFO_CURSOR_Y6				(NASCINFO_CURSOR_Y5 + NASCINFO_ITEM_LINESPACE)
#define	NASCINFO_CURSOR_Y7				(NASCINFO_CURSOR_Y6 + NASCINFO_ITEM_LINESPACE)
#define	NASCINFO_CURSOR_Y8				(NASCINFO_CURSOR_Y7 + NASCINFO_ITEM_LINESPACE)
#define	NASCINFO_CURSOR_Y9				(NASCINFO_CURSOR_Y8 + NASCINFO_ITEM_LINESPACE)
#define	NASCINFO_CURSOR_Y10				(NASCINFO_CURSOR_Y9 + NASCINFO_ITEM_LINESPACE)

#define	NASCINFO_CARD_STATUS_X			NASCINFO_CURSOR_X
#define	NASCINFO_CARD_STATUS_Y			(NASCINFO_CURSOR_Y7 + 5)
#define	NASCINFO_CARD_STATUS_W			NASCINFO_CURSOR_W
#define	NASCINFO_CARD_STATUS_H			(OSD_SCREEN_HEIGHT - NASCINFO_CARD_STATUS_Y)

#define	NASCINFO_CARD_MSG_ICON_W		55
#define	NASCINFO_CARD_MSG_ICON_H		50
#define	NASCINFO_CARD_MSG_ICON_X		189
#define	NASCINFO_CARD_MSG_ICON_Y		(NASCINFO_CARD_STATUS_Y + 3)

#define	NASCINFO_CARD_MSG_SCROLL_W		9
#define	NASCINFO_CARD_MSG_SCROLL_H		470
#define	NASCINFO_CARD_MSG_SCROLL_X		995
#define	NASCINFO_CARD_MSG_SCROLL_Y		NASCINFO_CURSOR_Y1

#if defined(CONFIG_MW_CAS_NAGRA_FEATURE_PPV)
#define NADCSYSSTAT_ITEM01_ID				(eMenuFrame_Window_SystemStatus + 0x0001)
#define NADCSYSSTAT_ITEM02_ID				(eMenuFrame_Window_SystemStatus + 0x0002)

typedef struct tag_CAS_NaList_content
{
	/* for drawing application window */
	HUINT32 		ulCurFocus;
	HUINT32 		ulNumOfSubItem, ulMaxNumOfSubItem;
	SettingsLeafSubItem_t	*subItems;

	/* running info for app */
	HUINT8			ucTitle[MAX_ELEMENT_TEXT_LENGTH];

	/* List Item */
	HBOOL			bDrawCursor;
	Custom_list_t		stTextListBox;
	GWM_ObjDraw_t	objDrawFunc;


} XmgrCas_NaListContent_t;
#endif

#endif /* __xmgr_cas_NaSMART_INFO_COORDINATE_H__ */

/* end of file */

