obj-y 									+= xmgr_cas_na_system_info.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_mset.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_pangea.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_mset_carderror.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_mset_cardinfo.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_mset_selprog.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_mset_rechar.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_mset_packpurc.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_pangea_carderror.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_pangea_cardinfo.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_pangea_prodcatal.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_pangea_purcprod.o
obj-$(CONFIG_MW_CAS_NAGRA_MEDIASET)		+= xmgr_cas_na_ppv_menu_pangea_rechar.o
obj-$(CONFIG_MW_CAS_NAGRA_TIVU)			+= xmgr_cas_na_ppv_menu_tivu_carderror.o
obj-$(CONFIG_MW_CAS_NAGRA_TIVU)			+= xmgr_cas_na_ppv_menu_tivu_cardinfo.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
ccflags-y += -I$(OCTO_DIR)/oapi/server/include

# Sub-CAS include path
