obj-$(CONFIG_OTA_DVBSSU)		+= dvb_ssu/
obj-$(CONFIG_OTA_ASTRA)			+= dvb_ssu/
obj-$(CONFIG_OTA_FSATSSU)		+= dvb_ssu/
obj-$(CONFIG_OTA_HUMAX)			+= dvb_ssu/
obj-$(CONFIG_OTA_SES)			+= dvb_ssu/
obj-$(CONFIG_OTA_DTT_EU)			+= dvb_ssu/
obj-$(CONFIG_OTA_DTT_UK)			+= dvb_ssu/
obj-$(CONFIG_OTA_AMX_CENAM)			+= dvb_ssu/

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

