-include ./dirs

ifeq ($(DIRS),)
TARGET = symoptstub

SOURCES =                \
	symoptdevicedevcertstub.c symoptlacqstub.c symoptlicstub.c symoptutilstub.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
