-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = licensecleanstore

DRM_MODULE_CFLAGS =

SOURCES =                \
	licensecleanstore.c 
	
endif	
   
include $(DRM_SOURCE_PATH)/default.mak
