obj-y += mgr_action.o
obj-y += mgr_action_api.o
obj-y += mgr_action_background_task.o
#bj-y += mgr_action_batch.o
obj-y += mgr_action_batch_new.o


# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr

# Additional include path
ccflags-y += -I$(OCTO_TVMANAGER_DIR)/include_plugin

