obj-y += oapi_exe.o

# ---- include path----
ccflags-y += -I$(HLIB_DIR)/include
ccflags-y += -I$(DLIB_DIR)/include
ccflags-y += -I$(OCTO_DIR)/include
ccflags-y += -I$(OCTO_DIR)/api/protocol
ccflags-y += -I$(OCTO_DIR)/main/oxserver/include


