-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = secureclockgetresponse

DRM_MODULE_CFLAGS =

SOURCES =                \
	 secureclockgetresponse.c
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
