obj-y += nx_prism_menu_channel.o
obj-y += nx_prism_menu_search_ui.o
obj-y += nx_prism_menu_signal.o
obj-y += nx_prism_menu_search_option.o
obj-y += nx_prism_menu_edit_chlist.o
obj-y += nx_prism_menu_search_setoption.o
obj-y += nx_prism_menu_edit_chlist_opt.o
obj-y += nx_prism_menu_fav_chlist.o
obj-y += nx_prism_menu_fav_chlist_opt.o

obj-$(CONFIG_MW_CH_SATELLITE) += nx_prism_menu_search_sat_fixed.o
obj-$(CONFIG_MW_CH_SATELLITE) += nx_prism_menu_search_sat_satsetting.o
obj-$(CONFIG_MW_CH_SATELLITE) += nx_prism_menu_search_sat_tpset.o
obj-$(CONFIG_MW_CH_SATELLITE) += nx_prism_menu_search_sat_scd.o
obj-$(CONFIG_MW_CH_SATELLITE) += nx_prism_menu_search_sat_scdsetting.o

# Additional include path
ccflags-y += -I../../../../../../../make/include

