obj-y += tir_api.o
obj-y += tir_nvr.o
obj-y += irldvt_ir_api.o
#obj-y += irldvt_ir_sup.o


# Additional include path
ccflags-y += -I./include

ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/pal/include
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/include
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/include/product
ccflags-y += -I$../../../../make/include

# Basic include path
