/***************************************************************************
*     (c)2008-2011 Broadcom Corporation
*  
*  This program is the proprietary software of Broadcom Corporation and/or its licensors,
*  and may only be used, duplicated, modified or distributed pursuant to the terms and
*  conditions of a separate, written license agreement executed between you and Broadcom
*  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
*  no license (express or implied), right to use, or waiver of any kind with respect to the
*  Software, and Broadcom expressly reserves all rights in and to the Software and all
*  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
*  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
*  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.  
*   
*  Except as expressly set forth in the Authorized License,
*   
*  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
*  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
*  and to use this information only in connection with your use of Broadcom integrated circuit products.
*   
*  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS" 
*  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR 
*  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO 
*  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES 
*  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, 
*  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION 
*  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF 
*  USE OR PERFORMANCE OF THE SOFTWARE.
*  
*  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS 
*  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR 
*  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR 
*  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF 
*  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT 
*  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE 
*  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF 
*  ANY LIMITED REMEDY.
* 
* $brcm_Workfile: nexus_gpio_table.c $
* $brcm_Revision: 4 $
* $brcm_Date: 1/14/11 9:37a $
*
* API Description:
*   API name: Gpio
*    Specific APIs related to Gpio Control.
*
* Revision History:
*
* $brcm_Log: /nexus/modules/gpio/7325/src/nexus_gpio_table.c $
* 
* 4   1/14/11 9:37a jrubio
* SW7408-146: add GetPinMux
* 
* 3   3/12/09 2:14p jgarrett
* PR 50409: Fixing holes in the interrupt table
* 
* 2   5/23/08 4:37p jrubio
* PR42692: update gpio for keypad
* 
* 1   3/4/08 4:46p jrubio
* PR40169: adding nexus gpio table
* 
***************************************************************************/
#include "nexus_gpio_module.h"
#include "bchp_sun_top_ctrl.h"
#include "bchp_gio.h"
#include "priv/nexus_core.h"

BDBG_MODULE(nexus_gpio_table);

typedef struct NEXUS_GpioTable
{
    uint32_t addr;
    unsigned mask;
    unsigned shift;
} NEXUS_GpioTable;

NEXUS_GpioTable g_gpioTable[NEXUS_NUM_GPIO_PINS] = {
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_00_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_01_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_02_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_03_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_04_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_05_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_06_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_06_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_07_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_07_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_08_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_08_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_09_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_09_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_10_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_10_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_11_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_11_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_12_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_12_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_13_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_13_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_14_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_14_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_15_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_15_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_16_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_16_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_17_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_17_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_18_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_18_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_19_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_19_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_20_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_20_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_21_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_21_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_22_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_22_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_23_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_23_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_24_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_24_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_25_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_25_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_26_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_26_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_27_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_27_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_28_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_28_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_29_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_29_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_30_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_30_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_31_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_31_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_32_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_32_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_33_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_33_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_34_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_34_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_35_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_35_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_36_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_36_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_37_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_37_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_38_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_38_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_39_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_39_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_40_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_40_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_41_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_41_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_42_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_42_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_43_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_43_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_44_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_44_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_45_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_45_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_46_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_46_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_47_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_47_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_48_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_48_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_49_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_49_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_50_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_50_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_51_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_51_SHIFT},
    /* Odd that this is in _9... */
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_52_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_52_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_53_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_53_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_54_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_54_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_55_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_55_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_56_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_56_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_57_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_57_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_58_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_58_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_59_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_59_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_60_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_60_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_61_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_61_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_62_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_62_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_63_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_63_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_64_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_64_SHIFT}, 
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_65_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_65_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_66_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_66_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_67_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_67_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_68_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_68_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_69_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_69_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_70_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_70_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_72_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_73_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_74_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_75_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_76_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_77_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_77_SHIFT},
};

NEXUS_GpioTable g_sgpioTable[NEXUS_NUM_SGPIO_PINS] = {
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_00_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_01_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_02_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_03_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_04_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_05_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_06_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_06_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_07_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_07_SHIFT}
};

/* These functions must be implemented per-chip */
NEXUS_Error NEXUS_Gpio_P_GetPinMux(NEXUS_GpioType type, unsigned pin, uint32_t *pAddr, uint32_t *pMask, unsigned *pShift )
{
    NEXUS_GpioTable *pEntry=NULL;
    if ( type == NEXUS_GpioType_eSpecial ) {
        if ( pin >= NEXUS_NUM_SGPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        pEntry = g_sgpioTable+pin;
    }
    else if ( type == NEXUS_GpioType_eStandard ) {
        if ( pin >= NEXUS_NUM_GPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        pEntry = g_gpioTable+pin;
    }
    else {
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }
    *pAddr = pEntry->addr;
    *pMask = pEntry->mask;
    *pShift = pEntry->shift;
    return 0;
}

NEXUS_Error NEXUS_Gpio_P_CheckPinmux(NEXUS_GpioType type, unsigned pin)
{
    NEXUS_GpioTable *pEntry=NULL;
    uint32_t val;

    BDBG_ASSERT(type < NEXUS_GpioType_eMax);

    if ( type == NEXUS_GpioType_eSpecial )
    {
        if ( pin >= NEXUS_NUM_SGPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        pEntry = g_sgpioTable+pin;
    }
    else
    {
        if ( pin >= NEXUS_NUM_GPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        pEntry = g_gpioTable+pin;
    }

    val = BREG_Read32(g_pCoreHandles->reg, pEntry->addr);
    if ( val & pEntry->mask )
    {
        /* Pin is not configured as GPIO */
        BDBG_ERR(("Pin mux register for %s %u is not properly configured - value %u should be 0",
                  (type == NEXUS_GpioType_eSpecial)?"sgpio":"gpio", pin, (val&pEntry->mask)>>pEntry->shift));
        return BERR_TRACE(BERR_INVALID_PARAMETER);
    }

    return BERR_SUCCESS;
}

NEXUS_Error NEXUS_Gpio_P_GetPinData(NEXUS_GpioType type, unsigned pin, uint32_t *pAddress, uint32_t *pShift)
{
    BDBG_ASSERT(type < NEXUS_GpioType_eMax);

    if ( type == NEXUS_GpioType_eSpecial )
    {
        if ( pin >= NEXUS_NUM_SGPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        else
        {
            *pAddress = BCHP_GIO_ODEN_EXT;
            *pShift = pin;
        }
    }
    else
    {
        if ( pin >= NEXUS_NUM_GPIO_PINS )
        {
            return BERR_TRACE(BERR_INVALID_PARAMETER);
        }
        else if ( pin < 32 )
        {
            *pAddress = BCHP_GIO_ODEN_LO;
            *pShift = pin;
        }
        else if ( pin < 64 )
        {
            *pAddress = BCHP_GIO_ODEN_HI;
            *pShift = pin-32;
        }
        else if ( pin < 88 )
        {
            /* Pins 85..64 are located in EXT, above sgpio bits */
            *pAddress = BCHP_GIO_ODEN_EXT;
            *pShift = (pin-64)+NEXUS_NUM_SGPIO_PINS;
        }
#ifdef  BCHP_GIO_ODEN_EXT_HI/* Waiting for Correct Headers */
        else
        {
            /* Pins 112..88 are in EXT_HI */
            *pAddress = BCHP_GIO_ODEN_EXT_HI;
            *pShift = (pin-86);
        }
#endif
    }

    return BERR_SUCCESS;
}

