obj-y += vmx_vr_iptvh_mgr.o
obj-y += vmx_vr_iptvh_api.o
#obj-y += model/

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
