/******************************************************************************
*    (c)2011-2013 Broadcom Corporation
*
* This program is the proprietary software of Broadcom Corporation and/or its licensors,
* and may only be used, duplicated, modified or distributed pursuant to the terms and
* conditions of a separate, written license agreement executed between you and Broadcom
* (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
* no license (express or implied), right to use, or waiver of any kind with respect to the
* Software, and Broadcom expressly reserves all rights in and to the Software and all
* intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
* HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
* NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
*
* Except as expressly set forth in the Authorized License,
*
* 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
* secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
* and to use this information only in connection with your use of Broadcom integrated circuit products.
*
* 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
* AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
* WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
* THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
* OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
* LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
* OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
* USE OR PERFORMANCE OF THE SOFTWARE.
*
* 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
* LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
* EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
* USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
* THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
* ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
* LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
* ANY LIMITED REMEDY.
*
* $brcm_Workfile: $
* $brcm_Revision: $
* $brcm_Date: $
*
* Module Description:
*
* Revision History:
*
* $brcm_Log: $
* 
*****************************************************************************/
#ifndef _BSAT_7366_INTR_H_
#define _BSAT_7366_INTR_H_

#include "bchp_leap_l1.h"
#include "bchp_sds_intr2_0_0.h"
#include "bchp_sds_intr2_0_1.h"
#include "bchp_sds_intr2_0_2.h"
#include "bchp_sds_intr2_0_3.h"
#include "bchp_sds_intr2_0_4.h"
#include "bchp_sds_intr2_0_5.h"
#include "bchp_sds_intr2_0_6.h"
#include "bchp_sds_intr2_0_7.h"
#include "bchp_afec0_intr_0.h"
#include "bchp_afec1_intr_0.h"
#include "bchp_afec0_intr_1.h"
#include "bchp_afec1_intr_1.h"
#include "bchp_afec0_intr_2.h"
#include "bchp_afec1_intr_2.h"
#include "bchp_afec0_intr_3.h"
#include "bchp_afec1_intr_3.h"
#include "bchp_tfec_intr2_0.h"
#include "bchp_tfec_intr2_1.h"
#include "bchp_tfec_intr2_2.h"
#include "bchp_tfec_intr2_3.h"
#include "bchp_tfec_intr2_4.h"
#include "bchp_tfec_intr2_5.h"
#include "bchp_tfec_intr2_6.h"
#include "bchp_tfec_intr2_7.h"


#ifdef LEAP_ARC

/* Interrupt IDs for BSAT PI running on LEAP */
/* Channel 0 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_0               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_0           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_0                BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_0               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_0             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_0             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_0             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_0                   BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_0      BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_0     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_0    BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_0           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 1 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_1               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_1           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_1                BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_1               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_1             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_1             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_1             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_1                   BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_1      BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_1     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_1    BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_1           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 2 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_2               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_2           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_2                BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_2               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_2             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_2             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_2             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_2                   BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_2      BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_2     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_2    BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_2           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 3 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_3               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_3           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_3                BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_3               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_3             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_3             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_3             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_3                   BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_3      BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_3     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_3    BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_3           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 4 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_4               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_4           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_4                BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_4               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_4             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_4             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_4             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_4                   BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_4      BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_4     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_4    BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_4           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 5 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_5               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_5           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_5                BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_5               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_5             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_5             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_5             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_5                   BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_5      BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_5     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_5    BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_5           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 6 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_6               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_6           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_6                BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_6               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_6             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_6             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_6             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_6                   BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_6      BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_6     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_6    BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_6           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 7 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_7               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_7           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_7                BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_7               BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_7             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_7             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_7             BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_7                   BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_7      BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_7     BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_7    BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_7           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* AFEC interrupts */
#define BCHP_INT_ID_AFEC_LOCK_0              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_0          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_0           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W1_STATUS_AFEC0_0_INTR_SHIFT+32, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_0       BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W1_STATUS_AFEC0_0_INTR_SHIFT+32, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_1              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_1          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS0_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_1           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC0_1_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_1       BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC0_1_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_2              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_2          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_2           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC1_0_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_2       BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC1_0_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_3              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_3          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS1_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_3           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC1_1_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_3       BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC1_1_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_4              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_4          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_4           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC2_0_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_4       BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC2_0_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_5              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_5          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS2_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_5           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC2_1_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_5       BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC2_1_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_6              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_6          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_0_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_6           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC3_0_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_6       BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC3_0_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_7              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_7          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_SDS3_1_INTR_SHIFT, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_7           BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC3_1_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_7       BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_AFEC3_1_INTR_SHIFT, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)

/* TFEC interrupts */
#define BCHP_INT_ID_TFEC_LOCK_0              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC0_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_0          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC0_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_0              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC0_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_1              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC0_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_1          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC0_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_1              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC0_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_2              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC1_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_2          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC1_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_2              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC1_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_3              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC1_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_3          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC1_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_3              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC1_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_4              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC2_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_4          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC2_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_4              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC2_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_5              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC2_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_5          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC2_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_5              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC2_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_6              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC3_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_6          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC3_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_6              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC3_0_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_7              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC3_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_7          BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC3_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_7              BINT_LEAP_INT_ID_CREATE(BCHP_LEAP_L1_INTR_W0_STATUS_TFEC3_1_INTR_SHIFT, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)

#else

/* Interrupt IDs for BSAT PI running on ARM */
/* Channel 0 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_0               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_0           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_0                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_0               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_0             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_0             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_0             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_0                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_0      BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_0     BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_0    BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_0           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 1 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_1               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_1           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_1                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_1               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_1             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_1             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_1             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_1                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_1      BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_1     BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_1    BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_1           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 2 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_2               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_2           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_2                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_2               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_2             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_2             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_2             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_2                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_2      BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_2     BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_2    BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_2           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 3 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_3               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_3           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_3                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_3               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_3             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_3             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_3             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_3                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_3      BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_3     BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_3    BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_3           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 4 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_4               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_4           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_4                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_4               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_4             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_4             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_4             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_4                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_4      BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_4     BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_4    BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_4           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 5 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_5               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_5           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_5                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_5               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_5             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_5             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_5             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_5                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_5      BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_5     BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_5    BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_5           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 6 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_6               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_6           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_6                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_6               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_6             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_6             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_6             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_6                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_6      BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_6     BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_6    BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_6           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* Channel 7 SDS interrupts */
#define BCHP_INT_ID_SDS_LOCK_7               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_in_lock_SHIFT)
#define BCHP_INT_ID_SDS_NOT_LOCK_7           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_rvb_out_lock_SHIFT)
#define BCHP_INT_ID_SDS_BTM_7                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bclktimer_int_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_7               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_bertimer_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM1_7             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer1_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM2_7             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer2_int_SHIFT)
#define BCHP_INT_ID_SDS_GENTM3_7             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_gentimer3_int_SHIFT)
#define BCHP_INT_ID_MI2C_7                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_mi2c_int_SHIFT)
#define BCHP_INT_ID_HP_FRAME_BOUNDARY_7      BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_frame_boundary_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_MATCH_7     BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_match_SHIFT)
#define BCHP_INT_ID_SDS_HP_STATE_CHANGE_7    BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_hp_state_change_SHIFT)
#define BCHP_INT_ID_SDS_DFT_DONE_7           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_dft_done_int_SHIFT)

/* AFEC interrupts */
#define BCHP_INT_ID_AFEC_LOCK_0              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_0          BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_0           BCHP_INT_ID_CREATE(BCHP_AFEC0_INTR_0_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_0       BCHP_INT_ID_CREATE(BCHP_AFEC0_INTR_0_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_1              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_1          BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_1           BCHP_INT_ID_CREATE(BCHP_AFEC1_INTR_0_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_1       BCHP_INT_ID_CREATE(BCHP_AFEC1_INTR_0_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_2              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_2          BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_2_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_2           BCHP_INT_ID_CREATE(BCHP_AFEC0_INTR_1_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_2       BCHP_INT_ID_CREATE(BCHP_AFEC0_INTR_1_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_3              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_3          BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_3_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_3           BCHP_INT_ID_CREATE(BCHP_AFEC1_INTR_1_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_3       BCHP_INT_ID_CREATE(BCHP_AFEC1_INTR_1_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_4              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_4          BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_4_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_4           BCHP_INT_ID_CREATE(BCHP_AFEC0_INTR_2_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_4       BCHP_INT_ID_CREATE(BCHP_AFEC0_INTR_2_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_5              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_5          BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_5_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_5           BCHP_INT_ID_CREATE(BCHP_AFEC1_INTR_2_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_5       BCHP_INT_ID_CREATE(BCHP_AFEC1_INTR_2_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_6              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_6          BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_6_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_6           BCHP_INT_ID_CREATE(BCHP_AFEC0_INTR_3_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_6       BCHP_INT_ID_CREATE(BCHP_AFEC0_INTR_3_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_LOCK_7              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_in_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_7          BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_7_CPU_STATUS, BCHP_SDS_INTR2_0_0_CPU_STATUS_ahb_out_lock_SHIFT)
#define BCHP_INT_ID_AFEC_MP_LOCK_7           BCHP_INT_ID_CREATE(BCHP_AFEC1_INTR_3_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_INTR_SHIFT)
#define BCHP_INT_ID_AFEC_MP_NOT_LOCK_7       BCHP_INT_ID_CREATE(BCHP_AFEC1_INTR_3_CPU_STATUS, BCHP_AFEC0_INTR_0_CPU_STATUS_MP_LOCK_NEG_INTR_SHIFT)

/* TFEC interrupts */
#define BCHP_INT_ID_TFEC_LOCK_0              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_0_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_0          BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_0_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_0              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_0_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_1              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_1_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_1          BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_1_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_1              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_1_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_2              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_2_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_2          BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_2_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_2              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_2_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_3              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_3_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_3          BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_3_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_3              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_3_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_4              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_4_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_4          BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_4_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_4              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_4_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_5              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_5_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_5          BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_5_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_5              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_5_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_6              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_6_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_6          BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_6_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_6              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_6_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_LOCK_7              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_7_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TIL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_NOT_LOCK_7          BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_7_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TOL_INTR_SHIFT)
#define BCHP_INT_ID_TFEC_SYNC_7              BCHP_INT_ID_CREATE(BCHP_TFEC_INTR2_7_CPU_STATUS, BCHP_TFEC_INTR2_0_CPU_STATUS_TRIL_INTR_SHIFT)

#endif

#endif /* _BSAT_7366_INTR_H_ */

