obj-y += irdeto/
obj-y += pal/

obj-y += ldvtmain.o
obj-y += dvtapp.o
obj-y += environment.o
obj-y += irldvt_output.o
obj-y += get_enum_str.o


# Additional include path
ccflags-y += -I./irdeto/include
ccflags-y += -I./glib
ccflags-y += -I./glib/include
ccflags-y += -I./pal
ccflags-y += -I./pal/include
#ccflags-y += -I./output/include
#ccflags-y += -I./ondk/include


# Basic include path
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/pal/include
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/include
ccflags-y += -I../../../make/include
#ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/output/include


# Additional include path

