obj-y 						+= base/

obj-y += xsvc_logcapture.o
obj-y += psvc_logcapture.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

