obj-y += common/
obj-y += context/
obj-y += database/
obj-y += eit/
obj-y += rawmgr/
obj-y += epg3g/

obj-y += svc_epg_api.o
obj-y += svc_epg.o
obj-$(CONFIG_DEBUG) += svc_epg_cmd.o


# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw

# Additional include path

