/***************************************************************************
 *     Copyright (c) 2007-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bast_7335_priv.h $
 * $brcm_Revision: Hydra_Software_Devel/45 $
 * $brcm_Date: 10/15/12 4:07p $
 *
 * [File Description:]
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/portinginterface/ast/src/g2/7335/bast_7335_priv.h $
 * 
 * Hydra_Software_Devel/45   10/15/12 4:07p enavarro
 * SWSATFE-220: add implementation for BAST_GetVersionInfo()
 * 
 * Hydra_Software_Devel/44   9/6/12 6:23p ronchan
 * SWSATFE-214: rename 73xx to g2
 * 
 * Hydra_Software_Devel/43   7/11/12 9:43a ronchan
 * SW7335-36: incremented code version to 0x26
 * 
 * Hydra_Software_Devel/42   6/5/12 11:10a ronchan
 * SW7335-36: incremented code version to 0x25
 * 
 * Hydra_Software_Devel/41   4/4/12 11:50a ronchan
 * SW7335-36: Incremented code version to 0x24
 * 
 * Hydra_Software_Devel/40   3/14/12 10:49a ronchan
 * SW7335-36: Incremented code version to 0x23
 * 
 * Hydra_Software_Devel/39   1/5/12 10:25a enavarro
 * SW7335-36: Incremented code version to 0x22
 * 
 * Hydra_Software_Devel/38   10/31/11 11:10a ronchan
 * SW7335-36: Incremented code version to 0x21
 * 
 * Hydra_Software_Devel/37   3/18/11 3:06p ronchan
 * SW7335-36: Incremented code version to 0x20
 * 
 * Hydra_Software_Devel/36   1/28/11 11:47a ronchan
 * SW7335-36: incremented code version to 0x19
 * 
 * Hydra_Software_Devel/34   9/29/10 2:07p ronchan
 * SW7335-36: incremented code version to 0x18
 * 
 * Hydra_Software_Devel/33   8/16/10 4:08p ronchan
 * SW7335-36: incremented code version to 0x17
 * 
 * Hydra_Software_Devel/32   3/24/10 10:53a ronchan
 * SW7335-36: incremented code version to 0x16
 * 
 * Hydra_Software_Devel/31   2/15/10 11:20a ronchan
 * SW7335-36: incremented code version to 0x15
 * 
 * Hydra_Software_Devel/30   1/25/10 3:30p ronchan
 * SW7335-36: incremented code version to 0x14
 * 
 * Hydra_Software_Devel/29   12/10/09 10:25a ronchan
 * SW7335-36: incremented code version to 0x13
 * 
 * Hydra_Software_Devel/28   11/12/09 2:49p ronchan
 * SW7335-36: incremented code version to 0x12
 * 
 * Hydra_Software_Devel/27   11/6/09 9:06p ronchan
 * SW7335-36: incremented code version to 0x11
 * 
 * Hydra_Software_Devel/26   10/29/09 11:34a ronchan
 * SW7335-36: incremented code version to 0x10
 * 
 * Hydra_Software_Devel/25   10/19/09 10:10a ronchan
 * SW7335-36: incremented code version to 0xF
 * 
 * Hydra_Software_Devel/24   9/24/09 5:29p ronchan
 * SW7335-36: incremented code version to 0xE
 * 
 * Hydra_Software_Devel/23   8/6/09 4:48p ronchan
 * PR 37881: incremented code version to 0xD
 * 
 * Hydra_Software_Devel/22   7/21/09 4:47p ronchan
 * PR 37881: use turbo interrupt shift definitions
 * 
 * Hydra_Software_Devel/21   7/7/09 2:33p ronchan
 * PR 37881: incremented code version to 0xC
 * 
 * Hydra_Software_Devel/20   6/3/09 10:01a ronchan
 * PR 37881: incremented code version to 0xB
 * 
 * Hydra_Software_Devel/19   3/23/09 3:29p ronchan
 * PR 37881: incremented code version to 0xA
 * 
 * Hydra_Software_Devel/18   2/23/09 10:33a ronchan
 * PR 37881: incremented code version to 0x9
 * 
 * Hydra_Software_Devel/17   1/31/09 1:32a jrubio
 * PR51629: fix 7336 support
 * 
 * Hydra_Software_Devel/16   1/28/09 11:47a ronchan
 * PR 37881: incremented code version to 0x8
 * 
 * Hydra_Software_Devel/15   1/12/09 2:13p ronchan
 * PR 37881: incremented code version to 0x7
 * 
 * Hydra_Software_Devel/14   12/17/08 10:57a ronchan
 * PR 37881: incremented code version to 0x6
 * 
 * Hydra_Software_Devel/13   11/24/08 3:41p ronchan
 * PR 37881: incremented code version to 0x5
 * 
 * Hydra_Software_Devel/11   10/15/08 11:33a ronchan
 * PR 37881: incremented code version to 0x4
 * 
 * Hydra_Software_Devel/10   10/13/08 3:06p ronchan
 * PR 37881: removed config version
 * 
 * Hydra_Software_Devel/9   9/24/08 9:52a ronchan
 * PR 37881: incremented code version to 0x3
 * 
 * Hydra_Software_Devel/8   8/29/08 10:08a ronchan
 * PR 37881: incremented code version
 * 
 * Hydra_Software_Devel/7   7/23/08 4:55p ronchan
 * PR 37881: added new B0 registers
 * 
 * Hydra_Software_Devel/6   4/28/08 2:27p ronchan
 * PR 37881: added vsense interrupts
 * 
 * Hydra_Software_Devel/5   3/14/08 2:37p ronchan
 * PR 37881: set AFEC lock irqs to be mpeg lock irqs
 * 
 * Hydra_Software_Devel/4   12/14/07 1:25p ronchan
 * PR 37881: added tuner dac div ratio
 * 
 * Hydra_Software_Devel/3   12/13/07 5:51p ronchan
 * PR 37881: fixed interrupt ids
 * 
 * Hydra_Software_Devel/2   12/6/07 4:03p ronchan
 * PR 37881: added afec register abstraction
 * 
 * Hydra_Software_Devel/1   12/4/07 3:54p enavarro
 * PR 37881: initial version
 *
 ***************************************************************************/
#ifndef _BAST_7335_PRIV_H__
#define _BAST_7335_PRIV_H__ 

#include "bchp_sds_0.h"
#include "bchp_sds_intr2_0_0.h"
#include "bchp_sds_intr2_0_1.h"
#include "bchp_tuner_0.h"
#include "bchp_tfec_0.h"
#include "bchp_afec_0.h"
#include "bchp_grb_0.h"
#include "bchp_sds_1.h"
#include "bchp_sds_intr2_1_0.h"
#include "bchp_sds_intr2_1_1.h"
#include "bchp_tuner_1.h"
#include "bchp_qpsk.h"
#include "bchp_qpsk_intr2_0.h"
#include "bchp_qpsk_intr2_1.h"
#include "bchp_tfec_1.h"
#include "bchp_afec_1.h"
#include "bchp_grb_1.h"
#include "bchp_ftm_intr2.h"
#include "bchp_ftm_phy.h"
#include "bchp_ftm_uart.h"
#include "bchp_ftm_skit.h"


#define BAST_G2_MAX_CHANNELS 3
#define BAST_G2_XTAL_FREQ 54000000
#define BAST_G2_CHIP 0x7335
#define BAST_G2_BUILD_VERSION   0x27
#define BAST_G2_TUNER_DAC_DIV_RATIO 0x13

/* channel 0 interrupts */
#define BCHP_INT_ID_SDS_LOCK_IS_0               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_0_IRQSTS2_RVIL_IS_SHIFT + 8)
#define BCHP_INT_ID_SDS_NOT_LOCK_IS_0           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_0_IRQSTS2_RVOL_IS_SHIFT + 8)
#define BCHP_INT_ID_SDS_BTM_IS_0                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_0_IRQSTS1_BTM_IS_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_IS_0               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_0_IRQSTS1_BRTM_IS_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS1_0             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_0_IRQSTS5_GENTM_IS1_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS2_0             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_0_IRQSTS5_GENTM_IS2_SHIFT)
#define BCHP_INT_ID_SDS_XTLTM_IS_0              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_0_IRQSTS5_XTLTM_IS_SHIFT)
#define BCHP_INT_ID_SDS_if_agc_le_thresh_rise_0 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_0_IRQMSK5_if_agc_le_thresh_rise_SHIFT)
#define BCHP_INT_ID_SDS_if_agc_le_thresh_fall_0 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_0_IRQMSK5_if_agc_le_thresh_fall_SHIFT)
#define BCHP_INT_ID_SDS_rf_agc_le_thresh_rise_0 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_0_IRQMSK5_rf_agc_le_thresh_rise_SHIFT)
#define BCHP_INT_ID_SDS_rf_agc_le_thresh_fall_0 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_0_IRQMSK5_rf_agc_le_thresh_fall_SHIFT)
#define BCHP_INT_ID_SDS_rf_agc_gt_max_change_0  BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_0_IRQMSK5_rf_agc_gt_max_change_SHIFT)
#define BCHP_INT_ID_SDS_sar_vol_gt_hi_thrsh_0   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_0_IRQSTS5_sar_vol_gt_hi_thrsh_SHIFT)
#define BCHP_INT_ID_SDS_sar_vol_lt_lo_thrsh_0   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_0_CPU_STATUS, BCHP_SDS_0_IRQSTS5_sar_vol_lt_lo_thrsh_SHIFT)
#define BCHP_INT_ID_DSDN_IS_0                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_0_IRQSTS1_DSDN_IS_SHIFT)
#define BCHP_INT_ID_SDS_HP_IS_0                 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_0_IRQSTS2_HP_IS_SHIFT + 8)
#define BCHP_INT_ID_MI2C_IS_0                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_0_IRQSTS1_MIC_IS_SHIFT)
#define BCHP_INT_ID_TURBO_LOCK_IS_0             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_0_IRQSTS3_TIL_IS_SHIFT + 16)
#define BCHP_INT_ID_TURBO_NOT_LOCK_IS_0         BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_0_CPU_STATUS, BCHP_SDS_0_IRQSTS3_TOL_IS_SHIFT + 16)
#define BCHP_INT_ID_AFEC_LOCK_IS_0              BCHP_INT_ID_CREATE(BCHP_AFEC_0_uP_IRQ_STAT, BCHP_AFEC_0_uP_IRQ_STAT_uP_mp_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_IS_0          BCHP_INT_ID_CREATE(BCHP_AFEC_0_uP_IRQ_STAT, BCHP_AFEC_0_uP_IRQ_STAT_uP_mp_lock_edge_SHIFT)


/* channel 1 interrupts */
#define BCHP_INT_ID_SDS_LOCK_IS_1               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_0_IRQSTS2_RVIL_IS_SHIFT + 8)
#define BCHP_INT_ID_SDS_NOT_LOCK_IS_1           BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_0_IRQSTS2_RVOL_IS_SHIFT + 8)
#define BCHP_INT_ID_SDS_BTM_IS_1                BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_0_IRQSTS1_BTM_IS_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_IS_1               BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_0_IRQSTS1_BRTM_IS_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS1_1             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_0_IRQSTS5_GENTM_IS1_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS2_1             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_0_IRQSTS5_GENTM_IS2_SHIFT)
#define BCHP_INT_ID_SDS_XTLTM_IS_1              BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_0_IRQSTS5_XTLTM_IS_SHIFT)
#define BCHP_INT_ID_SDS_if_agc_le_thresh_rise_1 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_0_IRQMSK5_if_agc_le_thresh_rise_SHIFT)
#define BCHP_INT_ID_SDS_if_agc_le_thresh_fall_1 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_0_IRQMSK5_if_agc_le_thresh_fall_SHIFT)
#define BCHP_INT_ID_SDS_rf_agc_le_thresh_rise_1 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_0_IRQMSK5_rf_agc_le_thresh_rise_SHIFT)
#define BCHP_INT_ID_SDS_rf_agc_le_thresh_fall_1 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_0_IRQMSK5_rf_agc_le_thresh_fall_SHIFT)
#define BCHP_INT_ID_SDS_rf_agc_gt_max_change_1  BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_0_IRQMSK5_rf_agc_gt_max_change_SHIFT)
#define BCHP_INT_ID_SDS_sar_vol_gt_hi_thrsh_1   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_0_IRQSTS5_sar_vol_gt_hi_thrsh_SHIFT)
#define BCHP_INT_ID_SDS_sar_vol_lt_lo_thrsh_1   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_1_1_CPU_STATUS, BCHP_SDS_0_IRQSTS5_sar_vol_lt_lo_thrsh_SHIFT)
#define BCHP_INT_ID_DSDN_IS_1                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_0_IRQSTS1_DSDN_IS_SHIFT)
#define BCHP_INT_ID_SDS_HP_IS_1                 BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_0_IRQSTS2_HP_IS_SHIFT + 8)
#define BCHP_INT_ID_MI2C_IS_1                   BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_0_IRQSTS1_MIC_IS_SHIFT)
#define BCHP_INT_ID_TURBO_LOCK_IS_1             BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_0_IRQSTS3_TIL_IS_SHIFT + 16)
#define BCHP_INT_ID_TURBO_NOT_LOCK_IS_1         BCHP_INT_ID_CREATE(BCHP_SDS_INTR2_0_1_CPU_STATUS, BCHP_SDS_0_IRQSTS3_TOL_IS_SHIFT + 16)
#define BCHP_INT_ID_AFEC_LOCK_IS_1              BCHP_INT_ID_CREATE(BCHP_AFEC_1_uP_IRQ_STAT, BCHP_AFEC_0_uP_IRQ_STAT_uP_mp_lock_SHIFT)
#define BCHP_INT_ID_AFEC_NOT_LOCK_IS_1          BCHP_INT_ID_CREATE(BCHP_AFEC_1_uP_IRQ_STAT, BCHP_AFEC_0_uP_IRQ_STAT_uP_mp_lock_edge_SHIFT)

/* channel 2 interrupts */
#define BCHP_INT_ID_SDS_LOCK_IS_2               BCHP_INT_ID_CREATE(BCHP_QPSK_INTR2_0_CPU_STATUS, BCHP_SDS_0_IRQSTS2_RVIL_IS_SHIFT + 8)
#define BCHP_INT_ID_SDS_NOT_LOCK_IS_2           BCHP_INT_ID_CREATE(BCHP_QPSK_INTR2_0_CPU_STATUS, BCHP_SDS_0_IRQSTS2_RVOL_IS_SHIFT + 8)
#define BCHP_INT_ID_SDS_BTM_IS_2                BCHP_INT_ID_CREATE(BCHP_QPSK_INTR2_0_CPU_STATUS, BCHP_SDS_0_IRQSTS1_BTM_IS_SHIFT)
#define BCHP_INT_ID_SDS_BRTM_IS_2               BCHP_INT_ID_CREATE(BCHP_QPSK_INTR2_0_CPU_STATUS, BCHP_SDS_0_IRQSTS1_BRTM_IS_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS1_2             BCHP_INT_ID_CREATE(BCHP_QPSK_INTR2_1_CPU_STATUS, BCHP_SDS_0_IRQSTS5_GENTM_IS1_SHIFT)
#define BCHP_INT_ID_SDS_GENTM_IS2_2             BCHP_INT_ID_CREATE(BCHP_QPSK_INTR2_1_CPU_STATUS, BCHP_SDS_0_IRQSTS5_GENTM_IS2_SHIFT)
#define BCHP_INT_ID_SDS_XTLTM_IS_2              BCHP_INT_ID_CREATE(BCHP_QPSK_INTR2_1_CPU_STATUS, BCHP_SDS_0_IRQSTS5_XTLTM_IS_SHIFT)
#define BCHP_INT_ID_MI2C_IS_2                   BCHP_INT_ID_CREATE(BCHP_QPSK_INTR2_0_CPU_STATUS, BCHP_SDS_0_IRQSTS1_MIC_IS_SHIFT)

#define BCHP_SDS_ADCDBIT BCHP_SDS_0_ADCDBIT
#define BCHP_SDS_ADCPCLP BCHP_SDS_0_ADCPCLP
#define BCHP_SDS_ADCPCTL BCHP_SDS_0_ADCPCTL
#define BCHP_SDS_AFECTL1 BCHP_SDS_0_AFECTL1
#define BCHP_SDS_AGCMISC BCHP_SDS_0_AGCMISC
#define BCHP_SDS_AGFCTL BCHP_SDS_0_AGFCTL
#define BCHP_SDS_AGICTL BCHP_SDS_0_AGICTL
#define BCHP_SDS_AGTCTL BCHP_SDS_0_AGTCTL
#define BCHP_SDS_AUXID BCHP_SDS_0_AUXID
#define BCHP_SDS_BCKTMR BCHP_SDS_0_BCKTMR
#define BCHP_SDS_BERCTLA BCHP_SDS_0_BERCTLA
#define BCHP_SDS_BERCTLB BCHP_SDS_0_BERCTLB
#define BCHP_SDS_BLCPTH BCHP_SDS_0_BLCPTH
#define BCHP_SDS_BLPCTL1 BCHP_SDS_0_BLPCTL1
#define BCHP_SDS_BLPCTL2 BCHP_SDS_0_BLPCTL2
#define BCHP_SDS_BLPCTL3 BCHP_SDS_0_BLPCTL3
#define BCHP_SDS_BLSCCP BCHP_SDS_0_BLSCCP
#define BCHP_SDS_CGCTL1 BCHP_SDS_0_CGCTL1
#define BCHP_SDS_CGCTL2 BCHP_SDS_0_CGCTL2
#define BCHP_SDS_CGCTRL BCHP_SDS_0_CGCTRL
#define BCHP_SDS_CGDIV0 BCHP_SDS_0_CGDIV0
#define BCHP_SDS_CGDIV1 BCHP_SDS_0_CGDIV1
#define BCHP_SDS_CGDIV10 BCHP_SDS_0_CGDIV10
#define BCHP_SDS_CGDIV11 BCHP_SDS_0_CGDIV11
#define BCHP_SDS_CGDIV2 BCHP_SDS_0_CGDIV2
#define BCHP_SDS_CGDIV3 BCHP_SDS_0_CGDIV3
#define BCHP_SDS_CGDIV4 BCHP_SDS_0_CGDIV4
#define BCHP_SDS_CGDIV5 BCHP_SDS_0_CGDIV5
#define BCHP_SDS_CGDIV6 BCHP_SDS_0_CGDIV6
#define BCHP_SDS_CGDIV7 BCHP_SDS_0_CGDIV7
#define BCHP_SDS_CGDIV8 BCHP_SDS_0_CGDIV8
#define BCHP_SDS_CGDIV9 BCHP_SDS_0_CGDIV9
#define BCHP_SDS_CGMISC BCHP_SDS_0_CGMISC
#define BCHP_SDS_CGMISC2 BCHP_SDS_0_CGMISC2
#define BCHP_SDS_CGPDWN BCHP_SDS_0_CGPDWN
#define BCHP_SDS_CGPLLCTL2 BCHP_SDS_0_CGPLLCTL2
#define BCHP_SDS_CGPLLCTL3 BCHP_SDS_0_CGPLLCTL3
#define BCHP_SDS_CGPLLCTL4 BCHP_SDS_0_CGPLLCTL4
#define BCHP_SDS_CGPLLCTL5 BCHP_SDS_0_CGPLLCTL5
#define BCHP_SDS_CGPLLCTL6 BCHP_SDS_0_CGPLLCTL6
#define BCHP_SDS_CGPLLCTL7 BCHP_SDS_0_CGPLLCTL7
#define BCHP_SDS_CLCTL BCHP_SDS_0_CLCTL
#define BCHP_SDS_CLFBCTL BCHP_SDS_0_CLFBCTL
#define BCHP_SDS_CLFBCTL2 BCHP_SDS_0_CLFBCTL2
#define BCHP_SDS_CLFFCTL BCHP_SDS_0_CLFFCTL
#define BCHP_SDS_CLMISC BCHP_SDS_0_CLMISC
#define BCHP_SDS_CLMISC2 BCHP_SDS_0_CLMISC2
#define BCHP_SDS_CLOON BCHP_SDS_0_CLOON
#define BCHP_SDS_CLPDCTL BCHP_SDS_0_CLPDCTL
#define BCHP_SDS_CLQCFD BCHP_SDS_0_CLQCFD
#define BCHP_SDS_CLSTS BCHP_SDS_0_CLSTS
#define BCHP_SDS_CORMSK BCHP_SDS_0_CORMSK
#define BCHP_SDS_DCOCTL1 BCHP_SDS_0_DCOCTL1
#define BCHP_SDS_DCOCTL2 BCHP_SDS_0_DCOCTL2
#define BCHP_SDS_DFCTL BCHP_SDS_0_DFCTL
#define BCHP_SDS_DSCMD BCHP_SDS_0_DSCMD
#define BCHP_SDS_DSCMEMADR BCHP_SDS_0_DSCMEMADR
#define BCHP_SDS_DSCMEMDAT BCHP_SDS_0_DSCMEMDAT
#define BCHP_SDS_DSFIRCTL BCHP_SDS_0_DSFIRCTL
#define BCHP_SDS_DS_SAR_THRSH BCHP_SDS_0_DS_SAR_THRSH
#define BCHP_SDS_DS_SAR_DATA_OUT BCHP_SDS_0_DS_SAR_DATA_OUT
#define BCHP_SDS_DS_SAR_DC_OFFSET BCHP_SDS_0_DS_SAR_DC_OFFSET
#define BCHP_SDS_DS_SAR_LPF_INT BCHP_SDS_0_DS_SAR_LPF_INT
#define BCHP_SDS_DS_SAR_CONTROL BCHP_SDS_0_DS_SAR_CONTROL
#define BCHP_SDS_DS_MISC_CONTROL BCHP_SDS_0_DS_MISC_CONTROL
#define BCHP_SDS_DS_PARITY BCHP_SDS_0_DS_PARITY
#define BCHP_SDS_DSCTL1 BCHP_SDS_0_DSCTL1
#define BCHP_SDS_DSCTL10 BCHP_SDS_0_DSCTL10
#define BCHP_SDS_DSCTL11 BCHP_SDS_0_DSCTL11
#define BCHP_SDS_DSCTL12 BCHP_SDS_0_DSCTL12
#define BCHP_SDS_DSCTL13 BCHP_SDS_0_DSCTL13
#define BCHP_SDS_DSCTL14 BCHP_SDS_0_DSCTL14
#define BCHP_SDS_DSCTL2 BCHP_SDS_0_DSCTL2
#define BCHP_SDS_DSCTL3 BCHP_SDS_0_DSCTL3
#define BCHP_SDS_DSCTL4 BCHP_SDS_0_DSCTL4
#define BCHP_SDS_DSCTL5 BCHP_SDS_0_DSCTL5
#define BCHP_SDS_DSCTL6 BCHP_SDS_0_DSCTL6
#define BCHP_SDS_DSCTL7 BCHP_SDS_0_DSCTL7
#define BCHP_SDS_DSCTL8 BCHP_SDS_0_DSCTL8
#define BCHP_SDS_DSCTL9 BCHP_SDS_0_DSCTL9
#define BCHP_SDS_DSRPLY BCHP_SDS_0_DSRPLY
#define BCHP_SDS_DSTGCTL BCHP_SDS_0_DSTGCTL
#define BCHP_SDS_EQBLND BCHP_SDS_0_EQBLND
#define BCHP_SDS_EQCFAD BCHP_SDS_0_EQCFAD
#define BCHP_SDS_EQFFE1 BCHP_SDS_0_EQFFE1
#define BCHP_SDS_EQFFE2 BCHP_SDS_0_EQFFE2
#define BCHP_SDS_EQFFE3 BCHP_SDS_0_EQFFE3
#define BCHP_SDS_EQFRZ1 BCHP_SDS_0_EQFRZ1
#define BCHP_SDS_EQFRZ2 BCHP_SDS_0_EQFRZ2
#define BCHP_SDS_EQFRZ3 BCHP_SDS_0_EQFRZ3
#define BCHP_SDS_EQMISC BCHP_SDS_0_EQMISC
#define BCHP_SDS_EQMODE BCHP_SDS_0_EQMODE
#define BCHP_SDS_EQMU BCHP_SDS_0_EQMU
#define BCHP_SDS_EXTIFDIR BCHP_SDS_0_EXTIFDIR
#define BCHP_SDS_FBLC BCHP_SDS_0_FBLC
#define BCHP_SDS_FBLI BCHP_SDS_0_FBLI
#define BCHP_SDS_FBPA BCHP_SDS_0_FBPA
#define BCHP_SDS_FECTL BCHP_SDS_0_FECTL
#define BCHP_SDS_PLHDRCFG BCHP_SDS_0_PLHDRCFG
#define BCHP_SDS_FILTCTL BCHP_SDS_0_FILTCTL
#define BCHP_SDS_FIRQSTS1 BCHP_SDS_0_FIRQSTS1
#define BCHP_SDS_FIRQSTS2 BCHP_SDS_0_FIRQSTS2
#define BCHP_SDS_FIRQSTS3 BCHP_SDS_0_FIRQSTS3
#define BCHP_SDS_FIRQSTS4 BCHP_SDS_0_FIRQSTS4
#define BCHP_SDS_FIRQSTS5 BCHP_SDS_0_FIRQSTS5
#define BCHP_SDS_FMAX BCHP_SDS_0_FMAX
#define BCHP_SDS_FMMAX BCHP_SDS_0_FMMAX
#define BCHP_SDS_DCOLKCTL BCHP_SDS_0_DCOLKCTL
#define BCHP_SDS_GENCTRL1 BCHP_SDS_0_GENCTRL1
#define BCHP_SDS_GENCTRL2 BCHP_SDS_0_GENCTRL2
#define BCHP_SDS_GLBCTL BCHP_SDS_0_GLBCTL
#define BCHP_SDS_PILOTCTL BCHP_SDS_0_PILOTCTL
#define BCHP_SDS_HPCTRL1 BCHP_SDS_0_HPCTRL1
#define BCHP_SDS_HPCTRL2 BCHP_SDS_0_HPCTRL2
#define BCHP_SDS_HPCTRL3 BCHP_SDS_0_HPCTRL3
#define BCHP_SDS_HPCTRL4 BCHP_SDS_0_HPCTRL4
#define BCHP_SDS_HPCTRL5 BCHP_SDS_0_HPCTRL5
#define BCHP_SDS_HPCTRL6 BCHP_SDS_0_HPCTRL6
#define BCHP_SDS_HPCTRL7 BCHP_SDS_0_HPCTRL7
#define BCHP_SDS_HPCTRL8 BCHP_SDS_0_HPCTRL8
#define BCHP_SDS_HPLLCTL BCHP_SDS_0_HPLLCTL
#define BCHP_SDS_HPMODE BCHP_SDS_0_HPMODE
#define BCHP_SDS_HPPDWN BCHP_SDS_0_HPPDWN
#define BCHP_SDS_HSTATEBP BCHP_SDS_0_HSTATEBP
#define BCHP_SDS_IFMAX BCHP_SDS_0_IFMAX
#define BCHP_SDS_IICCNT BCHP_SDS_0_IICCNT
#define BCHP_SDS_IICHPA BCHP_SDS_0_IICHPA
#define BCHP_SDS_IICTL1 BCHP_SDS_0_IICTL1
#define BCHP_SDS_IICTL2 BCHP_SDS_0_IICTL2
#define BCHP_SDS_IQAMP BCHP_SDS_0_IQAMP
#define BCHP_SDS_IQPHS BCHP_SDS_0_IQPHS
#define BCHP_SDS_IRQMSK1 BCHP_SDS_0_IRQMSK1
#define BCHP_SDS_IRQMSK2 BCHP_SDS_0_IRQMSK2
#define BCHP_SDS_IRQMSK3 BCHP_SDS_0_IRQMSK3
#define BCHP_SDS_IRQMSK4 BCHP_SDS_0_IRQMSK4
#define BCHP_SDS_IRQMSK5 BCHP_SDS_0_IRQMSK5
#define BCHP_SDS_IRQSTS1 BCHP_SDS_0_IRQSTS1
#define BCHP_SDS_IRQSTS2 BCHP_SDS_0_IRQSTS2
#define BCHP_SDS_IRQSTS3 BCHP_SDS_0_IRQSTS3
#define BCHP_SDS_IRQSTS4 BCHP_SDS_0_IRQSTS4
#define BCHP_SDS_IRQSTS5 BCHP_SDS_0_IRQSTS5
#define BCHP_SDS_MCTRL BCHP_SDS_0_MCTRL
#define BCHP_SDS_MISCTL BCHP_SDS_0_MISCTL
#define BCHP_SDS_MIXCTL BCHP_SDS_0_MIXCTL
#define BCHP_SDS_NDFCTL BCHP_SDS_0_NDFCTL
#define BCHP_SDS_NVCTL BCHP_SDS_0_NVCTL
#define BCHP_SDS_OIFCTL BCHP_SDS_0_OIFCTL
#define BCHP_SDS_OIFCTL2 BCHP_SDS_0_OIFCTL2
#define BCHP_SDS_OIFCTL3 BCHP_SDS_0_OIFCTL3
#define BCHP_SDS_OIFCTL4 BCHP_SDS_0_OIFCTL4
#define BCHP_SDS_OIFCTL5 BCHP_SDS_0_OIFCTL5
#define BCHP_SDS_OPLL_NDIV_INT BCHP_SDS_0_OPLL_NDIV_INT
#define BCHP_SDS_OPLL_NDIV_FRAC BCHP_SDS_0_OPLL_NDIV_FRAC
#define BCHP_SDS_OPLL_MPDIV BCHP_SDS_0_OPLL_MPDIV
#define BCHP_SDS_OPLL_CTRL1 BCHP_SDS_0_OPLL_CTRL1
#define BCHP_SDS_OPLL_CTRL0 BCHP_SDS_0_OPLL_CTRL0
#define BCHP_SDS_OPLL_MODE BCHP_SDS_0_OPLL_MODE
#define BCHP_SDS_OPLL_PWRDN BCHP_SDS_0_OPLL_PWRDN
#define BCHP_SDS_OPLL_RST BCHP_SDS_0_OPLL_RST
#define BCHP_SDS_ONFN BCHP_SDS_0_ONFN
#define BCHP_SDS_PFCTL BCHP_SDS_0_PFCTL
#define BCHP_SDS_PLDCTL BCHP_SDS_0_PLDCTL
#define BCHP_SDS_PSCTL BCHP_SDS_0_PSCTL
#define BCHP_SDS_PUPCFG BCHP_SDS_0_PUPCFG
#define BCHP_SDS_PUPCFGB BCHP_SDS_0_PUPCFGB
#define BCHP_SDS_REVID BCHP_SDS_0_REVID
#define BCHP_SDS_SNRCTL BCHP_SDS_0_SNRCTL
#define BCHP_SDS_TFAVG BCHP_SDS_0_TFAVG
#define BCHP_SDS_TRNLEN BCHP_SDS_0_TRNLEN
#define BCHP_SDS_VLCTL1 BCHP_SDS_0_VLCTL1
#define BCHP_SDS_VLCTL2 BCHP_SDS_0_VLCTL2
#define BCHP_SDS_VLCTL3 BCHP_SDS_0_VLCTL3
#define BCHP_SDS_VTCTL1 BCHP_SDS_0_VTCTL1
#define BCHP_SDS_VTCTL2 BCHP_SDS_0_VTCTL2
#define BCHP_SDS_WSMAX BCHP_SDS_0_WSMAX
#define BCHP_SDS_HI_HOLE BCHP_SDS_0_HI_HOLE
#define BCHP_SDS_HI_SPARE BCHP_SDS_0_HI_SPARE
#define BCHP_SDS_HI_TST BCHP_SDS_0_HI_TST
#define BCHP_SDS_ICB_CTL BCHP_SDS_0_ICB_CTL
#define BCHP_SDS_MI2CSA BCHP_SDS_0_MI2CSA
#define BCHP_SDS_BEST BCHP_SDS_0_BEST
#define BCHP_SDS_BLP BCHP_SDS_0_BLP
#define BCHP_SDS_BNCO BCHP_SDS_0_BNCO
#define BCHP_SDS_BRFO BCHP_SDS_0_BRFO
#define BCHP_SDS_CGSTA BCHP_SDS_0_CGSTA
#define BCHP_SDS_CGSTA1 BCHP_SDS_0_CGSTA1
#define BCHP_SDS_CGSTA2 BCHP_SDS_0_CGSTA2
#define BCHP_SDS_DST1 BCHP_SDS_0_DST1
#define BCHP_SDS_DST2 BCHP_SDS_0_DST2
#define BCHP_SDS_PLHDRSCR1 BCHP_SDS_0_PLHDRSCR1
#define BCHP_SDS_PLHDRSCR2 BCHP_SDS_0_PLHDRSCR2
#define BCHP_SDS_PLHDRSCR3 BCHP_SDS_0_PLHDRSCR3
#define BCHP_SDS_EQSFT BCHP_SDS_0_EQSFT
#define BCHP_SDS_FLFO BCHP_SDS_0_FLFO
#define BCHP_SDS_FRF1 BCHP_SDS_0_FRF1
#define BCHP_SDS_FRF2 BCHP_SDS_0_FRF2
#define BCHP_SDS_FRF3 BCHP_SDS_0_FRF3
#define BCHP_SDS_FRSV BCHP_SDS_0_FRSV
#define BCHP_SDS_OSIGPN BCHP_SDS_0_OSIGPN
#define BCHP_SDS_MIICRX1 BCHP_SDS_0_MIICRX1
#define BCHP_SDS_MIICRX2 BCHP_SDS_0_MIICRX2
#define BCHP_SDS_STAT BCHP_SDS_0_STAT
#define BCHP_SDS_TPOUT BCHP_SDS_0_TPOUT
#define BCHP_SDS_TSFT BCHP_SDS_0_TSFT
#define BCHP_SDS_VCNT BCHP_SDS_0_VCNT
#define BCHP_SDS_VRCV BCHP_SDS_0_VRCV
#define BCHP_SDS_VREC BCHP_SDS_0_VREC
#define BCHP_SDS_VST BCHP_SDS_0_VST
#define BCHP_SDS_VSTC BCHP_SDS_0_VSTC
#define BCHP_SDS_MBOX_CSR_P BCHP_SDS_0_MBOX_CSR_P
#define BCHP_SDS_MBOX_CSR_S BCHP_SDS_0_MBOX_CSR_S
#define BCHP_SDS_MBOX_DATA_P BCHP_SDS_0_MBOX_DATA_P
#define BCHP_SDS_MBOX_DATA_S BCHP_SDS_0_MBOX_DATA_S
#define BCHP_SDS_HD16QAM BCHP_SDS_0_HD16QAM
#define BCHP_SDS_HD8PSK1 BCHP_SDS_0_HD8PSK1
#define BCHP_SDS_HD8PSK2 BCHP_SDS_0_HD8PSK2
#define BCHP_SDS_ABW BCHP_SDS_0_ABW
#define BCHP_SDS_ADC BCHP_SDS_0_ADC
#define BCHP_SDS_ADCTL BCHP_SDS_0_ADCTL
#define BCHP_SDS_AEST BCHP_SDS_0_AEST
#define BCHP_SDS_AFECTL BCHP_SDS_0_AFECTL
#define BCHP_SDS_AFECTL2 BCHP_SDS_0_AFECTL2
#define BCHP_SDS_AGF BCHP_SDS_0_AGF
#define BCHP_SDS_AII BCHP_SDS_0_AII
#define BCHP_SDS_AGI BCHP_SDS_0_AGI
#define BCHP_SDS_AIT BCHP_SDS_0_AIT
#define BCHP_SDS_AGT BCHP_SDS_0_AGT
#define BCHP_SDS_AGCLI BCHP_SDS_0_AGCLI
#define BCHP_SDS_DSGIN BCHP_SDS_0_DSGIN
#define BCHP_SDS_IAGCTH BCHP_SDS_0_IAGCTH
#define BCHP_SDS_AIF BCHP_SDS_0_AIF
#define BCHP_SDS_ATHR BCHP_SDS_0_ATHR
#define BCHP_SDS_BEIT BCHP_SDS_0_BEIT
#define BCHP_SDS_BEM1 BCHP_SDS_0_BEM1
#define BCHP_SDS_BEM2 BCHP_SDS_0_BEM2
#define BCHP_SDS_BEM3 BCHP_SDS_0_BEM3
#define BCHP_SDS_BERC BCHP_SDS_0_BERC
#define BCHP_SDS_BERTMR BCHP_SDS_0_BERTMR
#define BCHP_SDS_GENTMR1 BCHP_SDS_0_GENTMR1
#define BCHP_SDS_GENTMR2 BCHP_SDS_0_GENTMR2
#define BCHP_SDS_XTLTMR BCHP_SDS_0_XTLTMR
#define BCHP_SDS_BFOS BCHP_SDS_0_BFOS
#define BCHP_SDS_BLEN BCHP_SDS_0_BLEN
#define BCHP_SDS_BRI BCHP_SDS_0_BRI
#define BCHP_SDS_BRIC BCHP_SDS_0_BRIC
#define BCHP_SDS_BRLC BCHP_SDS_0_BRLC
#define BCHP_SDS_BTMR BCHP_SDS_0_BTMR
#define BCHP_SDS_CICC BCHP_SDS_0_CICC
#define BCHP_SDS_CLCT BCHP_SDS_0_CLCT
#define BCHP_SDS_CLHT BCHP_SDS_0_CLHT
#define BCHP_SDS_CLLA BCHP_SDS_0_CLLA
#define BCHP_SDS_CLLT BCHP_SDS_0_CLLT
#define BCHP_SDS_CMA BCHP_SDS_0_CMA
#define BCHP_SDS_CMATH BCHP_SDS_0_CMATH
#define BCHP_SDS_CRBFD BCHP_SDS_0_CRBFD
#define BCHP_SDS_DCDSX BCHP_SDS_0_DCDSX
#define BCHP_SDS_DCO BCHP_SDS_0_DCO
#define BCHP_SDS_DDIO BCHP_SDS_0_DDIO
#define BCHP_SDS_DELIF BCHP_SDS_0_DELIF
#define BCHP_SDS_DPTH BCHP_SDS_0_DPTH
#define BCHP_SDS_DSCT BCHP_SDS_0_DSCT
#define BCHP_SDS_DTCT BCHP_SDS_0_DTCT
#define BCHP_SDS_F0B BCHP_SDS_0_F0B
#define BCHP_SDS_FCIC BCHP_SDS_0_FCIC
#define BCHP_SDS_FERC BCHP_SDS_0_FERC
#define BCHP_SDS_FRC BCHP_SDS_0_FRC
#define BCHP_SDS_FERR BCHP_SDS_0_FERR
#define BCHP_SDS_FFCNT BCHP_SDS_0_FFCNT
#define BCHP_SDS_FFLPA BCHP_SDS_0_FFLPA
#define BCHP_SDS_FFNORM BCHP_SDS_0_FFNORM
#define BCHP_SDS_FLI BCHP_SDS_0_FLI
#define BCHP_SDS_FLIC BCHP_SDS_0_FLIC
#define BCHP_SDS_FLIC1 BCHP_SDS_0_FLIC1
#define BCHP_SDS_FLIF BCHP_SDS_0_FLIF
#define BCHP_SDS_FLLC BCHP_SDS_0_FLLC
#define BCHP_SDS_FLLC1 BCHP_SDS_0_FLLC1
#define BCHP_SDS_FLPA BCHP_SDS_0_FLPA
#define BCHP_SDS_FLSW BCHP_SDS_0_FLSW
#define BCHP_SDS_FLTD BCHP_SDS_0_FLTD
#define BCHP_SDS_FMOD BCHP_SDS_0_FMOD
#define BCHP_SDS_FNRM BCHP_SDS_0_FNRM
#define BCHP_SDS_FRF BCHP_SDS_0_FRF
#define BCHP_SDS_FRS BCHP_SDS_0_FRS
#define BCHP_SDS_FSYN BCHP_SDS_0_FSYN
#define BCHP_SDS_H8PSK BCHP_SDS_0_H8PSK
#define BCHP_SDS_HPBP BCHP_SDS_0_HPBP
#define BCHP_SDS_HPCC0 BCHP_SDS_0_HPCC0
#define BCHP_SDS_HPCC1 BCHP_SDS_0_HPCC1
#define BCHP_SDS_HPCC2 BCHP_SDS_0_HPCC2
#define BCHP_SDS_HPCC3 BCHP_SDS_0_HPCC3
#define BCHP_SDS_HPCC4 BCHP_SDS_0_HPCC4
#define BCHP_SDS_HPCC5 BCHP_SDS_0_HPCC5
#define BCHP_SDS_HPCC6 BCHP_SDS_0_HPCC6
#define BCHP_SDS_HPCC7 BCHP_SDS_0_HPCC7
#define BCHP_SDS_HPDC0 BCHP_SDS_0_HPDC0
#define BCHP_SDS_HPDC1 BCHP_SDS_0_HPDC1
#define BCHP_SDS_HPDC2 BCHP_SDS_0_HPDC2
#define BCHP_SDS_HPDC3 BCHP_SDS_0_HPDC3
#define BCHP_SDS_HPDC4 BCHP_SDS_0_HPDC4
#define BCHP_SDS_HPDC5 BCHP_SDS_0_HPDC5
#define BCHP_SDS_HPDC6 BCHP_SDS_0_HPDC6
#define BCHP_SDS_HPDC7 BCHP_SDS_0_HPDC7
#define BCHP_SDS_IRQ BCHP_SDS_0_IRQ
#define BCHP_SDS_IRQMSK BCHP_SDS_0_IRQMSK
#define BCHP_SDS_IRQRST BCHP_SDS_0_IRQRST
#define BCHP_SDS_MGTH BCHP_SDS_0_MGTH
#define BCHP_SDS_MIICTX1 BCHP_SDS_0_MIICTX1
#define BCHP_SDS_MIICTX2 BCHP_SDS_0_MIICTX2
#define BCHP_SDS_MISC1 BCHP_SDS_0_MISC1
#define BCHP_SDS_MISC2 BCHP_SDS_0_MISC2
#define BCHP_SDS_MSMAX BCHP_SDS_0_MSMAX
#define BCHP_SDS_OFD BCHP_SDS_0_OFD
#define BCHP_SDS_OFNSEQ BCHP_SDS_0_OFNSEQ
#define BCHP_SDS_OPLL BCHP_SDS_0_OPLL
#define BCHP_SDS_OPLL2 BCHP_SDS_0_OPLL2
#define BCHP_SDS_OVRDSEL BCHP_SDS_0_OVRDSEL
#define BCHP_SDS_SIMAX BCHP_SDS_0_SIMAX
#define BCHP_SDS_SITHRSH BCHP_SDS_0_SITHRSH
#define BCHP_SDS_FFOFF BCHP_SDS_0_FFOFF
#define BCHP_SDS_SISTEP BCHP_SDS_0_SISTEP
#define BCHP_SDS_FFCOEF0 BCHP_SDS_0_FFCOEF0
#define BCHP_SDS_FFCOEF1 BCHP_SDS_0_FFCOEF1
#define BCHP_SDS_FFCOEF2 BCHP_SDS_0_FFCOEF2
#define BCHP_SDS_FFCOEF3 BCHP_SDS_0_FFCOEF3
#define BCHP_SDS_FFCOEF4 BCHP_SDS_0_FFCOEF4
#define BCHP_SDS_FFCOEF5 BCHP_SDS_0_FFCOEF5
#define BCHP_SDS_FFCOEF6 BCHP_SDS_0_FFCOEF6
#define BCHP_SDS_PEST BCHP_SDS_0_PEST
#define BCHP_SDS_PHDIV1 BCHP_SDS_0_PHDIV1
#define BCHP_SDS_PHDIV2 BCHP_SDS_0_PHDIV2
#define BCHP_SDS_PLC BCHP_SDS_0_PLC
#define BCHP_SDS_PLC1 BCHP_SDS_0_PLC1
#define BCHP_SDS_PLCTL BCHP_SDS_0_PLCTL
#define BCHP_SDS_PLI BCHP_SDS_0_PLI
#define BCHP_SDS_PLPA BCHP_SDS_0_PLPA
#define BCHP_SDS_PLSW BCHP_SDS_0_PLSW
#define BCHP_SDS_PLTD BCHP_SDS_0_PLTD
#define BCHP_SDS_PSMAX BCHP_SDS_0_PSMAX
#define BCHP_SDS_HDRD BCHP_SDS_0_HDRD
#define BCHP_SDS_HDRA BCHP_SDS_0_HDRA
#define BCHP_SDS_FRF4 BCHP_SDS_0_FRF4
#define BCHP_SDS_PVMAX BCHP_SDS_0_PVMAX
#define BCHP_SDS_Q15T BCHP_SDS_0_Q15T
#define BCHP_SDS_QPSK BCHP_SDS_0_QPSK
#define BCHP_SDS_RBDT BCHP_SDS_0_RBDT
#define BCHP_SDS_RERT BCHP_SDS_0_RERT
#define BCHP_SDS_RLMAX BCHP_SDS_0_RLMAX
#define BCHP_SDS_RTDC1 BCHP_SDS_0_RTDC1
#define BCHP_SDS_RTDC2 BCHP_SDS_0_RTDC2
#define BCHP_SDS_RXBT BCHP_SDS_0_RXBT
#define BCHP_SDS_RXRT BCHP_SDS_0_RXRT
#define BCHP_SDS_SCIC BCHP_SDS_0_SCIC
#define BCHP_SDS_SFTDLY BCHP_SDS_0_SFTDLY
#define BCHP_SDS_SLEW BCHP_SDS_0_SLEW
#define BCHP_SDS_SNRE BCHP_SDS_0_SNRE
#define BCHP_SDS_SNRHT BCHP_SDS_0_SNRHT
#define BCHP_SDS_SNRLT BCHP_SDS_0_SNRLT
#define BCHP_SDS_TCMAX BCHP_SDS_0_TCMAX
#define BCHP_SDS_TCTL BCHP_SDS_0_TCTL
#define BCHP_SDS_TLMAX BCHP_SDS_0_TLMAX
#define BCHP_SDS_TMTH BCHP_SDS_0_TMTH
#define BCHP_SDS_TNRM BCHP_SDS_0_TNRM
#define BCHP_SDS_TPCTL1 BCHP_SDS_0_TPCTL1
#define BCHP_SDS_TPCTL2 BCHP_SDS_0_TPCTL2
#define BCHP_SDS_TPCTL3 BCHP_SDS_0_TPCTL3
#define BCHP_SDS_TPDIR BCHP_SDS_0_TPDIR
#define BCHP_SDS_TPDS BCHP_SDS_0_TPDS
#define BCHP_SDS_TPODS3 BCHP_SDS_0_TPODS3
#define BCHP_SDS_TPWC BCHP_SDS_0_TPWC
#define BCHP_SDS_TSTM BCHP_SDS_0_TSTM
#define BCHP_SDS_V0 BCHP_SDS_0_V0
#define BCHP_SDS_V1 BCHP_SDS_0_V1
#define BCHP_SDS_V2 BCHP_SDS_0_V2
#define BCHP_SDS_V3 BCHP_SDS_0_V3
#define BCHP_SDS_V4 BCHP_SDS_0_V4
#define BCHP_SDS_V5 BCHP_SDS_0_V5
#define BCHP_SDS_V6 BCHP_SDS_0_V6
#define BCHP_SDS_V7 BCHP_SDS_0_V7
#define BCHP_SDS_VCOS BCHP_SDS_0_VCOS
#define BCHP_SDS_VINT BCHP_SDS_0_VINT
#define BCHP_SDS_VLCI BCHP_SDS_0_VLCI
#define BCHP_SDS_VLCQ BCHP_SDS_0_VLCQ
#define BCHP_SDS_XSEED BCHP_SDS_0_XSEED
#define BCHP_SDS_XTAP1 BCHP_SDS_0_XTAP1
#define BCHP_SDS_XTAP2 BCHP_SDS_0_XTAP2
#define BCHP_SDS_FNRMR BCHP_SDS_0_FNRMR
#define BCHP_SDS_LUPD BCHP_SDS_0_LUPD
#define BCHP_SDS_LUPA BCHP_SDS_0_LUPA
#define BCHP_SDS_MEMTMR0 BCHP_SDS_0_MEMTMR0
#define BCHP_SDS_MEMTMR1 BCHP_SDS_0_MEMTMR1
#define BCHP_SDS_SPLL_NDIV_INT BCHP_SDS_0_SPLL_NDIV_INT
#define BCHP_SDS_SPLL_NDIV_FRAC BCHP_SDS_0_SPLL_NDIV_FRAC
#define BCHP_SDS_SPLL_MPDIV BCHP_SDS_0_SPLL_MPDIV
#define BCHP_SDS_SPLL_CTRL1 BCHP_SDS_0_SPLL_CTRL1
#define BCHP_SDS_SPLL_CTRL0 BCHP_SDS_0_SPLL_CTRL0
#define BCHP_SDS_SPLL_MODE BCHP_SDS_0_SPLL_MODE
#define BCHP_SDS_SPLL_PWRDN BCHP_SDS_0_SPLL_PWRDN
#define BCHP_SDS_SPLL_RST BCHP_SDS_0_SPLL_RST
#define BCHP_SDS_DFT_CTRL0 BCHP_SDS_0_DFT_CTRL0
#define BCHP_SDS_DFT_CTRL1 BCHP_SDS_0_DFT_CTRL1
#define BCHP_SDS_DFT_RANGE_START BCHP_SDS_0_DFT_RANGE_START
#define BCHP_SDS_DFT_RANGE_END BCHP_SDS_0_DFT_RANGE_END
#define BCHP_SDS_DFT_DDFS_FCW BCHP_SDS_0_DFT_DDFS_FCW
#define BCHP_SDS_DFT_PEAK_POW BCHP_SDS_0_DFT_PEAK_POW
#define BCHP_SDS_DFT_PEAK_BIN BCHP_SDS_0_DFT_PEAK_BIN
#define BCHP_SDS_DFT_TOTAL_POW BCHP_SDS_0_DFT_TOTAL_POW
#define BCHP_SDS_DFT_MEM_RADDR BCHP_SDS_0_DFT_MEM_RADDR
#define BCHP_SDS_DFT_MEM_RDATA BCHP_SDS_0_DFT_MEM_RDATA
#define BCHP_SDS_NTCH_CTRL BCHP_SDS_0_NTCH_CTRL
#define BCHP_SDS_NTCH_FCWADJ_SCL BCHP_SDS_0_NTCH_FCWADJ_SCL
#define BCHP_SDS_NTCH_FCW0 BCHP_SDS_0_NTCH_FCW0
#define BCHP_SDS_NTCH_FCW1 BCHP_SDS_0_NTCH_FCW1
#define BCHP_SDS_NTCH_FCW2 BCHP_SDS_0_NTCH_FCW2
#define BCHP_SDS_NTCH_FCW3 BCHP_SDS_0_NTCH_FCW3
#define BCHP_SDS_NTCH_DCO0_INT BCHP_SDS_0_NTCH_DCO0_INT
#define BCHP_SDS_NTCH_DCO1_INT BCHP_SDS_0_NTCH_DCO1_INT
#define BCHP_SDS_NTCH_DCO2_INT BCHP_SDS_0_NTCH_DCO2_INT
#define BCHP_SDS_BRSW BCHP_SDS_0_BRSW
#define BCHP_SDS_SDSLEN BCHP_SDS_0_SDSLEN
#define BCHP_SDS_SDSIG BCHP_SDS_0_SDSIG

#define BCHP_TFEC_TFECTL BCHP_TFEC_0_TFECTL
#define BCHP_TFEC_MEMTM0 BCHP_TFEC_0_MEMTM0
#define BCHP_TFEC_MEMTM1 BCHP_TFEC_0_MEMTM1
#define BCHP_TFEC_MEMTM2 BCHP_TFEC_0_MEMTM2
#define BCHP_TFEC_MEMTM3 BCHP_TFEC_0_MEMTM3
#define BCHP_TFEC_TCOR BCHP_TFEC_0_TCOR
#define BCHP_TFEC_TERR BCHP_TFEC_0_TERR
#define BCHP_TFEC_TFMT BCHP_TFEC_0_TFMT
#define BCHP_TFEC_TPAK BCHP_TFEC_0_TPAK
#define BCHP_TFEC_TSSQ BCHP_TFEC_0_TSSQ
#define BCHP_TFEC_TSYN BCHP_TFEC_0_TSYN
#define BCHP_TFEC_TTUR BCHP_TFEC_0_TTUR
#define BCHP_TFEC_TZPK BCHP_TFEC_0_TZPK
#define BCHP_TFEC_TZSY BCHP_TFEC_0_TZSY
#define BCHP_TFEC_TITR BCHP_TFEC_0_TITR
#define BCHP_TFEC_TCIL BCHP_TFEC_0_TCIL
#define BCHP_TFEC_TRSD BCHP_TFEC_0_TRSD
#define BCHP_TFEC_TPN BCHP_TFEC_0_TPN

#define BCHP_AFEC_LDPC_CONFIG_0 BCHP_AFEC_0_LDPC_CONFIG_0
#define BCHP_AFEC_LDPC_CONFIG_1 BCHP_AFEC_0_LDPC_CONFIG_1
#define BCHP_AFEC_LDPC_CONFIG_2 BCHP_AFEC_0_LDPC_CONFIG_2
#define BCHP_AFEC_LDPC_CONFIG_3 BCHP_AFEC_0_LDPC_CONFIG_3
#define BCHP_AFEC_LDPC_CONFIG_4 BCHP_AFEC_0_LDPC_CONFIG_4
#define BCHP_AFEC_LDPC_CONFIG_5 BCHP_AFEC_0_LDPC_CONFIG_5
#define BCHP_AFEC_LDPC_CONFIG_6 BCHP_AFEC_0_LDPC_CONFIG_6
#define BCHP_AFEC_LDPC_CONFIG_7 BCHP_AFEC_0_LDPC_CONFIG_7
#define BCHP_AFEC_LDPC_CONFIG_8 BCHP_AFEC_0_LDPC_CONFIG_8
#define BCHP_AFEC_LDPC_CONFIG_9 BCHP_AFEC_0_LDPC_CONFIG_9
#define BCHP_AFEC_LDPC_P_RAM_ADDR BCHP_AFEC_0_LDPC_P_RAM_ADDR
#define BCHP_AFEC_LDPC_P_RAM_DATA BCHP_AFEC_0_LDPC_P_RAM_DATA
#define BCHP_AFEC_LDPC_STATUS BCHP_AFEC_0_LDPC_STATUS
#define BCHP_AFEC_LDPC_TEST_CONFIG BCHP_AFEC_0_LDPC_TEST_CONFIG
#define BCHP_AFEC_LDPC_MET_CRC BCHP_AFEC_0_LDPC_MET_CRC
#define BCHP_AFEC_LDPC_EDGE_CRC BCHP_AFEC_0_LDPC_EDGE_CRC
#define BCHP_AFEC_LDPC_PSL_CTL BCHP_AFEC_0_LDPC_PSL_CTL
#define BCHP_AFEC_LDPC_PSL_INT_THRES BCHP_AFEC_0_LDPC_PSL_INT_THRES
#define BCHP_AFEC_LDPC_PSL_INT BCHP_AFEC_0_LDPC_PSL_INT
#define BCHP_AFEC_LDPC_PSL_AVE BCHP_AFEC_0_LDPC_PSL_AVE
#define BCHP_AFEC_LDPC_PSL_XCS BCHP_AFEC_0_LDPC_PSL_XCS
#define BCHP_AFEC_LDPC_FRM_CNT BCHP_AFEC_0_LDPC_FRM_CNT
#define BCHP_AFEC_LDPC_FAIL_CNT BCHP_AFEC_0_LDPC_FAIL_CNT
#define BCHP_AFEC_LDPC_CONFIG_10 BCHP_AFEC_0_LDPC_CONFIG_10
#define BCHP_AFEC_BCH_RST BCHP_AFEC_0_BCH_RST
#define BCHP_AFEC_BCH_TPCTL BCHP_AFEC_0_BCH_TPCTL
#define BCHP_AFEC_BCH_TPSIG BCHP_AFEC_0_BCH_TPSIG
#define BCHP_AFEC_BCH_DECCFG0 BCHP_AFEC_0_BCH_DECCFG0
#define BCHP_AFEC_BCH_DECCFG1 BCHP_AFEC_0_BCH_DECCFG1
#define BCHP_AFEC_BCH_DECNBLK BCHP_AFEC_0_BCH_DECNBLK
#define BCHP_AFEC_BCH_DECCBLK BCHP_AFEC_0_BCH_DECCBLK
#define BCHP_AFEC_BCH_DECBBLK BCHP_AFEC_0_BCH_DECBBLK
#define BCHP_AFEC_BCH_DECCBIT BCHP_AFEC_0_BCH_DECCBIT
#define BCHP_AFEC_BCH_DECMCOR BCHP_AFEC_0_BCH_DECMCOR
#define BCHP_AFEC_BCH_BBHDR0 BCHP_AFEC_0_BCH_BBHDR0
#define BCHP_AFEC_BCH_BBHDR1 BCHP_AFEC_0_BCH_BBHDR1
#define BCHP_AFEC_BCH_BBHDR2 BCHP_AFEC_0_BCH_BBHDR2
#define BCHP_AFEC_BCH_MPCFG0 BCHP_AFEC_0_BCH_MPCFG0
#define BCHP_AFEC_BCH_MPCFG1 BCHP_AFEC_0_BCH_MPCFG1
#define BCHP_AFEC_BCH_MPLCK BCHP_AFEC_0_BCH_MPLCK
#define BCHP_AFEC_RST BCHP_AFEC_0_RST
#define BCHP_AFEC_DP_RST BCHP_AFEC_0_DP_RST
#define BCHP_AFEC_PCI_IRQ_STAT BCHP_AFEC_0_PCI_IRQ_STAT
#define BCHP_AFEC_uP_IRQ_STAT BCHP_AFEC_0_uP_IRQ_STAT
#define BCHP_AFEC_PCI_IRQ_FSTAT BCHP_AFEC_0_PCI_IRQ_FSTAT
#define BCHP_AFEC_uP_IRQ_FSTAT BCHP_AFEC_0_uP_IRQ_FSTAT
#define BCHP_AFEC_PCI_IRQ_SET BCHP_AFEC_0_PCI_IRQ_SET
#define BCHP_AFEC_uP_IRQ_SET BCHP_AFEC_0_uP_IRQ_SET
#define BCHP_AFEC_PCI_IRQ_MSK BCHP_AFEC_0_PCI_IRQ_MSK
#define BCHP_AFEC_uP_IRQ_MSK BCHP_AFEC_0_uP_IRQ_MSK
#define BCHP_AFEC_PCI_IRQ_RESET BCHP_AFEC_0_PCI_IRQ_RESET
#define BCHP_AFEC_uP_IRQ_RESET BCHP_AFEC_0_uP_IRQ_RESET
#define BCHP_AFEC_USE_16K_FECFRAME BCHP_AFEC_0_USE_16K_FECFRAME
#define BCHP_AFEC_TM_0 BCHP_AFEC_0_TM_0
#define BCHP_AFEC_TM_1 BCHP_AFEC_0_TM_1
#define BCHP_AFEC_TM_2 BCHP_AFEC_0_TM_2
#define BCHP_AFEC_TM_3 BCHP_AFEC_0_TM_3
#define BCHP_AFEC_TM_4 BCHP_AFEC_0_TM_4

#define BCHP_TUNER_ANACTL0 BCHP_TUNER_0_ANACTL0
#define BCHP_TUNER_ANACTL1 BCHP_TUNER_0_ANACTL1
#define BCHP_TUNER_ANACTL2 BCHP_TUNER_0_ANACTL2
#define BCHP_TUNER_ANACTL3 BCHP_TUNER_0_ANACTL3
#define BCHP_TUNER_ANACTL4 BCHP_TUNER_0_ANACTL4
#define BCHP_TUNER_ANACTL5 BCHP_TUNER_0_ANACTL5
#define BCHP_TUNER_ANACTL6 BCHP_TUNER_0_ANACTL6
#define BCHP_TUNER_ANACTL7 BCHP_TUNER_0_ANACTL7
#define BCHP_TUNER_ANACTL8 BCHP_TUNER_0_ANACTL8
#define BCHP_TUNER_ANACTL9 BCHP_TUNER_0_ANACTL9
#define BCHP_TUNER_ANACTL10 BCHP_TUNER_0_ANACTL10
#define BCHP_TUNER_ANACTL11 BCHP_TUNER_0_ANACTL11
#define BCHP_TUNER_ANACTL12 BCHP_TUNER_0_ANACTL12
#define BCHP_TUNER_ANACTL13 BCHP_TUNER_0_ANACTL13
#define BCHP_TUNER_ANACTL14 BCHP_TUNER_0_ANACTL14
#define BCHP_TUNER_ANACTL15 BCHP_TUNER_0_ANACTL15
#define BCHP_TUNER_ANACTL16 BCHP_TUNER_0_ANACTL16
#define BCHP_TUNER_ANACTL17 BCHP_TUNER_0_ANACTL17
#define BCHP_TUNER_ANACTL18 BCHP_TUNER_0_ANACTL18
#define BCHP_TUNER_ANACTL19 BCHP_TUNER_0_ANACTL19
#define BCHP_TUNER_ANACTL20 BCHP_TUNER_0_ANACTL20
#define BCHP_TUNER_ANACTL21 BCHP_TUNER_0_ANACTL21
#define BCHP_TUNER_ANACTL22 BCHP_TUNER_0_ANACTL22
#define BCHP_TUNER_ANACTL23 BCHP_TUNER_0_ANACTL23
#define BCHP_TUNER_ANACTL24 BCHP_TUNER_0_ANACTL24
#define BCHP_TUNER_ANACTL25 BCHP_TUNER_0_ANACTL25
#define BCHP_TUNER_ANACTL26 BCHP_TUNER_0_ANACTL26
#define BCHP_TUNER_ANACTL27 BCHP_TUNER_0_ANACTL27
#define BCHP_TUNER_ANACTL28 BCHP_TUNER_0_ANACTL28
#define BCHP_TUNER_ANACTL29 BCHP_TUNER_0_ANACTL29
#define BCHP_TUNER_ANACTL30 BCHP_TUNER_0_ANACTL30
#define BCHP_TUNER_ANACTL31 BCHP_TUNER_0_ANACTL31
#define BCHP_TUNER_DIGCTL0 BCHP_TUNER_0_DIGCTL0
#define BCHP_TUNER_DIGCTL1 BCHP_TUNER_0_DIGCTL1
#define BCHP_TUNER_DIGCTL2 BCHP_TUNER_0_DIGCTL2
#define BCHP_TUNER_DIGCTL3 BCHP_TUNER_0_DIGCTL3
#define BCHP_TUNER_DIGCTL4 BCHP_TUNER_0_DIGCTL4
#define BCHP_TUNER_DIGCTL5 BCHP_TUNER_0_DIGCTL5
#define BCHP_TUNER_DIGCTL6 BCHP_TUNER_0_DIGCTL6
#define BCHP_TUNER_DIGCTL7 BCHP_TUNER_0_DIGCTL7
#define BCHP_TUNER_DIGCTL8 BCHP_TUNER_0_DIGCTL8
#define BCHP_TUNER_DIGCTL9 BCHP_TUNER_0_DIGCTL9
#define BCHP_TUNER_DIGCTL10 BCHP_TUNER_0_DIGCTL10
#define BCHP_TUNER_DIGCTL11 BCHP_TUNER_0_DIGCTL11
#define BCHP_TUNER_DIGCTL12 BCHP_TUNER_0_DIGCTL12
#define BCHP_TUNER_DIGCTL13 BCHP_TUNER_0_DIGCTL13
#define BCHP_TUNER_DIGCTL14 BCHP_TUNER_0_DIGCTL14
#define BCHP_TUNER_DIGCTL15 BCHP_TUNER_0_DIGCTL15
#define BCHP_TUNER_DIGCTL16 BCHP_TUNER_0_DIGCTL16
#define BCHP_TUNER_DIGCTL17 BCHP_TUNER_0_DIGCTL17
#define BCHP_TUNER_DIGCTL18 BCHP_TUNER_0_DIGCTL18
#define BCHP_TUNER_DIGCTL19 BCHP_TUNER_0_DIGCTL19
#define BCHP_TUNER_DIGCTL20 BCHP_TUNER_0_DIGCTL20
#define BCHP_TUNER_DIGCTL21 BCHP_TUNER_0_DIGCTL21
#define BCHP_TUNER_DIGCTL22 BCHP_TUNER_0_DIGCTL22
#define BCHP_TUNER_DIGCTL23 BCHP_TUNER_0_DIGCTL23
#define BCHP_TUNER_DIGCTL24 BCHP_TUNER_0_DIGCTL24
#define BCHP_TUNER_DIGCTL25 BCHP_TUNER_0_DIGCTL25
#define BCHP_TUNER_DIGCTL26 BCHP_TUNER_0_DIGCTL26
#define BCHP_TUNER_DIGCTL27 BCHP_TUNER_0_DIGCTL27
#define BCHP_TUNER_DIGCTL28 BCHP_TUNER_0_DIGCTL28
#define BCHP_TUNER_DIGCTL29 BCHP_TUNER_0_DIGCTL29
#define BCHP_TUNER_DIGCTL30 BCHP_TUNER_0_DIGCTL30
#define BCHP_TUNER_DIGCTL31 BCHP_TUNER_0_DIGCTL31
#define BCHP_TUNER_MB0 BCHP_TUNER_0_MB0
#define BCHP_TUNER_MB1 BCHP_TUNER_0_MB1
#define BCHP_TUNER_MB2 BCHP_TUNER_0_MB2
#define BCHP_TUNER_MB3 BCHP_TUNER_0_MB3
#define BCHP_TUNER_MB4 BCHP_TUNER_0_MB4
#define BCHP_TUNER_MB5 BCHP_TUNER_0_MB5
#define BCHP_TUNER_MB6 BCHP_TUNER_0_MB6
#define BCHP_TUNER_MB7 BCHP_TUNER_0_MB7
#define BCHP_TUNER_AGC_GAIN_CTL BCHP_TUNER_0_AGC_GAIN_CTL
#define BCHP_TUNER_DC_OFF_CTL BCHP_TUNER_0_DC_OFF_CTL

#define BCHP_SDS_INTR2_0_CPU_STATUS BCHP_SDS_INTR2_0_0_CPU_STATUS
#define BCHP_SDS_INTR2_0_CPU_SET BCHP_SDS_INTR2_0_0_CPU_SET
#define BCHP_SDS_INTR2_0_CPU_CLEAR BCHP_SDS_INTR2_0_0_CPU_CLEAR
#define BCHP_SDS_INTR2_0_CPU_MASK_STATUS BCHP_SDS_INTR2_0_0_CPU_MASK_STATUS
#define BCHP_SDS_INTR2_0_CPU_MASK_SET BCHP_SDS_INTR2_0_0_CPU_MASK_SET
#define BCHP_SDS_INTR2_0_CPU_MASK_CLEAR BCHP_SDS_INTR2_0_0_CPU_MASK_CLEAR
#define BCHP_SDS_INTR2_0_PCI_STATUS BCHP_SDS_INTR2_0_0_PCI_STATUS
#define BCHP_SDS_INTR2_0_PCI_SET BCHP_SDS_INTR2_0_0_PCI_SET
#define BCHP_SDS_INTR2_0_PCI_CLEAR BCHP_SDS_INTR2_0_0_PCI_CLEAR
#define BCHP_SDS_INTR2_0_PCI_MASK_STATUS BCHP_SDS_INTR2_0_0_PCI_MASK_STATUS
#define BCHP_SDS_INTR2_0_PCI_MASK_SET BCHP_SDS_INTR2_0_0_PCI_MASK_SET
#define BCHP_SDS_INTR2_0_PCI_MASK_CLEAR BCHP_SDS_INTR2_0_0_PCI_MASK_CLEAR

#define BCHP_SDS_INTR2_1_CPU_STATUS BCHP_SDS_INTR2_0_1_CPU_STATUS
#define BCHP_SDS_INTR2_1_CPU_SET BCHP_SDS_INTR2_0_1_CPU_SET
#define BCHP_SDS_INTR2_1_CPU_CLEAR BCHP_SDS_INTR2_0_1_CPU_CLEAR
#define BCHP_SDS_INTR2_1_CPU_MASK_STATUS BCHP_SDS_INTR2_0_1_CPU_MASK_STATUS
#define BCHP_SDS_INTR2_1_CPU_MASK_SET BCHP_SDS_INTR2_0_1_CPU_MASK_SET
#define BCHP_SDS_INTR2_1_CPU_MASK_CLEAR BCHP_SDS_INTR2_0_1_CPU_MASK_CLEAR
#define BCHP_SDS_INTR2_1_PCI_STATUS BCHP_SDS_INTR2_0_1_PCI_STATUS
#define BCHP_SDS_INTR2_1_PCI_SET BCHP_SDS_INTR2_0_1_PCI_SET
#define BCHP_SDS_INTR2_1_PCI_CLEAR BCHP_SDS_INTR2_0_1_PCI_CLEAR
#define BCHP_SDS_INTR2_1_PCI_MASK_STATUS BCHP_SDS_INTR2_0_1_PCI_MASK_STATUS
#define BCHP_SDS_INTR2_1_PCI_MASK_SET BCHP_SDS_INTR2_0_1_PCI_MASK_SET
#define BCHP_SDS_INTR2_1_PCI_MASK_CLEAR BCHP_SDS_INTR2_0_1_PCI_MASK_CLEAR

#define BCHP_GRB_REVISION BCHP_GRB_0_REVISION
#define BCHP_GRB_CTRL BCHP_GRB_0_CTRL
#define BCHP_GRB_SW_RESET_0 BCHP_GRB_0_SW_RESET_0
#define BCHP_GRB_SW_RESET_1 BCHP_GRB_0_SW_RESET_1


#endif /* _BAST_7335_PRIV_H__ */

