obj-y += UniversalClient_Common_API.o
obj-y += UniversalClient_DVB_API.o
obj-y += UniversalClient_API.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
