obj-y += xmgr_cas_va_menu.o
obj-y += xmgr_cas_va_statuslist.o
obj-y += xmgr_cas_va_maturity_rate.o
obj-$(CONFIG_MW_CAS_VIACCESS_MULTI_OPMSG) += xmgr_cas_va_op_message.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

# Sub-CAS include path
