
obj-$(CONFIG_PROD_HDR1000S)			+= xsvc_download_init_hdr1000s.o
obj-$(CONFIG_PROD_HMS1000S)			+= xsvc_download_init_hms1000s.o
obj-$(CONFIG_PROD_HMSLITE)			+= xsvc_download_init_hms1000s.o
obj-$(CONFIG_PROD_IR4000HD)			+= xsvc_download_init_ir4000hd.o
obj-$(CONFIG_PROD_ICORDPRO)			+= xsvc_download_init_icordpro.o
obj-$(CONFIG_PROD_HDNEO)			+= xsvc_download_init_hdneo.o
obj-$(CONFIG_PROD_HGS1000S)			+= xsvc_download_init_hgs1000s.o
obj-$(CONFIG_PROD_HGS1000SIT)			+= xsvc_download_init_hgs1000sit.o
obj-$(CONFIG_PROD_HD9000I)			+= xsvc_download_init_hd9000i.o
obj-$(CONFIG_PROD_HMS1000T)			+= xsvc_download_init_hms1000t.o
obj-$(CONFIG_PROD_IHDR6100C)		+= xsvc_download_init_ihdr6100c.o
obj-$(CONFIG_PROD_FVP4000T)			+= xsvc_download_init_fvp4000t.o
obj-$(CONFIG_PROD_HMX4KBBC)			+= xsvc_download_init_hmx4kbbc.o
obj-$(CONFIG_PROD_DIGIMAXT2)		+= xsvc_download_init_digimaxt2.o
obj-$(CONFIG_PROD_HDFOXIRCONNECT)	+= xsvc_download_init_hdfoxirconnect.o
obj-$(CONFIG_PROD_YSR2000)			+= xsvc_download_init_ysr2000.o
obj-$(CONFIG_PROD_YS1000)			+= xsvc_download_init_ys1000.o
obj-$(CONFIG_PROD_CDIG2000C)		+= xsvc_download_init_cdig2000c.o
obj-$(CONFIG_PROD_ROCKYPOM)		+= xsvc_download_init_rockypom.o
obj-$(CONFIG_PROD_ROCKYWPOM)		+= xsvc_download_init_rockypom.o
obj-$(CONFIG_PROD_HA7100S) 		+= xsvc_download_init_ha7100s.o
obj-$(CONFIG_PROD_M1) 		+= xsvc_download_init_m1.o
obj-$(CONFIG_PROD_DT95420UHD) 		+= xsvc_download_init_dt95420uhd.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

