#
obj-y := tmbslTDA18273/src/
obj-y += drv_channel_tn18273.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18273/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18273/tmbslTDA18273/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/dp10048
