# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =    \
    DVS      \
    InMemory \

include $(PLAYREADY_DIR)/GNUmakefile.common

