obj-$(CONFIG_APCORE_IP_EPG) += xmgr_epg_ip_humax_ukdtt.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path
