#include "nexus_platform.h"
/*#include "nexus_gpio_module.h"*/
#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"
 
const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
/*/////////////   11 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//11  */
/*//////////////  58 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//58  */  /* SC0_VCC */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//59  */  /* SC0_CLK */
/*//////////////  60 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//60  */  /* SC0_RST */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//61  */  /* SC0_IO */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//62  */  /* SC0_PRES */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//63  */  /* SC0_AUX1 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//64  */  /* SC0_AUX2 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//65  */  /* SC0_VPP */
/*//////////////  70 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT5,	/*//79  */  /* MTSIF0_CLK */
/*//////////////  80 //////////////*/ 
	HUMAX_GPIO_FUNCTION_ALT5,	/*//80  */  /* MTSIF0_DATA0 */
	HUMAX_GPIO_FUNCTION_ALT5,	/*//81  */  /* MTSIF0_SYNC */
	HUMAX_GPIO_FUNCTION_ALT5,	/*//82  */  /* MTSIF0_DATA1 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//83  */  /* N.C. */
	HUMAX_GPIO_FUNCTION_ALT5,	/*//84  */  /* MTSIF0_DATA2 */
	HUMAX_GPIO_FUNCTION_ALT5,	/*//85  */  /* MTSIF0_DATA3 */
	HUMAX_GPIO_FUNCTION_ALT5,	/*//86  */  /* MTSIF0_DATA4 */
	HUMAX_GPIO_FUNCTION_ALT5,	/*//87  */  /* MTSIF0_DATA5 */
	HUMAX_GPIO_FUNCTION_ALT5,	/*//88  */  /* MTSIF0_DATA6 */
	HUMAX_GPIO_FUNCTION_ALT5,	/*//89  */  /* MTSIF0_DATA7 */
/*//////////////  90 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//90  */  /**/
	HUMAX_GPIO_FUNCTION_ALT5,	/*//91  */  /* MTSIF0_INC */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//92  */  /* NTSIF0_RST */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//93  */  /* GP_DEMOD_IRQ */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//94  */  /* GP_DEMOD_RST */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//95  */  /* GP_ENET_LED */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//96  */  /* ENET_LINK */
	HUMAX_GPIO_FUNCTION_ALT4,	/*//97  */  /* ENET_ACT */ 
/*////////////// 110 //////////////*/	
	HUMAX_GPIO_FUNCTION_ALT1,	/*//110  */  /* UART_TXD_0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//111  */  /* UART_RXD_0 */
	
/*////////////// AON_GPIO 00(0~20)//////////////*/	
	HUMAX_GPIO_FUNCTION_NCTP,	/*//0  */  /**/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//1  */  /**/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//2  */  /**/
	HUMAX_GPIO_FUNCTION_GPIO,	/*//3  */  /* FR_LED_STBY */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//4  */  /* FR_LED_POWER */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//5  */  /**/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//6  */  /**/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//7  */  /**/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//8  */  /**/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//9  */  /**/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//10  */ /**/

	HUMAX_GPIO_FUNCTION_NCTP,	/*//11  */  /**/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//12  */  /**/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//13  */  /**/
	HUMAX_GPIO_FUNCTION_GPIO,	/*//14  */  /* LED POWER */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//15  */  /**/
	HUMAX_GPIO_FUNCTION_ALT3,	/*//16  */  /* SPI_CLK*/
	HUMAX_GPIO_FUNCTION_ALT3,	/*//17  */  /* SPI_MOSI */
	HUMAX_GPIO_FUNCTION_ALT3,	/*//18  */  /* SPI_MISO */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//19  */  /* SPI_STR (Control GPIO) */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//20  */  /* GP_HDD_PWR_CTRL */

/*////////////// AON_SGPIO (0~1,4~7) //////////////*/	
	HUMAX_GPIO_FUNCTION_ALT1,	/*//0  */ /* HDMI_BSC_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//1  */ /* HDMI_BSC_SDA */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//4  */ /**/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//5  */ /**/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//6  */ /* I2C_DEMOD_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*//7  */ /* I2C_DEMOD_SDA */
};

/*************************
*	gpio: 11, 58~65, 79, 80~97 : 2 + 8 + 18 = 30
*	sgpio: NONE : NONE
*	aon_gpio: 0~20 : 21
*	aon_sgpio: 0~1,4~7 : 6
*************************/
HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
/* GPIO */
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_onoff_gpio_011_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_onoff_gpio_011_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_onoff_gpio_058_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_onoff_gpio_058_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_059_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_059_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_060_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_060_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_061_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_061_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_062_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_062_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_063_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_063_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_064_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_064_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_065_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_065_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_079_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_onoff_gpio_079_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_080_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_080_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_081_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_081_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_082_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_082_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_083_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_083_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_084_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_084_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_085_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_085_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_086_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_086_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_087_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_onoff_gpio_087_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_088_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_088_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_089_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_089_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_090_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_090_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_091_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_091_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_092_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_092_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_093_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_093_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_094_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_094_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_095_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_onoff_gpio_095_SHIFT},

    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_onoff_gpio_096_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_onoff_gpio_096_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_onoff_gpio_097_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_onoff_gpio_097_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_onoff_gpio_110_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_onoff_gpio_110_SHIFT},
    {BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_onoff_gpio_111_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_onoff_gpio_111_SHIFT},

/* AON GPIO */
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_02_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_06_SHIFT},

    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_14_SHIFT},

    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_SHIFT},

/* AON SGPIO */
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_01_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_04_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_05_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_06_SHIFT},
    {BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_07_SHIFT}
};
