obj-y += bus_mgrobj.o
obj-y += bus_lnklist.o
obj-y += bus_main.o
obj-y += bus_timer.o

# Basic include path

# Additional include path
ccflags-y += -I$(OCTO_DIR)/main/oxserver
ccflags-y += -I$(OCTO_TVMANAGER_DIR)/bus/include

