# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =       \
    base        \
    oaeppssimpl \
    oaeppss     \
    hsm         \

include $(PLAYREADY_DIR)/GNUmakefile.common

