#!/bin/sh

IF_WAN=$1

/usr/local/sbin/smcroute -k
/bin/kill -KILL $(cat /tmp/mdns-repeater.pid)
/usr/local/sbin/iptables -t nat -F
/usr/local/sbin/iptables -t mangle -F

#Terminating mdns-repeater takes hundreds milliseconds
sleep 1

# NAT
/usr/local/sbin/iptables -t nat -A POSTROUTING -o $IF_WAN -j MASQUERADE

# MC Packet 
ifconfig $IF_WAN promisc
/usr/local/sbin/smcroute -d
/usr/local/sbin/smcroute -a $IF_WAN 0.0.0.0 239.255.255.250 br0
/usr/local/sbin/smcroute -a br0 10.255.128.213 239.255.255.250 $IF_WAN

# Bonjour
/usr/local/sbin/mdns-repeater $IF_WAN br0 -p /tmp/mdns-repeater.pid

# UPnP
/usr/local/sbin/iptables -t mangle -A PREROUTING -d 224.0.0.0/240.0.0.0 -j TTL --ttl-inc 1
/usr/local/sbin/iptables -t nat -A PREROUTING -p udp -i $IF_WAN --dport dlna-start:dlna-end -j DNAT --to 10.255.128.213

#DMS
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 50001 -j DNAT --to 10.255.128.213:50001
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 9000 -j DNAT --to 10.255.128.213:9000
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 9001 -j DNAT --to 10.255.128.213:9001
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 9002 -j DNAT --to 10.255.128.213:9002

# DMP loopback error 2014-04-01
#/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i br0 --dport 9000 -j DNAT --to 10.255.128.213:9000
#/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i br0 --dport 9001 -j DNAT --to 10.255.128.213:9001
#/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i br0 --dport 9002 -j DNAT --to 10.255.128.213:9002

#DMR
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 55200 -j DNAT --to 10.255.128.213:55200

#DIAL
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 56789 -j DNAT --to 10.255.128.213:56789
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 56790 -j DNAT --to 10.255.128.213:56790

#SATIP
/usr/local/sbin/iptables -t nat -A PREROUTING -p udp -i $IF_WAN --dport satip-ssdp -j DNAT --to 10.255.128.213:49554
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 554 -j DNAT --to 10.255.128.213:50554
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 50555 -j DNAT --to 10.255.128.213:50555

#AirPlay
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 36667 -j DNAT --to 10.255.128.213:36667
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 36666 -j DNAT --to 10.255.128.213:36666
/usr/local/sbin/iptables -t nat -A PREROUTING -p udp -i $IF_WAN --dport airtunes-start:airtunes-end -j DNAT --to 10.255.128.211

#RC
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 58801 -j DNAT --to 10.255.128.213:58801
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 58802 -j DNAT --to 10.255.128.213:58802
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 58803 -j DNAT --to 10.255.128.213:58803

#etc
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 80 -j DNAT --to 10.255.128.213:80
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 8080 -j DNAT --to 10.255.128.213:8080
/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp -i $IF_WAN --dport 443 -j DNAT --to 10.255.128.213:443

