/***************************************************************************
 *     Copyright (c) 1999-2010, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_aud_fmm_dp_esr20.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 5/7/10 9:39p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri May  7 20:12:22 2010
 *                 MD5 Checksum         9170aeef162fecc7d1a70fbd8134c303
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7468/rdb/b0/bchp_aud_fmm_dp_esr20.h $
 * 
 * Hydra_Software_Devel/1   5/7/10 9:39p albertl
 * SW7468-226: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_AUD_FMM_DP_ESR20_H__
#define BCHP_AUD_FMM_DP_ESR20_H__

/***************************************************************************
 *AUD_FMM_DP_ESR20 - FMM_DP Error Status for HOST 0
 ***************************************************************************/
#define BCHP_AUD_FMM_DP_ESR20_STATUS             0x00397c80 /* Error Status Register */
#define BCHP_AUD_FMM_DP_ESR20_STATUS_SET         0x00397c84 /* Error Set Register */
#define BCHP_AUD_FMM_DP_ESR20_STATUS_CLEAR       0x00397c88 /* Error Clear Register */
#define BCHP_AUD_FMM_DP_ESR20_MASK               0x00397c8c /* Mask Status Register */
#define BCHP_AUD_FMM_DP_ESR20_MASK_SET           0x00397c90 /* Mask Set Register */
#define BCHP_AUD_FMM_DP_ESR20_MASK_CLEAR         0x00397c94 /* Mask Clear Register */

#endif /* #ifndef BCHP_AUD_FMM_DP_ESR20_H__ */

/* End of File */
