/***************************************************************************
 *     Copyright (c) 1999-2010, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_sun_gisb_arb_sec.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 5/7/10 11:29p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri May  7 20:16:44 2010
 *                 MD5 Checksum         9170aeef162fecc7d1a70fbd8134c303
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7468/rdb/b0/bchp_sun_gisb_arb_sec.h $
 * 
 * Hydra_Software_Devel/1   5/7/10 11:29p albertl
 * SW7468-226: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_SUN_GISB_ARB_SEC_H__
#define BCHP_SUN_GISB_ARB_SEC_H__

/***************************************************************************
 *SUN_GISB_ARB_SEC - GISB Arbiter secure registers
 ***************************************************************************/
#define BCHP_SUN_GISB_ARB_SEC_RSV_S              0x0030e000 /* RESERVED */
#define BCHP_SUN_GISB_ARB_SEC_RSV_E              0x0030e064 /* RESERVED */

/***************************************************************************
 *RSV_S - RESERVED
 ***************************************************************************/
/* SUN_GISB_ARB_SEC :: RSV_S :: reserved0 [31:00] */
#define BCHP_SUN_GISB_ARB_SEC_RSV_S_reserved0_MASK                 0xffffffff
#define BCHP_SUN_GISB_ARB_SEC_RSV_S_reserved0_SHIFT                0

/***************************************************************************
 *RSV_E - RESERVED
 ***************************************************************************/
/* SUN_GISB_ARB_SEC :: RSV_E :: reserved0 [31:00] */
#define BCHP_SUN_GISB_ARB_SEC_RSV_E_reserved0_MASK                 0xffffffff
#define BCHP_SUN_GISB_ARB_SEC_RSV_E_reserved0_SHIFT                0

#endif /* #ifndef BCHP_SUN_GISB_ARB_SEC_H__ */

/* End of File */
