obj-y += xsvc_epg_process_tvtv_main.o
obj-y += xsvc_epg_tvtv_data.o
obj-y += xsvc_epg_tvtv_lib.o
obj-y += xsvc_epg_context_tvtv.o
obj-y += xsvc_epg_tvtv_db_lib.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path
ccflags-y += -I$(OCTO_TVSERVICE_DIR)/pal/include

