obj-y += pal_hdmi.o

# Basic include path
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/pal/include
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/include
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.pal
# Additional include path

