obj-y += dbus_server.o
obj-y += dbus_util_cvt.o

obj-y +=  as_apk_media_airplay.o
obj-y +=  as_apk_util_builder.o
obj-y +=  as_apk_cas_action.o
obj-y +=  as_apk_cas_ci.o
obj-y +=  as_apk_cas_irdeto.o
obj-y +=  as_apk_cas_mmi.o
obj-y +=  as_apk_cas_nagra.o
obj-y +=  as_apk_util_datastreamer.o
obj-y +=  as_apk_util_db.o
obj-y +=  as_apk_dlna_util.o
obj-y +=  as_apk_util_drmagent.o
obj-y +=  as_apk_util_dsmcc.o
#obj-y +=  as_apk_util_event.o
obj-y +=  as_apk_util_exe.o
obj-y +=  as_apk_util_extdev.o
obj-y +=  as_apk_filemgr_base.o
obj-y +=  as_apk_filemgr_browse.o
obj-y +=  as_apk_filemgr_ftpserver.o
obj-y +=  as_apk_filemgr_group.o
obj-y +=  as_apk_filemgr_sambaclient.o
obj-y +=  as_apk_filemgr_sambaserver.o
obj-y +=  as_apk_filemgr_storage.o
obj-y +=  as_apk_media_play.o
obj-y +=  as_apk_media_record.o
obj-y +=  as_apk_meta_antenna.o
#obj-y +=  as_apk_meta_mail.o
obj-y +=  as_apk_meta_query.o
obj-y +=  as_apk_meta_record.o
obj-y +=  as_apk_meta_schedule.o
#obj-y +=  as_apk_meta_search.o
obj-y +=  as_apk_meta_service.o
obj-y +=  as_apk_util_network.o
obj-y +=  as_apk_output_audio.o
obj-y +=  as_apk_output_hdmi.o
obj-y +=  as_apk_output_panel.o
obj-y +=  as_apk_output_video.o
obj-y +=  as_apk_util_power.o
obj-y +=  as_apk_scenario_base.o
obj-y +=  as_apk_scenario_pincode.o
obj-y +=  as_apk_util_swupdate.o
obj-y +=  as_apk_sysinfo_stb.o
obj-y +=  as_apk_sysinfo_tuner.o



obj-y += as_apk_module_submodule.o

# Additional include path
ccflags-y += -I$(APPLTOP_SRC_DIR)/octopus/appkit_server/include
