obj-y += pl_satip.o

# DLNA 3rd-party include path
include $(OCTOSVC_SRC_DIR)/homma/main/module/include/Makefile.include.mxlib

ccflags-$(CONFIG_HOMMA_SATIP) += -I$(THIRDPARTY_DIR)/dlna/mxlib/mxsatip
