obj-y								+= base/
obj-$(CONFIG_OP_ZIGGO_EMM_UPDATE)	+= ziggo/

obj-y	+= xmgr_emmupdate.o
obj-y	+= pmgr_emmupdate.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

