obj-y += nx_core_shahid.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include
ccflags-y += -I$(NATIVEAPP_CORE_INCLUDE_DIR)/include

# Additional include path
ccflags-y += -I$(NATIVEAPP_PORT_INCLUDE_DIR)/include