obj-y += xmgr_rec_viaccess_base.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw

# Additional include path
#ccflags-y += -I$(OCTO_TVMANAGER_PLUGIN_DIR)/xmgr/pvr/local_include
ccflags-y += -I$(OCTO_TVSERVICE_PLUGIN_DIR)/xsvc/cas/viaccess/ui
