obj-y += mgr_live.o
obj-y += mgr_live_zap.o
obj-$(CONFIG_MW_MM_PVR) += mgr_live_pincode.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr

# Additional include path
ccflags-y += -I$(OCTO_TVMANAGER_DIR)/include_plugin

