#
obj-y += tmbslTDA10025_Cfg.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/dp10025/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/dp10025/tmbslHCDP/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/dp10025/tmbslTDA10025/cfg
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/dp10025/tmbslTDA10025/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/cab/dp10025/tmbslTDA10025/src

