obj-y += oapi_rpcprotocol.o
obj-y += oapi_datastreamer.o
#obj-y += oapi_deprecated.o
#obj-y += thapi.o
#obj-y += uapi.o
#obj-y += protocol/
obj-y += module/

# ---- include path----
ccflags-y += -I$(HLIB_DIR)/include
ccflags-y += -I$(OCTO_DIR)/include
ccflags-y += -I$(OCTO_DIR)/api/protocol
ccflags-y += -I$(OCTO_DIR)/main/oxserver/include

#ccflags-y += -I$(OCTO_DIR)/main/umma
#ccflags-y += -I$(OCTO_DIR)/main/thma

