-include ./dirs

ifeq ($(DIRS),)
TARGET = contentrevocationstub

SOURCES =                \
	contentrevocationlevlstub.c contentrevocationlicstub.c contentrevocationutilstub.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
