#!/bin/sh

[ -x /usr/sbin/dnsmasq ] || exit 0

. /lib/lsb/init-functions
. /etc/default/rcS

case "$1" in
	start)
		if [ "$VERBOSE" != no ]; then
			log_begin_msg "Starting dnsmasq..."
		fi
		#exec /usr/sbin/dnsmasq
		;;
	stop)
		if [ "$VERBOSE" != no ]; then
			log_begin_msg "Stopping dnsmasq..."
		fi
		killall dnsmasq
		;;
	*)
		if [ "$VERBOSE" != no ]; then
			log_success_msg "Usage: /etc/init.d/S41dnsmasq {start | stop}"
		fi
		exit 1
		;;
esac

