/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_int_id_sm_l2.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 4/4/11 1:41p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Apr  1 16:56:07 2011
 *                 MD5 Checksum         d03d08c4839c3311c9d35c4cd5e10373
 *
 * Compiled with:  RDB Utility          unknown
 *                 RDB Parser           3.0
 *                 generate_int_id.pl   1.0
 *                 Perl Interpreter     5.008005
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7344/rdb/b0/bchp_int_id_sm_l2.h $
 * 
 * Hydra_Software_Devel/1   4/4/11 1:41p albertl
 * SW7344-40: Initial revision.
 *
 ***************************************************************************/

#include "bchp.h"
#include "bchp_sm_l2.h"

#ifndef BCHP_INT_ID_SM_L2_H__
#define BCHP_INT_ID_SM_L2_H__

#define BCHP_INT_ID_SM_IRQ                    BCHP_INT_ID_CREATE(BCHP_SM_L2_CPU_STATUS, BCHP_SM_L2_CPU_STATUS_SM_IRQ_SHIFT)
#define BCHP_INT_ID_SM_RX_FIFO_INTR           BCHP_INT_ID_CREATE(BCHP_SM_L2_CPU_STATUS, BCHP_SM_L2_CPU_STATUS_SM_RX_FIFO_INTR_SHIFT)
#define BCHP_INT_ID_SM_TX_FIFO_INTR           BCHP_INT_ID_CREATE(BCHP_SM_L2_CPU_STATUS, BCHP_SM_L2_CPU_STATUS_SM_TX_FIFO_INTR_SHIFT)

#endif /* #ifndef BCHP_INT_ID_SM_L2_H__ */

/* End of File */
