
var OAPI = function(appName) {
	// TODO: initialization

	if(!("WebSocket" in window)) {
		throw "'WebSocket' does NOT supported!";
	}

	var a = this;
	a.name = appName;
}

OAPI.prototype.name = 'Unknown';
OAPI.prototype.socket = null;
OAPI.prototype.id = 0;
OAPI.prototype.onmessage = {
	success : null,
	error : null
};

OAPI.prototype.open = function(url, success, error) {
	var a = this;

	console.log("open: " + url);

	try {
		a.socket = new WebSocket(url, "octo-protocol-via-websocket");
	} catch (e) {
		console.log("new WebSocket(" + url + ") error!");
		error(e);
		return;
	}

	a.socket.onopen = function() {
		console.log("socket.onopen");

		a.query({
			"application" : {
				"target" : a.name,
				"operation" : "start"
			}
		}, success, error);
	}

	a.socket.onclose = function() {
		console.log("socket.onclose");
		error();
	}

	a.socket.onmessage = function(e) {
		console.log("socket.onmessage: " + e.data);

		try {
			// 뒤에 뭐가 붙는지 하나 잘라줘야 동작함 ...
			var message = JSON.parse(e.data.substr(0, e.data.length - 1));
		} catch (e) {
			console.log(e);
		}

		a.id = message.id;

		if(message.hugedata) {
			console.log(message);
			a.query({
				"datastorage" : {
					"accesscode" : message.hugedata.accesscode,
					"operation" : "get"
				}
			}, a.onmessage.success, a.onmessage.error);
		} else {
			if(a.onmessage.success)
				a.onmessage.success(message);
		}
	}

	a.socket.onerror = function(e) {
		console.log("socket.onerror: " + e);

		if(a.onmessage.error)
			a.onmessage.error();
	}
}

OAPI.prototype.close = function() {
	var a = this;

	console.log("close");

	a.socket = null;

}

OAPI.prototype.call = function(command) {
	var a = this;

	if(!(a.socket) || a.socket.readyState != WebSocket.OPEN)
		throw "'OAPI' does not opened!!";

	command.id = a.id;
	a.socket.send(JSON.stringify(command));
}

OAPI.prototype.query = function(command, success, error) {
	var a = this;

	if(!(a.socket) || a.socket.readyState != WebSocket.OPEN)
		throw "'OAPI does not opened!!";

	a.onmessage.success = success;
	a.onmessage.error = error;

	command.id = a.id;
	a.socket.send(JSON.stringify(command));

	return null;
}


// for debug
function DEBUG_getServiceList() {
	return {
		service : [{
			svc_uid : 1,
			ts_uid : 1,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28205,
			tsid : 1073,
			onid : 1,
			lcn : 1,
			pmt_pid : 500,
			pcr_pid : 601,
			video_pid : 601,
			audio_pid : 602,
			name : "rbb Brandenburg",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 2,
			ts_uid : 1,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28206,
			tsid : 1073,
			onid : 1,
			lcn : 2,
			pmt_pid : 600,
			pcr_pid : 601,
			video_pid : 601,
			audio_pid : 602,
			name : "rbb Berlin",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 3,
			ts_uid : 1,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28221,
			tsid : 1073,
			onid : 1,
			lcn : 3,
			pmt_pid : 2100,
			pcr_pid : 2601,
			video_pid : 2601,
			audio_pid : 602,
			name : "ARD-TEST-1",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 4,
			ts_uid : 1,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28224,
			tsid : 1073,
			onid : 1,
			lcn : 4,
			pmt_pid : 2400,
			pcr_pid : 2601,
			video_pid : 2601,
			audio_pid : 2602,
			name : "NDR FS MV",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 5,
			ts_uid : 1,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28225,
			tsid : 1073,
			onid : 1,
			lcn : 5,
			pmt_pid : 2500,
			pcr_pid : 2601,
			video_pid : 2601,
			audio_pid : 2602,
			name : "NDR FS HH",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 6,
			ts_uid : 1,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28226,
			tsid : 1073,
			onid : 1,
			lcn : 6,
			pmt_pid : 2600,
			pcr_pid : 2601,
			video_pid : 2601,
			audio_pid : 2602,
			name : "NDR FS NDS",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 7,
			ts_uid : 1,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28227,
			tsid : 1073,
			onid : 1,
			lcn : 7,
			pmt_pid : 2700,
			pcr_pid : 2601,
			video_pid : 2601,
			audio_pid : 2602,
			name : "NDR FS SH",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 8,
			ts_uid : 1,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28228,
			tsid : 1073,
			onid : 1,
			lcn : 8,
			pmt_pid : 2800,
			pcr_pid : 2901,
			video_pid : 2901,
			audio_pid : 2902,
			name : "MDR Sachsen",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 9,
			ts_uid : 1,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28229,
			tsid : 1073,
			onid : 1,
			lcn : 9,
			pmt_pid : 2900,
			pcr_pid : 2901,
			video_pid : 2901,
			audio_pid : 2902,
			name : "MDR S-Anhalt",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 10,
			ts_uid : 1,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28230,
			tsid : 1073,
			onid : 1,
			lcn : 10,
			pmt_pid : 3000,
			pcr_pid : 2901,
			video_pid : 2901,
			audio_pid : 2902,
			name : "MDR Thuringen",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 11,
			ts_uid : 1,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28231,
			tsid : 1073,
			onid : 1,
			lcn : 11,
			pmt_pid : 3100,
			pcr_pid : 3101,
			video_pid : 3101,
			audio_pid : 3102,
			name : "SWR Fernsehen RP",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 12,
			ts_uid : 2,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 17500,
			tsid : 1107,
			onid : 1,
			lcn : 12,
			pmt_pid : 96,
			pcr_pid : 255,
			video_pid : 255,
			audio_pid : 256,
			name : "SAT.1",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 13,
			ts_uid : 2,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 17501,
			tsid : 1107,
			onid : 1,
			lcn : 13,
			pmt_pid : 97,
			pcr_pid : 511,
			video_pid : 511,
			audio_pid : 512,
			name : "ProSieben",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 14,
			ts_uid : 2,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 17502,
			tsid : 1107,
			onid : 1,
			lcn : 14,
			pmt_pid : 98,
			pcr_pid : 767,
			video_pid : 767,
			audio_pid : 768,
			name : "kabel eins",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 15,
			ts_uid : 2,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 17503,
			tsid : 1107,
			onid : 1,
			lcn : 15,
			pmt_pid : 99,
			pcr_pid : 1023,
			video_pid : 1023,
			audio_pid : 1024,
			name : "N24",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 16,
			ts_uid : 2,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 17504,
			tsid : 1107,
			onid : 1,
			lcn : 16,
			pmt_pid : 100,
			pcr_pid : 1279,
			video_pid : 1279,
			audio_pid : 1280,
			name : "SIXX",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 17,
			ts_uid : 2,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 17505,
			tsid : 1107,
			onid : 1,
			lcn : 17,
			pmt_pid : 101,
			pcr_pid : 1535,
			video_pid : 1535,
			audio_pid : 1536,
			name : "Sat.1 Comedy",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 18,
			ts_uid : 2,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 17506,
			tsid : 1107,
			onid : 1,
			lcn : 18,
			pmt_pid : 102,
			pcr_pid : 1791,
			video_pid : 1791,
			audio_pid : 1792,
			name : "kabel eins classics",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 19,
			ts_uid : 2,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 17507,
			tsid : 1107,
			onid : 1,
			lcn : 19,
			pmt_pid : 103,
			pcr_pid : 255,
			video_pid : 255,
			audio_pid : 256,
			name : "SAT.1 Bayern",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 20,
			ts_uid : 2,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 17508,
			tsid : 1107,
			onid : 1,
			lcn : 20,
			pmt_pid : 104,
			pcr_pid : 255,
			video_pid : 255,
			audio_pid : 256,
			name : "SAT.1 NRW",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 21,
			ts_uid : 3,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 61200,
			tsid : 1057,
			onid : 1,
			lcn : 21,
			pmt_pid : 96,
			pcr_pid : 255,
			video_pid : 255,
			audio_pid : 8192,
			name : "RTL HD",
			video_codec : "H.264",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "hd",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 22,
			ts_uid : 3,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 61201,
			tsid : 1057,
			onid : 1,
			lcn : 22,
			pmt_pid : 97,
			pcr_pid : 511,
			video_pid : 511,
			audio_pid : 8192,
			name : "VOX HD",
			video_codec : "H.264",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "hd",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 23,
			ts_uid : 3,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 61202,
			tsid : 1057,
			onid : 1,
			lcn : 23,
			pmt_pid : 8192,
			pcr_pid : 8192,
			video_pid : 8192,
			audio_pid : 8192,
			name : ".",
			svctype : "tv",
			videotype : "hd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 24,
			ts_uid : 3,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 61203,
			tsid : 1057,
			onid : 1,
			lcn : 24,
			pmt_pid : 8192,
			pcr_pid : 8192,
			video_pid : 8192,
			audio_pid : 8192,
			name : ".",
			svctype : "tv",
			videotype : "hd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 25,
			ts_uid : 3,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 61204,
			tsid : 1057,
			onid : 1,
			lcn : 25,
			pmt_pid : 100,
			pcr_pid : 1279,
			video_pid : 1279,
			audio_pid : 8192,
			name : "SPORT1 HD",
			video_codec : "H.264",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "hd",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 26,
			ts_uid : 3,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 61205,
			tsid : 1057,
			onid : 1,
			lcn : 26,
			pmt_pid : 101,
			pcr_pid : 1535,
			video_pid : 1535,
			audio_pid : 8192,
			name : "RTL2 HD",
			video_codec : "H.264",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "hd",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 27,
			ts_uid : 4,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28007,
			tsid : 1079,
			onid : 1,
			lcn : 27,
			pmt_pid : 200,
			pcr_pid : 210,
			video_pid : 210,
			audio_pid : 220,
			name : "3sat",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 28,
			ts_uid : 4,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28012,
			tsid : 1079,
			onid : 1,
			lcn : 1,
			pmt_pid : 700,
			pcr_pid : 710,
			video_pid : 8192,
			audio_pid : 710,
			name : "DKULTUR",
			audio_codec : "MPEG",
			svctype : "radio",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 29,
			ts_uid : 4,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28013,
			tsid : 1079,
			onid : 1,
			lcn : 2,
			pmt_pid : 800,
			pcr_pid : 810,
			video_pid : 8192,
			audio_pid : 810,
			name : "DLF",
			audio_codec : "MPEG",
			svctype : "radio",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 30,
			ts_uid : 4,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28008,
			tsid : 1079,
			onid : 1,
			lcn : 28,
			pmt_pid : 300,
			pcr_pid : 310,
			video_pid : 310,
			audio_pid : 320,
			name : "KI.KA",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 31,
			ts_uid : 4,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28006,
			tsid : 1079,
			onid : 1,
			lcn : 29,
			pmt_pid : 100,
			pcr_pid : 110,
			video_pid : 110,
			audio_pid : 120,
			name : "ZDF",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 32,
			ts_uid : 4,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28014,
			tsid : 1079,
			onid : 1,
			lcn : 30,
			pmt_pid : 650,
			pcr_pid : 660,
			video_pid : 660,
			audio_pid : 670,
			name : "zdf_neo",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 33,
			ts_uid : 4,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28011,
			tsid : 1079,
			onid : 1,
			lcn : 31,
			pmt_pid : 600,
			pcr_pid : 610,
			video_pid : 610,
			audio_pid : 620,
			name : "ZDFinfo",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 34,
			ts_uid : 4,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28016,
			tsid : 1079,
			onid : 1,
			lcn : 32,
			pmt_pid : 1100,
			pcr_pid : 1110,
			video_pid : 1110,
			audio_pid : 1120,
			name : "zdf.kultur",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 35,
			ts_uid : 4,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28017,
			tsid : 1079,
			onid : 1,
			lcn : 3,
			pmt_pid : 411,
			pcr_pid : 410,
			video_pid : 8192,
			audio_pid : 410,
			name : "DRadio Wissen",
			audio_codec : "MPEG",
			svctype : "radio",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 36,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12003,
			tsid : 1089,
			onid : 1,
			lcn : 33,
			pmt_pid : 44,
			pcr_pid : 163,
			video_pid : 163,
			audio_pid : 104,
			name : "RTL Television",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 37,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12020,
			tsid : 1089,
			onid : 1,
			lcn : 34,
			pmt_pid : 46,
			pcr_pid : 166,
			video_pid : 166,
			audio_pid : 128,
			name : "RTL2",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 38,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12040,
			tsid : 1089,
			onid : 1,
			lcn : 35,
			pmt_pid : 45,
			pcr_pid : 165,
			video_pid : 165,
			audio_pid : 120,
			name : "SUPER RTL",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 39,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12060,
			tsid : 1089,
			onid : 1,
			lcn : 36,
			pmt_pid : 47,
			pcr_pid : 167,
			video_pid : 167,
			audio_pid : 136,
			name : "VOX",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 40,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12090,
			tsid : 1089,
			onid : 1,
			lcn : 37,
			pmt_pid : 48,
			pcr_pid : 169,
			video_pid : 169,
			audio_pid : 73,
			name : "n-tv",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 41,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12080,
			tsid : 1089,
			onid : 1,
			lcn : 38,
			pmt_pid : 41,
			pcr_pid : 168,
			video_pid : 168,
			audio_pid : 137,
			name : "Channel 21",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 42,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12041,
			tsid : 1089,
			onid : 1,
			lcn : 39,
			pmt_pid : 52,
			pcr_pid : 172,
			video_pid : 172,
			audio_pid : 145,
			name : "SUPER RTL CH",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 43,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12061,
			tsid : 1089,
			onid : 1,
			lcn : 40,
			pmt_pid : 53,
			pcr_pid : 173,
			video_pid : 173,
			audio_pid : 146,
			name : "VOX CH",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 44,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12005,
			tsid : 1089,
			onid : 1,
			lcn : 41,
			pmt_pid : 55,
			pcr_pid : 163,
			video_pid : 163,
			audio_pid : 104,
			name : "RTL HB NDS",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 45,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12004,
			tsid : 1089,
			onid : 1,
			lcn : 42,
			pmt_pid : 54,
			pcr_pid : 163,
			video_pid : 163,
			audio_pid : 104,
			name : "RTL HH SH",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 46,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12006,
			tsid : 1089,
			onid : 1,
			lcn : 43,
			pmt_pid : 56,
			pcr_pid : 163,
			video_pid : 163,
			audio_pid : 104,
			name : "RTL FS",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 47,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12030,
			tsid : 1089,
			onid : 1,
			lcn : 44,
			pmt_pid : 58,
			pcr_pid : 301,
			video_pid : 301,
			audio_pid : 303,
			name : "RTL Living",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 48,
			ts_uid : 5,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 12095,
			tsid : 1089,
			onid : 1,
			lcn : 45,
			pmt_pid : 49,
			pcr_pid : 168,
			video_pid : 168,
			audio_pid : 137,
			name : "Channel 21",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 49,
			ts_uid : 6,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28306,
			tsid : 1201,
			onid : 1,
			lcn : 46,
			pmt_pid : 300,
			pcr_pid : 101,
			video_pid : 101,
			audio_pid : 102,
			name : "WDR Bielefeld",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 50,
			ts_uid : 6,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28307,
			tsid : 1201,
			onid : 1,
			lcn : 47,
			pmt_pid : 400,
			pcr_pid : 101,
			video_pid : 101,
			audio_pid : 102,
			name : "WDR Dortmund",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 51,
			ts_uid : 6,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28308,
			tsid : 1201,
			onid : 1,
			lcn : 48,
			pmt_pid : 500,
			pcr_pid : 101,
			video_pid : 101,
			audio_pid : 102,
			name : "WDR Dusseldorf",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 52,
			ts_uid : 6,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28309,
			tsid : 1201,
			onid : 1,
			lcn : 49,
			pmt_pid : 600,
			pcr_pid : 101,
			video_pid : 101,
			audio_pid : 102,
			name : "WDR Essen",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 53,
			ts_uid : 6,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28310,
			tsid : 1201,
			onid : 1,
			lcn : 50,
			pmt_pid : 700,
			pcr_pid : 101,
			video_pid : 101,
			audio_pid : 102,
			name : "WDR Munster",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 54,
			ts_uid : 6,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28311,
			tsid : 1201,
			onid : 1,
			lcn : 51,
			pmt_pid : 800,
			pcr_pid : 101,
			video_pid : 101,
			audio_pid : 102,
			name : "WDR Siegen",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 55,
			ts_uid : 6,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28385,
			tsid : 1201,
			onid : 1,
			lcn : 52,
			pmt_pid : 1200,
			pcr_pid : 1201,
			video_pid : 1201,
			audio_pid : 1202,
			name : "Radio Bremen TV",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 56,
			ts_uid : 6,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28394,
			tsid : 1201,
			onid : 1,
			lcn : 53,
			pmt_pid : 1400,
			pcr_pid : 1601,
			video_pid : 1601,
			audio_pid : 1602,
			name : "WDR Test B",
			video_codec : "H.264",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "hd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 57,
			ts_uid : 6,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28395,
			tsid : 1201,
			onid : 1,
			lcn : 54,
			pmt_pid : 1500,
			pcr_pid : 101,
			video_pid : 101,
			audio_pid : 102,
			name : "WDR Test A",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 58,
			ts_uid : 6,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28396,
			tsid : 1201,
			onid : 1,
			lcn : 55,
			pmt_pid : 1600,
			pcr_pid : 1601,
			video_pid : 1601,
			audio_pid : 1602,
			name : "Einsfestival HD",
			video_codec : "H.264",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "hd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 59,
			ts_uid : 6,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28397,
			tsid : 1201,
			onid : 1,
			lcn : 4,
			pmt_pid : 1800,
			pcr_pid : 2001,
			video_pid : 8192,
			audio_pid : 2001,
			name : "MEHRKANALTEST",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "radio",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 60,
			ts_uid : 7,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28534,
			tsid : 1111,
			onid : 1,
			lcn : 56,
			pmt_pid : 34,
			pcr_pid : 3301,
			video_pid : 3301,
			audio_pid : 3302,
			name : "WDR Aachen",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 61,
			ts_uid : 7,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28535,
			tsid : 1111,
			onid : 1,
			lcn : 57,
			pmt_pid : 35,
			pcr_pid : 3301,
			video_pid : 3301,
			audio_pid : 3302,
			name : "WDR Wuppertal",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 62,
			ts_uid : 7,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28536,
			tsid : 1111,
			onid : 1,
			lcn : 58,
			pmt_pid : 36,
			pcr_pid : 3301,
			video_pid : 3301,
			audio_pid : 3302,
			name : "WDR Bonn",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 63,
			ts_uid : 7,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 28537,
			tsid : 1111,
			onid : 1,
			lcn : 59,
			pmt_pid : 37,
			pcr_pid : 3301,
			video_pid : 3301,
			audio_pid : 3302,
			name : "WDR Duisburg",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 64,
			ts_uid : 7,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 7292,
			tsid : 1111,
			onid : 1,
			lcn : 5,
			pmt_pid : 7292,
			pcr_pid : 1292,
			video_pid : 8192,
			audio_pid : 1292,
			name : "Radio neue Hoffnung",
			audio_codec : "MPEG",
			svctype : "radio",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 65,
			ts_uid : 7,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 7298,
			tsid : 1111,
			onid : 1,
			lcn : 6,
			pmt_pid : 38,
			pcr_pid : 33,
			video_pid : 8192,
			audio_pid : 3607,
			name : "Radio Maryja",
			audio_codec : "MPEG",
			svctype : "radio",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 66,
			ts_uid : 7,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 7289,
			tsid : 1111,
			onid : 1,
			lcn : 7,
			pmt_pid : 7289,
			pcr_pid : 1289,
			video_pid : 8192,
			audio_pid : 1289,
			name : "Radio Horeb",
			audio_codec : "MPEG",
			svctype : "radio",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 67,
			ts_uid : 7,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 7290,
			tsid : 1111,
			onid : 1,
			lcn : 60,
			pmt_pid : 7290,
			pcr_pid : 6290,
			video_pid : 1290,
			audio_pid : 2290,
			name : "Sky News Intl",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 68,
			ts_uid : 7,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 7266,
			tsid : 1111,
			onid : 1,
			lcn : 61,
			pmt_pid : 7266,
			pcr_pid : 8191,
			video_pid : 8192,
			audio_pid : 8192,
			name : "STB Comag",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 69,
			ts_uid : 7,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 7296,
			tsid : 1111,
			onid : 1,
			lcn : 62,
			pmt_pid : 32,
			pcr_pid : 33,
			video_pid : 33,
			audio_pid : 3606,
			name : "TV TRWAM",
			video_codec : "MPEG-2",
			audio_codec : "MPEG",
			svctype : "tv",
			videotype : "sd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : false,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 70,
			ts_uid : 8,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 11100,
			tsid : 1011,
			onid : 1,
			lcn : 63,
			pmt_pid : 6000,
			pcr_pid : 6010,
			video_pid : 6010,
			audio_pid : 6020,
			name : "Das Erste HD",
			video_codec : "H.264",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "hd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 71,
			ts_uid : 8,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 11110,
			tsid : 1011,
			onid : 1,
			lcn : 64,
			pmt_pid : 6100,
			pcr_pid : 6110,
			video_pid : 6110,
			audio_pid : 6120,
			name : "ZDF HD",
			video_codec : "H.264",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "hd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}, {
			svc_uid : 72,
			ts_uid : 8,
			prv_uid : 0,
			ant_uid : 1,
			svcid : 11120,
			tsid : 1011,
			onid : 1,
			lcn : 65,
			pmt_pid : 6200,
			pcr_pid : 6210,
			video_pid : 6210,
			audio_pid : 6221,
			name : "arte HD",
			video_codec : "H.264",
			audio_codec : "MPEG",
			dolby_codec : "AC3",
			svctype : "tv",
			videotype : "hd",
			castype : "fta",
			optype : "none",
			delitype : "sat",
			sattype : "ASTRA_1",
			lcnflag : false,
			visiblesvcflag : true,
			dolbyflag : true,
			locked : false,
			stereo_config : "stereo"
		}]
	};
}