-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = licensegeneratechallenge

DRM_MODULE_CFLAGS =

SOURCES =                \
	 licensegeneratechallenge.c 
	
endif	
   
include $(DRM_SOURCE_PATH)/default.mak
