obj-y += xmgr_search_lcnupdate_ses.o
obj-y += xmgr_search_lcnupdate_action_ses.o
obj-y += xmgr_search_info_ses.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

