#
obj-y := tmbslTDA18275/
obj-y += drv_channel_tn18275.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18275/inc
#inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18275/tmbslTDA18275/inc
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/dp10048
