/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_pcie_ep_cfg_vpd.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 10/28/11 12:07a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Thu Oct 27 17:24:41 2011
 *                 MD5 Checksum         d0bb3b528cbe25f62f7a44e82cd25af7
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7425/rdb/b1/bchp_pcie_ep_cfg_vpd.h $
 * 
 * Hydra_Software_Devel/1   10/28/11 12:07a vanessah
 * SW7425-1620: add 7425 B0 rdb header file
 *
 ***************************************************************************/

#ifndef BCHP_PCIE_EP_CFG_VPD_H__
#define BCHP_PCIE_EP_CFG_VPD_H__

/***************************************************************************
 *PCIE_EP_CFG_VPD
 ***************************************************************************/
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP             0x00412050 /* vpd_cap */
#define BCHP_PCIE_EP_CFG_VPD_VPD_DATA            0x00412054 /* vpd_data */

/***************************************************************************
 *VPD_CAP - vpd_cap
 ***************************************************************************/
/* PCIE_EP_CFG_VPD :: VPD_CAP :: FLAG [31:31] */
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_FLAG_MASK                     0x80000000
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_FLAG_SHIFT                    31
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_FLAG_DEFAULT                  0

/* PCIE_EP_CFG_VPD :: VPD_CAP :: ADDRESS [30:18] */
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_ADDRESS_MASK                  0x7ffc0000
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_ADDRESS_SHIFT                 18
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_ADDRESS_DEFAULT               0

/* PCIE_EP_CFG_VPD :: VPD_CAP :: RESERVED0 [17:16] */
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_RESERVED0_MASK                0x00030000
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_RESERVED0_SHIFT               16

/* PCIE_EP_CFG_VPD :: VPD_CAP :: VPD_NEXT_CAP_PTR [15:08] */
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_VPD_NEXT_CAP_PTR_MASK         0x0000ff00
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_VPD_NEXT_CAP_PTR_SHIFT        8
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_VPD_NEXT_CAP_PTR_DEFAULT      88

/* PCIE_EP_CFG_VPD :: VPD_CAP :: VPD_CAP_ID [07:00] */
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_VPD_CAP_ID_MASK               0x000000ff
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_VPD_CAP_ID_SHIFT              0
#define BCHP_PCIE_EP_CFG_VPD_VPD_CAP_VPD_CAP_ID_DEFAULT            3

/***************************************************************************
 *VPD_DATA - vpd_data
 ***************************************************************************/
/* PCIE_EP_CFG_VPD :: VPD_DATA :: VPD_DATA [31:00] */
#define BCHP_PCIE_EP_CFG_VPD_VPD_DATA_VPD_DATA_MASK                0xffffffff
#define BCHP_PCIE_EP_CFG_VPD_VPD_DATA_VPD_DATA_SHIFT               0
#define BCHP_PCIE_EP_CFG_VPD_VPD_DATA_VPD_DATA_DEFAULT             0

#endif /* #ifndef BCHP_PCIE_EP_CFG_VPD_H__ */

/* End of File */
