/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_vbi_enc.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 10/28/11 1:25a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Thu Oct 27 17:31:28 2011
 *                 MD5 Checksum         d0bb3b528cbe25f62f7a44e82cd25af7
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7425/rdb/b1/bchp_vbi_enc.h $
 * 
 * Hydra_Software_Devel/1   10/28/11 1:25a vanessah
 * SW7425-1620: add 7425 B0 rdb header file
 *
 ***************************************************************************/

#ifndef BCHP_VBI_ENC_H__
#define BCHP_VBI_ENC_H__

/***************************************************************************
 *VBI_ENC - VBI_ENC  registers
 ***************************************************************************/
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL            0x00698000 /* Core select for VBI_0_CORE_0 */
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL            0x00698004 /* Core select for VBI_0_CORE_1 */
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL            0x00698008 /* Core select for VBI_0_CORE_2 */
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL            0x0069800c /* Core select for VBI_0_CORE_3 */
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL            0x00698010 /* Core select for VBI_0_CORE_4 */
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL            0x00698014 /* Core select for VBI_0_CORE_5 */
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL            0x00698018 /* Core select for VBI_0_CORE_6 */
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL            0x0069801c /* Core select for VBI_0_CORE_7 */
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL            0x00698020 /* Core select for VBI_1_CORE_0 */
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL            0x00698024 /* Core select for VBI_1_CORE_1 */
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL            0x00698028 /* Core select for VBI_1_CORE_2 */
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL            0x0069802c /* Core select for VBI_1_CORE_3 */
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL            0x00698030 /* Core select for VBI_1_CORE_4 */
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL            0x00698034 /* Core select for VBI_1_CORE_5 */
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL            0x00698038 /* Core select for VBI_1_CORE_6 */
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL            0x0069803c /* Core select for VBI_1_CORE_7 */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL      0x00698040 /* Core select for VBI_ANCIL_0_CORE_0 */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL      0x00698044 /* Core select for VBI_ANCIL_0_CORE_1 */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL      0x00698048 /* Core select for VBI_ANCIL_0_CORE_2 */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL      0x0069804c /* Core select for VBI_ANCIL_0_CORE_3 */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL      0x00698050 /* Core select for VBI_ANCIL_0_CORE_4 */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL      0x00698054 /* Core select for VBI_ANCIL_0_CORE_5 */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL      0x00698058 /* Core select for VBI_ANCIL_1_CORE_0 */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL      0x0069805c /* Core select for VBI_ANCIL_1_CORE_1 */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL      0x00698060 /* Core select for VBI_ANCIL_1_CORE_2 */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL      0x00698064 /* Core select for VBI_ANCIL_1_CORE_3 */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL      0x00698068 /* Core select for VBI_ANCIL_1_CORE_4 */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL      0x0069806c /* Core select for VBI_ANCIL_1_CORE_5 */
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL             0x00698070 /* for Interrupt control for VBI_0 */
#define BCHP_VBI_ENC_VBI_0_PEDESTAL              0x00698074 /* Pedestal Value Register  for VBI_0 */
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH          0x00698078 /* Video Encoder VBI_0  Pass through Control for Top Field */
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL             0x0069807c /* for Interrupt control for VBI_1 */
#define BCHP_VBI_ENC_VBI_1_PEDESTAL              0x00698080 /* Pedestal Value Register  for VBI_1 */
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH          0x00698084 /* Video Encoder VBI_1  Pass through Control for Top Field */
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL       0x00698088 /* for Interrupt control for VBI_ANCIL_0 */
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH    0x0069808c /* Video Encoder VBI_ANCIL_0  Pass through Control for Top Field */
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL       0x00698090 /* for Interrupt control for VBI_ANCIL_1 */
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH    0x00698094 /* Video Encoder VBI_ANCIL_1  Pass through Control for Top Field */

/***************************************************************************
 *VBI_0_CORE_0_SEL - Core select for VBI_0_CORE_0
 ***************************************************************************/
/* VBI_ENC :: VBI_0_CORE_0_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_0_CORE_0_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_0_CORE_0_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_0_CORE_1_SEL - Core select for VBI_0_CORE_1
 ***************************************************************************/
/* VBI_ENC :: VBI_0_CORE_1_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_0_CORE_1_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_0_CORE_1_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_0_CORE_2_SEL - Core select for VBI_0_CORE_2
 ***************************************************************************/
/* VBI_ENC :: VBI_0_CORE_2_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_0_CORE_2_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_0_CORE_2_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_0_CORE_3_SEL - Core select for VBI_0_CORE_3
 ***************************************************************************/
/* VBI_ENC :: VBI_0_CORE_3_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_0_CORE_3_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_0_CORE_3_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_0_CORE_4_SEL - Core select for VBI_0_CORE_4
 ***************************************************************************/
/* VBI_ENC :: VBI_0_CORE_4_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_0_CORE_4_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_0_CORE_4_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_0_CORE_5_SEL - Core select for VBI_0_CORE_5
 ***************************************************************************/
/* VBI_ENC :: VBI_0_CORE_5_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_0_CORE_5_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_0_CORE_5_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_0_CORE_6_SEL - Core select for VBI_0_CORE_6
 ***************************************************************************/
/* VBI_ENC :: VBI_0_CORE_6_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_0_CORE_6_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_0_CORE_6_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_0_CORE_7_SEL - Core select for VBI_0_CORE_7
 ***************************************************************************/
/* VBI_ENC :: VBI_0_CORE_7_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_0_CORE_7_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_0_CORE_7_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_1_CORE_0_SEL - Core select for VBI_1_CORE_0
 ***************************************************************************/
/* VBI_ENC :: VBI_1_CORE_0_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_1_CORE_0_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_1_CORE_0_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_1_CORE_1_SEL - Core select for VBI_1_CORE_1
 ***************************************************************************/
/* VBI_ENC :: VBI_1_CORE_1_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_1_CORE_1_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_1_CORE_1_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_1_CORE_2_SEL - Core select for VBI_1_CORE_2
 ***************************************************************************/
/* VBI_ENC :: VBI_1_CORE_2_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_1_CORE_2_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_1_CORE_2_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_1_CORE_3_SEL - Core select for VBI_1_CORE_3
 ***************************************************************************/
/* VBI_ENC :: VBI_1_CORE_3_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_1_CORE_3_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_1_CORE_3_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_1_CORE_4_SEL - Core select for VBI_1_CORE_4
 ***************************************************************************/
/* VBI_ENC :: VBI_1_CORE_4_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_1_CORE_4_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_1_CORE_4_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_1_CORE_5_SEL - Core select for VBI_1_CORE_5
 ***************************************************************************/
/* VBI_ENC :: VBI_1_CORE_5_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_1_CORE_5_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_1_CORE_5_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_1_CORE_6_SEL - Core select for VBI_1_CORE_6
 ***************************************************************************/
/* VBI_ENC :: VBI_1_CORE_6_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_1_CORE_6_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_1_CORE_6_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_1_CORE_7_SEL - Core select for VBI_1_CORE_7
 ***************************************************************************/
/* VBI_ENC :: VBI_1_CORE_7_SEL :: reserved0 [31:05] */
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_reserved0_MASK               0xffffffe0
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_reserved0_SHIFT              5

/* VBI_ENC :: VBI_1_CORE_7_SEL :: SEL [04:00] */
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_MASK                     0x0000001f
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_SHIFT                    0
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_DEFAULT                  16
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_CCE_0                    0
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_CCE_1                    1
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_WSE_0                    2
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_WSE_1                    3
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_CGMSAE_0                 4
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_CGMSAE_1                 5
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_TTE_0                    6
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_TTE_1                    7
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_GSE_0                    8
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_GSE_1                    9
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_AMOLE_0                  10
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_AMOLE_1                  11
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_PASSTHRU_0               12
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_PASSTHRU_1               13
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_COPY_PROTECT_0           14
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_COPY_PROTECT_1           15
#define BCHP_VBI_ENC_VBI_1_CORE_7_SEL_SEL_DISABLE                  16

/***************************************************************************
 *VBI_ANCIL_0_CORE_0_SEL - Core select for VBI_ANCIL_0_CORE_0
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_0_CORE_0_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_0_CORE_0_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_0_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_ANCIL_0_CORE_1_SEL - Core select for VBI_ANCIL_0_CORE_1
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_0_CORE_1_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_0_CORE_1_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_1_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_ANCIL_0_CORE_2_SEL - Core select for VBI_ANCIL_0_CORE_2
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_0_CORE_2_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_0_CORE_2_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_2_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_ANCIL_0_CORE_3_SEL - Core select for VBI_ANCIL_0_CORE_3
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_0_CORE_3_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_0_CORE_3_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_3_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_ANCIL_0_CORE_4_SEL - Core select for VBI_ANCIL_0_CORE_4
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_0_CORE_4_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_0_CORE_4_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_4_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_ANCIL_0_CORE_5_SEL - Core select for VBI_ANCIL_0_CORE_5
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_0_CORE_5_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_0_CORE_5_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_0_CORE_5_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_ANCIL_1_CORE_0_SEL - Core select for VBI_ANCIL_1_CORE_0
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_1_CORE_0_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_1_CORE_0_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_0_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_ANCIL_1_CORE_1_SEL - Core select for VBI_ANCIL_1_CORE_1
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_1_CORE_1_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_1_CORE_1_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_1_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_ANCIL_1_CORE_2_SEL - Core select for VBI_ANCIL_1_CORE_2
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_1_CORE_2_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_1_CORE_2_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_2_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_ANCIL_1_CORE_3_SEL - Core select for VBI_ANCIL_1_CORE_3
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_1_CORE_3_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_1_CORE_3_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_3_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_ANCIL_1_CORE_4_SEL - Core select for VBI_ANCIL_1_CORE_4
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_1_CORE_4_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_1_CORE_4_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_4_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_ANCIL_1_CORE_5_SEL - Core select for VBI_ANCIL_1_CORE_5
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_1_CORE_5_SEL :: reserved0 [31:04] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_reserved0_MASK         0xfffffff0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_reserved0_SHIFT        4

/* VBI_ENC :: VBI_ANCIL_1_CORE_5_SEL :: SEL [03:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_MASK               0x0000000f
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_SHIFT              0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_DEFAULT            12
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_CCE_ANCIL_0        0
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_CCE_ANCIL_1        1
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_WSE_ANCIL_0        2
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_WSE_ANCIL_1        3
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_TTE_ANCIL_0        4
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_TTE_ANCIL_1        5
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_GSE_ANCIL_0        6
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_GSE_ANCIL_1        7
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_AMOLE_ANCIL_0      8
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_AMOLE_ANCIL_1      9
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_PASSTHRU_ANCIL_0   10
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_PASSTHRU_ANCIL_1   11
#define BCHP_VBI_ENC_VBI_ANCIL_1_CORE_5_SEL_SEL_DISABLE            12

/***************************************************************************
 *VBI_0_INTR_CTRL - for Interrupt control for VBI_0
 ***************************************************************************/
/* VBI_ENC :: VBI_0_INTR_CTRL :: reserved_for_eco0 [31:28] */
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_reserved_for_eco0_MASK        0xf0000000
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_reserved_for_eco0_SHIFT       28
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_reserved_for_eco0_DEFAULT     0

/* VBI_ENC :: VBI_0_INTR_CTRL :: INTR1_LINE [27:16] */
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_INTR1_LINE_MASK               0x0fff0000
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_INTR1_LINE_SHIFT              16
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_INTR1_LINE_DEFAULT            0

/* VBI_ENC :: VBI_0_INTR_CTRL :: reserved_for_eco1 [15:12] */
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_reserved_for_eco1_MASK        0x0000f000
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_reserved_for_eco1_SHIFT       12
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_reserved_for_eco1_DEFAULT     0

/* VBI_ENC :: VBI_0_INTR_CTRL :: INTR0_LINE [11:00] */
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_INTR0_LINE_MASK               0x00000fff
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_INTR0_LINE_SHIFT              0
#define BCHP_VBI_ENC_VBI_0_INTR_CTRL_INTR0_LINE_DEFAULT            0

/***************************************************************************
 *VBI_0_PEDESTAL - Pedestal Value Register  for VBI_0
 ***************************************************************************/
/* VBI_ENC :: VBI_0_PEDESTAL :: reserved0 [31:08] */
#define BCHP_VBI_ENC_VBI_0_PEDESTAL_reserved0_MASK                 0xffffff00
#define BCHP_VBI_ENC_VBI_0_PEDESTAL_reserved0_SHIFT                8

/* VBI_ENC :: VBI_0_PEDESTAL :: VALUE [07:00] */
#define BCHP_VBI_ENC_VBI_0_PEDESTAL_VALUE_MASK                     0x000000ff
#define BCHP_VBI_ENC_VBI_0_PEDESTAL_VALUE_SHIFT                    0
#define BCHP_VBI_ENC_VBI_0_PEDESTAL_VALUE_DEFAULT                  0

/***************************************************************************
 *VBI_0_PASS_THROUGH - Video Encoder VBI_0  Pass through Control for Top Field
 ***************************************************************************/
/* VBI_ENC :: VBI_0_PASS_THROUGH :: reserved0 [31:31] */
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_reserved0_MASK             0x80000000
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_reserved0_SHIFT            31

/* VBI_ENC :: VBI_0_PASS_THROUGH :: FILTER_BYPASS [30:30] */
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_FILTER_BYPASS_MASK         0x40000000
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_FILTER_BYPASS_SHIFT        30
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_FILTER_BYPASS_DEFAULT      0

/* VBI_ENC :: VBI_0_PASS_THROUGH :: MULT [29:22] */
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_MULT_MASK                  0x3fc00000
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_MULT_SHIFT                 22
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_MULT_DEFAULT               255

/* VBI_ENC :: VBI_0_PASS_THROUGH :: LINE_START [21:11] */
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_LINE_START_MASK            0x003ff800
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_LINE_START_SHIFT           11
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_LINE_START_DEFAULT         20

/* VBI_ENC :: VBI_0_PASS_THROUGH :: COUNT [10:00] */
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_COUNT_MASK                 0x000007ff
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_COUNT_SHIFT                0
#define BCHP_VBI_ENC_VBI_0_PASS_THROUGH_COUNT_DEFAULT              0

/***************************************************************************
 *VBI_1_INTR_CTRL - for Interrupt control for VBI_1
 ***************************************************************************/
/* VBI_ENC :: VBI_1_INTR_CTRL :: reserved_for_eco0 [31:28] */
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_reserved_for_eco0_MASK        0xf0000000
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_reserved_for_eco0_SHIFT       28
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_reserved_for_eco0_DEFAULT     0

/* VBI_ENC :: VBI_1_INTR_CTRL :: INTR1_LINE [27:16] */
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_INTR1_LINE_MASK               0x0fff0000
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_INTR1_LINE_SHIFT              16
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_INTR1_LINE_DEFAULT            0

/* VBI_ENC :: VBI_1_INTR_CTRL :: reserved_for_eco1 [15:12] */
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_reserved_for_eco1_MASK        0x0000f000
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_reserved_for_eco1_SHIFT       12
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_reserved_for_eco1_DEFAULT     0

/* VBI_ENC :: VBI_1_INTR_CTRL :: INTR0_LINE [11:00] */
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_INTR0_LINE_MASK               0x00000fff
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_INTR0_LINE_SHIFT              0
#define BCHP_VBI_ENC_VBI_1_INTR_CTRL_INTR0_LINE_DEFAULT            0

/***************************************************************************
 *VBI_1_PEDESTAL - Pedestal Value Register  for VBI_1
 ***************************************************************************/
/* VBI_ENC :: VBI_1_PEDESTAL :: reserved0 [31:08] */
#define BCHP_VBI_ENC_VBI_1_PEDESTAL_reserved0_MASK                 0xffffff00
#define BCHP_VBI_ENC_VBI_1_PEDESTAL_reserved0_SHIFT                8

/* VBI_ENC :: VBI_1_PEDESTAL :: VALUE [07:00] */
#define BCHP_VBI_ENC_VBI_1_PEDESTAL_VALUE_MASK                     0x000000ff
#define BCHP_VBI_ENC_VBI_1_PEDESTAL_VALUE_SHIFT                    0
#define BCHP_VBI_ENC_VBI_1_PEDESTAL_VALUE_DEFAULT                  0

/***************************************************************************
 *VBI_1_PASS_THROUGH - Video Encoder VBI_1  Pass through Control for Top Field
 ***************************************************************************/
/* VBI_ENC :: VBI_1_PASS_THROUGH :: reserved0 [31:31] */
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_reserved0_MASK             0x80000000
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_reserved0_SHIFT            31

/* VBI_ENC :: VBI_1_PASS_THROUGH :: FILTER_BYPASS [30:30] */
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_FILTER_BYPASS_MASK         0x40000000
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_FILTER_BYPASS_SHIFT        30
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_FILTER_BYPASS_DEFAULT      0

/* VBI_ENC :: VBI_1_PASS_THROUGH :: MULT [29:22] */
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_MULT_MASK                  0x3fc00000
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_MULT_SHIFT                 22
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_MULT_DEFAULT               255

/* VBI_ENC :: VBI_1_PASS_THROUGH :: LINE_START [21:11] */
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_LINE_START_MASK            0x003ff800
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_LINE_START_SHIFT           11
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_LINE_START_DEFAULT         20

/* VBI_ENC :: VBI_1_PASS_THROUGH :: COUNT [10:00] */
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_COUNT_MASK                 0x000007ff
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_COUNT_SHIFT                0
#define BCHP_VBI_ENC_VBI_1_PASS_THROUGH_COUNT_DEFAULT              0

/***************************************************************************
 *VBI_ANCIL_0_INTR_CTRL - for Interrupt control for VBI_ANCIL_0
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_0_INTR_CTRL :: reserved_for_eco0 [31:28] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_reserved_for_eco0_MASK  0xf0000000
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_reserved_for_eco0_SHIFT 28
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_reserved_for_eco0_DEFAULT 0

/* VBI_ENC :: VBI_ANCIL_0_INTR_CTRL :: INTR1_LINE [27:16] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_INTR1_LINE_MASK         0x0fff0000
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_INTR1_LINE_SHIFT        16
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_INTR1_LINE_DEFAULT      0

/* VBI_ENC :: VBI_ANCIL_0_INTR_CTRL :: reserved_for_eco1 [15:12] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_reserved_for_eco1_MASK  0x0000f000
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_reserved_for_eco1_SHIFT 12
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_reserved_for_eco1_DEFAULT 0

/* VBI_ENC :: VBI_ANCIL_0_INTR_CTRL :: INTR0_LINE [11:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_INTR0_LINE_MASK         0x00000fff
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_INTR0_LINE_SHIFT        0
#define BCHP_VBI_ENC_VBI_ANCIL_0_INTR_CTRL_INTR0_LINE_DEFAULT      0

/***************************************************************************
 *VBI_ANCIL_0_PASS_THROUGH - Video Encoder VBI_ANCIL_0  Pass through Control for Top Field
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_0_PASS_THROUGH :: reserved0 [31:30] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH_reserved0_MASK       0xc0000000
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH_reserved0_SHIFT      30

/* VBI_ENC :: VBI_ANCIL_0_PASS_THROUGH :: MULT [29:22] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH_MULT_MASK            0x3fc00000
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH_MULT_SHIFT           22
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH_MULT_DEFAULT         255

/* VBI_ENC :: VBI_ANCIL_0_PASS_THROUGH :: LINE_START [21:11] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH_LINE_START_MASK      0x003ff800
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH_LINE_START_SHIFT     11
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH_LINE_START_DEFAULT   20

/* VBI_ENC :: VBI_ANCIL_0_PASS_THROUGH :: COUNT [10:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH_COUNT_MASK           0x000007ff
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH_COUNT_SHIFT          0
#define BCHP_VBI_ENC_VBI_ANCIL_0_PASS_THROUGH_COUNT_DEFAULT        0

/***************************************************************************
 *VBI_ANCIL_1_INTR_CTRL - for Interrupt control for VBI_ANCIL_1
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_1_INTR_CTRL :: reserved_for_eco0 [31:28] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_reserved_for_eco0_MASK  0xf0000000
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_reserved_for_eco0_SHIFT 28
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_reserved_for_eco0_DEFAULT 0

/* VBI_ENC :: VBI_ANCIL_1_INTR_CTRL :: INTR1_LINE [27:16] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_INTR1_LINE_MASK         0x0fff0000
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_INTR1_LINE_SHIFT        16
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_INTR1_LINE_DEFAULT      0

/* VBI_ENC :: VBI_ANCIL_1_INTR_CTRL :: reserved_for_eco1 [15:12] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_reserved_for_eco1_MASK  0x0000f000
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_reserved_for_eco1_SHIFT 12
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_reserved_for_eco1_DEFAULT 0

/* VBI_ENC :: VBI_ANCIL_1_INTR_CTRL :: INTR0_LINE [11:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_INTR0_LINE_MASK         0x00000fff
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_INTR0_LINE_SHIFT        0
#define BCHP_VBI_ENC_VBI_ANCIL_1_INTR_CTRL_INTR0_LINE_DEFAULT      0

/***************************************************************************
 *VBI_ANCIL_1_PASS_THROUGH - Video Encoder VBI_ANCIL_1  Pass through Control for Top Field
 ***************************************************************************/
/* VBI_ENC :: VBI_ANCIL_1_PASS_THROUGH :: reserved0 [31:30] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH_reserved0_MASK       0xc0000000
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH_reserved0_SHIFT      30

/* VBI_ENC :: VBI_ANCIL_1_PASS_THROUGH :: MULT [29:22] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH_MULT_MASK            0x3fc00000
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH_MULT_SHIFT           22
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH_MULT_DEFAULT         255

/* VBI_ENC :: VBI_ANCIL_1_PASS_THROUGH :: LINE_START [21:11] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH_LINE_START_MASK      0x003ff800
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH_LINE_START_SHIFT     11
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH_LINE_START_DEFAULT   20

/* VBI_ENC :: VBI_ANCIL_1_PASS_THROUGH :: COUNT [10:00] */
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH_COUNT_MASK           0x000007ff
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH_COUNT_SHIFT          0
#define BCHP_VBI_ENC_VBI_ANCIL_1_PASS_THROUGH_COUNT_DEFAULT        0

#endif /* #ifndef BCHP_VBI_ENC_H__ */

/* End of File */
