obj-y += svc_swup.o
obj-y += svc_swup_install.o
obj-y += svc_swup_ip.o
obj-y += svc_swup_ip_download.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw
# Additional include path

