obj-y += xmgr_satrecord_action_base.o
obj-y += xmgr_satrecord_detect_base.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr

# Additional include path
ccflags-y += -I$(OCTO_TVMANAGER_PLUGIN_DIR)/xmgr/satrecord/local_include
