obj-y 							+= base/
obj-$(CONFIG_OP_MIDDLE_EAST)	+= mesat/
obj-$(CONFIG_OP_SES)				+= ses/
obj-$(CONFIG_OP_UK_DTT)			+= ukdtt/
obj-$(CONFIG_OP_ZIGGO)			+= ziggo/
obj-$(CONFIG_OP_ERTELECOM)		+= ertelecom/
obj-y += pmgr_action.o
obj-y += xmgr_action.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas


