obj-$(CONFIG_PROD_ICORDPRO)		+= xmgr_tplist_icordpro.o
obj-$(CONFIG_PROD_HMS1000S)		+= xmgr_tplist_hms1000s.o
obj-$(CONFIG_PROD_HMSLITE)		+= xmgr_tplist_hms1000s.o
obj-$(CONFIG_PROD_FVP4000T)		+= xmgr_tplist_fvp4000t.o
obj-$(CONFIG_OP_TELENOR)		+= xmgr_tplist_telenor.o
obj-$(CONFIG_OP_TDC)			+= xmgr_tplist_tdc.o
obj-$(CONFIG_PROD_HA7100S) 		+= xmgr_tplist_ha7100s.o
obj-$(CONFIG_PROD_M1) 		+= xmgr_tplist_m1.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

