obj-y += base/
obj-$(CONFIG_OP_MIDDLE_EAST)	+= mesat/
obj-$(CONFIG_OP_SES)	+= ses/

obj-y += pmgr_coldboot.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

