ifeq ($(CONFIG_MW_CAS_VIACCESS), y)
obj-y += va_main.o
obj-y += va_crypt.o
obj-y += va_ctrl.o
obj-y += va_sc.o
obj-y += va_stdby.o
obj-y += va_xnvm.o
else
obj-y += main.o
endif
# Additional include path