#!/bin/sh

case "$1" in
    start)
		# Create core dump with executable name and process id
		# Ref.: http://www.linuxhowtos.org/Tips%20and%20Tricks/coredump.htm
		echo "core.%e.%p" > /proc/sys/kernel/core_pattern
		# Remove previouse core dump and log files
		rm -f /core* /*.comm /rpclog.* /*.dump
		rm -f /home/core*  /home/*.comm /home/rpclog.* /home/*.dump
		rm -f /home/sechdlr/root/core*  /home/sechdlr/root/*.comm /home/sechdlr/root/rpclog.* /home/sechdlr/root/*.dump
		rm -f /home/settop/root/core*  /home/settop/root/*.comm /home/settop/root/rpclog.* /home/settop/root/*.dump
		rm -f /home/imma/root/core*  /home/imma/root/*.comm /home/imma/root/rpclog.* /home/imma/root/*.dump
		rm -f /home/homma/root/core*  /home/homma/root/*.comm /home/homma/root/rpclog.* /home/homma/root/*.dump
		rm -f /home/corsair/root/core*  /home/corsair/root/*.comm /home/corsair/root/rpclog.* /home/corsair/root/*.dump

		# Enable core dump
		ulimit -c unlimited
		export UVA_DRM_LIB_DIR="/usr/browser/drm/"
		# Run PCD
		exec /home/dfbmaster &
		exec /home/sechdlr/root/home/hamalauncher &
		exec /home/settop/root/home/hamalauncher &
		exec /home/imma/root/home/hamalauncher &
		exec /home/homma/root/home/hamalauncher &
		exec /home/corsair/root/home/hamalauncher &
		exec /home/hama &
		;;
    stop)
		if [ "$VERBOSE" != no ]; then
			log_begin_msg "Stopping Application processes"
		fi
		killall obama
		killall corsair
		;;
    *)
		if [ "$VERBOSE" != no ]; then
			log_success_msg "Usage: /etc/init.d/S90settop {start|stop}"
		fi
		exit 1
		;;
esac

