obj-y += pal_sef.o
obj-y += pal_sef_thread.o

# Basic include path
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.pal
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/include
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/pal/include
ccflags-y += -I$(APPLTOP_SRC_DIR)/irldvt/utils/include
# Additional include path

