obj-y							+= base/
obj-$(CONFIG_OP_ZIGGO)			+= ziggo/
obj-$(CONFIG_OP_MIDDLE_EAST)	+= mesat/

obj-y		+= xmgr_pg.o
obj-y		+= pmgr_pg.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule

# Additional include path

