obj-y += mgr_media_core_util.o
obj-$(CONFIG_MW_MM_PVR) += mgr_media_video_thumbnail.o
obj-y += mgr_mplayer.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr

# Additional include path
ccflags-y += -I$(OCTO_TVMANAGER_DIR)/include_plugin

