obj-y += xmgr_cas_na_ppv_mediaset_banner.o
obj-y += xmgr_cas_na_ppv_pangea_banner.o
obj-y += xmgr_cas_na_ppv_mediaset_popup.o
obj-y += xmgr_cas_na_ppv_pangea_popup.o
obj-y += xmgr_cas_na_ppv_mediaset_carderror.o
obj-y += xmgr_cas_na_ppv_pangea_carderror.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
ccflags-y += -I$(OCTO_DIR)/oapi/server/include

# Sub-CAS include path
