#!/bin/sh

# execute the default stbhotplug script
/sbin/stbhotplug $@

# input hotplug
if [ "$1" = "input" ] && [ "$ACTION" = "add" -o "$ACTION" = "remove" ]; then
	if [ -f /usr/etc/hotplug.d/dfb_input_hotplug ]; then
		exec /usr/etc/hotplug.d/dfb_input_hotplug
	fi
fi

exit 0
