obj-y += otl_conv_common.o
obj-y += otl_conv_service.o
obj-$(CONFIG_MW_MM_PVR) += otl_conv_recording.o
obj-y += otl_conv_operator.o
obj-y += int_otl_conv.o

###################################
# OCTO flags & include dirs
###################################

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mgr
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.mw
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.pal
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.dlna

# Additional include path
