
obj-$(CONFIG_SUPPORT_UMMA_SAMBA_SERVER) += umma_smbs.o

# Additional include path
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/smbs/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fm/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fs
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fs/pal/include
