############################################################
#	  (c)2012 Broadcom Corporation
#
#  This program is the proprietary software of Broadcom Corporation and/or its licensors,
#  and may only be used, duplicated, modified or distributed pursuant to the terms and
#  conditions of a separate, written license agreement executed between you and Broadcom
#  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
#  no license (express or implied), right to use, or waiver of any kind with respect to the
#  Software, and Broadcom expressly reserves all rights in and to the Software and all
#  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
#  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
#  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
#
#  Except as expressly set forth in the Authorized License,
#
#  1.	  This program, including its structure, sequence and organization, constitutes the valuable trade
#  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
#  and to use this information only in connection with your use of Broadcom integrated circuit products.
#
#  2.	  TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
#  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
#  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
#  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
#  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
#  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
#  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
#  USE OR PERFORMANCE OF THE SOFTWARE.
#
#  3.	  TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
#  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
#  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
#  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
#  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
#  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
#  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
#  ANY LIMITED REMEDY.
#
# $brcm_Workfile: Makefile $
# $brcm_Revision: 2 $
# $brcm_Date: 9/6/12 5:22p $
#
# Module Description:
#
# Revision History:
#
# $brcm_Log: /BSEAV/lib/mpeg2_ts_parse/test/Makefile $
# 
# 2   9/6/12 5:22p erickson
# SW7435-349: add standard header
# 
############################################################
include ../../../api/build/tools.mak
BSEAV = $(shell cd ../../.. && ${PWD})
include $(BSEAV)/lib/bwin/build/system.mak
CFLAGS += $(SYSTEM_FLAGS)
include $(BSEAV)/lib/bwin/build/magnumbase.mak
CFLAGS += $(MAGNUM_INCLUDE) $(MAGNUM_GENERIC_CHIP_DEFINES)

APP=ts_parse

SRCS = main.c \
	../psip.c \
	../psip_common.c \
	../psip_dccsct.c \
	../psip_dcct.c \
	../psip_decode_tree_01.c \
	../psip_decode_tree_02.c \
	../psip_descriptor.c \
	../psip_eit.c \
	../psip_ett.c \
	../psip_mgt.c \
	../psip_mss.c \
	../psip_rrt.c \
	../psip_stt.c \
	../psip_vct.c \
	../ts_ca.c \
	../ts_packet.c \
	../ts_pat.c \
	../ts_pmt.c \
	../ts_priv.c \
	../ts_psi.c

OBJS = $(subst .c,.o,$(SRCS))

CFLAGS += -I.. -I.

$(APP): $(OBJS)
	$(CC) -o $@ $^ $(LFLAGS)

clean:
	$(RM) $(APP) $(OBJS)
