obj-$(CONFIG_MW_CAS_NAGRA_OP_MEDIASET) += na_mgr_ppv_mset.o
obj-$(CONFIG_MW_CAS_NAGRA_OP_SPAIN) += na_mgr_ppv_tdt.o
obj-$(CONFIG_MW_CAS_NAGRA_OP_RCS) += na_mgr_ppv_rcs.o

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas


# Additional include path

