-include ./dirs

ifeq ($(DIRS),)
TARGET = meteringreal

SOURCES =                \
	drmmeterapi.c drmmetercertstore.c drmmeterimp.c drmmeterimpv1.c meteringutilreal.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
