obj-y += cx_nvram.o
obj-y += cx_sc.o
obj-y += cx_dscr.o
obj-y += cx_dmx.o
obj-y += cx_ui.o


# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

