# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =      \
    lib        \
    libnorand  \

include $(PLAYREADY_DIR)/GNUmakefile.common

