obj-y += iruc_mgr.o
obj-y += iruc_drv.o
obj-y += iruc_ctrl.o
obj-y += iruc_os_stdlib.o

obj-y += iruc_spi_stream.o
obj-y += iruc_spi_os.o
obj-y += iruc_spi_ps.o
obj-y += iruc_spi_device.o
obj-y += iruc_spi_timer.o
obj-y += iruc_spi_sc.o
obj-y += UniversalClient_SPI.o

# for test of Irdeto Cloaked CA Agent VM Validator
obj-$(CONFIG_MW_CAS_IRDETO_UCAS_VM_VAILDATOR) += uc_stub/

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

