-include ./dirs

ifeq ($(DIRS),)
TARGET = devicestorestub

SOURCES =                \
	devicestoreutilstub.c drmdevicestorestub.c drmdevstorestub.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
