obj-y += vmx_vr_bc_ecm.o
obj-y += vmx_vr_bc_emm.o
obj-y += vmx_vr_bc_psi_mgr.o

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
