-include ./dirs

ifeq ($(DIRS),)
#TARGET = drmcerts
TARGETEXE = generatecompanycertrequest

DRM_MODULE_CFLAGS =

SOURCES =                \
	generatecompanycertrequest.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
