#############################################################################
#
#       Copyright (c) 2005-2011, Broadcom Corporation.
#       All rights reserved.
#       Confidential Property of Broadcom Corporation.
#
#  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
#  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
#  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
#
# $brcm_Workfile: Makefile $
# $brcm_Revision: Hydra_Software_Devel/10 $
# $brcm_Date: 10/25/11 3:39p $
#
# File Description:
#
# Revision History:
#
# $brcm_Log: /rockford/applications/mux_static_test/Makefile $
# 
# Hydra_Software_Devel/10   10/25/11 3:39p nilesh
# SW7425-1236: Merge to mainline
# 
# Hydra_Software_Devel/SW7425-1580/1   10/25/11 3:20p nilesh
# SW7425-1236: Update mux static test to compile/run
# 
# Hydra_Software_Devel/9   6/28/11 10:06a delkert
# SW7425-341: Use muxlib common code for storage I/O
#
# Hydra_Software_Devel/8   5/27/11 10:19a delkert
# SW7425-446: Fix so MP4 mux static test builds (muxlib includes moved)
#
# Hydra_Software_Devel/7   5/2/11 1:38p delkert
# SW7425-327: Fix mux static test so it builds with new inc files. Fix
# logic on KEEP_TEMP_FILES.
#
# Hydra_Software_Devel/6   4/4/11 6:35p delkert
# SW7425-73: Replace transport_stub.c in APP_SOURCES (accidentally
# omitted by merge)
#
# Hydra_Software_Devel/5   4/4/11 6:21p delkert
# SW7425-73: Merge mp4_mux_devel to mainline
#
# Hydra_Software_Devel/mp4_mux_devel/1   4/4/11 6:15p delkert
# SW7425-73: Added option for building MP4 version of mux_static_test
#
# Hydra_Software_Devel/4   11/11/10 3:37p nilesh
# SW7425-38: Update to use actual XPT PI
#
# Hydra_Software_Devel/3   9/28/10 4:54p nilesh
# SW7425-38: Added audio encoder and transport stubs
#
# Hydra_Software_Devel/2   9/24/10 12:00p nilesh
# SW7425-38: Added video encoder stub interface
#
# Hydra_Software_Devel/1   9/21/10 5:36p nilesh
# SW7425-38: Initial mux_static_test implementation (Create/Destroy)
#
#############################################################################

# Requires the use of the 'plat' script which defines the following:
#   PLATFORM (97038, 97398, ...)
#   BCHP_VER (B0, B1, C0, ...)
#   BCHP_7411_VER (C0, D0, ...) plus versions for other secondary chipsets
#   DEBUG
#   LINUX
#   ARCH
#   TOOLCHAIN

# Target O/S (can be one of the following: linuxuser vxworks)
ifeq ($(SYSTEM),vxworks)
    TARGET_OS = vxworks
else
ifeq ($(SYSTEM), linuxemu)
    TARGET_OS = linuxemu
else
    TARGET_OS = linuxuser
endif
endif

# Directories relative to location of makefile
MAGNUM_DIR = ../../../magnum
ROCKFORD_DIR = ../../../rockford
FRAMEWORK_DIR = $(ROCKFORD_DIR)/appframework

# Name of application
ifeq ($(SYSTEM),vxworks)
APP = mux_static_test.out
else
APP = mux_static_test
endif

# Application object file list, include path, C flags, and link
# flags
APP_SOURCES= \
	./video_encoder_stub.c \
	./audio_encoder_stub.c

ifeq ($(MP4), y)
APP_SOURCES +=	./mux_static_test_mp4.c
else
APP_SOURCES +=	./mux_static_test.c \
	            ./transport_stub.c
endif

# Initial application settings
APP_INCLUDES =
APP_CFLAGS   =
APP_LDFLAGS  =

# Must define ENDIAN to be either big or little
ENDIAN = little

# Want to see details (y/n)?
VERBOSE = n

# Debug (y/n)?
DEBUG ?= y
ifeq ($(DEBUG),y)
APP_CFLAGS += -DBDBG_DEBUG_BUILD
endif

ifeq ($(TARGET_OS),vxworks)
CFLAGS += -DVXWORKS
else
CFLAGS += -DLINUX
	ifeq ($(TARGET_OS),linuxclient)
	CFLAGS += -DIKOS_EMULATION
	endif
endif

# Include object file list, include path, and C flags for common utilities and base modules
# (sets MAGNUM_SOURCES, MAGNUM_INCLUDES, MAGNUM_CFLAGS, and MAGNUM_MODULE_DIR)
include $(FRAMEWORK_DIR)/build/magnum.inc

# NOTE: This *could* include muxlib.inc to include all this, but as of now it has unresolved
#       dependencies that break the build. For now it includes just the files required.

# Include object file list, include path, and C flags for other magnum modules required
# by this application (adds to MAGNUM_SOURCES, MAGNUM_INCLUDES, and MAGNUM_CFLAGS).
# Here is where you also define module specific makefile defines
BVDC_MACROVISION ?= y
ifeq ($(MP4), y)
include $(MAGNUM_DIR)/syslib/muxlib/bmuxlib_file_mp4.inc
include $(MAGNUM_DIR)/syslib/muxlib/bmuxlib_common.inc
else
include $(MAGNUM_DIR)/syslib/muxlib/bmuxlib_stream_ts.inc
include $(MAGNUM_DIR)/syslib/muxlib/bmuxlib_common.inc
include $(MAGNUM_DIR)/portinginterface/xpt/bxpt.inc
endif

# At this point, user can add additional files, include paths, and C flags to
# MAGNUM_SOURCES, MAGNUM_INCLUDES, and MAGNUM_CFLAGS (optional).

# Include other common modules (adds to COMMON_SOURCES, COMMON_INCLUDES, and
# COMMON_CFLAGS)
ifeq ($(MP4), y)
COMMON_SOURCES += $(ROCKFORD_DIR)/unittests/syslib/muxlib/muxer_file.c
COMMON_INCLUDES += $(ROCKFORD_DIR)/unittests/syslib/muxlib
endif

# Specifies how magnum files and application files are built.
include $(FRAMEWORK_DIR)/build/$(TARGET_OS)/build.inc

# End of file
