obj-y += db/
obj-y += filemgr/
obj-y += media/
obj-y += meta/
obj-y += system/
obj-y += network/
obj-$(CONFIG_MW_CAS) += cas/
obj-$(CONFIG_MW_MM_DLNA) += dlna/

obj-y += nx_port.o

# Basic include path
ccflags-y += -I$(NATIVEAPP_TOP_DIR)/include
ccflags-y += -I$(NATIVEAPP_PORT_INCLUDE_DIR)/include

# Additional include path
