#
obj-y :=

ifeq ($(CONFIG_RC_H101),y)
obj-y += RC-H101.o
endif

ifeq ($(CONFIG_R_J03),y)
obj-y += R-J03.o
endif

ifeq ($(CONFIG_RM_E06),y)
obj-y += RM-E06.o
endif

ifeq ($(CONFIG_RM_F01),y)
obj-y += RM-F01.o
endif

ifeq ($(CONFIG_RM_F02),y)
obj-y += RM-F02.o
endif

ifeq ($(CONFIG_RM_F04),y)
obj-y += RM-F04.o
endif

ifeq ($(CONFIG_RM_L01U),y)
obj-y += RM-L01U.o
endif

ifeq ($(CONFIG_RM_G01),y)
obj-y += RM-G01.o
endif

ifeq ($(CONFIG_RM_G02),y)
obj-y += RM-G02.o
endif

ifeq ($(CONFIG_RM_G07),y)
obj-y += RM-G07.o
endif

ifeq ($(CONFIG_RM_G08),y)
obj-y += RM-G08.o
endif

ifeq ($(CONFIG_RM_H04S),y)
obj-y += RM-H04S.o
endif

ifeq ($(CONFIG_RM_H05S),y)
obj-y += RM-H05S.o
endif

ifeq ($(CONFIG_RM_I02S),y)
obj-y += RM-I02S.o
endif

ifeq ($(CONFIG_RM_H04S_E08),y)
obj-y += RM-H04S_E08.o
endif

ifeq ($(CONFIG_URC_39741RJ2_001),y)
obj-y += URC-39741RJ2-001.o
endif

ifeq ($(CONFIG_URC_178200),y)
obj-y += URC-178200.o
endif

ifeq ($(CONFIG_RC_05),y)
obj-y += RC-05.o
endif

ifeq ($(CONFIG_XMP_01),y)
obj-y += XMP-01.o
endif

ifeq ($(CONFIG_R_C01),y)
obj-y += R-C01.o
endif

ifeq ($(CONFIG_RM_M02),y)
obj-y += RM-M02.o
endif

ifeq ($(CONFIG_RM_M03),y)
obj-y += RM-M03.o
endif

ifeq ($(CONFIG_RM_M04),y)
obj-y += RM-M04.o
endif

ifeq ($(CONFIG_RM_M08),y)
obj-y += RM-M08.o
endif

ifeq ($(CONFIG_RM_H09U),y)
obj-y += RM-H09U.o
endif

ifeq ($(CONFIG_RUWIDO_R97),y)
obj-y += RUWIDO_R97.o
endif

ifeq ($(CONFIG_R_843),y)
obj-y += R-843.o
endif

ifeq ($(CONFIG_R_849),y)
obj-y += R-849.o
endif

ifeq ($(CONFIG_R_861),y)
obj-y += R-861.o
endif

ifeq ($(CONFIG_NOVA_CE),y)
obj-y += NOVA-CE.o
endif

ifeq ($(CONFIG_RM_N01),y)
obj-y += RM-N01.o
endif

ifeq ($(CONFIG_RM_M14),y)
obj-y += RM-M14.o
endif

