obj-$(CONFIG_MW_CI) += ci/
obj-$(CONFIG_MW_CAS_NAGRA) += nagra/
obj-$(CONFIG_MW_CAS_IRDETO_UCAS) += uc/
obj-$(CONFIG_MW_CAS_IRDETO_SCELL) += irdeto/	
obj-$(CONFIG_MW_CAS_IRDETO_LOADER_V5) += uc/ir_ldv5/

obj-$(CONFIG_MW_CAS_IRDETO_LOADER_DVT_V5) += irdeto/ld_v5/
obj-$(CONFIG_MW_CAS_IRDETO_LOADER_DVT_V5) += irdeto/ldvt_app_v5/


obj-$(CONFIG_MW_CAS_CONAX) += conax/
obj-$(CONFIG_MW_CAS_VIACCESS) += viaccess/
obj-$(CONFIG_MW_CAS_SATSA) += satsa/
obj-$(CONFIG_MW_CAS_VERIMATRIX) += verimatrix/

obj-y += scenario/
obj-y += init/

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
