obj-y += xmgr_live_base.o
obj-y += xmgr_live_view_base.o
obj-y += xmgr_live_lock_base.o
obj-y += xmgr_live_comp_base.o
obj-y += xmgr_live_zap_base.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas.mgr


