#ifndef __DI_ERR_H__
#define __DI_ERR_H__

typedef enum DI_ERR_CODE
{
	DI_ERR_OK= 0,
	DI_ERR_ERROR,
	DI_ERR_INVALID_PARAM,
	DI_ERR_NO_RESOURCE,
	DI_ERR_NO_ALLOC,
	DI_ERR_NOT_SUPPORTED,
	DI_ERR_INIT,
	DI_ERR_SEND,
	DI_ERR_RECV,
	DI_ERR_TIMEOUT,
	DI_ERR_CRC,
	DI_ERR_NO_PARTITIONS,
	DI_ERR_MAX
}DI_ERR_CODE;

#endif /* __DI_ERR_H__ */
