# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

TARGETS =    \
    general  \
    builder  \

include $(PLAYREADY_DIR)/GNUmakefile.common

