#
obj-y := drv_channel_dp10048.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18273

ifneq ($(CONFIG_PLATFORM_TN18275),)
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/tn18275
endif
