obj-$(CONFIG_APUI_SET_RECORDING_UI_DISPLAY) += nx_prism_recordings.o
obj-$(CONFIG_APUI_SET_RECORDING_UI_DISPLAY) += nx_prism_recordings_extension.o

# Additional include path
ccflags-y += -I../../../../../../../make/include

