obj-y += asn1decode.o
obj-y += der_decode.o
obj-y += asn1tag.o
obj-y += output.o
obj-y += utils.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path

