obj-y += util_task.o
obj-y += linkedlist.o
obj-y += treeutil.o
#obj-y += timeconv.o
obj-y += memchain.o
obj-y += get_enum_str.o
#obj-y += utils.o

ccflags-y += -I$(OCTO_MAIN_INCLUDE_DIR)
ccflags-y += -I$(OCTO_UTILS_DIR)/utils/include

