# @@@+++@@@@******************************************************************
# **
# ** Microsoft (r) PlayReady (r)
# ** Copyright (c) Microsoft Corporation. All rights reserved.
# **
# @@@+++@@@@******************************************************************

SRC_DIR = ..

PLAYREADY_TEST=1

include $(PLAYREADY_DIR)/PK_GNUmakefile.common

