#include "nexus_platform.h"
/*#include "nexus_gpio_module.h"*/
#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"

const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
	/*GPIO*/
/*/////////////   0 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 000 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 001 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 002 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 003 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 004 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 005 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 006 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 007 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 008 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */  /* GPIO 009 */
/*//////////////  10 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */ 
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 018 EBI_#CS0 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 019 */
/*//////////////  20 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 023 SDS0_DSEC_TXOUT,22K_TONE */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 024 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 025 EBI_DATA0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 026 EBI_DATA1*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 027 EBI_DATA2*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 028 EBI_DATA3*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 029 EBI_DATA4*/
/*//////////////  30 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 030 EBI_DATA5*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 031 EBI_DATA6*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 032 EBI_DATA7 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*//////////////  40 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 040 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 041 EBI_RD# */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 042 EBI_WE0#*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 043 EBI_DS# */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 044 EBI_TS# */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 045 NAND_RDY_#BSY*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 047 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 048 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 049 */
/*//////////////  50 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 050 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 051 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 055 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*//////////////  60 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 060 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*//////////////  70 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 070 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 074 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 075 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// GPIO 076 SW_#RSTREQ */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 077 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// GPIO 078 AUD_#MUTE */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 079 SC0_VCC */
/*//////////////  80 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 080 SC0_CLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 081 SC0_RST */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 082 SC0_IO */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 083 SC0_PRES */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 084 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 085 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// GPIO 086 SC0_VCC_SEL*/
	HUMAX_GPIO_FUNCTION_ALT2,	/*// GPIO 087 STRAP_UART_TX0 */
	HUMAX_GPIO_FUNCTION_ALT2,	/*// GPIO 088 UART_RX0 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 089 strap_UART_TX1 */
/*//////////////  90 //////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 090 UART_RX1*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 092 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 093 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 094 */
	/****** GPIO 95**** */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 096 OFDM_CLK */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 097 OFDM_DATA*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 098 OFDM_SYNC*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 099 OFDM_VAL */
/*////////////// 100 ///////////// /*/
	HUMAX_GPIO_FUNCTION_ALT2,	/*// GPIO 100 OFDM_ERR*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 101 USB0_PWRON1 (& strap)*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 102 strap_USB0_PWRON2    */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 103 USB0_PWRFLT1         */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 104 */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// GPIO 105 strap_ENET_ACTIVITY*/
	/****** GPIO 106*** */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  GPIO 107 CH_UP */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  GPIO 108 CH_DN */
	HUMAX_GPIO_FUNCTION_GPIO,	/*//  GPIO 109 VOL_UP */
/*////////////// 110 //////////////*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*// GPIO 110 VOL_DN */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 115 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
/*////////////// 120 //////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 120 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// GPIO 124 */

/*SGPIOs*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// SGPIO 00 BSC_M0_SCL */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// SGPIO 01 BSC_M0_SDA */
	HUMAX_GPIO_FUNCTION_ALT1,	/*// SGPIO 02 BSC_M1_SCL*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// SGPIO 03 BSC_M1_SDA*/

/*AON_GPIOs*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*// AON_GPIO 00 STRAP_AON_GPIO_00(AUD_SPDIF)*/
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 01 STRAP_AON_GPIO_01 */
	/****** AON_GPIO 02**** */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 03 PWR KEY */
	HUMAX_GPIO_FUNCTION_ALT4,	/*// AON_GPIO 04 LNBP_IRQ# */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 05 LED_POWER */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// AON_GPIO  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 07 LED_MESSAGE */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 08 LED_STBY */ 
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 10 strap_AON_GPIO_10 */
	HUMAX_GPIO_FUNCTION_GPIO,	/*// AON_GPIO 11 strap_AON_GPIO_11 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// AON_GPIO 13 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// AON_GPIO 14 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// AON_GPIO 15 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// AON_GPIO 16 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// AON_GPIO 17 */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*//  */
	HUMAX_GPIO_FUNCTION_NCTP,	/*// AON_GPIO 20 EEPROM_WP*/

/*AON_SGPIOs*/
	HUMAX_GPIO_FUNCTION_ALT1,	/*//  */ /* AON_SGPIO 00 BSC_M3_SCL */
	HUMAX_GPIO_FUNCTION_ALT1	/*//  */ /* AON_SGPIO 01 BSC_M3_SDA */
};

HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
	/*GPIO*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_00_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_01_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_02_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_03_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_04_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_05_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_06_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_06_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_07_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_07_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_08_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_08_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_09_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_09_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_10_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_10_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_11_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_11_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_12_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_12_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_13_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_13_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_14_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_14_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_15_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_15_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_16_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_16_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_17_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_17_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_18_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_18_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_19_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_19_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_20_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_20_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_21_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_21_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_22_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_22_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_23_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_23_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_24_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_24_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_25_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_25_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_26_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_26_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_27_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_27_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_28_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_28_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_29_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_29_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_30_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_30_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_31_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_31_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_32_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_32_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_33_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_33_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_34_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_34_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_35_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_35_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_36_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_36_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_37_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_37_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_38_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_38_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_39_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_39_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_40_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_40_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_41_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_41_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_42_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_42_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_43_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_43_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_44_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_44_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_45_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_45_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_46_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_46_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_47_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_47_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_48_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_48_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_49_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_49_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_50_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_50_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_51_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_51_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_52_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_52_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_53_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_53_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_54_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_54_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_55_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_55_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_56_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_56_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_57_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_57_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_58_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_58_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_59_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_59_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_60_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_60_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_61_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_61_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_62_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_62_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_63_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_63_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_64_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_64_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_65_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_65_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_66_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_66_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_67_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_67_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_68_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_68_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_69_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_69_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_70_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_70_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_72_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_72_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_73_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_73_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_74_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_74_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_75_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_75_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_76_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_76_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_77_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_77_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_78_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_78_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_79_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_79_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_80_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_80_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_81_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_81_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_82_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_82_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_83_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_83_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_84_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_84_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_85_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_85_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_86_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_86_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_87_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_87_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_88_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_88_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_89_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_89_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_90_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_90_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_91_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_91_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_92_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_92_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_93_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_93_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_94_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_94_SHIFT},
	/*{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, 0, 0},*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_96_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_96_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_97_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_97_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_98_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_98_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_99_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_99_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_100_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_100_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_101_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_101_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_102_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_102_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_103_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_103_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_104_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_104_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_105_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_105_SHIFT},
	/*{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, 0, 0},*/
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_107_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_107_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_108_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_108_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_109_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_109_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_110_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_110_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_111_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_111_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_112_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_112_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_113_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_113_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_114_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_114_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_115_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_115_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_116_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_116_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_117_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_117_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_118_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_118_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_119_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_119_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_120_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_120_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_121_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_121_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_122_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_122_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_123_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_123_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_124_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_124_SHIFT},

	 /*SGPIO*/
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_01_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_02_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_03_SHIFT},
	
	/* AON_GPIO and AON_SGPIO */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
	/*{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, 0, 0},*/
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_14_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_01_SHIFT}
};

