obj-y += cxcore_main.o
obj-y += cxcore_session.o
obj-y += cxcore_stream.o
obj-y += cxcore_emm.o
obj-y += cxcore_ecm.o
obj-y += cxcore_os.o
obj-y += cxcore_sc.o
obj-y += cxcore_ui.o
obj-y += cxcore_nvm.o
obj-$(CONFIG_MW_MM_PVR) += cxcore_pvr.o

obj-$(CONFIG_MW_CAS_CONAX_CPM) += cxcore_cpm.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
