/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_sid_dq.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 6/14/12 2:30p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Jun 13 16:39:03 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7429/rdb/b0/bchp_sid_dq.h $
 * 
 * Hydra_Software_Devel/1   6/14/12 2:30p pntruong
 * SW7429-185: Initial version.
 *
 ***************************************************************************/

#ifndef BCHP_SID_DQ_H__
#define BCHP_SID_DQ_H__

/***************************************************************************
 *SID_DQ
 ***************************************************************************/
#define BCHP_SID_DQ_RAM_START                    0x00440400 /* Start of DQ RAM */
#define BCHP_SID_DQ_RAM_END                      0x004404bc /* End of DQ RAM */

/***************************************************************************
 *RAM_START - Start of DQ RAM
 ***************************************************************************/
/* SID_DQ :: RAM_START :: DequantIndex0 [31:24] */
#define BCHP_SID_DQ_RAM_START_DequantIndex0_MASK                   0xff000000
#define BCHP_SID_DQ_RAM_START_DequantIndex0_SHIFT                  24

/* SID_DQ :: RAM_START :: DequantIndex1 [23:16] */
#define BCHP_SID_DQ_RAM_START_DequantIndex1_MASK                   0x00ff0000
#define BCHP_SID_DQ_RAM_START_DequantIndex1_SHIFT                  16

/* SID_DQ :: RAM_START :: DequantIndex2 [15:08] */
#define BCHP_SID_DQ_RAM_START_DequantIndex2_MASK                   0x0000ff00
#define BCHP_SID_DQ_RAM_START_DequantIndex2_SHIFT                  8

/* SID_DQ :: RAM_START :: DequantIndex3 [07:00] */
#define BCHP_SID_DQ_RAM_START_DequantIndex3_MASK                   0x000000ff
#define BCHP_SID_DQ_RAM_START_DequantIndex3_SHIFT                  0

/***************************************************************************
 *RAM_END - End of DQ RAM
 ***************************************************************************/
/* SID_DQ :: RAM_END :: DequantIndex0 [31:24] */
#define BCHP_SID_DQ_RAM_END_DequantIndex0_MASK                     0xff000000
#define BCHP_SID_DQ_RAM_END_DequantIndex0_SHIFT                    24

/* SID_DQ :: RAM_END :: DequantIndex1 [23:16] */
#define BCHP_SID_DQ_RAM_END_DequantIndex1_MASK                     0x00ff0000
#define BCHP_SID_DQ_RAM_END_DequantIndex1_SHIFT                    16

/* SID_DQ :: RAM_END :: DequantIndex2 [15:08] */
#define BCHP_SID_DQ_RAM_END_DequantIndex2_MASK                     0x0000ff00
#define BCHP_SID_DQ_RAM_END_DequantIndex2_SHIFT                    8

/* SID_DQ :: RAM_END :: DequantIndex3 [07:00] */
#define BCHP_SID_DQ_RAM_END_DequantIndex3_MASK                     0x000000ff
#define BCHP_SID_DQ_RAM_END_DequantIndex3_SHIFT                    0

#endif /* #ifndef BCHP_SID_DQ_H__ */

/* End of File */
