obj-y += rest_bind.o
obj-y += rest_bind_common.o
obj-y += rest_bind_channel.o
obj-y += rest_bind_channel_tunable.o
obj-y += rest_bind_player.o
obj-y += rest_bind_player_live.o
obj-y += rest_bind_epg.o
obj-y += rest_bind_schedule.o
obj-y += rest_bind_scan.o
obj-y += rest_bind_scan_channels.o
obj-y += rest_bind_record.o
obj-y += rest_bind_recorder.o
obj-y += rest_bind_sysenv.o
obj-y += rest_bind_settings.o
obj-y += rest_bind_pincode.o
obj-y += rest_bind_tuner.o

ccflags-y += -I$(NODEBINDER_SRC_DIR)/local_include

