obj-y += uapi.o
obj-y += uapi_rpcprotocol.o
obj-y += uapi_fm.o
obj-y += uapi_fs.o
obj-y += uapi_hotplug.o
obj-$(CONFIG_SUPPORT_UMMA_SAMBA_CLIENT) += uapi_smbc.o
obj-$(CONFIG_SUPPORT_UMMA_SAMBA_SERVER) += uapi_smbs.o
obj-$(CONFIG_SUPPORT_UMMA_FTP_SERVER) += uapi_ftps.o

# ---- include path----

