/********************************************************************
 * $Workfile  :   nvram_map.h  $
 * Project    :
 * Author     :
 * Description: Header file for nvram map
 *
 *                              Copyright (c) 2012 by HUMAX Co., Ltd.
 *                                               All rights reserved.
 ********************************************************************/

#ifndef _NVRAM_MAP_H_
#define _NVRAM_MAP_H_

/********************************************************************
 Header Files
 ********************************************************************/

/********************************************************************
 Constant/Macro Definition
 ********************************************************************/

/********************************************************************
 Structure and Type Definition
 ********************************************************************/
/* CAUTION! : String Size must be short if you can. */
/*            Because if string length is more larger, code size will be increased */
#define WLAN_MAC_ADDR	"WLAN_MAC_ADDR"
#define MAC2_ADDR		"MAC2_ADDR"
#define MAC3_ADDR		"MAC3_ADDR"
#define SIG_KERNEL		"SIG_KERNEL"	// kernel signature
#define SIG_ROOTFS		"SIG_ROOTFS"	// rootfs signature
#define SIG_UPGRADER	"SIG_UPGRADER"		/* upgrader (OTA loader) signature */
#define SIG_APP1		"SIG_APP1"		// kernel, rootfs외 extend partition #1 signature
#define SIG_APP2		"SIG_APP2"		// kernel, rootfs외 extend partition #2 signature
#define SIG_APP3		"SIG_APP3"		// kernel, rootfs외 extend partition #3 signature
#define CHK_SIG_APP1	"CHK_SIG_APP1"	// extend partition #1 signature check flag(NGS에서는 android area check용도)
#define SIGN_KEY		"SIGN_KEY"
#define OBSC_KEY		"OBSC_KEY"
#define EOTA_CHANNEL	"EMERGE_OTA_CHANNEL"
#define EOTA_RETRY		"EMERGE_OTA_RETRY"
#define BOOT_ERR		"BOOT_ERR"
#define UPGRADE_ERR		"UPGRADE_ERR"
#define SYS_UPATE_DATE	"SYSTEM_UPATE_DATE"
#define BTMAC_ADDR		"BTMAC_ADDR"
#define IRDETO_PRIVATEDATA		"IRDETO_PRIVATEDATA"
#define HDCP22_UNBOUNDED_KEY	"HDCP22_UNBOUNDED_KEY"		/* unbounded key. You must run ProvisioningTool */
#define HDCP22_KEY	"HDCP22_KEY"				/* provisioned & bounded key */
#define CPU_MAX_TEMP	"CPU_MAX_TEMP"				/* CPU Max temperature */
#define CM_MAX_TEMP	"CM_MAX_TEMP"				/* CM Max temperature */
#define OTA_DN_TYPE	"OTA_DN_TYPE"				/* OTA info between booloader and upgrader */
#define UG_PARTITION "UG_PARTITION"

#define SYSTEM_ID				"SYSTEM_ID"					// DI_NVRAM_FIELD_SYSTEM_ID | DRV_NVRAM_PARTITION_RO
#define HD_RESOULTION			"HD_RESOULTION"				// DI_NVRAM_FIELD_HD_RESOULTION	| DRV_NVRAM_PARTITION_RW
#define STR_720x240P	"720x240P"
#define STR_2880x240P	"2880x240P"
#define STR_640x480P	"640x480P"
#define STR_720x480I	"720x480I"
#define STR_720x480P	"720x480P"
#define STR_1440x480P	"1440x480P"
#define STR_2880x480I	"2880x480I"
#define STR_2880x480P	"2880x480P"
#define STR_720x288P	"720x288P"
#define STR_2880x288P	"2880x288P"
#define STR_720x576I	"720x576I"
#define STR_720x576P	"720x576P"
#define STR_1440x576P	"1440x576P"
#define STR_2880x576I	"2880x576I"
#define STR_2880x576P	"2880x576P"
#define STR_1080x720P	"1080x720P"
#define STR_1280x720P	"1280x720P"
#define STR_1920x1080I	"1920x1080I"
#define STR_1920x1080P	"1920x1080P"
#define STR_3840x2160P	"3840x2160P"

#define FIELD_RATE			"FIELD_RATE"				// DI_NVRAM_FIELD_FIELD_RATE | DRV_NVRAM_PARTITION_RW
#define STR_24HZ		"24HZ"
#define STR_25HZ		"25HZ"
#define STR_30HZ		"30HZ"
#define STR_50HZ		"50HZ"
#define STR_60HZ		"60HZ"
#define STR_100HZ		"100HZ"
#define STR_120HZ		"120HZ"
#define STR_200HZ		"200HZ"
#define STR_240HZ		"240HZ"

#define SFLASH					"SFLASH"					// DI_NVRAM_FIELD_SFLASH | DRV_NVRAM_PARTITION_RO
#define SFLASH_CRC				"SFLASH_CRC"				// DI_NVRAM_FIELD_SFLASH_CRC | DRV_NVRAM_PARTITION_RW
#define SFLASH_SIZE				"SFLASH_SIZE"				// DI_NVRAM_FIELD_SFLASH_SIZE | DRV_NVRAM_PARTITION_RW
#define SERIAL_NO				"SERIAL_NO"					// DI_NVRAM_FIELD_SERIAL_NO | DRV_NVRAM_PARTITION_RO
#define DTCP_KEY				"DTCP_KEY"					// DI_NVRAM_FIELD_DTCP_KEY | DRV_NVRAM_PARTITION_RO
#define CI_PLUS_KEY				"CI_PLUS_KEY"				// DI_NVRAM_FIELD_CI_PLUS_KEY | DRV_NVRAM_PARTITION_RO
#define MAC_ADDR				"MAC_ADDR"					// DI_NVRAM_FIELD_MAC_ADDR | DRV_NVRAM_PARTITION_RO
#define HDCP_KEY				"HDCP_KEY"					// DI_NVRAM_FIELD_HDCP_KEY | DRV_NVRAM_PARTITION_RO
#define PARING_DATA				"PARING_DATA"				// DI_NVRAM_FIELD_PARING_DATA | DRV_NVRAM_PARTITION_RO
#define CM_SERIAL_NO			"CM_SERIAL_NO"				// DI_NVRAM_FIELD_CM_SERIAL_NO | DRV_NVRAM_PARTITION_RO
#define CM_MAC_ADDR				"CM_MAC_ADDR"				// DI_NVRAM_FIELD_CM_MAC_ADDR | DRV_NVRAM_PARTITION_RO
#define CM_MAC_ADDR_ANOTHER		"CM_MAC_ADDR_ANOTHER"		// DI_NVRAM_FIELD_CM_MAC_ADDR_ANOTHER | DRV_NVRAM_PARTITION_RO
#define IRDETO_BBCB				"IRDETO_BBCB"				// DI_NVRAM_FIELD_IRDETO_BBCB | DRV_NVRAM_PARTITION_RO
#define IRDETO_CPCB				"IRDETO_CPCB"				// DI_NVRAM_FIELD_IRDETO_CPCB | DRV_NVRAM_PARTITION_RW
#define IRDETO_CPCB_ENCRYPTED	"IRDETO_CPCB_ENCRYPTED"		// DI_NVRAM_FIELD_IRDETO_CPCB_ENCRYPTED | DRV_NVRAM_PARTITION_RW
#define IRDETO_UC_SECURE_ID		"IRDETO_UC_SECURE_ID"		// DI_NVRAM_FIELD_IRDETO_UC_SECURE_ID | DRV_NVRAM_PARTITION_RO
#define IRDETO_UC_PRIVATE_DATA	"IRDETO_UC_PRIVATE_DATA"	// DI_NVRAM_FIELD_IRDETO_UC_PRIVATE_DATA | DRV_NVRAM_PARTITION_RO
#define IRDETO_CA_PARTITION		"IRDETO_CA_PARTITION"		// DI_NVRAM_FIELD_IRDETO_CA_PARTITION | DRV_NVRAM_PARTITION_RW
#define IRDETO_LOADER_PARTITION	"IRDETO_LOADER_PARTITION"	// DI_NVRAM_FIELD_IRDETO_LOADER_PARTITION | DRV_NVRAM_PARTITION_RW
#define IRDETO_IR_PARTITION		"IRDETO_IR_PARTITION"		// DI_NVRAM_FIELD_IRDETO_IR_PARTITION | DRV_NVRAM_PARTITION_RW
#define IR_BACKUP_PARTITION		"IR_BACKUP_PARTITION"		// DI_NVRAM_FIELD_IRDETO_IR_BACKUP_PARTITION | DRV_NVRAM_PARTITION_RW
#define PRIVATE					"PRAVATE"					// DI_NVRAM_FIELD_PRIVATE | DRV_NVRAM_PARTITION_RO
#define CSC_KEY					"CSC_KEY"					// DI_NVRAM_FIELD_CSC_KEY | DRV_NVRAM_PARTITION_RO
#define LANGUAGE				"LANGUAGE"					// DI_NVRAM_FIELD_LANGUAGE | DRV_NVRAM_PARTITION_RW
#define TV_STANDARD				"TV_STANDARD"				// DI_NVRAM_FIELD_TV_STANDARD | DRV_NVRAM_PARTITION_RW
#define SCART_RGB				"SCART_RGB"					// DI_NVRAM_FIELD_SCART_RGB | DRV_NVRAM_PARTITION_RW
#define SD_STANDARD				"SD_STANDARD"				// DI_NVRAM_FIELD_SD_STANDARD | DRV_NVRAM_PARTITION_RW
#define OTA_FLAG1				"OTA_FLAG1"					// DI_NVRAM_FIELD_OTA_FLAG1 | DRV_NVRAM_PARTITION_RW
#define OTA_FLAG2				"OTA_FLAG2"					// DI_NVRAM_FIELD_OTA_FLAG2 | DRV_NVRAM_PARTITION_RW
#define OTA_FLAG3				"OTA_FLAG3"					// DI_NVRAM_FIELD_OTA_FLAG3 | DRV_NVRAM_PARTITION_RW
#define OTA_TYPE1				"OTA_TYPE1"					// DI_NVRAM_FIELD_OTA_TYPE1 | DRV_NVRAM_PARTITION_RW
#define OTA_TYPE2				"OTA_TYPE2"					// DI_NVRAM_FIELD_OTA_TYPE2 | DRV_NVRAM_PARTITION_RW
#define OTA_TYPE3				"OTA_TYPE3"					// DI_NVRAM_FIELD_OTA_TYPE3 | DRV_NVRAM_PARTITION_RW
#define CH_TYPE1				"CH_TYPE1"					// DI_NVRAM_FIELD_CH_TYPE1 | DRV_NVRAM_PARTITION_RW
#define CH_TYPE2				"CH_TYPE2"					// DI_NVRAM_FIELD_CH_TYPE2 | DRV_NVRAM_PARTITION_RW
#define CH_TYPE3				"CH_TYPE3"					// DI_NVRAM_FIELD_CH_TYPE3 | DRV_NVRAM_PARTITION_RW
#define TUNER_ID1				"TUNER_ID1"					// DI_NVRAM_FIELD_TUNER_ID1 | DRV_NVRAM_PARTITION_RW
#define TUNER_ID2				"TUNER_ID2"					// DI_NVRAM_FIELD_TUNER_ID2 | DRV_NVRAM_PARTITION_RW
#define TUNER_ID3				"TUNER_ID3"					// DI_NVRAM_FIELD_TUNER_ID3 | DRV_NVRAM_PARTITION_RW
#define ANTENA_POWER1			"ANTENA_POWER1"				// DI_NVRAM_FIELD_ANTENA_POWER1 | DRV_NVRAM_PARTITION_RW
#define ANTENA_POWER2			"ANTENA_POWER2"				// DI_NVRAM_FIELD_ANTENA_POWER2 | DRV_NVRAM_PARTITION_RW
#define ANTENA_POWER3			"ANTENA_POWER3"				// DI_NVRAM_FIELD_ANTENA_POWER3 | DRV_NVRAM_PARTITION_RW
#define ES_PID1					"ES_PID1"					// DI_NVRAM_FIELD_ES_PID1 | DRV_NVRAM_PARTITION_RW
#define ES_PID2					"ES_PID2"					// DI_NVRAM_FIELD_ES_PID2 | DRV_NVRAM_PARTITION_RW
#define ES_PID3					"ES_PID3"					// DI_NVRAM_FIELD_ES_PID3 | DRV_NVRAM_PARTITION_RW
#define TRANSACTION_ID1			"TRANSACTION_ID1"			// DI_NVRAM_FIELD_TRANSACTION_ID1 | DRV_NVRAM_PARTITION_RW
#define TRANSACTION_ID2			"TRANSACTION_ID2"			// DI_NVRAM_FIELD_TRANSACTION_ID2 | DRV_NVRAM_PARTITION_RW
#define TRANSACTION_ID3			"TRANSACTION_ID3"			// DI_NVRAM_FIELD_TRANSACTION_ID3 | DRV_NVRAM_PARTITION_RW
#define APP_VERSION				"APP_VERSION"				// DI_NVRAM_FIELD_APP_VERSION | DRV_NVRAM_PARTITION_RW
#define OTALDR_VERSION			"OTALDR_VERSION"			// DI_NVRAM_FIELD_OTALDR_VERSION | DRV_NVRAM_PARTITION_RW
#define OAD_VERSION				"OAD_VERSION"				// DI_NVRAM_FIELD_OAD_VERSION | DRV_NVRAM_PARTITION_RW
#define NET_IP_CONFIG			"NET_IP_CONFIG"				// DI_NVRAM_FIELD_NET_IP_CONFIG | DRV_NVRAM_PARTITION_RW
#define NET_IP_SETTING			"NET_IP_SETTING"			// DI_NVRAM_FIELD_NET_IP_SETTING | DRV_NVRAM_PARTITION_RW
#define RCU_CUSTOM_CODE			"RCU_CUSTOM_CODE"			// DI_NVRAM_FIELD_RCU_CUSTOM_CODE | DRV_NVRAM_PARTITION_RW
#define RCU_CUSTOM_CODE2		"RCU_CUSTOM_CODE2"			// DI_NVRAM_FIELD_RCU_CUSTOM_CODE2 | DRV_NVRAM_PARTITION_RW
#define PANEL_DISPLAY			"PANEL_DISPLAY"				// DI_NVRAM_FIELD_PANEL_DISPLAY | DRV_NVRAM_PARTITION_RW
#define PANEL_DIMMING			"PANEL_DIMMING"				// DI_NVRAM_FIELD_PANEL_DIMMING | DRV_NVRAM_PARTITION_RW
#define ASPECT_RATIO			"ASPECT_RATIO"				// DI_NVRAM_FIELD_ASPECT_RATIO | DRV_NVRAM_PARTITION_RW
#define COUNTRY_CODE			"COUNTRY_CODE"				// DI_NVRAM_FIELD_COUNTRY_CODE | DRV_NVRAM_PARTITION_RW
#define USAGE_ID				"USAGE_ID"					// DI_NVRAM_FIELD_USAGE_ID | DRV_NVRAM_PARTITION_RW
#define CH_INFO_S				"CH_INFO_S"					// DI_NVRAM_FIELD_CH_INFO_S | DRV_NVRAM_PARTITION_RW
#define CH_INFO_T				"CH_INFO_T"					// DI_NVRAM_FIELD_CH_INFO_T | DRV_NVRAM_PARTITION_RW
#define CH_INFO_C				"CH_INFO_C"					// DI_NVRAM_FIELD_CH_INFO_C | DRV_NVRAM_PARTITION_RW
#define OTA_FTP_INFO			"FTP_OTA_INFO"				// DI_NVRAM_FIELD_OTA_FTP_INFO | DRV_NVRAM_PARTITION_RW
#define NET_PORTAL_IP			"NET_PORTAL_IP"				// DI_NVRAM_FIELD_NET_PORTAL_IP | DRV_NVRAM_PARTITION_RW
#define NET_DOWN_PATH			"NET_DOWN_PATH"				// DI_NVRAM_FIELD_NET_DOWN_PATH | DRV_NVRAM_PARTITION_RW
#define LOADER_VERSION			"LOADER_VERSION"			// DI_NVRAM_FIELD_LOADER_VERSION | DRV_NVRAM_PARTITION_RW
#define OSD_DISPLAY				"OSD_DISPLAY"				// DI_NVRAM_FIELD_OSD_DISPLAY | DRV_NVRAM_PARTITION_RW
#define BIN8K					"BIN8K"						// DI_NVRAM_FIELD_BIN8K | DRV_NVRAM_PARTITION_RW
#define DISPLAY_FACTORY_INFO	"DISPLAY_FACTORY_INFO"		// DI_NVRAM_FIELD_DISPLAY_FACTORY_INFO | DRV_NVRAM_PARTITION_RW
#define RAWFS					"RAWFS"						// DI_NVRAM_FIELD_RAWFS | DRV_NVRAM_PARTITION_W_RAWFS
#define FACLDR_VERSION			"FACLDR_VERSION"			// DI_NVRAM_FIELD_FACLDR_VERSION | DRV_NVRAM_PARTITION_RW
#define APP_VERSION_NEXT		"APP_VERSION_NEXT"			// DI_NVRAM_FIELD_APP_VERSION_NEXT | DRV_NVRAM_PARTITION_RW
#define LOADER_VERSION_NEXT		"LOADER_VERSION_NEXT"		// DI_NVRAM_FIELD_LOADER_VERSION_NEXT | DRV_NVRAM_PARTITION_RW
#define OTALDR_VERSION_NEXT		"OTALDR_VERSION_NEXT"		// DI_NVRAM_FIELD_OTALDR_VERSION_NEXT | DRV_NVRAM_PARTITION_RW
#define FACTORY_GANG_WRITED		"FACTORY_GANG_WRITED"		// DI_NVRAM_FIELD_FACTORY_GANG_WRITED | DRV_NVRAM_PARTITION_RW
#define FACTORY_MODE_BOOT		"FACTORY_MODE_BOOT"			// RW
#define KERNEL_SIZE				"KERNEL_SIZE"				// DI_NVRAM_FIELD_KERNEL_SIZE | DRV_NVRAM_PARTITION_RW
#define KERNEL_CRC				"KERNEL_CRC"				// DI_NVRAM_FIELD_KERNEL_CRC | DRV_NVRAM_PARTITION_RW
#define ROOTFS_SIZE				"ROOTFS_SIZE"				// DI_NVRAM_FIELD_ROOTFS_SIZE | DRV_NVRAM_PARTITION_RW
#define ROOTFS_CRC				"ROOTFS_CRC"				// DI_NVRAM_FIELD_ROOTFS_CRC | DRV_NVRAM_PARTITION_RW
#define GANG_CRC				"GANG_CRC"					// DI_NVRAM_FIELD_GANG_CRC | DRV_NVRAM_PARTITION_RW
#define DSTB_ID					"DSTB_ID"					// DI_NVRAM_FIELD_DSTB_ID | DRV_NVRAM_PARTITION_RW
#define VA_EXTRA_DATA			"VA_EXTRA_DATA"				// DI_NVRAM_FIELD_VA_EXTRA_DATA | DRV_NVRAM_PARTITION_RW
#define NETFLIX_ESN				"NETFLIX_ESN"				// DI_NVRAM_FIELD_NETFLIX_ESN | DRV_NVRAM_PARTITION_RW
#define DIAG_APP				"DIAG_APP"					// DI_NVRAM_FIELD_DIAG_APP | DRV_NVRAM_PARTITION_RW
#define HDMI_PRIORITY			"HDMI_PRIORITY"				// DI_NVRAM_FIELD_DIAG_APP | DRV_NVRAM_PARTITION_RW
#define PKG_VERSION				"PKG_VERSION"				// OTA Image Version
#endif /* _NVRAM_MAP_H_ */





