#include "nexus_platform.h"
/*#include "nexus_gpio_module.h"*/
#include "bchp_sun_top_ctrl.h"
#include "bchp_aon_pin_ctrl.h"

#include "humax_pinmux.h"

/*
	g_humaxGpioTable[] 와 순서가 일치해야 함.
*/
const char g_humaxGpioFunctionTable[HUMAX_NUM_GPIO_PINS] = {
	/*///////////// GPIO 0 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 000 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 001 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 002 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 003 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 004 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 005 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 006 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 007 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 008 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 009 */ /* // */

	/*///////////// GPIO 10 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 010 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 011 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 012 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 013 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 014 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 015 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 016 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 017 */ /* // */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 018 */ /* /EBI_CS0B/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 019 */ /* // */

	/*///////////// GPIO 20 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 020 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 021 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 022 */ /* // */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 023 */ /* /DS_AGC_CTL/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 024 */ /* // */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 025 */ /* /EBI_DATA0/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 026 */ /* /EBI_DATA1/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 027 */ /* /EBI_DATA2/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 028 */ /* /EBI_DATA3/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 029 */ /* /EBI_DATA4/ */

	/*///////////// GPIO 30 ///////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 030 */ /* /EBI_DATA5/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 031 */ /* /EBI_DATA6/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 032 */ /* /EBI_DATA7/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 033 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 034 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 035 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 036 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 037 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 038 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 039 */ /* // */

	/*///////////// GPIO 40 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 040 */ /* // */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 041 */ /* /EBI_RDB/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 042 */ /* /EBI_WE0B/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 043 */ /* /EBI_DSB/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 044 */ /* /EBI_TSB/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 045 */ /* /NAND_RBB/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 046 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 047 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 048 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 049 */ /* // */

	/*///////////// GPIO 50 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 050 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 051 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 052 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 053 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 054 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 055 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 056 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 057 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 058 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 059 */ /* // */

	/*///////////// GPIO 60 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 060 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 061 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 062 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 063 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 064 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 065 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 066 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 067 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 068 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 069 */ /* // */

	/*///////////// GPIO 70 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 070 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 071 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 072 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 073 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 074 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 075 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 076 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 077 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 078 */ /* // */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 079 */ /* /SC0_VCC/ */
	
	/*///////////// GPIO 80 ///////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 080 */ /* /SC0_CLK/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 081 */ /* /SC0_RST/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 082 */ /* /SC0_IO/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 083 */ /* /SC0_PRES/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 084 */ /* /SC0_AUX1/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 085 */ /* /SC0_AUX2/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 086 */ /* /SC0_VPP/ */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 087 */ /* /UART_TX0/ */
	HUMAX_GPIO_FUNCTION_ALT2,	/* GPIO 088 */ /* /UART_RX0/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 089 */ /* // */

	/*///////////// GPIO 90 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 090 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 091 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 092 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 093 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 094 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 095 */ /* /gpio 95 is not exist/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 096 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 097 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 098 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 099 */ /* // */
	
	/*///////////// GPIO 100 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 100 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 101 */ /* /USB0_PWRON_1, Not Used/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 102 */ /* /USB0_PWRON_2/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 103 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 104 */ /* // */
	HUMAX_GPIO_FUNCTION_ALT1,	/* GPIO 105 */ /* /ENET_ACTIVITY/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 106 */ /* /gpio 106 is not exist/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 107 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 108 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 109 */ /* // */

	/*///////////// GPIO 110 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 110 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 111 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 112 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 113 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 114 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 115 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 116 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 117 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 118 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 119 */ /* // */

	/*///////////// GPIO 120 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 120 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 121 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 122 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 123 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* GPIO 124 */ /* // */

	/*///////////// SGPIO 0 ///////////////*/
	HUMAX_GPIO_FUNCTION_ALT2,	/* SGPIO 000 */ /* /HDMI_TX_BSC_SCL/ */
	HUMAX_GPIO_FUNCTION_ALT2,	/* SGPIO 001 */ /* /HDMI_TX_BSC_SDA/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* SGPIO 002 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* SGPIO 003 */ /* // */

	/*///////////// AON GPIO 0 ///////////////*/
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_GPIO 000 */ /* /AUD_SPDIF/ */
	HUMAX_GPIO_FUNCTION_ALT1,	/* AON_GPIO 001 */ /* /ENET_LINK/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 002 */ /* /aon_gpio_02 is not exist/ */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 003 */ /* /GPIO-PWR_SW/ */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 004 */ /* /GPIO-LED_GREEN/ */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 005 */ /* /GPIO-LED_RED/ */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 006 */ /* /GPIO-AUD_ENABLE/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 007 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 008 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 009 */ /* // */

	/*///////////// AON GPIO 10 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 010 */ /* // */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 011 */ /* // */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 012 */ /* /GPIO-HW_BIT2/ */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 013 */ /* /GPIO-HW_BIT1/ */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 014 */ /* /GPIO-HW_BIT0/ */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 015 */ /* /GPIO-SCART_RB_0/ */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 016 */ /* /GPIO-SCART_RB_1/ */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 017 */ /* /GPIO-SCART_FB/ */
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 018 */ /* // */
	HUMAX_GPIO_FUNCTION_GPIO,	/* AON_GPIO 019 */ /* /GPIO-SCART_EN/ */

	/*///////////// AON GPIO 20 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_GPIO 020 */ /* // */
	
	/*///////////// AON SGPIO 0 ///////////////*/
	HUMAX_GPIO_FUNCTION_NCTP,	/* AON_SGPIO 000 */ /* /USB0_PWRFLT_1, Not Used/ */
	HUMAX_GPIO_FUNCTION_ALT2	/* AON_SGPIO 001 */ /* /USB0_PWRFLT_2/ */
};

/*
	g_humaxGpioFunctionTable[] 와 순서가 일치해야 함.
	gpio 번호 순서대로 나열해야 함.
	platform 에서 지원하지 않는 gpio 의 경우 dummy table 을 만들도록 함 (순서 유지를 위해..)
*/
HUMAX_GpioTable g_humaxGpioTable[HUMAX_NUM_GPIO_PINS] = {
	/* gpio */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_00_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_00_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_01_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_01_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_02_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_03_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_04_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_04_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_05_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_05_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_06_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_06_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_07_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_07_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_08_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_08_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_09_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_09_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_10_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_gpio_10_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_11_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_11_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_12_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_12_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_13_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_13_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_14_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_14_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_15_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_15_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_16_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_16_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_17_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_17_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_18_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_18_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_19_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_19_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_20_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_20_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_21_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_21_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_22_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_22_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_23_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_23_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_24_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_gpio_24_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_25_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_25_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_26_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_26_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_27_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_27_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_28_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_28_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_29_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_29_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_30_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_30_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_31_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_31_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_32_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_32_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_33_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_33_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_34_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_34_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_35_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_35_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_36_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_36_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_37_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_37_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_38_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_38_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_39_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_39_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_40_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_40_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_41_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_41_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_42_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_42_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_43_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_43_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_44_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_44_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_45_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_45_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_46_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_46_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_47_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_47_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_48_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_48_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_49_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_49_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_50_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_50_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_51_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_51_SHIFT},	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_52_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_52_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_53_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_53_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_54_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_54_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_55_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_55_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_56_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_56_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_57_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_57_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_58_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_58_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_59_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_59_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_60_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_60_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_61_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_61_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_62_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_62_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_63_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_63_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_64_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_64_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_65_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_65_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_66_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_66_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_67_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_67_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_68_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_68_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_69_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_69_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_70_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_70_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_71_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_72_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_72_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_73_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_73_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_74_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_74_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_75_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_75_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_76_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_76_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_77_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_77_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_78_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_78_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_79_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_79_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_80_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_80_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_81_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_81_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_82_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_82_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_83_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_83_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_84_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_84_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_85_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_85_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_86_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_86_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_87_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_87_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_88_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_88_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_89_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_89_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_90_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_90_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_91_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_91_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_92_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_92_SHIFT},
	
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_93_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_93_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_94_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_94_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, 0x00000000, 0}, /* GPIO 095 is not exist */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_96_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_96_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_97_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_97_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_98_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_98_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_99_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_99_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_100_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_100_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_101_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_101_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_102_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_102_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_103_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_103_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_104_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_104_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_105_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_105_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, 0x00000000, 0}, /* GPIO 106 is not exist */
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_107_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_107_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_108_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_108_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_109_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_109_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_110_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_110_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_111_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_111_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_112_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_112_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_113_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_113_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_114_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_114_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_115_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_115_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_116_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_116_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_117_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_117_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_118_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_14_gpio_118_SHIFT},

	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_119_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_119_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_120_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_120_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_121_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_121_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_122_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_122_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_123_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_123_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_124_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_gpio_124_SHIFT},

	/* sgpio */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_sgpio_01_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_02_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_02_SHIFT},
	{BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_03_MASK, BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_15_sgpio_03_SHIFT},

	/* aon_gpio */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_00_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_01_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, 0x00000000, 0}, /* aon_gpio_02 is not exist */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_03_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_04_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_0_aon_gpio_05_SHIFT},
	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_06_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_07_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_08_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_09_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_10_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_11_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_12_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_1_aon_gpio_13_SHIFT},

	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_14_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_14_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_15_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_16_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_17_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_18_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_19_SHIFT},
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_gpio_20_SHIFT},

	/* aon_sgpio */
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_2_aon_sgpio_00_SHIFT},	
	{BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_01_MASK, BCHP_AON_PIN_CTRL_PIN_MUX_CTRL_3_aon_sgpio_01_SHIFT}	
};

