-include ./dirs

ifeq ($(DIRS),)
TARGET = secureclockstub

SOURCES =                \
	secureclockutilstub.c secureclockrequeststub.c secureclockresponsestub.c secureclockmanagerstub.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
