obj-y += vd_api.o
obj-y += vd_dmx.o
obj-y += vd_dsc.o
obj-y += vd_extstorage.o
obj-y += vd_loader.o
obj-y += vd_macrovision.o
obj-y += vd_sc.o
obj-y += vd_storage.o
obj-y += vd_streamcrypto.o
obj-y += vd_timer.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
