# Octo Models
obj-$(CONFIG_PROD_HMS1000S) += xdb_param_default_hms1000s.o
obj-$(CONFIG_PROD_HMSLITE) += xdb_param_default_hms1000s.o
obj-$(CONFIG_PROD_IR4000HD) += xdb_param_default_ir4000hd.o
obj-$(CONFIG_PROD_ICORDPRO) += xdb_param_default_icordpro.o
obj-$(CONFIG_PROD_HDNEO) += xdb_param_default_hdneo.o
obj-$(CONFIG_PROD_HMS1000T) += xdb_param_default_hms1000t.o
obj-$(CONFIG_PROD_HD9000I) += xdb_param_default_hd9000i.o
obj-$(CONFIG_PROD_IHDR6100C) += xdb_param_default_ihdr6100c.o
obj-$(CONFIG_PROD_FVP4000T) += xdb_param_default_fvp4000t.o
obj-$(CONFIG_PROD_HMX4KBBC) += xdb_param_default_hmx4kbbc.o
obj-$(CONFIG_PROD_DIGIMAXT2) += xdb_param_default_digimaxt2.o
obj-$(CONFIG_PROD_HDFOXIRCONNECT) += xdb_param_default_hdfoxirconnect.o
obj-$(CONFIG_PROD_YSR2000) += xdb_param_default_ysr2000.o
obj-$(CONFIG_PROD_YS1000) += xdb_param_default_ys1000.o
obj-$(CONFIG_PROD_CDIG2000C) += xdb_param_default_cdig2000c.o
obj-$(CONFIG_PROD_ROCKYPOM) += xdb_param_default_rockypom.o
obj-$(CONFIG_PROD_ROCKYWPOM) += xdb_param_default_rockypom.o
obj-$(CONFIG_PROD_HGS1000S) += xdb_param_default_hgs1000s.o
obj-$(CONFIG_PROD_HA7100S) += xdb_param_default_ha7100s.o
obj-$(CONFIG_PROD_M1) += xdb_param_default_m1.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xdb

# Additional include path
ccflags-y += -I$(OCTO_DB_DIR)/param/local_include

