
obj-$(CONFIG_SUPPORT_NIMA) += nima.o
obj-$(CONFIG_SUPPORT_NIMA) += nima_util.o
obj-$(CONFIG_SUPPORT_NIMA) += nima_command_procedure.o
obj-$(CONFIG_SUPPORT_NIMA) += nima_scenario.o
obj-$(CONFIG_SUPPORT_NIMA) += nima_db.o
obj-$(CONFIG_SUPPORT_NIMA) += nima_conv.o
obj-$(CONFIG_SUPPORT_NIMA) += nima_server.o
obj-$(CONFIG_SUPPORT_NIMA) += nima_session.o
obj-$(CONFIG_SUPPORT_NIMA) += nima_debug.o
