obj-y						+= base/
obj-$(CONFIG_OP_FREESAT)	+= freesat/
obj-$(CONFIG_OP_MIDDLE_EAST)+= mesat/
obj-y += pmgr_setting.o
obj-y += xmgr_setting.o

# Basic include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmgr
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xmodule


