
obj-$(CONFIG_SUPPORT_UMMA_FTP_SERVER) += umma_ftps.o

# Additional include path
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/ftps/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fm/include
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fs
ccflags-y += -I$(OCTOSVC_SRC_DIR)/umma/main/module/fs/pal/include
