-include ./dirs

ifeq ($(DIRS),)
TARGET = wmdrmnetreal

SOURCES =                \
	drmndcertbuilder.c drmnddevicecert.c drmxmlrsakeys.c wmdrmnetimplreal.c wmdrmnetutilreal.c 
	
endif
   
include $(DRM_SOURCE_PATH)/default.mak
