obj-y += pal_panel.o
obj-$(CONFIG_DEBUG) += pal_panel_cmd.o

obj-$(CONFIG_MW_SYS_VFD)		+= pal_panel_vfd.o
obj-$(CONFIG_MW_SYS_LCD)		+= pal_panel_lcd.o
obj-$(CONFIG_MW_SYS_7SEG)		+= pal_panel_7seg.o

# Basic include path
include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.pal
# Additional include path

