#
obj-y := src/
obj-y += drv_channel_cxd2820.o

# Additional include path
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/ds2820/include
inccflag-y += -I$(HUMAX_DRIVER_DIR)/di/channel/ter/ds2820/src/i2c/i2c_feusb
