obj-y += ca_scr.o
obj-$(CONFIG_MW_CAS_NAGRA_OP_SES) += ca_scr_ext.o

# MW include path
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xsvc
include $(OCTO_PLUGIN_INCLUDE_DIR)/Makefile.include.xcas

# Additional include path
