obj-y += oapi_cas_nagra.o
obj-y += oapi_cas_irdeto.o
obj-y += oapi_cas_verimatrix.o
obj-y += oapi_cas_mmi.o
obj-y += oapi_cas_ci.o
obj-y += oapi_cas_action.o

# Basic include path
#include $(OCTO_MAIN_INCLUDE_DIR)/Makefile.include.oapimgr

# ---- include path----
ccflags-y += -I$(HLIB_DIR)/include
ccflags-y += -I$(DLIB_DIR)/include
ccflags-y += -I$(OCTO_DIR)/include
ccflags-y += -I$(OCTO_DIR)/api/protocol
ccflags-y += -I$(OCTO_DIR)/main/oxserver/include


